/**
 * bodyContent — „Žmogaus kūnas” trivijos klausimai (EN + LT).
 *
 * Po 15 klausimų kiekvienam lygiui (lengvas/vidutinis/sunkus/ekstremalus) = 60.
 * Temos: organai, skeletas, kraujas, jutimai, ląstelės — grynas patikrintas
 * anatomijos ir fiziologijos mokslas.
 *
 * TAISYKLĖS (Manifestas):
 *   - 1 teisingas + 5 distractors; visi 6 variantai VISOSE kalbose ≤46 simbolių;
 *   - faktai 100% patikrinti (sourceVerified); neutralu (jokios politikos/religijos);
 *   - LT vidinės kabutės tik „...” (ne ASCII "); detalės — į explanation, ne į variantą.
 *
 * Formatas — žr. triviaTypes.ts (TriviaQuestion). category visada "body".
 */

import { TriviaQuestion } from "./triviaTypes";

export const BODY_QUESTIONS: TriviaQuestion[] = [
  // ======================= LENGVAS (Easy) =======================
  {
    id: "bod_le_001",
    category: "body",
    subTheme: "organs",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Anatomy (heart pumps blood)",
    emoji: "❤️",
    translations: {
      en: {
        question: "Which organ pumps blood around the body?",
        correct: "Heart",
        distractors: ["Liver", "Lungs", "Kidney", "Stomach", "Brain"],
        explanation: "The heart pumps blood through the body.",
      },
      lt: {
        question: "Kuris organas pumpuoja kraują po kūną?",
        correct: "Širdis",
        distractors: ["Kepenys", "Plaučiai", "Inkstas", "Skrandis", "Smegenys"],
        explanation: "Širdis pumpuoja kraują po visą kūną.",
      },
    },
  },
  {
    id: "bod_le_002",
    category: "body",
    subTheme: "organs",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Anatomy (lungs for breathing)",
    emoji: "🫁",
    translations: {
      en: {
        question: "Which organs do you use to breathe?",
        correct: "Lungs",
        distractors: ["Heart", "Liver", "Kidneys", "Stomach", "Bladder"],
        explanation: "The lungs take in air so we can breathe.",
      },
      lt: {
        question: "Kuriais organais kvėpuojame?",
        correct: "Plaučiais",
        distractors: ["Širdimi", "Kepenimis", "Inkstais", "Skrandžiu", "Šlapimo pūsle"],
        explanation: "Plaučiai įkvepia orą, kad galėtume kvėpuoti.",
      },
    },
  },
  {
    id: "bod_le_003",
    category: "body",
    subTheme: "senses",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Senses (eyes for sight)",
    emoji: "👁️",
    translations: {
      en: {
        question: "Which body part do you use to see?",
        correct: "Eyes",
        distractors: ["Ears", "Nose", "Tongue", "Hands", "Feet"],
        explanation: "We see the world through our eyes.",
      },
      lt: {
        question: "Kuria kūno dalimi matome?",
        correct: "Akimis",
        distractors: ["Ausimis", "Nosimi", "Liežuviu", "Rankomis", "Kojomis"],
        explanation: "Pasaulį matome akimis.",
      },
    },
  },
  {
    id: "bod_le_004",
    category: "body",
    subTheme: "skeleton",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Anatomy (skull protects brain)",
    emoji: "💀",
    translations: {
      en: {
        question: "Which bones protect the brain?",
        correct: "Skull",
        distractors: ["Ribs", "Spine", "Hip", "Jaw only", "Knee"],
        explanation: "The skull is a bony case protecting the brain.",
      },
      lt: {
        question: "Kurie kaulai saugo smegenis?",
        correct: "Kaukolė",
        distractors: ["Šonkauliai", "Stuburas", "Klubas", "Tik žandikaulis", "Kelis"],
        explanation: "Kaukolė — kaulinis dangtis, saugantis smegenis.",
      },
    },
  },
  {
    id: "bod_le_005",
    category: "body",
    subTheme: "senses",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Senses (ears for hearing)",
    emoji: "👂",
    translations: {
      en: {
        question: "Which body part do you use to hear?",
        correct: "Ears",
        distractors: ["Eyes", "Nose", "Mouth", "Hands", "Skin"],
        explanation: "We hear sounds with our ears.",
      },
      lt: {
        question: "Kuria kūno dalimi girdime?",
        correct: "Ausimis",
        distractors: ["Akimis", "Nosimi", "Burna", "Rankomis", "Oda"],
        explanation: "Garsus girdime ausimis.",
      },
    },
  },
  {
    id: "bod_le_006",
    category: "body",
    subTheme: "anatomy",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Anatomy (teeth for chewing)",
    emoji: "🦷",
    translations: {
      en: {
        question: "What do we use to chew food?",
        correct: "Teeth",
        distractors: ["Nails", "Lips", "Ears", "Hair", "Eyebrows"],
        explanation: "Teeth break food into smaller pieces.",
      },
      lt: {
        question: "Kuo kramtome maistą?",
        correct: "Dantimis",
        distractors: ["Nagais", "Lūpomis", "Ausimis", "Plaukais", "Antakiais"],
        explanation: "Dantys susmulkina maistą į mažesnius gabalėlius.",
      },
    },
  },
  {
    id: "bod_le_007",
    category: "body",
    subTheme: "anatomy",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Anatomy (largest organ is skin)",
    emoji: "🖐️",
    translations: {
      en: {
        question: "What is the body's largest organ?",
        correct: "Skin",
        distractors: ["Liver", "Heart", "Brain", "Lungs", "Stomach"],
        explanation: "Skin is the largest organ of the body.",
      },
      lt: {
        question: "Koks didžiausias kūno organas?",
        correct: "Oda",
        distractors: ["Kepenys", "Širdis", "Smegenys", "Plaučiai", "Skrandis"],
        explanation: "Oda — didžiausias kūno organas.",
      },
    },
  },
  {
    id: "bod_le_008",
    category: "body",
    subTheme: "anatomy",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Anatomy (blood is red)",
    emoji: "🩸",
    translations: {
      en: {
        question: "What color is human blood?",
        correct: "Red",
        distractors: ["Blue", "Green", "Yellow", "Purple", "Clear"],
        explanation: "Human blood is red due to hemoglobin.",
      },
      lt: {
        question: "Kokios spalvos yra žmogaus kraujas?",
        correct: "Raudonas",
        distractors: ["Mėlynas", "Žalias", "Geltonas", "Violetinis", "Skaidrus"],
        explanation: "Žmogaus kraujas raudonas dėl hemoglobino.",
      },
    },
  },
  {
    id: "bod_le_009",
    category: "body",
    subTheme: "anatomy",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Anatomy (fingers count, 5 per hand)",
    emoji: "✋",
    translations: {
      en: {
        question: "How many fingers are on one human hand?",
        correct: "5",
        distractors: ["4", "6", "3", "7", "10"],
        explanation: "One hand has five fingers, including the thumb.",
      },
      lt: {
        question: "Kiek pirštų yra ant vienos žmogaus rankos?",
        correct: "5",
        distractors: ["4", "6", "3", "7", "10"],
        explanation: "Ant vienos rankos penki pirštai su nykščiu.",
      },
    },
  },
  {
    id: "bod_le_010",
    category: "body",
    subTheme: "senses",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Senses (nose for smell)",
    emoji: "👃",
    translations: {
      en: {
        question: "Which body part do you use to smell?",
        correct: "Nose",
        distractors: ["Eyes", "Ears", "Hands", "Knees", "Elbows"],
        explanation: "We smell scents with our nose.",
      },
      lt: {
        question: "Kuria kūno dalimi užuodžiame kvapus?",
        correct: "Nosimi",
        distractors: ["Akimis", "Ausimis", "Rankomis", "Keliais", "Alkūnėmis"],
        explanation: "Kvapus užuodžiame nosimi.",
      },
    },
  },
  {
    id: "bod_le_011",
    category: "body",
    subTheme: "organs",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Anatomy (brain controls body)",
    emoji: "🧠",
    translations: {
      en: {
        question: "Which organ controls thinking and the body?",
        correct: "Brain",
        distractors: ["Heart", "Liver", "Lungs", "Stomach", "Kidney"],
        explanation: "The brain controls thoughts and body functions.",
      },
      lt: {
        question: "Kuris organas valdo mąstymą ir kūną?",
        correct: "Smegenys",
        distractors: ["Širdis", "Kepenys", "Plaučiai", "Skrandis", "Inkstas"],
        explanation: "Smegenys valdo mintis ir kūno funkcijas.",
      },
    },
  },
  {
    id: "bod_le_012",
    category: "body",
    subTheme: "senses",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Senses (tongue for taste)",
    emoji: "👅",
    translations: {
      en: {
        question: "Which body part lets you taste food?",
        correct: "Tongue",
        distractors: ["Nose", "Ear", "Eye", "Finger", "Cheek"],
        explanation: "Taste buds on the tongue sense flavors.",
      },
      lt: {
        question: "Kuria kūno dalimi jaučiame maisto skonį?",
        correct: "Liežuviu",
        distractors: ["Nosimi", "Ausimi", "Akimi", "Pirštu", "Skruostu"],
        explanation: "Skonio receptoriai liežuvyje jaučia skonius.",
      },
    },
  },
  {
    id: "bod_le_013",
    category: "body",
    subTheme: "skeleton",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Anatomy (bones make skeleton)",
    emoji: "🦴",
    translations: {
      en: {
        question: "What is the framework of bones in the body called?",
        correct: "Skeleton",
        distractors: ["Muscle", "Nerve", "Vessel", "Tendon", "Gland"],
        explanation: "All the bones together form the skeleton.",
      },
      lt: {
        question: "Kaip vadinamas kūno kaulų karkasas?",
        correct: "Skeletas",
        distractors: ["Raumuo", "Nervas", "Kraujagyslė", "Sausgyslė", "Liauka"],
        explanation: "Visi kaulai kartu sudaro skeletą.",
      },
    },
  },
  {
    id: "bod_le_014",
    category: "body",
    subTheme: "anatomy",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Anatomy (muscles move body)",
    emoji: "💪",
    translations: {
      en: {
        question: "What lets your body move and lift things?",
        correct: "Muscles",
        distractors: ["Bones only", "Skin", "Hair", "Nails", "Blood"],
        explanation: "Muscles contract to move the body.",
      },
      lt: {
        question: "Kas leidžia kūnui judėti ir kelti daiktus?",
        correct: "Raumenys",
        distractors: ["Tik kaulai", "Oda", "Plaukai", "Nagai", "Kraujas"],
        explanation: "Raumenys susitraukdami judina kūną.",
      },
    },
  },
  {
    id: "bod_le_015",
    category: "body",
    subTheme: "anatomy",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Anatomy (hair grows on head)",
    emoji: "💇",
    translations: {
      en: {
        question: "Where does hair grow most on people?",
        correct: "Head",
        distractors: ["Palms", "Soles", "Tongue", "Teeth", "Eyeballs"],
        explanation: "Hair grows thickest on the head.",
      },
      lt: {
        question: "Kur žmonėms auga daugiausia plaukų?",
        correct: "Ant galvos",
        distractors: ["Delnuose", "Paduose", "Ant liežuvio", "Ant dantų", "Ant akių"],
        explanation: "Tankiausiai plaukai auga ant galvos.",
      },
    },
  },

  // ======================= VIDUTINIS (Medium) =======================
  {
    id: "bod_me_001",
    category: "body",
    subTheme: "skeleton",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (206 bones in adult)",
    emoji: "🦴",
    translations: {
      en: {
        question: "About how many bones are in an adult human body?",
        correct: "206",
        distractors: ["106", "150", "300", "250", "180"],
        explanation: "An adult human has about 206 bones.",
      },
      lt: {
        question: "Maždaug kiek kaulų yra suaugusio žmogaus kūne?",
        correct: "206",
        distractors: ["106", "150", "300", "250", "180"],
        explanation: "Suaugęs žmogus turi maždaug 206 kaulus.",
      },
    },
  },
  {
    id: "bod_me_002",
    category: "body",
    subTheme: "organs",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (kidneys filter blood)",
    emoji: "🫘",
    translations: {
      en: {
        question: "Which organs filter waste from the blood?",
        correct: "Kidneys",
        distractors: ["Lungs", "Heart", "Brain", "Spleen", "Pancreas"],
        explanation: "Kidneys filter waste and make urine.",
      },
      lt: {
        question: "Kurie organai filtruoja atliekas iš kraujo?",
        correct: "Inkstai",
        distractors: ["Plaučiai", "Širdis", "Smegenys", "Blužnis", "Kasa"],
        explanation: "Inkstai filtruoja atliekas ir gamina šlapimą.",
      },
    },
  },
  {
    id: "bod_me_003",
    category: "body",
    subTheme: "anatomy",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (red cells carry oxygen)",
    emoji: "🩸",
    translations: {
      en: {
        question: "Which blood cells carry oxygen?",
        correct: "Red blood cells",
        distractors: ["White blood cells", "Platelets", "Nerve cells", "Skin cells", "Fat cells"],
        explanation: "Red blood cells carry oxygen with hemoglobin.",
      },
      lt: {
        question: "Kurios kraujo ląstelės neša deguonį?",
        correct: "Raudonieji kraujo kūneliai",
        distractors: ["Baltieji kūneliai", "Trombocitai", "Nervų ląstelės", "Odos ląstelės", "Riebalų ląstelės"],
        explanation: "Raudonieji kūneliai hemoglobinu neša deguonį.",
      },
    },
  },
  {
    id: "bod_me_004",
    category: "body",
    subTheme: "organs",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (stomach digests food)",
    emoji: "🍽️",
    translations: {
      en: {
        question: "Which organ uses acid to digest food?",
        correct: "Stomach",
        distractors: ["Heart", "Lungs", "Brain", "Kidney", "Bladder"],
        explanation: "The stomach uses acid to break down food.",
      },
      lt: {
        question: "Kuris organas rūgštimi virškina maistą?",
        correct: "Skrandis",
        distractors: ["Širdis", "Plaučiai", "Smegenys", "Inkstas", "Šlapimo pūslė"],
        explanation: "Skrandis rūgštimi skaido maistą.",
      },
    },
  },
  {
    id: "bod_me_005",
    category: "body",
    subTheme: "anatomy",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (adult body about 60% water)",
    emoji: "💧",
    translations: {
      en: {
        question: "About what fraction of the adult body is water?",
        correct: "About 60%",
        distractors: ["About 10%", "About 25%", "About 90%", "About 40%", "About 80%"],
        explanation: "An adult body is roughly 60 percent water.",
      },
      lt: {
        question: "Maždaug kiek suaugusio kūno sudaro vanduo?",
        correct: "Apie 60%",
        distractors: ["Apie 10%", "Apie 25%", "Apie 90%", "Apie 40%", "Apie 80%"],
        explanation: "Suaugęs kūnas yra maždaug 60 procentų vandens.",
      },
    },
  },
  {
    id: "bod_me_006",
    category: "body",
    subTheme: "anatomy",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (biceps in the arm)",
    emoji: "💪",
    translations: {
      en: {
        question: "The biceps muscle is found in which body part?",
        correct: "Arm",
        distractors: ["Leg", "Back", "Neck", "Chest", "Foot"],
        explanation: "The biceps is a muscle in the upper arm.",
      },
      lt: {
        question: "Kurioje kūno dalyje yra dvigalvis (biceps) raumuo?",
        correct: "Rankoje",
        distractors: ["Kojoje", "Nugaroje", "Kakle", "Krūtinėje", "Pėdoje"],
        explanation: "Bicepsas — raumuo viršutinėje rankos dalyje.",
      },
    },
  },
  {
    id: "bod_me_007",
    category: "body",
    subTheme: "organs",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (liver processes nutrients)",
    emoji: "🫀",
    translations: {
      en: {
        question: "Which large organ helps clean the blood and store energy?",
        correct: "Liver",
        distractors: ["Heart", "Lung", "Bladder", "Eye", "Ear"],
        explanation: "The liver filters blood and stores energy.",
      },
      lt: {
        question: "Kuris didelis organas valo kraują ir kaupia energiją?",
        correct: "Kepenys",
        distractors: ["Širdis", "Plautis", "Šlapimo pūslė", "Akis", "Ausis"],
        explanation: "Kepenys filtruoja kraują ir kaupia energiją.",
      },
    },
  },
  {
    id: "bod_me_008",
    category: "body",
    subTheme: "anatomy",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (heart has four chambers)",
    emoji: "❤️",
    translations: {
      en: {
        question: "How many chambers does the human heart have?",
        correct: "4",
        distractors: ["2", "3", "5", "6", "1"],
        explanation: "The heart has four chambers.",
      },
      lt: {
        question: "Kiek kamerų turi žmogaus širdis?",
        correct: "4",
        distractors: ["2", "3", "5", "6", "1"],
        explanation: "Širdis turi keturias kameras.",
      },
    },
  },
  {
    id: "bod_me_009",
    category: "body",
    subTheme: "skeleton",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (ribs protect heart and lungs)",
    emoji: "🦴",
    translations: {
      en: {
        question: "Which bones form a cage protecting the heart and lungs?",
        correct: "Ribs",
        distractors: ["Skull", "Spine", "Pelvis", "Femur", "Jaw"],
        explanation: "The ribs form a cage around the heart and lungs.",
      },
      lt: {
        question: "Kurie kaulai sudaro narvą, saugantį širdį ir plaučius?",
        correct: "Šonkauliai",
        distractors: ["Kaukolė", "Stuburas", "Dubuo", "Šlaunikaulis", "Žandikaulis"],
        explanation: "Šonkauliai sudaro narvą aplink širdį ir plaučius.",
      },
    },
  },
  {
    id: "bod_me_010",
    category: "body",
    subTheme: "anatomy",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (lungs come in a pair)",
    emoji: "🫁",
    translations: {
      en: {
        question: "How many lungs does a person normally have?",
        correct: "2",
        distractors: ["1", "3", "4", "5", "6"],
        explanation: "People normally have two lungs.",
      },
      lt: {
        question: "Kiek plaučių paprastai turi žmogus?",
        correct: "2",
        distractors: ["1", "3", "4", "5", "6"],
        explanation: "Žmogus paprastai turi du plaučius.",
      },
    },
  },
  {
    id: "bod_me_011",
    category: "body",
    subTheme: "anatomy",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (skeletal muscle moves bones)",
    emoji: "🦵",
    translations: {
      en: {
        question: "What connects muscles to bones?",
        correct: "Tendons",
        distractors: ["Veins", "Nerves", "Arteries", "Glands", "Cartilage"],
        explanation: "Tendons attach muscles to bones.",
      },
      lt: {
        question: "Kas jungia raumenis prie kaulų?",
        correct: "Sausgyslės",
        distractors: ["Venos", "Nervai", "Arterijos", "Liaukos", "Kremzlė"],
        explanation: "Sausgyslės tvirtina raumenis prie kaulų.",
      },
    },
  },
  {
    id: "bod_me_012",
    category: "body",
    subTheme: "senses",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (eardrum in the ear)",
    emoji: "👂",
    translations: {
      en: {
        question: "The eardrum is part of which organ?",
        correct: "Ear",
        distractors: ["Eye", "Nose", "Throat", "Skin", "Tongue"],
        explanation: "The eardrum vibrates to help us hear.",
      },
      lt: {
        question: "Ausies būgnelis yra kurio organo dalis?",
        correct: "Ausies",
        distractors: ["Akies", "Nosies", "Gerklės", "Odos", "Liežuvio"],
        explanation: "Ausies būgnelis virpa ir padeda girdėti.",
      },
    },
  },
  {
    id: "bod_me_013",
    category: "body",
    subTheme: "anatomy",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (adult has 32 teeth)",
    emoji: "🦷",
    translations: {
      en: {
        question: "How many teeth does a typical adult have?",
        correct: "32",
        distractors: ["20", "24", "28", "36", "40"],
        explanation: "A full adult set is 32 teeth.",
      },
      lt: {
        question: "Kiek dantų paprastai turi suaugęs žmogus?",
        correct: "32",
        distractors: ["20", "24", "28", "36", "40"],
        explanation: "Pilnas suaugusio žmogaus rinkinys — 32 dantys.",
      },
    },
  },
  {
    id: "bod_me_014",
    category: "body",
    subTheme: "skeleton",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (spine, vertebral column)",
    emoji: "🦴",
    translations: {
      en: {
        question: "What is the column of bones along the back called?",
        correct: "Spine",
        distractors: ["Rib", "Skull", "Pelvis", "Collarbone", "Kneecap"],
        explanation: "The spine is the column of bones in the back.",
      },
      lt: {
        question: "Kaip vadinamas kaulų stulpas išilgai nugaros?",
        correct: "Stuburas",
        distractors: ["Šonkaulis", "Kaukolė", "Dubuo", "Raktikaulis", "Girnelė"],
        explanation: "Stuburas — kaulų stulpas nugaroje.",
      },
    },
  },
  {
    id: "bod_me_015",
    category: "body",
    subTheme: "anatomy",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Physiology (resting heart rate ~60-100 bpm)",
    emoji: "💓",
    translations: {
      en: {
        question: "A resting adult heart beats roughly how many times a minute?",
        correct: "About 70",
        distractors: ["About 20", "About 150", "About 250", "About 10", "About 400"],
        explanation: "A resting adult heart beats about 60-100 times a minute.",
      },
      lt: {
        question: "Ramybės būsenoje suaugusiojo širdis plaka maždaug kiek kartų per minutę?",
        correct: "Apie 70",
        distractors: ["Apie 20", "Apie 150", "Apie 250", "Apie 10", "Apie 400"],
        explanation: "Ramybėje suaugusiojo širdis plaka apie 60-100 k./min.",
      },
    },
  },

  // ======================= SUNKUS (Hard) =======================
  {
    id: "bod_su_001",
    category: "body",
    subTheme: "anatomy",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Anatomy (femur is longest bone)",
    emoji: "🦴",
    translations: {
      en: {
        question: "What is the longest bone in the human body?",
        correct: "Femur",
        distractors: ["Tibia", "Humerus", "Spine", "Skull", "Rib"],
        explanation: "The femur, the thigh bone, is the longest bone.",
      },
      lt: {
        question: "Koks ilgiausias kaulas žmogaus kūne?",
        correct: "Šlaunikaulis",
        distractors: ["Blauzdikaulis", "Žastikaulis", "Stuburas", "Kaukolė", "Šonkaulis"],
        explanation: "Šlaunikaulis (femur) yra ilgiausias kūno kaulas.",
      },
    },
  },
  {
    id: "bod_su_002",
    category: "body",
    subTheme: "organs",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Anatomy (skin is largest organ; trap vs liver)",
    emoji: "🧬",
    translations: {
      en: {
        question: "What is the largest internal organ?",
        correct: "Liver",
        distractors: ["Heart", "Brain", "Kidney", "Spleen", "Pancreas"],
        explanation: "The liver is the largest internal organ.",
      },
      lt: {
        question: "Koks didžiausias vidaus organas?",
        correct: "Kepenys",
        distractors: ["Širdis", "Smegenys", "Inkstas", "Blužnis", "Kasa"],
        explanation: "Kepenys — didžiausias vidaus organas.",
      },
    },
  },
  {
    id: "bod_su_003",
    category: "body",
    subTheme: "anatomy",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Anatomy (stapes is smallest bone, in ear)",
    emoji: "👂",
    translations: {
      en: {
        question: "The smallest bone in the body is found in which organ?",
        correct: "Ear",
        distractors: ["Eye", "Nose", "Hand", "Foot", "Knee"],
        explanation: "The stapes, the smallest bone, is in the ear.",
      },
      lt: {
        question: "Mažiausias kūno kaulas yra kuriame organe?",
        correct: "Ausyje",
        distractors: ["Akyje", "Nosyje", "Plaštakoje", "Pėdoje", "Kelyje"],
        explanation: "Mažiausias kaulas, kilpelė (stapes), yra ausyje.",
      },
    },
  },
  {
    id: "bod_su_004",
    category: "body",
    subTheme: "physiology",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Anatomy (red cells made in bone marrow)",
    emoji: "🦴",
    translations: {
      en: {
        question: "Where are most blood cells produced?",
        correct: "Bone marrow",
        distractors: ["Liver", "Heart", "Spleen", "Kidney", "Lungs"],
        explanation: "Bone marrow produces most blood cells.",
      },
      lt: {
        question: "Kur gaminama dauguma kraujo ląstelių?",
        correct: "Kaulų čiulpuose",
        distractors: ["Kepenyse", "Širdyje", "Blužnyje", "Inkste", "Plaučiuose"],
        explanation: "Dauguma kraujo ląstelių gaminama kaulų čiulpuose.",
      },
    },
  },
  {
    id: "bod_su_005",
    category: "body",
    subTheme: "physiology",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Physiology (insulin from pancreas)",
    emoji: "🩺",
    translations: {
      en: {
        question: "Which organ produces the hormone insulin?",
        correct: "Pancreas",
        distractors: ["Liver", "Kidney", "Heart", "Stomach", "Spleen"],
        explanation: "The pancreas makes insulin to control blood sugar.",
      },
      lt: {
        question: "Kuris organas gamina hormoną insuliną?",
        correct: "Kasa",
        distractors: ["Kepenys", "Inkstas", "Širdis", "Skrandis", "Blužnis"],
        explanation: "Kasa gamina insuliną, valdantį cukraus kiekį kraujyje.",
      },
    },
  },
  {
    id: "bod_su_006",
    category: "body",
    subTheme: "anatomy",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Anatomy (alveoli in lungs)",
    emoji: "🫁",
    translations: {
      en: {
        question: "Tiny air sacs where oxygen enters blood are called what?",
        correct: "Alveoli",
        distractors: ["Neurons", "Villi", "Nephrons", "Follicles", "Capillary loops"],
        explanation: "Alveoli in the lungs exchange oxygen and gas.",
      },
      lt: {
        question: "Kaip vadinami maži oro maišeliai, kur deguonis patenka į kraują?",
        correct: "Alveolės",
        distractors: ["Neuronai", "Gaureliai", "Nefronai", "Folikulai", "Kapiliarai"],
        explanation: "Alveolės plaučiuose keičiasi deguonimi ir dujomis.",
      },
    },
  },
  {
    id: "bod_su_007",
    category: "body",
    subTheme: "physiology",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Anatomy (white cells fight infection)",
    emoji: "🛡️",
    translations: {
      en: {
        question: "Which blood cells help fight infection?",
        correct: "White blood cells",
        distractors: ["Red blood cells", "Platelets", "Plasma cells only", "Nerve cells", "Muscle cells"],
        explanation: "White blood cells defend against infection.",
      },
      lt: {
        question: "Kurios kraujo ląstelės padeda kovoti su infekcija?",
        correct: "Baltieji kraujo kūneliai",
        distractors: ["Raudonieji kūneliai", "Trombocitai", "Tik plazmos ląstelės", "Nervų ląstelės", "Raumenų ląstelės"],
        explanation: "Baltieji kūneliai gina nuo infekcijos.",
      },
    },
  },
  {
    id: "bod_su_008",
    category: "body",
    subTheme: "anatomy",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Anatomy (largest muscle is gluteus maximus)",
    emoji: "🦵",
    translations: {
      en: {
        question: "What is the largest muscle in the human body?",
        correct: "Gluteus maximus",
        distractors: ["Biceps", "Heart", "Calf", "Tongue", "Jaw"],
        explanation: "The gluteus maximus in the buttock is the largest.",
      },
      lt: {
        question: "Koks didžiausias raumuo žmogaus kūne?",
        correct: "Didysis sėdmens raumuo",
        distractors: ["Bicepsas", "Širdis", "Blauzda", "Liežuvis", "Žandikaulis"],
        explanation: "Didysis sėdmens raumuo yra didžiausias.",
      },
    },
  },
  {
    id: "bod_su_009",
    category: "body",
    subTheme: "physiology",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Physiology (esophagus carries food)",
    emoji: "🍽️",
    translations: {
      en: {
        question: "Which tube carries food from the throat to the stomach?",
        correct: "Esophagus",
        distractors: ["Trachea", "Artery", "Vein", "Ureter", "Bronchus"],
        explanation: "The esophagus moves food to the stomach.",
      },
      lt: {
        question: "Kuris vamzdis veda maistą iš gerklės į skrandį?",
        correct: "Stemplė",
        distractors: ["Trachėja", "Arterija", "Vena", "Šlapimtakis", "Bronchas"],
        explanation: "Stemplė nuveda maistą į skrandį.",
      },
    },
  },
  {
    id: "bod_su_010",
    category: "body",
    subTheme: "anatomy",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Anatomy (cornea at front of eye)",
    emoji: "👁️",
    translations: {
      en: {
        question: "The clear front layer of the eye is called the what?",
        correct: "Cornea",
        distractors: ["Retina", "Iris", "Pupil", "Lens", "Sclera"],
        explanation: "The cornea is the clear front of the eye.",
      },
      lt: {
        question: "Kaip vadinamas skaidrus priekinis akies sluoksnis?",
        correct: "Ragena",
        distractors: ["Tinklainė", "Rainelė", "Vyzdys", "Lęšiukas", "Skleros dalis"],
        explanation: "Ragena — skaidri priekinė akies dalis.",
      },
    },
  },
  {
    id: "bod_su_011",
    category: "body",
    subTheme: "physiology",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Physiology (platelets help clotting)",
    emoji: "🩸",
    translations: {
      en: {
        question: "Which blood part helps wounds clot?",
        correct: "Platelets",
        distractors: ["Red cells", "White cells", "Plasma water", "Nerve cells", "Bone cells"],
        explanation: "Platelets clump to help blood clot.",
      },
      lt: {
        question: "Kuri kraujo dalis padeda žaizdoms krešėti?",
        correct: "Trombocitai",
        distractors: ["Raudonieji kūneliai", "Baltieji kūneliai", "Plazmos vanduo", "Nervų ląstelės", "Kaulų ląstelės"],
        explanation: "Trombocitai sukimba ir padeda kraujui krešėti.",
      },
    },
  },
  {
    id: "bod_su_012",
    category: "body",
    subTheme: "anatomy",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Anatomy (diaphragm muscle for breathing)",
    emoji: "🫁",
    translations: {
      en: {
        question: "Which muscle below the lungs helps you breathe?",
        correct: "Diaphragm",
        distractors: ["Biceps", "Heart", "Calf", "Jaw", "Tongue"],
        explanation: "The diaphragm contracts to pull air into the lungs.",
      },
      lt: {
        question: "Kuris raumuo po plaučiais padeda kvėpuoti?",
        correct: "Diafragma",
        distractors: ["Bicepsas", "Širdis", "Blauzda", "Žandikaulis", "Liežuvis"],
        explanation: "Diafragma susitraukdama įtraukia orą į plaučius.",
      },
    },
  },
  {
    id: "bod_su_013",
    category: "body",
    subTheme: "physiology",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Anatomy (neurons in nervous system)",
    emoji: "🧠",
    translations: {
      en: {
        question: "The basic cells that carry nerve signals are called what?",
        correct: "Neurons",
        distractors: ["Alveoli", "Nephrons", "Villi", "Platelets", "Follicles"],
        explanation: "Neurons are nerve cells that carry signals.",
      },
      lt: {
        question: "Kaip vadinamos pagrindinės ląstelės, nešančios nervų signalus?",
        correct: "Neuronai",
        distractors: ["Alveolės", "Nefronai", "Gaureliai", "Trombocitai", "Folikulai"],
        explanation: "Neuronai — nervų ląstelės, nešančios signalus.",
      },
    },
  },
  {
    id: "bod_su_014",
    category: "body",
    subTheme: "anatomy",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Anatomy (small intestine absorbs nutrients)",
    emoji: "🌀",
    translations: {
      en: {
        question: "Where are most nutrients absorbed from food?",
        correct: "Small intestine",
        distractors: ["Stomach", "Large intestine", "Liver", "Mouth", "Esophagus"],
        explanation: "Most nutrients are absorbed in the small intestine.",
      },
      lt: {
        question: "Kur iš maisto pasisavinama daugiausia maistinių medžiagų?",
        correct: "Plonojoje žarnoje",
        distractors: ["Skrandyje", "Storojoje žarnoje", "Kepenyse", "Burnoje", "Stemplėje"],
        explanation: "Daugiausia maistinių medžiagų pasisavinama plonojoje žarnoje.",
      },
    },
  },
  {
    id: "bod_su_015",
    category: "body",
    subTheme: "physiology",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Anatomy (nephrons filter in kidney)",
    emoji: "🫘",
    translations: {
      en: {
        question: "The tiny filtering units of the kidney are called what?",
        correct: "Nephrons",
        distractors: ["Neurons", "Alveoli", "Villi", "Follicles", "Capillaries only"],
        explanation: "Nephrons are the filtering units of the kidney.",
      },
      lt: {
        question: "Kaip vadinami maži inksto filtravimo vienetai?",
        correct: "Nefronai",
        distractors: ["Neuronai", "Alveolės", "Gaureliai", "Folikulai", "Tik kapiliarai"],
        explanation: "Nefronai — inksto filtravimo vienetai.",
      },
    },
  },

  // ======================= EKSTREMALUS (Extreme) =======================
  {
    id: "bod_ek_001",
    category: "body",
    subTheme: "physiology",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Anatomy (femur longest, stapes shortest)",
    emoji: "🦴",
    translations: {
      en: {
        question: "What is the name of the smallest bone in the body?",
        correct: "Stapes",
        distractors: ["Femur", "Ulna", "Patella", "Hyoid", "Coccyx"],
        explanation: "The stapes in the ear is the smallest bone.",
      },
      lt: {
        question: "Koks mažiausio kūno kaulo pavadinimas?",
        correct: "Kilpelė (stapes)",
        distractors: ["Šlaunikaulis", "Alkūnkaulis", "Girnelė", "Poliežuvinis", "Uodegikaulis"],
        explanation: "Kilpelė (stapes) ausyje — mažiausias kaulas.",
      },
    },
  },
  {
    id: "bod_ek_002",
    category: "body",
    subTheme: "physiology",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Biology (DNA carries genetic code)",
    emoji: "🧬",
    translations: {
      en: {
        question: "Which molecule carries our genetic information?",
        correct: "DNA",
        distractors: ["ATP", "Glucose", "Collagen", "Keratin", "Insulin"],
        explanation: "DNA carries the genetic code in cells.",
      },
      lt: {
        question: "Kuri molekulė neša mūsų genetinę informaciją?",
        correct: "DNR",
        distractors: ["ATP", "Gliukozė", "Kolagenas", "Keratinas", "Insulinas"],
        explanation: "DNR neša genetinį kodą ląstelėse.",
      },
    },
  },
  {
    id: "bod_ek_003",
    category: "body",
    subTheme: "physiology",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Anatomy (largest artery is aorta)",
    emoji: "🫀",
    translations: {
      en: {
        question: "What is the body's largest artery called?",
        correct: "Aorta",
        distractors: ["Vena cava", "Carotid", "Femoral", "Pulmonary vein", "Capillary"],
        explanation: "The aorta is the largest artery, leaving the heart.",
      },
      lt: {
        question: "Kaip vadinama didžiausia kūno arterija?",
        correct: "Aorta",
        distractors: ["Tuščioji vena", "Miego arterija", "Šlauninė", "Plautinė vena", "Kapiliaras"],
        explanation: "Aorta — didžiausia arterija, išeinanti iš širdies.",
      },
    },
  },
  {
    id: "bod_ek_004",
    category: "body",
    subTheme: "physiology",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Anatomy (46 chromosomes in human cells)",
    emoji: "🧬",
    translations: {
      en: {
        question: "How many chromosomes are in a typical human cell?",
        correct: "46",
        distractors: ["23", "44", "48", "92", "12"],
        explanation: "Most human cells have 46 chromosomes.",
      },
      lt: {
        question: "Kiek chromosomų yra įprastoje žmogaus ląstelėje?",
        correct: "46",
        distractors: ["23", "44", "48", "92", "12"],
        explanation: "Daugumoje žmogaus ląstelių yra 46 chromosomos.",
      },
    },
  },
  {
    id: "bod_ek_005",
    category: "body",
    subTheme: "anatomy",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Anatomy (largest organ skin, internal liver)",
    emoji: "🧠",
    translations: {
      en: {
        question: "Which part of the brain controls balance and coordination?",
        correct: "Cerebellum",
        distractors: ["Cerebrum", "Spinal cord", "Retina", "Cortex only", "Pituitary"],
        explanation: "The cerebellum manages balance and coordination.",
      },
      lt: {
        question: "Kuri smegenų dalis valdo pusiausvyrą ir koordinaciją?",
        correct: "Smegenėlės",
        distractors: ["Didieji pusrutuliai", "Nugaros smegenys", "Tinklainė", "Tik žievė", "Hipofizė"],
        explanation: "Smegenėlės valdo pusiausvyrą ir koordinaciją.",
      },
    },
  },
  {
    id: "bod_ek_006",
    category: "body",
    subTheme: "physiology",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Anatomy (small intestine longest part of gut)",
    emoji: "🌀",
    translations: {
      en: {
        question: "Which part of the digestive tract is the longest?",
        correct: "Small intestine",
        distractors: ["Stomach", "Esophagus", "Large intestine", "Mouth", "Throat"],
        explanation: "The small intestine is the longest digestive section.",
      },
      lt: {
        question: "Kuri virškinimo trakto dalis yra ilgiausia?",
        correct: "Plonoji žarna",
        distractors: ["Skrandis", "Stemplė", "Storoji žarna", "Burna", "Gerklė"],
        explanation: "Plonoji žarna — ilgiausia virškinimo trakto dalis.",
      },
    },
  },
  {
    id: "bod_ek_007",
    category: "body",
    subTheme: "physiology",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Biology (cell powerhouse mitochondria)",
    emoji: "🔋",
    translations: {
      en: {
        question: "Which cell part is called the powerhouse of the cell?",
        correct: "Mitochondria",
        distractors: ["Nucleus", "Ribosome", "Membrane", "Vacuole", "Cytoplasm"],
        explanation: "Mitochondria produce energy for the cell.",
      },
      lt: {
        question: "Kuri ląstelės dalis vadinama ląstelės jėgaine?",
        correct: "Mitochondrijos",
        distractors: ["Branduolys", "Ribosoma", "Membrana", "Vakuolė", "Citoplazma"],
        explanation: "Mitochondrijos gamina energiją ląstelei.",
      },
    },
  },
  {
    id: "bod_ek_008",
    category: "body",
    subTheme: "physiology",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Physiology (blood pH ~7.4)",
    emoji: "🩸",
    translations: {
      en: {
        question: "What is the approximate pH of healthy human blood?",
        correct: "About 7.4",
        distractors: [
          "About 7.0",
          "About 6.5",
          "About 8.5",
          "About 5.5",
          "About 8.0",
        ],
        explanation: "Healthy blood is slightly basic, with a pH near 7.4.",
      },
      lt: {
        question: "Koks yra apytikslis sveiko žmogaus kraujo pH?",
        correct: "Apie 7,4",
        distractors: [
          "Apie 7,0",
          "Apie 6,5",
          "Apie 8,5",
          "Apie 5,5",
          "Apie 8,0",
        ],
        explanation: "Sveikas kraujas šiek tiek šarminis, pH apie 7,4.",
      },
    },
  },
  {
    id: "bod_ek_009",
    category: "body",
    subTheme: "anatomy",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Anatomy (retina detects light)",
    emoji: "👁️",
    translations: {
      en: {
        question: "Which layer at the back of the eye detects light?",
        correct: "Retina",
        distractors: ["Cornea", "Iris", "Pupil", "Lens", "Sclera"],
        explanation: "The retina senses light and sends signals to the brain.",
      },
      lt: {
        question: "Kuris akies užpakalio sluoksnis pagauna šviesą?",
        correct: "Tinklainė",
        distractors: ["Ragena", "Rainelė", "Vyzdys", "Lęšiukas", "Sklera"],
        explanation: "Tinklainė jaučia šviesą ir siunčia signalus į smegenis.",
      },
    },
  },
  {
    id: "bod_ek_010",
    category: "body",
    subTheme: "physiology",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Physiology (hemoglobin carries oxygen)",
    emoji: "🩸",
    translations: {
      en: {
        question: "Which protein in red blood cells carries oxygen?",
        correct: "Hemoglobin",
        distractors: ["Keratin", "Collagen", "Insulin", "Albumin", "Myosin"],
        explanation: "Hemoglobin binds oxygen in red blood cells.",
      },
      lt: {
        question: "Kuris baltymas raudonuosiuose kūneliuose neša deguonį?",
        correct: "Hemoglobinas",
        distractors: ["Keratinas", "Kolagenas", "Insulinas", "Albuminas", "Miozinas"],
        explanation: "Hemoglobinas suriša deguonį raudonuosiuose kūneliuose.",
      },
    },
  },
  {
    id: "bod_ek_011",
    category: "body",
    subTheme: "physiology",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Biology (nucleus holds DNA)",
    emoji: "🧬",
    translations: {
      en: {
        question: "Which part of a cell holds most of its DNA?",
        correct: "Nucleus",
        distractors: ["Membrane", "Ribosome", "Mitochondria", "Vacuole", "Cytoplasm"],
        explanation: "The nucleus stores most of the cell's DNA.",
      },
      lt: {
        question: "Kurioje ląstelės dalyje yra daugiausia jos DNR?",
        correct: "Branduolyje",
        distractors: ["Membranoje", "Ribosomoje", "Mitochondrijose", "Vakuolėje", "Citoplazmoje"],
        explanation: "Branduolyje saugoma didžioji dalis ląstelės DNR.",
      },
    },
  },
  {
    id: "bod_ek_012",
    category: "body",
    subTheme: "anatomy",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Anatomy (liver can regenerate)",
    emoji: "🫀",
    translations: {
      en: {
        question: "Which human organ can regrow much of itself if damaged?",
        correct: "Liver",
        distractors: ["Heart", "Brain", "Eye", "Kidney", "Lung"],
        explanation: "The liver can regenerate a large part of itself.",
      },
      lt: {
        question: "Kuris žmogaus organas gali didele dalimi atsinaujinti po pažeidimo?",
        correct: "Kepenys",
        distractors: ["Širdis", "Smegenys", "Akis", "Inkstas", "Plautis"],
        explanation: "Kepenys gali atauginti didelę savo dalį.",
      },
    },
  },
  {
    id: "bod_ek_013",
    category: "body",
    subTheme: "physiology",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Anatomy (adult has 12 pairs of ribs)",
    emoji: "🦴",
    translations: {
      en: {
        question: "How many pairs of ribs does a typical person have?",
        correct: "12",
        distractors: ["10", "11", "13", "14", "8"],
        explanation: "Most people have 12 pairs of ribs.",
      },
      lt: {
        question: "Kiek porų šonkaulių paprastai turi žmogus?",
        correct: "12",
        distractors: ["10", "11", "13", "14", "8"],
        explanation: "Dauguma žmonių turi 12 porų šonkaulių.",
      },
    },
  },
  {
    id: "bod_ek_014",
    category: "body",
    subTheme: "anatomy",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Anatomy (hand has 27 bones)",
    emoji: "✋",
    translations: {
      en: {
        question: "About how many bones are in one human hand?",
        correct: "27",
        distractors: ["12", "19", "33", "40", "8"],
        explanation: "One human hand contains about 27 bones.",
      },
      lt: {
        question: "Maždaug kiek kaulų yra vienoje žmogaus plaštakoje?",
        correct: "27",
        distractors: ["12", "19", "33", "40", "8"],
        explanation: "Vienoje plaštakoje yra maždaug 27 kaulai.",
      },
    },
  },
  {
    id: "bod_ek_015",
    category: "body",
    subTheme: "physiology",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Anatomy (skin is largest organ overall)",
    emoji: "🖐️",
    translations: {
      en: {
        question: "Counting all organs, which is the largest of the body?",
        correct: "Skin",
        distractors: ["Liver", "Brain", "Heart", "Intestine", "Lung"],
        explanation: "Skin is the largest organ overall, larger than the liver.",
      },
      lt: {
        question: "Skaičiuojant visus organus, kuris yra didžiausias kūne?",
        correct: "Oda",
        distractors: ["Kepenys", "Smegenys", "Širdis", "Žarnynas", "Plautis"],
        explanation: "Oda — didžiausias visas organas, didesnis už kepenis.",
      },
    },
  },
  {
    id: "bod_le_016",
    category: "body",
    subTheme: "basics",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Legs used for walking",
    emoji: "🦵",
    translations: {
      en: {
        question: "Which body parts do you mainly use to walk?",
        correct: "Legs",
        distractors: ["Arms", "Ears", "Eyes", "Nose", "Hands"],
        explanation: "We walk using our legs and feet.",
      },
      lt: {
        question: "Kuriomis kūno dalimis daugiausia vaikštome?",
        correct: "Kojomis",
        distractors: ["Rankomis", "Ausimis", "Akimis", "Nosimi", "Plaštakomis"],
        explanation: "Vaikštome kojomis ir pėdomis.",
      },
    },
  },
  {
    id: "bod_le_017",
    category: "body",
    subTheme: "basics",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Nails grow on fingertips",
    emoji: "💅",
    translations: {
      en: {
        question: "What hard part grows at the tips of your fingers?",
        correct: "Nails",
        distractors: ["Scales", "Teeth", "Feathers", "Fur", "Horns"],
        explanation: "Fingernails grow at the tips of fingers.",
      },
      lt: {
        question: "Kokia kieta dalis auga pirštų galuose?",
        correct: "Nagai",
        distractors: ["Žvynai", "Dantys", "Plunksnos", "Kailis", "Ragai"],
        explanation: "Pirštų galuose auga nagai.",
      },
    },
  },
  {
    id: "bod_le_018",
    category: "body",
    subTheme: "basics",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Humans have 2 eyes",
    emoji: "👀",
    translations: {
      en: {
        question: "How many eyes does a person normally have?",
        correct: "2",
        distractors: ["1", "3", "4", "5", "0"],
        explanation: "People normally have two eyes.",
      },
      lt: {
        question: "Kiek akių paprastai turi žmogus?",
        correct: "2",
        distractors: ["1", "3", "4", "5", "0"],
        explanation: "Žmogus paprastai turi dvi akis.",
      },
    },
  },
  {
    id: "bod_le_019",
    category: "body",
    subTheme: "basics",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Tears come from eyes when crying",
    emoji: "😢",
    translations: {
      en: {
        question: "What liquid comes from your eyes when you cry?",
        correct: "Tears",
        distractors: ["Sweat", "Saliva", "Blood", "Mucus", "Oil"],
        explanation: "Crying releases tears from the eyes.",
      },
      lt: {
        question: "Koks skystis bėga iš akių, kai verki?",
        correct: "Ašaros",
        distractors: ["Prakaitas", "Seilės", "Kraujas", "Gleivės", "Aliejus"],
        explanation: "Verkiant iš akių bėga ašaros.",
      },
    },
  },
  {
    id: "bod_le_020",
    category: "body",
    subTheme: "basics",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Hand has palm and fingers",
    emoji: "✋",
    translations: {
      en: {
        question: "Which body part has a palm and fingers?",
        correct: "Hand",
        distractors: ["Foot", "Ear", "Nose", "Knee", "Elbow"],
        explanation: "The hand has a palm and five fingers.",
      },
      lt: {
        question: "Kuri kūno dalis turi delną ir pirštus?",
        correct: "Plaštaka",
        distractors: ["Pėda", "Ausis", "Nosis", "Kelis", "Alkūnė"],
        explanation: "Plaštaka turi delną ir penkis pirštus.",
      },
    },
  },
  {
    id: "bod_le_021",
    category: "body",
    subTheme: "basics",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Humans have 2 ears",
    emoji: "👂",
    translations: {
      en: {
        question: "How many ears does a person normally have?",
        correct: "2",
        distractors: ["1", "3", "4", "0", "5"],
        explanation: "People normally have two ears.",
      },
      lt: {
        question: "Kiek ausų paprastai turi žmogus?",
        correct: "2",
        distractors: ["1", "3", "4", "0", "5"],
        explanation: "Žmogus paprastai turi dvi ausis.",
      },
    },
  },
  {
    id: "bod_le_022",
    category: "body",
    subTheme: "basics",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Knee is the leg's middle joint",
    emoji: "🦵",
    translations: {
      en: {
        question: "What is the bendy joint in the middle of your leg called?",
        correct: "Knee",
        distractors: ["Elbow", "Wrist", "Shoulder", "Ankle", "Hip"],
        explanation: "The knee is the main joint in the middle of the leg.",
      },
      lt: {
        question: "Kaip vadinamas lankstus sąnarys kojos viduryje?",
        correct: "Kelis",
        distractors: ["Alkūnė", "Riešas", "Petys", "Kulkšnis", "Klubas"],
        explanation: "Kelis — pagrindinis kojos vidurio sąnarys.",
      },
    },
  },
  {
    id: "bod_le_023",
    category: "body",
    subTheme: "basics",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Sweat cools the body",
    emoji: "💧",
    translations: {
      en: {
        question: "Sweating helps your body do what?",
        correct: "Cool down",
        distractors: ["Warm up", "Grow", "Sleep", "Digest", "See"],
        explanation: "Sweat evaporates and cools the body.",
      },
      lt: {
        question: "Kam kūnui padeda prakaitavimas?",
        correct: "Atvėsti",
        distractors: ["Sušilti", "Augti", "Miegoti", "Virškinti", "Matyti"],
        explanation: "Prakaitas garuoja ir vėsina kūną.",
      },
    },
  },
  {
    id: "bod_le_024",
    category: "body",
    subTheme: "basics",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Elbow is the arm's middle joint",
    emoji: "💪",
    translations: {
      en: {
        question: "What is the bendy joint in the middle of your arm called?",
        correct: "Elbow",
        distractors: ["Knee", "Wrist", "Shoulder", "Ankle", "Hip"],
        explanation: "The elbow is the joint in the middle of the arm.",
      },
      lt: {
        question: "Kaip vadinamas lankstus sąnarys rankos viduryje?",
        correct: "Alkūnė",
        distractors: ["Kelis", "Riešas", "Petys", "Kulkšnis", "Klubas"],
        explanation: "Alkūnė — sąnarys rankos viduryje.",
      },
    },
  },
  {
    id: "bod_le_025",
    category: "body",
    subTheme: "basics",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Eyelids blink to protect eyes",
    emoji: "👁️",
    translations: {
      en: {
        question: "What quick movement do eyelids make to protect the eyes?",
        correct: "Blink",
        distractors: ["Smell", "Chew", "Hear", "Taste", "Speak"],
        explanation: "Blinking keeps the eyes clean and moist.",
      },
      lt: {
        question: "Kokį greitą judesį daro vokai, kad apsaugotų akis?",
        correct: "Mirksi",
        distractors: ["Uodžia", "Kramto", "Girdi", "Ragauja", "Kalba"],
        explanation: "Mirksėjimas valo ir drėkina akis.",
      },
    },
  },
  {
    id: "bod_le_026",
    category: "body",
    subTheme: "basics",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Humans have 2 legs",
    emoji: "🦵",
    translations: {
      en: {
        question: "How many legs does a human have?",
        correct: "2",
        distractors: ["1", "3", "4", "6", "0"],
        explanation: "Humans have two legs.",
      },
      lt: {
        question: "Kiek kojų turi žmogus?",
        correct: "2",
        distractors: ["1", "3", "4", "6", "0"],
        explanation: "Žmogus turi dvi kojas.",
      },
    },
  },
  {
    id: "bod_le_027",
    category: "body",
    subTheme: "basics",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Head holds the brain",
    emoji: "🧠",
    translations: {
      en: {
        question: "What is the top part of the body that holds the brain called?",
        correct: "Head",
        distractors: ["Foot", "Hand", "Knee", "Chest", "Back"],
        explanation: "The head holds the brain and the face.",
      },
      lt: {
        question: "Kaip vadinama viršutinė kūno dalis, kurioje yra smegenys?",
        correct: "Galva",
        distractors: ["Pėda", "Plaštaka", "Kelis", "Krūtinė", "Nugara"],
        explanation: "Galvoje yra smegenys ir veidas.",
      },
    },
  },
  {
    id: "bod_le_028",
    category: "body",
    subTheme: "basics",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Shoes go on feet",
    emoji: "🦶",
    translations: {
      en: {
        question: "On which body part do you wear shoes?",
        correct: "Feet",
        distractors: ["Hands", "Head", "Ears", "Eyes", "Nose"],
        explanation: "Shoes are worn on the feet.",
      },
      lt: {
        question: "Ant kurios kūno dalies avime batus?",
        correct: "Pėdos",
        distractors: ["Plaštakos", "Galva", "Ausys", "Akys", "Nosis"],
        explanation: "Batai avimi ant pėdų.",
      },
    },
  },
  {
    id: "bod_le_029",
    category: "body",
    subTheme: "basics",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Mouth used to speak and eat",
    emoji: "👄",
    translations: {
      en: {
        question: "Which part of the face do you use to speak and eat?",
        correct: "Mouth",
        distractors: ["Ear", "Eye", "Nose", "Cheek", "Chin"],
        explanation: "We speak and eat using the mouth.",
      },
      lt: {
        question: "Kuria veido dalimi kalbame ir valgome?",
        correct: "Burna",
        distractors: ["Ausimi", "Akimi", "Nosimi", "Skruostu", "Smakru"],
        explanation: "Kalbame ir valgome burna.",
      },
    },
  },
  {
    id: "bod_le_030",
    category: "body",
    subTheme: "basics",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Body needs sleep to rest",
    emoji: "😴",
    translations: {
      en: {
        question: "What does your body mainly need to rest at night?",
        correct: "Sleep",
        distractors: ["Food", "Water", "Exercise", "Sunlight", "Music"],
        explanation: "Sleep lets the body rest and recover.",
      },
      lt: {
        question: "Ko kūnui labiausiai reikia, kad pailsėtų naktį?",
        correct: "Miego",
        distractors: ["Maisto", "Vandens", "Mankštos", "Saulės", "Muzikos"],
        explanation: "Miegas leidžia kūnui pailsėti ir atsigauti.",
      },
    },
  },
  {
    id: "bod_me_016",
    category: "body",
    subTheme: "bones",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Patella is the kneecap",
    emoji: "🦵",
    translations: {
      en: {
        question: "What is the medical name for the kneecap?",
        correct: "Patella",
        distractors: ["Femur", "Tibia", "Fibula", "Humerus", "Pelvis"],
        explanation: "The kneecap is medically called the patella.",
      },
      lt: {
        question: "Koks medicininis kelio girnelės pavadinimas?",
        correct: "Girnelė",
        distractors: ["Šlaunikaulis", "Blauzdikaulis", "Šeivikaulis", "Žastikaulis", "Dubuo"],
        explanation: "Kelio girnelė medicininiu pavadinimu — patela (girnelė).",
      },
    },
  },
  {
    id: "bod_me_017",
    category: "body",
    subTheme: "senses",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Iris is the colored part of the eye",
    emoji: "👁️",
    translations: {
      en: {
        question: "What is the colored part of the eye called?",
        correct: "Iris",
        distractors: ["Pupil", "Retina", "Cornea", "Lens", "Sclera"],
        explanation: "The iris is the colored ring of the eye.",
      },
      lt: {
        question: "Kaip vadinama spalvota akies dalis?",
        correct: "Rainelė",
        distractors: ["Vyzdys", "Tinklainė", "Ragena", "Lęšiukas", "Skleura"],
        explanation: "Rainelė — spalvotas akies žiedas.",
      },
    },
  },
  {
    id: "bod_me_018",
    category: "body",
    subTheme: "systems",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Skin makes vitamin D from sunlight",
    emoji: "☀️",
    translations: {
      en: {
        question: "Which vitamin does our skin make from sunlight?",
        correct: "Vitamin D",
        distractors: ["Vitamin A", "Vitamin C", "Vitamin B", "Vitamin K", "Vitamin E"],
        explanation: "Skin produces vitamin D when exposed to sunlight.",
      },
      lt: {
        question: "Kurį vitaminą mūsų oda gamina iš saulės šviesos?",
        correct: "Vitaminą D",
        distractors: ["Vitaminą A", "Vitaminą C", "Vitaminą B", "Vitaminą K", "Vitaminą E"],
        explanation: "Saulėje oda gamina vitaminą D.",
      },
    },
  },
  {
    id: "bod_me_019",
    category: "body",
    subTheme: "bones",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Clavicle is the collarbone",
    emoji: "🦴",
    translations: {
      en: {
        question: "What is the medical term for the collarbone?",
        correct: "Clavicle",
        distractors: ["Scapula", "Sternum", "Rib", "Vertebra", "Pelvis"],
        explanation: "The collarbone is called the clavicle.",
      },
      lt: {
        question: "Koks medicininis raktikaulio pavadinimas?",
        correct: "Raktikaulis",
        distractors: ["Mentė", "Krūtinkaulis", "Šonkaulis", "Slankstelis", "Dubuo"],
        explanation: "Raktikaulis lotyniškai — clavicula.",
      },
    },
  },
  {
    id: "bod_me_020",
    category: "body",
    subTheme: "organs",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Gallbladder stores bile",
    emoji: "🫧",
    translations: {
      en: {
        question: "Which organ stores bile to help digest fats?",
        correct: "Gallbladder",
        distractors: ["Liver", "Pancreas", "Spleen", "Kidney", "Stomach"],
        explanation: "The gallbladder stores bile made by the liver.",
      },
      lt: {
        question: "Kuris organas kaupia tulžį, padedančią virškinti riebalus?",
        correct: "Tulžies pūslė",
        distractors: ["Kepenys", "Kasa", "Blužnis", "Inkstas", "Skrandis"],
        explanation: "Tulžies pūslė kaupia kepenų pagamintą tulžį.",
      },
    },
  },
  {
    id: "bod_me_021",
    category: "body",
    subTheme: "basics",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Children have 20 milk teeth",
    emoji: "🦷",
    translations: {
      en: {
        question: "How many baby (milk) teeth does a child usually have?",
        correct: "20",
        distractors: ["32", "24", "28", "16", "30"],
        explanation: "Children usually have 20 milk teeth.",
      },
      lt: {
        question: "Kiek pieninių dantų paprastai turi vaikas?",
        correct: "20",
        distractors: ["32", "24", "28", "16", "30"],
        explanation: "Vaikai paprastai turi 20 pieninių dantų.",
      },
    },
  },
  {
    id: "bod_me_022",
    category: "body",
    subTheme: "senses",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Pupil is the opening light passes through",
    emoji: "👁️",
    translations: {
      en: {
        question: "Through which opening does light enter the eye?",
        correct: "Pupil",
        distractors: ["Iris", "Lens", "Cornea", "Retina", "Eyelid"],
        explanation: "Light passes through the pupil into the eye.",
      },
      lt: {
        question: "Pro kurią angą šviesa patenka į akį?",
        correct: "Vyzdys",
        distractors: ["Rainelė", "Lęšiukas", "Ragena", "Tinklainė", "Vokas"],
        explanation: "Šviesa į akį patenka pro vyzdį.",
      },
    },
  },
  {
    id: "bod_me_023",
    category: "body",
    subTheme: "organs",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Cerebrum is the largest brain part",
    emoji: "🧠",
    translations: {
      en: {
        question: "What is the largest part of the human brain called?",
        correct: "Cerebrum",
        distractors: ["Cerebellum", "Brainstem", "Spinal cord", "Thalamus", "Cortex"],
        explanation: "The cerebrum is the brain's largest part.",
      },
      lt: {
        question: "Kaip vadinama didžiausia žmogaus smegenų dalis?",
        correct: "Didžiosios smegenys",
        distractors: ["Smegenėlės", "Smegenų kamienas", "Nugaros smegenys", "Talamas", "Žievė"],
        explanation: "Didžiosios smegenys — didžiausia smegenų dalis.",
      },
    },
  },
  {
    id: "bod_me_024",
    category: "body",
    subTheme: "organs",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Thyroid controls metabolism",
    emoji: "🦋",
    translations: {
      en: {
        question: "Which gland in the neck controls metabolism?",
        correct: "Thyroid",
        distractors: ["Pancreas", "Adrenal", "Pituitary", "Liver", "Spleen"],
        explanation: "The thyroid gland regulates metabolism.",
      },
      lt: {
        question: "Kuri liauka kakle reguliuoja medžiagų apykaitą?",
        correct: "Skydliaukė",
        distractors: ["Kasa", "Antinksčiai", "Hipofizė", "Kepenys", "Blužnis"],
        explanation: "Skydliaukė reguliuoja medžiagų apykaitą.",
      },
    },
  },
  {
    id: "bod_me_025",
    category: "body",
    subTheme: "bones",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Sternum is the breastbone",
    emoji: "🦴",
    translations: {
      en: {
        question: "What is the medical name for the breastbone?",
        correct: "Sternum",
        distractors: ["Clavicle", "Scapula", "Rib", "Pelvis", "Vertebra"],
        explanation: "The breastbone is called the sternum.",
      },
      lt: {
        question: "Koks medicininis krūtinkaulio pavadinimas?",
        correct: "Krūtinkaulis",
        distractors: ["Raktikaulis", "Mentė", "Šonkaulis", "Dubuo", "Slankstelis"],
        explanation: "Krūtinkaulis lotyniškai — sternum.",
      },
    },
  },
  {
    id: "bod_me_026",
    category: "body",
    subTheme: "organs",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Right lung has 3 lobes",
    emoji: "🫁",
    translations: {
      en: {
        question: "How many lobes does the right lung have?",
        correct: "3",
        distractors: ["2", "4", "1", "5", "6"],
        explanation: "The right lung has 3 lobes; the left has 2.",
      },
      lt: {
        question: "Kiek skilčių turi dešinysis plautis?",
        correct: "3",
        distractors: ["2", "4", "1", "5", "6"],
        explanation: "Dešinysis plautis turi 3 skiltis, kairysis — 2.",
      },
    },
  },
  {
    id: "bod_me_027",
    category: "body",
    subTheme: "systems",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Plasma is the liquid part of blood",
    emoji: "🩸",
    translations: {
      en: {
        question: "What is the liquid part of blood called?",
        correct: "Plasma",
        distractors: ["Serum", "Lymph", "Marrow", "Bile", "Mucus"],
        explanation: "Plasma is the fluid that carries blood cells.",
      },
      lt: {
        question: "Kaip vadinama skystoji kraujo dalis?",
        correct: "Plazma",
        distractors: ["Serumas", "Limfa", "Čiulpai", "Tulžis", "Gleivės"],
        explanation: "Plazma — skystis, nešantis kraujo ląsteles.",
      },
    },
  },
  {
    id: "bod_me_028",
    category: "body",
    subTheme: "basics",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Enamel is the tooth's outer covering",
    emoji: "🦷",
    translations: {
      en: {
        question: "What is the hard white outer covering of a tooth called?",
        correct: "Enamel",
        distractors: ["Dentin", "Pulp", "Root", "Gum", "Crown"],
        explanation: "Enamel is the hard outer layer of a tooth.",
      },
      lt: {
        question: "Kaip vadinamas kietas baltas išorinis danties sluoksnis?",
        correct: "Emalis",
        distractors: ["Dentinas", "Pulpa", "Šaknis", "Dantenos", "Vainikas"],
        explanation: "Emalis — kietas išorinis danties sluoksnis.",
      },
    },
  },
  {
    id: "bod_me_029",
    category: "body",
    subTheme: "bones",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Humerus is the upper arm bone",
    emoji: "💪",
    translations: {
      en: {
        question: "What is the bone of the upper arm called?",
        correct: "Humerus",
        distractors: ["Femur", "Radius", "Ulna", "Tibia", "Clavicle"],
        explanation: "The upper arm bone is the humerus.",
      },
      lt: {
        question: "Kaip vadinamas žasto kaulas?",
        correct: "Žastikaulis",
        distractors: ["Šlaunikaulis", "Stipinkaulis", "Alkūnkaulis", "Blauzdikaulis", "Raktikaulis"],
        explanation: "Viršutinės rankos kaulas — žastikaulis.",
      },
    },
  },
  {
    id: "bod_me_030",
    category: "body",
    subTheme: "systems",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Circulatory system: heart and vessels",
    emoji: "❤️",
    translations: {
      en: {
        question: "Which body system includes the heart and blood vessels?",
        correct: "Circulatory system",
        distractors: ["Digestive system", "Nervous system", "Respiratory system", "Skeletal system", "Muscular system"],
        explanation: "The circulatory system moves blood around the body.",
      },
      lt: {
        question: "Kuri kūno sistema apima širdį ir kraujagysles?",
        correct: "Kraujotakos sistema",
        distractors: ["Virškinimo sistema", "Nervų sistema", "Kvėpavimo sistema", "Skeleto sistema", "Raumenų sistema"],
        explanation: "Kraujotakos sistema varinėja kraują po kūną.",
      },
    },
  },
  {
    id: "bod_su_016",
    category: "body",
    subTheme: "organs",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Hypothalamus regulates temperature and hunger",
    emoji: "🧠",
    translations: {
      en: {
        question: "Which brain part regulates temperature, hunger and thirst?",
        correct: "Hypothalamus",
        distractors: ["Cerebellum", "Hippocampus", "Amygdala", "Medulla", "Pituitary"],
        explanation: "The hypothalamus controls temperature, hunger and thirst.",
      },
      lt: {
        question: "Kuri smegenų dalis reguliuoja temperatūrą, alkį ir troškulį?",
        correct: "Pagumburis",
        distractors: ["Smegenėlės", "Hipokampas", "Migdolinis kūnas", "Pailgosios smegenys", "Hipofizė"],
        explanation: "Pagumburis valdo temperatūrą, alkį ir troškulį.",
      },
    },
  },
  {
    id: "bod_su_017",
    category: "body",
    subTheme: "systems",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "12 pairs of cranial nerves",
    emoji: "🧠",
    translations: {
      en: {
        question: "How many pairs of cranial nerves do humans have?",
        correct: "12",
        distractors: ["10", "8", "14", "24", "31"],
        explanation: "Humans have 12 pairs of cranial nerves.",
      },
      lt: {
        question: "Kiek porų galvinių nervų turi žmogus?",
        correct: "12",
        distractors: ["10", "8", "14", "24", "31"],
        explanation: "Žmogus turi 12 porų galvinių nervų.",
      },
    },
  },
  {
    id: "bod_su_018",
    category: "body",
    subTheme: "bones",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Scapula is the shoulder blade",
    emoji: "🦴",
    translations: {
      en: {
        question: "What is the medical name for the shoulder blade?",
        correct: "Scapula",
        distractors: ["Clavicle", "Sternum", "Humerus", "Pelvis", "Patella"],
        explanation: "The shoulder blade is called the scapula.",
      },
      lt: {
        question: "Koks medicininis mentės pavadinimas?",
        correct: "Mentė",
        distractors: ["Raktikaulis", "Krūtinkaulis", "Žastikaulis", "Dubuo", "Girnelė"],
        explanation: "Mentė lotyniškai — scapula.",
      },
    },
  },
  {
    id: "bod_su_019",
    category: "body",
    subTheme: "systems",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Arteries carry blood away from heart",
    emoji: "🩸",
    translations: {
      en: {
        question: "Which blood vessels carry blood away from the heart?",
        correct: "Arteries",
        distractors: ["Veins", "Capillaries", "Lymph vessels", "Venules", "Ducts"],
        explanation: "Arteries carry blood away from the heart.",
      },
      lt: {
        question: "Kurios kraujagyslės neša kraują nuo širdies?",
        correct: "Arterijos",
        distractors: ["Venos", "Kapiliarai", "Limfagyslės", "Venulės", "Latakai"],
        explanation: "Arterijos neša kraują nuo širdies.",
      },
    },
  },
  {
    id: "bod_su_020",
    category: "body",
    subTheme: "systems",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Gas exchange happens in capillaries",
    emoji: "🫁",
    translations: {
      en: {
        question: "In which tiny vessels do oxygen and CO2 exchange happen?",
        correct: "Capillaries",
        distractors: ["Arteries", "Veins", "Aorta", "Venules", "Lymphatics"],
        explanation: "Gas exchange occurs across thin capillary walls.",
      },
      lt: {
        question: "Kuriose mažose kraujagyslėse vyksta deguonies ir CO2 mainai?",
        correct: "Kapiliaruose",
        distractors: ["Arterijose", "Venose", "Aortoje", "Venulėse", "Limfagyslėse"],
        explanation: "Dujų mainai vyksta per plonas kapiliarų sieneles.",
      },
    },
  },
  {
    id: "bod_su_021",
    category: "body",
    subTheme: "organs",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Spleen filters blood, stores white cells",
    emoji: "🩸",
    translations: {
      en: {
        question: "Which organ filters blood and helps the immune system?",
        correct: "Spleen",
        distractors: ["Liver", "Kidney", "Pancreas", "Thymus", "Gallbladder"],
        explanation: "The spleen filters blood and supports immunity.",
      },
      lt: {
        question: "Kuris organas filtruoja kraują ir padeda imuninei sistemai?",
        correct: "Blužnis",
        distractors: ["Kepenys", "Inkstas", "Kasa", "Užkrūčio liauka", "Tulžies pūslė"],
        explanation: "Blužnis filtruoja kraują ir palaiko imunitetą.",
      },
    },
  },
  {
    id: "bod_su_022",
    category: "body",
    subTheme: "bones",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Newborns have about 300 bones",
    emoji: "👶",
    translations: {
      en: {
        question: "Roughly how many bones does a newborn baby have?",
        correct: "About 300",
        distractors: ["About 206", "About 250", "About 150", "About 100", "About 350"],
        explanation: "Babies have around 300 bones that later fuse to 206.",
      },
      lt: {
        question: "Maždaug kiek kaulų turi naujagimis?",
        correct: "Apie 300",
        distractors: ["Apie 206", "Apie 250", "Apie 150", "Apie 100", "Apie 350"],
        explanation: "Naujagimis turi apie 300 kaulų, vėliau jie suauga iki 206.",
      },
    },
  },
  {
    id: "bod_su_023",
    category: "body",
    subTheme: "senses",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Eustachian tube links middle ear to throat",
    emoji: "👂",
    translations: {
      en: {
        question: "The eustachian tube connects the middle ear to where?",
        correct: "The throat",
        distractors: ["The nose", "The eye", "The brain", "The sinus", "The stomach"],
        explanation: "The eustachian tube links the middle ear to the throat.",
      },
      lt: {
        question: "Klausomasis (Eustachijaus) vamzdelis jungia vidurinę ausį su kuo?",
        correct: "Gerkle",
        distractors: ["Nosimi", "Akimi", "Smegenimis", "Prienosiu", "Skrandžiu"],
        explanation: "Šis vamzdelis jungia vidurinę ausį su gerkle.",
      },
    },
  },
  {
    id: "bod_su_024",
    category: "body",
    subTheme: "organs",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Stomach uses hydrochloric acid",
    emoji: "🧪",
    translations: {
      en: {
        question: "Which acid in the stomach helps break down food?",
        correct: "Hydrochloric acid",
        distractors: ["Sulfuric acid", "Citric acid", "Lactic acid", "Acetic acid", "Nitric acid"],
        explanation: "The stomach uses hydrochloric acid to digest food.",
      },
      lt: {
        question: "Kuri rūgštis skrandyje padeda skaidyti maistą?",
        correct: "Druskos rūgštis",
        distractors: ["Sieros rūgštis", "Citrinų rūgštis", "Pieno rūgštis", "Acto rūgštis", "Azoto rūgštis"],
        explanation: "Skrandis maistą virškina druskos rūgštimi.",
      },
    },
  },
  {
    id: "bod_su_025",
    category: "body",
    subTheme: "bones",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Humans have 7 cervical vertebrae",
    emoji: "🦴",
    translations: {
      en: {
        question: "How many neck (cervical) vertebrae do humans have?",
        correct: "7",
        distractors: ["5", "12", "9", "10", "8"],
        explanation: "Humans, like most mammals, have 7 neck vertebrae.",
      },
      lt: {
        question: "Kiek kaklo slankstelių turi žmogus?",
        correct: "7",
        distractors: ["5", "12", "9", "10", "8"],
        explanation: "Žmogus, kaip ir dauguma žinduolių, turi 7 kaklo slankstelius.",
      },
    },
  },
  {
    id: "bod_su_026",
    category: "body",
    subTheme: "systems",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "O negative is universal donor",
    emoji: "🩸",
    translations: {
      en: {
        question: "Which blood type is the universal donor?",
        correct: "O negative",
        distractors: ["AB positive", "A positive", "B negative", "O positive", "AB negative"],
        explanation: "O negative can be given to almost anyone.",
      },
      lt: {
        question: "Kuri kraujo grupė yra universalus donoras?",
        correct: "O neigiama",
        distractors: ["AB teigiama", "A teigiama", "B neigiama", "O teigiama", "AB neigiama"],
        explanation: "O neigiamą kraują galima perpilti beveik visiems.",
      },
    },
  },
  {
    id: "bod_su_027",
    category: "body",
    subTheme: "organs",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Hippocampus forms new memories",
    emoji: "🧠",
    translations: {
      en: {
        question: "Which brain part is key to forming new memories?",
        correct: "Hippocampus",
        distractors: ["Cerebellum", "Amygdala", "Cerebrum", "Brainstem", "Thalamus"],
        explanation: "The hippocampus helps form new long-term memories.",
      },
      lt: {
        question: "Kuri smegenų dalis svarbiausia formuojant naujus prisiminimus?",
        correct: "Hipokampas",
        distractors: ["Smegenėlės", "Migdolinis kūnas", "Didžiosios smegenys", "Smegenų kamienas", "Talamas"],
        explanation: "Hipokampas padeda formuoti naujus ilgalaikius prisiminimus.",
      },
    },
  },
  {
    id: "bod_su_028",
    category: "body",
    subTheme: "systems",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Erythrocytes are red blood cells",
    emoji: "🩸",
    translations: {
      en: {
        question: "What is the medical name for red blood cells?",
        correct: "Erythrocytes",
        distractors: ["Leukocytes", "Platelets", "Lymphocytes", "Neutrophils", "Plasma"],
        explanation: "Red blood cells are called erythrocytes.",
      },
      lt: {
        question: "Koks medicininis raudonųjų kraujo kūnelių pavadinimas?",
        correct: "Eritrocitai",
        distractors: ["Leukocitai", "Trombocitai", "Limfocitai", "Neutrofilai", "Plazma"],
        explanation: "Raudonieji kraujo kūneliai vadinami eritrocitais.",
      },
    },
  },
  {
    id: "bod_su_029",
    category: "body",
    subTheme: "bones",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Mandible is the lower jaw bone",
    emoji: "🦷",
    translations: {
      en: {
        question: "Which bone forms the lower jaw?",
        correct: "Mandible",
        distractors: ["Maxilla", "Zygomatic", "Temporal", "Frontal", "Hyoid"],
        explanation: "The mandible is the movable lower jaw bone.",
      },
      lt: {
        question: "Kuris kaulas sudaro apatinį žandikaulį?",
        correct: "Apatinis žandikaulis",
        distractors: ["Viršutinis žandikaulis", "Skruostikaulis", "Smilkinkaulis", "Kaktikaulis", "Poliežuvinis kaulas"],
        explanation: "Apatinis žandikaulis (mandibula) yra judantis.",
      },
    },
  },
  {
    id: "bod_su_030",
    category: "body",
    subTheme: "systems",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Vena cava is the largest vein",
    emoji: "🩸",
    translations: {
      en: {
        question: "What is the largest vein returning blood to the heart?",
        correct: "Vena cava",
        distractors: ["Aorta", "Pulmonary artery", "Carotid", "Jugular", "Femoral artery"],
        explanation: "The vena cava returns blood to the heart.",
      },
      lt: {
        question: "Kaip vadinama didžiausia vena, grąžinanti kraują į širdį?",
        correct: "Tuščioji vena",
        distractors: ["Aorta", "Plaučių arterija", "Miego arterija", "Jungo vena", "Šlaunies arterija"],
        explanation: "Tuščioji vena grąžina kraują į širdį.",
      },
    },
  },
  {
    id: "bod_ek_016",
    category: "body",
    subTheme: "systems",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "B cells produce antibodies",
    emoji: "🦠",
    translations: {
      en: {
        question: "Which white blood cells produce antibodies?",
        correct: "B lymphocytes",
        distractors: ["T cells", "Neutrophils", "Macrophages", "Platelets", "Eosinophils"],
        explanation: "B lymphocytes (B cells) make antibodies.",
      },
      lt: {
        question: "Kurie baltieji kraujo kūneliai gamina antikūnus?",
        correct: "B limfocitai",
        distractors: ["T ląstelės", "Neutrofilai", "Makrofagai", "Trombocitai", "Eozinofilai"],
        explanation: "B limfocitai (B ląstelės) gamina antikūnus.",
      },
    },
  },
  {
    id: "bod_ek_017",
    category: "body",
    subTheme: "systems",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Oligodendrocytes myelinate CNS axons",
    emoji: "🧠",
    translations: {
      en: {
        question: "In the brain, which cells make the myelin that speeds nerve signals?",
        correct: "Oligodendrocytes",
        distractors: ["Neurons", "Astrocytes", "Microglia", "Schwann cells", "Ependymal cells"],
        explanation: "Oligodendrocytes myelinate axons in the brain.",
      },
      lt: {
        question: "Smegenyse kurios ląstelės gamina mieliną, spartinantį nervų signalus?",
        correct: "Oligodendrocitai",
        distractors: ["Neuronai", "Astrocitai", "Mikroglija", "Švano ląstelės", "Ependiminės ląstelės"],
        explanation: "Oligodendrocitai mielinizuoja smegenų aksonus.",
      },
    },
  },
  {
    id: "bod_ek_018",
    category: "body",
    subTheme: "organs",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Corpus callosum links brain hemispheres",
    emoji: "🧠",
    translations: {
      en: {
        question: "Which structure connects the two hemispheres of the brain?",
        correct: "Corpus callosum",
        distractors: ["Cerebellum", "Thalamus", "Brainstem", "Hippocampus", "Pons"],
        explanation: "The corpus callosum joins the brain's two halves.",
      },
      lt: {
        question: "Kuri struktūra jungia abu smegenų pusrutulius?",
        correct: "Rumbuotasis kūnas",
        distractors: ["Smegenėlės", "Talamas", "Smegenų kamienas", "Hipokampas", "Tiltas"],
        explanation: "Rumbuotasis kūnas (corpus callosum) jungia smegenų puses.",
      },
    },
  },
  {
    id: "bod_ek_019",
    category: "body",
    subTheme: "systems",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "DNA replicates in S phase",
    emoji: "🧬",
    translations: {
      en: {
        question: "During which phase of the cell cycle does DNA replicate?",
        correct: "S phase",
        distractors: ["G1 phase", "G2 phase", "M phase", "Prophase", "Telophase"],
        explanation: "DNA is copied during the S (synthesis) phase.",
      },
      lt: {
        question: "Kurioje ląstelės ciklo fazėje vyksta DNR replikacija?",
        correct: "S fazė",
        distractors: ["G1 fazė", "G2 fazė", "M fazė", "Profazė", "Telofazė"],
        explanation: "DNR kopijuojama S (sintezės) fazėje.",
      },
    },
  },
  {
    id: "bod_ek_020",
    category: "body",
    subTheme: "organs",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Glomerulus is the kidney's filter ball",
    emoji: "🫘",
    translations: {
      en: {
        question: "What is the ball of capillaries in a kidney's filter called?",
        correct: "Glomerulus",
        distractors: ["Tubule", "Loop of Henle", "Ureter", "Cortex", "Medulla"],
        explanation: "The glomerulus filters blood inside each nephron.",
      },
      lt: {
        question: "Kaip vadinamas kapiliarų kamuoliukas inksto filtre?",
        correct: "Glomerulas",
        distractors: ["Kanalėlis", "Henlės kilpa", "Šlapimtakis", "Žievė", "Šerdis"],
        explanation: "Glomerulas filtruoja kraują kiekviename nefrone.",
      },
    },
  },
  {
    id: "bod_ek_021",
    category: "body",
    subTheme: "systems",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Keratin in hair, nails, skin",
    emoji: "💇",
    translations: {
      en: {
        question: "Which protein forms hair, nails and the skin's outer layer?",
        correct: "Keratin",
        distractors: ["Collagen", "Elastin", "Myosin", "Albumin", "Fibrin"],
        explanation: "Keratin is the tough protein in hair, nails and skin.",
      },
      lt: {
        question: "Kuris baltymas sudaro plaukus, nagus ir išorinį odos sluoksnį?",
        correct: "Keratinas",
        distractors: ["Kolagenas", "Elastinas", "Miozinas", "Albuminas", "Fibrinas"],
        explanation: "Keratinas — tvirtas plaukų, nagų ir odos baltymas.",
      },
    },
  },
  {
    id: "bod_ek_022",
    category: "body",
    subTheme: "systems",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Calcium triggers muscle contraction",
    emoji: "💪",
    translations: {
      en: {
        question: "Which ion is essential to trigger muscle contraction?",
        correct: "Calcium",
        distractors: ["Sodium", "Potassium", "Iron", "Magnesium", "Chloride"],
        explanation: "Calcium ions trigger muscle fibers to contract.",
      },
      lt: {
        question: "Kuris jonas būtinas raumens susitraukimui sukelti?",
        correct: "Kalcis",
        distractors: ["Natris", "Kalis", "Geležis", "Magnis", "Chloridas"],
        explanation: "Kalcio jonai sukelia raumenų skaidulų susitraukimą.",
      },
    },
  },
  {
    id: "bod_ek_023",
    category: "body",
    subTheme: "organs",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "SA node sets heart rhythm",
    emoji: "❤️",
    translations: {
      en: {
        question: "Which node acts as the heart's natural pacemaker?",
        correct: "Sinoatrial node",
        distractors: ["AV node", "Bundle of His", "Purkinje fibers", "Aorta", "Septum"],
        explanation: "The sinoatrial (SA) node sets the heart's rhythm.",
      },
      lt: {
        question: "Kuris mazgas yra natūralus širdies ritmo vedlys?",
        correct: "Sinusinis mazgas",
        distractors: ["Prieširdžių mazgas", "Hiso pluoštas", "Purkinjės skaidulos", "Aorta", "Pertvara"],
        explanation: "Sinusinis mazgas nustato širdies ritmą.",
      },
    },
  },
  {
    id: "bod_ek_024",
    category: "body",
    subTheme: "organs",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Pineal gland makes melatonin",
    emoji: "🧠",
    translations: {
      en: {
        question: "Which gland makes melatonin to regulate sleep?",
        correct: "Pineal gland",
        distractors: ["Pituitary", "Thyroid", "Adrenal", "Hypothalamus", "Thymus"],
        explanation: "The pineal gland produces melatonin for sleep cycles.",
      },
      lt: {
        question: "Kuri liauka gamina melatoniną miegui reguliuoti?",
        correct: "Kankorėžinė liauka",
        distractors: ["Hipofizė", "Skydliaukė", "Antinksčiai", "Pagumburis", "Užkrūčio liauka"],
        explanation: "Kankorėžinė liauka gamina melatoniną miego ciklams.",
      },
    },
  },
  {
    id: "bod_ek_025",
    category: "body",
    subTheme: "systems",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Mature red blood cells lack a nucleus",
    emoji: "🩸",
    translations: {
      en: {
        question: "Which human cells have no nucleus when mature?",
        correct: "Red blood cells",
        distractors: ["White blood cells", "Neurons", "Liver cells", "Muscle cells", "Skin cells"],
        explanation: "Mature red blood cells lose their nucleus.",
      },
      lt: {
        question: "Kurios žmogaus ląstelės subrendusios neturi branduolio?",
        correct: "Raudonieji kraujo kūneliai",
        distractors: ["Baltieji kraujo kūneliai", "Neuronai", "Kepenų ląstelės", "Raumenų ląstelės", "Odos ląstelės"],
        explanation: "Subrendę raudonieji kraujo kūneliai netenka branduolio.",
      },
    },
  },
  {
    id: "bod_ek_026",
    category: "body",
    subTheme: "systems",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Vitamin K needed for clotting",
    emoji: "🩸",
    translations: {
      en: {
        question: "Which vitamin is essential for blood clotting?",
        correct: "Vitamin K",
        distractors: ["Vitamin C", "Vitamin D", "Vitamin A", "Vitamin B12", "Vitamin E"],
        explanation: "Vitamin K is needed to form blood clots.",
      },
      lt: {
        question: "Kuris vitaminas būtinas kraujo krešėjimui?",
        correct: "Vitaminas K",
        distractors: ["Vitaminas C", "Vitaminas D", "Vitaminas A", "Vitaminas B12", "Vitaminas E"],
        explanation: "Vitaminas K reikalingas kraujo krešuliams formuotis.",
      },
    },
  },
  {
    id: "bod_ek_027",
    category: "body",
    subTheme: "systems",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Sarcomere is the contractile unit of muscle",
    emoji: "💪",
    translations: {
      en: {
        question: "What is the smallest contracting unit of a muscle called?",
        correct: "Sarcomere",
        distractors: ["Myofibril", "Tendon", "Fascicle", "Motor unit", "Actin"],
        explanation: "The sarcomere is the basic contracting unit of muscle.",
      },
      lt: {
        question: "Kaip vadinamas mažiausias susitraukiantis raumens vienetas?",
        correct: "Sarkomeras",
        distractors: ["Miofibrilė", "Sausgyslė", "Pluoštelis", "Motorinis vienetas", "Aktinas"],
        explanation: "Sarkomeras — pagrindinis susitraukiantis raumens vienetas.",
      },
    },
  },
  {
    id: "bod_ek_028",
    category: "body",
    subTheme: "systems",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Dendrites receive nerve signals",
    emoji: "🧠",
    translations: {
      en: {
        question: "Which part of a neuron receives incoming signals?",
        correct: "Dendrites",
        distractors: ["Axon", "Myelin", "Synapse", "Soma", "Node"],
        explanation: "Dendrites receive signals from other neurons.",
      },
      lt: {
        question: "Kuri neurono dalis priima ateinančius signalus?",
        correct: "Dendritai",
        distractors: ["Aksonas", "Mielinas", "Sinapsė", "Soma", "Mazgas"],
        explanation: "Dendritai priima signalus iš kitų neuronų.",
      },
    },
  },
  {
    id: "bod_ek_029",
    category: "body",
    subTheme: "systems",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Fibrinogen becomes fibrin in clots",
    emoji: "🩸",
    translations: {
      en: {
        question: "Which blood protein turns into fibrin to form clots?",
        correct: "Fibrinogen",
        distractors: ["Hemoglobin", "Albumin", "Globulin", "Collagen", "Keratin"],
        explanation: "Fibrinogen converts to fibrin to make blood clots.",
      },
      lt: {
        question: "Kuris kraujo baltymas virsta fibrinu krešuliams formuoti?",
        correct: "Fibrinogenas",
        distractors: ["Hemoglobinas", "Albuminas", "Globulinas", "Kolagenas", "Keratinas"],
        explanation: "Fibrinogenas virsta fibrinu ir formuoja kraujo krešulius.",
      },
    },
  },
  {
    id: "bod_ek_030",
    category: "body",
    subTheme: "systems",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Average adult has about 5 liters of blood",
    emoji: "🩸",
    translations: {
      en: {
        question: "Roughly how many liters of blood does an average adult have?",
        correct: "About 5 liters",
        distractors: ["About 2 liters", "About 8 liters", "About 10 liters", "About 3 liters", "About 12 liters"],
        explanation: "An average adult has about 5 liters of blood.",
      },
      lt: {
        question: "Maždaug kiek litrų kraujo turi vidutinis suaugęs žmogus?",
        correct: "Apie 5 litrus",
        distractors: ["Apie 2 litrus", "Apie 8 litrus", "Apie 10 litrų", "Apie 3 litrus", "Apie 12 litrų"],
        explanation: "Vidutinis suaugęs žmogus turi apie 5 litrus kraujo.",
      },
    },
  },
];
