/**
 * bodyContent — „Žmogaus kūnas” trivijos klausimai (EN + LT).
 *
 * Po 15 klausimų kiekvienam lygiui (lengvas/vidutinis/sunkus/ekstremalus) = 60.
 * Temos: organai, skeletas, kraujas, jutimai, ląstelės — grynas patikrintas
 * anatomijos ir fiziologijos mokslas.
 *
 * TAISYKLĖS (Manifestas):
 *   - 1 teisingas + 5 distractors; visi 6 variantai VISOSE kalbose ≤46 simbolių;
 *   - faktai 100% patikrinti (sourceVerified); neutralu (jokios politikos/religijos);
 *   - LT vidinės kabutės tik „...” (ne ASCII "); detalės — į explanation, ne į variantą.
 *
 * Formatas — žr. triviaTypes.ts (TriviaQuestion). category visada "body".
 */

import { TriviaQuestion } from "./triviaTypes";

export const BODY_QUESTIONS: TriviaQuestion[] = [
  // ======================= LENGVAS (Easy) =======================
  {
    id: "bod_le_001",
    category: "body",
    subTheme: "organs",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Anatomy (heart pumps blood)",
    emoji: "❤️",
    translations: {
      en: {
        question: "Which organ pumps blood around the body?",
        correct: "Heart",
        distractors: ["Liver", "Lungs", "Kidney", "Stomach", "Brain"],
        explanation: "The heart pumps blood through the body.",
      },
      lt: {
        question: "Kuris organas pumpuoja kraują po kūną?",
        correct: "Širdis",
        distractors: ["Kepenys", "Plaučiai", "Inkstas", "Skrandis", "Smegenys"],
        explanation: "Širdis pumpuoja kraują po visą kūną.",
      },
    },
  },
  {
    id: "bod_le_002",
    category: "body",
    subTheme: "organs",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Anatomy (lungs for breathing)",
    emoji: "🫁",
    translations: {
      en: {
        question: "Which organs do you use to breathe?",
        correct: "Lungs",
        distractors: ["Heart", "Liver", "Kidneys", "Stomach", "Bladder"],
        explanation: "The lungs take in air so we can breathe.",
      },
      lt: {
        question: "Kuriais organais kvėpuojame?",
        correct: "Plaučiais",
        distractors: ["Širdimi", "Kepenimis", "Inkstais", "Skrandžiu", "Šlapimo pūsle"],
        explanation: "Plaučiai įkvepia orą, kad galėtume kvėpuoti.",
      },
    },
  },
  {
    id: "bod_le_003",
    category: "body",
    subTheme: "senses",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Senses (eyes for sight)",
    emoji: "👁️",
    translations: {
      en: {
        question: "Which body part do you use to see?",
        correct: "Eyes",
        distractors: ["Ears", "Nose", "Tongue", "Hands", "Feet"],
        explanation: "We see the world through our eyes.",
      },
      lt: {
        question: "Kuria kūno dalimi matome?",
        correct: "Akimis",
        distractors: ["Ausimis", "Nosimi", "Liežuviu", "Rankomis", "Kojomis"],
        explanation: "Pasaulį matome akimis.",
      },
    },
  },
  {
    id: "bod_le_004",
    category: "body",
    subTheme: "skeleton",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Anatomy (skull protects brain)",
    emoji: "💀",
    translations: {
      en: {
        question: "Which bones protect the brain?",
        correct: "Skull",
        distractors: ["Ribs", "Spine", "Hip", "Jaw only", "Knee"],
        explanation: "The skull is a bony case protecting the brain.",
      },
      lt: {
        question: "Kurie kaulai saugo smegenis?",
        correct: "Kaukolė",
        distractors: ["Šonkauliai", "Stuburas", "Klubas", "Tik žandikaulis", "Kelis"],
        explanation: "Kaukolė — kaulinis dangtis, saugantis smegenis.",
      },
    },
  },
  {
    id: "bod_le_005",
    category: "body",
    subTheme: "senses",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Senses (ears for hearing)",
    emoji: "👂",
    translations: {
      en: {
        question: "Which body part do you use to hear?",
        correct: "Ears",
        distractors: ["Eyes", "Nose", "Mouth", "Hands", "Skin"],
        explanation: "We hear sounds with our ears.",
      },
      lt: {
        question: "Kuria kūno dalimi girdime?",
        correct: "Ausimis",
        distractors: ["Akimis", "Nosimi", "Burna", "Rankomis", "Oda"],
        explanation: "Garsus girdime ausimis.",
      },
    },
  },
  {
    id: "bod_le_006",
    category: "body",
    subTheme: "anatomy",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Anatomy (teeth for chewing)",
    emoji: "🦷",
    translations: {
      en: {
        question: "What do we use to chew food?",
        correct: "Teeth",
        distractors: ["Nails", "Lips", "Ears", "Hair", "Eyebrows"],
        explanation: "Teeth break food into smaller pieces.",
      },
      lt: {
        question: "Kuo kramtome maistą?",
        correct: "Dantimis",
        distractors: ["Nagais", "Lūpomis", "Ausimis", "Plaukais", "Antakiais"],
        explanation: "Dantys susmulkina maistą į mažesnius gabalėlius.",
      },
    },
  },
  {
    id: "bod_le_007",
    category: "body",
    subTheme: "anatomy",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Anatomy (largest organ is skin)",
    emoji: "🖐️",
    translations: {
      en: {
        question: "What is the body's largest organ?",
        correct: "Skin",
        distractors: ["Liver", "Heart", "Brain", "Lungs", "Stomach"],
        explanation: "Skin is the largest organ of the body.",
      },
      lt: {
        question: "Koks didžiausias kūno organas?",
        correct: "Oda",
        distractors: ["Kepenys", "Širdis", "Smegenys", "Plaučiai", "Skrandis"],
        explanation: "Oda — didžiausias kūno organas.",
      },
    },
  },
  {
    id: "bod_le_008",
    category: "body",
    subTheme: "anatomy",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Anatomy (blood is red)",
    emoji: "🩸",
    translations: {
      en: {
        question: "What color is human blood?",
        correct: "Red",
        distractors: ["Blue", "Green", "Yellow", "Purple", "Clear"],
        explanation: "Human blood is red due to hemoglobin.",
      },
      lt: {
        question: "Kokios spalvos yra žmogaus kraujas?",
        correct: "Raudonas",
        distractors: ["Mėlynas", "Žalias", "Geltonas", "Violetinis", "Skaidrus"],
        explanation: "Žmogaus kraujas raudonas dėl hemoglobino.",
      },
    },
  },
  {
    id: "bod_le_009",
    category: "body",
    subTheme: "anatomy",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Anatomy (fingers count, 5 per hand)",
    emoji: "✋",
    translations: {
      en: {
        question: "How many fingers are on one human hand?",
        correct: "5",
        distractors: ["4", "6", "3", "7", "10"],
        explanation: "One hand has five fingers, including the thumb.",
      },
      lt: {
        question: "Kiek pirštų yra ant vienos žmogaus rankos?",
        correct: "5",
        distractors: ["4", "6", "3", "7", "10"],
        explanation: "Ant vienos rankos penki pirštai su nykščiu.",
      },
    },
  },
  {
    id: "bod_le_010",
    category: "body",
    subTheme: "senses",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Senses (nose for smell)",
    emoji: "👃",
    translations: {
      en: {
        question: "Which body part do you use to smell?",
        correct: "Nose",
        distractors: ["Eyes", "Ears", "Hands", "Knees", "Elbows"],
        explanation: "We smell scents with our nose.",
      },
      lt: {
        question: "Kuria kūno dalimi užuodžiame kvapus?",
        correct: "Nosimi",
        distractors: ["Akimis", "Ausimis", "Rankomis", "Keliais", "Alkūnėmis"],
        explanation: "Kvapus užuodžiame nosimi.",
      },
    },
  },
  {
    id: "bod_le_011",
    category: "body",
    subTheme: "organs",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Anatomy (brain controls body)",
    emoji: "🧠",
    translations: {
      en: {
        question: "Which organ controls thinking and the body?",
        correct: "Brain",
        distractors: ["Heart", "Liver", "Lungs", "Stomach", "Kidney"],
        explanation: "The brain controls thoughts and body functions.",
      },
      lt: {
        question: "Kuris organas valdo mąstymą ir kūną?",
        correct: "Smegenys",
        distractors: ["Širdis", "Kepenys", "Plaučiai", "Skrandis", "Inkstas"],
        explanation: "Smegenys valdo mintis ir kūno funkcijas.",
      },
    },
  },
  {
    id: "bod_le_012",
    category: "body",
    subTheme: "senses",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Senses (tongue for taste)",
    emoji: "👅",
    translations: {
      en: {
        question: "Which body part lets you taste food?",
        correct: "Tongue",
        distractors: ["Nose", "Ear", "Eye", "Finger", "Cheek"],
        explanation: "Taste buds on the tongue sense flavors.",
      },
      lt: {
        question: "Kuria kūno dalimi jaučiame maisto skonį?",
        correct: "Liežuviu",
        distractors: ["Nosimi", "Ausimi", "Akimi", "Pirštu", "Skruostu"],
        explanation: "Skonio receptoriai liežuvyje jaučia skonius.",
      },
    },
  },
  {
    id: "bod_le_013",
    category: "body",
    subTheme: "skeleton",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Anatomy (bones make skeleton)",
    emoji: "🦴",
    translations: {
      en: {
        question: "What is the framework of bones in the body called?",
        correct: "Skeleton",
        distractors: ["Muscle", "Nerve", "Vessel", "Tendon", "Gland"],
        explanation: "All the bones together form the skeleton.",
      },
      lt: {
        question: "Kaip vadinamas kūno kaulų karkasas?",
        correct: "Skeletas",
        distractors: ["Raumuo", "Nervas", "Kraujagyslė", "Sausgyslė", "Liauka"],
        explanation: "Visi kaulai kartu sudaro skeletą.",
      },
    },
  },
  {
    id: "bod_le_014",
    category: "body",
    subTheme: "anatomy",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Anatomy (muscles move body)",
    emoji: "💪",
    translations: {
      en: {
        question: "What lets your body move and lift things?",
        correct: "Muscles",
        distractors: ["Bones only", "Skin", "Hair", "Nails", "Blood"],
        explanation: "Muscles contract to move the body.",
      },
      lt: {
        question: "Kas leidžia kūnui judėti ir kelti daiktus?",
        correct: "Raumenys",
        distractors: ["Tik kaulai", "Oda", "Plaukai", "Nagai", "Kraujas"],
        explanation: "Raumenys susitraukdami judina kūną.",
      },
    },
  },
  {
    id: "bod_le_015",
    category: "body",
    subTheme: "anatomy",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Anatomy (hair grows on head)",
    emoji: "💇",
    translations: {
      en: {
        question: "Where does hair grow most on people?",
        correct: "Head",
        distractors: ["Palms", "Soles", "Tongue", "Teeth", "Eyeballs"],
        explanation: "Hair grows thickest on the head.",
      },
      lt: {
        question: "Kur žmonėms auga daugiausia plaukų?",
        correct: "Ant galvos",
        distractors: ["Delnuose", "Paduose", "Ant liežuvio", "Ant dantų", "Ant akių"],
        explanation: "Tankiausiai plaukai auga ant galvos.",
      },
    },
  },

  // ======================= VIDUTINIS (Medium) =======================
  {
    id: "bod_me_001",
    category: "body",
    subTheme: "skeleton",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (206 bones in adult)",
    emoji: "🦴",
    translations: {
      en: {
        question: "About how many bones are in an adult human body?",
        correct: "206",
        distractors: ["106", "150", "300", "250", "180"],
        explanation: "An adult human has about 206 bones.",
      },
      lt: {
        question: "Maždaug kiek kaulų yra suaugusio žmogaus kūne?",
        correct: "206",
        distractors: ["106", "150", "300", "250", "180"],
        explanation: "Suaugęs žmogus turi maždaug 206 kaulus.",
      },
    },
  },
  {
    id: "bod_me_002",
    category: "body",
    subTheme: "organs",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (kidneys filter blood)",
    emoji: "🫘",
    translations: {
      en: {
        question: "Which organs filter waste from the blood?",
        correct: "Kidneys",
        distractors: ["Lungs", "Heart", "Brain", "Spleen", "Pancreas"],
        explanation: "Kidneys filter waste and make urine.",
      },
      lt: {
        question: "Kurie organai filtruoja atliekas iš kraujo?",
        correct: "Inkstai",
        distractors: ["Plaučiai", "Širdis", "Smegenys", "Blužnis", "Kasa"],
        explanation: "Inkstai filtruoja atliekas ir gamina šlapimą.",
      },
    },
  },
  {
    id: "bod_me_003",
    category: "body",
    subTheme: "anatomy",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (red cells carry oxygen)",
    emoji: "🩸",
    translations: {
      en: {
        question: "Which blood cells carry oxygen?",
        correct: "Red blood cells",
        distractors: ["White blood cells", "Platelets", "Nerve cells", "Skin cells", "Fat cells"],
        explanation: "Red blood cells carry oxygen with hemoglobin.",
      },
      lt: {
        question: "Kurios kraujo ląstelės neša deguonį?",
        correct: "Raudonieji kraujo kūneliai",
        distractors: ["Baltieji kūneliai", "Trombocitai", "Nervų ląstelės", "Odos ląstelės", "Riebalų ląstelės"],
        explanation: "Raudonieji kūneliai hemoglobinu neša deguonį.",
      },
    },
  },
  {
    id: "bod_me_004",
    category: "body",
    subTheme: "organs",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (stomach digests food)",
    emoji: "🍽️",
    translations: {
      en: {
        question: "Which organ uses acid to digest food?",
        correct: "Stomach",
        distractors: ["Heart", "Lungs", "Brain", "Kidney", "Bladder"],
        explanation: "The stomach uses acid to break down food.",
      },
      lt: {
        question: "Kuris organas rūgštimi virškina maistą?",
        correct: "Skrandis",
        distractors: ["Širdis", "Plaučiai", "Smegenys", "Inkstas", "Šlapimo pūslė"],
        explanation: "Skrandis rūgštimi skaido maistą.",
      },
    },
  },
  {
    id: "bod_me_005",
    category: "body",
    subTheme: "anatomy",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (adult body about 60% water)",
    emoji: "💧",
    translations: {
      en: {
        question: "About what fraction of the adult body is water?",
        correct: "About 60%",
        distractors: ["About 10%", "About 25%", "About 90%", "About 40%", "About 80%"],
        explanation: "An adult body is roughly 60 percent water.",
      },
      lt: {
        question: "Maždaug kiek suaugusio kūno sudaro vanduo?",
        correct: "Apie 60%",
        distractors: ["Apie 10%", "Apie 25%", "Apie 90%", "Apie 40%", "Apie 80%"],
        explanation: "Suaugęs kūnas yra maždaug 60 procentų vandens.",
      },
    },
  },
  {
    id: "bod_me_006",
    category: "body",
    subTheme: "anatomy",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (biceps in the arm)",
    emoji: "💪",
    translations: {
      en: {
        question: "The biceps muscle is found in which body part?",
        correct: "Arm",
        distractors: ["Leg", "Back", "Neck", "Chest", "Foot"],
        explanation: "The biceps is a muscle in the upper arm.",
      },
      lt: {
        question: "Kurioje kūno dalyje yra dvigalvis (biceps) raumuo?",
        correct: "Rankoje",
        distractors: ["Kojoje", "Nugaroje", "Kakle", "Krūtinėje", "Pėdoje"],
        explanation: "Bicepsas — raumuo viršutinėje rankos dalyje.",
      },
    },
  },
  {
    id: "bod_me_007",
    category: "body",
    subTheme: "organs",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (liver processes nutrients)",
    emoji: "🫀",
    translations: {
      en: {
        question: "Which large organ helps clean the blood and store energy?",
        correct: "Liver",
        distractors: ["Heart", "Lung", "Bladder", "Eye", "Ear"],
        explanation: "The liver filters blood and stores energy.",
      },
      lt: {
        question: "Kuris didelis organas valo kraują ir kaupia energiją?",
        correct: "Kepenys",
        distractors: ["Širdis", "Plautis", "Šlapimo pūslė", "Akis", "Ausis"],
        explanation: "Kepenys filtruoja kraują ir kaupia energiją.",
      },
    },
  },
  {
    id: "bod_me_008",
    category: "body",
    subTheme: "anatomy",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (heart has four chambers)",
    emoji: "❤️",
    translations: {
      en: {
        question: "How many chambers does the human heart have?",
        correct: "4",
        distractors: ["2", "3", "5", "6", "1"],
        explanation: "The heart has four chambers.",
      },
      lt: {
        question: "Kiek kamerų turi žmogaus širdis?",
        correct: "4",
        distractors: ["2", "3", "5", "6", "1"],
        explanation: "Širdis turi keturias kameras.",
      },
    },
  },
  {
    id: "bod_me_009",
    category: "body",
    subTheme: "skeleton",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (ribs protect heart and lungs)",
    emoji: "🦴",
    translations: {
      en: {
        question: "Which bones form a cage protecting the heart and lungs?",
        correct: "Ribs",
        distractors: ["Skull", "Spine", "Pelvis", "Femur", "Jaw"],
        explanation: "The ribs form a cage around the heart and lungs.",
      },
      lt: {
        question: "Kurie kaulai sudaro narvą, saugantį širdį ir plaučius?",
        correct: "Šonkauliai",
        distractors: ["Kaukolė", "Stuburas", "Dubuo", "Šlaunikaulis", "Žandikaulis"],
        explanation: "Šonkauliai sudaro narvą aplink širdį ir plaučius.",
      },
    },
  },
  {
    id: "bod_me_010",
    category: "body",
    subTheme: "anatomy",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (lungs come in a pair)",
    emoji: "🫁",
    translations: {
      en: {
        question: "How many lungs does a person normally have?",
        correct: "2",
        distractors: ["1", "3", "4", "5", "6"],
        explanation: "People normally have two lungs.",
      },
      lt: {
        question: "Kiek plaučių paprastai turi žmogus?",
        correct: "2",
        distractors: ["1", "3", "4", "5", "6"],
        explanation: "Žmogus paprastai turi du plaučius.",
      },
    },
  },
  {
    id: "bod_me_011",
    category: "body",
    subTheme: "anatomy",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (skeletal muscle moves bones)",
    emoji: "🦵",
    translations: {
      en: {
        question: "What connects muscles to bones?",
        correct: "Tendons",
        distractors: ["Veins", "Nerves", "Arteries", "Glands", "Cartilage"],
        explanation: "Tendons attach muscles to bones.",
      },
      lt: {
        question: "Kas jungia raumenis prie kaulų?",
        correct: "Sausgyslės",
        distractors: ["Venos", "Nervai", "Arterijos", "Liaukos", "Kremzlė"],
        explanation: "Sausgyslės tvirtina raumenis prie kaulų.",
      },
    },
  },
  {
    id: "bod_me_012",
    category: "body",
    subTheme: "senses",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (eardrum in the ear)",
    emoji: "👂",
    translations: {
      en: {
        question: "The eardrum is part of which organ?",
        correct: "Ear",
        distractors: ["Eye", "Nose", "Throat", "Skin", "Tongue"],
        explanation: "The eardrum vibrates to help us hear.",
      },
      lt: {
        question: "Ausies būgnelis yra kurio organo dalis?",
        correct: "Ausies",
        distractors: ["Akies", "Nosies", "Gerklės", "Odos", "Liežuvio"],
        explanation: "Ausies būgnelis virpa ir padeda girdėti.",
      },
    },
  },
  {
    id: "bod_me_013",
    category: "body",
    subTheme: "anatomy",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (adult has 32 teeth)",
    emoji: "🦷",
    translations: {
      en: {
        question: "How many teeth does a typical adult have?",
        correct: "32",
        distractors: ["20", "24", "28", "36", "40"],
        explanation: "A full adult set is 32 teeth.",
      },
      lt: {
        question: "Kiek dantų paprastai turi suaugęs žmogus?",
        correct: "32",
        distractors: ["20", "24", "28", "36", "40"],
        explanation: "Pilnas suaugusio žmogaus rinkinys — 32 dantys.",
      },
    },
  },
  {
    id: "bod_me_014",
    category: "body",
    subTheme: "skeleton",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Anatomy (spine, vertebral column)",
    emoji: "🦴",
    translations: {
      en: {
        question: "What is the column of bones along the back called?",
        correct: "Spine",
        distractors: ["Rib", "Skull", "Pelvis", "Collarbone", "Kneecap"],
        explanation: "The spine is the column of bones in the back.",
      },
      lt: {
        question: "Kaip vadinamas kaulų stulpas išilgai nugaros?",
        correct: "Stuburas",
        distractors: ["Šonkaulis", "Kaukolė", "Dubuo", "Raktikaulis", "Girnelė"],
        explanation: "Stuburas — kaulų stulpas nugaroje.",
      },
    },
  },
  {
    id: "bod_me_015",
    category: "body",
    subTheme: "anatomy",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Physiology (resting heart rate ~60-100 bpm)",
    emoji: "💓",
    translations: {
      en: {
        question: "A resting adult heart beats roughly how many times a minute?",
        correct: "About 70",
        distractors: ["About 20", "About 150", "About 250", "About 10", "About 400"],
        explanation: "A resting adult heart beats about 60-100 times a minute.",
      },
      lt: {
        question: "Ramybės būsenoje suaugusiojo širdis plaka maždaug kiek kartų per minutę?",
        correct: "Apie 70",
        distractors: ["Apie 20", "Apie 150", "Apie 250", "Apie 10", "Apie 400"],
        explanation: "Ramybėje suaugusiojo širdis plaka apie 60-100 k./min.",
      },
    },
  },

  // ======================= SUNKUS (Hard) =======================
  {
    id: "bod_su_001",
    category: "body",
    subTheme: "anatomy",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Anatomy (femur is longest bone)",
    emoji: "🦴",
    translations: {
      en: {
        question: "What is the longest bone in the human body?",
        correct: "Femur",
        distractors: ["Tibia", "Humerus", "Spine", "Skull", "Rib"],
        explanation: "The femur, the thigh bone, is the longest bone.",
      },
      lt: {
        question: "Koks ilgiausias kaulas žmogaus kūne?",
        correct: "Šlaunikaulis",
        distractors: ["Blauzdikaulis", "Žastikaulis", "Stuburas", "Kaukolė", "Šonkaulis"],
        explanation: "Šlaunikaulis (femur) yra ilgiausias kūno kaulas.",
      },
    },
  },
  {
    id: "bod_su_002",
    category: "body",
    subTheme: "organs",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Anatomy (skin is largest organ; trap vs liver)",
    emoji: "🧬",
    translations: {
      en: {
        question: "What is the largest internal organ?",
        correct: "Liver",
        distractors: ["Heart", "Brain", "Kidney", "Spleen", "Pancreas"],
        explanation: "The liver is the largest internal organ.",
      },
      lt: {
        question: "Koks didžiausias vidaus organas?",
        correct: "Kepenys",
        distractors: ["Širdis", "Smegenys", "Inkstas", "Blužnis", "Kasa"],
        explanation: "Kepenys — didžiausias vidaus organas.",
      },
    },
  },
  {
    id: "bod_su_003",
    category: "body",
    subTheme: "anatomy",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Anatomy (stapes is smallest bone, in ear)",
    emoji: "👂",
    translations: {
      en: {
        question: "The smallest bone in the body is found in which organ?",
        correct: "Ear",
        distractors: ["Eye", "Nose", "Hand", "Foot", "Knee"],
        explanation: "The stapes, the smallest bone, is in the ear.",
      },
      lt: {
        question: "Mažiausias kūno kaulas yra kuriame organe?",
        correct: "Ausyje",
        distractors: ["Akyje", "Nosyje", "Plaštakoje", "Pėdoje", "Kelyje"],
        explanation: "Mažiausias kaulas, kilpelė (stapes), yra ausyje.",
      },
    },
  },
  {
    id: "bod_su_004",
    category: "body",
    subTheme: "physiology",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Anatomy (red cells made in bone marrow)",
    emoji: "🦴",
    translations: {
      en: {
        question: "Where are most blood cells produced?",
        correct: "Bone marrow",
        distractors: ["Liver", "Heart", "Spleen", "Kidney", "Lungs"],
        explanation: "Bone marrow produces most blood cells.",
      },
      lt: {
        question: "Kur gaminama dauguma kraujo ląstelių?",
        correct: "Kaulų čiulpuose",
        distractors: ["Kepenyse", "Širdyje", "Blužnyje", "Inkste", "Plaučiuose"],
        explanation: "Dauguma kraujo ląstelių gaminama kaulų čiulpuose.",
      },
    },
  },
  {
    id: "bod_su_005",
    category: "body",
    subTheme: "physiology",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Physiology (insulin from pancreas)",
    emoji: "🩺",
    translations: {
      en: {
        question: "Which organ produces the hormone insulin?",
        correct: "Pancreas",
        distractors: ["Liver", "Kidney", "Heart", "Stomach", "Spleen"],
        explanation: "The pancreas makes insulin to control blood sugar.",
      },
      lt: {
        question: "Kuris organas gamina hormoną insuliną?",
        correct: "Kasa",
        distractors: ["Kepenys", "Inkstas", "Širdis", "Skrandis", "Blužnis"],
        explanation: "Kasa gamina insuliną, valdantį cukraus kiekį kraujyje.",
      },
    },
  },
  {
    id: "bod_su_006",
    category: "body",
    subTheme: "anatomy",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Anatomy (alveoli in lungs)",
    emoji: "🫁",
    translations: {
      en: {
        question: "Tiny air sacs where oxygen enters blood are called what?",
        correct: "Alveoli",
        distractors: ["Neurons", "Villi", "Nephrons", "Follicles", "Capillary loops"],
        explanation: "Alveoli in the lungs exchange oxygen and gas.",
      },
      lt: {
        question: "Kaip vadinami maži oro maišeliai, kur deguonis patenka į kraują?",
        correct: "Alveolės",
        distractors: ["Neuronai", "Gaureliai", "Nefronai", "Folikulai", "Kapiliarai"],
        explanation: "Alveolės plaučiuose keičiasi deguonimi ir dujomis.",
      },
    },
  },
  {
    id: "bod_su_007",
    category: "body",
    subTheme: "physiology",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Anatomy (white cells fight infection)",
    emoji: "🛡️",
    translations: {
      en: {
        question: "Which blood cells help fight infection?",
        correct: "White blood cells",
        distractors: ["Red blood cells", "Platelets", "Plasma cells only", "Nerve cells", "Muscle cells"],
        explanation: "White blood cells defend against infection.",
      },
      lt: {
        question: "Kurios kraujo ląstelės padeda kovoti su infekcija?",
        correct: "Baltieji kraujo kūneliai",
        distractors: ["Raudonieji kūneliai", "Trombocitai", "Tik plazmos ląstelės", "Nervų ląstelės", "Raumenų ląstelės"],
        explanation: "Baltieji kūneliai gina nuo infekcijos.",
      },
    },
  },
  {
    id: "bod_su_008",
    category: "body",
    subTheme: "anatomy",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Anatomy (largest muscle is gluteus maximus)",
    emoji: "🦵",
    translations: {
      en: {
        question: "What is the largest muscle in the human body?",
        correct: "Gluteus maximus",
        distractors: ["Biceps", "Heart", "Calf", "Tongue", "Jaw"],
        explanation: "The gluteus maximus in the buttock is the largest.",
      },
      lt: {
        question: "Koks didžiausias raumuo žmogaus kūne?",
        correct: "Didysis sėdmens raumuo",
        distractors: ["Bicepsas", "Širdis", "Blauzda", "Liežuvis", "Žandikaulis"],
        explanation: "Didysis sėdmens raumuo yra didžiausias.",
      },
    },
  },
  {
    id: "bod_su_009",
    category: "body",
    subTheme: "physiology",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Physiology (esophagus carries food)",
    emoji: "🍽️",
    translations: {
      en: {
        question: "Which tube carries food from the throat to the stomach?",
        correct: "Esophagus",
        distractors: ["Trachea", "Artery", "Vein", "Ureter", "Bronchus"],
        explanation: "The esophagus moves food to the stomach.",
      },
      lt: {
        question: "Kuris vamzdis veda maistą iš gerklės į skrandį?",
        correct: "Stemplė",
        distractors: ["Trachėja", "Arterija", "Vena", "Šlapimtakis", "Bronchas"],
        explanation: "Stemplė nuveda maistą į skrandį.",
      },
    },
  },
  {
    id: "bod_su_010",
    category: "body",
    subTheme: "anatomy",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Anatomy (cornea at front of eye)",
    emoji: "👁️",
    translations: {
      en: {
        question: "The clear front layer of the eye is called the what?",
        correct: "Cornea",
        distractors: ["Retina", "Iris", "Pupil", "Lens", "Sclera"],
        explanation: "The cornea is the clear front of the eye.",
      },
      lt: {
        question: "Kaip vadinamas skaidrus priekinis akies sluoksnis?",
        correct: "Ragena",
        distractors: ["Tinklainė", "Rainelė", "Vyzdys", "Lęšiukas", "Skleros dalis"],
        explanation: "Ragena — skaidri priekinė akies dalis.",
      },
    },
  },
  {
    id: "bod_su_011",
    category: "body",
    subTheme: "physiology",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Physiology (platelets help clotting)",
    emoji: "🩸",
    translations: {
      en: {
        question: "Which blood part helps wounds clot?",
        correct: "Platelets",
        distractors: ["Red cells", "White cells", "Plasma water", "Nerve cells", "Bone cells"],
        explanation: "Platelets clump to help blood clot.",
      },
      lt: {
        question: "Kuri kraujo dalis padeda žaizdoms krešėti?",
        correct: "Trombocitai",
        distractors: ["Raudonieji kūneliai", "Baltieji kūneliai", "Plazmos vanduo", "Nervų ląstelės", "Kaulų ląstelės"],
        explanation: "Trombocitai sukimba ir padeda kraujui krešėti.",
      },
    },
  },
  {
    id: "bod_su_012",
    category: "body",
    subTheme: "anatomy",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Anatomy (diaphragm muscle for breathing)",
    emoji: "🫁",
    translations: {
      en: {
        question: "Which muscle below the lungs helps you breathe?",
        correct: "Diaphragm",
        distractors: ["Biceps", "Heart", "Calf", "Jaw", "Tongue"],
        explanation: "The diaphragm contracts to pull air into the lungs.",
      },
      lt: {
        question: "Kuris raumuo po plaučiais padeda kvėpuoti?",
        correct: "Diafragma",
        distractors: ["Bicepsas", "Širdis", "Blauzda", "Žandikaulis", "Liežuvis"],
        explanation: "Diafragma susitraukdama įtraukia orą į plaučius.",
      },
    },
  },
  {
    id: "bod_su_013",
    category: "body",
    subTheme: "physiology",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Anatomy (neurons in nervous system)",
    emoji: "🧠",
    translations: {
      en: {
        question: "The basic cells that carry nerve signals are called what?",
        correct: "Neurons",
        distractors: ["Alveoli", "Nephrons", "Villi", "Platelets", "Follicles"],
        explanation: "Neurons are nerve cells that carry signals.",
      },
      lt: {
        question: "Kaip vadinamos pagrindinės ląstelės, nešančios nervų signalus?",
        correct: "Neuronai",
        distractors: ["Alveolės", "Nefronai", "Gaureliai", "Trombocitai", "Folikulai"],
        explanation: "Neuronai — nervų ląstelės, nešančios signalus.",
      },
    },
  },
  {
    id: "bod_su_014",
    category: "body",
    subTheme: "anatomy",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Anatomy (small intestine absorbs nutrients)",
    emoji: "🌀",
    translations: {
      en: {
        question: "Where are most nutrients absorbed from food?",
        correct: "Small intestine",
        distractors: ["Stomach", "Large intestine", "Liver", "Mouth", "Esophagus"],
        explanation: "Most nutrients are absorbed in the small intestine.",
      },
      lt: {
        question: "Kur iš maisto pasisavinama daugiausia maistinių medžiagų?",
        correct: "Plonojoje žarnoje",
        distractors: ["Skrandyje", "Storojoje žarnoje", "Kepenyse", "Burnoje", "Stemplėje"],
        explanation: "Daugiausia maistinių medžiagų pasisavinama plonojoje žarnoje.",
      },
    },
  },
  {
    id: "bod_su_015",
    category: "body",
    subTheme: "physiology",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Anatomy (nephrons filter in kidney)",
    emoji: "🫘",
    translations: {
      en: {
        question: "The tiny filtering units of the kidney are called what?",
        correct: "Nephrons",
        distractors: ["Neurons", "Alveoli", "Villi", "Follicles", "Capillaries only"],
        explanation: "Nephrons are the filtering units of the kidney.",
      },
      lt: {
        question: "Kaip vadinami maži inksto filtravimo vienetai?",
        correct: "Nefronai",
        distractors: ["Neuronai", "Alveolės", "Gaureliai", "Folikulai", "Tik kapiliarai"],
        explanation: "Nefronai — inksto filtravimo vienetai.",
      },
    },
  },

  // ======================= EKSTREMALUS (Extreme) =======================
  {
    id: "bod_ek_001",
    category: "body",
    subTheme: "physiology",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Anatomy (femur longest, stapes shortest)",
    emoji: "🦴",
    translations: {
      en: {
        question: "What is the name of the smallest bone in the body?",
        correct: "Stapes",
        distractors: ["Femur", "Ulna", "Patella", "Hyoid", "Coccyx"],
        explanation: "The stapes in the ear is the smallest bone.",
      },
      lt: {
        question: "Koks mažiausio kūno kaulo pavadinimas?",
        correct: "Kilpelė (stapes)",
        distractors: ["Šlaunikaulis", "Alkūnkaulis", "Girnelė", "Poliežuvinis", "Uodegikaulis"],
        explanation: "Kilpelė (stapes) ausyje — mažiausias kaulas.",
      },
    },
  },
  {
    id: "bod_ek_002",
    category: "body",
    subTheme: "physiology",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Biology (DNA carries genetic code)",
    emoji: "🧬",
    translations: {
      en: {
        question: "Which molecule carries our genetic information?",
        correct: "DNA",
        distractors: ["ATP", "Glucose", "Collagen", "Keratin", "Insulin"],
        explanation: "DNA carries the genetic code in cells.",
      },
      lt: {
        question: "Kuri molekulė neša mūsų genetinę informaciją?",
        correct: "DNR",
        distractors: ["ATP", "Gliukozė", "Kolagenas", "Keratinas", "Insulinas"],
        explanation: "DNR neša genetinį kodą ląstelėse.",
      },
    },
  },
  {
    id: "bod_ek_003",
    category: "body",
    subTheme: "physiology",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Anatomy (largest artery is aorta)",
    emoji: "🫀",
    translations: {
      en: {
        question: "What is the body's largest artery called?",
        correct: "Aorta",
        distractors: ["Vena cava", "Carotid", "Femoral", "Pulmonary vein", "Capillary"],
        explanation: "The aorta is the largest artery, leaving the heart.",
      },
      lt: {
        question: "Kaip vadinama didžiausia kūno arterija?",
        correct: "Aorta",
        distractors: ["Tuščioji vena", "Miego arterija", "Šlauninė", "Plautinė vena", "Kapiliaras"],
        explanation: "Aorta — didžiausia arterija, išeinanti iš širdies.",
      },
    },
  },
  {
    id: "bod_ek_004",
    category: "body",
    subTheme: "physiology",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Anatomy (46 chromosomes in human cells)",
    emoji: "🧬",
    translations: {
      en: {
        question: "How many chromosomes are in a typical human cell?",
        correct: "46",
        distractors: ["23", "44", "48", "92", "12"],
        explanation: "Most human cells have 46 chromosomes.",
      },
      lt: {
        question: "Kiek chromosomų yra įprastoje žmogaus ląstelėje?",
        correct: "46",
        distractors: ["23", "44", "48", "92", "12"],
        explanation: "Daugumoje žmogaus ląstelių yra 46 chromosomos.",
      },
    },
  },
  {
    id: "bod_ek_005",
    category: "body",
    subTheme: "anatomy",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Anatomy (largest organ skin, internal liver)",
    emoji: "🧠",
    translations: {
      en: {
        question: "Which part of the brain controls balance and coordination?",
        correct: "Cerebellum",
        distractors: ["Cerebrum", "Spinal cord", "Retina", "Cortex only", "Pituitary"],
        explanation: "The cerebellum manages balance and coordination.",
      },
      lt: {
        question: "Kuri smegenų dalis valdo pusiausvyrą ir koordinaciją?",
        correct: "Smegenėlės",
        distractors: ["Didieji pusrutuliai", "Nugaros smegenys", "Tinklainė", "Tik žievė", "Hipofizė"],
        explanation: "Smegenėlės valdo pusiausvyrą ir koordinaciją.",
      },
    },
  },
  {
    id: "bod_ek_006",
    category: "body",
    subTheme: "physiology",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Anatomy (small intestine longest part of gut)",
    emoji: "🌀",
    translations: {
      en: {
        question: "Which part of the digestive tract is the longest?",
        correct: "Small intestine",
        distractors: ["Stomach", "Esophagus", "Large intestine", "Mouth", "Throat"],
        explanation: "The small intestine is the longest digestive section.",
      },
      lt: {
        question: "Kuri virškinimo trakto dalis yra ilgiausia?",
        correct: "Plonoji žarna",
        distractors: ["Skrandis", "Stemplė", "Storoji žarna", "Burna", "Gerklė"],
        explanation: "Plonoji žarna — ilgiausia virškinimo trakto dalis.",
      },
    },
  },
  {
    id: "bod_ek_007",
    category: "body",
    subTheme: "physiology",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Biology (cell powerhouse mitochondria)",
    emoji: "🔋",
    translations: {
      en: {
        question: "Which cell part is called the powerhouse of the cell?",
        correct: "Mitochondria",
        distractors: ["Nucleus", "Ribosome", "Membrane", "Vacuole", "Cytoplasm"],
        explanation: "Mitochondria produce energy for the cell.",
      },
      lt: {
        question: "Kuri ląstelės dalis vadinama ląstelės jėgaine?",
        correct: "Mitochondrijos",
        distractors: ["Branduolys", "Ribosoma", "Membrana", "Vakuolė", "Citoplazma"],
        explanation: "Mitochondrijos gamina energiją ląstelei.",
      },
    },
  },
  {
    id: "bod_ek_008",
    category: "body",
    subTheme: "physiology",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Physiology (blood pH ~7.4)",
    emoji: "🩸",
    translations: {
      en: {
        question: "What is the approximate pH of healthy human blood?",
        correct: "About 7.4",
        distractors: [
          "About 7.0",
          "About 6.5",
          "About 8.5",
          "About 5.5",
          "About 8.0",
        ],
        explanation: "Healthy blood is slightly basic, with a pH near 7.4.",
      },
      lt: {
        question: "Koks yra apytikslis sveiko žmogaus kraujo pH?",
        correct: "Apie 7,4",
        distractors: [
          "Apie 7,0",
          "Apie 6,5",
          "Apie 8,5",
          "Apie 5,5",
          "Apie 8,0",
        ],
        explanation: "Sveikas kraujas šiek tiek šarminis, pH apie 7,4.",
      },
    },
  },
  {
    id: "bod_ek_009",
    category: "body",
    subTheme: "anatomy",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Anatomy (retina detects light)",
    emoji: "👁️",
    translations: {
      en: {
        question: "Which layer at the back of the eye detects light?",
        correct: "Retina",
        distractors: ["Cornea", "Iris", "Pupil", "Lens", "Sclera"],
        explanation: "The retina senses light and sends signals to the brain.",
      },
      lt: {
        question: "Kuris akies užpakalio sluoksnis pagauna šviesą?",
        correct: "Tinklainė",
        distractors: ["Ragena", "Rainelė", "Vyzdys", "Lęšiukas", "Sklera"],
        explanation: "Tinklainė jaučia šviesą ir siunčia signalus į smegenis.",
      },
    },
  },
  {
    id: "bod_ek_010",
    category: "body",
    subTheme: "physiology",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Physiology (hemoglobin carries oxygen)",
    emoji: "🩸",
    translations: {
      en: {
        question: "Which protein in red blood cells carries oxygen?",
        correct: "Hemoglobin",
        distractors: ["Keratin", "Collagen", "Insulin", "Albumin", "Myosin"],
        explanation: "Hemoglobin binds oxygen in red blood cells.",
      },
      lt: {
        question: "Kuris baltymas raudonuosiuose kūneliuose neša deguonį?",
        correct: "Hemoglobinas",
        distractors: ["Keratinas", "Kolagenas", "Insulinas", "Albuminas", "Miozinas"],
        explanation: "Hemoglobinas suriša deguonį raudonuosiuose kūneliuose.",
      },
    },
  },
  {
    id: "bod_ek_011",
    category: "body",
    subTheme: "physiology",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Biology (nucleus holds DNA)",
    emoji: "🧬",
    translations: {
      en: {
        question: "Which part of a cell holds most of its DNA?",
        correct: "Nucleus",
        distractors: ["Membrane", "Ribosome", "Mitochondria", "Vacuole", "Cytoplasm"],
        explanation: "The nucleus stores most of the cell's DNA.",
      },
      lt: {
        question: "Kurioje ląstelės dalyje yra daugiausia jos DNR?",
        correct: "Branduolyje",
        distractors: ["Membranoje", "Ribosomoje", "Mitochondrijose", "Vakuolėje", "Citoplazmoje"],
        explanation: "Branduolyje saugoma didžioji dalis ląstelės DNR.",
      },
    },
  },
  {
    id: "bod_ek_012",
    category: "body",
    subTheme: "anatomy",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Anatomy (liver can regenerate)",
    emoji: "🫀",
    translations: {
      en: {
        question: "Which human organ can regrow much of itself if damaged?",
        correct: "Liver",
        distractors: ["Heart", "Brain", "Eye", "Kidney", "Lung"],
        explanation: "The liver can regenerate a large part of itself.",
      },
      lt: {
        question: "Kuris žmogaus organas gali didele dalimi atsinaujinti po pažeidimo?",
        correct: "Kepenys",
        distractors: ["Širdis", "Smegenys", "Akis", "Inkstas", "Plautis"],
        explanation: "Kepenys gali atauginti didelę savo dalį.",
      },
    },
  },
  {
    id: "bod_ek_013",
    category: "body",
    subTheme: "physiology",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Anatomy (adult has 12 pairs of ribs)",
    emoji: "🦴",
    translations: {
      en: {
        question: "How many pairs of ribs does a typical person have?",
        correct: "12",
        distractors: ["10", "11", "13", "14", "8"],
        explanation: "Most people have 12 pairs of ribs.",
      },
      lt: {
        question: "Kiek porų šonkaulių paprastai turi žmogus?",
        correct: "12",
        distractors: ["10", "11", "13", "14", "8"],
        explanation: "Dauguma žmonių turi 12 porų šonkaulių.",
      },
    },
  },
  {
    id: "bod_ek_014",
    category: "body",
    subTheme: "anatomy",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Anatomy (hand has 27 bones)",
    emoji: "✋",
    translations: {
      en: {
        question: "About how many bones are in one human hand?",
        correct: "27",
        distractors: ["12", "19", "33", "40", "8"],
        explanation: "One human hand contains about 27 bones.",
      },
      lt: {
        question: "Maždaug kiek kaulų yra vienoje žmogaus plaštakoje?",
        correct: "27",
        distractors: ["12", "19", "33", "40", "8"],
        explanation: "Vienoje plaštakoje yra maždaug 27 kaulai.",
      },
    },
  },
  {
    id: "bod_ek_015",
    category: "body",
    subTheme: "physiology",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Anatomy (skin is largest organ overall)",
    emoji: "🖐️",
    translations: {
      en: {
        question: "Counting all organs, which is the largest of the body?",
        correct: "Skin",
        distractors: ["Liver", "Brain", "Heart", "Intestine", "Lung"],
        explanation: "Skin is the largest organ overall, larger than the liver.",
      },
      lt: {
        question: "Skaičiuojant visus organus, kuris yra didžiausias kūne?",
        correct: "Oda",
        distractors: ["Kepenys", "Smegenys", "Širdis", "Žarnynas", "Plautis"],
        explanation: "Oda — didžiausias visas organas, didesnis už kepenis.",
      },
    },
  },
];
