/**
 * brandsNames — 💡 „Vardų paslaptys" potemė (tema „Prekių ženklų istorijos").
 *
 * MAŽAS FAILAS pagal potemę. 40 klausimų (10/lygiui). Iš kur kilo garsių (daugiausia
 * technologijų) prekių ženklų VARDAI: Apple, Google, Amazon, Bluetooth, Nokia ...
 * Tik istoriniai/įsitvirtinę faktai — JOKIOS reklamos.
 *
 * TAISYKLĖS: 1 teisingas + 5 distraktoriai; ≤46 simb.; teisingas NE ilgiausias >+5;
 * LT be vidinių kabučių; jokio atsakymo klausime; EMOJI NEUTRALUS (neišduoda atsakymo).
 */

import { TriviaQuestion } from "./triviaTypes";

export const BRANDS_NAMES: TriviaQuestion[] = [
  // ===================== LENGVAS (9–12 m. vaikas) =====================
  {
    id: "brn_nm_001",
    category: "brands",
    subTheme: "names",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Google — name is a play on 'googol' (1 followed by 100 zeros)",
    emoji: "🔎",
    translations: {
      en: {
        question: "Which search engine's name plays on the giant number 'googol'?",
        correct: "Google",
        distractors: ["Yahoo", "Bing", "Ask", "Lycos", "Baidu"],
        explanation: "A googol is a 1 followed by a hundred zeros — a huge amount of data.",
      },
      lt: {
        question: "Kurios paieškos sistemos vardas kilo iš milžiniško skaičiaus googol?",
        correct: "Google",
        distractors: ["Yahoo", "Bing", "Ask", "Lycos", "Baidu"],
        explanation: "Googol yra vienetas su šimtu nulių — milžiniškas duomenų kiekis.",
      },
    },
  },
  {
    id: "brn_nm_002",
    category: "brands",
    subTheme: "names",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Amazon — named after the world's largest river by volume",
    emoji: "🛒",
    translations: {
      en: {
        question: "The shopping giant Amazon is named after which huge river?",
        correct: "The Amazon",
        distractors: ["The Nile", "The Congo", "The Ganges", "The Danube", "The Orinoco"],
        explanation: "Its founder wanted a name starting with A that meant 'biggest'.",
      },
      lt: {
        question: "Pirkinių milžinė Amazon pavadinta pagal kurią didžiulę upę?",
        correct: "Amazonę",
        distractors: ["Nilą", "Kongą", "Gangą", "Dunojų", "Orinoką"],
        explanation: "Įkūrėjas norėjo vardo, prasidedančio A ir reiškiančio didžiausią.",
      },
    },
  },
  {
    id: "brn_nm_003",
    category: "brands",
    subTheme: "names",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Nintendo — maker of Mario and the Switch; began in 1889 making playing cards",
    emoji: "🎮",
    translations: {
      en: {
        question: "Which game company makes Mario and the Switch console?",
        correct: "Nintendo",
        distractors: ["Sega", "Sony", "Atari", "Capcom", "Bandai"],
        explanation: "Nintendo started way back in 1889 making paper playing cards!",
      },
      lt: {
        question: "Kuri žaidimų bendrovė kuria Mario ir konsolę Switch?",
        correct: "Nintendo",
        distractors: ["Sega", "Sony", "Atari", "Capcom", "Bandai"],
        explanation: "Nintendo pradėjo dar 1889 m. gamindama popierines kortas!",
      },
    },
  },
  {
    id: "brn_nm_004",
    category: "brands",
    subTheme: "names",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Samsung — name means 'three stars' in Korean",
    emoji: "📱",
    translations: {
      en: {
        question: "Which Korean tech brand's name means 'three stars'?",
        correct: "Samsung",
        distractors: ["LG", "Sony", "Sharp", "Haier", "Hyundai"],
        explanation: "The founder chose stars to suggest something big and everlasting.",
      },
      lt: {
        question: "Kurio korėjiečių technologijų ženklo vardas reiškia tris žvaigždes?",
        correct: "Samsung",
        distractors: ["LG", "Sony", "Sharp", "Haier", "Hyundai"],
        explanation: "Įkūrėjas pasirinko žvaigždes, kad keltų didingumo ir amžinumo įspūdį.",
      },
    },
  },
  {
    id: "brn_nm_005",
    category: "brands",
    subTheme: "names",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Sony — makes PlayStation; name from Latin 'sonus' (sound)",
    emoji: "🎮",
    translations: {
      en: {
        question: "Which brand makes the PlayStation game consoles?",
        correct: "Sony",
        distractors: ["Microsoft", "Nintendo", "Sega", "Atari", "LG"],
        explanation: "The name Sony comes from the Latin word 'sonus', meaning sound.",
      },
      lt: {
        question: "Kuris ženklas gamina PlayStation žaidimų konsoles?",
        correct: "Sony",
        distractors: ["Microsoft", "Nintendo", "Sega", "Atari", "LG"],
        explanation: "Vardas Sony kilo iš lotyniško žodžio sonus — garsas.",
      },
    },
  },
  {
    id: "brn_nm_006",
    category: "brands",
    subTheme: "names",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Netflix — began by mailing rental DVDs before streaming",
    emoji: "📺",
    translations: {
      en: {
        question: "Before streaming, Netflix started by posting people what?",
        correct: "DVDs",
        distractors: ["CDs", "Books", "Games", "Posters", "Tapes"],
        explanation: "It mailed rental DVDs in red envelopes long before online video.",
      },
      lt: {
        question: "Ką, dar prieš srautinį vaizdą, Netflix siuntė žmonėms paštu?",
        correct: "DVD diskus",
        distractors: ["CD diskus", "Knygas", "Žaidimus", "Plakatus", "Kasetes"],
        explanation: "Ji siuntė nuomos DVD raudonuose vokuose dar gerokai prieš vaizdą internetu.",
      },
    },
  },
  {
    id: "brn_nm_007",
    category: "brands",
    subTheme: "names",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Microsoft — name blends 'microcomputer' and 'software'",
    emoji: "💻",
    translations: {
      en: {
        question: "Which software giant's name blends 'microcomputer' and 'software'?",
        correct: "Microsoft",
        distractors: ["Macintosh", "Megabyte", "Micron", "Minitel", "Macrohard"],
        explanation: "The name simply mixes the words microcomputer and software.",
      },
      lt: {
        question: "Kurio programų milžino vardas jungia mikrokompiuterį ir programinę įrangą?",
        correct: "Microsoft",
        distractors: ["Macintosh", "Megabyte", "Micron", "Minitel", "Macrohard"],
        explanation: "Vardas tiesiog sujungia žodžius mikrokompiuteris ir programinė įranga.",
      },
    },
  },
  {
    id: "brn_nm_008",
    category: "brands",
    subTheme: "names",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Spotify — popular music streaming app with a green logo",
    emoji: "🎵",
    translations: {
      en: {
        question: "Which app with a green logo lets you stream millions of songs?",
        correct: "Spotify",
        distractors: ["Deezer", "Tidal", "Pandora", "Napster", "SoundCloud"],
        explanation: "The Swedish app's odd name was reportedly coined almost by accident.",
      },
      lt: {
        question: "Kuri programėlė su žaliu logotipu leidžia klausytis milijonų dainų?",
        correct: "Spotify",
        distractors: ["Deezer", "Tidal", "Pandora", "Napster", "SoundCloud"],
        explanation: "Pasak kūrėjų, keistas švedų programėlės vardas gimė beveik atsitiktinai.",
      },
    },
  },
  {
    id: "brn_nm_009",
    category: "brands",
    subTheme: "names",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Apple — maker of the iPhone; first logo showed Isaac Newton",
    emoji: "📱",
    translations: {
      en: {
        question: "Which company makes the iPhone?",
        correct: "Apple",
        distractors: ["Samsung", "Nokia", "Google", "Sony", "Xiaomi"],
        explanation: "Its bitten-fruit logo is one of the most famous symbols on Earth.",
      },
      lt: {
        question: "Kuri bendrovė gamina iPhone?",
        correct: "Apple",
        distractors: ["Samsung", "Nokia", "Google", "Sony", "Xiaomi"],
        explanation: "Jos pakąsto vaisiaus logotipas — vienas garsiausių ženklų pasaulyje.",
      },
    },
  },
  {
    id: "brn_nm_010",
    category: "brands",
    subTheme: "names",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "YouTube — Google-owned video site; 'tube' is old slang for television",
    emoji: "📺",
    translations: {
      en: {
        question: "Which video site, now owned by Google, is famous for user videos?",
        correct: "YouTube",
        distractors: ["TikTok", "Vimeo", "Twitch", "Dailymotion", "Reels"],
        explanation: "'Tube' is old slang for a television set, so it means 'your TV'.",
      },
      lt: {
        question: "Kuri vaizdo svetainė, dabar priklausanti Google, garsi naudotojų vaizdais?",
        correct: "YouTube",
        distractors: ["TikTok", "Vimeo", "Twitch", "Dailymotion", "Reels"],
        explanation: "Tube yra senas televizoriaus slengas, tad vardas reiškia tavo TV.",
      },
    },
  },

  // ===================== VIDUTINIS (12–18 m. paauglys) =====================
  {
    id: "brn_nm_011",
    category: "brands",
    subTheme: "names",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Amazon — Jeff Bezos first named it 'Cadabra', changed as it sounded like 'cadaver'",
    emoji: "🛒",
    translations: {
      en: {
        question: "Amazon was almost named which magic-sounding word at first?",
        correct: "Cadabra",
        distractors: ["Abraca", "Bookmonster", "Aardvark", "Zoom", "MakeItSo"],
        explanation: "Bezos changed it because Cadabra sounded too much like 'cadaver'.",
      },
      lt: {
        question: "Kuriuo magiškai skambančiu žodžiu Amazon iš pradžių vos nebuvo pavadinta?",
        correct: "Cadabra",
        distractors: ["Abraca", "Bookmonster", "Aardvark", "Zoom", "MakeItSo"],
        explanation: "Bezosas jį pakeitė, nes Cadabra per daug priminė žodį lavonas.",
      },
    },
  },
  {
    id: "brn_nm_012",
    category: "brands",
    subTheme: "names",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Bluetooth — named after Viking king Harald 'Bluetooth' Gormsson; logo is his runes",
    emoji: "📶",
    translations: {
      en: {
        question: "Which wireless tech is named after a Viking king who united tribes?",
        correct: "Bluetooth",
        distractors: ["Wi-Fi", "Ethernet", "Infrared", "Zigbee", "Hotspot"],
        explanation: "King Harald united Denmark; the logo joins his initials in runes.",
      },
      lt: {
        question: "Kuri belaidė technologija pavadinta vikingų karaliaus, suvienijusio gentis, vardu?",
        correct: "Bluetooth",
        distractors: ["Wi-Fi", "Ethernet", "Infraraudonieji", "Zigbee", "Hotspot"],
        explanation: "Karalius Haraldas suvienijo Daniją; logotipas jungia jo inicialus runomis.",
      },
    },
  },
  {
    id: "brn_nm_013",
    category: "brands",
    subTheme: "names",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Nokia — named after a town and river in Finland; began as a paper mill",
    emoji: "📱",
    translations: {
      en: {
        question: "The phone pioneer Nokia is named after a place in which country?",
        correct: "Finland",
        distractors: ["Sweden", "Norway", "Japan", "Germany", "Estonia"],
        explanation: "Nokia is a town and river there; the firm began as a paper mill.",
      },
      lt: {
        question: "Telefonų pradininkė Nokia pavadinta pagal vietovę kurioje šalyje?",
        correct: "Suomijoje",
        distractors: ["Švedijoje", "Norvegijoje", "Japonijoje", "Vokietijoje", "Estijoje"],
        explanation: "Nokia ten yra miestelis ir upė; firma pradėjo nuo popieriaus malūno.",
      },
    },
  },
  {
    id: "brn_nm_014",
    category: "brands",
    subTheme: "names",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Reebok — named after the rhebok, a fast African antelope",
    emoji: "👟",
    translations: {
      en: {
        question: "The sportswear brand Reebok is named after a fast African what?",
        correct: "Antelope",
        distractors: ["Lion", "Eagle", "Zebra", "Cheetah", "Leopard"],
        explanation: "The rhebok is a small, nimble antelope from southern Africa.",
      },
      lt: {
        question: "Sporto prekės ženklas Reebok pavadintas greito Afrikos ko vardu?",
        correct: "Antilopės",
        distractors: ["Liūto", "Erelio", "Zebro", "Geparado", "Leopardo"],
        explanation: "Rhebok yra maža, vikri pietų Afrikos antilopė.",
      },
    },
  },
  {
    id: "brn_nm_015",
    category: "brands",
    subTheme: "names",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Pepsi — name derived from 'dyspepsia' (indigestion); sold as a digestion aid",
    emoji: "🥤",
    translations: {
      en: {
        question: "Which fizzy drink's name comes from a word for indigestion?",
        correct: "Pepsi",
        distractors: ["Fanta", "Sprite", "Crush", "Tango", "Schweppes"],
        explanation: "It was first sold as a tonic to calm an upset stomach.",
      },
      lt: {
        question: "Kurio gazuoto gėrimo vardas kilo iš žodžio, reiškiančio nevirškinimą?",
        correct: "Pepsi",
        distractors: ["Fanta", "Sprite", "Crush", "Tango", "Schweppes"],
        explanation: "Iš pradžių jis parduotas kaip tonikas skrandžiui nuraminti.",
      },
    },
  },
  {
    id: "brn_nm_016",
    category: "brands",
    subTheme: "names",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Haribo — acronym: HAns RIegel BOnn (founder name + the city of Bonn)",
    emoji: "🍬",
    translations: {
      en: {
        question: "Haribo's name joins its founder's name with which German city?",
        correct: "Bonn",
        distractors: ["Berlin", "Munich", "Cologne", "Hamburg", "Bremen"],
        explanation: "HAns RIegel BOnn fit together into the short name Haribo.",
      },
      lt: {
        question: "Haribo vardas jungia įkūrėjo vardą su kuriuo Vokietijos miestu?",
        correct: "Bonu",
        distractors: ["Berlynu", "Miunchenu", "Kelnu", "Hamburgu", "Brėmenu"],
        explanation: "HAns RIegel BOnn susidėjo į trumpą vardą Haribo.",
      },
    },
  },
  {
    id: "brn_nm_017",
    category: "brands",
    subTheme: "names",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Nivea — from Latin 'niveus', meaning snow-white (like the cream)",
    emoji: "🧴",
    translations: {
      en: {
        question: "The skin cream Nivea takes its name from Latin for which look?",
        correct: "Snow-white",
        distractors: ["Sky-blue", "Sea-green", "Rose-pink", "Pale-gold", "Soft-grey"],
        explanation: "From 'niveus', snowy white, just like the colour of the cream.",
      },
      lt: {
        question: "Odos kremas Nivea pavadintas pagal lotynišką žodį, reiškiantį kokią išvaizdą?",
        correct: "Sniego baltumą",
        distractors: ["Dangaus mėlynumą", "Jūros žalumą", "Rožių rausvumą", "Blyškų auksą", "Švelnų pilkumą"],
        explanation: "Iš niveus — snieguotai baltas, kaip ir paties kremo spalva.",
      },
    },
  },
  {
    id: "brn_nm_018",
    category: "brands",
    subTheme: "names",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "eBay — first launched as 'AuctionWeb'; name from founder's firm Echo Bay",
    emoji: "🛒",
    translations: {
      en: {
        question: "Which auction site first went online under the name AuctionWeb?",
        correct: "eBay",
        distractors: ["Amazon", "Etsy", "Craigslist", "Yahoo", "PayPal"],
        explanation: "The short name came from the founder's company, Echo Bay.",
      },
      lt: {
        question: "Kuri aukcionų svetainė internete pirmiausia pasirodė pavadinimu AuctionWeb?",
        correct: "eBay",
        distractors: ["Amazon", "Etsy", "Craigslist", "Yahoo", "PayPal"],
        explanation: "Trumpas vardas kilo iš įkūrėjo bendrovės Echo Bay.",
      },
    },
  },
  {
    id: "brn_nm_019",
    category: "brands",
    subTheme: "names",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Vaseline — blends German 'Wasser' (water) and Greek 'elaion' (oil)",
    emoji: "🧴",
    translations: {
      en: {
        question: "Vaseline's name blends the German for water with the Greek for what?",
        correct: "Oil",
        distractors: ["Wax", "Skin", "Fat", "Stone", "Salt"],
        explanation: "'Wasser' (water) plus 'elaion' (oil) gave us Vaseline.",
      },
      lt: {
        question: "Vaseline vardas jungia vokišką žodį vanduo su graikišku žodžiu, reiškiančiu ką?",
        correct: "Aliejų",
        distractors: ["Vašką", "Odą", "Riebalus", "Akmenį", "Druską"],
        explanation: "Wasser (vanduo) ir elaion (aliejus) davė vardą Vaseline.",
      },
    },
  },
  {
    id: "brn_nm_020",
    category: "brands",
    subTheme: "names",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Aldi — short for 'Albrecht Diskont' (Albrecht Discount)",
    emoji: "🛒",
    translations: {
      en: {
        question: "The budget supermarket Aldi shortens which two-word name?",
        correct: "Albrecht Discount",
        distractors: ["Always Discount", "Allied Dairy", "Alpine Deal", "Albert Dunn", "Allgäu Direct"],
        explanation: "The Albrecht brothers built the discount chain in Germany.",
      },
      lt: {
        question: "Pigi parduotuvė Aldi sutrumpina kurį dviejų žodžių pavadinimą?",
        correct: "Albrecht Discount",
        distractors: ["Always Discount", "Allied Dairy", "Alpine Deal", "Albert Dunn", "Allgäu Direct"],
        explanation: "Broliai Albrechtai sukūrė šį nuolaidų tinklą Vokietijoje.",
      },
    },
  },

  // ===================== SUNKUS (suaugęs, kuris domisi) =====================
  {
    id: "brn_nm_021",
    category: "brands",
    subTheme: "names",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Apple's first 1976 logo showed Isaac Newton under an apple tree",
    emoji: "💻",
    translations: {
      en: {
        question: "Apple's very first logo showed which scientist under a tree?",
        correct: "Isaac Newton",
        distractors: ["Albert Einstein", "Galileo", "Leonardo", "Edison", "Darwin"],
        explanation: "The 1976 logo pictured Newton just as an apple was about to fall.",
      },
      lt: {
        question: "Pirmasis Apple logotipas vaizdavo kurį mokslininką po medžiu?",
        correct: "Isaac Newton",
        distractors: ["Albert Einstein", "Galilėjų", "Leonardą", "Edisoną", "Darviną"],
        explanation: "1976 m. logotipe Newtonas sėdėjo kaip tik krintant obuoliui.",
      },
    },
  },
  {
    id: "brn_nm_022",
    category: "brands",
    subTheme: "names",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Sony — name from Latin 'sonus' (sound) plus the slang 'sonny'",
    emoji: "🎮",
    translations: {
      en: {
        question: "Sony joins Latin 'sonus' (sound) with which friendly English word?",
        correct: "Sonny",
        distractors: ["Sunny", "Song", "Son", "Sony-boy", "Soni"],
        explanation: "'Sonny boys' was 1950s slang for bright, lively young men.",
      },
      lt: {
        question: "Sony jungia lotynišką sonus (garsas) su kuriuo draugišku anglišku žodžiu?",
        correct: "Sonny",
        distractors: ["Sunny", "Song", "Son", "Sony-boy", "Soni"],
        explanation: "Sonny boys 6-ajame dešimtmetyje vadino guvius, žvalius jaunuolius.",
      },
    },
  },
  {
    id: "brn_nm_023",
    category: "brands",
    subTheme: "names",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Cisco — name shortened from 'San Francisco'; logo evokes the Golden Gate Bridge",
    emoji: "💻",
    translations: {
      en: {
        question: "The tech company Cisco's name is shortened from which US city?",
        correct: "San Francisco",
        distractors: ["Sacramento", "San Diego", "San Jose", "Santa Clara", "Seattle"],
        explanation: "Cisco comes from San Francisco; its logo even echoes the Golden Gate Bridge.",
      },
      lt: {
        question: "Technologijų bendrovės Cisco vardas sutrumpintas iš kurio JAV miesto?",
        correct: "San Franciskas",
        distractors: ["Sakramentas", "San Diegas", "San Chosė", "Santa Klara", "Sietlas"],
        explanation: "Cisco kilo iš San Francisko; logotipas net primena Auksinių vartų tiltą.",
      },
    },
  },
  {
    id: "brn_nm_024",
    category: "brands",
    subTheme: "names",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Xerox — from 'xerography', Greek for 'dry writing' (dry powder toner)",
    emoji: "🖨️",
    translations: {
      en: {
        question: "Xerox comes from 'xerography', Greek for which kind of writing?",
        correct: "Dry writing",
        distractors: ["Light writing", "Fast writing", "Ink writing", "Heat writing", "Copy writing"],
        explanation: "Its copiers used dry powder toner instead of wet ink.",
      },
      lt: {
        question: "Xerox kilo iš xerography — graikiškai kokio rašymo?",
        correct: "Sauso rašymo",
        distractors: ["Šviesos rašymo", "Greito rašymo", "Rašalo rašymo", "Karščio rašymo", "Kopijų rašymo"],
        explanation: "Jos kopijavimo aparatai naudojo sausus miltelius, o ne skystą rašalą.",
      },
    },
  },
  {
    id: "brn_nm_025",
    category: "brands",
    subTheme: "names",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Intel — short for 'Integrated Electronics'",
    emoji: "💻",
    translations: {
      en: {
        question: "The chip maker Intel is short for which two words?",
        correct: "Integrated Electronics",
        distractors: ["Interface Electronics", "Intelligent Engines", "Internal Logic Tools", "Integrated Lenses", "Interlinked Engines"],
        explanation: "The founders simply joined 'integrated' and 'electronics'.",
      },
      lt: {
        question: "Procesorių gamintoja Intel yra kurių dviejų žodžių santrumpa?",
        correct: "Integrated Electronics",
        distractors: ["Interface Electronics", "Intelligent Engines", "Internal Logic Tools", "Integrated Lenses", "Interlinked Engines"],
        explanation: "Įkūrėjai tiesiog sujungė integrated ir electronics.",
      },
    },
  },
  {
    id: "brn_nm_026",
    category: "brands",
    subTheme: "names",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Atari — name from a warning term in the board game Go (a stone is in danger)",
    emoji: "🎮",
    translations: {
      en: {
        question: "Atari took its name from a warning word in which board game?",
        correct: "Go",
        distractors: ["Chess", "Shogi", "Mahjong", "Backgammon", "Checkers"],
        explanation: "In Go, 'atari' warns that a stone is about to be captured.",
      },
      lt: {
        question: "Atari pasiėmė vardą iš įspėjamojo žodžio kuriame stalo žaidime?",
        correct: "Go",
        distractors: ["Šachmatuose", "Šogi", "Madžonge", "Narduose", "Šaškėse"],
        explanation: "Žaidime Go atari įspėja, kad akmuo tuoj bus paimtas.",
      },
    },
  },
  {
    id: "brn_nm_027",
    category: "brands",
    subTheme: "names",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Virgin — Richard Branson's team picked it as they were 'virgins' in business",
    emoji: "✈️",
    translations: {
      en: {
        question: "Richard Branson's brand Virgin got its name because the team was new at what?",
        correct: "Business",
        distractors: ["Music", "Flying", "Travel", "Selling", "Trade"],
        explanation: "They joked they were complete beginners, or 'virgins', in business.",
      },
      lt: {
        question: "Ričardo Bransono ženklas Virgin pavadintas, nes komanda buvo nauja kame?",
        correct: "Versle",
        distractors: ["Muzikoje", "Aviacijoje", "Kelionėse", "Pardavime", "Prekyboje"],
        explanation: "Jie juokavo esą visiški naujokai, arba virgins, versle.",
      },
    },
  },
  {
    id: "brn_nm_028",
    category: "brands",
    subTheme: "names",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "LG — originally 'Lucky Goldstar' (later slogan 'Life's Good')",
    emoji: "📱",
    translations: {
      en: {
        question: "The Korean giant LG originally stood for which two words?",
        correct: "Lucky Goldstar",
        distractors: ["Large Group", "Leading Gear", "Light Glow", "Local Goods", "Long Game"],
        explanation: "Lucky and Goldstar merged; later the slogan became 'Life's Good'.",
      },
      lt: {
        question: "Korėjiečių milžinė LG iš pradžių reiškė kuriuos du žodžius?",
        correct: "Lucky Goldstar",
        distractors: ["Large Group", "Leading Gear", "Light Glow", "Local Goods", "Long Game"],
        explanation: "Lucky ir Goldstar susijungė; vėliau šūkis tapo Life's Good.",
      },
    },
  },
  {
    id: "brn_nm_029",
    category: "brands",
    subTheme: "names",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "WhatsApp — the name is a pun on the greeting 'What's up?'",
    emoji: "💬",
    translations: {
      en: {
        question: "The messaging app WhatsApp's name puns on which everyday greeting?",
        correct: "What's up",
        distractors: ["How are you", "Good day", "Hey there", "What now", "All good"],
        explanation: "It sounds just like asking a friend 'What's up?'.",
      },
      lt: {
        question: "Žinučių programėlės WhatsApp vardas žaidžia su kuriuo kasdieniu pasisveikinimu?",
        correct: "What's up",
        distractors: ["How are you", "Good day", "Hey there", "What now", "All good"],
        explanation: "Jis skamba lygiai kaip draugo klausimas What's up?",
      },
    },
  },
  {
    id: "brn_nm_030",
    category: "brands",
    subTheme: "names",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Yahoo — founders liked the word for a rude brute from Gulliver's Travels",
    emoji: "🔎",
    translations: {
      en: {
        question: "Yahoo took its name from a crude brute invented in which classic book?",
        correct: "Gulliver's Travels",
        distractors: ["Robinson Crusoe", "Treasure Island", "Moby-Dick", "Don Quixote", "Frankenstein"],
        explanation: "The Yahoos are wild, rude humans in Jonathan Swift's story.",
      },
      lt: {
        question: "Yahoo pasiėmė vardą iš grubaus padaro, sukurto kurioje klasikinėje knygoje?",
        correct: "Guliverio kelionėse",
        distractors: ["Robinzone Kruzo", "Lobių saloje", "Mobyje Dike", "Don Kichote", "Frankenšteine"],
        explanation: "Jahai yra laukiniai, grubūs žmonės Džonatano Svifto pasakojime.",
      },
    },
  },

  // ===================== EKSTREMALUS (srities žinovas) =====================
  {
    id: "brn_nm_031",
    category: "brands",
    subTheme: "names",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Starbucks — named after Starbuck, the first mate in Moby-Dick",
    emoji: "☕",
    translations: {
      en: {
        question: "Starbucks is named after a character from which classic novel?",
        correct: "Moby-Dick",
        distractors: ["Treasure Island", "Robinson Crusoe", "The Odyssey", "Gulliver's Travels", "Oliver Twist"],
        explanation: "Starbuck is the calm first mate aboard the whaling ship Pequod.",
      },
      lt: {
        question: "Starbucks pavadintas pagal personažą iš kurio klasikinio romano?",
        correct: "Moby Dick",
        distractors: ["Lobių sala", "Robinzonas Kruzo", "Odisėja", "Guliverio kelionės", "Oliveris Tvistas"],
        explanation: "Starbukas — ramus banginių laivo Pequod vyresnysis kapitono padėjėjas.",
      },
    },
  },
  {
    id: "brn_nm_032",
    category: "brands",
    subTheme: "names",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Asus — name from the last four letters of 'Pegasus'",
    emoji: "💻",
    translations: {
      en: {
        question: "The computer brand Asus is taken from the end of which mythical horse?",
        correct: "Pegasus",
        distractors: ["Unicorn", "Phoenix", "Griffin", "Centaur", "Sleipnir"],
        explanation: "They dropped the first letters of Pegasus to sit high in listings.",
      },
      lt: {
        question: "Kompiuterių ženklas Asus paimtas iš kurio mitinio žirgo galo?",
        correct: "Pegaso",
        distractors: ["Vienaragio", "Fenikso", "Grifo", "Kentauro", "Sleipniro"],
        explanation: "Jie nubraukė pirmąsias Pegasus raides, kad būtų aukščiau sąrašuose.",
      },
    },
  },
  {
    id: "brn_nm_033",
    category: "brands",
    subTheme: "names",
    level: "ekstremalus",
    isTrap: true,
    sourceVerified: "Wi-Fi — a catchy name playing on 'hi-fi'; 'Wireless Fidelity' is a back-formed myth",
    emoji: "📶",
    translations: {
      en: {
        question: "The name Wi-Fi is often wrongly expanded to which phrase?",
        correct: "Wireless Fidelity",
        distractors: ["Wireless Frequency", "Wide Function", "Wired Finder", "Window Field", "Web Finder"],
        explanation: "In truth Wi-Fi was just a snappy play on the old word 'hi-fi'.",
      },
      lt: {
        question: "Pavadinimas Wi-Fi dažnai klaidingai išplečiamas į kurią frazę?",
        correct: "Wireless Fidelity",
        distractors: ["Wireless Frequency", "Wide Function", "Wired Finder", "Window Field", "Web Finder"],
        explanation: "Iš tikrųjų Wi-Fi buvo tik skambus senojo žodžio hi-fi žaismas.",
      },
    },
  },
  {
    id: "brn_nm_034",
    category: "brands",
    subTheme: "names",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Adobe — named after Adobe Creek behind co-founder John Warnock's house",
    emoji: "💻",
    translations: {
      en: {
        question: "Adobe software is named after a creek; 'adobe' also means which material?",
        correct: "Mud brick",
        distractors: ["Marble", "Concrete", "Timber", "Sandstone", "Plaster"],
        explanation: "Adobe Creek ran behind a co-founder's home in California.",
      },
      lt: {
        question: "Adobe programos pavadintos upelio vardu; adobe dar reiškia kurią medžiagą?",
        correct: "Molio plytą",
        distractors: ["Marmurą", "Betoną", "Medieną", "Smiltainį", "Tinką"],
        explanation: "Adobe upelis tekėjo už vieno bendraįkūrio namo Kalifornijoje.",
      },
    },
  },
  {
    id: "brn_nm_035",
    category: "brands",
    subTheme: "names",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Skype — shortened from 'Sky peer-to-peer' (Skyper → Skype)",
    emoji: "💬",
    translations: {
      en: {
        question: "Skype's name was shortened from 'Sky' plus which phrase?",
        correct: "Peer-to-peer",
        distractors: ["Phone line", "People talk", "Internet call", "Provider net", "Open line"],
        explanation: "'Sky-Peer-to-Peer' became 'Skyper', then simply Skype.",
      },
      lt: {
        question: "Skype vardas sutrumpintas iš Sky ir kurios frazės?",
        correct: "Peer-to-peer",
        distractors: ["Phone line", "People talk", "Internet call", "Provider net", "Open line"],
        explanation: "Sky-Peer-to-Peer virto Skyper, o tada tiesiog Skype.",
      },
    },
  },
  {
    id: "brn_nm_036",
    category: "brands",
    subTheme: "names",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Instagram — blend of 'instant camera' and 'telegram'",
    emoji: "📷",
    translations: {
      en: {
        question: "Instagram's name blends 'instant camera' with which word?",
        correct: "Telegram",
        distractors: ["Program", "Diagram", "Hologram", "Anagram", "Kilogram"],
        explanation: "'Instant' plus 'telegram' captured quick photos sent to friends.",
      },
      lt: {
        question: "Instagram vardas jungia momentinį fotoaparatą su kuriuo žodžiu?",
        correct: "Telegrama",
        distractors: ["Programa", "Diagrama", "Holograma", "Anagrama", "Kilograma"],
        explanation: "Instant ir telegram perteikė greitas nuotraukas, siunčiamas draugams.",
      },
    },
  },
  {
    id: "brn_nm_037",
    category: "brands",
    subTheme: "names",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Verizon — blend of Latin 'veritas' (truth) and 'horizon'",
    emoji: "📱",
    translations: {
      en: {
        question: "Verizon's name blends the Latin for 'truth' with which word?",
        correct: "Horizon",
        distractors: ["Vision", "Region", "Season", "Reason", "Origin"],
        explanation: "'Veritas' (truth) plus 'horizon' formed the name Verizon.",
      },
      lt: {
        question: "Verizon vardas jungia lotynišką tiesą su kuriuo žodžiu?",
        correct: "Horizontas",
        distractors: ["Vizija", "Regionas", "Sezonas", "Priežastis", "Ištaka"],
        explanation: "Veritas (tiesa) ir horizon sudarė vardą Verizon.",
      },
    },
  },
  {
    id: "brn_nm_038",
    category: "brands",
    subTheme: "names",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Google — early research project was named 'BackRub'",
    emoji: "🔎",
    translations: {
      en: {
        question: "Before its famous name, Google was a project called what?",
        correct: "BackRub",
        distractors: ["WebCrawl", "PageNet", "SearchBox", "LinkRank", "NetSpider"],
        explanation: "The early name described how it studied a page's back links.",
      },
      lt: {
        question: "Prieš garsųjį vardą Google buvo projektas pavadinimu kaip?",
        correct: "BackRub",
        distractors: ["WebCrawl", "PageNet", "SearchBox", "LinkRank", "NetSpider"],
        explanation: "Ankstyvas vardas apibūdino, kaip jis tyrė puslapio nuorodas atgal.",
      },
    },
  },
  {
    id: "brn_nm_039",
    category: "brands",
    subTheme: "names",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "WD-40 — name means 'Water Displacement, 40th formula'",
    emoji: "🧴",
    translations: {
      en: {
        question: "The spray WD-40 is named because it was the 40th try to make a what?",
        correct: "Water displacer",
        distractors: ["Wood polish", "Weld cleaner", "Wax coating", "Wire degreaser", "Window spray"],
        explanation: "WD-40 stands for 'Water Displacement, 40th formula'.",
      },
      lt: {
        question: "Purškiklis WD-40 pavadintas, nes tai buvo 40-as bandymas sukurti ką?",
        correct: "Vandens slopintuvą",
        distractors: ["Medžio politūrą", "Suvirinimo valiklį", "Vaško dangą", "Vielų valiklį", "Langų purškiklį"],
        explanation: "WD-40 reiškia Water Displacement, 40-oji formulė.",
      },
    },
  },
  {
    id: "brn_nm_040",
    category: "brands",
    subTheme: "names",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Uber — from the German word 'über', meaning 'above' or 'super'",
    emoji: "📱",
    translations: {
      en: {
        question: "The ride app Uber takes its name from a German word meaning what?",
        correct: "Above",
        distractors: ["Under", "Fast", "Easy", "Best", "Around"],
        explanation: "'Über' means 'above' or 'superior' in German.",
      },
      lt: {
        question: "Pavėžėjimo programėlė Uber pavadinta pagal vokišką žodį, reiškiantį ką?",
        correct: "Virš",
        distractors: ["Po", "Greitai", "Lengvai", "Geriausia", "Aplink"],
        explanation: "Über vokiškai reiškia virš arba pranašesnis.",
      },
    },
  },
];
