/**
 * brandsFashion — 👟 „Mada ir daiktai" potemė (tema „Prekių ženklų istorijos").
 *
 * MAŽAS FAILAS pagal potemę. 40 klausimų (10/lygiui). Drabužių, avalynės, žaislų
 * ir kasdienių daiktų prekių ženklų ISTORIJOS (Adidas/Puma brolių vaidas, LEGO,
 * IKEA, Velcro ...). Tik istoriniai/įsitvirtinę faktai — JOKIOS reklamos.
 *
 * TAISYKLĖS: 1 teisingas + 5 distraktoriai; ≤46 simb.; teisingas NE ilgiausias >+5;
 * LT be vidinių kabučių; jokio atsakymo klausime; EMOJI NEUTRALUS (neišduoda atsakymo).
 */

import { TriviaQuestion } from "./triviaTypes";

export const BRANDS_FASHION: TriviaQuestion[] = [
  // ===================== LENGVAS (9–12 m. vaikas) =====================
  {
    id: "brn_fa_001",
    category: "brands",
    subTheme: "fashion",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "LEGO — name from Danish 'leg godt' (play well); founded Billund, Denmark 1932",
    emoji: "🧩",
    translations: {
      en: {
        question: "Which Danish toy brand is famous for small studded plastic bricks?",
        correct: "LEGO",
        distractors: ["Playmobil", "Meccano", "K'Nex", "Etch A Sketch", "Mega Bloks"],
        explanation: "Its Danish name comes from 'leg godt', meaning 'play well'.",
      },
      lt: {
        question: "Kuris danų žaislų ženklas garsus mažomis plastiko kaladėlėmis su kaišteliais?",
        correct: "LEGO",
        distractors: ["Playmobil", "Meccano", "K'Nex", "Etch A Sketch", "Mega Bloks"],
        explanation: "Daniškas vardas kilo iš leg godt — žaisk gerai.",
      },
    },
  },
  {
    id: "brn_fa_002",
    category: "brands",
    subTheme: "fashion",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Hula Hoop — spinning hoop popularized by Wham-O in the 1958 craze",
    emoji: "🧸",
    translations: {
      en: {
        question: "Which toy is a light hoop you spin around your waist?",
        correct: "Hula Hoop",
        distractors: ["Frisbee", "Yo-yo", "Pogo stick", "Skipping rope", "Spinning top"],
        explanation: "Wham-O sold millions of them during a huge 1950s craze.",
      },
      lt: {
        question: "Kuris žaislas yra lengvas lankas, kurį suki aplink liemenį?",
        correct: "Hula Hoop",
        distractors: ["Frisbee", "Jo-jo", "Pogo lazda", "Šokdynė", "Vilkelis"],
        explanation: "Wham-O pardavė jų milijonus per didžiulę 6-ojo dešimtmečio madą.",
      },
    },
  },
  {
    id: "brn_fa_003",
    category: "brands",
    subTheme: "fashion",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "IKEA — Swedish flat-pack furniture; products carry Swedish names",
    emoji: "🛒",
    translations: {
      en: {
        question: "Which Swedish store sells flat-pack furniture with Swedish names?",
        correct: "IKEA",
        distractors: ["Jysk", "Argos", "Habitat", "Conforama", "Leroy Merlin"],
        explanation: "You carry it home in a flat box and build it yourself.",
      },
      lt: {
        question: "Kuri švedų parduotuvė prekiauja plokščiose dėžėse supakuotais baldais?",
        correct: "IKEA",
        distractors: ["Jysk", "Argos", "Habitat", "Conforama", "Leroy Merlin"],
        explanation: "Baldą parsineši plokščioje dėžėje ir susirenki pats.",
      },
    },
  },
  {
    id: "brn_fa_004",
    category: "brands",
    subTheme: "fashion",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Puma — logo is a leaping puma; founded by Rudolf Dassler",
    emoji: "👟",
    translations: {
      en: {
        question: "Which sportswear brand has a leaping wild cat as its logo?",
        correct: "Puma",
        distractors: ["Adidas", "Nike", "Reebok", "Fila", "Kappa"],
        explanation: "It was founded by Rudolf Dassler, brother of the Adidas founder.",
      },
      lt: {
        question: "Kurio sporto prekės ženklo logotipe pavaizduota šuoliuojanti laukinė katė?",
        correct: "Puma",
        distractors: ["Adidas", "Nike", "Reebok", "Fila", "Kappa"],
        explanation: "Jį įkūrė Rudolfas Dassleris, Adidas įkūrėjo brolis.",
      },
    },
  },
  {
    id: "brn_fa_005",
    category: "brands",
    subTheme: "fashion",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Levi's — Levi Strauss, one of the oldest blue jeans makers (1853)",
    emoji: "👖",
    translations: {
      en: {
        question: "Which brand is one of the oldest makers of blue jeans?",
        correct: "Levi's",
        distractors: ["Wrangler", "Lee", "Diesel", "Gap", "Pepe"],
        explanation: "Levi Strauss sold sturdy riveted trousers in the Gold Rush era.",
      },
      lt: {
        question: "Kuris prekės ženklas yra vienas seniausių mėlynų džinsų gamintojų?",
        correct: "Levi's",
        distractors: ["Wrangler", "Lee", "Diesel", "Gap", "Pepe"],
        explanation: "Levis Straussas Aukso karštinės laikais pardavinėjo tvirtas kniedytas kelnes.",
      },
    },
  },
  {
    id: "brn_fa_006",
    category: "brands",
    subTheme: "fashion",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Rubik's Cube — twist puzzle matching colours, invented by Ernő Rubik",
    emoji: "🧩",
    translations: {
      en: {
        question: "On a Rubik's Cube you twist the sides to match what?",
        correct: "Colours",
        distractors: ["Numbers", "Letters", "Shapes", "Animals", "Stars"],
        explanation: "Hungarian Ernő Rubik first built it to study how parts move without it falling apart.",
      },
      lt: {
        question: "Rubiko kubelyje sukioji puses, kad sutaptų kas?",
        correct: "Spalvos",
        distractors: ["Skaičiai", "Raidės", "Figūros", "Gyvūnai", "Žvaigždės"],
        explanation: "Vengras Ernő Rubikas jį sukūrė tirdamas, kaip dalys gali judėti kubeliui nesubyrant.",
      },
    },
  },
  {
    id: "brn_fa_007",
    category: "brands",
    subTheme: "fashion",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Barbie — Mattel doll named after Barbara; boyfriend Ken named after a son",
    emoji: "🧸",
    translations: {
      en: {
        question: "Which Mattel doll has a long-time boyfriend named Ken?",
        correct: "Barbie",
        distractors: ["Bratz", "Sindy", "Polly", "Cindy", "Lottie"],
        explanation: "Barbie and Ken were named after the maker's daughter and son.",
      },
      lt: {
        question: "Kuri Mattel lėlė jau seniai turi vaikiną, vardu Kenas?",
        correct: "Barbė",
        distractors: ["Bratz", "Sindy", "Polly", "Cindy", "Lottie"],
        explanation: "Barbė ir Kenas pavadinti gamintojos dukters ir sūnaus vardais.",
      },
    },
  },
  {
    id: "brn_fa_008",
    category: "brands",
    subTheme: "fashion",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Crocs — foam clogs full of ventilation holes",
    emoji: "👟",
    translations: {
      en: {
        question: "Which brand makes light foam clogs full of holes?",
        correct: "Crocs",
        distractors: ["Birkenstock", "Skechers", "Vans", "Adidas", "Havaianas"],
        explanation: "The holes let water out and keep the soft clogs cool.",
      },
      lt: {
        question: "Kuris ženklas gamina lengvas putplasčio klumpes su skylutėmis?",
        correct: "Crocs",
        distractors: ["Birkenstock", "Skechers", "Vans", "Adidas", "Havaianas"],
        explanation: "Skylutės išleidžia vandenį ir laiko minkštas klumpes vėsias.",
      },
    },
  },
  {
    id: "brn_fa_009",
    category: "brands",
    subTheme: "fashion",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Rolex — five-point crown logo; Swiss luxury watch brand",
    emoji: "⌚",
    translations: {
      en: {
        question: "Which luxury watch brand uses a five-point crown as its logo?",
        correct: "Rolex",
        distractors: ["Omega", "Casio", "Seiko", "Tissot", "Swatch"],
        explanation: "The little crown is meant to signal a king-like quality.",
      },
      lt: {
        question: "Kuris prabangus laikrodžių ženklas naudoja penkiašakę karūną logotipe?",
        correct: "Rolex",
        distractors: ["Omega", "Casio", "Seiko", "Tissot", "Swatch"],
        explanation: "Maža karūnėlė turi reikšti karališką kokybę.",
      },
    },
  },
  {
    id: "brn_fa_010",
    category: "brands",
    subTheme: "fashion",
    level: "lengvas",
    isTrap: true,
    sourceVerified: "Play-Doh — first sold as a wallpaper cleaner before becoming a toy",
    emoji: "🧸",
    translations: {
      en: {
        question: "Which colourful modelling dough comes in little tubs for kids?",
        correct: "Play-Doh",
        distractors: ["Plasticine", "Slime", "Crayola", "Fimo", "Silly Putty"],
        explanation: "Surprise: it was first sold as a cleaner for dirty wallpaper!",
      },
      lt: {
        question: "Koks spalvotas lipdymo tešlukas parduodamas mažuose indeliuose vaikams?",
        correct: "Play-Doh",
        distractors: ["Plastilinas", "Gličas", "Crayola", "Fimo", "Silly Putty"],
        explanation: "Netikėta: iš pradžių jis parduotas kaip nešvarių tapetų valiklis!",
      },
    },
  },

  // ===================== VIDUTINIS (12–18 m. paauglys) =====================
  {
    id: "brn_fa_011",
    category: "brands",
    subTheme: "fashion",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Adidas and Puma founded by brothers Adolf and Rudolf Dassler after a feud",
    emoji: "👟",
    translations: {
      en: {
        question: "Adidas and Puma were started by two feuding men — how were they related?",
        correct: "Brothers",
        distractors: ["Cousins", "Friends", "Twins", "Schoolmates", "Neighbours"],
        explanation: "Adolf and Rudolf Dassler split after a bitter falling-out.",
      },
      lt: {
        question: "Adidas ir Puma įkūrė du susipykę vyrai — kuo jie buvo vienas kitam?",
        correct: "Broliai",
        distractors: ["Pusbroliai", "Draugai", "Dvyniai", "Bendraklasiai", "Kaimynai"],
        explanation: "Adolfas ir Rudolfas Dassleriai išsiskyrė po kartaus kivirčo.",
      },
    },
  },
  {
    id: "brn_fa_012",
    category: "brands",
    subTheme: "fashion",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "LEGO — name from Danish 'leg godt' ('play well')",
    emoji: "🧩",
    translations: {
      en: {
        question: "The name LEGO comes from a Danish phrase meaning what?",
        correct: "Play well",
        distractors: ["Build it", "Have fun", "Little block", "Good toy", "Play more"],
        explanation: "By luck, 'lego' also means 'I put together' in Latin.",
      },
      lt: {
        question: "Pavadinimas LEGO kilo iš daniško posakio, reiškiančio ką?",
        correct: "Žaisk gerai",
        distractors: ["Statyk", "Linksminkis", "Maža kaladė", "Geras žaislas", "Žaisk daugiau"],
        explanation: "Atsitiktinai lego lotyniškai dar reiškia surenku.",
      },
    },
  },
  {
    id: "brn_fa_013",
    category: "brands",
    subTheme: "fashion",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Nike — named after the Greek goddess of victory",
    emoji: "👟",
    translations: {
      en: {
        question: "Nike is named after the Greek goddess of what?",
        correct: "Victory",
        distractors: ["Wisdom", "Love", "Speed", "War", "Beauty"],
        explanation: "The swoosh logo is said to suggest the goddess's wing.",
      },
      lt: {
        question: "Nike pavadintas pagal graikų deivę, valdančią ką?",
        correct: "Pergalę",
        distractors: ["Išmintį", "Meilę", "Greitį", "Karą", "Grožį"],
        explanation: "Sakoma, kad logotipo brūkšnys primena deivės sparną.",
      },
    },
  },
  {
    id: "brn_fa_014",
    category: "brands",
    subTheme: "fashion",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Velcro — name from French 'velours' (velvet) + 'crochet' (hook)",
    emoji: "🧥",
    translations: {
      en: {
        question: "The name Velcro joins the French words for velvet and what?",
        correct: "Hook",
        distractors: ["Loop", "Cloth", "String", "Knot", "Tape"],
        explanation: "Its inventor copied burrs that stuck to his dog's fur on a walk.",
      },
      lt: {
        question: "Pavadinimas Velcro jungia prancūziškus žodžius aksomas ir kas?",
        correct: "Kabliukas",
        distractors: ["Kilpa", "Audinys", "Virvė", "Mazgas", "Juosta"],
        explanation: "Kūrėjas nukopijavo dagius, kurie per pasivaikščiojimą prilipo prie jo šuns.",
      },
    },
  },
  {
    id: "brn_fa_015",
    category: "brands",
    subTheme: "fashion",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Ray-Ban — Aviator sunglasses developed for US Army Air Corps pilots",
    emoji: "🕶️",
    translations: {
      en: {
        question: "Ray-Ban's Aviator sunglasses were first made for which job?",
        correct: "Pilots",
        distractors: ["Sailors", "Drivers", "Skiers", "Soldiers", "Police"],
        explanation: "They were built to 'ban' harsh sun rays for American aviators.",
      },
      lt: {
        question: "Ray-Ban Aviator akiniai nuo saulės pirmiausia sukurti kuriai profesijai?",
        correct: "Lakūnams",
        distractors: ["Jūreiviams", "Vairuotojams", "Slidininkams", "Kariams", "Policijai"],
        explanation: "Jie sukurti taip, kad sulaikytų ryškius saulės spindulius amerikiečių lakūnams.",
      },
    },
  },
  {
    id: "brn_fa_016",
    category: "brands",
    subTheme: "fashion",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Dr. Martens — air-cushioned boots invented by Dr. Klaus Märtens after a foot injury",
    emoji: "👢",
    translations: {
      en: {
        question: "Dr. Martens boots were invented by a German doctor to help what?",
        correct: "A hurt foot",
        distractors: ["Bad knees", "Flat feet", "Cold toes", "A sore back", "Weak ankles"],
        explanation: "He added air cushions after hurting his foot in a skiing fall.",
      },
      lt: {
        question: "Dr. Martens batus sukūrė vokiečių gydytojas, kad padėtų kam?",
        correct: "Sužeistai pėdai",
        distractors: ["Skaudantiems keliams", "Plokščioms pėdoms", "Šąlantiems pirštams", "Skaudančiai nugarai", "Silpnoms kulkšnims"],
        explanation: "Jis pridėjo oro pagalvėles susižeidęs pėdą slidinėdamas.",
      },
    },
  },
  {
    id: "brn_fa_017",
    category: "brands",
    subTheme: "fashion",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Lacoste — crocodile logo from René Lacoste's tennis nickname",
    emoji: "👕",
    translations: {
      en: {
        question: "The Lacoste crocodile came from the nickname of which kind of athlete?",
        correct: "A tennis player",
        distractors: ["A racing driver", "A golfer", "A swimmer", "A skier", "A sailor"],
        explanation: "René Lacoste was nicknamed 'the Crocodile' on the tennis court.",
      },
      lt: {
        question: "Lacoste krokodilas kilo iš kokio sportininko pravardės?",
        correct: "Tenisininko",
        distractors: ["Lenktynininko", "Golfininko", "Plaukiko", "Slidininko", "Buriuotojo"],
        explanation: "René Lacoste teniso korte buvo pramintas Krokodilu.",
      },
    },
  },
  {
    id: "brn_fa_018",
    category: "brands",
    subTheme: "fashion",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "IKEA — acronym: Ingvar Kamprad + Elmtaryd (farm) + Agunnaryd (village)",
    emoji: "🛒",
    translations: {
      en: {
        question: "IKEA's name combines the founder's initials with his what?",
        correct: "Farm and village",
        distractors: ["City and street", "School and town", "Shop and road", "Lake and hill", "Wife and son"],
        explanation: "Ingvar Kamprad added his Elmtaryd farm and Agunnaryd village.",
      },
      lt: {
        question: "IKEA pavadinimas jungia įkūrėjo inicialus su jo kuo?",
        correct: "Ūkiu ir kaimu",
        distractors: ["Miestu ir gatve", "Mokykla ir miesteliu", "Parduotuve ir keliu", "Ežeru ir kalva", "Žmona ir sūnumi"],
        explanation: "Ingvaras Kampradas pridėjo Elmtaryd ūkį ir Agunnaryd kaimą.",
      },
    },
  },
  {
    id: "brn_fa_019",
    category: "brands",
    subTheme: "fashion",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Teddy bear — named after US President Theodore 'Teddy' Roosevelt",
    emoji: "🧸",
    translations: {
      en: {
        question: "The teddy bear was named after which US president?",
        correct: "Theodore Roosevelt",
        distractors: ["Abraham Lincoln", "George Washington", "Andrew Jackson", "Woodrow Wilson", "Calvin Coolidge"],
        explanation: "Teddy Roosevelt famously refused to shoot a bear cub on a hunt.",
      },
      lt: {
        question: "Pliušinis meškiukas pavadintas kurio JAV prezidento vardu?",
        correct: "Theodore Roosevelt",
        distractors: ["Abraham Lincoln", "George Washington", "Andrew Jackson", "Woodrow Wilson", "Calvin Coolidge"],
        explanation: "Teddy Rooseveltas medžioklėje atsisakė nušauti meškiuką.",
      },
    },
  },
  {
    id: "brn_fa_020",
    category: "brands",
    subTheme: "fashion",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Monopoly — property board game with play money, houses and hotels",
    emoji: "🎲",
    translations: {
      en: {
        question: "Which classic board game uses play money to buy streets and houses?",
        correct: "Monopoly",
        distractors: ["Cluedo", "Risk", "Scrabble", "The Game of Life", "Sorry!"],
        explanation: "Its top-hatted mascot is the cheerful Rich Uncle Pennybags.",
      },
      lt: {
        question: "Kuris klasikinis stalo žaidimas naudoja žaislinius pinigus gatvėms pirkti?",
        correct: "Monopolis",
        distractors: ["Cluedo", "Risk", "Scrabble", "Gyvenimo žaidimas", "Sorry!"],
        explanation: "Jo talismanas su cilindru — linksmasis dėdė Pinigėlis.",
      },
    },
  },

  // ===================== SUNKUS (suaugęs, kuris domisi) =====================
  {
    id: "brn_fa_021",
    category: "brands",
    subTheme: "fashion",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Timberland — yellow waterproof work boots, embraced by hip-hop culture",
    emoji: "👢",
    translations: {
      en: {
        question: "Which brand is famous for yellow waterproof work boots loved by hip-hop fans?",
        correct: "Timberland",
        distractors: ["Caterpillar", "Red Wing", "Dr. Martens", "Wolverine", "Sorel"],
        explanation: "The sturdy wheat-coloured boot became a 1990s street icon.",
      },
      lt: {
        question: "Kuris ženklas garsus geltonais neperšlampamais darbo batais, mėgstamais hiphopo?",
        correct: "Timberland",
        distractors: ["Caterpillar", "Red Wing", "Dr. Martens", "Wolverine", "Sorel"],
        explanation: "Tvirtas kviečių spalvos batas tapo 10-ojo dešimtmečio gatvės simboliu.",
      },
    },
  },
  {
    id: "brn_fa_022",
    category: "brands",
    subTheme: "fashion",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Tupperware — sold mostly through home 'Tupperware parties' (Brownie Wise)",
    emoji: "🛒",
    translations: {
      en: {
        question: "Tupperware became famous through which way of selling?",
        correct: "Home parties",
        distractors: ["TV adverts", "Door knocking", "Mail order", "Street stalls", "Radio spots"],
        explanation: "Saleswoman Brownie Wise built the friendly home-party model.",
      },
      lt: {
        question: "Tupperware išgarsėjo per kokį pardavimo būdą?",
        correct: "Namų vakarėlius",
        distractors: ["TV reklamas", "Beldimą į duris", "Paštą", "Gatvės prekystalius", "Radijo reklamas"],
        explanation: "Pardavėja Brownie Wise sukūrė jaukių namų vakarėlių modelį.",
      },
    },
  },
  {
    id: "brn_fa_023",
    category: "brands",
    subTheme: "fashion",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Zipper — early version marketed as the 'clasp locker'; 'zipper' name from B.F. Goodrich",
    emoji: "🧥",
    translations: {
      en: {
        question: "The zipper was first sold under which earlier name?",
        correct: "Clasp locker",
        distractors: ["Slide hook", "Snap line", "Quick clip", "Tooth lock", "Grip rail"],
        explanation: "The snappy word 'zipper' came later from a brand of rubber boots.",
      },
      lt: {
        question: "Užtrauktukas iš pradžių buvo parduodamas kokiu ankstesniu pavadinimu?",
        correct: "Clasp locker",
        distractors: ["Slide hook", "Snap line", "Quick clip", "Tooth lock", "Grip rail"],
        explanation: "Skambus žodis zipper atsirado vėliau, nuo guminių batų prekės ženklo.",
      },
    },
  },
  {
    id: "brn_fa_024",
    category: "brands",
    subTheme: "fashion",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Post-it Notes — born from a 3M chemist's accidental weak (low-tack) adhesive",
    emoji: "📄",
    translations: {
      en: {
        question: "Post-it Notes were born from a 3M scientist's accidental what?",
        correct: "Weak glue",
        distractors: ["Strong glue", "New paper", "Bright dye", "Cheap ink", "Soft cloth"],
        explanation: "A 'failed' weak adhesive turned out perfect for re-stickable notes.",
      },
      lt: {
        question: "Lipnūs lapeliai Post-it gimė iš 3M mokslininko atsitiktinio ko?",
        correct: "Silpnų klijų",
        distractors: ["Stiprių klijų", "Naujo popieriaus", "Ryškaus dažo", "Pigaus rašalo", "Minkšto audinio"],
        explanation: "Nevykę silpni klijai pasirodė puikūs perklijuojamiems lapeliams.",
      },
    },
  },
  {
    id: "brn_fa_025",
    category: "brands",
    subTheme: "fashion",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Chanel No. 5 — launched 1921 by designer Coco Chanel (the fifth sample)",
    emoji: "🌸",
    translations: {
      en: {
        question: "The famous No. 5 perfume was launched by which fashion designer?",
        correct: "Coco Chanel",
        distractors: ["Christian Dior", "Yves Saint Laurent", "Jeanne Lanvin", "Nina Ricci", "Elsa Schiaparelli"],
        explanation: "She chose the fifth sample on the table, so it became 'No. 5'.",
      },
      lt: {
        question: "Garsiuosius kvepalus No. 5 sukūrė kuri mados dizainerė?",
        correct: "Coco Chanel",
        distractors: ["Christian Dior", "Yves Saint Laurent", "Jeanne Lanvin", "Nina Ricci", "Elsa Schiaparelli"],
        explanation: "Ji pasirinko penktą mėginį ant stalo, todėl atsirado No. 5.",
      },
    },
  },
  {
    id: "brn_fa_026",
    category: "brands",
    subTheme: "fashion",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Burberry — trench coat developed from gabardine for WWI officers",
    emoji: "🧥",
    translations: {
      en: {
        question: "Burberry's classic trench coat was first developed for whom?",
        correct: "Soldiers",
        distractors: ["Sailors", "Farmers", "Hunters", "Climbers", "Firefighters"],
        explanation: "Its waterproof gabardine coats were worn by officers in the trenches.",
      },
      lt: {
        question: "Klasikinis Burberry trenčkotas pirmiausia buvo sukurtas kam?",
        correct: "Kariams",
        distractors: ["Jūreiviams", "Ūkininkams", "Medžiotojams", "Alpinistams", "Ugniagesiams"],
        explanation: "Neperšlampamus gabardino paltus dėvėjo karininkai apkasuose.",
      },
    },
  },
  {
    id: "brn_fa_027",
    category: "brands",
    subTheme: "fashion",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Hermès Birkin bag — named after actress and singer Jane Birkin (1984)",
    emoji: "👜",
    translations: {
      en: {
        question: "The Hermès Birkin handbag is named after which famous person?",
        correct: "Jane Birkin",
        distractors: ["Grace Kelly", "Audrey Hepburn", "Brigitte Bardot", "Jackie Kennedy", "Twiggy"],
        explanation: "The bag was designed after she met the boss on a flight in 1984.",
      },
      lt: {
        question: "Hermès rankinė Birkin pavadinta kurio garsaus žmogaus vardu?",
        correct: "Jane Birkin",
        distractors: ["Grace Kelly", "Audrey Hepburn", "Brigitte Bardot", "Jackie Kennedy", "Twiggy"],
        explanation: "Rankinė sukurta po jos pokalbio su vadovu lėktuve 1984 m.",
      },
    },
  },
  {
    id: "brn_fa_028",
    category: "brands",
    subTheme: "fashion",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Swatch — Swiss brand; 'Swatch' = 'second watch'; revived Swiss watchmaking 1980s",
    emoji: "⌚",
    translations: {
      en: {
        question: "The colourful, cheap Swatch watches come from which country?",
        correct: "Switzerland",
        distractors: ["Japan", "Germany", "USA", "France", "Italy"],
        explanation: "The name means 'second watch'; it rescued Swiss watchmaking in the 1980s.",
      },
      lt: {
        question: "Spalvingi, nebrangūs Swatch laikrodžiai kilę iš kurios šalies?",
        correct: "Šveicarijos",
        distractors: ["Japonijos", "Vokietijos", "JAV", "Prancūzijos", "Italijos"],
        explanation: "Vardas reiškia antrąjį laikrodį; jis išgelbėjo Šveicarijos laikrodininkystę.",
      },
    },
  },
  {
    id: "brn_fa_029",
    category: "brands",
    subTheme: "fashion",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Converse All Star — promoted by basketball player and salesman Chuck Taylor",
    emoji: "👟",
    translations: {
      en: {
        question: "The classic Converse basketball shoe is named after which person?",
        correct: "Chuck Taylor",
        distractors: ["Jack Purcell", "Stan Smith", "Michael Air", "John Wood", "Bob Cousy"],
        explanation: "Player-salesman Chuck Taylor pushed the All Star so hard he got his name on it.",
      },
      lt: {
        question: "Klasikinis Converse krepšinio batas pavadintas kurio žmogaus vardu?",
        correct: "Chuck Taylor",
        distractors: ["Jack Purcell", "Stan Smith", "Michael Air", "John Wood", "Bob Cousy"],
        explanation: "Žaidėjas ir pardavėjas Chuckas Tayloras taip reklamavo batą, kad gavo jį savo vardu.",
      },
    },
  },
  {
    id: "brn_fa_030",
    category: "brands",
    subTheme: "fashion",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Bic — known for cheap pens, disposable lighters and razors (Marcel Bich)",
    emoji: "🖊️",
    translations: {
      en: {
        question: "Besides cheap pens, Bic is hugely famous for which flame product?",
        correct: "Lighters",
        distractors: ["Toasters", "Candles", "Matches", "Stoves", "Torches"],
        explanation: "Bic mass-produces disposable lighters and razors as well as pens.",
      },
      lt: {
        question: "Be pigių rašiklių, Bic itin garsus kuriuo liepsnos gaminiu?",
        correct: "Žiebtuvėliais",
        distractors: ["Skrudintuvais", "Žvakėmis", "Degtukais", "Viryklėmis", "Deglais"],
        explanation: "Bic masiškai gamina vienkartinius žiebtuvėlius ir skustuvus, ne tik rašiklius.",
      },
    },
  },

  // ===================== EKSTREMALUS (srities žinovas) =====================
  {
    id: "brn_fa_031",
    category: "brands",
    subTheme: "fashion",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Adidas and Puma both founded in Herzogenaurach, Germany; the feud split the town",
    emoji: "👟",
    translations: {
      en: {
        question: "Adidas and Puma were both founded in which single German town?",
        correct: "Herzogenaurach",
        distractors: ["Schweinfurt", "Regensburg", "Nuremberg", "Bayreuth", "Würzburg"],
        explanation: "The brothers' feud split the small town into two loyal camps.",
      },
      lt: {
        question: "Adidas ir Puma abu įkurti kuriame viename Vokietijos miestelyje?",
        correct: "Herzogenaurach",
        distractors: ["Schweinfurt", "Regensburg", "Niurnbergas", "Bayreuth", "Würzburg"],
        explanation: "Brolių vaidas padalijo miestelį į dvi ištikimas stovyklas.",
      },
    },
  },
  {
    id: "brn_fa_032",
    category: "brands",
    subTheme: "fashion",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Rubik's Cube — originally sold as the 'Magic Cube' (Bűvös Kocka)",
    emoji: "🧩",
    translations: {
      en: {
        question: "The Rubik's Cube was first sold under which earlier name?",
        correct: "Magic Cube",
        distractors: ["Colour Cube", "Puzzle Box", "Twist Cube", "Wonder Cube", "Hungary Cube"],
        explanation: "Ernő Rubik's 'Bűvös Kocka' reached the West as the Magic Cube.",
      },
      lt: {
        question: "Rubiko kubelis iš pradžių buvo parduodamas kokiu ankstesniu pavadinimu?",
        correct: "Magic Cube",
        distractors: ["Colour Cube", "Puzzle Box", "Twist Cube", "Wonder Cube", "Hungary Cube"],
        explanation: "Ernő Rubiko Bűvös Kocka Vakarus pasiekė kaip Magic Cube.",
      },
    },
  },
  {
    id: "brn_fa_033",
    category: "brands",
    subTheme: "fashion",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Levi's — riveted jeans patented in 1873 with tailor Jacob Davis",
    emoji: "👖",
    translations: {
      en: {
        question: "Levi's riveted jeans were patented with which partner in 1873?",
        correct: "Jacob Davis",
        distractors: ["John Stetson", "Henry Ford", "Levi Junior", "Sam Walton", "Jack Lee"],
        explanation: "Tailor Jacob Davis had the rivet idea and teamed up with Levi Strauss.",
      },
      lt: {
        question: "Levi's kniedyti džinsai 1873 m. patentuoti su kuriuo partneriu?",
        correct: "Jacob Davis",
        distractors: ["John Stetson", "Henry Ford", "Levi Junior", "Sam Walton", "Jack Lee"],
        explanation: "Siuvėjas Jacobas Davisas sugalvojo kniedes ir susidėjo su Leviu Straussu.",
      },
    },
  },
  {
    id: "brn_fa_034",
    category: "brands",
    subTheme: "fashion",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Nike swoosh designed by student Carolyn Davidson for about $35 in 1971",
    emoji: "👟",
    translations: {
      en: {
        question: "Nike's swoosh logo was designed by a student paid roughly how much?",
        correct: "35 dollars",
        distractors: ["350 dollars", "3 dollars", "3500 dollars", "35000 dollars", "Nothing"],
        explanation: "Carolyn Davidson was later also thanked with company shares.",
      },
      lt: {
        question: "Nike brūkšnio logotipą sukūrė studentė, kuriai sumokėta maždaug kiek?",
        correct: "35 doleriai",
        distractors: ["350 dolerių", "3 doleriai", "3500 dolerių", "35000 dolerių", "Nieko"],
        explanation: "Vėliau Carolyn Davidson buvo padėkota ir bendrovės akcijomis.",
      },
    },
  },
  {
    id: "brn_fa_035",
    category: "brands",
    subTheme: "fashion",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Slinky — invented by naval engineer Richard James after a spring fell off a shelf",
    emoji: "🧸",
    translations: {
      en: {
        question: "The Slinky toy was invented after a tension spring fell off what?",
        correct: "A shelf",
        distractors: ["A roof", "A train", "A truck", "A plane", "A bridge"],
        explanation: "A naval engineer watched the spring 'walk' and saw a toy in it.",
      },
      lt: {
        question: "Žaislas Slinky atsirado, kai įtempta spyruoklė nukrito nuo ko?",
        correct: "Lentynos",
        distractors: ["Stogo", "Traukinio", "Sunkvežimio", "Lėktuvo", "Tilto"],
        explanation: "Jūrų laivyno inžinierius pamatė, kaip spyruoklė tarsi vaikšto, ir įžvelgė joje žaislą.",
      },
    },
  },
  {
    id: "brn_fa_036",
    category: "brands",
    subTheme: "fashion",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Louis Vuitton — started as a maker of flat-topped luggage trunks in Paris, 1854",
    emoji: "🧳",
    translations: {
      en: {
        question: "Which fashion house began as a maker of flat-topped luggage trunks?",
        correct: "Louis Vuitton",
        distractors: ["Chanel", "Yves Saint Laurent", "Versace", "Prada", "Armani"],
        explanation: "Its flat trunks could stack neatly on the new railway journeys.",
      },
      lt: {
        question: "Kuris mados namas pradėjo nuo plokščiaviršių kelioninių lagaminų gamybos?",
        correct: "Louis Vuitton",
        distractors: ["Chanel", "Yves Saint Laurent", "Versace", "Prada", "Armani"],
        explanation: "Plokšti lagaminai puikiai krovėsi vienas ant kito naujose traukinių kelionėse.",
      },
    },
  },
  {
    id: "brn_fa_037",
    category: "brands",
    subTheme: "fashion",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Gucci — founded by Guccio Gucci in Florence, Italy, 1921",
    emoji: "👜",
    translations: {
      en: {
        question: "The luxury brand Gucci was founded in which Italian city?",
        correct: "Florence",
        distractors: ["Milan", "Rome", "Naples", "Venice", "Turin"],
        explanation: "Guccio Gucci opened his leather goods shop there in 1921.",
      },
      lt: {
        question: "Prabangos ženklas Gucci buvo įkurtas kuriame Italijos mieste?",
        correct: "Florencijoje",
        distractors: ["Milane", "Romoje", "Neapolyje", "Venecijoje", "Turine"],
        explanation: "Guccio Gucci 1921 m. ten atidarė savo odos gaminių parduotuvę.",
      },
    },
  },
  {
    id: "brn_fa_038",
    category: "brands",
    subTheme: "fashion",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Stetson — 'cowboy hat' maker founded by John B. Stetson in the USA",
    emoji: "🎩",
    translations: {
      en: {
        question: "The classic Stetson cowboy hat brand comes from which country?",
        correct: "USA",
        distractors: ["Mexico", "Spain", "Argentina", "Australia", "Canada"],
        explanation: "John B. Stetson created the 'Boss of the Plains' hat in 1865.",
      },
      lt: {
        question: "Klasikinė Stetson kaubojiškų skrybėlių markė kilusi iš kurios šalies?",
        correct: "JAV",
        distractors: ["Meksikos", "Ispanijos", "Argentinos", "Australijos", "Kanados"],
        explanation: "Johnas B. Stetsonas 1865 m. sukūrė skrybėlę Lygumų valdovas.",
      },
    },
  },
  {
    id: "brn_fa_039",
    category: "brands",
    subTheme: "fashion",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Crocs — first shown at a 2002 boat show as a slip-resistant boating clog",
    emoji: "👟",
    translations: {
      en: {
        question: "Crocs clogs were first designed as shoes for which activity?",
        correct: "Boating",
        distractors: ["Gardening", "Hiking", "Running", "Nursing", "Cooking"],
        explanation: "The grippy foam clog was first sold as a slip-resistant boat shoe.",
      },
      lt: {
        question: "Crocs klumpės pirmiausia sukurtos kaip avalynė kokiai veiklai?",
        correct: "Plaukiojimui valtimi",
        distractors: ["Sodininkystei", "Žygiams", "Bėgimui", "Slaugai", "Maisto gaminimui"],
        explanation: "Neslidi putplasčio klumpė iš pradžių parduota kaip valties avalynė.",
      },
    },
  },
  {
    id: "brn_fa_040",
    category: "brands",
    subTheme: "fashion",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Birkenstock — contoured cork footbed developed in Germany in the 1890s",
    emoji: "👡",
    translations: {
      en: {
        question: "Birkenstock's famous contoured cork footbed was invented in which country?",
        correct: "Germany",
        distractors: ["Sweden", "Switzerland", "Austria", "USA", "Denmark"],
        explanation: "The Birkenstock family shaped supportive cork insoles long ago.",
      },
      lt: {
        question: "Garsusis Birkenstock kontūrinis kamštinis padas sukurtas kurioje šalyje?",
        correct: "Vokietijoje",
        distractors: ["Švedijoje", "Šveicarijoje", "Austrijoje", "JAV", "Danijoje"],
        explanation: "Birkenstock šeima seniai sukūrė pėdą palaikančius kamštinius padus.",
      },
    },
  },
];
