/**
 * brandsCars — 🚗 „Automobiliai ir technika" potemė (tema „Prekių ženklų istorijos").
 *
 * MAŽAS FAILAS pagal potemę. 40 klausimų (10/lygiui). Automobilių (ir motociklų,
 * padangų) prekių ženklų VARDŲ KILMĖS ir istorijos (Mercedes, Ferrari, Audi ...).
 * Tik istoriniai/įsitvirtinę faktai — JOKIOS reklamos. Jokios politikos.
 *
 * TAISYKLĖS: 1 teisingas + 5 distraktoriai; ≤46 simb.; teisingas NE ilgiausias >+5;
 * LT be vidinių kabučių; jokio atsakymo klausime; EMOJI NEUTRALUS (neišduoda atsakymo).
 */

import { TriviaQuestion } from "./triviaTypes";

export const BRANDS_CARS: TriviaQuestion[] = [
  // ===================== LENGVAS (9–12 m. vaikas) =====================
  {
    id: "brn_ca_001",
    category: "brands",
    subTheme: "cars",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Ferrari — prancing horse badge from WWI ace Francesco Baracca's plane",
    emoji: "🚗",
    translations: {
      en: {
        question: "Which sports car brand's badge is a black prancing horse on yellow?",
        correct: "Ferrari",
        distractors: ["Lamborghini", "Aston Martin", "Maserati", "Bugatti", "Alfa Romeo"],
        explanation: "The black horse came from the plane of a World War I flying ace.",
      },
      lt: {
        question: "Kurio sporto automobilių ženklas yra juodas stojantis žirgas geltoname fone?",
        correct: "Ferrari",
        distractors: ["Lamborghini", "Aston Martin", "Maserati", "Bugatti", "Alfa Romeo"],
        explanation: "Juodas žirgas paimtas nuo Pirmojo pasaulinio karo lakūno aso lėktuvo.",
      },
    },
  },
  {
    id: "brn_ca_002",
    category: "brands",
    subTheme: "cars",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Benz Patent-Motorwagen (1886) is widely called the first true automobile",
    emoji: "🚗",
    translations: {
      en: {
        question: "Which German brand built one of the first true automobiles in 1886?",
        correct: "Mercedes-Benz",
        distractors: ["BMW", "Audi", "Opel", "Porsche", "Volkswagen"],
        explanation: "Karl Benz's Patent-Motorwagen is often called the very first car.",
      },
      lt: {
        question: "Kuris vokiečių ženklas 1886 m. pastatė vieną pirmųjų tikrų automobilių?",
        correct: "Mercedes-Benz",
        distractors: ["BMW", "Audi", "Opel", "Porsche", "Volkswagen"],
        explanation: "Karlo Benzo Patent-Motorwagen dažnai vadinamas pirmuoju automobiliu.",
      },
    },
  },
  {
    id: "brn_ca_003",
    category: "brands",
    subTheme: "cars",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Volkswagen — makes the rounded 'Beetle'; name means 'people's car' in German",
    emoji: "🚗",
    translations: {
      en: {
        question: "Which brand makes the famous rounded car nicknamed the Beetle?",
        correct: "Volkswagen",
        distractors: ["Fiat", "Renault", "Citroën", "Opel", "Mini"],
        explanation: "Volkswagen means 'people's car' in German.",
      },
      lt: {
        question: "Kuris ženklas gamina garsų apvalų automobiliuką, pramintą Vabalu?",
        correct: "Volkswagen",
        distractors: ["Fiat", "Renault", "Citroën", "Opel", "Mini"],
        explanation: "Volkswagen vokiškai reiškia žmonių automobilį.",
      },
    },
  },
  {
    id: "brn_ca_004",
    category: "brands",
    subTheme: "cars",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Ford — Model T, early mass-produced car on Henry Ford's assembly line",
    emoji: "🚗",
    translations: {
      en: {
        question: "Which American brand built the Model T, an early mass-made car?",
        correct: "Ford",
        distractors: ["Chevrolet", "Cadillac", "Dodge", "Buick", "Chrysler"],
        explanation: "Henry Ford's moving assembly line made cars cheap enough for many.",
      },
      lt: {
        question: "Kuris amerikiečių ženklas pagamino Model T, vieną pirmų masinių automobilių?",
        correct: "Ford",
        distractors: ["Chevrolet", "Cadillac", "Dodge", "Buick", "Chrysler"],
        explanation: "Henrio Fordo judantis konvejeris padarė automobilius prieinamus daugeliui.",
      },
    },
  },
  {
    id: "brn_ca_005",
    category: "brands",
    subTheme: "cars",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Jeep — rugged off-roader 'Wrangler'; name may come from army 'GP' vehicles",
    emoji: "🚙",
    translations: {
      en: {
        question: "Which brand is famous for the rugged off-road Wrangler?",
        correct: "Jeep",
        distractors: ["Land Rover", "Toyota", "Subaru", "Hummer", "Suzuki"],
        explanation: "The name may come from army 'general purpose' vehicles.",
      },
      lt: {
        question: "Kuris ženklas garsus tvirtu visureigiu Wrangler?",
        correct: "Jeep",
        distractors: ["Land Rover", "Toyota", "Subaru", "Hummer", "Suzuki"],
        explanation: "Vardas galbūt kilo iš kariuomenės bendros paskirties mašinų.",
      },
    },
  },
  {
    id: "brn_ca_006",
    category: "brands",
    subTheme: "cars",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Tesla — named after Nikola Tesla, pioneer of alternating-current electricity",
    emoji: "🔌",
    translations: {
      en: {
        question: "Tesla cars are named after a famous pioneer of which technology?",
        correct: "Electricity",
        distractors: ["Steam", "Radio", "Flight", "Telephone", "Photography"],
        explanation: "Nikola Tesla helped develop alternating-current electric power.",
      },
      lt: {
        question: "Tesla automobiliai pavadinti garsaus kurios technologijos pradininko vardu?",
        correct: "Elektros",
        distractors: ["Garo", "Radijo", "Skrydžio", "Telefono", "Fotografijos"],
        explanation: "Nikola Tesla padėjo sukurti kintamosios srovės elektrą.",
      },
    },
  },
  {
    id: "brn_ca_007",
    category: "brands",
    subTheme: "cars",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Lamborghini — raging bull logo; founder was a Taurus and liked bullfighting",
    emoji: "🚗",
    translations: {
      en: {
        question: "Which Italian car brand uses a raging bull as its logo?",
        correct: "Lamborghini",
        distractors: ["Ferrari", "Maserati", "Fiat", "Alfa Romeo", "Pagani"],
        explanation: "Its founder loved bullfighting and was born under the Taurus sign.",
      },
      lt: {
        question: "Kuris italų automobilių ženklas naudoja įniršusį bulių logotipe?",
        correct: "Lamborghini",
        distractors: ["Ferrari", "Maserati", "Fiat", "Alfa Romeo", "Pagani"],
        explanation: "Įkūrėjas mėgo bulių kautynes ir gimė po Jaučio ženklu.",
      },
    },
  },
  {
    id: "brn_ca_008",
    category: "brands",
    subTheme: "cars",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "BMW — round blue-and-white badge; colours from the flag of Bavaria",
    emoji: "🚗",
    translations: {
      en: {
        question: "Which German brand has a round badge in blue and white?",
        correct: "BMW",
        distractors: ["Audi", "Volkswagen", "Opel", "Mercedes", "Porsche"],
        explanation: "The blue and white come from the flag of Bavaria, its home region.",
      },
      lt: {
        question: "Kuris vokiečių ženklas turi apvalų ženkliuką su mėlyna ir balta?",
        correct: "BMW",
        distractors: ["Audi", "Volkswagen", "Opel", "Mercedes", "Porsche"],
        explanation: "Mėlyna ir balta paimtos iš Bavarijos, jo gimtinės, vėliavos.",
      },
    },
  },
  {
    id: "brn_ca_009",
    category: "brands",
    subTheme: "cars",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Toyota — Japanese maker of the Corolla and Prius",
    emoji: "🚗",
    translations: {
      en: {
        question: "Which Japanese brand makes the best-selling Corolla and the Prius?",
        correct: "Toyota",
        distractors: ["Honda", "Nissan", "Mazda", "Suzuki", "Subaru"],
        explanation: "Toyota grew into one of the biggest carmakers in the world.",
      },
      lt: {
        question: "Kuris japonų ženklas gamina perkamiausią Corolla ir Prius?",
        correct: "Toyota",
        distractors: ["Honda", "Nissan", "Mazda", "Suzuki", "Subaru"],
        explanation: "Toyota išaugo į vieną didžiausių automobilių gamintojų pasaulyje.",
      },
    },
  },
  {
    id: "brn_ca_010",
    category: "brands",
    subTheme: "cars",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Michelin — its mascot 'Bibendum' is a man made of tyres",
    emoji: "🛞",
    translations: {
      en: {
        question: "Which tyre brand's mascot is a white puffy man made of tyres?",
        correct: "Michelin",
        distractors: ["Pirelli", "Goodyear", "Dunlop", "Bridgestone", "Continental"],
        explanation: "The Michelin Man is one of the world's oldest brand mascots.",
      },
      lt: {
        question: "Kurio padangų ženklo talismanas yra baltas puraus žmogeliukas iš padangų?",
        correct: "Michelin",
        distractors: ["Pirelli", "Goodyear", "Dunlop", "Bridgestone", "Continental"],
        explanation: "Michelin žmogeliukas yra vienas seniausių prekių ženklų talismanų pasaulyje.",
      },
    },
  },

  // ===================== VIDUTINIS (12–18 m. paauglys) =====================
  {
    id: "brn_ca_011",
    category: "brands",
    subTheme: "cars",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Mercedes — name from Mercédès Jellinek, daughter of businessman Emil Jellinek",
    emoji: "🚗",
    translations: {
      en: {
        question: "The name 'Mercedes' came from the first name of whose family member?",
        correct: "A businessman's daughter",
        distractors: ["A famous opera singer", "A racer's wife", "The founder", "A goddess", "A film star"],
        explanation: "Salesman Emil Jellinek named the cars after his daughter Mercédès.",
      },
      lt: {
        question: "Vardas Mercedes kilo iš kieno šeimos nario vardo?",
        correct: "Verslininko dukters",
        distractors: ["Garsios operos dainininkės", "Lenktynininko žmonos", "Įkūrėjo", "Deivės", "Kino žvaigždės"],
        explanation: "Pardavėjas Emilis Jellinekas pavadino mašinas dukters Mercédès vardu.",
      },
    },
  },
  {
    id: "brn_ca_012",
    category: "brands",
    subTheme: "cars",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Audi — Latin for founder August Horch's name; 'horch' = 'listen' in German",
    emoji: "🚗",
    translations: {
      en: {
        question: "Audi is the Latin form of founder Horch's name, which means what?",
        correct: "Listen",
        distractors: ["Drive", "Hurry", "Go fast", "Be first", "Look"],
        explanation: "'Horch' means 'listen!' in German; 'audi' is its Latin twin.",
      },
      lt: {
        question: "Audi yra lotyniška įkūrėjo Horcho pavardės forma; ką ji reiškia?",
        correct: "Klausyk",
        distractors: ["Važiuok", "Skubėk", "Greitai", "Būk pirmas", "Žiūrėk"],
        explanation: "Horch vokiškai reiškia klausyk; audi yra jo lotyniškas atitikmuo.",
      },
    },
  },
  {
    id: "brn_ca_013",
    category: "brands",
    subTheme: "cars",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Volvo — Latin for 'I roll'; company began making ball bearings",
    emoji: "🚗",
    translations: {
      en: {
        question: "The car brand Volvo is Latin for what?",
        correct: "I roll",
        distractors: ["I drive", "I go", "I move", "I run", "I lead"],
        explanation: "A fitting name for a firm that started out making ball bearings.",
      },
      lt: {
        question: "Automobilių ženklas Volvo lotyniškai reiškia ką?",
        correct: "Aš riedu",
        distractors: ["Aš vairuoju", "Aš einu", "Aš judu", "Aš bėgu", "Aš vedu"],
        explanation: "Tinkamas vardas firmai, pradėjusiai nuo rutulinių guolių gamybos.",
      },
    },
  },
  {
    id: "brn_ca_014",
    category: "brands",
    subTheme: "cars",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Subaru — Japanese for the Pleiades star cluster; logo shows its stars",
    emoji: "🚗",
    translations: {
      en: {
        question: "Subaru is the Japanese name of which star cluster shown in its logo?",
        correct: "The Pleiades",
        distractors: ["The Big Dipper", "Orion", "The North Star", "The Hyades", "Cassiopeia"],
        explanation: "'Subaru' means the Pleiades; the small stars sit in its badge.",
      },
      lt: {
        question: "Subaru japoniškai yra kurio žvaigždžių spiečiaus, rodomo logotipe, vardas?",
        correct: "Sietynas",
        distractors: ["Grįžulo Ratai", "Orionas", "Šiaurinė žvaigždė", "Hiados", "Kasiopėja"],
        explanation: "Subaru reiškia Sietyną; mažos žvaigždės sėdi jo ženkliuke.",
      },
    },
  },
  {
    id: "brn_ca_015",
    category: "brands",
    subTheme: "cars",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Volvo — invented the three-point seatbelt and shared the patent freely (1959)",
    emoji: "🚗",
    translations: {
      en: {
        question: "Volvo invented and gave away the patent for which safety item?",
        correct: "The three-point seatbelt",
        distractors: ["The crumple zone", "Anti-lock brakes", "The padded dashboard", "The headrest", "The child seat"],
        explanation: "Volvo shared the design free so it could save lives everywhere.",
      },
      lt: {
        question: "Volvo išrado ir nemokamai atidavė kurio saugos elemento patentą?",
        correct: "Trijų taškų saugos diržą",
        distractors: ["Deformacijos zoną", "Stabdžių ABS", "Minkštą prietaisų skydą", "Galvos atramą", "Vaiko kėdutę"],
        explanation: "Volvo dalijosi nemokamai, kad diržas gelbėtų gyvybes visur.",
      },
    },
  },
  {
    id: "brn_ca_016",
    category: "brands",
    subTheme: "cars",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "BMW — began as an aircraft engine maker before building cars",
    emoji: "🚗",
    translations: {
      en: {
        question: "Before cars, BMW mainly built engines for what?",
        correct: "Aircraft",
        distractors: ["Ships", "Trains", "Tractors", "Boats", "Bicycles"],
        explanation: "BMW started life as a maker of aircraft engines in Bavaria.",
      },
      lt: {
        question: "Prieš automobilius BMW daugiausia gamino variklius kam?",
        correct: "Lėktuvams",
        distractors: ["Laivams", "Traukiniams", "Traktoriams", "Valtims", "Dviračiams"],
        explanation: "BMW pradėjo kaip lėktuvų variklių gamintoja Bavarijoje.",
      },
    },
  },
  {
    id: "brn_ca_017",
    category: "brands",
    subTheme: "cars",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Ferdinand Porsche designed the original Volkswagen Beetle",
    emoji: "🚗",
    translations: {
      en: {
        question: "Porsche's founder also designed which famous small 'people's car'?",
        correct: "The Beetle",
        distractors: ["The Mini", "The Fiat 500", "The 2CV", "The Trabant", "The Lada"],
        explanation: "Ferdinand Porsche designed the original Volkswagen Beetle.",
      },
      lt: {
        question: "Porsche įkūrėjas taip pat sukūrė kurį garsų mažą žmonių automobiliuką?",
        correct: "Vabalą",
        distractors: ["Mini", "Fiat 500", "2CV", "Trabant", "Lada"],
        explanation: "Ferdinandas Porsche sukūrė pirmąjį Volkswagen Vabalą.",
      },
    },
  },
  {
    id: "brn_ca_018",
    category: "brands",
    subTheme: "cars",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Lamborghini — Ferruccio Lamborghini was a wealthy tractor manufacturer first",
    emoji: "🚗",
    translations: {
      en: {
        question: "Lamborghini built which kind of machine before making sports cars?",
        correct: "Tractors",
        distractors: ["Combines", "Boats", "Trucks", "Pumps", "Cranes"],
        explanation: "Ferruccio Lamborghini grew rich making farm tractors.",
      },
      lt: {
        question: "Lamborghini gamino kokias mašinas prieš pradėdamas leisti sportinius automobilius?",
        correct: "Traktorius",
        distractors: ["Kombainus", "Valtis", "Sunkvežimius", "Siurblius", "Kranus"],
        explanation: "Feručas Lamborginis praturtėjo gamindamas žemės ūkio traktorius.",
      },
    },
  },
  {
    id: "brn_ca_019",
    category: "brands",
    subTheme: "cars",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Honda — first became famous for motorcycles before cars",
    emoji: "🏍️",
    translations: {
      en: {
        question: "Honda first became world-famous for making what, before cars?",
        correct: "Motorcycles",
        distractors: ["Bicycles", "Boats", "Planes", "Tractors", "Scooters"],
        explanation: "Soichiro Honda's motorbikes conquered the globe first.",
      },
      lt: {
        question: "Honda pirmiausia išgarsėjo gamindama ką, dar prieš automobilius?",
        correct: "Motociklus",
        distractors: ["Dviračius", "Valtis", "Lėktuvus", "Traktorius", "Motorolerius"],
        explanation: "Soičiro Hondos motociklai pirmiausia užkariavo pasaulį.",
      },
    },
  },
  {
    id: "brn_ca_020",
    category: "brands",
    subTheme: "cars",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Toyota — changed name from 'Toyoda' to 'Toyota' (eight strokes, seen as lucky)",
    emoji: "🚗",
    translations: {
      en: {
        question: "Toyota changed its name from 'Toyoda' partly for which reason?",
        correct: "Luck and style",
        distractors: ["A legal fight", "A new owner", "A spelling error", "A merger", "A king's wish"],
        explanation: "The new spelling took eight brush strokes, a number seen as lucky.",
      },
      lt: {
        question: "Toyota pakeitė vardą iš Toyoda į Toyota iš dalies dėl kokios priežasties?",
        correct: "Sėkmės ir stiliaus",
        distractors: ["Teisinio ginčo", "Naujo savininko", "Rašybos klaidos", "Susijungimo", "Karaliaus valios"],
        explanation: "Naujas rašmuo užėmė aštuonis brūkšnius — laimingu laikomą skaičių.",
      },
    },
  },

  // ===================== SUNKUS (suaugęs, kuris domisi) =====================
  {
    id: "brn_ca_021",
    category: "brands",
    subTheme: "cars",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Ferrari horse — emblem of WWI fighter ace Francesco Baracca, given to Enzo Ferrari",
    emoji: "🚗",
    translations: {
      en: {
        question: "Ferrari's prancing horse came from the plane of which kind of person?",
        correct: "A flying ace",
        distractors: ["A general", "A king", "A spy", "A pilot's son", "A racer"],
        explanation: "Fighter ace Francesco Baracca's emblem was gifted to Enzo Ferrari.",
      },
      lt: {
        question: "Ferrari žirgas paimtas nuo kokio žmogaus lėktuvo?",
        correct: "Lakūno aso",
        distractors: ["Generolo", "Karaliaus", "Šnipo", "Lakūno sūnaus", "Lenktynininko"],
        explanation: "Naikintuvo aso Frančesko Barakos emblema buvo padovanota Encui Ferariui.",
      },
    },
  },
  {
    id: "brn_ca_022",
    category: "brands",
    subTheme: "cars",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Audi — four rings represent the four firms of Auto Union (Audi, DKW, Horch, Wanderer)",
    emoji: "🚗",
    translations: {
      en: {
        question: "Audi's four rings stand for four firms merged under which name?",
        correct: "Auto Union",
        distractors: ["Auto Group", "Auto Allianz", "Quattro", "Volkswagen", "Daimler"],
        explanation: "Audi, DKW, Horch and Wanderer joined together as Auto Union.",
      },
      lt: {
        question: "Audi keturi žiedai reiškia keturias firmas, susijungusias po kokiu vardu?",
        correct: "Auto Union",
        distractors: ["Auto Group", "Auto Allianz", "Quattro", "Volkswagen", "Daimler"],
        explanation: "Audi, DKW, Horch ir Wanderer susijungė į Auto Union.",
      },
    },
  },
  {
    id: "brn_ca_023",
    category: "brands",
    subTheme: "cars",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Mazda — name linked to Ahura Mazda (Zoroastrian god) and founder Jujiro Matsuda",
    emoji: "🚗",
    translations: {
      en: {
        question: "Mazda's name is linked to which ancient god of wisdom and light?",
        correct: "Ahura Mazda",
        distractors: ["Ra", "Apollo", "Mithra", "Marduk", "Helios"],
        explanation: "It echoes the Zoroastrian god and founder Jujiro Matsuda's name.",
      },
      lt: {
        question: "Mazda vardas siejamas su kuriuo senovės išminties ir šviesos dievu?",
        correct: "Ahura Mazda",
        distractors: ["Ra", "Apolonu", "Mitra", "Marduku", "Heliju"],
        explanation: "Jis primena zoroastrų dievo ir įkūrėjo Džudžiro Macudos vardą.",
      },
    },
  },
  {
    id: "brn_ca_024",
    category: "brands",
    subTheme: "cars",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Rolls-Royce — bonnet ornament called the 'Spirit of Ecstasy' since 1911",
    emoji: "🚗",
    translations: {
      en: {
        question: "What is the name of the flying-lady ornament on a Rolls-Royce?",
        correct: "Spirit of Ecstasy",
        distractors: ["Flying Goddess", "Silver Angel", "Winged Victory", "Lady Fortune", "Grace"],
        explanation: "The little silver figure has topped the cars since 1911.",
      },
      lt: {
        question: "Koks yra skraidančios moters statulėlės ant Rolls-Royce pavadinimas?",
        correct: "Spirit of Ecstasy",
        distractors: ["Flying Goddess", "Silver Angel", "Winged Victory", "Lady Fortune", "Grace"],
        explanation: "Maža sidabrinė figūrėlė puošia mašinas nuo 1911 m.",
      },
    },
  },
  {
    id: "brn_ca_025",
    category: "brands",
    subTheme: "cars",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Maserati — trident logo inspired by Neptune's statue in Bologna",
    emoji: "🚗",
    translations: {
      en: {
        question: "Maserati's trident logo was inspired by a statue in which Italian city?",
        correct: "Bologna",
        distractors: ["Rome", "Venice", "Milan", "Florence", "Naples"],
        explanation: "It copies the trident of the Neptune fountain in Bologna.",
      },
      lt: {
        question: "Maserati trišakio logotipas įkvėptas statulos kuriame Italijos mieste?",
        correct: "Bolonijoje",
        distractors: ["Romoje", "Venecijoje", "Milane", "Florencijoje", "Neapolyje"],
        explanation: "Jis nukopijuotas nuo Neptūno fontano trišakio Bolonijoje.",
      },
    },
  },
  {
    id: "brn_ca_026",
    category: "brands",
    subTheme: "cars",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Citroën — double-chevron logo shaped like the teeth of a (helical) gear",
    emoji: "🚗",
    translations: {
      en: {
        question: "Citroën's double-chevron logo is shaped like the teeth of what?",
        correct: "A gear",
        distractors: ["A comb", "A saw", "A zip", "A crown", "A fence"],
        explanation: "André Citroën first made money producing special gear wheels.",
      },
      lt: {
        question: "Citroën dvigubo paukštuko logotipas primena ko dantis?",
        correct: "Krumpliaračio",
        distractors: ["Šukų", "Pjūklo", "Užtrauktuko", "Karūnos", "Tvoros"],
        explanation: "André Citroënas pirmuosius pinigus uždirbo gamindamas krumpliaračius.",
      },
    },
  },
  {
    id: "brn_ca_027",
    category: "brands",
    subTheme: "cars",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Peugeot — lion logo first marked the quality of its steel saw blades (1858)",
    emoji: "🚗",
    translations: {
      en: {
        question: "Peugeot's lion logo was first used to mark the quality of its what?",
        correct: "Saw blades",
        distractors: ["Coffee mills", "Bicycles", "Cars", "Clocks", "Umbrellas"],
        explanation: "Long before cars, Peugeot made tools, and the lion meant strong steel.",
      },
      lt: {
        question: "Peugeot liūto logotipas pirmiausia žymėjo kurio gaminio kokybę?",
        correct: "Pjūklų geležčių",
        distractors: ["Kavamalių", "Dviračių", "Automobilių", "Laikrodžių", "Skėčių"],
        explanation: "Gerokai prieš automobilius Peugeot gamino įrankius, o liūtas reiškė tvirtą plieną.",
      },
    },
  },
  {
    id: "brn_ca_028",
    category: "brands",
    subTheme: "cars",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Cadillac — named after Antoine de la Mothe Cadillac, founder of Detroit",
    emoji: "🚗",
    translations: {
      en: {
        question: "Cadillac is named after the founder of which US city?",
        correct: "Detroit",
        distractors: ["Chicago", "Boston", "New York", "Dallas", "Miami"],
        explanation: "Antoine de la Mothe Cadillac founded Detroit back in 1701.",
      },
      lt: {
        question: "Cadillac pavadintas kurio JAV miesto įkūrėjo vardu?",
        correct: "Detroito",
        distractors: ["Čikagos", "Bostono", "Niujorko", "Dalaso", "Majamio"],
        explanation: "Antuanas de la Mot Kadijakas įkūrė Detroitą dar 1701 m.",
      },
    },
  },
  {
    id: "brn_ca_029",
    category: "brands",
    subTheme: "cars",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Bugatti — founded by Ettore Bugatti, from a family of artists and designers",
    emoji: "🚗",
    translations: {
      en: {
        question: "The hyper-fast Bugatti cars were founded by a family of what?",
        correct: "Artists",
        distractors: ["Doctors", "Sailors", "Bankers", "Farmers", "Soldiers"],
        explanation: "Ettore Bugatti came from a noted line of artists and designers.",
      },
      lt: {
        question: "Itin greitus Bugatti automobilius įkūrė kokios profesijos šeima?",
        correct: "Menininkų",
        distractors: ["Gydytojų", "Jūreivių", "Bankininkų", "Ūkininkų", "Karių"],
        explanation: "Etorė Bugatis kilo iš žinomos menininkų ir dizainerių giminės.",
      },
    },
  },
  {
    id: "brn_ca_030",
    category: "brands",
    subTheme: "cars",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Hyundai — Korean word meaning 'modernity'",
    emoji: "🚗",
    translations: {
      en: {
        question: "The carmaker Hyundai's name means what in Korean?",
        correct: "Modernity",
        distractors: ["Big star", "Three rivers", "Gold mountain", "New road", "Rising sun"],
        explanation: "A fitting name for a firm built during Korea's fast modern growth.",
      },
      lt: {
        question: "Automobilių gamintojos Hyundai vardas korėjietiškai reiškia ką?",
        correct: "Modernumą",
        distractors: ["Didelę žvaigždę", "Tris upes", "Aukso kalną", "Naują kelią", "Tekančią saulę"],
        explanation: "Tinkamas vardas firmai, gimusiai per spartų Korėjos modernėjimą.",
      },
    },
  },

  // ===================== EKSTREMALUS (srities žinovas) =====================
  {
    id: "brn_ca_031",
    category: "brands",
    subTheme: "cars",
    level: "ekstremalus",
    isTrap: true,
    sourceVerified: "BMW roundel myth — often wrongly said to show a propeller; colours are Bavaria's flag",
    emoji: "🚗",
    translations: {
      en: {
        question: "The BMW badge is wrongly said to show a spinning what?",
        correct: "Propeller",
        distractors: ["Wheel", "Compass", "Turbine", "Fan", "Gear"],
        explanation: "In truth the blue and white simply come from the Bavarian flag.",
      },
      lt: {
        question: "Apie BMW ženkliuką klaidingai sakoma, kad jis vaizduoja besisukantį ką?",
        correct: "Propelerį",
        distractors: ["Ratą", "Kompasą", "Turbiną", "Ventiliatorių", "Krumpliaratį"],
        explanation: "Iš tikrųjų mėlyna ir balta tiesiog paimtos iš Bavarijos vėliavos.",
      },
    },
  },
  {
    id: "brn_ca_032",
    category: "brands",
    subTheme: "cars",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Kia — name roughly means 'to arise or rise out of Asia' in Korean characters",
    emoji: "🚗",
    translations: {
      en: {
        question: "The Korean brand Kia's name roughly means 'to rise out of' where?",
        correct: "Asia",
        distractors: ["Europe", "Africa", "America", "Oceania", "the North"],
        explanation: "The characters suggest rising up and out of Asia onto the world.",
      },
      lt: {
        question: "Korėjiečių ženklo Kia vardas maždaug reiškia iškilimą iš kur?",
        correct: "Azijos",
        distractors: ["Europos", "Afrikos", "Amerikos", "Okeanijos", "Šiaurės"],
        explanation: "Rašmenys reiškia iškilimą iš Azijos į pasaulį.",
      },
    },
  },
  {
    id: "brn_ca_033",
    category: "brands",
    subTheme: "cars",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Subaru — its six stars represent firms merged into Fuji Heavy Industries",
    emoji: "🚗",
    translations: {
      en: {
        question: "Subaru's five small logo stars mark the firms merged to create which company?",
        correct: "Fuji Heavy Industries",
        distractors: ["Nissan Industries", "Honda Heavy Group", "Toyota Holdings", "Mitsubishi Motors", "Datsun Works"],
        explanation: "Five firms merged in 1953; the big sixth star stands for the group itself.",
      },
      lt: {
        question: "Penkios mažos Subaru žvaigždės žymi firmas, susijungusias į kurią bendrovę?",
        correct: "Fuji Heavy Industries",
        distractors: ["Nissan Industries", "Honda Heavy Group", "Toyota Holdings", "Mitsubishi Motors", "Datsun Works"],
        explanation: "Penkios firmos susijungė 1953 m.; didelė šešta žvaigždė žymi pačią grupę.",
      },
    },
  },
  {
    id: "brn_ca_034",
    category: "brands",
    subTheme: "cars",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Datsun — early brand name later replaced worldwide by Nissan",
    emoji: "🚗",
    translations: {
      en: {
        question: "The old Datsun badge was later replaced worldwide by which brand?",
        correct: "Nissan",
        distractors: ["Toyota", "Honda", "Mazda", "Subaru", "Isuzu"],
        explanation: "Datsun cars were gradually rebadged as Nissan across the globe.",
      },
      lt: {
        question: "Senas Datsun ženkliukas vėliau visame pasaulyje pakeistas kuriuo ženklu?",
        correct: "Nissan",
        distractors: ["Toyota", "Honda", "Mazda", "Subaru", "Isuzu"],
        explanation: "Datsun automobiliai pamažu visur pervadinti į Nissan.",
      },
    },
  },
  {
    id: "brn_ca_035",
    category: "brands",
    subTheme: "cars",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Aston Martin — co-founder Lionel Martin + Aston Hill (a hill-climb course)",
    emoji: "🚗",
    translations: {
      en: {
        question: "Aston Martin joins a founder's name with the name of a what?",
        correct: "A hill-climb",
        distractors: ["A racetrack", "A village", "A river", "A castle", "A bridge"],
        explanation: "Lionel Martin raced at Aston Hill, so the cars became Aston Martin.",
      },
      lt: {
        question: "Pavadinimas Aston Martin sujungia įkūrėjo vardą su kokio renginio pavadinimu?",
        correct: "Įkalnės lenktynių",
        distractors: ["Lenktynių trasos", "Kaimo", "Upės", "Pilies", "Tilto"],
        explanation: "Lionelis Martinas lenktyniavo Astono kalvoje, todėl atsirado Aston Martin.",
      },
    },
  },
  {
    id: "brn_ca_036",
    category: "brands",
    subTheme: "cars",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Rolls-Royce — co-founder Charles Rolls was a pioneer aviator, died in a 1910 air crash",
    emoji: "🚗",
    translations: {
      en: {
        question: "Rolls-Royce's co-founder Charles Rolls was also an early what?",
        correct: "Aviator",
        distractors: ["Sailor", "Banker", "Painter", "Diplomat", "Surgeon"],
        explanation: "The pioneer pilot died young in one of the first plane crashes.",
      },
      lt: {
        question: "Kuo dar garsėjo Rolls-Royce bendraįkūrėjas Charlesas Rollsas?",
        correct: "Lakūnu",
        distractors: ["Jūreiviu", "Bankininku", "Dailininku", "Diplomatu", "Chirurgu"],
        explanation: "Aviacijos pradininkas jaunas žuvo per vieną pirmųjų lėktuvo katastrofų.",
      },
    },
  },
  {
    id: "brn_ca_037",
    category: "brands",
    subTheme: "cars",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Škoda — the Czech maker first produced bicycles (Laurin & Klement), then motorbikes, cars",
    emoji: "🚗",
    translations: {
      en: {
        question: "The Czech carmaker Škoda first produced which product in the 1890s?",
        correct: "Bicycles",
        distractors: ["Pianos", "Watches", "Shoes", "Boats", "Cameras"],
        explanation: "It began with bicycles, then motorbikes, before building cars.",
      },
      lt: {
        question: "Čekų automobilių gamintoja Škoda 10-ajame dešimtmetyje pirmiausia gamino ką?",
        correct: "Dviračius",
        distractors: ["Pianinus", "Laikrodžius", "Batus", "Valtis", "Fotoaparatus"],
        explanation: "Ji pradėjo nuo dviračių, vėliau motociklų, o tada automobilių.",
      },
    },
  },
  {
    id: "brn_ca_038",
    category: "brands",
    subTheme: "cars",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Jeep — name widely thought to come from the army term 'GP' (general purpose)",
    emoji: "🚙",
    translations: {
      en: {
        question: "The Jeep name is widely thought to come from which two-word term?",
        correct: "General purpose",
        distractors: ["Ground patrol", "Great power", "Giant pickup", "Jump platform", "Just powerful"],
        explanation: "Soldiers may have slurred the letters 'GP' into the word 'Jeep'.",
      },
      lt: {
        question: "Manoma, kad pavadinimas Jeep kilo iš kurio dviejų žodžių termino?",
        correct: "Bendra paskirtis",
        distractors: ["Žemės patrulis", "Didelė galia", "Milžiniškas pikapas", "Šuolio platforma", "Tiesiog galingas"],
        explanation: "Kariai galbūt suliejo raides GP į žodį Jeep.",
      },
    },
  },
  {
    id: "brn_ca_039",
    category: "brands",
    subTheme: "cars",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Bentley — luxury brand owned by the Volkswagen Group since 1998",
    emoji: "🚗",
    translations: {
      en: {
        question: "Today the British luxury brand Bentley is owned by which group?",
        correct: "Volkswagen",
        distractors: ["BMW", "Daimler", "Toyota", "Ford", "Fiat"],
        explanation: "The Volkswagen Group bought Bentley back in 1998.",
      },
      lt: {
        question: "Šiandien britų prabangos ženklas Bentley priklauso kuriai grupei?",
        correct: "Volkswagen",
        distractors: ["BMW", "Daimler", "Toyota", "Ford", "Fiat"],
        explanation: "Volkswagen grupė nupirko Bentley dar 1998 m.",
      },
    },
  },
  {
    id: "brn_ca_040",
    category: "brands",
    subTheme: "cars",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Mini — designed by Alec Issigonis after the 1956 Suez fuel crisis",
    emoji: "🚗",
    translations: {
      en: {
        question: "The classic Mini was designed in answer to which 1950s crisis?",
        correct: "A fuel crisis",
        distractors: ["A car ban", "A steel shortage", "A road tax", "A factory strike", "A flood"],
        explanation: "A fuel shortage pushed designers to make a tiny, thrifty car.",
      },
      lt: {
        question: "Klasikinis Mini sukurtas atsakant į kurią 6-ojo dešimtmečio krizę?",
        correct: "Kuro krizę",
        distractors: ["Automobilių draudimą", "Plieno trūkumą", "Kelių mokestį", "Gamyklos streiką", "Potvynį"],
        explanation: "Kuro trūkumas paskatino sukurti mažytį, taupų automobilį.",
      },
    },
  },
];
