/**
 * brandsFood — 🍟 „Maistas ir gėrimai" potemė (tema „Prekių ženklų istorijos").
 *
 * MAŽAS FAILAS pagal potemę. 40 klausimų (10/lygiui). Garsių maisto/gėrimų prekių
 * ženklų ISTORIJOS ir KILMĖS faktai (Coca-Cola, McDonald's, Toblerone ...).
 * Tik istoriniai/įsitvirtinę faktai — JOKIOS reklamos ar vertinimų.
 *
 * TAISYKLĖS: 1 teisingas + 5 distraktoriai; ≤46 simb.; teisingas NE ilgiausias >+5;
 * LT be vidinių kabučių; jokio atsakymo klausime; EMOJI NEUTRALUS (neišduoda atsakymo).
 */

import { TriviaQuestion } from "./triviaTypes";

export const BRANDS_FOOD: TriviaQuestion[] = [
  // ===================== LENGVAS (9–12 m. vaikas) =====================
  {
    id: "brn_fd_001",
    category: "brands",
    subTheme: "food",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Coca-Cola Co. history — invented by pharmacist John Pemberton, Atlanta 1886",
    emoji: "🥤",
    translations: {
      en: {
        question: "A pharmacist first mixed which fizzy drink back in 1886?",
        correct: "Coca-Cola",
        distractors: ["Pepsi", "Fanta", "Sprite", "7 Up", "Dr Pepper"],
        explanation: "Atlanta pharmacist John Pemberton sold it first as a medicinal tonic.",
      },
      lt: {
        question: "Kurį gazuotą gėrimą vaistininkas pirmą kartą sumaišė 1886 m.?",
        correct: "Coca-Cola",
        distractors: ["Pepsi", "Fanta", "Sprite", "7 Up", "Dr Pepper"],
        explanation: "Atlantos vaistininkas Johnas Pembertonas iš pradžių pardavinėjo jį kaip vaistą.",
      },
    },
  },
  {
    id: "brn_fd_002",
    category: "brands",
    subTheme: "food",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "McDonald's — Big Mac created by franchisee Jim Delligatti, 1967",
    emoji: "🍔",
    translations: {
      en: {
        question: "The Big Mac burger comes from which fast-food chain?",
        correct: "McDonald's",
        distractors: ["Burger King", "KFC", "Wendy's", "Subway", "Five Guys"],
        explanation: "A franchisee invented the Big Mac in 1967; it became the menu star.",
      },
      lt: {
        question: "Iš kurio greito maisto tinklo kilo Big Mac mėsainis?",
        correct: "McDonald's",
        distractors: ["Burger King", "KFC", "Wendy's", "Subway", "Five Guys"],
        explanation: "Frančizės savininkas sukūrė Big Mac 1967 m.; jis tapo meniu žvaigžde.",
      },
    },
  },
  {
    id: "brn_fd_003",
    category: "brands",
    subTheme: "food",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Oreo (Mondelez) — best-selling cookie, launched 1912",
    emoji: "🍪",
    translations: {
      en: {
        question: "Which cookie is famous for the trick twist, lick and dunk?",
        correct: "Oreo",
        distractors: ["Chips Ahoy", "KitKat", "TUC", "Digestive", "Pringles"],
        explanation: "Two chocolate discs with cream, sold since 1912 and loved worldwide.",
      },
      lt: {
        question: "Kuris sausainis garsus žaidimu pasukti, palaižyti, pamirkyti?",
        correct: "Oreo",
        distractors: ["Chips Ahoy", "KitKat", "TUC", "Digestive", "Pringles"],
        explanation: "Du šokoladiniai diskeliai su kremu pardavinėjami nuo 1912 m.",
      },
    },
  },
  {
    id: "brn_fd_004",
    category: "brands",
    subTheme: "food",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Toblerone — triangular bar shaped after the Matterhorn",
    emoji: "🍫",
    translations: {
      en: {
        question: "Which chocolate bar has a famous triangular shape?",
        correct: "Toblerone",
        distractors: ["KitKat", "Twix", "Mars", "Snickers", "Bounty"],
        explanation: "Its row of peaks makes the Swiss chocolate instantly recognisable.",
      },
      lt: {
        question: "Kuris šokoladas garsus trikampe forma?",
        correct: "Toblerone",
        distractors: ["KitKat", "Twix", "Mars", "Snickers", "Bounty"],
        explanation: "Eilė smailių daro šveicarišką šokoladą iškart atpažįstamą.",
      },
    },
  },
  {
    id: "brn_fd_005",
    category: "brands",
    subTheme: "food",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Starbucks — logo is a twin-tailed siren, founded Seattle 1971",
    emoji: "☕",
    translations: {
      en: {
        question: "The twin-tailed mermaid logo belongs to which coffee chain?",
        correct: "Starbucks",
        distractors: ["Costa", "Lavazza", "Dunkin'", "Nescafé", "Tchibo"],
        explanation: "The sea siren suits the brand's start in the seaport of Seattle.",
      },
      lt: {
        question: "Kuriam kavos tinklui priklauso dvyuodegės undinės logotipas?",
        correct: "Starbucks",
        distractors: ["Costa", "Lavazza", "Dunkin'", "Nescafé", "Tchibo"],
        explanation: "Jūrų undinė tinka prekės ženklui, gimusiam Sietlo uostamiestyje.",
      },
    },
  },
  {
    id: "brn_fd_006",
    category: "brands",
    subTheme: "food",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "KFC — Colonel Harland Sanders; Kentucky Colonel is an honorary title",
    emoji: "🍗",
    translations: {
      en: {
        question: "Which chicken chain shows a smiling Colonel on its bucket?",
        correct: "KFC",
        distractors: ["Popeyes", "McDonald's", "Burger King", "Nando's", "Subway"],
        explanation: "Harland Sanders held an honorary Kentucky Colonel title, not a military one.",
      },
      lt: {
        question: "Kuris vištienos tinklas ant kibirėlio rodo besišypsantį pulkininką?",
        correct: "KFC",
        distractors: ["Popeyes", "McDonald's", "Burger King", "Nando's", "Subway"],
        explanation: "Harlandas Sandersas turėjo garbės Kentukio pulkininko vardą, ne karinį.",
      },
    },
  },
  {
    id: "brn_fd_007",
    category: "brands",
    subTheme: "food",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Nutella — chocolate-hazelnut spread by Ferrero, Italy 1960s",
    emoji: "🍫",
    translations: {
      en: {
        question: "Which sweet spread mixes chocolate with hazelnut, made by Ferrero?",
        correct: "Nutella",
        distractors: ["Kinder", "Milka", "Cadbury", "Lindt", "Daim"],
        explanation: "Born in Italy when cocoa was scarce, so cheaper hazelnuts were added.",
      },
      lt: {
        question: "Kuris saldus užtepas jungia šokoladą su lazdyno riešutu (Ferrero)?",
        correct: "Nutella",
        distractors: ["Kinder", "Milka", "Cadbury", "Lindt", "Daim"],
        explanation: "Gimė Italijoje, kai trūko kakavos, todėl pridėta pigesnių riešutų.",
      },
    },
  },
  {
    id: "brn_fd_008",
    category: "brands",
    subTheme: "food",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Haribo — Hans Riegel made first gummy bear (Tanzbär), Bonn 1922",
    emoji: "🍬",
    translations: {
      en: {
        question: "Which German brand created the very first gummy bears?",
        correct: "Haribo",
        distractors: ["Trolli", "Katjes", "Maoam", "Mentos", "Skittles"],
        explanation: "In 1922 its founder shaped a little dancing bear from fruit gum.",
      },
      lt: {
        question: "Kuris vokiečių prekės ženklas sukūrė pačius pirmuosius guminukus meškiukus?",
        correct: "Haribo",
        distractors: ["Trolli", "Katjes", "Maoam", "Mentos", "Skittles"],
        explanation: "1922 m. įkūrėjas iš vaisinės gumos nulipdė mažą šokantį meškiuką.",
      },
    },
  },
  {
    id: "brn_fd_009",
    category: "brands",
    subTheme: "food",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Pringles — saddle-shaped crisps stacked in a tubular can",
    emoji: "🥫",
    translations: {
      en: {
        question: "Which crisps come neatly stacked inside a tall tube can?",
        correct: "Pringles",
        distractors: ["Lay's", "Doritos", "Cheetos", "Ruffles", "TUC"],
        explanation: "The clever can was so loved its designer's ashes were buried in one.",
      },
      lt: {
        question: "Kurie traškučiai sudėti tvarkingais stulpeliais aukštoje tūbelėje?",
        correct: "Pringles",
        distractors: ["Lay's", "Doritos", "Cheetos", "Ruffles", "TUC"],
        explanation: "Talpykla taip patiko, kad jos kūrėjo pelenai palaidoti tokioje tūbelėje.",
      },
    },
  },
  {
    id: "brn_fd_010",
    category: "brands",
    subTheme: "food",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Kellogg's — Corn Flakes from the Kellogg brothers' sanitarium, 1890s",
    emoji: "🥣",
    translations: {
      en: {
        question: "Which brand first put Corn Flakes on the breakfast table?",
        correct: "Kellogg's",
        distractors: ["Nestlé", "Quaker", "Weetabix", "Nesquik", "Post"],
        explanation: "The flakes were a happy accident at the Kellogg brothers' health clinic.",
      },
      lt: {
        question: "Kuris prekės ženklas pirmas atnešė Corn Flakes dribsnius ant pusryčių stalo?",
        correct: "Kellogg's",
        distractors: ["Nestlé", "Quaker", "Weetabix", "Nesquik", "Post"],
        explanation: "Dribsniai gimė atsitiktinai brolių Keloggų sveikatos klinikoje.",
      },
    },
  },

  // ===================== VIDUTINIS (12–18 m. paauglys) =====================
  {
    id: "brn_fd_011",
    category: "brands",
    subTheme: "food",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Pepsi — originally sold as 'Brad's Drink' by Caleb Bradham, 1893",
    emoji: "🥤",
    translations: {
      en: {
        question: "Which cola was first sold under the name Brad's Drink?",
        correct: "Pepsi",
        distractors: ["Coca-Cola", "Fanta", "Sprite", "7 Up", "Tango"],
        explanation: "Pharmacist Caleb Bradham renamed his drink Pepsi in 1898.",
      },
      lt: {
        question: "Kuri kola iš pradžių buvo parduodama pavadinimu Brad's Drink?",
        correct: "Pepsi",
        distractors: ["Coca-Cola", "Fanta", "Sprite", "7 Up", "Tango"],
        explanation: "Vaistininkas Calebas Bradhamas savo gėrimą Pepsi pervadino 1898 m.",
      },
    },
  },
  {
    id: "brn_fd_012",
    category: "brands",
    subTheme: "food",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Fanta — created at Coca-Cola Germany during WWII trade embargo, 1940",
    emoji: "🍊",
    translations: {
      en: {
        question: "In which country was Fanta first invented during World War II?",
        correct: "Germany",
        distractors: ["USA", "Italy", "Austria", "Brazil", "Spain"],
        explanation: "Coca-Cola's German branch lost its syrup supply and improvised Fanta.",
      },
      lt: {
        question: "Kurioje šalyje per Antrąjį pasaulinį karą buvo sukurta Fanta?",
        correct: "Vokietija",
        distractors: ["JAV", "Italija", "Austrija", "Brazilija", "Ispanija"],
        explanation: "Coca-Cola vokiečių skyrius neteko sirupo ir improvizuodamas sukūrė Fantą.",
      },
    },
  },
  {
    id: "brn_fd_013",
    category: "brands",
    subTheme: "food",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "M&M's — named for Forrest Mars and Bruce Murrie",
    emoji: "🍫",
    translations: {
      en: {
        question: "The two M's in M&M's stand for the surnames of which pair?",
        correct: "Mars and Murrie",
        distractors: ["Miller and Moore", "Mason and Mills", "Meyer and Munro", "Morris and Mack", "Mann and Meade"],
        explanation: "Forrest Mars teamed up with Bruce Murrie, son of a Hershey boss.",
      },
      lt: {
        question: "Dvi raidės M pavadinime M&M's reiškia kurios poros pavardes?",
        correct: "Mars ir Murrie",
        distractors: ["Miller ir Moore", "Mason ir Mills", "Meyer ir Munro", "Morris ir Mack", "Mann ir Meade"],
        explanation: "Forestas Marsas susidėjo su Brusu Muriu, Hershey vadovo sūnumi.",
      },
    },
  },
  {
    id: "brn_fd_014",
    category: "brands",
    subTheme: "food",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Snickers — named after a favorite horse of the Mars family, 1930",
    emoji: "🐎",
    translations: {
      en: {
        question: "Which chocolate bar was named after the Mars family's horse?",
        correct: "Snickers",
        distractors: ["Twix", "Bounty", "Mars", "Milky Way", "Galaxy"],
        explanation: "The 1930 bar took the name of their beloved riding horse.",
      },
      lt: {
        question: "Kuris šokoladukas pavadintas Marsų šeimos žirgo vardu?",
        correct: "Snickers",
        distractors: ["Twix", "Bounty", "Mars", "Milky Way", "Galaxy"],
        explanation: "1930 m. batonėlis gavo jų mylimo jojamojo žirgo vardą.",
      },
    },
  },
  {
    id: "brn_fd_015",
    category: "brands",
    subTheme: "food",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Nestlé — founder Henri Nestlé; name means 'little nest', logo is a bird's nest",
    emoji: "🏭",
    translations: {
      en: {
        question: "Nestlé's nest logo fits because the founder's name means what?",
        correct: "Little nest",
        distractors: ["Fresh milk", "Mountain spring", "Pure cream", "Sweet home", "Good morning"],
        explanation: "Henri Nestlé's surname means 'little nest' in his Swiss-German dialect.",
      },
      lt: {
        question: "Ką reiškia Nestlé įkūrėjo pavardė, prie kurios puikiai dera lizdo logotipas?",
        correct: "Mažas lizdas",
        distractors: ["Šviežias pienas", "Kalnų šaltinis", "Tyra grietinėlė", "Mieli namai", "Labas rytas"],
        explanation: "Henrio Nestlé pavardė jo šveicarų tarme reiškia mažą lizdą.",
      },
    },
  },
  {
    id: "brn_fd_016",
    category: "brands",
    subTheme: "food",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Skittles — long advertised with the colourful 'Taste the Rainbow' theme",
    emoji: "🍬",
    translations: {
      en: {
        question: "Which colourful sweets are famous for a slogan about tasting a rainbow?",
        correct: "Skittles",
        distractors: ["M&M's", "Starburst", "Mentos", "Smarties", "Nerds"],
        explanation: "Skittles built its whole image around the bright rainbow of colours.",
      },
      lt: {
        question: "Kurie spalvingi saldainiai garsūs šūkiu apie vaivorykštės skonį?",
        correct: "Skittles",
        distractors: ["M&M's", "Starburst", "Mentos", "Smarties", "Nerds"],
        explanation: "Skittles visą įvaizdį sukūrė aplink ryškią spalvų vaivorykštę.",
      },
    },
  },
  {
    id: "brn_fd_017",
    category: "brands",
    subTheme: "food",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Gatorade — developed at University of Florida for the Gators, 1965",
    emoji: "🥤",
    translations: {
      en: {
        question: "Gatorade was first made to help athletes at which university?",
        correct: "Florida",
        distractors: ["Texas", "Ohio State", "Alabama", "Michigan", "UCLA"],
        explanation: "Scientists mixed it in 1965 for the Florida Gators football team.",
      },
      lt: {
        question: "Gatorade pirmiausia sukurtas padėti kurio universiteto sportininkams?",
        correct: "Floridos",
        distractors: ["Teksaso", "Ohajo", "Alabamos", "Mičigano", "UCLA"],
        explanation: "Mokslininkai jį sumaišė 1965 m. Floridos Gators futbolo komandai.",
      },
    },
  },
  {
    id: "brn_fd_018",
    category: "brands",
    subTheme: "food",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Heinz — '57 Varieties' slogan chosen by H.J. Heinz in 1896, not a real count",
    emoji: "🥫",
    translations: {
      en: {
        question: "Heinz long advertised having how many product varieties?",
        correct: "57",
        distractors: ["27", "99", "100", "12", "64"],
        explanation: "Henry Heinz just liked the number in 1896; it was never a true count.",
      },
      lt: {
        question: "Kiek produktų rūšių Heinz ilgai teigė turinti savo reklamose?",
        correct: "57",
        distractors: ["27", "99", "100", "12", "64"],
        explanation: "Henriui Heinzui 1896 m. tiesiog patiko skaičius; tai niekada nebuvo tikras kiekis.",
      },
    },
  },
  {
    id: "brn_fd_019",
    category: "brands",
    subTheme: "food",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Wrigley — gave away gum as a premium with baking powder; gum outsold it",
    emoji: "🛒",
    translations: {
      en: {
        question: "Wrigley gave free chewing gum to help sell which other product?",
        correct: "Baking powder",
        distractors: ["Soap flakes", "Cleaning powder", "Matches", "Coffee", "Soda"],
        explanation: "The free gum proved far more popular than the powder itself.",
      },
      lt: {
        question: "Wrigley dovanojo nemokamą kramtomąją gumą, kad parduotų kurį kitą produktą?",
        correct: "Kepimo miltelius",
        distractors: ["Muilo dribsnius", "Valymo miltelius", "Degtukus", "Kavą", "Gazuotą"],
        explanation: "Nemokama guma pasirodė kur kas populiaresnė nei patys milteliai.",
      },
    },
  },
  {
    id: "brn_fd_020",
    category: "brands",
    subTheme: "food",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Kinder — Ferrero line for kids; 'Kinder' means 'children' in German, launched 1968",
    emoji: "🍫",
    translations: {
      en: {
        question: "Which brand is famous for chocolate eggs with a toy surprise inside?",
        correct: "Kinder",
        distractors: ["Cadbury", "Milka", "Lindt", "Nestlé", "Hershey"],
        explanation: "Kinder is German for 'children'; the surprise egg appeared in 1974.",
      },
      lt: {
        question: "Kuris prekės ženklas garsus šokoladiniais kiaušiniais su žaislu viduje?",
        correct: "Kinder",
        distractors: ["Cadbury", "Milka", "Lindt", "Nestlé", "Hershey"],
        explanation: "Kinder vokiškai reiškia vaikus; staigmenos kiaušinis pasirodė 1974 m.",
      },
    },
  },

  // ===================== SUNKUS (suaugęs, kuris domisi) =====================
  {
    id: "brn_fd_021",
    category: "brands",
    subTheme: "food",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Pringles can designed by Fredric Baur, an organic chemist; ashes buried in a can",
    emoji: "🥫",
    translations: {
      en: {
        question: "The Pringles tube was designed by Fredric Baur, who worked as a what?",
        correct: "Chemist",
        distractors: ["Architect", "Sculptor", "Plumber", "Banker", "Jeweler"],
        explanation: "So proud of his can, he asked for his ashes to be buried in one.",
      },
      lt: {
        question: "Pringles tūbelę sukūrė Fredricas Bauras — kokia buvo jo profesija?",
        correct: "Chemikas",
        distractors: ["Architektas", "Skulptorius", "Santechnikas", "Bankininkas", "Juvelyras"],
        explanation: "Jis taip didžiavosi savo talpykla, kad paprašė jo pelenus palaidoti tokioje.",
      },
    },
  },
  {
    id: "brn_fd_022",
    category: "brands",
    subTheme: "food",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Toblerone — a bear is hidden in the Matterhorn logo (Bern = city of bears)",
    emoji: "🍫",
    translations: {
      en: {
        question: "Which animal hides inside the mountain on the Toblerone logo?",
        correct: "A bear",
        distractors: ["An eagle", "A lion", "A wolf", "A goat", "A fox"],
        explanation: "It is made in Bern, a city whose symbol has always been the bear.",
      },
      lt: {
        question: "Koks gyvūnas slepiasi kalne ant Toblerone logotipo?",
        correct: "Lokys",
        distractors: ["Erelis", "Liūtas", "Vilkas", "Ožys", "Lapė"],
        explanation: "Jis gaminamas Berne, kurio simbolis nuo seno yra lokys.",
      },
    },
  },
  {
    id: "brn_fd_023",
    category: "brands",
    subTheme: "food",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Dr Pepper — created by pharmacist Charles Alderton, Waco, Texas, 1885",
    emoji: "🥤",
    translations: {
      en: {
        question: "Which soft drink was first mixed by a pharmacist in Waco, Texas?",
        correct: "Dr Pepper",
        distractors: ["Pepsi", "RC Cola", "Fanta", "Sprite", "Mello Yello"],
        explanation: "Charles Alderton blended it at Morrison's drugstore in 1885.",
      },
      lt: {
        question: "Kurį gaivųjį gėrimą Veiko mieste, Teksase, pirmas sumaišė vaistininkas?",
        correct: "Dr Pepper",
        distractors: ["Pepsi", "RC Cola", "Fanta", "Sprite", "Mello Yello"],
        explanation: "Charlesas Aldertonas jį sukūrė Morrisono vaistinėje 1885 m.",
      },
    },
  },
  {
    id: "brn_fd_024",
    category: "brands",
    subTheme: "food",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Red Bull — based on the Thai energy drink Krating Daeng ('red gaur')",
    emoji: "🥤",
    translations: {
      en: {
        question: "Red Bull was inspired by an energy tonic from which country?",
        correct: "Thailand",
        distractors: ["Japan", "India", "Austria", "China", "Vietnam"],
        explanation: "An Austrian adapted the Thai workers' drink Krating Daeng for the West.",
      },
      lt: {
        question: "Red Bull buvo įkvėptas energinio tonizuojančio gėrimo iš kurios šalies?",
        correct: "Tailando",
        distractors: ["Japonijos", "Indijos", "Austrijos", "Kinijos", "Vietnamo"],
        explanation: "Austras pritaikė tajų darbininkų gėrimą Krating Daeng Vakarams.",
      },
    },
  },
  {
    id: "brn_fd_025",
    category: "brands",
    subTheme: "food",
    level: "sunkus",
    isTrap: true,
    sourceVerified: "Milky Way bar — named after a popular malted milk drink, not the galaxy",
    emoji: "🍫",
    translations: {
      en: {
        question: "The Milky Way chocolate bar was actually named after what?",
        correct: "A malted drink",
        distractors: ["The galaxy", "A racehorse", "A song", "A river", "A cow"],
        explanation: "It took its name from a then-popular malted milkshake, not the stars.",
      },
      lt: {
        question: "Šokoladukas Milky Way iš tikrųjų pavadintas pagal ką?",
        correct: "Salyklo gėrimą",
        distractors: ["Galaktiką", "Lenktyninį žirgą", "Dainą", "Upę", "Karvę"],
        explanation: "Vardą jis gavo iš tuomet populiaraus salyklo kokteilio, o ne nuo žvaigždžių.",
      },
    },
  },
  {
    id: "brn_fd_026",
    category: "brands",
    subTheme: "food",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Doritos — first made at Casa de Fritos, Disneyland, early 1960s",
    emoji: "🥫",
    translations: {
      en: {
        question: "Doritos chips were first created and sold at which place?",
        correct: "Disneyland",
        distractors: ["A ballpark", "A cinema", "A gas station", "A school", "A county fair"],
        explanation: "A restaurant there fried up leftover tortillas into the first Doritos.",
      },
      lt: {
        question: "Doritos traškučiai pirmą kartą sukurti ir parduoti kurioje vietoje?",
        correct: "Disneilende",
        distractors: ["Stadione", "Kino teatre", "Degalinėje", "Mokykloje", "Mugėje"],
        explanation: "Tenykštis restoranas iš likusių tortilijų iškepė pirmuosius Doritos.",
      },
    },
  },
  {
    id: "brn_fd_027",
    category: "brands",
    subTheme: "food",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "PEZ — name from German 'Pfefferminz' (peppermint); began as an anti-smoking mint",
    emoji: "🍬",
    translations: {
      en: {
        question: "PEZ candy is named after the German word for which flavour?",
        correct: "Peppermint",
        distractors: ["Lemon", "Honey", "Cherry", "Liquorice", "Aniseed"],
        explanation: "PEZ comes from Pfefferminz; it started as a mint to help quit smoking.",
      },
      lt: {
        question: "PEZ saldainiai pavadinti pagal vokišką kurio skonio žodį?",
        correct: "Pipirmėtės",
        distractors: ["Citrinos", "Medaus", "Vyšnios", "Saldymedžio", "Anyžiaus"],
        explanation: "PEZ kilo iš Pfefferminz; pradžioje tai buvo mėtinis saldainis nuo rūkymo.",
      },
    },
  },
  {
    id: "brn_fd_028",
    category: "brands",
    subTheme: "food",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Cadbury — built model village Bournville for workers near Birmingham, 1890s",
    emoji: "🏭",
    translations: {
      en: {
        question: "Cadbury built a model village for its workers called what?",
        correct: "Bournville",
        distractors: ["Cocoaton", "Cadburyton", "New Birmingham", "Sweetfield", "Chocolton"],
        explanation: "The Quaker Cadbury family built leafy Bournville in the 1890s.",
      },
      lt: {
        question: "Kokiu pavadinimu Cadbury pastatė pavyzdinį miestelį savo darbuotojams?",
        correct: "Bournville",
        distractors: ["Cocoaton", "Cadburyton", "Naujasis Birmingemas", "Sweetfield", "Chocolton"],
        explanation: "Kvakeriška Cadbury šeima 1890-aisiais pastatė žaliąjį Bournville.",
      },
    },
  },
  {
    id: "brn_fd_029",
    category: "brands",
    subTheme: "food",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Spam — popularly said to be a blend of 'spiced ham' (origin kept secret)",
    emoji: "🥫",
    translations: {
      en: {
        question: "The canned meat Spam is popularly said to shorten which two words?",
        correct: "Spiced ham",
        distractors: ["Smoked ham", "Sliced ham", "Salt and ham", "Special meat", "Pork and ham"],
        explanation: "The maker keeps the real origin secret, but spiced ham is the favourite story.",
      },
      lt: {
        question: "Konservuota mėsa Spam, manoma, sutrumpina kuriuos du žodžius?",
        correct: "Spiced ham",
        distractors: ["Smoked ham", "Sliced ham", "Salt and ham", "Special meat", "Pork and ham"],
        explanation: "Gamintojas tikrąją kilmę slepia, bet populiariausia versija — spiced ham.",
      },
    },
  },
  {
    id: "brn_fd_030",
    category: "brands",
    subTheme: "food",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Coca-Cola — its 1930s ads by Haddon Sundblom popularized the modern red Santa image",
    emoji: "🥤",
    translations: {
      en: {
        question: "Which brand's 1930s ads helped shape the popular red-suited Santa?",
        correct: "Coca-Cola",
        distractors: ["Pepsi", "Cadbury", "Nestlé", "Hershey", "Lipton"],
        explanation: "An illustrator painted the jolly Santa for Coca-Cola, fixing the look.",
      },
      lt: {
        question: "Kurio ženklo 1930-ųjų reklamos padėjo įtvirtinti raudonai apsirengusį Kalėdų Senelį?",
        correct: "Coca-Cola",
        distractors: ["Pepsi", "Cadbury", "Nestlé", "Hershey", "Lipton"],
        explanation: "Iliustratorius nupiešė linksmąjį Senelį Coca-Cola reklamoms ir įtvirtino įvaizdį.",
      },
    },
  },

  // ===================== EKSTREMALUS (srities žinovas) =====================
  {
    id: "brn_fd_031",
    category: "brands",
    subTheme: "food",
    level: "ekstremalus",
    isTrap: true,
    sourceVerified: "Häagen-Dazs — invented Danish-sounding name by Reuben Mattus in the Bronx, NY",
    emoji: "🍦",
    translations: {
      en: {
        question: "The Häagen-Dazs ice-cream brand was actually founded in which place?",
        correct: "New York",
        distractors: ["Copenhagen", "Oslo", "Stockholm", "Reykjavik", "Vienna"],
        explanation: "The Danish-sounding name was invented in the Bronx to seem exotic.",
      },
      lt: {
        question: "Kurioje vietoje iš tikrųjų įkurtas ledų prekės ženklas Häagen-Dazs?",
        correct: "Niujorke",
        distractors: ["Kopenhagoje", "Osle", "Stokholme", "Reikjavike", "Vienoje"],
        explanation: "Daniškai skambantis vardas sugalvotas Bronkse, kad atrodytų egzotiškas.",
      },
    },
  },
  {
    id: "brn_fd_032",
    category: "brands",
    subTheme: "food",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Michelin Guide — started by a tire firm to encourage motoring (more driving, more tires)",
    emoji: "🍴",
    translations: {
      en: {
        question: "A tire company started the Michelin restaurant guide to encourage what?",
        correct: "Driving",
        distractors: ["Cooking", "Tourism abroad", "Eating out", "Train travel", "Walking"],
        explanation: "More road trips meant more worn-out tires to replace and sell.",
      },
      lt: {
        question: "Padangų įmonė pradėjo Michelin restoranų gidą, kad paskatintų ką?",
        correct: "Vairavimą",
        distractors: ["Gaminimą", "Keliones į užsienį", "Maitinimąsi", "Keliones traukiniu", "Vaikščiojimą"],
        explanation: "Daugiau kelionių automobiliu reiškė daugiau nudėvėtų padangų pardavimui.",
      },
    },
  },
  {
    id: "brn_fd_033",
    category: "brands",
    subTheme: "food",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Milton Hershey founded the Hershey Industrial (Milton Hershey) School for orphan boys",
    emoji: "🍫",
    translations: {
      en: {
        question: "Chocolate maker Milton Hershey also founded a famous what?",
        correct: "School",
        distractors: ["Hospital", "Church", "Zoo", "Library", "Stadium"],
        explanation: "His school for orphan children still owns much of the company today.",
      },
      lt: {
        question: "Ką garsaus, be šokolado, taip pat įkūrė Miltonas Hershey?",
        correct: "Mokyklą",
        distractors: ["Ligoninę", "Bažnyčią", "Zoologijos sodą", "Biblioteką", "Stadioną"],
        explanation: "Jo mokykla našlaičiams ir šiandien valdo didelę bendrovės dalį.",
      },
    },
  },
  {
    id: "brn_fd_034",
    category: "brands",
    subTheme: "food",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "PepsiCo owns Tropicana (historically), Quaker Oats and Gatorade",
    emoji: "🏭",
    translations: {
      en: {
        question: "Quaker Oats and Gatorade both sit under which drinks-and-snacks giant?",
        correct: "PepsiCo",
        distractors: ["Coca-Cola", "Nestlé", "Unilever", "Kraft", "Mars"],
        explanation: "PepsiCo's empire reaches far beyond its famous cola.",
      },
      lt: {
        question: "Quaker Oats ir Gatorade abu priklauso kuriam gėrimų ir užkandžių milžinui?",
        correct: "PepsiCo",
        distractors: ["Coca-Cola", "Nestlé", "Unilever", "Kraft", "Mars"],
        explanation: "PepsiCo imperija toli peržengia jos garsiosios kolos ribas.",
      },
    },
  },
  {
    id: "brn_fd_035",
    category: "brands",
    subTheme: "food",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Unilever long ran the Heartbrand ice cream (Wall's, Algida...) under one heart logo; ice cream demerged into The Magnum Ice Cream Co. Dec 2025 — framed historically",
    emoji: "🍦",
    translations: {
      en: {
        question: "For decades one heart logo united ice creams like Wall's and Algida under which firm?",
        correct: "Unilever",
        distractors: ["Nestlé", "Mars", "Danone", "Mondelez", "General Mills"],
        explanation: "Brands like Wall's and Algida long shared one company's red heart logo.",
      },
      lt: {
        question: "Daugelį metų vienas širdies logotipas jungė ledus Wall's ir Algida po kuria bendrove?",
        correct: "Unilever",
        distractors: ["Nestlé", "Mars", "Danone", "Mondelez", "General Mills"],
        explanation: "Tokie ženklai kaip Wall's ir Algida ilgai dalijosi tos pačios bendrovės širdies logotipu.",
      },
    },
  },
  {
    id: "brn_fd_036",
    category: "brands",
    subTheme: "food",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "J.S. Fry & Sons made the first solid eating chocolate bar, 1847",
    emoji: "🍫",
    translations: {
      en: {
        question: "Which British firm pressed the first solid eating chocolate bar in 1847?",
        correct: "Fry's",
        distractors: ["Cadbury", "Lindt", "Nestlé", "Hershey", "Rowntree"],
        explanation: "Joseph Fry mixed cocoa into a paste that could be moulded into bars.",
      },
      lt: {
        question: "Kuri britų bendrovė 1847 m. išspaudė pirmą kietą valgomą šokolado plytelę?",
        correct: "Fry's",
        distractors: ["Cadbury", "Lindt", "Nestlé", "Hershey", "Rowntree"],
        explanation: "Josephas Fry kakavą pavertė mase, kurią buvo galima lieti plytelėmis.",
      },
    },
  },
  {
    id: "brn_fd_037",
    category: "brands",
    subTheme: "food",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Nescafé — launched by Nestlé in 1938 amid Brazil's coffee surplus",
    emoji: "☕",
    translations: {
      en: {
        question: "Which company launched powdered instant coffee as Nescafé in 1938?",
        correct: "Nestlé",
        distractors: ["Maxwell House", "Lavazza", "Folgers", "Douwe Egberts", "Kenco"],
        explanation: "Brazil's mountain of unsold coffee pushed Nestlé to invent it.",
      },
      lt: {
        question: "Kuri bendrovė 1938 m. išleido tirpiąją kavą pavadinimu Nescafé?",
        correct: "Nestlé",
        distractors: ["Maxwell House", "Lavazza", "Folgers", "Douwe Egberts", "Kenco"],
        explanation: "Brazilijos neparduotos kavos kalnas paskatino Nestlé ją sukurti.",
      },
    },
  },
  {
    id: "brn_fd_038",
    category: "brands",
    subTheme: "food",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Ray Kroc bought McDonald's from the McDonald brothers and franchised it worldwide",
    emoji: "🍔",
    translations: {
      en: {
        question: "Who bought McDonald's from the founding brothers and franchised it worldwide?",
        correct: "Ray Kroc",
        distractors: ["Dave Thomas", "Colonel Sanders", "Glen Bell", "Carl Karcher", "Howard Johnson"],
        explanation: "A milkshake-machine salesman, he turned the burger shop into a global chain.",
      },
      lt: {
        question: "Kas nupirko McDonald's iš įkūrėjų brolių ir išplėtė jį po visą pasaulį?",
        correct: "Ray Kroc",
        distractors: ["Dave Thomas", "Colonel Sanders", "Glen Bell", "Carl Karcher", "Howard Johnson"],
        explanation: "Kokteilių aparatų pardavėjas pavertė mėsainių užkandinę pasauliniu tinklu.",
      },
    },
  },
  {
    id: "brn_fd_039",
    category: "brands",
    subTheme: "food",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Sprite — launched by Coca-Cola in 1961 to compete with 7 Up",
    emoji: "🥤",
    translations: {
      en: {
        question: "Coca-Cola launched Sprite in 1961 mainly to rival which lemon-lime soda?",
        correct: "7 Up",
        distractors: ["Pepsi", "Fanta", "Tango", "Mirinda", "Schweppes"],
        explanation: "Sprite was Coca-Cola's answer to the popularity of 7 Up.",
      },
      lt: {
        question: "Coca-Cola 1961 m. išleido Sprite daugiausia kad konkuruotų su kuriuo gėrimu?",
        correct: "7 Up",
        distractors: ["Pepsi", "Fanta", "Tango", "Mirinda", "Schweppes"],
        explanation: "Sprite buvo Coca-Cola atsakas į 7 Up populiarumą.",
      },
    },
  },
  {
    id: "brn_fd_040",
    category: "brands",
    subTheme: "food",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Ferrero makes Nutella, Ferrero Rocher, Kinder and Tic Tac; based in Alba, Italy",
    emoji: "🍫",
    translations: {
      en: {
        question: "Nutella, Ferrero Rocher and Tic Tac all come from which Italian company?",
        correct: "Ferrero",
        distractors: ["Perugina", "Lavazza", "Barilla", "Lindt", "Nestlé"],
        explanation: "All these treats are made by Ferrero in the town of Alba.",
      },
      lt: {
        question: "Nutella, Ferrero Rocher ir Tic Tac — visi iš kurios italų bendrovės?",
        correct: "Ferrero",
        distractors: ["Perugina", "Lavazza", "Barilla", "Lindt", "Nestlé"],
        explanation: "Visus šiuos skanėstus gamina Ferrero Albos miestelyje.",
      },
    },
  },
];
