/**
 * cosmosPlanets — 🪐 „Planetos ir Saulės sistema" potemė (tema „Kosmosas").
 *
 * MAŽAS FAILAS pagal potemę (savininko valia 2026-06-13: maži dokumentai, kad
 * būtų lengva taisyti). Kiekviena Kosmoso potemė — atskiras failas; juos sujungia
 * plonas cosmosContent.ts indeksas.
 *
 * 40 klausimų (10/lygiui). Faktai nusistovėję (planetos/Saulės sistema). NEKARTOJA
 * tech „space" potemės faktų (Jupiteris didžiausias, Marsas raudonas, Saturno žiedai,
 * Mercury arčiausiai, Olimpo kalnas, Ganimedas, Titano metanas, Veneros para>metai,
 * Uranas ant šono, karščiausia Venera, Saulė=vandenilis — TŲ čia NĖRA).
 *
 * TAISYKLĖS: 1 teisingas + 5 distraktoriai; visi ≤46 simb. abiem kalbom; teisingas
 * NE ilgiausias >+5; LT kabutės „..."; jokio atsakymo klausime; emoji neišduoda.
 */

import { TriviaQuestion } from "./triviaTypes";

export const COSMOS_PLANETS: TriviaQuestion[] = [
  // ===================== LENGVAS (9–12 m. vaikas) =====================
  {
    id: "cos_pla_001",
    category: "cosmos",
    subTheme: "planets",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "NASA — Mercury is the smallest planet",
    emoji: "🪐",
    translations: {
      en: {
        question: "Which planet is the smallest in our Solar System?",
        correct: "Mercury",
        distractors: ["Mars", "Venus", "Earth", "Pluto", "Neptune"],
        explanation: "Mercury is only a little bigger than our Moon.",
      },
      lt: {
        question: "Kuri planeta yra mažiausia mūsų Saulės sistemoje?",
        correct: "Merkurijus",
        distractors: ["Marsas", "Venera", "Žemė", "Plutonas", "Neptūnas"],
        explanation: "Merkurijus tik truputį didesnis už mūsų Mėnulį.",
      },
    },
  },
  {
    id: "cos_pla_002",
    category: "cosmos",
    subTheme: "planets",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Basic astronomy — Solar System definition",
    emoji: "☀️",
    translations: {
      en: {
        question: "What do we call the Sun together with all the planets around it?",
        correct: "The Solar System",
        distractors: ["The galaxy", "The universe", "The Milky Way", "A constellation", "A nebula"],
        explanation: "Our Solar System has the Sun, 8 planets and many moons.",
      },
      lt: {
        question: "Kaip vadinama Saulė kartu su visomis aplink ją skriejančiomis planetomis?",
        correct: "Saulės sistema",
        distractors: ["Galaktika", "Visata", "Paukščių Takas", "Žvaigždynas", "Ūkas"],
        explanation: "Saulės sistemą sudaro Saulė, 8 planetos ir daug mėnulių.",
      },
    },
  },
  {
    id: "cos_pla_003",
    category: "cosmos",
    subTheme: "planets",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Basic astronomy — orbit",
    emoji: "🔄",
    translations: {
      en: {
        question: "What do we call the path a planet travels around the Sun?",
        correct: "An orbit",
        distractors: ["A circle", "A lap", "A spin", "A loop", "A track"],
        explanation: "Planets follow oval-shaped orbits around the Sun.",
      },
      lt: {
        question: "Kaip vadinamas kelias, kuriuo planeta juda aplink Saulę?",
        correct: "Orbita",
        distractors: ["Apskritimas", "Ratas", "Sukimasis", "Kilpa", "Takelis"],
        explanation: "Planetos skrieja ovaliomis orbitomis aplink Saulę.",
      },
    },
  },
  {
    id: "cos_pla_004",
    category: "cosmos",
    subTheme: "planets",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Basic astronomy — meteor",
    emoji: "☄️",
    translations: {
      en: {
        question: "What do we call a 'shooting star' that streaks across the sky?",
        correct: "A meteor",
        distractors: ["A planet", "A comet", "A galaxy", "A satellite", "A star"],
        explanation: "A meteor is a small rock burning up in our atmosphere.",
      },
      lt: {
        question: "Kaip vadinama „krintanti žvaigždė”, brėžianti dangų?",
        correct: "Meteoras",
        distractors: ["Planeta", "Kometa", "Galaktika", "Palydovas", "Žvaigždė"],
        explanation: "Meteoras — mažas akmuo, sudegantis mūsų atmosferoje.",
      },
    },
  },
  {
    id: "cos_pla_005",
    category: "cosmos",
    subTheme: "planets",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Basic astronomy — Moon reflects sunlight",
    emoji: "🌙",
    translations: {
      en: {
        question: "What lights up the Moon so we can see it at night?",
        correct: "The Sun",
        distractors: ["The stars", "The Earth", "Itself", "Streetlights", "Fire"],
        explanation: "The Moon makes no light; it reflects the Sun's light.",
      },
      lt: {
        question: "Kas apšviečia Mėnulį, kad jį matytume naktį?",
        correct: "Saulė",
        distractors: ["Žvaigždės", "Žemė", "Jis pats", "Gatvių žibintai", "Ugnis"],
        explanation: "Mėnulis šviesos neskleidžia — jis atspindi Saulės šviesą.",
      },
    },
  },
  {
    id: "cos_pla_006",
    category: "cosmos",
    subTheme: "planets",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Basic astronomy — Earth's rotation causes day/night",
    emoji: "🌍",
    translations: {
      en: {
        question: "What causes day and night on Earth?",
        correct: "Earth spinning",
        distractors: ["The Moon moving", "The Sun moving", "Clouds passing", "The seasons", "Earth's tilt"],
        explanation: "Earth spins once about every 24 hours, making day and night.",
      },
      lt: {
        question: "Kas sukelia dieną ir naktį Žemėje?",
        correct: "Žemės sukimasis",
        distractors: ["Mėnulio judėjimas", "Saulės judėjimas", "Praplaukiantys debesys", "Metų laikai", "Žemės pokrypis"],
        explanation: "Žemė apsisuka maždaug per 24 valandas — taip kaitaliojasi diena ir naktis.",
      },
    },
  },
  {
    id: "cos_pla_007",
    category: "cosmos",
    subTheme: "planets",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "NASA — Earth is the third planet from the Sun",
    emoji: "🌎",
    translations: {
      en: {
        question: "Which planet is the third one from the Sun?",
        correct: "Earth",
        distractors: ["Venus", "Mars", "Mercury", "Jupiter", "Saturn"],
        explanation: "Order from the Sun: Mercury, Venus, Earth, Mars...",
      },
      lt: {
        question: "Kuri planeta yra trečia nuo Saulės?",
        correct: "Žemė",
        distractors: ["Venera", "Marsas", "Merkurijus", "Jupiteris", "Saturnas"],
        explanation: "Eilė nuo Saulės: Merkurijus, Venera, Žemė, Marsas...",
      },
    },
  },
  {
    id: "cos_pla_008",
    category: "cosmos",
    subTheme: "planets",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "NASA — the Sun is far larger than Earth",
    emoji: "☀️",
    translations: {
      en: {
        question: "Which is much bigger — the Sun or the Earth?",
        correct: "The Sun",
        distractors: ["The Earth", "They are equal", "The Moon", "Mars", "You can't tell"],
        explanation: "About a million Earths could fit inside the Sun.",
      },
      lt: {
        question: "Kas daug didesnis — Saulė ar Žemė?",
        correct: "Saulė",
        distractors: ["Žemė", "Jos vienodos", "Mėnulis", "Marsas", "Negalima pasakyti"],
        explanation: "Į Saulę tilptų apie milijonas Žemių.",
      },
    },
  },
  {
    id: "cos_pla_009",
    category: "cosmos",
    subTheme: "planets",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Basic astronomy — a moon is a natural satellite",
    emoji: "🌗",
    translations: {
      en: {
        question: "What do we call a natural companion that orbits a planet?",
        correct: "A moon",
        distractors: ["A star", "A comet", "A planet", "A galaxy", "A rocket"],
        explanation: "Many planets have moons; Earth has one — our Moon.",
      },
      lt: {
        question: "Kaip vadinamas natūralus palydovas, skriejantis aplink planetą?",
        correct: "Palydovas",
        distractors: ["Žvaigždė", "Kometa", "Planeta", "Galaktika", "Raketa"],
        explanation: "Daugelis planetų turi palydovų; Žemė turi vieną — Mėnulį.",
      },
    },
  },
  {
    id: "cos_pla_010",
    category: "cosmos",
    subTheme: "planets",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "NASA — Neptune is the farthest, coldest major planet",
    emoji: "🔵",
    translations: {
      en: {
        question: "Which planet is famous for being very cold and far from the Sun?",
        correct: "Neptune",
        distractors: ["Mercury", "Venus", "Mars", "Jupiter", "Earth"],
        explanation: "Neptune is the most distant planet from the Sun.",
      },
      lt: {
        question: "Kuri planeta garsi tuo, kad labai šalta ir toli nuo Saulės?",
        correct: "Neptūnas",
        distractors: ["Merkurijus", "Venera", "Marsas", "Jupiteris", "Žemė"],
        explanation: "Neptūnas — toliausia nuo Saulės esanti planeta.",
      },
    },
  },

  // ===================== VIDUTINIS (12–18 m.) =====================
  {
    id: "cos_pla_011",
    category: "cosmos",
    subTheme: "planets",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Roman mythology — Jupiter, king of the gods",
    emoji: "⚡",
    translations: {
      en: {
        question: "Which planet is named after the Roman king of the gods?",
        correct: "Jupiter",
        distractors: ["Mars", "Saturn", "Neptune", "Mercury", "Venus"],
        explanation: "Jupiter is the largest planet — fittingly named for the king.",
      },
      lt: {
        question: "Kuri planeta pavadinta romėnų dievų karaliaus vardu?",
        correct: "Jupiteris",
        distractors: ["Marsas", "Saturnas", "Neptūnas", "Merkurijus", "Venera"],
        explanation: "Jupiteris — didžiausia planeta, tinkamai pavadinta karaliaus vardu.",
      },
    },
  },
  {
    id: "cos_pla_012",
    category: "cosmos",
    subTheme: "planets",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "NASA — asteroid belt between Mars and Jupiter",
    emoji: "☄️",
    translations: {
      en: {
        question: "Between which two planets does the asteroid belt lie?",
        correct: "Mars and Jupiter",
        distractors: ["Earth and Mars", "Jupiter and Saturn", "Venus and Earth", "Saturn and Uranus", "Mercury and Venus"],
        explanation: "The main asteroid belt orbits between Mars and Jupiter.",
      },
      lt: {
        question: "Tarp kurių dviejų planetų driekiasi asteroidų žiedas?",
        correct: "Marso ir Jupiterio",
        distractors: ["Žemės ir Marso", "Jupiterio ir Saturno", "Veneros ir Žemės", "Saturno ir Urano", "Merkurijaus ir Veneros"],
        explanation: "Pagrindinis asteroidų žiedas skrieja tarp Marso ir Jupiterio.",
      },
    },
  },
  {
    id: "cos_pla_013",
    category: "cosmos",
    subTheme: "planets",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "NASA — Saturn's density is less than water",
    emoji: "🪐",
    translations: {
      en: {
        question: "Which planet is so light it could float in water?",
        correct: "Saturn",
        distractors: ["Jupiter", "Neptune", "Uranus", "Mars", "Mercury"],
        explanation: "Saturn's average density is less than that of water.",
      },
      lt: {
        question: "Kuri planeta tokia lengva, kad galėtų plūduriuoti vandenyje?",
        correct: "Saturnas",
        distractors: ["Jupiteris", "Neptūnas", "Uranas", "Marsas", "Merkurijus"],
        explanation: "Vidutinis Saturno tankis mažesnis nei vandens.",
      },
    },
  },
  {
    id: "cos_pla_014",
    category: "cosmos",
    subTheme: "planets",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "NASA — Venus is similar in size to Earth",
    emoji: "🌕",
    translations: {
      en: {
        question: "Which planet is often called Earth's twin because of its size?",
        correct: "Venus",
        distractors: ["Mars", "Mercury", "Neptune", "Saturn", "Jupiter"],
        explanation: "Venus is almost the same size as Earth, but far hotter.",
      },
      lt: {
        question: "Kuri planeta dėl dydžio dažnai vadinama Žemės dvyne?",
        correct: "Venera",
        distractors: ["Marsas", "Merkurijus", "Neptūnas", "Saturnas", "Jupiteris"],
        explanation: "Venera beveik tokio pat dydžio kaip Žemė, tik daug karštesnė.",
      },
    },
  },
  {
    id: "cos_pla_015",
    category: "cosmos",
    subTheme: "planets",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "NASA — Neptune has the fastest winds",
    emoji: "🌬️",
    translations: {
      en: {
        question: "Which planet has the fastest winds in the Solar System?",
        correct: "Neptune",
        distractors: ["Jupiter", "Saturn", "Uranus", "Mars", "Venus"],
        explanation: "Neptune's winds can reach about 2,000 km/h.",
      },
      lt: {
        question: "Kurioje planetoje pučia greičiausi vėjai Saulės sistemoje?",
        correct: "Neptūnas",
        distractors: ["Jupiteris", "Saturnas", "Uranas", "Marsas", "Venera"],
        explanation: "Neptūno vėjai gali siekti apie 2 000 km/h.",
      },
    },
  },
  {
    id: "cos_pla_016",
    category: "cosmos",
    subTheme: "planets",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "NASA — Ceres, dwarf planet in the asteroid belt",
    emoji: "🪨",
    translations: {
      en: {
        question: "Which dwarf planet sits inside the main asteroid belt?",
        correct: "Ceres",
        distractors: ["Pluto", "Eris", "Makemake", "Haumea", "Charon"],
        explanation: "Ceres is the largest object in the asteroid belt.",
      },
      lt: {
        question: "Kuri nykštukinė planeta yra pagrindiniame asteroidų žiede?",
        correct: "Cerera",
        distractors: ["Plutonas", "Eridė", "Makemakė", "Haumėja", "Charonas"],
        explanation: "Cerera — didžiausias asteroidų žiedo objektas.",
      },
    },
  },
  {
    id: "cos_pla_017",
    category: "cosmos",
    subTheme: "planets",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Basic astronomy — Earth's orbital period is one year",
    emoji: "📅",
    translations: {
      en: {
        question: "How long does Earth take to travel once around the Sun?",
        correct: "One year",
        distractors: ["One day", "One month", "Ten years", "One week", "100 days"],
        explanation: "One full orbit of the Sun is exactly what we call a year.",
      },
      lt: {
        question: "Per kiek laiko Žemė vieną kartą apskrieja Saulę?",
        correct: "Per vienus metus",
        distractors: ["Per vieną dieną", "Per vieną mėnesį", "Per dešimt metų", "Per vieną savaitę", "Per 100 dienų"],
        explanation: "Vienas pilnas ratas aplink Saulę ir yra tai, ką vadiname metais.",
      },
    },
  },
  {
    id: "cos_pla_018",
    category: "cosmos",
    subTheme: "planets",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "NASA — Jupiter has the shortest day (~9.9 h)",
    emoji: "🪐",
    translations: {
      en: {
        question: "Which planet spins fastest, with a day under 11 hours?",
        correct: "Jupiter",
        distractors: ["Earth", "Mars", "Venus", "Mercury", "Saturn"],
        explanation: "Despite its size, Jupiter spins once in under 10 hours.",
      },
      lt: {
        question: "Kuri planeta sukasi greičiausiai — para trumpesnė nei 11 valandų?",
        correct: "Jupiteris",
        distractors: ["Žemė", "Marsas", "Venera", "Merkurijus", "Saturnas"],
        explanation: "Nepaisant dydžio, Jupiteris apsisuka greičiau nei per 10 valandų.",
      },
    },
  },
  {
    id: "cos_pla_019",
    category: "cosmos",
    subTheme: "planets",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "NASA — Mercury and Venus have no moons",
    emoji: "🌑",
    translations: {
      en: {
        question: "Which two planets have no moons at all?",
        correct: "Mercury and Venus",
        distractors: ["Earth and Mars", "Mars and Venus", "Mercury and Earth", "Venus and Earth", "Mars and Mercury"],
        explanation: "All other planets have at least one moon; these two have none.",
      },
      lt: {
        question: "Kurios dvi planetos visai neturi mėnulių?",
        correct: "Merkurijus ir Venera",
        distractors: ["Žemė ir Marsas", "Marsas ir Venera", "Merkurijus ir Žemė", "Venera ir Žemė", "Marsas ir Merkurijus"],
        explanation: "Visos kitos planetos turi bent vieną mėnulį, o šios dvi — nė vieno.",
      },
    },
  },
  {
    id: "cos_pla_020",
    category: "cosmos",
    subTheme: "planets",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "NASA — Mars's moons Phobos and Deimos",
    emoji: "🔴",
    translations: {
      en: {
        question: "What are the names of Mars's two small moons?",
        correct: "Phobos and Deimos",
        distractors: ["Io and Europa", "Titan and Rhea", "Luna and Charon", "Deimos and Ceres", "Phobos and Titan"],
        explanation: "Phobos and Deimos are small, lumpy, asteroid-like moons.",
      },
      lt: {
        question: "Kaip vadinasi du maži Marso mėnuliai?",
        correct: "Fobas ir Deimas",
        distractors: ["Ijo ir Europa", "Titanas ir Rėja", "Luna ir Charonas", "Deimas ir Cerera", "Fobas ir Titanas"],
        explanation: "Fobas ir Deimas — maži, gumbuoti, į asteroidus panašūs mėnuliai.",
      },
    },
  },

  // ===================== SUNKUS (suaugę) =====================
  {
    id: "cos_pla_021",
    category: "cosmos",
    subTheme: "planets",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "NASA — Io (Jupiter's moon) is the most volcanic body",
    emoji: "🌋",
    translations: {
      en: {
        question: "Which planet's moon Io is the most volcanic place we know?",
        correct: "Jupiter",
        distractors: ["Saturn", "Neptune", "Mars", "Uranus", "Venus"],
        explanation: "Io, a moon of Jupiter, has hundreds of active volcanoes.",
      },
      lt: {
        question: "Kurios planetos mėnulis Ijo yra vulkaniškiausia žinoma vieta?",
        correct: "Jupiteris",
        distractors: ["Saturnas", "Neptūnas", "Marsas", "Uranas", "Venera"],
        explanation: "Ijo, Jupiterio mėnulis, turi šimtus aktyvių ugnikalnių.",
      },
    },
  },
  {
    id: "cos_pla_022",
    category: "cosmos",
    subTheme: "planets",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "NASA — Europa likely has a subsurface ocean",
    emoji: "🧊",
    translations: {
      en: {
        question: "Which icy moon of Jupiter likely hides a salty ocean?",
        correct: "Europa",
        distractors: ["Io", "Titan", "Ganymede", "Callisto", "Enceladus"],
        explanation: "Beneath Europa's ice may lie more water than all Earth's seas.",
      },
      lt: {
        question: "Kuris ledinis Jupiterio mėnulis tikriausiai slepia sūrų vandenyną?",
        correct: "Europa",
        distractors: ["Ijo", "Titanas", "Ganimedas", "Kalisto", "Enceladas"],
        explanation: "Po Europos ledu gali būti daugiau vandens nei visose Žemės jūrose.",
      },
    },
  },
  {
    id: "cos_pla_023",
    category: "cosmos",
    subTheme: "planets",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Astronomy history — Neptune predicted by math, 1846",
    emoji: "🔭",
    translations: {
      en: {
        question: "Which planet was found using math before anyone saw it?",
        correct: "Neptune",
        distractors: ["Uranus", "Pluto", "Saturn", "Mercury", "Mars"],
        explanation: "Neptune's place was calculated from Uranus's odd orbit (1846).",
      },
      lt: {
        question: "Kuri planeta buvo rasta skaičiavimais, dar jos nepamačius?",
        correct: "Neptūnas",
        distractors: ["Uranas", "Plutonas", "Saturnas", "Merkurijus", "Marsas"],
        explanation: "Neptūno vietą apskaičiavo iš keisto Urano judėjimo (1846 m.).",
      },
    },
  },
  {
    id: "cos_pla_024",
    category: "cosmos",
    subTheme: "planets",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Planetary science — diamond rain on ice giants",
    emoji: "💎",
    translations: {
      en: {
        question: "On which planets do scientists think it may rain diamonds?",
        correct: "Neptune and Uranus",
        distractors: ["Mars and Venus", "Jupiter and Saturn", "Earth and Mars", "Mercury and Venus", "Saturn and Mars"],
        explanation: "Deep pressure may squeeze carbon into diamonds on both ice giants.",
      },
      lt: {
        question: "Kuriose planetose, mokslininkų manymu, gali lyti deimantais?",
        correct: "Neptūne ir Urane",
        distractors: ["Marse ir Veneroje", "Jupiteryje ir Saturne", "Žemėje ir Marse", "Merkurijuje ir Veneroje", "Saturne ir Marse"],
        explanation: "Gilumos slėgis ten gali spausti anglį į deimantus.",
      },
    },
  },
  {
    id: "cos_pla_025",
    category: "cosmos",
    subTheme: "planets",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Astrophysics — the Sun is a G-type (yellow dwarf) star",
    emoji: "☀️",
    translations: {
      en: {
        question: "What type of star is our Sun?",
        correct: "A yellow dwarf",
        distractors: ["A red giant", "A white dwarf", "A blue giant", "A neutron star", "A supergiant"],
        explanation: "The Sun is a middle-aged yellow dwarf (a G-type star).",
      },
      lt: {
        question: "Kokio tipo žvaigždė yra mūsų Saulė?",
        correct: "Geltonoji nykštukė",
        distractors: ["Raudonoji milžinė", "Baltoji nykštukė", "Mėlynoji milžinė", "Neutroninė žvaigždė", "Supermilžinė"],
        explanation: "Saulė — vidutinio amžiaus geltonoji nykštukė (G tipo žvaigždė).",
      },
    },
  },
  {
    id: "cos_pla_026",
    category: "cosmos",
    subTheme: "planets",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Astronomy — the Moon is tidally locked to Earth",
    emoji: "🌚",
    translations: {
      en: {
        question: "Why does the same side of the Moon always face Earth?",
        correct: "It is tidally locked",
        distractors: ["It does not spin", "Earth's magnetism", "The Sun holds it", "It spins too fast", "Air resistance"],
        explanation: "The Moon rotates once per orbit, so one face always faces us.",
      },
      lt: {
        question: "Kodėl mums visada matoma ta pati Mėnulio pusė?",
        correct: "Sinchroninis sukimasis",
        distractors: ["Jis nesisuka", "Žemės magnetizmas", "Saulė jį laiko", "Sukasi per greitai", "Oro pasipriešinimas"],
        explanation: "Mėnulis apsisuka kartą per orbitą, tad rodo tą pačią pusę.",
      },
    },
  },
  {
    id: "cos_pla_027",
    category: "cosmos",
    subTheme: "planets",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "NASA — Mercury's year is about 88 Earth days",
    emoji: "☄️",
    translations: {
      en: {
        question: "About how many Earth-days long is one year on Mercury?",
        correct: "About 88 days",
        distractors: ["About 365 days", "About 30 days", "About 687 days", "About 225 days", "About 12 days"],
        explanation: "Mercury races around the Sun in just 88 days.",
      },
      lt: {
        question: "Maždaug kiek Žemės parų trunka vieni metai Merkurijuje?",
        correct: "Apie 88 dienas",
        distractors: ["Apie 365 dienas", "Apie 30 dienų", "Apie 687 dienas", "Apie 225 dienas", "Apie 12 dienų"],
        explanation: "Merkurijus aplekia Saulę vos per 88 dienas.",
      },
    },
  },
  {
    id: "cos_pla_028",
    category: "cosmos",
    subTheme: "planets",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "NASA — Saturn's rings are mostly water ice and rock",
    emoji: "💍",
    translations: {
      en: {
        question: "What are Saturn's bright rings mostly made of?",
        correct: "Ice and rock",
        distractors: ["Gas and dust", "Pure metal", "Liquid water", "Burning fire", "Solid glass"],
        explanation: "The rings are countless chunks of ice and rock orbiting Saturn.",
      },
      lt: {
        question: "Iš ko daugiausia sudaryti ryškūs Saturno žiedai?",
        correct: "Ledo ir uolienų",
        distractors: ["Dujų ir dulkių", "Gryno metalo", "Skysto vandens", "Liepsnos", "Stiklo"],
        explanation: "Žiedai — nesuskaičiuojami ledo ir uolienų gabalai aplink Saturną.",
      },
    },
  },
  {
    id: "cos_pla_029",
    category: "cosmos",
    subTheme: "planets",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "NASA — Venus has retrograde (backward) rotation",
    emoji: "🔄",
    translations: {
      en: {
        question: "Which planet spins backwards compared to most others?",
        correct: "Venus",
        distractors: ["Uranus", "Mars", "Jupiter", "Mercury", "Neptune"],
        explanation: "On Venus the Sun would rise in the west and set in the east.",
      },
      lt: {
        question: "Kuri planeta sukasi atvirkščiai nei dauguma kitų?",
        correct: "Venera",
        distractors: ["Uranas", "Marsas", "Jupiteris", "Merkurijus", "Neptūnas"],
        explanation: "Veneroje Saulė tekėtų vakaruose, o leistųsi rytuose.",
      },
    },
  },
  {
    id: "cos_pla_030",
    category: "cosmos",
    subTheme: "planets",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "NASA — Mars has planet-wide dust storms",
    emoji: "🟠",
    translations: {
      en: {
        question: "Which planet has dust storms that can cover the whole globe?",
        correct: "Mars",
        distractors: ["Venus", "Jupiter", "Mercury", "Saturn", "Earth"],
        explanation: "Martian dust storms can rage for weeks across the planet.",
      },
      lt: {
        question: "Kurioje planetoje dulkių audros gali apgaubti visą rutulį?",
        correct: "Marsas",
        distractors: ["Venera", "Jupiteris", "Merkurijus", "Saturnas", "Žemė"],
        explanation: "Marso dulkių audros gali siausti savaitėmis po visą planetą.",
      },
    },
  },

  // ===================== EKSTREMALUS (žinovai) =====================
  {
    id: "cos_pla_031",
    category: "cosmos",
    subTheme: "planets",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "NASA — the heliopause bounds the heliosphere",
    emoji: "🌌",
    translations: {
      en: {
        question: "What is the edge where the Sun's wind meets interstellar space?",
        correct: "The heliopause",
        distractors: ["The event horizon", "The Roche limit", "The Lagrange point", "The ecliptic plane", "The photosphere"],
        explanation: "Voyager 1 crossed the heliopause into interstellar space in 2012.",
      },
      lt: {
        question: "Kaip vadinama riba, kur Saulės vėjas susitinka su tarpžvaigždine erdve?",
        correct: "Heliopauzė",
        distractors: ["Įvykių horizontas", "Rošo riba", "Lagranžo taškas", "Ekliptikos plokštuma", "Fotosfera"],
        explanation: "Voyager 1 kirto heliopauzę į tarpžvaigždinę erdvę 2012 m.",
      },
    },
  },
  {
    id: "cos_pla_032",
    category: "cosmos",
    subTheme: "planets",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "NASA — Eris, distant dwarf planet (discovered 2005)",
    emoji: "🪨",
    translations: {
      en: {
        question: "Which distant dwarf planet was once dubbed a '10th planet'?",
        correct: "Eris",
        distractors: ["Ceres", "Vesta", "Pallas", "Sedna", "Hygiea"],
        explanation: "Eris's 2005 discovery led to defining 'dwarf planet' in 2006.",
      },
      lt: {
        question: "Kuri tolima nykštukinė planeta kadaise vadinta „dešimtąja planeta”?",
        correct: "Eridė",
        distractors: ["Cerera", "Vesta", "Paladė", "Sedna", "Higėja"],
        explanation: "Eridės atradimas 2005 m. paskatino 2006 m. apibrėžti „nykštukinę planetą”.",
      },
    },
  },
  {
    id: "cos_pla_033",
    category: "cosmos",
    subTheme: "planets",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Astrophysics — the Sun holds ~99.8% of system mass",
    emoji: "☀️",
    translations: {
      en: {
        question: "About what share of the Solar System's mass is in the Sun?",
        correct: "About 99.8%",
        distractors: ["About 50%", "About 75%", "About 90%", "About 25%", "About 10%"],
        explanation: "Almost all the system's mass is the Sun; planets are leftovers.",
      },
      lt: {
        question: "Maždaug kokią Saulės sistemos masės dalį sudaro Saulė?",
        correct: "Apie 99,8 %",
        distractors: ["Apie 50 %", "Apie 75 %", "Apie 90 %", "Apie 25 %", "Apie 10 %"],
        explanation: "Beveik visa sistemos masė — Saulė; planetos tėra likučiai.",
      },
    },
  },
  {
    id: "cos_pla_034",
    category: "cosmos",
    subTheme: "planets",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Astronomy — the four Galilean moons of Jupiter",
    emoji: "🔭",
    translations: {
      en: {
        question: "What are Jupiter's four big moons collectively called?",
        correct: "The Galilean moons",
        distractors: ["The Medicean rings", "The Saturnian moons", "The Jovian belt", "The Lagrange moons", "The Kepler moons"],
        explanation: "Galileo spotted Io, Europa, Ganymede and Callisto in 1610.",
      },
      lt: {
        question: "Kaip bendrai vadinami keturi dideli Jupiterio mėnuliai?",
        correct: "Galilėjiniai mėnuliai",
        distractors: ["Medičėjų žiedai", "Saturno mėnuliai", "Jovijaus juosta", "Lagranžo mėnuliai", "Keplerio mėnuliai"],
        explanation: "Galilėjus 1610 m. pastebėjo Ijo, Europą, Ganimedą ir Kalisto.",
      },
    },
  },
  {
    id: "cos_pla_035",
    category: "cosmos",
    subTheme: "planets",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "NASA — Galileo was first to orbit Jupiter (1995)",
    emoji: "🛰️",
    translations: {
      en: {
        question: "Which probe was the first to orbit Jupiter, arriving in 1995?",
        correct: "Galileo",
        distractors: ["Cassini", "Juno", "Voyager 1", "Pioneer 10", "New Horizons"],
        explanation: "The Galileo orbiter studied Jupiter and its moons for 8 years.",
      },
      lt: {
        question: "Kuris zondas pirmas pradėjo skrieti aplink Jupiterį (1995 m.)?",
        correct: "Galileo",
        distractors: ["Cassini", "Juno", "Voyager 1", "Pioneer 10", "New Horizons"],
        explanation: "Galileo zondas 8 metus tyrė Jupiterį ir jo mėnulius.",
      },
    },
  },
  {
    id: "cos_pla_036",
    category: "cosmos",
    subTheme: "planets",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "NASA — Triton orbits Neptune retrograde (captured)",
    emoji: "🔵",
    translations: {
      en: {
        question: "Which big moon orbits Neptune backwards, likely a captured world?",
        correct: "Triton",
        distractors: ["Titan", "Charon", "Europa", "Phobos", "Miranda"],
        explanation: "Triton's backward orbit hints it was captured from the Kuiper Belt.",
      },
      lt: {
        question: "Kuris didelis mėnulis aplink Neptūną skrieja atbulai, tikriausiai pagautas?",
        correct: "Tritonas",
        distractors: ["Titanas", "Charonas", "Europa", "Fobas", "Miranda"],
        explanation: "Atbula Tritono orbita rodo, kad jis pagautas iš Koiperio žiedo.",
      },
    },
  },
  {
    id: "cos_pla_037",
    category: "cosmos",
    subTheme: "planets",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "NASA — Valles Marineris, vast canyon on Mars",
    emoji: "🟥",
    translations: {
      en: {
        question: "What is the name of the vast canyon system on Mars?",
        correct: "Valles Marineris",
        distractors: ["Olympus Mons", "Hellas Basin", "Mariana Rille", "Noctis Maze", "Tharsis Gap"],
        explanation: "Valles Marineris stretches over 4,000 km — far longer than any on Earth.",
      },
      lt: {
        question: "Kaip vadinasi milžiniška kanjonų sistema Marse?",
        correct: "Valles Marineris",
        distractors: ["Olimpo kalnas", "Helo baseinas", "Marianos vaga", "Noktiso labirintas", "Tarsio plyšys"],
        explanation: "Valles Marineris driekiasi per 4 000 km — daug ilgesnis nei bet kuris Žemėje.",
      },
    },
  },
  {
    id: "cos_pla_038",
    category: "cosmos",
    subTheme: "planets",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "NASA — Saturn's hexagonal north-pole storm",
    emoji: "⬡",
    translations: {
      en: {
        question: "Which planet has a six-sided (hexagon) storm at its north pole?",
        correct: "Saturn",
        distractors: ["Jupiter", "Neptune", "Uranus", "Earth", "Venus"],
        explanation: "Saturn's polar hexagon is wide enough to swallow several Earths.",
      },
      lt: {
        question: "Kurios planetos šiauriniame ašigalyje sukasi šešiakampė audra?",
        correct: "Saturnas",
        distractors: ["Jupiteris", "Neptūnas", "Uranas", "Žemė", "Venera"],
        explanation: "Į Saturno ašigalio šešiakampį tilptų kelios Žemės.",
      },
    },
  },
  {
    id: "cos_pla_039",
    category: "cosmos",
    subTheme: "planets",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Orbital mechanics — Lagrange points",
    emoji: "🛰️",
    translations: {
      en: {
        question: "What is a stable spot where a craft can park between two big bodies?",
        correct: "A Lagrange point",
        distractors: ["A Roche limit", "An event horizon", "A heliopause", "A barycenter", "An apsis"],
        explanation: "The James Webb telescope parks at the Sun-Earth L2 Lagrange point.",
      },
      lt: {
        question: "Kaip vadinama stabili vieta, kur tarp dviejų kūnų gali stovėti zondas?",
        correct: "Lagranžo taškas",
        distractors: ["Rošo riba", "Įvykių horizontas", "Heliopauzė", "Baricentras", "Apsidė"],
        explanation: "Džeimso Webo teleskopas stovi Saulės–Žemės L2 Lagranžo taške.",
      },
    },
  },
  {
    id: "cos_pla_040",
    category: "cosmos",
    subTheme: "planets",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "NASA — Neptune's orbital period ≈ 165 years",
    emoji: "🔵",
    translations: {
      en: {
        question: "About how long does Neptune take to orbit the Sun once?",
        correct: "About 165 years",
        distractors: ["About 84 years", "About 30 years", "About 248 years", "About 12 years", "About 1 year"],
        explanation: "Neptune has completed only one orbit since its 1846 discovery.",
      },
      lt: {
        question: "Maždaug per kiek laiko Neptūnas vieną kartą apskrieja Saulę?",
        correct: "Apie 165 metus",
        distractors: ["Apie 84 metus", "Apie 30 metų", "Apie 248 metus", "Apie 12 metų", "Apie 1 metus"],
        explanation: "Nuo atradimo 1846 m. Neptūnas apskriejo Saulę tik vieną kartą.",
      },
    },
  },
];
