/**
 * cosmosUniverse — 🔭 „Visata ir žvaigždės" potemė (tema „Kosmosas").
 *
 * MAŽAS FAILAS pagal potemę. 40 klausimų (10/lygiui). Tema — gilus kosmosas:
 * galaktikos, žvaigždės, juodosios skylės, Visatos kilmė ir paslaptys.
 * NEKARTOJA spacerace (supernova, įvykių horizontas, žvaigždynas, Visatos amžius,
 * Hubble/Webb) nei planets (Saulė=geltonoji nykštukė, heliopauzė) faktų.
 *
 * TAISYKLĖS: 1 teisingas + 5 distraktoriai; ≤46 simb.; teisingas NE ilgiausias >+5;
 * LT be vidinių kabučių; jokio atsakymo klausime.
 */

import { TriviaQuestion } from "./triviaTypes";

export const COSMOS_UNIVERSE: TriviaQuestion[] = [
  // ===================== LENGVAS (9–12 m. vaikas) =====================
  {
    id: "cos_uni_001",
    category: "cosmos",
    subTheme: "universe",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Astronomy — our galaxy is the Milky Way",
    emoji: "🌌",
    translations: {
      en: {
        question: "What is the name of the galaxy we live in?",
        correct: "The Milky Way",
        distractors: ["Andromeda", "The Big Dipper", "The Sun", "Orion", "The Solar System"],
        explanation: "Our Sun is one of billions of stars in the Milky Way.",
      },
      lt: {
        question: "Kaip vadinasi galaktika, kurioje gyvename?",
        correct: "Paukščių Takas",
        distractors: ["Andromeda", "Grįžulo Ratai", "Saulė", "Orionas", "Saulės sistema"],
        explanation: "Mūsų Saulė — viena iš milijardų Paukščių Tako žvaigždžių.",
      },
    },
  },
  {
    id: "cos_uni_002",
    category: "cosmos",
    subTheme: "universe",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Astronomy — the Sun is a star",
    emoji: "☀️",
    translations: {
      en: {
        question: "Is the Sun a planet or a star?",
        correct: "A star",
        distractors: ["A planet", "A moon", "A comet", "An asteroid", "A galaxy"],
        explanation: "The Sun is an average-sized star that gives us light and heat.",
      },
      lt: {
        question: "Saulė yra planeta ar žvaigždė?",
        correct: "Žvaigždė",
        distractors: ["Planeta", "Mėnulis", "Kometa", "Asteroidas", "Galaktika"],
        explanation: "Saulė — vidutinio dydžio žvaigždė, teikianti šviesą ir šilumą.",
      },
    },
  },
  {
    id: "cos_uni_003",
    category: "cosmos",
    subTheme: "universe",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Astronomy — a galaxy is a huge group of stars",
    emoji: "🌌",
    translations: {
      en: {
        question: "What do we call a huge group of billions of stars?",
        correct: "A galaxy",
        distractors: ["A planet", "A country", "A village", "A crowd", "A forest"],
        explanation: "Galaxies hold billions of stars, gas and dust.",
      },
      lt: {
        question: "Kaip vadinama didžiulė milijardų žvaigždžių grupė?",
        correct: "Galaktika",
        distractors: ["Planeta", "Valstybė", "Kaimas", "Minia", "Miškas"],
        explanation: "Galaktikose telpa milijardai žvaigždžių, dujų ir dulkių.",
      },
    },
  },
  {
    id: "cos_uni_004",
    category: "cosmos",
    subTheme: "universe",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Astronomy — stars look small because they are distant",
    emoji: "✨",
    translations: {
      en: {
        question: "Why do stars look so tiny from Earth?",
        correct: "They are very far away",
        distractors: ["They are truly tiny", "They are hiding", "They are asleep", "They are dim lamps", "They are clouds"],
        explanation: "Stars are huge, but their great distance makes them look like dots.",
      },
      lt: {
        question: "Kodėl žvaigždės iš Žemės atrodo tokios mažytės?",
        correct: "Jos labai toli",
        distractors: ["Jos tikrai mažytės", "Jos slepiasi", "Jos miega", "Jos blankios lempos", "Jos yra debesys"],
        explanation: "Žvaigždės milžiniškos, bet dėl didelio nuotolio jos atrodo kaip taškeliai.",
      },
    },
  },
  {
    id: "cos_uni_005",
    category: "cosmos",
    subTheme: "universe",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Astronomy — a comet's tail",
    emoji: "☄️",
    translations: {
      en: {
        question: "What do we call the long glowing trail behind a comet?",
        correct: "Its tail",
        distractors: ["Its head", "Its wing", "Its root", "Its shadow", "Its rope"],
        explanation: "Sunlight and solar wind push a comet's tail away from the Sun.",
      },
      lt: {
        question: "Kaip vadinama ilga švytinti juosta paskui kometą?",
        correct: "Uodega",
        distractors: ["Galva", "Sparnas", "Šaknis", "Šešėlis", "Virvė"],
        explanation: "Saulės šviesa ir Saulės vėjas nupučia kometos uodegą tolyn nuo Saulės.",
      },
    },
  },
  {
    id: "cos_uni_006",
    category: "cosmos",
    subTheme: "universe",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Astronomy — stars are far larger than planets",
    emoji: "⭐",
    translations: {
      en: {
        question: "Which is usually bigger — a star or a planet?",
        correct: "A star",
        distractors: ["A planet", "Both the same", "The Moon", "You can't tell", "A comet"],
        explanation: "Most stars are vastly bigger than any planet.",
      },
      lt: {
        question: "Kas paprastai didesnis — žvaigždė ar planeta?",
        correct: "Žvaigždė",
        distractors: ["Planeta", "Abi vienodos", "Mėnulis", "Negalima pasakyti", "Kometa"],
        explanation: "Dauguma žvaigždžių yra milžiniškai didesnės už bet kurią planetą.",
      },
    },
  },
  {
    id: "cos_uni_007",
    category: "cosmos",
    subTheme: "universe",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Astronomy — nebula as a star-forming cloud",
    emoji: "☁️",
    translations: {
      en: {
        question: "What do we call a giant cloud of gas where stars are born?",
        correct: "A nebula",
        distractors: ["A crater", "A desert", "A river", "A cave", "A meadow"],
        explanation: "Gravity pulls nebula gas together until new stars switch on.",
      },
      lt: {
        question: "Kaip vadinamas milžiniškas dujų debesis, kuriame gimsta žvaigždės?",
        correct: "Ūkas",
        distractors: ["Krateris", "Dykuma", "Upė", "Urvas", "Pieva"],
        explanation: "Gravitacija traukia ūko dujas, kol įsižiebia naujos žvaigždės.",
      },
    },
  },
  {
    id: "cos_uni_008",
    category: "cosmos",
    subTheme: "universe",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Astronomy — interstellar distances are vast",
    emoji: "🚀",
    translations: {
      en: {
        question: "Can we quickly travel to other stars with today's rockets?",
        correct: "No, they are too far",
        distractors: ["Yes, in one day", "Yes, by airplane", "Yes, by car", "Yes, in an hour", "Yes, very easily"],
        explanation: "Even the nearest star is trillions of kilometers away.",
      },
      lt: {
        question: "Ar šiandienos raketomis galime greitai nuskristi iki kitų žvaigždžių?",
        correct: "Ne, jos per toli",
        distractors: ["Taip, per dieną", "Taip, lėktuvu", "Taip, automobiliu", "Taip, per valandą", "Taip, labai lengvai"],
        explanation: "Net artimiausia žvaigždė yra už trilijonų kilometrų.",
      },
    },
  },
  {
    id: "cos_uni_009",
    category: "cosmos",
    subTheme: "universe",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Astronomy — the universe is everything that exists",
    emoji: "🌌",
    translations: {
      en: {
        question: "What do we call all of space and everything in it?",
        correct: "The universe",
        distractors: ["The galaxy", "The sky", "The Earth", "The ocean", "The country"],
        explanation: "The universe holds all galaxies, stars, planets and space itself.",
      },
      lt: {
        question: "Kaip vadinama visa erdvė ir viskas, kas joje yra?",
        correct: "Visata",
        distractors: ["Galaktika", "Dangus", "Žemė", "Vandenynas", "Valstybė"],
        explanation: "Visatą sudaro visos galaktikos, žvaigždės, planetos ir pati erdvė.",
      },
    },
  },
  {
    id: "cos_uni_010",
    category: "cosmos",
    subTheme: "universe",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Astronomy — twinkling caused by Earth's atmosphere",
    emoji: "✨",
    translations: {
      en: {
        question: "Why do stars seem to twinkle in the night sky?",
        correct: "Earth's air bends light",
        distractors: ["They blink on and off", "They are dying", "They spin fast", "They get tired", "They explode"],
        explanation: "Moving air high above us bends starlight, so stars seem to flicker.",
      },
      lt: {
        question: "Kodėl naktiniame danguje žvaigždės atrodo mirgančios?",
        correct: "Žemės oras lenkia šviesą",
        distractors: ["Jos užsidega ir gęsta", "Jos miršta", "Jos greit sukasi", "Jos pavargsta", "Jos sprogsta"],
        explanation: "Judantis oras virš mūsų lenkia žvaigždžių šviesą, tad jos mirga.",
      },
    },
  },

  // ===================== VIDUTINIS (12–18 m.) =====================
  {
    id: "cos_uni_011",
    category: "cosmos",
    subTheme: "universe",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Astronomy — a light-year measures distance",
    emoji: "📏",
    translations: {
      en: {
        question: "A 'light-year' is a measure of what?",
        correct: "Distance",
        distractors: ["Time", "Speed", "Weight", "Brightness", "Age"],
        explanation: "It is how far light travels in one year — about 9.5 trillion km.",
      },
      lt: {
        question: "Šviesmetis yra ko matas?",
        correct: "Atstumo",
        distractors: ["Laiko", "Greičio", "Svorio", "Ryškumo", "Amžiaus"],
        explanation: "Tai kelias, kurį šviesa nukeliauja per metus — apie 9,5 trln. km.",
      },
    },
  },
  {
    id: "cos_uni_012",
    category: "cosmos",
    subTheme: "universe",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Astronomy — Andromeda, nearest large galaxy",
    emoji: "🌌",
    translations: {
      en: {
        question: "Which large galaxy is the nearest to our Milky Way?",
        correct: "Andromeda",
        distractors: ["The Sombrero", "Triangulum", "Whirlpool", "Pinwheel", "Cartwheel"],
        explanation: "Andromeda is about 2.5 million light-years away.",
      },
      lt: {
        question: "Kuri didelė galaktika yra arčiausiai mūsų Paukščių Tako?",
        correct: "Andromeda",
        distractors: ["Sombrero", "Triangulum", "Verpetas", "Vėjo malūnėlis", "Vežimo ratas"],
        explanation: "Andromeda nutolusi apie 2,5 milijono šviesmečių.",
      },
    },
  },
  {
    id: "cos_uni_013",
    category: "cosmos",
    subTheme: "universe",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Astronomy — Sirius is the brightest night-sky star",
    emoji: "⭐",
    translations: {
      en: {
        question: "What is the brightest star in Earth's night sky?",
        correct: "Sirius",
        distractors: ["Polaris", "Betelgeuse", "Vega", "Rigel", "Antares"],
        explanation: "Sirius shines brightly and is fairly close, about 8.6 light-years.",
      },
      lt: {
        question: "Kuri žvaigždė ryškiausia Žemės naktiniame danguje?",
        correct: "Sirijus",
        distractors: ["Šiaurinė", "Betelgeizė", "Vega", "Rigelis", "Antaresas"],
        explanation: "Sirijus ryškus ir gana arti — apie 8,6 šviesmečio.",
      },
    },
  },
  {
    id: "cos_uni_014",
    category: "cosmos",
    subTheme: "universe",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Astronomy — the Milky Way is a spiral galaxy",
    emoji: "🌀",
    translations: {
      en: {
        question: "What shape is our Milky Way galaxy?",
        correct: "A spiral",
        distractors: ["A cube", "A ring", "A square", "A cone", "A straight line"],
        explanation: "It is a barred spiral, with arms winding out from the center.",
      },
      lt: {
        question: "Kokios formos yra mūsų Paukščių Tako galaktika?",
        correct: "Spiralės",
        distractors: ["Kubo", "Žiedo", "Kvadrato", "Kūgio", "Tiesios linijos"],
        explanation: "Tai spiralinė galaktika su iš centro besivyniojančiomis vijomis.",
      },
    },
  },
  {
    id: "cos_uni_015",
    category: "cosmos",
    subTheme: "universe",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Astrophysics — blue stars are the hottest",
    emoji: "🔵",
    translations: {
      en: {
        question: "Red stars are cooler — which color marks the hottest stars?",
        correct: "Blue",
        distractors: ["Red", "Yellow", "Orange", "Green", "Brown"],
        explanation: "Hotter stars glow blue-white; cooler ones glow red.",
      },
      lt: {
        question: "Raudonos žvaigždės vėsesnės — kuri spalva žymi karščiausias?",
        correct: "Mėlyna",
        distractors: ["Raudona", "Geltona", "Oranžinė", "Žalia", "Ruda"],
        explanation: "Karštesnės žvaigždės švyti melsvai, vėsesnės — raudonai.",
      },
    },
  },
  {
    id: "cos_uni_016",
    category: "cosmos",
    subTheme: "universe",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Astronomy — Polaris, the North Star",
    emoji: "🧭",
    translations: {
      en: {
        question: "Which star sits above the North Pole and guides travelers?",
        correct: "Polaris",
        distractors: ["Sirius", "Vega", "Betelgeuse", "Rigel", "Antares"],
        explanation: "Polaris stays nearly fixed while other stars seem to circle it.",
      },
      lt: {
        question: "Kuri žvaigždė stovi virš Šiaurės ašigalio ir veda keliautojus?",
        correct: "Šiaurinė",
        distractors: ["Sirijus", "Vega", "Betelgeizė", "Rigelis", "Antaresas"],
        explanation: "Šiaurinė beveik nejuda, o kitos žvaigždės tarsi sukasi aplink ją.",
      },
    },
  },
  {
    id: "cos_uni_017",
    category: "cosmos",
    subTheme: "universe",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Astronomy — starlight shows the past",
    emoji: "⏳",
    translations: {
      en: {
        question: "When we look at distant stars, we are seeing...?",
        correct: "The past",
        distractors: ["The future", "The present", "Nothing real", "A mirror", "Tomorrow"],
        explanation: "Their light traveled for years, so we see how they looked long ago.",
      },
      lt: {
        question: "Žvelgdami į tolimas žvaigždes, mes matome...?",
        correct: "Praeitį",
        distractors: ["Ateitį", "Dabartį", "Nieko tikro", "Veidrodį", "Rytojų"],
        explanation: "Jų šviesa keliavo metų metus, tad matome, kokios jos buvo seniai.",
      },
    },
  },
  {
    id: "cos_uni_018",
    category: "cosmos",
    subTheme: "universe",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Cosmology — the Big Bang theory",
    emoji: "💥",
    translations: {
      en: {
        question: "What is the theory of how the universe began?",
        correct: "The Big Bang",
        distractors: ["The Big Crunch", "The Steady State", "The Cold Start", "The Big Freeze", "The Great Wall"],
        explanation: "The universe began tiny and hot, then expanded for billions of years.",
      },
      lt: {
        question: "Kaip vadinama teorija apie Visatos pradžią?",
        correct: "Didysis sprogimas",
        distractors: ["Didysis susitraukimas", "Pastovi būsena", "Šaltas startas", "Didysis šaltis", "Didžioji siena"],
        explanation: "Visata gimė maža ir karšta, paskui milijardus metų plėtėsi.",
      },
    },
  },
  {
    id: "cos_uni_019",
    category: "cosmos",
    subTheme: "universe",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Physics — speed of light ~300,000 km/s",
    emoji: "⚡",
    translations: {
      en: {
        question: "About how fast does light travel through space?",
        correct: "About 300,000 km/s",
        distractors: ["About 30,000 km/s", "About 1,000 km/s", "About 3 million km/s", "About 300 km/s", "About 30 km/s"],
        explanation: "Nothing we know of can travel faster than light.",
      },
      lt: {
        question: "Maždaug kokiu greičiu šviesa sklinda erdve?",
        correct: "Apie 300 000 km/s",
        distractors: ["Apie 30 000 km/s", "Apie 1 000 km/s", "Apie 3 mln. km/s", "Apie 300 km/s", "Apie 30 km/s"],
        explanation: "Niekas, ką žinome, negali judėti greičiau už šviesą.",
      },
    },
  },
  {
    id: "cos_uni_020",
    category: "cosmos",
    subTheme: "universe",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Astronomy — the Milky Way has hundreds of billions of stars",
    emoji: "🌟",
    translations: {
      en: {
        question: "Roughly how many stars does our Milky Way hold?",
        correct: "Hundreds of billions",
        distractors: ["About one thousand", "About a million", "Exactly eight", "A few hundred", "About ten"],
        explanation: "Estimates run from 100 to 400 billion stars.",
      },
      lt: {
        question: "Maždaug kiek žvaigždžių yra mūsų Paukščių Take?",
        correct: "Šimtai milijardų",
        distractors: ["Apie tūkstantį", "Apie milijoną", "Lygiai aštuonios", "Keli šimtai", "Apie dešimt"],
        explanation: "Vertinama nuo 100 iki 400 milijardų žvaigždžių.",
      },
    },
  },

  // ===================== SUNKUS (suaugę) =====================
  {
    id: "cos_uni_021",
    category: "cosmos",
    subTheme: "universe",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Astrophysics — supermassive black hole at galaxy center",
    emoji: "⚫",
    translations: {
      en: {
        question: "What lurks at the very center of our Milky Way?",
        correct: "A black hole",
        distractors: ["A giant star", "A bright planet", "A huge comet", "Empty space", "A second sun"],
        explanation: "A supermassive black hole called Sagittarius A* sits there.",
      },
      lt: {
        question: "Kas tūno pačiame mūsų Paukščių Tako centre?",
        correct: "Juodoji skylė",
        distractors: ["Milžiniška žvaigždė", "Ryški planeta", "Didelė kometa", "Tuščia erdvė", "Antra saulė"],
        explanation: "Ten yra supermasyvi juodoji skylė, vadinama Šaulio A*.",
      },
    },
  },
  {
    id: "cos_uni_022",
    category: "cosmos",
    subTheme: "universe",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Astrophysics — neutron star is a collapsed stellar core",
    emoji: "⭐",
    translations: {
      en: {
        question: "What is the tiny, super-dense core left after a big star dies?",
        correct: "A neutron star",
        distractors: ["A white dwarf", "A red giant", "A brown dwarf", "A blue moon", "A gas cloud"],
        explanation: "A sugar-cube of neutron star matter would weigh billions of tons.",
      },
      lt: {
        question: "Kas lieka kaip mažytė, itin tanki šerdis žuvus didelei žvaigždei?",
        correct: "Neutroninė žvaigždė",
        distractors: ["Baltoji nykštukė", "Raudonoji milžinė", "Rudoji nykštukė", "Mėlynas mėnulis", "Dujų debesis"],
        explanation: "Cukraus gabalėlio dydžio neutroninės medžiagos gabalas svertų milijardus tonų.",
      },
    },
  },
  {
    id: "cos_uni_023",
    category: "cosmos",
    subTheme: "universe",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Astronomy — Milky Way and Andromeda will collide",
    emoji: "🌌",
    translations: {
      en: {
        question: "Andromeda is heading our way — what happens in ~4 billion years?",
        correct: "They will collide",
        distractors: ["It will vanish", "It will stop", "It will shrink", "Nothing at all", "It will explode"],
        explanation: "The two galaxies will slowly merge into one bigger galaxy.",
      },
      lt: {
        question: "Andromeda artėja — kas nutiks po maždaug 4 milijardų metų?",
        correct: "Jos susidurs",
        distractors: ["Ji išnyks", "Ji sustos", "Ji susitrauks", "Visai nieko", "Ji sprogs"],
        explanation: "Abi galaktikos lėtai susilies į vieną didesnę galaktiką.",
      },
    },
  },
  {
    id: "cos_uni_024",
    category: "cosmos",
    subTheme: "universe",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Cosmology — cosmic microwave background",
    emoji: "📡",
    translations: {
      en: {
        question: "What faint glow, left from the Big Bang, fills the whole sky?",
        correct: "Cosmic background",
        distractors: ["Northern lights", "Star shine", "Sunlight echo", "Moon glow", "Comet dust"],
        explanation: "This microwave 'afterglow' is detected in every direction.",
      },
      lt: {
        question: "Koks blankus švytėjimas, likęs po Didžiojo sprogimo, užpildo dangų?",
        correct: "Kosminis fonas",
        distractors: ["Šiaurės pašvaistė", "Žvaigždžių spindesys", "Saulės aidas", "Mėnulio švytėjimas", "Kometų dulkės"],
        explanation: "Šis silpnas mikrobangų švytėjimas aptinkamas iš visų pusių.",
      },
    },
  },
  {
    id: "cos_uni_025",
    category: "cosmos",
    subTheme: "universe",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Astrophysics — stars are mostly hydrogen and helium",
    emoji: "☀️",
    translations: {
      en: {
        question: "Stars are mostly made of which two gases?",
        correct: "Hydrogen and helium",
        distractors: ["Oxygen and carbon", "Nitrogen and neon", "Iron and gold", "Water and air", "Carbon and argon"],
        explanation: "Stars fuse hydrogen into helium, releasing light and heat.",
      },
      lt: {
        question: "Iš kurių dviejų dujų daugiausia sudarytos žvaigždės?",
        correct: "Vandenilio ir helio",
        distractors: ["Deguonies ir anglies", "Azoto ir neono", "Geležies ir aukso", "Vandens ir oro", "Anglies ir argono"],
        explanation: "Žvaigždės jungia vandenilį į helį ir taip skleidžia šviesą bei šilumą.",
      },
    },
  },
  {
    id: "cos_uni_026",
    category: "cosmos",
    subTheme: "universe",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Astrophysics — the Sun will become a red giant",
    emoji: "🔴",
    translations: {
      en: {
        question: "What will our Sun swell into in about 5 billion years?",
        correct: "A red giant",
        distractors: ["A black hole", "A neutron star", "A blue giant", "A pulsar", "A comet"],
        explanation: "It will balloon huge, then shed its layers and shrink to a dwarf.",
      },
      lt: {
        question: "Kuo maždaug po 5 milijardų metų išsipūs mūsų Saulė?",
        correct: "Raudonąja milžine",
        distractors: ["Juodąja skyle", "Neutronine žvaigžde", "Mėlynąja milžine", "Pulsaru", "Kometa"],
        explanation: "Ji milžiniškai išsipūs, paskui nubers sluoksnius ir taps nykštuke.",
      },
    },
  },
  {
    id: "cos_uni_027",
    category: "cosmos",
    subTheme: "universe",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Cosmology — the universe is expanding (Hubble)",
    emoji: "↔️",
    translations: {
      en: {
        question: "Edwin Hubble showed the universe is not still, but...?",
        correct: "Expanding",
        distractors: ["Shrinking", "Standing still", "Spinning", "Only cooling", "Collapsing"],
        explanation: "Distant galaxies are racing away from us in all directions.",
      },
      lt: {
        question: "Edvinas Hablas parodė, kad Visata ne stovi, o...?",
        correct: "Plečiasi",
        distractors: ["Traukiasi", "Stovi vietoje", "Sukasi", "Tik vėsta", "Griūva"],
        explanation: "Tolimos galaktikos tolsta nuo mūsų į visas puses.",
      },
    },
  },
  {
    id: "cos_uni_028",
    category: "cosmos",
    subTheme: "universe",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Astrophysics — a pulsar is a spinning neutron star",
    emoji: "📡",
    translations: {
      en: {
        question: "What is a fast-spinning star that sends out beams like a lighthouse?",
        correct: "A pulsar",
        distractors: ["A quasar", "A planet", "A comet", "A meteor", "A nebula"],
        explanation: "A pulsar's beam sweeps past us as regular pulses.",
      },
      lt: {
        question: "Kas yra greit besisukanti žvaigždė, siunčianti spindulius kaip švyturys?",
        correct: "Pulsaras",
        distractors: ["Kvazaras", "Planeta", "Kometa", "Meteoras", "Ūkas"],
        explanation: "Pulsaro spindulys praslysta pro mus kaip taisyklingi blyksniai.",
      },
    },
  },
  {
    id: "cos_uni_029",
    category: "cosmos",
    subTheme: "universe",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Astronomy — Olbers' paradox (finite age / light travel)",
    emoji: "🌃",
    translations: {
      en: {
        question: "If stars are countless, why is the night sky still dark?",
        correct: "Light hasn't all arrived",
        distractors: ["Stars switch off at night", "The Moon blocks them", "Air absorbs all light", "They shine by day only", "Earth is too small"],
        explanation: "The universe is young enough that distant light hasn't reached us.",
      },
      lt: {
        question: "Jei žvaigždžių nesuskaičiuojama, kodėl naktinis dangus vis tiek tamsus?",
        correct: "Šviesa dar ne visa atėjo",
        distractors: ["Naktį žvaigždės gęsta", "Mėnulis jas užstoja", "Oras sugeria šviesą", "Jos šviečia tik dieną", "Žemė per maža"],
        explanation: "Visata pakankamai jauna, kad tolima šviesa dar mūsų nepasiekė.",
      },
    },
  },
  {
    id: "cos_uni_030",
    category: "cosmos",
    subTheme: "universe",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Astronomy — Proxima Centauri, nearest star to the Sun",
    emoji: "⭐",
    translations: {
      en: {
        question: "What is the nearest star to the Sun, about 4 light-years away?",
        correct: "Proxima Centauri",
        distractors: ["Sirius", "Polaris", "Betelgeuse", "Vega", "Barnard's Star"],
        explanation: "Proxima Centauri is a small red dwarf with a known planet.",
      },
      lt: {
        question: "Kuri žvaigždė artimiausia Saulei, maždaug už 4 šviesmečių?",
        correct: "Proksima Kentauro",
        distractors: ["Sirijus", "Šiaurinė", "Betelgeizė", "Vega", "Barnardo žvaigždė"],
        explanation: "Proksima Kentauro — maža raudonoji nykštukė su žinoma planeta.",
      },
    },
  },

  // ===================== EKSTREMALUS (žinovai) =====================
  {
    id: "cos_uni_031",
    category: "cosmos",
    subTheme: "universe",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Astrophysics — Sagittarius A*, Milky Way's central black hole",
    emoji: "⚫",
    translations: {
      en: {
        question: "What is the name of the black hole at our galaxy's center?",
        correct: "Sagittarius A*",
        distractors: ["Cygnus X-1", "Andromeda", "Betelgeuse", "Proxima", "Polaris"],
        explanation: "It has about 4 million times the mass of our Sun.",
      },
      lt: {
        question: "Kaip vadinasi juodoji skylė mūsų galaktikos centre?",
        correct: "Šaulio A*",
        distractors: ["Gulbės X-1", "Andromeda", "Betelgeizė", "Proksima", "Šiaurinė"],
        explanation: "Jos masė maždaug 4 milijonus kartų didesnė už Saulės.",
      },
    },
  },
  {
    id: "cos_uni_032",
    category: "cosmos",
    subTheme: "universe",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Cosmology — dark matter dominates mass",
    emoji: "🕳️",
    translations: {
      en: {
        question: "What unseen stuff makes up most of the matter in the universe?",
        correct: "Dark matter",
        distractors: ["Bright gas", "Star dust", "Hydrogen", "Antimatter", "Plasma"],
        explanation: "We feel its gravity, but it gives off no light we can see.",
      },
      lt: {
        question: "Kokia nematoma medžiaga sudaro didžiąją Visatos materijos dalį?",
        correct: "Tamsioji materija",
        distractors: ["Ryškios dujos", "Žvaigždžių dulkės", "Vandenilis", "Antimaterija", "Plazma"],
        explanation: "Jos gravitaciją jaučiame, bet ji neskleidžia mums matomos šviesos.",
      },
    },
  },
  {
    id: "cos_uni_033",
    category: "cosmos",
    subTheme: "universe",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Cosmology — dark energy drives accelerating expansion",
    emoji: "↔️",
    translations: {
      en: {
        question: "What mysterious force is speeding up the universe's expansion?",
        correct: "Dark energy",
        distractors: ["Gravity", "Magnetism", "Solar wind", "Friction", "Dark matter"],
        explanation: "Dark energy seems to push space itself apart faster and faster.",
      },
      lt: {
        question: "Kokia paslaptinga jėga greitina Visatos plėtimąsi?",
        correct: "Tamsioji energija",
        distractors: ["Gravitacija", "Magnetizmas", "Saulės vėjas", "Trintis", "Tamsioji materija"],
        explanation: "Tamsioji energija tarsi vis sparčiau stumia pačią erdvę tolyn.",
      },
    },
  },
  {
    id: "cos_uni_034",
    category: "cosmos",
    subTheme: "universe",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Astronomy — Betelgeuse, red supergiant in Orion",
    emoji: "🔴",
    translations: {
      en: {
        question: "Which red supergiant in Orion may explode as a supernova someday?",
        correct: "Betelgeuse",
        distractors: ["Rigel", "Sirius", "Vega", "Polaris", "Aldebaran"],
        explanation: "Betelgeuse is so big it would swallow the inner planets.",
      },
      lt: {
        question: "Kuri raudonoji supermilžinė Orione kada nors gali sprogti kaip supernova?",
        correct: "Betelgeizė",
        distractors: ["Rigelis", "Sirijus", "Vega", "Šiaurinė", "Aldebaranas"],
        explanation: "Betelgeizė tokia didelė, kad prarytų vidines planetas.",
      },
    },
  },
  {
    id: "cos_uni_035",
    category: "cosmos",
    subTheme: "universe",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Astrophysics — redshift of receding galaxies",
    emoji: "🔴",
    translations: {
      en: {
        question: "What do we call the stretching of light from a galaxy moving away?",
        correct: "Redshift",
        distractors: ["Blueshift", "Sunburn", "Glare", "Eclipse", "Mirage"],
        explanation: "Receding galaxies stretch their light toward longer, redder waves.",
      },
      lt: {
        question: "Kaip vadinamas tolstančios galaktikos šviesos ištįsimas?",
        correct: "Raudonasis poslinkis",
        distractors: ["Mėlynasis poslinkis", "Nudegimas", "Akinimas", "Užtemimas", "Miražas"],
        explanation: "Tolstančių galaktikų šviesa ištįsta į ilgesnes, raudonesnes bangas.",
      },
    },
  },
  {
    id: "cos_uni_036",
    category: "cosmos",
    subTheme: "universe",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Cosmology — ~2 trillion galaxies estimated",
    emoji: "🌌",
    translations: {
      en: {
        question: "Roughly how many galaxies are in the observable universe?",
        correct: "About two trillion",
        distractors: ["About one hundred", "About a million", "About one billion", "Exactly eight", "About a thousand"],
        explanation: "Each of those galaxies holds billions of stars of its own.",
      },
      lt: {
        question: "Maždaug kiek galaktikų yra stebimoje Visatoje?",
        correct: "Apie du trilijonus",
        distractors: ["Apie šimtą", "Apie milijoną", "Apie milijardą", "Lygiai aštuonios", "Apie tūkstantį"],
        explanation: "Kiekviena tų galaktikų turi savo milijardus žvaigždžių.",
      },
    },
  },
  {
    id: "cos_uni_037",
    category: "cosmos",
    subTheme: "universe",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Astrophysics — red dwarfs are the most common stars",
    emoji: "⭐",
    translations: {
      en: {
        question: "What is the most common type of star in the universe?",
        correct: "Red dwarf",
        distractors: ["Blue giant", "Yellow dwarf", "Neutron star", "Red giant", "White dwarf"],
        explanation: "Small, cool red dwarfs vastly outnumber stars like our Sun.",
      },
      lt: {
        question: "Koks žvaigždžių tipas Visatoje yra dažniausias?",
        correct: "Raudonoji nykštukė",
        distractors: ["Mėlynoji milžinė", "Geltonoji nykštukė", "Neutroninė žvaigždė", "Raudonoji milžinė", "Baltoji nykštukė"],
        explanation: "Mažos, vėsios raudonosios nykštukės gerokai gausesnės už Saulės tipą.",
      },
    },
  },
  {
    id: "cos_uni_038",
    category: "cosmos",
    subTheme: "universe",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Astrophysics — a quasar is a bright active galactic nucleus",
    emoji: "💡",
    translations: {
      en: {
        question: "What is a blazing, distant galaxy core fed by a giant black hole?",
        correct: "A quasar",
        distractors: ["A pulsar", "A nebula", "A comet", "A nova", "A meteor"],
        explanation: "Quasars can outshine their entire host galaxy of stars.",
      },
      lt: {
        question: "Kas yra akinamai ryškus tolimas galaktikos branduolys, maitinamas juodosios skylės?",
        correct: "Kvazaras",
        distractors: ["Pulsaras", "Ūkas", "Kometa", "Nova", "Meteoras"],
        explanation: "Kvazarai gali nustelbti visą savo galaktikos žvaigždžių šviesą.",
      },
    },
  },
  {
    id: "cos_uni_039",
    category: "cosmos",
    subTheme: "universe",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Astrophysics — kilonova (neutron star merger) forges gold",
    emoji: "💥",
    translations: {
      en: {
        question: "What blast, when two neutron stars merge, forges gold and platinum?",
        correct: "A kilonova",
        distractors: ["A solar flare", "A meteor shower", "A sunspot", "An eclipse", "A moonquake"],
        explanation: "Much of the gold on Earth was likely made in such collisions.",
      },
      lt: {
        question: "Koks sprogimas, susiliejus dviem neutroninėms žvaigždėms, kala auksą ir platiną?",
        correct: "Kilonova",
        distractors: ["Saulės žybsnis", "Meteorų lietus", "Saulės dėmė", "Užtemimas", "Mėnulio drebėjimas"],
        explanation: "Didelė dalis Žemės aukso tikriausiai gimė per tokius susidūrimus.",
      },
    },
  },
  {
    id: "cos_uni_040",
    category: "cosmos",
    subTheme: "universe",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Astronomy — light from Proxima Centauri takes ~4 years",
    emoji: "⏳",
    translations: {
      en: {
        question: "How long does light from the Sun's nearest neighbor star reach us?",
        correct: "About 4 years",
        distractors: ["About 8 minutes", "About 1 second", "About 1,000 years", "About 1 day", "About 1 hour"],
        explanation: "Sunlight takes 8 minutes; the next star's light takes over 4 years.",
      },
      lt: {
        question: "Per kiek laiko mus pasiekia šviesa nuo artimiausios Saulės kaimynės žvaigždės?",
        correct: "Maždaug per 4 metus",
        distractors: ["Maždaug per 8 min.", "Maždaug per 1 sek.", "Maždaug per 1 000 metų", "Maždaug per 1 dieną", "Maždaug per 1 val."],
        explanation: "Saulės šviesa keliauja 8 min., o kitos žvaigždės — daugiau nei 4 metus.",
      },
    },
  },
];
