/**
 * cosmosRockets — 🛰️ „Raketos ir tyrimai" potemė (tema „Kosmosas").
 *
 * MAŽAS FAILAS pagal potemę. 40 klausimų (10/lygiui). Tema — kaip skrendam ir
 * tiriam kosmosą: raketos, palydovai, zondai, misijos. NEKARTOJA spacerace
 * (Falcon/SpaceX, Sputnik, Salyut, Perseverance, Voyager, Hubble, Webb) nei
 * planets (Galileo orbiteris) nei astronauts (Soyuz) faktų.
 *
 * TAISYKLĖS: 1 teisingas + 5 distraktoriai; ≤46 simb.; teisingas NE ilgiausias >+5;
 * LT be vidinių kabučių; jokio atsakymo klausime; jokios politikos (vengiu
 * valstybinių/karinių asmenų — tik neutralūs faktai/objektai).
 */

import { TriviaQuestion } from "./triviaTypes";

export const COSMOS_ROCKETS: TriviaQuestion[] = [
  // ===================== LENGVAS (9–12 m. vaikas) =====================
  {
    id: "cos_roc_001",
    category: "cosmos",
    subTheme: "rockets",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Physics — rockets lift off by burning fuel",
    emoji: "🚀",
    translations: {
      en: {
        question: "What makes a rocket blast off into the sky?",
        correct: "Burning fuel",
        distractors: ["A big fan", "A spring", "Magnets", "A balloon", "Flapping wings"],
        explanation: "Burning fuel shoots hot gas down, pushing the rocket up.",
      },
      lt: {
        question: "Kas pakelia raketą į dangų?",
        correct: "Degantis kuras",
        distractors: ["Didelis ventiliatorius", "Spyruoklė", "Magnetai", "Balionas", "Plasnojantys sparnai"],
        explanation: "Degantis kuras išsviedžia karštas dujas žemyn, o raketą stumia aukštyn.",
      },
    },
  },
  {
    id: "cos_roc_002",
    category: "cosmos",
    subTheme: "rockets",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Spaceflight — satellites orbit and relay signals",
    emoji: "🛰️",
    translations: {
      en: {
        question: "What orbits Earth and sends us TV, internet or GPS signals?",
        correct: "A satellite",
        distractors: ["An airplane", "A drone", "A balloon", "A kite", "A star"],
        explanation: "Thousands of satellites circle Earth carrying signals.",
      },
      lt: {
        question: "Kas skrieja aplink Žemę ir siunčia TV, internetą ar GPS signalus?",
        correct: "Palydovas",
        distractors: ["Lėktuvas", "Dronas", "Balionas", "Aitvaras", "Žvaigždė"],
        explanation: "Tūkstančiai palydovų skrieja aplink Žemę ir perduoda signalus.",
      },
    },
  },
  {
    id: "cos_roc_003",
    category: "cosmos",
    subTheme: "rockets",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Spaceflight — rockets carry astronauts to space",
    emoji: "🚀",
    translations: {
      en: {
        question: "What vehicle carries astronauts up into space?",
        correct: "A rocket",
        distractors: ["A train", "A ship", "A car", "An airplane", "A bicycle"],
        explanation: "Only a rocket is powerful enough to reach space.",
      },
      lt: {
        question: "Kokia transporto priemonė nukelia astronautus į kosmosą?",
        correct: "Raketa",
        distractors: ["Traukinys", "Laivas", "Automobilis", "Lėktuvas", "Dviratis"],
        explanation: "Tik raketa pakankamai galinga pasiekti kosmosą.",
      },
    },
  },
  {
    id: "cos_roc_004",
    category: "cosmos",
    subTheme: "rockets",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "NASA — rovers drive on Mars",
    emoji: "🤖",
    translations: {
      en: {
        question: "What do we call a robot vehicle that drives across Mars?",
        correct: "A rover",
        distractors: ["A boat", "A scooter", "A train", "A tractor", "A glider"],
        explanation: "Rovers roll over rocks and sand to study the Martian ground.",
      },
      lt: {
        question: "Kaip vadinama robotinė mašina, važinėjanti Marse?",
        correct: "Marsaeigis",
        distractors: ["Valtis", "Paspirtukas", "Traukinys", "Traktorius", "Sklandytuvas"],
        explanation: "Marsaeigiai rieda per akmenis ir smėlį tirdami Marso gruntą.",
      },
    },
  },
  {
    id: "cos_roc_005",
    category: "cosmos",
    subTheme: "rockets",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Physics — rockets carry their own oxygen",
    emoji: "💨",
    translations: {
      en: {
        question: "Must a rocket carry its own oxygen to burn fuel in space?",
        correct: "Yes, there's no air",
        distractors: ["No, it uses sunlight", "No, space has air", "No, it uses water", "No, never needed", "No, it uses wind"],
        explanation: "With no air in space, rockets bring oxygen to burn their fuel.",
      },
      lt: {
        question: "Ar raketa turi vežtis savo deguonį, kad degintų kurą kosmose?",
        correct: "Taip, ten nėra oro",
        distractors: ["Ne, naudoja Saulę", "Ne, kosmose yra oro", "Ne, naudoja vandenį", "Ne, niekada nereikia", "Ne, naudoja vėją"],
        explanation: "Kosmose oro nėra, todėl raketa deguonį kurui deginti vežasi pati.",
      },
    },
  },
  {
    id: "cos_roc_006",
    category: "cosmos",
    subTheme: "rockets",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Spaceflight — a launch sends a rocket up",
    emoji: "🚀",
    translations: {
      en: {
        question: "What do we call the moment a rocket is sent up?",
        correct: "A launch",
        distractors: ["A landing", "A parking", "A splash", "A jump", "A drop"],
        explanation: "At launch the engines fire and the rocket lifts off.",
      },
      lt: {
        question: "Kaip vadinama akimirka, kai raketa paleidžiama aukštyn?",
        correct: "Paleidimas",
        distractors: ["Nusileidimas", "Stovėjimas", "Pliumptelėjimas", "Šuolis", "Kritimas"],
        explanation: "Per paleidimą užsidega varikliai ir raketa pakyla.",
      },
    },
  },
  {
    id: "cos_roc_007",
    category: "cosmos",
    subTheme: "rockets",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Astronomy — telescopes let us see far away",
    emoji: "🔭",
    translations: {
      en: {
        question: "What do telescopes help us do?",
        correct: "See faraway things",
        distractors: ["Hear sounds", "Smell gases", "Touch stars", "Taste the planets", "Lift rockets"],
        explanation: "Telescopes gather light to show distant, faint objects.",
      },
      lt: {
        question: "Kam padeda teleskopai?",
        correct: "Matyti tolimus dalykus",
        distractors: ["Girdėti garsus", "Užuosti dujas", "Liesti žvaigždes", "Ragauti tolimas planetas", "Kelti raketas"],
        explanation: "Teleskopai surenka šviesą ir parodo tolimus, blankius objektus.",
      },
    },
  },
  {
    id: "cos_roc_008",
    category: "cosmos",
    subTheme: "rockets",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Spaceflight — robotic probes explore without people",
    emoji: "🛰️",
    translations: {
      en: {
        question: "What do we call a spacecraft with no people, sent to explore?",
        correct: "A probe",
        distractors: ["A jet", "A yacht", "A truck", "A glider", "A canoe"],
        explanation: "Probes fly to far worlds and send back photos and data.",
      },
      lt: {
        question: "Kaip vadinamas erdvėlaivis be žmonių, siunčiamas tyrinėti?",
        correct: "Zondas",
        distractors: ["Reaktyvinis lėktuvas", "Jachta", "Sunkvežimis", "Sklandytuvas", "Baidarė"],
        explanation: "Zondai skrenda į tolimus pasaulius ir siunčia nuotraukas bei duomenis.",
      },
    },
  },
  {
    id: "cos_roc_009",
    category: "cosmos",
    subTheme: "rockets",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Engineering — rockets drop spent stages",
    emoji: "🚀",
    translations: {
      en: {
        question: "What falls away from a rocket once its fuel is used up?",
        correct: "A spent stage",
        distractors: ["The crew", "The windows", "The seats", "The lights", "The doors"],
        explanation: "Dropping empty stages makes the rocket lighter to climb higher.",
      },
      lt: {
        question: "Kas atkrinta nuo raketos, kai sunaudojamas jos kuras?",
        correct: "Tuščia pakopa",
        distractors: ["Įgula", "Langai", "Keleivių sėdynės", "Šviesos", "Durys"],
        explanation: "Numetus tuščias pakopas raketa palengvėja ir kyla aukščiau.",
      },
    },
  },
  {
    id: "cos_roc_010",
    category: "cosmos",
    subTheme: "rockets",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Spaceflight — rockets travel to space",
    emoji: "🌌",
    translations: {
      en: {
        question: "After a successful launch, where does a rocket head?",
        correct: "Into space",
        distractors: ["Underground", "Into the sea", "To a forest", "Into a cave", "Back home"],
        explanation: "It climbs above the air into the emptiness of space.",
      },
      lt: {
        question: "Po sėkmingo paleidimo kur keliauja raketa?",
        correct: "Į kosmosą",
        distractors: ["Po žeme", "Į jūrą", "Į mišką", "Į urvą", "Atgal namo"],
        explanation: "Ji pakyla virš oro į tuščią kosmoso erdvę.",
      },
    },
  },

  // ===================== VIDUTINIS (12–18 m.) =====================
  {
    id: "cos_roc_011",
    category: "cosmos",
    subTheme: "rockets",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Physics — Newton's third law drives rockets",
    emoji: "🚀",
    translations: {
      en: {
        question: "Which idea explains how a rocket pushes itself forward?",
        correct: "Action and reaction",
        distractors: ["The law of floating", "The law of magnets", "The law of heat", "The law of sound", "The law of light"],
        explanation: "Gas pushed backward pushes the rocket forward (Newton's 3rd law).",
      },
      lt: {
        question: "Kuri idėja paaiškina, kaip raketa pati stumiasi pirmyn?",
        correct: "Veiksmas ir atoveiksmis",
        distractors: ["Plūduriavimo dėsnis", "Magnetų dėsnis", "Šilumos dėsnis", "Garso dėsnis", "Šviesos dėsnis"],
        explanation: "Dujos, stumiamos atgal, stumia raketą pirmyn (3-iasis Niutono dėsnis).",
      },
    },
  },
  {
    id: "cos_roc_012",
    category: "cosmos",
    subTheme: "rockets",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Engineering — staging sheds dead weight",
    emoji: "🚀",
    translations: {
      en: {
        question: "Why do big rockets drop off sections as they climb?",
        correct: "To shed dead weight",
        distractors: ["To look cooler", "To make noise", "To slow down", "To turn around", "To signal the ground"],
        explanation: "Once a stage is empty, dumping it lets the rest fly faster.",
      },
      lt: {
        question: "Kodėl didelės raketos kildamos numeta dalis?",
        correct: "Kad numestų svorį",
        distractors: ["Kad gražiau atrodytų", "Kad keltų triukšmą", "Kad sulėtėtų", "Kad apsisuktų", "Kad duotų signalą"],
        explanation: "Kai pakopa tuščia, ją numetus likusi raketa skrenda greičiau.",
      },
    },
  },
  {
    id: "cos_roc_013",
    category: "cosmos",
    subTheme: "rockets",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "NASA — Saturn V launched the Apollo Moon missions",
    emoji: "🚀",
    translations: {
      en: {
        question: "Which giant rocket launched the Apollo crews toward the Moon?",
        correct: "Saturn V",
        distractors: ["Falcon 9", "Atlas", "Titan", "Ariane", "Delta"],
        explanation: "Saturn V is still among the tallest, most powerful rockets ever flown.",
      },
      lt: {
        question: "Kuri milžiniška raketa nešė Apollo įgulas link Mėnulio?",
        correct: "Saturn V",
        distractors: ["Falcon 9", "Atlas", "Titan", "Ariane", "Delta"],
        explanation: "Saturn V — viena aukščiausių ir galingiausių kada nors skridusių raketų.",
      },
    },
  },
  {
    id: "cos_roc_014",
    category: "cosmos",
    subTheme: "rockets",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Physics — orbit is continuous free fall around Earth",
    emoji: "🛰️",
    translations: {
      en: {
        question: "Why doesn't an orbiting satellite simply fall back to Earth?",
        correct: "It circles fast enough",
        distractors: ["It is very light", "Magnets hold it up", "It has no weight", "Balloons lift it", "The Sun pulls it"],
        explanation: "It moves sideways so fast that it keeps falling around the Earth.",
      },
      lt: {
        question: "Kodėl skriejantis palydovas tiesiog nenukrenta atgal į Žemę?",
        correct: "Skrieja pakankamai greitai",
        distractors: ["Jis labai lengvas", "Laiko magnetai", "Jis nieko nesveria", "Pakelia balionai", "Saulė jį traukia aukštyn"],
        explanation: "Jis taip greitai juda į šoną, kad nuolat krenta aplink Žemę.",
      },
    },
  },
  {
    id: "cos_roc_015",
    category: "cosmos",
    subTheme: "rockets",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Physics — escape velocity",
    emoji: "🚀",
    translations: {
      en: {
        question: "What do we call the speed needed to break free of Earth's gravity?",
        correct: "Escape velocity",
        distractors: ["Top speed", "Light speed", "Sound speed", "Spin speed", "Free fall"],
        explanation: "Below it you fall back; reach it and you can leave Earth.",
      },
      lt: {
        question: "Kaip vadinamas greitis, reikalingas ištrūkti iš Žemės traukos?",
        correct: "Pabėgimo greitis",
        distractors: ["Didžiausias greitis", "Šviesos greitis", "Garso greitis", "Sukimosi greitis", "Laisvas kritimas"],
        explanation: "Mažesniu greičiu nukrisi; jį pasiekęs gali palikti Žemę.",
      },
    },
  },
  {
    id: "cos_roc_016",
    category: "cosmos",
    subTheme: "rockets",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "ESA — Rosetta/Philae landed on a comet (2014)",
    emoji: "☄️",
    translations: {
      en: {
        question: "Which mission landed a small craft on a comet in 2014?",
        correct: "Rosetta",
        distractors: ["Cassini", "Juno", "Magellan", "Pioneer", "Dawn"],
        explanation: "Rosetta's Philae lander touched down on a comet's icy surface.",
      },
      lt: {
        question: "Kuri misija 2014 m. nutupdė mažą aparatą ant kometos?",
        correct: "Rosetta",
        distractors: ["Cassini", "Juno", "Magellan", "Pioneer", "Dawn"],
        explanation: "Rosetta aparatas Philae nusileido ant ledinės kometos.",
      },
    },
  },
  {
    id: "cos_roc_017",
    category: "cosmos",
    subTheme: "rockets",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Spaceflight — geostationary orbit stays over one spot",
    emoji: "🛰️",
    translations: {
      en: {
        question: "Which orbit keeps a satellite fixed above one spot on Earth?",
        correct: "Geostationary",
        distractors: ["Polar orbit", "Low orbit", "Spiral orbit", "Random orbit", "Backward orbit"],
        explanation: "It circles once a day, matching Earth's spin, so it seems still.",
      },
      lt: {
        question: "Kuri orbita laiko palydovą virš tos pačios Žemės vietos?",
        correct: "Geostacionari",
        distractors: ["Poliarinė orbita", "Žema orbita", "Spiralinė orbita", "Atsitiktinė orbita", "Atbula orbita"],
        explanation: "Ji apsuka kartą per parą, kaip ir Žemė, tad atrodo nejudanti.",
      },
    },
  },
  {
    id: "cos_roc_018",
    category: "cosmos",
    subTheme: "rockets",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Technology — GPS uses a satellite network",
    emoji: "📡",
    translations: {
      en: {
        question: "Which navigation system relies on a network of satellites?",
        correct: "GPS",
        distractors: ["Wi-Fi", "Radar", "Sonar", "A compass", "Radio"],
        explanation: "Your phone times signals from several satellites to find you.",
      },
      lt: {
        question: "Kuri navigacijos sistema remiasi palydovų tinklu?",
        correct: "GPS",
        distractors: ["Wi-Fi", "Radaras", "Sonaras", "Kompasas", "Radijas"],
        explanation: "Telefonas matuoja kelių palydovų signalus ir nustato tavo vietą.",
      },
    },
  },
  {
    id: "cos_roc_019",
    category: "cosmos",
    subTheme: "rockets",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Spaceflight — reusable rockets land and fly again",
    emoji: "🚀",
    translations: {
      en: {
        question: "What does a 'reusable' rocket do to cut costs?",
        correct: "Lands and flies again",
        distractors: ["It burns up fully", "It stays in orbit", "It sinks at sea", "It never returns", "It is thrown away"],
        explanation: "Landing the booster upright lets it be refueled and reflown.",
      },
      lt: {
        question: "Ką daro pakartotinai naudojama raketa, kad atpigtų skrydžiai?",
        correct: "Nusileidžia ir vėl pakyla",
        distractors: ["Visiškai sudega", "Lieka orbitoje", "Nuskęsta jūroje", "Niekada nebegrįžta atgal", "Yra išmetama"],
        explanation: "Vertikaliai nutupdyta pakopa vėl užpildoma kuru ir paleidžiama.",
      },
    },
  },
  {
    id: "cos_roc_020",
    category: "cosmos",
    subTheme: "rockets",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Spaceflight — CubeSats are tiny satellites",
    emoji: "🛰️",
    translations: {
      en: {
        question: "What do we call a tiny satellite about the size of a shoebox?",
        correct: "A CubeSat",
        distractors: ["A megasat", "A jumbo jet", "A space hub", "A star pod", "A moonlet"],
        explanation: "Cheap CubeSats let schools and startups reach orbit.",
      },
      lt: {
        question: "Kaip vadinamas mažytis palydovas, maždaug batų dėžės dydžio?",
        correct: "CubeSat",
        distractors: ["Megapalydovas", "Laineris", "Kosmoso mazgas", "Žvaigždės kapsulė", "Mėnuliukas"],
        explanation: "Pigūs mažieji palydovai leidžia mokykloms ir startuoliams pasiekti orbitą.",
      },
    },
  },

  // ===================== SUNKUS (suaugę) =====================
  {
    id: "cos_roc_021",
    category: "cosmos",
    subTheme: "rockets",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "NASA/ESA — Cassini studied Saturn; Huygens landed on Titan",
    emoji: "🪐",
    translations: {
      en: {
        question: "Which probe orbited Saturn and dropped a lander on its moon Titan?",
        correct: "Cassini",
        distractors: ["Juno", "Rosetta", "Magellan", "Pioneer", "Dawn"],
        explanation: "Cassini carried the Huygens lander, which reached Titan in 2005.",
      },
      lt: {
        question: "Kuris zondas skriejo aplink Saturną ir nuleido aparatą ant Titano?",
        correct: "Cassini",
        distractors: ["Juno", "Rosetta", "Magellan", "Pioneer", "Dawn"],
        explanation: "Cassini gabeno aparatą Huygens, kuris 2005 m. pasiekė Titaną.",
      },
    },
  },
  {
    id: "cos_roc_022",
    category: "cosmos",
    subTheme: "rockets",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "NASA — Juno has orbited Jupiter since 2016",
    emoji: "🪐",
    translations: {
      en: {
        question: "Which probe has been studying Jupiter from orbit since 2016?",
        correct: "Juno",
        distractors: ["Cassini", "Rosetta", "Magellan", "Pioneer", "Dawn"],
        explanation: "Juno peers below Jupiter's clouds and over its stormy poles.",
      },
      lt: {
        question: "Kuris zondas nuo 2016 m. iš orbitos tiria Jupiterį?",
        correct: "Juno",
        distractors: ["Cassini", "Rosetta", "Magellan", "Pioneer", "Dawn"],
        explanation: "Juno žvelgia po Jupiterio debesimis ir virš audringų ašigalių.",
      },
    },
  },
  {
    id: "cos_roc_023",
    category: "cosmos",
    subTheme: "rockets",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "NASA — Parker Solar Probe flew through the Sun's corona",
    emoji: "☀️",
    translations: {
      en: {
        question: "Which probe flew closest to the Sun, into its outer atmosphere?",
        correct: "Parker probe",
        distractors: ["SOHO satellite", "Helios craft", "Ulysses craft", "Genesis probe", "Pioneer probe"],
        explanation: "The Parker Solar Probe skims through the Sun's blazing corona.",
      },
      lt: {
        question: "Kuris zondas priskrido arčiausiai Saulės, į jos išorinę atmosferą?",
        correct: "Parkerio zondas",
        distractors: ["SOHO palydovas", "Helios aparatas", "Ulysses aparatas", "Genesis zondas", "Pioneer zondas"],
        explanation: "Parkerio zondas skrieja per akinamai karštą Saulės vainiką.",
      },
    },
  },
  {
    id: "cos_roc_024",
    category: "cosmos",
    subTheme: "rockets",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Physics — Earth's escape velocity ~11.2 km/s",
    emoji: "🚀",
    translations: {
      en: {
        question: "About how fast must you go to escape Earth's gravity?",
        correct: "About 11 km/s",
        distractors: ["About 1 km/s", "About 100 km/s", "About 0.3 km/s", "About 50 km/s", "About 300 km/s"],
        explanation: "That's roughly 40,000 km/h — far faster than any airplane.",
      },
      lt: {
        question: "Maždaug kokiu greičiu reikia lėkti, kad ištrūktum iš Žemės traukos?",
        correct: "Apie 11 km/s",
        distractors: ["Apie 1 km/s", "Apie 100 km/s", "Apie 0,3 km/s", "Apie 50 km/s", "Apie 300 km/s"],
        explanation: "Tai maždaug 40 000 km/h — kur kas greičiau už bet kurį lėktuvą.",
      },
    },
  },
  {
    id: "cos_roc_025",
    category: "cosmos",
    subTheme: "rockets",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Chemistry — hydrogen + oxygen burn to water vapor",
    emoji: "🚀",
    translations: {
      en: {
        question: "Which clean fuel pair burns to leave only water vapor?",
        correct: "Hydrogen and oxygen",
        distractors: ["Coal and air", "Kerosene and salt", "Wood and water", "Gas and sand", "Oil and ice"],
        explanation: "Many rockets burn liquid hydrogen with liquid oxygen.",
      },
      lt: {
        question: "Kuri švari kuro pora sudegusi palieka tik vandens garą?",
        correct: "Vandenilis ir deguonis",
        distractors: ["Anglis ir oras", "Žibalas ir druska", "Mediena ir vanduo", "Dujos ir smėlis", "Nafta ir ledas"],
        explanation: "Daug raketų degina skystą vandenilį su skystu deguonimi.",
      },
    },
  },
  {
    id: "cos_roc_026",
    category: "cosmos",
    subTheme: "rockets",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "History — Robert Goddard built the first liquid-fuel rocket (1926)",
    emoji: "🚀",
    translations: {
      en: {
        question: "Who built and flew the first liquid-fuel rocket, in 1926?",
        correct: "Robert Goddard",
        distractors: ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Charles Darwin", "Carl Sagan"],
        explanation: "Goddard's small rocket rose just 12 meters, but proved the idea.",
      },
      lt: {
        question: "Kas 1926 m. pastatė ir paleido pirmąją skysto kuro raketą?",
        correct: "Robertas Godardas",
        distractors: ["Izaokas Niutonas", "Albertas Einšteinas", "Galilėjus Galilėjus", "Čarlzas Darvinas", "Karlas Saganas"],
        explanation: "Godardo raketėlė pakilo vos 12 metrų, bet įrodė idėją.",
      },
    },
  },
  {
    id: "cos_roc_027",
    category: "cosmos",
    subTheme: "rockets",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Spaceflight — gravity assist (slingshot) maneuver",
    emoji: "🪐",
    translations: {
      en: {
        question: "What do we call using a planet's gravity to speed up a probe for free?",
        correct: "A gravity assist",
        distractors: ["A heat boost", "A fuel dump", "A solar sail", "A spin kick", "A drag brake"],
        explanation: "Swinging past a planet flings the probe onward, saving fuel.",
      },
      lt: {
        question: "Kaip vadinamas planetos traukos panaudojimas zondui pagreitinti be kuro?",
        correct: "Gravitacinis manevras",
        distractors: ["Šilumos postūmis", "Kuro išmetimas", "Saulės burė", "Sukimo smūgis", "Stabdymo skydas"],
        explanation: "Praskriedamas pro planetą zondas yra nusviedžiamas tolyn ir sutaupo kuro.",
      },
    },
  },
  {
    id: "cos_roc_028",
    category: "cosmos",
    subTheme: "rockets",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "NASA — Curiosity rover landed on Mars in 2012",
    emoji: "🤖",
    translations: {
      en: {
        question: "Which rover, landed in 2012, explores Mars's Gale Crater?",
        correct: "Curiosity",
        distractors: ["Spirit", "Opportunity", "Sojourner", "Viking", "Zhurong"],
        explanation: "Curiosity is a car-sized nuclear-powered science lab on wheels.",
      },
      lt: {
        question: "Kuris marsaeigis, nusileidęs 2012 m., tyrinėja Marso Gale kraterį?",
        correct: "Curiosity",
        distractors: ["Spirit", "Opportunity", "Sojourner", "Viking", "Zhurong"],
        explanation: "Curiosity — automobilio dydžio branduoline energija varoma laboratorija.",
      },
    },
  },
  {
    id: "cos_roc_029",
    category: "cosmos",
    subTheme: "rockets",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Spaceflight — ion engines use charged particles",
    emoji: "🛰️",
    translations: {
      en: {
        question: "Which weak but very efficient engine pushes probes with charged gas?",
        correct: "An ion engine",
        distractors: ["A jet engine", "A steam engine", "A diesel engine", "A wind engine", "A coal engine"],
        explanation: "Ion engines barely push, but can run for years to reach high speed.",
      },
      lt: {
        question: "Koks silpnas, bet labai taupus variklis stumia zondus įelektrintomis dujomis?",
        correct: "Joninis variklis",
        distractors: ["Reaktyvinis variklis", "Garo variklis", "Dyzelinis variklis", "Vėjo variklis", "Anglies variklis"],
        explanation: "Joniniai varikliai stumia silpnai, bet veikia metų metus.",
      },
    },
  },
  {
    id: "cos_roc_030",
    category: "cosmos",
    subTheme: "rockets",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "JAXA — Hayabusa returned the first asteroid sample",
    emoji: "☄️",
    translations: {
      en: {
        question: "Which Japanese probe first brought back a sample from an asteroid?",
        correct: "Hayabusa",
        distractors: ["Cassini", "Juno", "Rosetta", "Magellan", "Pioneer"],
        explanation: "Hayabusa returned tiny grains from asteroid Itokawa in 2010.",
      },
      lt: {
        question: "Kuris japonų zondas pirmas parvežė mėginį iš asteroido?",
        correct: "Hayabusa",
        distractors: ["Cassini", "Juno", "Rosetta", "Magellan", "Pioneer"],
        explanation: "Hayabusa 2010 m. parvežė smulkias dulkes nuo asteroido Itokavos.",
      },
    },
  },

  // ===================== EKSTREMALUS (žinovai) =====================
  {
    id: "cos_roc_031",
    category: "cosmos",
    subTheme: "rockets",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "History — Tsiolkovsky derived the rocket equation",
    emoji: "🚀",
    translations: {
      en: {
        question: "Whose equation links a rocket's fuel to the speed it can gain?",
        correct: "Tsiolkovsky's",
        distractors: ["Newton's", "Einstein's", "Kepler's", "Hawking's", "Darwin's"],
        explanation: "Konstantin Tsiolkovsky wrote the rocket equation back in 1903.",
      },
      lt: {
        question: "Kieno lygtis sieja raketos kurą su greičiu, kurį ji gali įgyti?",
        correct: "Ciolkovskio",
        distractors: ["Niutono", "Einšteino", "Keplerio", "Hokingo", "Darvino"],
        explanation: "Konstantinas Ciolkovskis raketos lygtį užrašė dar 1903 m.",
      },
    },
  },
  {
    id: "cos_roc_032",
    category: "cosmos",
    subTheme: "rockets",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "NASA — MESSENGER orbited Mercury (2011–2015)",
    emoji: "☿️",
    translations: {
      en: {
        question: "Which probe was the first to orbit and map Mercury?",
        correct: "MESSENGER",
        distractors: ["Magellan", "Cassini", "Juno", "Galileo", "Pioneer"],
        explanation: "MESSENGER mapped the whole scorched planet before crashing into it.",
      },
      lt: {
        question: "Kuris zondas pirmas pradėjo skrieti aplink Merkurijų ir jį kartografavo?",
        correct: "MESSENGER",
        distractors: ["Magellan", "Cassini", "Juno", "Galileo", "Pioneer"],
        explanation: "MESSENGER sudarė visos išdegusios planetos žemėlapį, paskui į ją nukrito.",
      },
    },
  },
  {
    id: "cos_roc_033",
    category: "cosmos",
    subTheme: "rockets",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "NASA — Magellan radar-mapped Venus in the 1990s",
    emoji: "🟡",
    translations: {
      en: {
        question: "Which probe mapped cloud-hidden Venus using radar in the 1990s?",
        correct: "Magellan",
        distractors: ["MESSENGER", "Cassini", "Juno", "Galileo", "Viking"],
        explanation: "Radar pierced Venus's thick clouds to reveal its surface.",
      },
      lt: {
        question: "Kuris zondas 10-ajame dešimtmetyje radaru kartografavo debesų slepiamą Venerą?",
        correct: "Magellan",
        distractors: ["MESSENGER", "Cassini", "Juno", "Galileo", "Viking"],
        explanation: "Radaras pramušė tankius Veneros debesis ir atskleidė paviršių.",
      },
    },
  },
  {
    id: "cos_roc_034",
    category: "cosmos",
    subTheme: "rockets",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "NASA — OSIRIS-REx sampled asteroid Bennu (2020)",
    emoji: "☄️",
    translations: {
      en: {
        question: "Which probe grabbed a sample from asteroid Bennu in 2020?",
        correct: "OSIRIS-REx",
        distractors: ["Hayabusa", "Cassini", "Juno", "Dawn", "Galileo"],
        explanation: "It tapped Bennu for a few seconds and flew the dust back to Earth.",
      },
      lt: {
        question: "Kuris zondas 2020 m. paėmė mėginį iš asteroido Benu?",
        correct: "OSIRIS-REx",
        distractors: ["Hayabusa", "Cassini", "Juno", "Dawn", "Galileo"],
        explanation: "Jis kelias sekundes palietė Benu ir parskraidino dulkes į Žemę.",
      },
    },
  },
  {
    id: "cos_roc_035",
    category: "cosmos",
    subTheme: "rockets",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "NASA — Dawn orbited both Vesta and Ceres",
    emoji: "🪨",
    translations: {
      en: {
        question: "Which probe orbited both the asteroid Vesta and dwarf planet Ceres?",
        correct: "Dawn",
        distractors: ["Juno", "Cassini", "Rosetta", "Pioneer", "Magellan"],
        explanation: "Dawn used efficient ion engines to visit two belt worlds.",
      },
      lt: {
        question: "Kuris zondas skriejo aplink asteroidą Vestą ir nykštukinę planetą Cererą?",
        correct: "Dawn",
        distractors: ["Juno", "Cassini", "Rosetta", "Pioneer", "Magellan"],
        explanation: "Dawn taupiais joniniais varikliais aplankė du žiedo pasaulius.",
      },
    },
  },
  {
    id: "cos_roc_036",
    category: "cosmos",
    subTheme: "rockets",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "ESA — JUICE launched in 2023 toward Jupiter's icy moons",
    emoji: "🧊",
    translations: {
      en: {
        question: "Which 2023 mission set off to study Jupiter's icy moons?",
        correct: "JUICE",
        distractors: ["Juno", "Cassini", "Galileo", "Rosetta", "Pioneer"],
        explanation: "JUICE will study Ganymede, Callisto and Europa in the 2030s.",
      },
      lt: {
        question: "Kuri 2023 m. misija leidosi tirti ledinių Jupiterio mėnulių?",
        correct: "JUICE",
        distractors: ["Juno", "Cassini", "Galileo", "Rosetta", "Pioneer"],
        explanation: "JUICE 2030-aisiais tirs Ganimedą, Kalisto ir Europą.",
      },
    },
  },
  {
    id: "cos_roc_037",
    category: "cosmos",
    subTheme: "rockets",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Technology — ~31 operational GPS satellites",
    emoji: "📡",
    translations: {
      en: {
        question: "About how many satellites make up the working GPS network?",
        correct: "About 30",
        distractors: ["About 3", "About 300", "About 3,000", "Just 1", "About 100"],
        explanation: "Around 24 are needed; a few extras keep coverage solid worldwide.",
      },
      lt: {
        question: "Maždaug kiek palydovų sudaro veikiantį GPS tinklą?",
        correct: "Apie 30",
        distractors: ["Apie 3", "Apie 300", "Apie 3 000", "Vos 1", "Apie 100"],
        explanation: "Jų reikia apie 24, o keli atsarginiai užtikrina aprėptį visame pasaulyje.",
      },
    },
  },
  {
    id: "cos_roc_038",
    category: "cosmos",
    subTheme: "rockets",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Spaceflight — polar orbits pass over the poles for mapping",
    emoji: "🛰️",
    translations: {
      en: {
        question: "Which orbit crosses over Earth's poles, ideal for full mapping?",
        correct: "A polar orbit",
        distractors: ["A lunar orbit", "A solar orbit", "A still orbit", "A figure-eight", "A square orbit"],
        explanation: "As Earth spins below, a polar satellite scans every strip in turn.",
      },
      lt: {
        question: "Kuri orbita kerta Žemės ašigalius ir tinka visam kartografavimui?",
        correct: "Poliarinė orbita",
        distractors: ["Mėnulio orbita", "Saulės orbita", "Stovinti orbita", "Aštuoniukės forma", "Kvadratinė orbita"],
        explanation: "Žemei sukantis apačioje, poliarinis palydovas nuskaito juostą po juostos.",
      },
    },
  },
  {
    id: "cos_roc_039",
    category: "cosmos",
    subTheme: "rockets",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "NASA — Sojourner was the first Mars rover (1997)",
    emoji: "🤖",
    translations: {
      en: {
        question: "Which tiny rover was the first to drive on Mars, back in 1997?",
        correct: "Sojourner",
        distractors: ["Curiosity", "Perseverance", "Spirit", "Opportunity", "Viking"],
        explanation: "Microwave-oven sized Sojourner proved rovers could work on Mars.",
      },
      lt: {
        question: "Kuris mažytis marsaeigis pirmas važiavo Marse dar 1997 m.?",
        correct: "Sojourner",
        distractors: ["Curiosity", "Perseverance", "Spirit", "Opportunity", "Viking"],
        explanation: "Mikrobangų krosnelės dydžio Sojourner įrodė, kad marsaeigiai veikia.",
      },
    },
  },
  {
    id: "cos_roc_040",
    category: "cosmos",
    subTheme: "rockets",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Spaceflight — solar sails push using sunlight pressure",
    emoji: "📡",
    translations: {
      en: {
        question: "What fuel-free method pushes a craft using sunlight on a big sail?",
        correct: "A solar sail",
        distractors: ["An ion drive", "A jet boost", "A gravity assist", "A booster", "A parachute"],
        explanation: "Tiny pushes from sunlight add up to steady, fuel-free thrust.",
      },
      lt: {
        question: "Koks kuro nenaudojantis būdas stumia aparatą Saulės šviesai spaudžiant didelę burę?",
        correct: "Saulės burė",
        distractors: ["Joninis variklis", "Reaktyvinis postūmis", "Gravitacinis manevras", "Pakopa", "Parašiutas"],
        explanation: "Maži šviesos postūmiai susideda į tolygią, kuro nenaudojančią trauką.",
      },
    },
  },
];
