/**
 * cosmosAstronauts — 🧑‍🚀 „Astronautai ir misijos" potemė (tema „Kosmosas").
 *
 * MAŽAS FAILAS pagal potemę. 40 klausimų (10/lygiui). Tema — ŽMONĖS kosmose:
 * gyvenimas TKS, kūnas nesvarume, garsūs pirmieji, gyvūnai kosmose, EVA.
 * NEKARTOJA „spacerace" (Gagarinas, Armstrongas, Apollo 11, Sputnik, Salyut)
 * nei „planets" faktų. Faktai nusistovėję (NASA/Roscosmos istorija).
 *
 * TAISYKLĖS: 1 teisingas + 5 distraktoriai; ≤46 simb. abiem kalbom; teisingas
 * NE ilgiausias >+5; LT kabutės „..."; jokio atsakymo klausime.
 */

import { TriviaQuestion } from "./triviaTypes";

export const COSMOS_ASTRONAUTS: TriviaQuestion[] = [
  // ===================== LENGVAS (9–12 m. vaikas) =====================
  {
    id: "cos_ast_001",
    category: "cosmos",
    subTheme: "astronauts",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "NASA — spacesuit (EVA suit)",
    emoji: "🧑‍🚀",
    translations: {
      en: {
        question: "What does an astronaut wear to go outside in space?",
        correct: "A spacesuit",
        distractors: ["A raincoat", "A wetsuit", "A snowsuit", "A life jacket", "A uniform"],
        explanation: "A spacesuit gives air, pressure and warmth in the vacuum.",
      },
      lt: {
        question: "Ką astronautas vilki, norėdamas išeiti į atvirą kosmosą?",
        correct: "Skafandrą",
        distractors: ["Lietpaltį", "Hidrokostiumą", "Žieminį kombinezoną", "Gelbėjimosi liemenę", "Uniformą"],
        explanation: "Skafandras duoda orą, slėgį ir šilumą vakuume.",
      },
    },
  },
  {
    id: "cos_ast_002",
    category: "cosmos",
    subTheme: "astronauts",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "NASA — astronauts live on the ISS",
    emoji: "🛰️",
    translations: {
      en: {
        question: "Where do astronauts live and work while orbiting Earth?",
        correct: "On a space station",
        distractors: ["On the Moon", "On Mars", "In an airplane", "In a submarine", "On a cloud"],
        explanation: "The International Space Station orbits about 400 km up.",
      },
      lt: {
        question: "Kur astronautai gyvena ir dirba, skriedami aplink Žemę?",
        correct: "Kosminėje stotyje",
        distractors: ["Mėnulyje", "Marse", "Lėktuve", "Povandeniniame laive", "Ant debesies"],
        explanation: "Tarptautinė kosminė stotis skrieja maždaug 400 km aukštyje.",
      },
    },
  },
  {
    id: "cos_ast_003",
    category: "cosmos",
    subTheme: "astronauts",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Physics — weightlessness (free fall) in orbit",
    emoji: "🎈",
    translations: {
      en: {
        question: "Why do astronauts float inside their spacecraft?",
        correct: "They are weightless",
        distractors: ["There is no air", "The ship is upside down", "They wear balloons", "Magnets lift them", "They are tiny"],
        explanation: "In orbit everything falls together, so astronauts feel weightless.",
      },
      lt: {
        question: "Kodėl astronautai sklando savo erdvėlaivio viduje?",
        correct: "Jie yra nesvarūs",
        distractors: ["Nėra oro", "Laivas apverstas", "Vilki balionus", "Pakelia magnetai", "Jie maži"],
        explanation: "Orbitoje viskas krenta kartu, tad astronautai jaučiasi nesvarūs.",
      },
    },
  },
  {
    id: "cos_ast_004",
    category: "cosmos",
    subTheme: "astronauts",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Spaceflight history — Laika, first animal to orbit (1957)",
    emoji: "🐕",
    translations: {
      en: {
        question: "Which animal was the first to orbit the Earth, in 1957?",
        correct: "A dog",
        distractors: ["A cat", "A monkey", "A mouse", "A bird", "A rabbit"],
        explanation: "A dog named Laika was the first animal to orbit our planet.",
      },
      lt: {
        question: "Koks gyvūnas pirmas apskriejo Žemę 1957 metais?",
        correct: "Šuo",
        distractors: ["Katė", "Beždžionė", "Pelė", "Paukštis", "Triušis"],
        explanation: "Šuo, vardu Laika, pirmas apskriejo mūsų planetą.",
      },
    },
  },
  {
    id: "cos_ast_005",
    category: "cosmos",
    subTheme: "astronauts",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "NASA — spacewalk (EVA)",
    emoji: "🚶",
    translations: {
      en: {
        question: "What do we call it when an astronaut goes outside the ship?",
        correct: "A spacewalk",
        distractors: ["A moonwalk", "A flyby", "A liftoff", "A landing", "A countdown"],
        explanation: "On a spacewalk, astronauts stay attached by a safety line.",
      },
      lt: {
        question: "Kaip vadinamas astronauto išėjimas už laivo į kosmosą?",
        correct: "Išėjimas į kosmosą",
        distractors: ["Mėnulio šokis", "Praskridimas", "Pakilimas", "Nusileidimas", "Atskaita"],
        explanation: "Išeidamas astronautas lieka pritvirtintas saugos lynu.",
      },
    },
  },
  {
    id: "cos_ast_006",
    category: "cosmos",
    subTheme: "astronauts",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Physics — space is a vacuum, sound cannot travel",
    emoji: "🔇",
    translations: {
      en: {
        question: "Can astronauts hear sounds out in open space?",
        correct: "No, space is silent",
        distractors: ["Yes, very loudly", "Only music", "Yes, like on Earth", "Only at night", "Yes, with echoes"],
        explanation: "Sound needs air to travel; open space is an empty vacuum.",
      },
      lt: {
        question: "Ar astronautai girdi garsus atvirame kosmose?",
        correct: "Ne, kosmose tylu",
        distractors: ["Taip, labai garsiai", "Tik muziką", "Taip, kaip Žemėje", "Tik naktį", "Taip, su aidu"],
        explanation: "Garsui sklisti reikia oro, o kosmosas yra tuščias vakuumas.",
      },
    },
  },
  {
    id: "cos_ast_007",
    category: "cosmos",
    subTheme: "astronauts",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "NASA — spacesuit helmet",
    emoji: "🪖",
    translations: {
      en: {
        question: "What protects an astronaut's head inside the suit?",
        correct: "A helmet",
        distractors: ["A hat", "A scarf", "A pillow", "A mask", "A hood"],
        explanation: "The helmet holds air and shields the eyes from bright sunlight.",
      },
      lt: {
        question: "Kas apsaugo astronauto galvą skafandre?",
        correct: "Šalmas",
        distractors: ["Kepurė", "Šalikas", "Pagalvė", "Kaukė", "Gobtuvas"],
        explanation: "Šalmas laiko orą ir saugo akis nuo ryškios Saulės.",
      },
    },
  },
  {
    id: "cos_ast_008",
    category: "cosmos",
    subTheme: "astronauts",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Spaceflight terminology — cosmonaut (Russia)",
    emoji: "🧑‍🚀",
    translations: {
      en: {
        question: "Russian space travelers are not called astronauts, but...?",
        correct: "Cosmonauts",
        distractors: ["Taikonauts", "Pilots", "Sailors", "Captains", "Spacemen"],
        explanation: "Russia uses 'cosmonaut'; China uses 'taikonaut'.",
      },
      lt: {
        question: "Rusijos kosmoso keliautojai vadinami ne astronautais, o...?",
        correct: "Kosmonautais",
        distractors: ["Taikonautais", "Pilotais", "Jūreiviais", "Kapitonais", "Erdvininkais"],
        explanation: "Rusijoje sakoma kosmonautas, Kinijoje — taikonautas.",
      },
    },
  },
  {
    id: "cos_ast_009",
    category: "cosmos",
    subTheme: "astronauts",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "NASA — freeze-dried space food",
    emoji: "🍱",
    translations: {
      en: {
        question: "How is much astronaut food kept for long missions?",
        correct: "Freeze-dried",
        distractors: ["Fresh and cold", "As hot soup", "In glass jars", "On open plates", "As ice cubes"],
        explanation: "Water is removed to save weight; astronauts add it back later.",
      },
      lt: {
        question: "Kaip dažnai laikomas astronautų maistas ilgoms misijoms?",
        correct: "Sausai džiovintas",
        distractors: ["Šviežias ir šaltas", "Karšta sriuba", "Stiklainiuose", "Ant atvirų lėkščių", "Ledukais"],
        explanation: "Vanduo pašalinamas, kad būtų lengviau; vėliau jis vėl pridedamas.",
      },
    },
  },
  {
    id: "cos_ast_010",
    category: "cosmos",
    subTheme: "astronauts",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Basic science — astronauts breathe oxygen",
    emoji: "💨",
    translations: {
      en: {
        question: "What must astronauts carry with them to breathe in space?",
        correct: "Oxygen",
        distractors: ["Helium", "Smoke", "Steam", "Dust", "Nitrogen only"],
        explanation: "There is no air in space, so oxygen is brought along.",
      },
      lt: {
        question: "Ką astronautai privalo turėti, kad galėtų kvėpuoti kosmose?",
        correct: "Deguonį",
        distractors: ["Helį", "Dūmus", "Garą", "Dulkes", "Vien azotą"],
        explanation: "Kosmose oro nėra, todėl deguonis pasiimamas su savimi.",
      },
    },
  },

  // ===================== VIDUTINIS (12–18 m.) =====================
  {
    id: "cos_ast_011",
    category: "cosmos",
    subTheme: "astronauts",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Spaceflight history — Valentina Tereshkova (1963)",
    emoji: "👩‍🚀",
    translations: {
      en: {
        question: "Who was the first woman to fly in space?",
        correct: "Valentina Tereshkova",
        distractors: ["Sally Ride", "Mae Jemison", "Helen Sharman", "Svetlana Savitskaya", "Kathryn Sullivan"],
        explanation: "She orbited Earth 48 times in 1963.",
      },
      lt: {
        question: "Kuri moteris pirmoji skrido į kosmosą?",
        correct: "Valentina Tereškova",
        distractors: ["Sally Ride", "Mae Jemison", "Helen Sharman", "Svetlana Savickaja", "Kathryn Sullivan"],
        explanation: "1963 m. ji apskriejo Žemę 48 kartus.",
      },
    },
  },
  {
    id: "cos_ast_012",
    category: "cosmos",
    subTheme: "astronauts",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "NASA — ISS continuously crewed since 2000 (launched 1998)",
    emoji: "🛰️",
    translations: {
      en: {
        question: "What is the name of the lab orbiting Earth since 1998?",
        correct: "The ISS",
        distractors: ["Mir", "Skylab", "Tiangong", "Salyut", "Hubble"],
        explanation: "The International Space Station is the size of a football field.",
      },
      lt: {
        question: "Kaip vadinama laboratorija, skriejanti aplink Žemę nuo 1998 m.?",
        correct: "TKS",
        distractors: ["Mir", "Skylab", "Tiangong", "Salyut", "Hubble"],
        explanation: "Tarptautinė kosminė stotis (TKS) — futbolo aikštės dydžio.",
      },
    },
  },
  {
    id: "cos_ast_013",
    category: "cosmos",
    subTheme: "astronauts",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Spaceflight history — Alexei Leonov, first spacewalk (1965)",
    emoji: "🚶",
    translations: {
      en: {
        question: "Who made the first-ever spacewalk, in 1965?",
        correct: "Alexei Leonov",
        distractors: ["Neil Armstrong", "Buzz Aldrin", "John Glenn", "Ed White", "Alan Shepard"],
        explanation: "Leonov floated outside his capsule for about 12 minutes.",
      },
      lt: {
        question: "Kas pirmas pasaulyje išėjo į atvirą kosmosą 1965 m.?",
        correct: "Aleksejus Leonovas",
        distractors: ["Nilas Armstrongas", "Buzas Oldrinas", "Džonas Glenas", "Edas Vaitas", "Alanas Šepardas"],
        explanation: "Leonovas sklandė už savo kapsulės apie 12 minučių.",
      },
    },
  },
  {
    id: "cos_ast_014",
    category: "cosmos",
    subTheme: "astronauts",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "NASA — ISS orbital period ~90 minutes",
    emoji: "⏱️",
    translations: {
      en: {
        question: "How long does the Space Station take to circle Earth once?",
        correct: "About 90 minutes",
        distractors: ["About 24 hours", "About 7 days", "Exactly 1 hour", "About 12 hours", "About 30 days"],
        explanation: "Crews see about 16 sunrises and sunsets every day.",
      },
      lt: {
        question: "Per kiek laiko kosminė stotis vieną kartą apskrieja Žemę?",
        correct: "Apie 90 minučių",
        distractors: ["Apie 24 valandas", "Apie 7 dienas", "Lygiai 1 valandą", "Apie 12 valandų", "Apie 30 dienų"],
        explanation: "Įgula kasdien mato apie 16 saulėtekių ir saulėlydžių.",
      },
    },
  },
  {
    id: "cos_ast_015",
    category: "cosmos",
    subTheme: "astronauts",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Space medicine — muscle atrophy in microgravity",
    emoji: "💪",
    translations: {
      en: {
        question: "Why do astronauts' muscles get weaker on long missions?",
        correct: "Too little gravity",
        distractors: ["Too much exercise", "Lack of sleep", "Cold temperatures", "Too much food", "Loud noise"],
        explanation: "Without gravity to push against, muscles waste away.",
      },
      lt: {
        question: "Kodėl per ilgas misijas astronautų raumenys nusilpsta?",
        correct: "Per maža gravitacija",
        distractors: ["Per daug mankštos", "Miego trūkumas", "Šaltis", "Per daug maisto", "Garsus triukšmas"],
        explanation: "Be gravitacijos, su kuria reikia kovoti, raumenys nyksta.",
      },
    },
  },
  {
    id: "cos_ast_016",
    category: "cosmos",
    subTheme: "astronauts",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "NASA — Apollo 13 survived an in-flight explosion (1970)",
    emoji: "🚀",
    translations: {
      en: {
        question: "Apollo 13 became famous for what?",
        correct: "Surviving an accident",
        distractors: ["Landing on Mars", "The first spacewalk", "Reaching the Sun", "Building a station", "Finding water"],
        explanation: "An oxygen tank burst, yet the crew returned home safely.",
      },
      lt: {
        question: "Kuo išgarsėjo Apollo 13 misija?",
        correct: "Išgyveno avariją",
        distractors: ["Nusileido Marse", "Pirmas išėjimas", "Pasiekė Saulę", "Pastatė stotį", "Rado vandens"],
        explanation: "Sprogo deguonies bakas, bet įgula saugiai grįžo namo.",
      },
    },
  },
  {
    id: "cos_ast_017",
    category: "cosmos",
    subTheme: "astronauts",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Spaceflight history — Ham the chimpanzee (1961)",
    emoji: "🐵",
    translations: {
      en: {
        question: "Before astronauts, which animal did the US launch in 1961?",
        correct: "A chimpanzee",
        distractors: ["A dog", "A horse", "A parrot", "A goat", "A turtle"],
        explanation: "Ham the chimp tested the capsule before humans flew.",
      },
      lt: {
        question: "Prieš astronautus, kokį gyvūną JAV paleido 1961 m.?",
        correct: "Šimpanzę",
        distractors: ["Šunį", "Arklį", "Papūgą", "Ožką", "Vėžlį"],
        explanation: "Šimpanzė Hamas išbandė kapsulę dar prieš žmones.",
      },
    },
  },
  {
    id: "cos_ast_018",
    category: "cosmos",
    subTheme: "astronauts",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "NASA — astronauts sleep in strapped sleeping bags",
    emoji: "😴",
    translations: {
      en: {
        question: "How do astronauts sleep on the Space Station?",
        correct: "Strapped in a bag",
        distractors: ["In soft beds", "Standing up only", "On the floor", "In a hammock", "Sitting in chairs"],
        explanation: "Sleeping bags are tied to a wall so they don't float away.",
      },
      lt: {
        question: "Kaip astronautai miega kosminėje stotyje?",
        correct: "Pririšti maiše",
        distractors: ["Minkštose lovose", "Tik stovėdami", "Ant grindų", "Hamake", "Sėdėdami kėdėse"],
        explanation: "Miegmaišiai pririšami prie sienos, kad nenuplauktų.",
      },
    },
  },
  {
    id: "cos_ast_019",
    category: "cosmos",
    subTheme: "astronauts",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Physics — microgravity is near-weightlessness",
    emoji: "🌀",
    translations: {
      en: {
        question: "What is the 'microgravity' astronauts feel in orbit?",
        correct: "Near-weightlessness",
        distractors: ["Double gravity", "Strong magnetism", "Extreme cold", "Fast spinning", "Bright light"],
        explanation: "Gravity is still there, but free fall makes them feel weightless.",
      },
      lt: {
        question: "Kas yra mikrogravitacija, kurią astronautai jaučia orbitoje?",
        correct: "Beveik nesvarumas",
        distractors: ["Dviguba gravitacija", "Stiprus magnetizmas", "Didelis šaltis", "Greitas sukimasis", "Ryški šviesa"],
        explanation: "Gravitacija yra, bet laisvas kritimas sukuria nesvarumo jausmą.",
      },
    },
  },
  {
    id: "cos_ast_020",
    category: "cosmos",
    subTheme: "astronauts",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "NASA — safety tethers during EVA",
    emoji: "🪢",
    translations: {
      en: {
        question: "What keeps an astronaut from drifting away on a spacewalk?",
        correct: "Safety tethers",
        distractors: ["Glue", "Magnets", "Ropes of hair", "Heavy boots", "Sticky tape"],
        explanation: "Tethers clip the astronaut to the station like a leash.",
      },
      lt: {
        question: "Kas neleidžia astronautui nuplaukti per išėjimą į kosmosą?",
        correct: "Saugos lynai",
        distractors: ["Klijai", "Magnetai", "Plaukų virvės", "Sunkūs batai", "Lipni juosta"],
        explanation: "Lynai prisega astronautą prie stoties tarsi pavadėlis.",
      },
    },
  },

  // ===================== SUNKUS (suaugę) =====================
  {
    id: "cos_ast_021",
    category: "cosmos",
    subTheme: "astronauts",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "NASA — John Glenn, first American to orbit (1962)",
    emoji: "👨‍🚀",
    translations: {
      en: {
        question: "Who was the first American to orbit the Earth, in 1962?",
        correct: "John Glenn",
        distractors: ["Alan Shepard", "Neil Armstrong", "Buzz Aldrin", "Chuck Yeager", "Gus Grissom"],
        explanation: "Alan Shepard flew first, but only a short hop — Glenn orbited.",
      },
      lt: {
        question: "Kuris amerikietis pirmas apskriejo Žemę 1962 m.?",
        correct: "Džonas Glenas",
        distractors: ["Alanas Šepardas", "Nilas Armstrongas", "Buzas Oldrinas", "Čakas Jėgeris", "Gasas Grisomas"],
        explanation: "Šepardas skrido pirmas, bet tik trumpai — Glenas apskriejo.",
      },
    },
  },
  {
    id: "cos_ast_022",
    category: "cosmos",
    subTheme: "astronauts",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Space medicine — spine lengthens in microgravity",
    emoji: "📏",
    translations: {
      en: {
        question: "Astronauts grow a few cm taller in space because their...?",
        correct: "Spine stretches out",
        distractors: ["Bones thicken", "Muscles swell", "Feet flatten", "Hair grows fast", "Skin loosens"],
        explanation: "Without gravity squeezing it, the spine relaxes and lengthens.",
      },
      lt: {
        question: "Kosmose astronautai paūgteli keliais cm, nes jų...?",
        correct: "Stuburas išsitempia",
        distractors: ["Kaulai sustorėja", "Raumenys išsipučia", "Pėdos suplokštėja", "Greit auga plaukai", "Atsipalaiduoja oda"],
        explanation: "Be gravitacijos spaudimo stuburas atsipalaiduoja ir pailgėja.",
      },
    },
  },
  {
    id: "cos_ast_023",
    category: "cosmos",
    subTheme: "astronauts",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "NASA — ISS recycles water from sweat and urine",
    emoji: "💧",
    translations: {
      en: {
        question: "On the ISS, the drinking water is mostly...?",
        correct: "Recycled water",
        distractors: ["Shipped up daily", "Made from air", "Melted comet ice", "Bottled on Earth", "Found in space"],
        explanation: "Sweat and even urine are cleaned back into safe drinking water.",
      },
      lt: {
        question: "TKS geriamasis vanduo daugiausia yra...?",
        correct: "Perdirbtas vanduo",
        distractors: ["Atgabenamas kasdien", "Pagamintas iš oro", "Ištirpdytas ledas", "Išpilstytas Žemėje", "Rastas kosmose"],
        explanation: "Prakaitas ir net šlapimas išvalomi atgal į saugų geriamąjį vandenį.",
      },
    },
  },
  {
    id: "cos_ast_024",
    category: "cosmos",
    subTheme: "astronauts",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "NASA — Bruce McCandless, first untethered spacewalk (1984)",
    emoji: "🧑‍🚀",
    translations: {
      en: {
        question: "Who took the first untethered spacewalk in 1984?",
        correct: "Bruce McCandless",
        distractors: ["Neil Armstrong", "Alexei Leonov", "John Glenn", "Buzz Aldrin", "Ed White"],
        explanation: "He flew free using a jet backpack, with no safety line.",
      },
      lt: {
        question: "Kas 1984 m. pirmas išėjo į kosmosą be saugos lyno?",
        correct: "Briusas Makendlesas",
        distractors: ["Nilas Armstrongas", "Aleksejus Leonovas", "Džonas Glenas", "Buzas Oldrinas", "Edas Vaitas"],
        explanation: "Jis skrido laisvai su reaktyvine kuprine, be saugos lyno.",
      },
    },
  },
  {
    id: "cos_ast_025",
    category: "cosmos",
    subTheme: "astronauts",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Spaceflight record — Valeri Polyakov, ~437 days (1994–95)",
    emoji: "📅",
    translations: {
      en: {
        question: "About how long is the longest single stay in space?",
        correct: "About 437 days",
        distractors: ["About 30 days", "About 90 days", "About 1,000 days", "About 50 days", "About 10 days"],
        explanation: "Valeri Polyakov spent about 14 months aboard the Mir station.",
      },
      lt: {
        question: "Maždaug kiek truko ilgiausias vienas skrydis kosmose?",
        correct: "Apie 437 dienas",
        distractors: ["Apie 30 dienų", "Apie 90 dienų", "Apie 1 000 dienų", "Apie 50 dienų", "Apie 10 dienų"],
        explanation: "Valerijus Poliakovas stotyje Mir praleido apie 14 mėnesių.",
      },
    },
  },
  {
    id: "cos_ast_026",
    category: "cosmos",
    subTheme: "astronauts",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "NASA — ISS run by five space agencies",
    emoji: "🛰️",
    translations: {
      en: {
        question: "How many space agencies jointly run the ISS?",
        correct: "Five",
        distractors: ["Two", "Three", "Ten", "One", "Twenty"],
        explanation: "NASA, Roscosmos, ESA, JAXA and Canada's CSA share the station.",
      },
      lt: {
        question: "Kiek kosmoso agentūrų kartu valdo TKS?",
        correct: "Penkios",
        distractors: ["Dvi", "Trys", "Dešimt", "Viena", "Dvidešimt"],
        explanation: "Stotį dalijasi NASA, Roscosmos, ESA, JAXA ir Kanados CSA.",
      },
    },
  },
  {
    id: "cos_ast_027",
    category: "cosmos",
    subTheme: "astronauts",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Space medicine — daily exercise prevents bone loss",
    emoji: "🏋️",
    translations: {
      en: {
        question: "Why do ISS astronauts exercise about 2 hours every day?",
        correct: "To slow bone loss",
        distractors: ["To stay warm", "To pass the time", "To save oxygen", "To sleep better", "To grow taller"],
        explanation: "Bones thin quickly without gravity, so exercise fights it.",
      },
      lt: {
        question: "Kodėl TKS astronautai kasdien mankštinasi apie 2 valandas?",
        correct: "Kad neretėtų kaulai",
        distractors: ["Kad nesušaltų", "Kad prabėgtų laikas", "Kad taupytų orą", "Kad geriau miegotų", "Kad paaugtų"],
        explanation: "Be gravitacijos kaulai greitai retėja, tad mankšta tam priešinasi.",
      },
    },
  },
  {
    id: "cos_ast_028",
    category: "cosmos",
    subTheme: "astronauts",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Psychology — the 'Overview Effect' (Frank White)",
    emoji: "🌍",
    translations: {
      en: {
        question: "What is the 'Overview Effect' many astronauts describe?",
        correct: "Awe at seeing Earth",
        distractors: ["Fear of the dark", "Loss of balance", "Sudden hunger", "Better eyesight", "Time slowing down"],
        explanation: "Seeing Earth whole from space often shifts how people think.",
      },
      lt: {
        question: "Kas yra apžvalgos efektas, kurį apibūdina daug astronautų?",
        correct: "Nuostaba matant Žemę",
        distractors: ["Tamsos baimė", "Pusiausvyros praradimas", "Staigus alkis", "Geresnė rega", "Laiko lėtėjimas"],
        explanation: "Pamačius visą Žemę iš kosmoso dažnai pasikeičia mąstymas.",
      },
    },
  },
  {
    id: "cos_ast_029",
    category: "cosmos",
    subTheme: "astronauts",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Space medicine — fluid shift puffs the face in microgravity",
    emoji: "😮",
    translations: {
      en: {
        question: "What happens to an astronaut's face in microgravity?",
        correct: "It puffs up",
        distractors: ["It turns blue", "It shrinks", "It freezes", "It glows", "It dries out"],
        explanation: "Body fluids drift upward, giving a puffy 'moon face'.",
      },
      lt: {
        question: "Kas nutinka astronauto veidui nesvarume?",
        correct: "Jis išsipučia",
        distractors: ["Pamėlsta", "Susitraukia", "Sušąla", "Švyti", "Išsausėja"],
        explanation: "Kūno skysčiai pakyla aukštyn, tad veidas tampa apkūnus.",
      },
    },
  },
  {
    id: "cos_ast_030",
    category: "cosmos",
    subTheme: "astronauts",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "NASA — ISS crew quarters (sleep pods)",
    emoji: "🛏️",
    translations: {
      en: {
        question: "What are the small private sleep spaces on the ISS called?",
        correct: "Crew quarters",
        distractors: ["Cockpits", "Lockers", "Cargo bays", "Airlocks", "Garages"],
        explanation: "Each crew member gets a phone-booth-sized padded cabin.",
      },
      lt: {
        question: "Kaip vadinamos mažos asmeninės miego vietos TKS?",
        correct: "Įgulos kajutės",
        distractors: ["Kabinos", "Spintelės", "Krovinių skyriai", "Šliuzai", "Garažai"],
        explanation: "Kiekvienas gauna telefono būdelės dydžio minkštą kajutę.",
      },
    },
  },

  // ===================== EKSTREMALUS (žinovai) =====================
  {
    id: "cos_ast_031",
    category: "cosmos",
    subTheme: "astronauts",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "NASA — ISS orbital speed ~28,000 km/h",
    emoji: "🚀",
    translations: {
      en: {
        question: "About how fast does the Space Station travel?",
        correct: "About 28,000 km/h",
        distractors: ["About 1,000 km/h", "About 100,000 km/h", "About 5,000 km/h", "About 300 km/h", "About 800 km/h"],
        explanation: "That's roughly 8 km every second — fast enough to stay in orbit.",
      },
      lt: {
        question: "Maždaug kokiu greičiu skrieja kosminė stotis?",
        correct: "Apie 28 000 km/h",
        distractors: ["Apie 1 000 km/h", "Apie 100 000 km/h", "Apie 5 000 km/h", "Apie 300 km/h", "Apie 800 km/h"],
        explanation: "Tai maždaug 8 km per sekundę — pakanka likti orbitoje.",
      },
    },
  },
  {
    id: "cos_ast_032",
    category: "cosmos",
    subTheme: "astronauts",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Spaceflight history — Dennis Tito, first space tourist (2001)",
    emoji: "💸",
    translations: {
      en: {
        question: "Who became the first paying space tourist, in 2001?",
        correct: "Dennis Tito",
        distractors: ["Elon Musk", "Richard Branson", "Jeff Bezos", "Yusaku Maezawa", "Guy Laliberté"],
        explanation: "He paid to fly to the ISS aboard a Russian Soyuz.",
      },
      lt: {
        question: "Kas 2001 m. tapo pirmuoju mokančiu kosmoso turistu?",
        correct: "Denisas Titas",
        distractors: ["Elonas Maskas", "Ričardas Bransonas", "Džefas Bezosas", "Jusaku Maezava", "Gajus Laljbertė"],
        explanation: "Jis sumokėjo už skrydį į TKS rusišku Sojuz laivu.",
      },
    },
  },
  {
    id: "cos_ast_033",
    category: "cosmos",
    subTheme: "astronauts",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Aerospace — the Kármán line at ~100 km",
    emoji: "📐",
    translations: {
      en: {
        question: "About how high is the Kármán line, the edge of space?",
        correct: "About 100 km up",
        distractors: ["About 10 km up", "About 1,000 km up", "About 500 km up", "About 50 km up", "About 5 km up"],
        explanation: "Above ~100 km, the air is too thin for planes to fly.",
      },
      lt: {
        question: "Maždaug kokiame aukštyje yra Karmano linija — kosmoso riba?",
        correct: "Apie 100 km",
        distractors: ["Apie 10 km", "Apie 1 000 km", "Apie 500 km", "Apie 50 km", "Apie 5 km"],
        explanation: "Virš ~100 km oras per retas, kad lėktuvai galėtų skristi.",
      },
    },
  },
  {
    id: "cos_ast_034",
    category: "cosmos",
    subTheme: "astronauts",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "NASA — Apollo 8, first crewed flight around the Moon (1968)",
    emoji: "🌙",
    translations: {
      en: {
        question: "Which mission first carried humans around the Moon, in 1968?",
        correct: "Apollo 8",
        distractors: ["Apollo 1", "Apollo 11", "Apollo 13", "Apollo 7", "Apollo 17"],
        explanation: "Apollo 8 orbited the Moon but did not land.",
      },
      lt: {
        question: "Kuri misija 1968 m. pirmoji nuskraidino žmones aplink Mėnulį?",
        correct: "Apollo 8",
        distractors: ["Apollo 1", "Apollo 11", "Apollo 13", "Apollo 7", "Apollo 17"],
        explanation: "Apollo 8 apskriejo Mėnulį, bet nenusileido.",
      },
    },
  },
  {
    id: "cos_ast_035",
    category: "cosmos",
    subTheme: "astronauts",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Space safety — orbital debris hypervelocity impacts",
    emoji: "☄️",
    translations: {
      en: {
        question: "Why is even tiny space debris dangerous to the ISS?",
        correct: "It hits at huge speed",
        distractors: ["It is poisonous", "It is magnetic", "It blocks the Sun", "It is very hot", "It makes noise"],
        explanation: "A paint fleck at orbital speed can crack a window.",
      },
      lt: {
        question: "Kodėl net mažytės kosmoso šiukšlės pavojingos TKS?",
        correct: "Trenkia milžinišku greičiu",
        distractors: ["Jos nuodingos", "Jos magnetinės", "Užstoja Saulę", "Jos būna labai karštos", "Kelia triukšmą"],
        explanation: "Dažų lustelis orbitiniu greičiu gali įskelti langą.",
      },
    },
  },
  {
    id: "cos_ast_036",
    category: "cosmos",
    subTheme: "astronauts",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Space medicine — cosmic radiation raises cancer risk",
    emoji: "☢️",
    translations: {
      en: {
        question: "What is a key long-term danger of cosmic radiation in space?",
        correct: "Higher cancer risk",
        distractors: ["Instant freezing", "Loss of hearing", "Hair turning green", "Sudden weight gain", "Color blindness"],
        explanation: "Beyond Earth's shield, astronauts soak up more radiation.",
      },
      lt: {
        question: "Koks pagrindinis ilgalaikis kosminės spinduliuotės pavojus?",
        correct: "Didesnė vėžio rizika",
        distractors: ["Akimirksniu sušąla", "Klausos praradimas", "Plaukai pažaliuoja", "Staigus svorio augimas", "Spalvinis aklumas"],
        explanation: "Už Žemės skydo astronautai sugeria daugiau spinduliuotės.",
      },
    },
  },
  {
    id: "cos_ast_037",
    category: "cosmos",
    subTheme: "astronauts",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "History — Leonov's suit ballooned on the first spacewalk (1965)",
    emoji: "🎈",
    translations: {
      en: {
        question: "On the first spacewalk, Leonov's suit dangerously...?",
        correct: "Ballooned up stiff",
        distractors: ["Caught fire", "Froze solid", "Tore open", "Filled with water", "Lost all color"],
        explanation: "It swelled so much he had to bleed out air to get back inside.",
      },
      lt: {
        question: "Per pirmąjį išėjimą Leonovo skafandras pavojingai...?",
        correct: "Išsipūtė ir sustingo",
        distractors: ["Užsidegė", "Sušalo", "Plyšo", "Prisipildė vandens", "Prarado spalvą"],
        explanation: "Jis taip išsipūtė, kad teko išleisti orą, norint grįžti vidun.",
      },
    },
  },
  {
    id: "cos_ast_038",
    category: "cosmos",
    subTheme: "astronauts",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Spacecraft engineering — heat shield protects on re-entry",
    emoji: "🔥",
    translations: {
      en: {
        question: "What does a capsule's heat shield protect against on return?",
        correct: "Re-entry heat",
        distractors: ["Cosmic rays", "Space debris", "The cold vacuum", "Bright sunlight", "Loud sound"],
        explanation: "Air friction heats the capsule to over 1,500 °C coming home.",
      },
      lt: {
        question: "Nuo ko kapsulės šilumos skydas saugo grįžtant į Žemę?",
        correct: "Nuo įkaitimo",
        distractors: ["Nuo spindulių", "Nuo šiukšlių", "Nuo šalto vakuumo", "Nuo Saulės", "Nuo garso"],
        explanation: "Oro trintis grįžtant įkaitina kapsulę iki daugiau nei 1 500 °C.",
      },
    },
  },
  {
    id: "cos_ast_039",
    category: "cosmos",
    subTheme: "astronauts",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Space medicine — tears do not fall in microgravity",
    emoji: "💧",
    translations: {
      en: {
        question: "Why can't astronauts cry normal falling tears in space?",
        correct: "Tears do not fall",
        distractors: ["Their eyes freeze", "They feel no sadness", "Tears turn to gas", "Eyes stop working", "It is not allowed"],
        explanation: "Without gravity, tears pool into a wobbly ball on the eye.",
      },
      lt: {
        question: "Kodėl kosmose astronautai negali verkti krentančiomis ašaromis?",
        correct: "Ašaros nenukrenta",
        distractors: ["Užšąla akys", "Nejaučia liūdesio", "Ašaros virsta dujomis", "Akys nustoja veikti", "Tai draudžiama"],
        explanation: "Be gravitacijos ašaros susirenka į virpantį kamuoliuką ant akies.",
      },
    },
  },
  {
    id: "cos_ast_040",
    category: "cosmos",
    subTheme: "astronauts",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Space medicine — space adaptation syndrome (space sickness)",
    emoji: "🤢",
    translations: {
      en: {
        question: "What do most astronauts feel during their first days in orbit?",
        correct: "Space motion sickness",
        distractors: ["Sudden total deafness", "Total blindness", "Memory loss", "Rapid aging", "Skin peeling"],
        explanation: "The confused inner ear causes nausea until the body adjusts.",
      },
      lt: {
        question: "Ką dauguma astronautų jaučia pirmosiomis dienomis orbitoje?",
        correct: "Kosminį pykinimą",
        distractors: ["Staigų kurtumą", "Visišką aklumą", "Atminties praradimą", "Spartų senėjimą", "Odos lupimąsi"],
        explanation: "Sutrikusi vidinė ausis sukelia pykinimą, kol kūnas prisitaiko.",
      },
    },
  },
];
