/**
 * geoContent — „Geografija ir pasaulis” trivijos klausimai (EN + LT).
 *
 * Po 15 klausimų kiekvienam lygiui (lengvas/vidutinis/sunkus/ekstremalus) = 60.
 * Temos: sostinės, žemynai, vandenynai, kalnai, upės, šalys, rekordai.
 *
 * TAISYKLĖS (Manifestas):
 *   - 1 teisingas + 5 distractors; visi 6 variantai VISOSE kalbose ≤46 simbolių;
 *   - faktai 100% patikrinti (sourceVerified); neutralu (jokios politikos/religijos);
 *   - LT vidinės kabutės tik „..." (ne ASCII "); detalės — į explanation, ne į variantą.
 *
 * Formatas — žr. triviaTypes.ts (TriviaQuestion). category visada "geo".
 */

import { TriviaQuestion } from "./triviaTypes";

export const GEO_QUESTIONS: TriviaQuestion[] = [
  // ======================= LENGVAS (Easy) =======================
  {
    id: "geo_le_001",
    category: "geo",
    subTheme: "capitals",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "World capitals (encyclopedic)",
    emoji: "🗼",
    translations: {
      en: {
        question: "What is the capital of France?",
        correct: "Paris",
        distractors: ["London", "Berlin", "Madrid", "Rome", "Lisbon"],
        explanation: "Paris has been the capital of France for centuries.",
      },
      lt: {
        question: "Kokia Prancūzijos sostinė?",
        correct: "Paryžius",
        distractors: ["Londonas", "Berlynas", "Madridas", "Roma", "Lisabona"],
        explanation: "Paryžius jau šimtmečius yra Prancūzijos sostinė.",
      },
    },
  },
  {
    id: "geo_le_002",
    category: "geo",
    subTheme: "oceans",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Oceanography (largest ocean)",
    emoji: "🌊",
    translations: {
      en: {
        question: "What is the largest ocean on Earth?",
        correct: "Pacific Ocean",
        distractors: [
          "Atlantic Ocean",
          "Indian Ocean",
          "Arctic Ocean",
          "Southern Ocean",
          "Mediterranean Sea",
        ],
        explanation: "The Pacific Ocean is the largest and deepest ocean.",
      },
      lt: {
        question: "Koks didžiausias Žemės vandenynas?",
        correct: "Ramusis vandenynas",
        distractors: [
          "Atlanto vandenynas",
          "Indijos vandenynas",
          "Arkties vandenynas",
          "Pietų vandenynas",
          "Viduržemio jūra",
        ],
        explanation: "Ramusis vandenynas yra didžiausias ir giliausias.",
      },
    },
  },
  {
    id: "geo_le_003",
    category: "geo",
    subTheme: "continents",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography (continents)",
    emoji: "🌍",
    translations: {
      en: {
        question: "How many continents are there on Earth?",
        correct: "7",
        distractors: ["5", "6", "8", "4", "9"],
        explanation: "The seven continents include Asia, Africa and Europe.",
      },
      lt: {
        question: "Kiek žemynų yra Žemėje?",
        correct: "7",
        distractors: ["5", "6", "8", "4", "9"],
        explanation: "Septyni žemynai: Azija, Afrika, Europa ir kiti.",
      },
    },
  },
  {
    id: "geo_le_004",
    category: "geo",
    subTheme: "capitals",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "World capitals (Japan)",
    emoji: "🇯🇵",
    translations: {
      en: {
        question: "What is the capital of Japan?",
        correct: "Tokyo",
        distractors: ["Kyoto", "Osaka", "Seoul", "Beijing", "Bangkok"],
        explanation: "Tokyo is Japan's capital and largest city.",
      },
      lt: {
        question: "Kokia Japonijos sostinė?",
        correct: "Tokijas",
        distractors: ["Kiotas", "Osaka", "Seulas", "Pekinas", "Bankokas"],
        explanation: "Tokijas — Japonijos sostinė ir didžiausias miestas.",
      },
    },
  },
  {
    id: "geo_le_005",
    category: "geo",
    subTheme: "capitals",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "World capitals (Italy)",
    emoji: "🇮🇹",
    translations: {
      en: {
        question: "What is the capital of Italy?",
        correct: "Rome",
        distractors: ["Milan", "Venice", "Naples", "Florence", "Turin"],
        explanation: "Rome is the capital of Italy and home to the Colosseum.",
      },
      lt: {
        question: "Kokia Italijos sostinė?",
        correct: "Roma",
        distractors: ["Milanas", "Venecija", "Neapolis", "Florencija", "Turinas"],
        explanation: "Roma — Italijos sostinė, garsėjanti Koliziejumi.",
      },
    },
  },
  {
    id: "geo_le_006",
    category: "geo",
    subTheme: "continents",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography (Egypt location)",
    emoji: "🐫",
    translations: {
      en: {
        question: "On which continent is Egypt located?",
        correct: "Africa",
        distractors: [
          "Asia",
          "Europe",
          "South America",
          "Australia",
          "Antarctica",
        ],
        explanation: "Egypt is in the north-east of Africa.",
      },
      lt: {
        question: "Kuriame žemyne yra Egiptas?",
        correct: "Afrika",
        distractors: [
          "Azija",
          "Europa",
          "Pietų Amerika",
          "Australija",
          "Antarktida",
        ],
        explanation: "Egiptas yra šiaurės rytų Afrikoje.",
      },
    },
  },
  {
    id: "geo_le_007",
    category: "geo",
    subTheme: "continents",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography (largest continent)",
    emoji: "🗺️",
    translations: {
      en: {
        question: "What is the largest continent by area?",
        correct: "Asia",
        distractors: [
          "Africa",
          "Europe",
          "North America",
          "Antarctica",
          "Australia",
        ],
        explanation: "Asia is the largest continent and the most populated.",
      },
      lt: {
        question: "Koks didžiausias žemynas pagal plotą?",
        correct: "Azija",
        distractors: [
          "Afrika",
          "Europa",
          "Šiaurės Amerika",
          "Antarktida",
          "Australija",
        ],
        explanation: "Azija — didžiausias ir daugiausiai gyventojų turintis žemynas.",
      },
    },
  },
  {
    id: "geo_le_008",
    category: "geo",
    subTheme: "capitals",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "World capitals (United Kingdom)",
    emoji: "🇬🇧",
    translations: {
      en: {
        question: "What is the capital of the United Kingdom?",
        correct: "London",
        distractors: [
          "Manchester",
          "Liverpool",
          "Dublin",
          "Edinburgh",
          "Birmingham",
        ],
        explanation: "London is the capital of the United Kingdom.",
      },
      lt: {
        question: "Kokia Jungtinės Karalystės sostinė?",
        correct: "Londonas",
        distractors: [
          "Mančesteris",
          "Liverpulis",
          "Dublinas",
          "Edinburgas",
          "Birmingemas",
        ],
        explanation: "Londonas — Jungtinės Karalystės sostinė.",
      },
    },
  },
  {
    id: "geo_le_009",
    category: "geo",
    subTheme: "capitals",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "World capitals (Spain)",
    emoji: "🇪🇸",
    translations: {
      en: {
        question: "What is the capital of Spain?",
        correct: "Madrid",
        distractors: ["Barcelona", "Valencia", "Seville", "Lisbon", "Porto"],
        explanation: "Madrid is the capital and largest city of Spain.",
      },
      lt: {
        question: "Kokia Ispanijos sostinė?",
        correct: "Madridas",
        distractors: ["Barselona", "Valensija", "Sevilija", "Lisabona", "Portas"],
        explanation: "Madridas — Ispanijos sostinė ir didžiausias miestas.",
      },
    },
  },
  {
    id: "geo_le_010",
    category: "geo",
    subTheme: "capitals",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "World capitals (Germany)",
    emoji: "🇩🇪",
    translations: {
      en: {
        question: "What is the capital of Germany?",
        correct: "Berlin",
        distractors: ["Munich", "Hamburg", "Frankfurt", "Cologne", "Vienna"],
        explanation: "Berlin is the capital and largest city of Germany.",
      },
      lt: {
        question: "Kokia Vokietijos sostinė?",
        correct: "Berlynas",
        distractors: ["Miunchenas", "Hamburgas", "Frankfurtas", "Kelnas", "Viena"],
        explanation: "Berlynas — Vokietijos sostinė ir didžiausias miestas.",
      },
    },
  },
  {
    id: "geo_le_011",
    category: "geo",
    subTheme: "capitals",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "World capitals (Russia)",
    emoji: "🇷🇺",
    translations: {
      en: {
        question: "What is the capital of Russia?",
        correct: "Moscow",
        distractors: [
          "Saint Petersburg",
          "Novosibirsk",
          "Kazan",
          "Sochi",
          "Minsk",
        ],
        explanation: "Moscow is the capital and largest city of Russia.",
      },
      lt: {
        question: "Kokia Rusijos sostinė?",
        correct: "Maskva",
        distractors: [
          "Sankt Peterburgas",
          "Novosibirskas",
          "Kazanė",
          "Sočis",
          "Minskas",
        ],
        explanation: "Maskva — Rusijos sostinė ir didžiausias miestas.",
      },
    },
  },
  {
    id: "geo_le_012",
    category: "geo",
    subTheme: "capitals",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "World capitals (Greece)",
    emoji: "🏛️",
    translations: {
      en: {
        question: "What is the capital of Greece?",
        correct: "Athens",
        distractors: [
          "Sparta",
          "Thessaloniki",
          "Crete",
          "Rome",
          "Istanbul",
        ],
        explanation: "Athens is the capital of Greece and an ancient city.",
      },
      lt: {
        question: "Kokia Graikijos sostinė?",
        correct: "Atėnai",
        distractors: [
          "Sparta",
          "Salonikai",
          "Kreta",
          "Roma",
          "Stambulas",
        ],
        explanation: "Atėnai — Graikijos sostinė ir senovinis miestas.",
      },
    },
  },
  {
    id: "geo_le_013",
    category: "geo",
    subTheme: "capitals",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "World capitals (China)",
    emoji: "🇨🇳",
    translations: {
      en: {
        question: "What is the capital of China?",
        correct: "Beijing",
        distractors: [
          "Shanghai",
          "Hong Kong",
          "Tokyo",
          "Guangzhou",
          "Seoul",
        ],
        explanation: "Beijing is the capital of China.",
      },
      lt: {
        question: "Kokia Kinijos sostinė?",
        correct: "Pekinas",
        distractors: [
          "Šanchajus",
          "Honkongas",
          "Tokijas",
          "Guangdžou",
          "Seulas",
        ],
        explanation: "Pekinas — Kinijos sostinė.",
      },
    },
  },
  {
    id: "geo_le_014",
    category: "geo",
    subTheme: "countries",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography (Italy shape)",
    emoji: "👢",
    translations: {
      en: {
        question: "Which country is shaped like a boot?",
        correct: "Italy",
        distractors: ["Spain", "Greece", "Portugal", "France", "Turkey"],
        explanation: "Italy's peninsula looks like a boot on the map.",
      },
      lt: {
        question: "Kuri šalis žemėlapyje primena batą?",
        correct: "Italija",
        distractors: ["Ispanija", "Graikija", "Portugalija", "Prancūzija", "Turkija"],
        explanation: "Italijos pusiasalis žemėlapyje atrodo kaip batas.",
      },
    },
  },
  {
    id: "geo_le_015",
    category: "geo",
    subTheme: "capitals",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "World capitals (Lithuania)",
    emoji: "🇱🇹",
    translations: {
      en: {
        question: "What is the capital of Lithuania?",
        correct: "Vilnius",
        distractors: ["Kaunas", "Klaipėda", "Šiauliai", "Panevėžys", "Riga"],
        explanation: "Vilnius is the capital and largest city of Lithuania.",
      },
      lt: {
        question: "Kokia Lietuvos sostinė?",
        correct: "Vilnius",
        distractors: ["Kaunas", "Klaipėda", "Šiauliai", "Panevėžys", "Ryga"],
        explanation: "Vilnius — Lietuvos sostinė ir didžiausias miestas.",
      },
    },
  },

  // ======================= VIDUTINIS (Medium) =======================
  {
    id: "geo_me_001",
    category: "geo",
    subTheme: "capitals",
    level: "vidutinis",
    isTrap: true,
    sourceVerified: "World capitals (Australia)",
    emoji: "🦘",
    translations: {
      en: {
        question: "What is the capital of Australia?",
        correct: "Canberra",
        distractors: ["Sydney", "Melbourne", "Brisbane", "Perth", "Auckland"],
        explanation: "Canberra is the capital, not Sydney or Melbourne.",
      },
      lt: {
        question: "Kokia Australijos sostinė?",
        correct: "Kanbera",
        distractors: ["Sidnėjus", "Melburnas", "Brisbenas", "Pertas", "Oklandas"],
        explanation: "Sostinė yra Kanbera, ne Sidnėjus ar Melburnas.",
      },
    },
  },
  {
    id: "geo_me_002",
    category: "geo",
    subTheme: "capitals",
    level: "vidutinis",
    isTrap: true,
    sourceVerified: "World capitals (Canada)",
    emoji: "🍁",
    translations: {
      en: {
        question: "What is the capital of Canada?",
        correct: "Ottawa",
        distractors: ["Toronto", "Vancouver", "Montreal", "Quebec", "Calgary"],
        explanation: "Ottawa is the capital, not Toronto.",
      },
      lt: {
        question: "Kokia Kanados sostinė?",
        correct: "Otava",
        distractors: ["Torontas", "Vankuveris", "Monrealis", "Kvebekas", "Kalgaris"],
        explanation: "Sostinė yra Otava, ne Torontas.",
      },
    },
  },
  {
    id: "geo_me_003",
    category: "geo",
    subTheme: "mountains",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Geography (highest mountain)",
    emoji: "🏔️",
    translations: {
      en: {
        question: "What is the highest mountain in the world?",
        correct: "Mount Everest",
        distractors: ["K2", "Mont Blanc", "Kilimanjaro", "Matterhorn", "Denali"],
        explanation: "Mount Everest is about 8 849 metres tall.",
      },
      lt: {
        question: "Koks aukščiausias kalnas pasaulyje?",
        correct: "Everestas",
        distractors: ["K2", "Monblanas", "Kilimandžaras", "Matterhornas", "Denalis"],
        explanation: "Everestas yra apie 8 849 metrų aukščio.",
      },
    },
  },
  {
    id: "geo_me_004",
    category: "geo",
    subTheme: "capitals",
    level: "vidutinis",
    isTrap: true,
    sourceVerified: "World capitals (Turkey)",
    emoji: "🇹🇷",
    translations: {
      en: {
        question: "What is the capital of Turkey?",
        correct: "Ankara",
        distractors: ["Istanbul", "Izmir", "Antalya", "Bursa", "Athens"],
        explanation: "Ankara is the capital, not Istanbul.",
      },
      lt: {
        question: "Kokia Turkijos sostinė?",
        correct: "Ankara",
        distractors: ["Stambulas", "Izmiras", "Antalija", "Bursa", "Atėnai"],
        explanation: "Sostinė yra Ankara, ne Stambulas.",
      },
    },
  },
  {
    id: "geo_me_005",
    category: "geo",
    subTheme: "records",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Geography (largest country)",
    emoji: "📏",
    translations: {
      en: {
        question: "Which is the largest country by area?",
        correct: "Russia",
        distractors: ["Canada", "China", "USA", "Brazil", "Australia"],
        explanation: "Russia is the largest country, spanning two continents.",
      },
      lt: {
        question: "Kuri šalis didžiausia pagal plotą?",
        correct: "Rusija",
        distractors: ["Kanada", "Kinija", "JAV", "Brazilija", "Australija"],
        explanation: "Rusija — didžiausia šalis, besidriekianti per du žemynus.",
      },
    },
  },
  {
    id: "geo_me_006",
    category: "geo",
    subTheme: "records",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Geography (smallest country)",
    emoji: "⛪",
    translations: {
      en: {
        question: "What is the smallest country in the world?",
        correct: "Vatican City",
        distractors: ["Monaco", "San Marino", "Malta", "Liechtenstein", "Luxembourg"],
        explanation: "Vatican City is the smallest country by area.",
      },
      lt: {
        question: "Kokia mažiausia šalis pasaulyje?",
        correct: "Vatikanas",
        distractors: ["Monakas", "San Marinas", "Malta", "Lichtenšteinas", "Liuksemburgas"],
        explanation: "Vatikanas — mažiausia šalis pagal plotą.",
      },
    },
  },
  {
    id: "geo_me_007",
    category: "geo",
    subTheme: "rivers",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Geography (Nile through Egypt)",
    emoji: "🏞️",
    translations: {
      en: {
        question: "Which river flows through Egypt?",
        correct: "Nile",
        distractors: ["Amazon", "Congo", "Ganges", "Danube", "Volga"],
        explanation: "The Nile flows north through Egypt to the sea.",
      },
      lt: {
        question: "Kuri upė teka per Egiptą?",
        correct: "Nilas",
        distractors: ["Amazonė", "Kongas", "Gangas", "Dunojus", "Volga"],
        explanation: "Nilas teka per Egiptą į šiaurę, link jūros.",
      },
    },
  },
  {
    id: "geo_me_008",
    category: "geo",
    subTheme: "capitals",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "World capitals (Portugal)",
    emoji: "🇵🇹",
    translations: {
      en: {
        question: "What is the capital of Portugal?",
        correct: "Lisbon",
        distractors: ["Porto", "Madrid", "Faro", "Coimbra", "Braga"],
        explanation: "Lisbon is the capital and largest city of Portugal.",
      },
      lt: {
        question: "Kokia Portugalijos sostinė?",
        correct: "Lisabona",
        distractors: ["Portas", "Madridas", "Faras", "Koimbra", "Braga"],
        explanation: "Lisabona — Portugalijos sostinė ir didžiausias miestas.",
      },
    },
  },
  {
    id: "geo_me_009",
    category: "geo",
    subTheme: "capitals",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "World capitals (Sweden)",
    emoji: "🇸🇪",
    translations: {
      en: {
        question: "What is the capital of Sweden?",
        correct: "Stockholm",
        distractors: ["Gothenburg", "Malmö", "Oslo", "Copenhagen", "Helsinki"],
        explanation: "Stockholm is the capital of Sweden.",
      },
      lt: {
        question: "Kokia Švedijos sostinė?",
        correct: "Stokholmas",
        distractors: ["Geteborgas", "Malmė", "Oslas", "Kopenhaga", "Helsinkis"],
        explanation: "Stokholmas — Švedijos sostinė.",
      },
    },
  },
  {
    id: "geo_me_010",
    category: "geo",
    subTheme: "capitals",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "World capitals (Norway)",
    emoji: "🇳🇴",
    translations: {
      en: {
        question: "What is the capital of Norway?",
        correct: "Oslo",
        distractors: ["Bergen", "Stockholm", "Trondheim", "Helsinki", "Reykjavik"],
        explanation: "Oslo is the capital of Norway.",
      },
      lt: {
        question: "Kokia Norvegijos sostinė?",
        correct: "Oslas",
        distractors: ["Bergenas", "Stokholmas", "Trondheimas", "Helsinkis", "Reikjavikas"],
        explanation: "Oslas — Norvegijos sostinė.",
      },
    },
  },
  {
    id: "geo_me_011",
    category: "geo",
    subTheme: "capitals",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "World capitals (Poland)",
    emoji: "🇵🇱",
    translations: {
      en: {
        question: "What is the capital of Poland?",
        correct: "Warsaw",
        distractors: ["Krakow", "Gdansk", "Wroclaw", "Poznan", "Lodz"],
        explanation: "Warsaw is the capital and largest city of Poland.",
      },
      lt: {
        question: "Kokia Lenkijos sostinė?",
        correct: "Varšuva",
        distractors: ["Krokuva", "Gdanskas", "Vroclavas", "Poznanė", "Lodzė"],
        explanation: "Varšuva — Lenkijos sostinė ir didžiausias miestas.",
      },
    },
  },
  {
    id: "geo_me_012",
    category: "geo",
    subTheme: "capitals",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "World capitals (Netherlands)",
    emoji: "🌷",
    translations: {
      en: {
        question: "What is the capital of the Netherlands?",
        correct: "Amsterdam",
        distractors: ["Rotterdam", "The Hague", "Utrecht", "Brussels", "Eindhoven"],
        explanation: "Amsterdam is the capital of the Netherlands.",
      },
      lt: {
        question: "Kokia Nyderlandų sostinė?",
        correct: "Amsterdamas",
        distractors: ["Roterdamas", "Haga", "Utrechtas", "Briuselis", "Eindhovenas"],
        explanation: "Amsterdamas — Nyderlandų sostinė.",
      },
    },
  },
  {
    id: "geo_me_013",
    category: "geo",
    subTheme: "deserts",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Geography (largest hot desert)",
    emoji: "🏜️",
    translations: {
      en: {
        question: "What is the largest hot desert in the world?",
        correct: "Sahara",
        distractors: ["Gobi", "Kalahari", "Arabian", "Mojave", "Atacama"],
        explanation: "The Sahara in Africa is the largest hot desert.",
      },
      lt: {
        question: "Kokia didžiausia karštoji dykuma pasaulyje?",
        correct: "Sachara",
        distractors: ["Gobis", "Kalaharis", "Arabijos", "Modavė", "Atakama"],
        explanation: "Sachara Afrikoje — didžiausia karštoji dykuma.",
      },
    },
  },
  {
    id: "geo_me_014",
    category: "geo",
    subTheme: "capitals",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "World capitals (Egypt)",
    emoji: "🕌",
    translations: {
      en: {
        question: "What is the capital of Egypt?",
        correct: "Cairo",
        distractors: ["Alexandria", "Giza", "Luxor", "Aswan", "Rabat"],
        explanation: "Cairo is the capital and largest city of Egypt.",
      },
      lt: {
        question: "Kokia Egipto sostinė?",
        correct: "Kairas",
        distractors: ["Aleksandrija", "Giza", "Luksoras", "Asuanas", "Rabatas"],
        explanation: "Kairas — Egipto sostinė ir didžiausias miestas.",
      },
    },
  },
  {
    id: "geo_me_015",
    category: "geo",
    subTheme: "capitals",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "World capitals (Latvia)",
    emoji: "🇱🇻",
    translations: {
      en: {
        question: "What is the capital of Latvia?",
        correct: "Riga",
        distractors: ["Vilnius", "Tallinn", "Kaunas", "Minsk", "Warsaw"],
        explanation: "Riga is the capital and largest city of Latvia.",
      },
      lt: {
        question: "Kokia Latvijos sostinė?",
        correct: "Ryga",
        distractors: ["Vilnius", "Talinas", "Kaunas", "Minskas", "Varšuva"],
        explanation: "Ryga — Latvijos sostinė ir didžiausias miestas.",
      },
    },
  },

  // ======================= SUNKUS (Hard) =======================
  {
    id: "geo_su_001",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: true,
    sourceVerified: "World capitals (Switzerland)",
    emoji: "🇨🇭",
    translations: {
      en: {
        question: "What is the capital of Switzerland?",
        correct: "Bern",
        distractors: ["Zurich", "Geneva", "Basel", "Lausanne", "Lucerne"],
        explanation: "Bern is the capital, not Zurich or Geneva.",
      },
      lt: {
        question: "Kokia Šveicarijos sostinė?",
        correct: "Bernas",
        distractors: ["Ciurichas", "Ženeva", "Bazelis", "Lozana", "Liucerna"],
        explanation: "Sostinė yra Bernas, ne Ciurichas ar Ženeva.",
      },
    },
  },
  {
    id: "geo_su_002",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: true,
    sourceVerified: "World capitals (New Zealand)",
    emoji: "🥝",
    translations: {
      en: {
        question: "What is the capital of New Zealand?",
        correct: "Wellington",
        distractors: ["Auckland", "Christchurch", "Hamilton", "Dunedin", "Sydney"],
        explanation: "Wellington is the capital, not Auckland.",
      },
      lt: {
        question: "Kokia Naujosios Zelandijos sostinė?",
        correct: "Velingtonas",
        distractors: ["Oklandas", "Kraistčerčas", "Hamiltonas", "Dunedinas", "Sidnėjus"],
        explanation: "Sostinė yra Velingtonas, ne Oklandas.",
      },
    },
  },
  {
    id: "geo_su_003",
    category: "geo",
    subTheme: "records",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "UN population data (2023, India)",
    emoji: "👥",
    translations: {
      en: {
        question: "Which country has the most people today?",
        correct: "India",
        distractors: ["China", "USA", "Indonesia", "Brazil", "Russia"],
        explanation: "In 2023 India became the most populous country.",
      },
      lt: {
        question: "Kuri šalis šiandien turi daugiausiai gyventojų?",
        correct: "Indija",
        distractors: ["Kinija", "JAV", "Indonezija", "Brazilija", "Rusija"],
        explanation: "2023 m. Indija tapo daugiausiai gyventojų turinčia šalimi.",
      },
    },
  },
  {
    id: "geo_su_004",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "World capitals (Argentina)",
    emoji: "🇦🇷",
    translations: {
      en: {
        question: "What is the capital of Argentina?",
        correct: "Buenos Aires",
        distractors: ["Córdoba", "Rosario", "Santiago", "Lima", "Montevideo"],
        explanation: "Buenos Aires is the capital of Argentina.",
      },
      lt: {
        question: "Kokia Argentinos sostinė?",
        correct: "Buenos Airės",
        distractors: ["Kordoba", "Rosarijus", "Santjagas", "Lima", "Montevidėjas"],
        explanation: "Buenos Airės — Argentinos sostinė.",
      },
    },
  },
  {
    id: "geo_su_005",
    category: "geo",
    subTheme: "records",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Oceanography (Mariana Trench)",
    emoji: "🕳️",
    translations: {
      en: {
        question: "What is the deepest ocean trench?",
        correct: "Mariana Trench",
        distractors: [
          "Tonga Trench",
          "Java Trench",
          "Puerto Rico Trench",
          "Philippine Trench",
          "Kermadec Trench",
        ],
        explanation: "The Mariana Trench reaches almost 11 000 metres deep.",
      },
      lt: {
        question: "Kokia giliausia vandenyno įduba?",
        correct: "Marianų įduba",
        distractors: [
          "Tongos įduba",
          "Javos įduba",
          "Puerto Riko įduba",
          "Filipinų įduba",
          "Kermadeko įduba",
        ],
        explanation: "Marianų įduba siekia beveik 11 000 metrų gylį.",
      },
    },
  },
  {
    id: "geo_su_006",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "World capitals (Iceland)",
    emoji: "🌋",
    translations: {
      en: {
        question: "What is the capital of Iceland?",
        correct: "Reykjavik",
        distractors: ["Oslo", "Helsinki", "Bergen", "Nuuk", "Tórshavn"],
        explanation: "Reykjavik is the world's northernmost capital.",
      },
      lt: {
        question: "Kokia Islandijos sostinė?",
        correct: "Reikjavikas",
        distractors: ["Oslas", "Helsinkis", "Bergenas", "Nukas", "Tórshaunas"],
        explanation: "Reikjavikas — labiausiai į šiaurę esanti sostinė.",
      },
    },
  },
  {
    id: "geo_su_007",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "World capitals (Finland)",
    emoji: "🇫🇮",
    translations: {
      en: {
        question: "What is the capital of Finland?",
        correct: "Helsinki",
        distractors: ["Espoo", "Tampere", "Turku", "Stockholm", "Tallinn"],
        explanation: "Helsinki is the capital of Finland.",
      },
      lt: {
        question: "Kokia Suomijos sostinė?",
        correct: "Helsinkis",
        distractors: ["Espas", "Tamperė", "Turku", "Stokholmas", "Talinas"],
        explanation: "Helsinkis — Suomijos sostinė.",
      },
    },
  },
  {
    id: "geo_su_008",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: true,
    sourceVerified: "World capitals (Morocco)",
    emoji: "🇲🇦",
    translations: {
      en: {
        question: "What is the capital of Morocco?",
        correct: "Rabat",
        distractors: ["Casablanca", "Marrakech", "Fez", "Tangier", "Cairo"],
        explanation: "Rabat is the capital, not Casablanca.",
      },
      lt: {
        question: "Kokia Maroko sostinė?",
        correct: "Rabatas",
        distractors: ["Kasablanka", "Marakešas", "Fesas", "Tangeras", "Kairas"],
        explanation: "Sostinė yra Rabatas, ne Kasablanka.",
      },
    },
  },
  {
    id: "geo_su_009",
    category: "geo",
    subTheme: "records",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Geography (largest island)",
    emoji: "🧊",
    translations: {
      en: {
        question: "What is the largest island in the world?",
        correct: "Greenland",
        distractors: ["New Guinea", "Borneo", "Madagascar", "Iceland", "Australia"],
        explanation: "Greenland is the largest island (Australia is a continent).",
      },
      lt: {
        question: "Kokia didžiausia sala pasaulyje?",
        correct: "Grenlandija",
        distractors: ["Naujoji Gvinėja", "Borneo", "Madagaskaras", "Islandija", "Australija"],
        explanation: "Grenlandija — didžiausia sala (Australija yra žemynas).",
      },
    },
  },
  {
    id: "geo_su_010",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "World capitals (Thailand)",
    emoji: "🇹🇭",
    translations: {
      en: {
        question: "What is the capital of Thailand?",
        correct: "Bangkok",
        distractors: ["Phuket", "Chiang Mai", "Hanoi", "Jakarta", "Manila"],
        explanation: "Bangkok is the capital of Thailand.",
      },
      lt: {
        question: "Kokia Tailando sostinė?",
        correct: "Bankokas",
        distractors: ["Puketas", "Čiangmajus", "Hanojus", "Džakarta", "Manila"],
        explanation: "Bankokas — Tailando sostinė.",
      },
    },
  },
  {
    id: "geo_su_011",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "World capitals (Chile)",
    emoji: "🇨🇱",
    translations: {
      en: {
        question: "What is the capital of Chile?",
        correct: "Santiago",
        distractors: ["Valparaíso", "Lima", "Buenos Aires", "Bogotá", "Quito"],
        explanation: "Santiago is the capital of Chile.",
      },
      lt: {
        question: "Kokia Čilės sostinė?",
        correct: "Santjagas",
        distractors: ["Valparaisas", "Lima", "Buenos Airės", "Bogota", "Kitas"],
        explanation: "Santjagas — Čilės sostinė.",
      },
    },
  },
  {
    id: "geo_su_012",
    category: "geo",
    subTheme: "mountains",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Geography (Ural Mountains)",
    emoji: "⛰️",
    translations: {
      en: {
        question: "Which mountain range separates Europe and Asia?",
        correct: "Ural Mountains",
        distractors: ["Alps", "Andes", "Himalayas", "Caucasus", "Carpathians"],
        explanation: "The Ural Mountains form the Europe-Asia boundary.",
      },
      lt: {
        question: "Kurie kalnai skiria Europą ir Aziją?",
        correct: "Uralo kalnai",
        distractors: ["Alpės", "Andai", "Himalajai", "Kaukazas", "Karpatai"],
        explanation: "Uralo kalnai sudaro Europos ir Azijos ribą.",
      },
    },
  },
  {
    id: "geo_su_013",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "World capitals (Mexico)",
    emoji: "🇲🇽",
    translations: {
      en: {
        question: "What is the capital of Mexico?",
        correct: "Mexico City",
        distractors: ["Cancún", "Guadalajara", "Tijuana", "Lima", "Bogotá"],
        explanation: "Mexico City is the capital of Mexico.",
      },
      lt: {
        question: "Kokia Meksikos sostinė?",
        correct: "Meksikas",
        distractors: ["Kankunas", "Gvadalachara", "Tichuana", "Lima", "Bogota"],
        explanation: "Meksikas (Mexico City) — Meksikos sostinė.",
      },
    },
  },
  {
    id: "geo_su_014",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "World capitals (Ireland)",
    emoji: "☘️",
    translations: {
      en: {
        question: "What is the capital of Ireland?",
        correct: "Dublin",
        distractors: ["Belfast", "Cork", "Galway", "London", "Edinburgh"],
        explanation: "Dublin is the capital of Ireland.",
      },
      lt: {
        question: "Kokia Airijos sostinė?",
        correct: "Dublinas",
        distractors: ["Belfastas", "Korkas", "Golvėjus", "Londonas", "Edinburgas"],
        explanation: "Dublinas — Airijos sostinė.",
      },
    },
  },
  {
    id: "geo_su_015",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: true,
    sourceVerified: "Geography (capital of Brazil)",
    emoji: "🇧🇷",
    translations: {
      en: {
        question: "What is the capital of Brazil?",
        correct: "Brasília",
        distractors: [
          "Rio de Janeiro",
          "São Paulo",
          "Buenos Aires",
          "Lima",
          "Bogotá",
        ],
        explanation: "Brasília was purpose-built and became capital in 1960.",
      },
      lt: {
        question: "Kokia Brazilijos sostinė?",
        correct: "Brazilija (Brasília)",
        distractors: [
          "Rio de Žaneiras",
          "San Paulas",
          "Buenos Airės",
          "Lima",
          "Bogota",
        ],
        explanation: "Brazilija (Brasília) specialiai pastatyta ir sostine tapo 1960 m.",
      },
    },
  },

  // ======================= EKSTREMALUS (Extreme) =======================
  {
    id: "geo_ek_001",
    category: "geo",
    subTheme: "capitals",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "World capitals (Kazakhstan, Astana)",
    emoji: "🇰🇿",
    translations: {
      en: {
        question: "What is the capital of Kazakhstan?",
        correct: "Astana",
        distractors: ["Almaty", "Bishkek", "Tashkent", "Baku", "Samarkand"],
        explanation: "Astana has been the capital since 1997.",
      },
      lt: {
        question: "Kokia Kazachstano sostinė?",
        correct: "Astana",
        distractors: ["Almata", "Biškekas", "Taškentas", "Baku", "Samarkandas"],
        explanation: "Astana yra sostinė nuo 1997 metų.",
      },
    },
  },
  {
    id: "geo_ek_002",
    category: "geo",
    subTheme: "capitals",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "World capitals (Bhutan)",
    emoji: "🇧🇹",
    translations: {
      en: {
        question: "What is the capital of Bhutan?",
        correct: "Thimphu",
        distractors: ["Kathmandu", "Dhaka", "Colombo", "Malé", "Naypyidaw"],
        explanation: "Thimphu is the capital of Bhutan in the Himalayas.",
      },
      lt: {
        question: "Kokia Butano sostinė?",
        correct: "Thimphu",
        distractors: ["Katmandu", "Daka", "Kolombas", "Malė", "Neipidas"],
        explanation: "Thimphu — Butano sostinė Himalajuose.",
      },
    },
  },
  {
    id: "geo_ek_003",
    category: "geo",
    subTheme: "capitals",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "World capitals (Mongolia)",
    emoji: "🇲🇳",
    translations: {
      en: {
        question: "What is the capital of Mongolia?",
        correct: "Ulaanbaatar",
        distractors: ["Astana", "Beijing", "Tashkent", "Bishkek", "Lhasa"],
        explanation: "Ulaanbaatar is the coldest capital city on average.",
      },
      lt: {
        question: "Kokia Mongolijos sostinė?",
        correct: "Ulan Batoras",
        distractors: ["Astana", "Pekinas", "Taškentas", "Biškekas", "Lasa"],
        explanation: "Ulan Batoras — vidutiniškai šalčiausia pasaulio sostinė.",
      },
    },
  },
  {
    id: "geo_ek_004",
    category: "geo",
    subTheme: "mountains",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography (Kilimanjaro in Tanzania)",
    emoji: "🇹🇿",
    translations: {
      en: {
        question: "In which country is Mount Kilimanjaro?",
        correct: "Tanzania",
        distractors: ["Kenya", "Uganda", "Ethiopia", "Morocco", "Egypt"],
        explanation: "Kilimanjaro is the highest mountain in Africa, in Tanzania.",
      },
      lt: {
        question: "Kurioje šalyje yra Kilimandžaro kalnas?",
        correct: "Tanzanija",
        distractors: ["Kenija", "Uganda", "Etiopija", "Marokas", "Egiptas"],
        explanation: "Kilimandžaras — aukščiausias Afrikos kalnas, Tanzanijoje.",
      },
    },
  },
  {
    id: "geo_ek_005",
    category: "geo",
    subTheme: "rivers",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography (Amazon rainforest, Brazil)",
    emoji: "🌳",
    translations: {
      en: {
        question: "The Amazon rainforest is mostly in which country?",
        correct: "Brazil",
        distractors: ["Peru", "Colombia", "Venezuela", "Bolivia", "Ecuador"],
        explanation: "About 60% of the Amazon rainforest is in Brazil.",
      },
      lt: {
        question: "Kurioje šalyje yra didžioji Amazonės miškų dalis?",
        correct: "Brazilija",
        distractors: ["Peru", "Kolumbija", "Venesuela", "Bolivija", "Ekvadoras"],
        explanation: "Apie 60% Amazonės atogrąžų miškų yra Brazilijoje.",
      },
    },
  },
  {
    id: "geo_ek_006",
    category: "geo",
    subTheme: "records",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography (longest coastline, Canada)",
    emoji: "🏖️",
    translations: {
      en: {
        question: "Which country has the longest coastline?",
        correct: "Canada",
        distractors: ["Russia", "Australia", "USA", "Indonesia", "Norway"],
        explanation: "Canada has the longest coastline of any country.",
      },
      lt: {
        question: "Kuri šalis turi ilgiausią pakrantę?",
        correct: "Kanada",
        distractors: ["Rusija", "Australija", "JAV", "Indonezija", "Norvegija"],
        explanation: "Kanada turi ilgiausią pakrantę pasaulyje.",
      },
    },
  },
  {
    id: "geo_ek_007",
    category: "geo",
    subTheme: "capitals",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "World capitals (Iran)",
    emoji: "🇮🇷",
    translations: {
      en: {
        question: "What is the capital of Iran?",
        correct: "Tehran",
        distractors: ["Baghdad", "Riyadh", "Kabul", "Ankara", "Dubai"],
        explanation: "Tehran is the capital and largest city of Iran.",
      },
      lt: {
        question: "Kokia Irano sostinė?",
        correct: "Teheranas",
        distractors: ["Bagdadas", "Rijadas", "Kabulas", "Ankara", "Dubajus"],
        explanation: "Teheranas — Irano sostinė ir didžiausias miestas.",
      },
    },
  },
  {
    id: "geo_ek_008",
    category: "geo",
    subTheme: "records",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography (Lake Baikal, Russia)",
    emoji: "💧",
    translations: {
      en: {
        question: "In which country is Lake Baikal, the deepest lake?",
        correct: "Russia",
        distractors: ["Mongolia", "China", "Kazakhstan", "Canada", "Switzerland"],
        explanation: "Lake Baikal in Russia is the world's deepest lake.",
      },
      lt: {
        question: "Kurioje šalyje yra giliausias ežeras Baikalas?",
        correct: "Rusija",
        distractors: ["Mongolija", "Kinija", "Kazachstanas", "Kanada", "Šveicarija"],
        explanation: "Baikalas Rusijoje — giliausias pasaulio ežeras.",
      },
    },
  },
  {
    id: "geo_ek_009",
    category: "geo",
    subTheme: "capitals",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "World capitals (Peru)",
    emoji: "🦙",
    translations: {
      en: {
        question: "What is the capital of Peru?",
        correct: "Lima",
        distractors: ["Cusco", "Quito", "La Paz", "Bogotá", "Santiago"],
        explanation: "Lima is the capital and largest city of Peru.",
      },
      lt: {
        question: "Kokia Peru sostinė?",
        correct: "Lima",
        distractors: ["Kuskas", "Kitas", "La Pasas", "Bogota", "Santjagas"],
        explanation: "Lima — Peru sostinė ir didžiausias miestas.",
      },
    },
  },
  {
    id: "geo_ek_010",
    category: "geo",
    subTheme: "capitals",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "World capitals (Vietnam)",
    emoji: "🇻🇳",
    translations: {
      en: {
        question: "What is the capital of Vietnam?",
        correct: "Hanoi",
        distractors: [
          "Ho Chi Minh City",
          "Bangkok",
          "Phnom Penh",
          "Vientiane",
          "Manila",
        ],
        explanation: "Hanoi is the capital of Vietnam in the north.",
      },
      lt: {
        question: "Kokia Vietnamo sostinė?",
        correct: "Hanojus",
        distractors: [
          "Hošiminas",
          "Bankokas",
          "Pnompenis",
          "Vientianas",
          "Manila",
        ],
        explanation: "Hanojus — Vietnamo sostinė šiaurėje.",
      },
    },
  },
  {
    id: "geo_ek_011",
    category: "geo",
    subTheme: "seas",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography (Nile to Mediterranean)",
    emoji: "🧭",
    translations: {
      en: {
        question: "Into which sea does the Nile flow?",
        correct: "Mediterranean Sea",
        distractors: [
          "Red Sea",
          "Black Sea",
          "Arabian Sea",
          "Caspian Sea",
          "Dead Sea",
        ],
        explanation: "The Nile empties into the Mediterranean Sea.",
      },
      lt: {
        question: "Į kurią jūrą įteka Nilas?",
        correct: "Viduržemio jūra",
        distractors: [
          "Raudonoji jūra",
          "Juodoji jūra",
          "Arabijos jūra",
          "Kaspijos jūra",
          "Negyvoji jūra",
        ],
        explanation: "Nilas įteka į Viduržemio jūrą.",
      },
    },
  },
  {
    id: "geo_ek_012",
    category: "geo",
    subTheme: "mountains",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography (Mont Blanc in the Alps)",
    emoji: "🗻",
    translations: {
      en: {
        question: "Mont Blanc is the highest peak of which range?",
        correct: "Alps",
        distractors: ["Pyrenees", "Andes", "Carpathians", "Urals", "Caucasus"],
        explanation: "Mont Blanc is the highest mountain in the Alps.",
      },
      lt: {
        question: "Monblanas yra aukščiausia kurių kalnų viršūnė?",
        correct: "Alpės",
        distractors: ["Pirėnai", "Andai", "Karpatai", "Uralas", "Kaukazas"],
        explanation: "Monblanas — aukščiausias Alpių kalnas.",
      },
    },
  },
  {
    id: "geo_ek_013",
    category: "geo",
    subTheme: "records",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography (Great Barrier Reef, Australia)",
    emoji: "🐠",
    translations: {
      en: {
        question: "The Great Barrier Reef lies near which country?",
        correct: "Australia",
        distractors: ["Brazil", "Mexico", "Egypt", "India", "Greece"],
        explanation: "The Great Barrier Reef is off the coast of Australia.",
      },
      lt: {
        question: "Prie kurios šalies yra Didysis Barjerinis rifas?",
        correct: "Australija",
        distractors: ["Brazilija", "Meksika", "Egiptas", "Indija", "Graikija"],
        explanation: "Didysis Barjerinis rifas yra prie Australijos krantų.",
      },
    },
  },
  {
    id: "geo_ek_014",
    category: "geo",
    subTheme: "capitals",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "World capitals (Cuba)",
    emoji: "🇨🇺",
    translations: {
      en: {
        question: "What is the capital of Cuba?",
        correct: "Havana",
        distractors: [
          "Santiago",
          "Kingston",
          "San Juan",
          "Nassau",
          "Santo Domingo",
        ],
        explanation: "Havana is the capital and largest city of Cuba.",
      },
      lt: {
        question: "Kokia Kubos sostinė?",
        correct: "Havana",
        distractors: [
          "Santjagas",
          "Kingstonas",
          "San Chuanas",
          "Nasau",
          "Santo Domingas",
        ],
        explanation: "Havana — Kubos sostinė ir didžiausias miestas.",
      },
    },
  },
  {
    id: "geo_ek_015",
    category: "geo",
    subTheme: "seas",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography (Strait of Gibraltar)",
    emoji: "🚢",
    translations: {
      en: {
        question: "Which strait separates Europe and Africa?",
        correct: "Strait of Gibraltar",
        distractors: [
          "Bosphorus",
          "Suez Canal",
          "Bering Strait",
          "Dardanelles",
          "Panama Canal",
        ],
        explanation: "The Strait of Gibraltar lies between Spain and Morocco.",
      },
      lt: {
        question: "Kuris sąsiauris skiria Europą ir Afriką?",
        correct: "Gibraltaro sąsiauris",
        distractors: [
          "Bosforas",
          "Sueco kanalas",
          "Beringo sąsiauris",
          "Dardanelai",
          "Panamos kanalas",
        ],
        explanation: "Gibraltaro sąsiauris yra tarp Ispanijos ir Maroko.",
      },
    },
  },
];
