/**
 * geoContent — „Geografija ir pasaulis” trivijos klausimai (EN + LT).
 *
 * Po 15 klausimų kiekvienam lygiui (lengvas/vidutinis/sunkus/ekstremalus) = 60.
 * Temos: sostinės, žemynai, vandenynai, kalnai, upės, šalys, rekordai.
 *
 * TAISYKLĖS (Manifestas):
 *   - 1 teisingas + 5 distractors; visi 6 variantai VISOSE kalbose ≤46 simbolių;
 *   - faktai 100% patikrinti (sourceVerified); neutralu (jokios politikos/religijos);
 *   - LT vidinės kabutės tik „..." (ne ASCII "); detalės — į explanation, ne į variantą.
 *
 * Formatas — žr. triviaTypes.ts (TriviaQuestion). category visada "geo".
 */

import { TriviaQuestion } from "./triviaTypes";

export const GEO_QUESTIONS: TriviaQuestion[] = [
  // ======================= LENGVAS (Easy) =======================
  {
    id: "geo_le_001",
    category: "geo",
    subTheme: "capitals",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "World capitals (encyclopedic)",
    emoji: "🗼",
    translations: {
      en: {
        question: "What is the capital of France?",
        correct: "Paris",
        distractors: ["London", "Berlin", "Madrid", "Rome", "Lisbon"],
        explanation: "Paris has been the capital of France for centuries.",
      },
      lt: {
        question: "Kokia Prancūzijos sostinė?",
        correct: "Paryžius",
        distractors: ["Londonas", "Berlynas", "Madridas", "Roma", "Lisabona"],
        explanation: "Paryžius jau šimtmečius yra Prancūzijos sostinė.",
      },
    },
  },
  {
    id: "geo_le_002",
    category: "geo",
    subTheme: "oceans",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Oceanography (largest ocean)",
    emoji: "🌊",
    translations: {
      en: {
        question: "What is the largest ocean on Earth?",
        correct: "Pacific Ocean",
        distractors: [
          "Atlantic Ocean",
          "Indian Ocean",
          "Arctic Ocean",
          "Southern Ocean",
          "Mediterranean Sea",
        ],
        explanation: "The Pacific Ocean is the largest and deepest ocean.",
      },
      lt: {
        question: "Koks didžiausias Žemės vandenynas?",
        correct: "Ramusis vandenynas",
        distractors: [
          "Atlanto vandenynas",
          "Indijos vandenynas",
          "Arkties vandenynas",
          "Pietų vandenynas",
          "Viduržemio jūra",
        ],
        explanation: "Ramusis vandenynas yra didžiausias ir giliausias.",
      },
    },
  },
  {
    id: "geo_le_003",
    category: "geo",
    subTheme: "continents",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography (continents)",
    emoji: "🌍",
    translations: {
      en: {
        question: "How many continents are there on Earth?",
        correct: "7",
        distractors: ["5", "6", "8", "4", "9"],
        explanation: "The seven continents include Asia, Africa and Europe.",
      },
      lt: {
        question: "Kiek žemynų yra Žemėje?",
        correct: "7",
        distractors: ["5", "6", "8", "4", "9"],
        explanation: "Septyni žemynai: Azija, Afrika, Europa ir kiti.",
      },
    },
  },
  {
    id: "geo_le_004",
    category: "geo",
    subTheme: "capitals",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "World capitals (Japan)",
    emoji: "🇯🇵",
    translations: {
      en: {
        question: "What is the capital of Japan?",
        correct: "Tokyo",
        distractors: ["Kyoto", "Osaka", "Seoul", "Beijing", "Bangkok"],
        explanation: "Tokyo is Japan's capital and largest city.",
      },
      lt: {
        question: "Kokia Japonijos sostinė?",
        correct: "Tokijas",
        distractors: ["Kiotas", "Osaka", "Seulas", "Pekinas", "Bankokas"],
        explanation: "Tokijas — Japonijos sostinė ir didžiausias miestas.",
      },
    },
  },
  {
    id: "geo_le_005",
    category: "geo",
    subTheme: "capitals",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "World capitals (Italy)",
    emoji: "🇮🇹",
    translations: {
      en: {
        question: "What is the capital of Italy?",
        correct: "Rome",
        distractors: ["Milan", "Venice", "Naples", "Florence", "Turin"],
        explanation: "Rome is the capital of Italy and home to the Colosseum.",
      },
      lt: {
        question: "Kokia Italijos sostinė?",
        correct: "Roma",
        distractors: ["Milanas", "Venecija", "Neapolis", "Florencija", "Turinas"],
        explanation: "Roma — Italijos sostinė, garsėjanti Koliziejumi.",
      },
    },
  },
  {
    id: "geo_le_006",
    category: "geo",
    subTheme: "continents",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography (Egypt location)",
    emoji: "🐫",
    translations: {
      en: {
        question: "On which continent is Egypt located?",
        correct: "Africa",
        distractors: [
          "Asia",
          "Europe",
          "South America",
          "Australia",
          "Antarctica",
        ],
        explanation: "Egypt is in the north-east of Africa.",
      },
      lt: {
        question: "Kuriame žemyne yra Egiptas?",
        correct: "Afrika",
        distractors: [
          "Azija",
          "Europa",
          "Pietų Amerika",
          "Australija",
          "Antarktida",
        ],
        explanation: "Egiptas yra šiaurės rytų Afrikoje.",
      },
    },
  },
  {
    id: "geo_le_007",
    category: "geo",
    subTheme: "continents",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography (largest continent)",
    emoji: "🗺️",
    translations: {
      en: {
        question: "What is the largest continent by area?",
        correct: "Asia",
        distractors: [
          "Africa",
          "Europe",
          "North America",
          "Antarctica",
          "Australia",
        ],
        explanation: "Asia is the largest continent and the most populated.",
      },
      lt: {
        question: "Koks didžiausias žemynas pagal plotą?",
        correct: "Azija",
        distractors: [
          "Afrika",
          "Europa",
          "Šiaurės Amerika",
          "Antarktida",
          "Australija",
        ],
        explanation: "Azija — didžiausias ir daugiausiai gyventojų turintis žemynas.",
      },
    },
  },
  {
    id: "geo_le_008",
    category: "geo",
    subTheme: "capitals",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "World capitals (United Kingdom)",
    emoji: "🇬🇧",
    translations: {
      en: {
        question: "What is the capital of the United Kingdom?",
        correct: "London",
        distractors: [
          "Manchester",
          "Liverpool",
          "Dublin",
          "Edinburgh",
          "Birmingham",
        ],
        explanation: "London is the capital of the United Kingdom.",
      },
      lt: {
        question: "Kokia Jungtinės Karalystės sostinė?",
        correct: "Londonas",
        distractors: [
          "Mančesteris",
          "Liverpulis",
          "Dublinas",
          "Edinburgas",
          "Birmingemas",
        ],
        explanation: "Londonas — Jungtinės Karalystės sostinė.",
      },
    },
  },
  {
    id: "geo_le_009",
    category: "geo",
    subTheme: "capitals",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "World capitals (Spain)",
    emoji: "🇪🇸",
    translations: {
      en: {
        question: "What is the capital of Spain?",
        correct: "Madrid",
        distractors: ["Barcelona", "Valencia", "Seville", "Lisbon", "Porto"],
        explanation: "Madrid is the capital and largest city of Spain.",
      },
      lt: {
        question: "Kokia Ispanijos sostinė?",
        correct: "Madridas",
        distractors: ["Barselona", "Valensija", "Sevilija", "Lisabona", "Portas"],
        explanation: "Madridas — Ispanijos sostinė ir didžiausias miestas.",
      },
    },
  },
  {
    id: "geo_le_010",
    category: "geo",
    subTheme: "capitals",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "World capitals (Germany)",
    emoji: "🇩🇪",
    translations: {
      en: {
        question: "What is the capital of Germany?",
        correct: "Berlin",
        distractors: ["Munich", "Hamburg", "Frankfurt", "Cologne", "Vienna"],
        explanation: "Berlin is the capital and largest city of Germany.",
      },
      lt: {
        question: "Kokia Vokietijos sostinė?",
        correct: "Berlynas",
        distractors: ["Miunchenas", "Hamburgas", "Frankfurtas", "Kelnas", "Viena"],
        explanation: "Berlynas — Vokietijos sostinė ir didžiausias miestas.",
      },
    },
  },
  {
    id: "geo_le_011",
    category: "geo",
    subTheme: "capitals",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "World capitals (Russia)",
    emoji: "🇷🇺",
    translations: {
      en: {
        question: "What is the capital of Russia?",
        correct: "Moscow",
        distractors: [
          "Saint Petersburg",
          "Novosibirsk",
          "Kazan",
          "Sochi",
          "Minsk",
        ],
        explanation: "Moscow is the capital and largest city of Russia.",
      },
      lt: {
        question: "Kokia Rusijos sostinė?",
        correct: "Maskva",
        distractors: [
          "Sankt Peterburgas",
          "Novosibirskas",
          "Kazanė",
          "Sočis",
          "Minskas",
        ],
        explanation: "Maskva — Rusijos sostinė ir didžiausias miestas.",
      },
    },
  },
  {
    id: "geo_le_012",
    category: "geo",
    subTheme: "capitals",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "World capitals (Greece)",
    emoji: "🏛️",
    translations: {
      en: {
        question: "What is the capital of Greece?",
        correct: "Athens",
        distractors: [
          "Sparta",
          "Thessaloniki",
          "Crete",
          "Rome",
          "Istanbul",
        ],
        explanation: "Athens is the capital of Greece and an ancient city.",
      },
      lt: {
        question: "Kokia Graikijos sostinė?",
        correct: "Atėnai",
        distractors: [
          "Sparta",
          "Salonikai",
          "Kreta",
          "Roma",
          "Stambulas",
        ],
        explanation: "Atėnai — Graikijos sostinė ir senovinis miestas.",
      },
    },
  },
  {
    id: "geo_le_013",
    category: "geo",
    subTheme: "capitals",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "World capitals (China)",
    emoji: "🇨🇳",
    translations: {
      en: {
        question: "What is the capital of China?",
        correct: "Beijing",
        distractors: [
          "Shanghai",
          "Hong Kong",
          "Tokyo",
          "Guangzhou",
          "Seoul",
        ],
        explanation: "Beijing is the capital of China.",
      },
      lt: {
        question: "Kokia Kinijos sostinė?",
        correct: "Pekinas",
        distractors: [
          "Šanchajus",
          "Honkongas",
          "Tokijas",
          "Guangdžou",
          "Seulas",
        ],
        explanation: "Pekinas — Kinijos sostinė.",
      },
    },
  },
  {
    id: "geo_le_014",
    category: "geo",
    subTheme: "countries",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography (Italy shape)",
    emoji: "👢",
    translations: {
      en: {
        question: "Which country is shaped like a boot?",
        correct: "Italy",
        distractors: ["Spain", "Greece", "Portugal", "France", "Turkey"],
        explanation: "Italy's peninsula looks like a boot on the map.",
      },
      lt: {
        question: "Kuri šalis žemėlapyje primena batą?",
        correct: "Italija",
        distractors: ["Ispanija", "Graikija", "Portugalija", "Prancūzija", "Turkija"],
        explanation: "Italijos pusiasalis žemėlapyje atrodo kaip batas.",
      },
    },
  },
  {
    id: "geo_le_015",
    category: "geo",
    subTheme: "capitals",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "World capitals (Lithuania)",
    emoji: "🇱🇹",
    translations: {
      en: {
        question: "What is the capital of Lithuania?",
        correct: "Vilnius",
        distractors: ["Kaunas", "Klaipėda", "Šiauliai", "Panevėžys", "Riga"],
        explanation: "Vilnius is the capital and largest city of Lithuania.",
      },
      lt: {
        question: "Kokia Lietuvos sostinė?",
        correct: "Vilnius",
        distractors: ["Kaunas", "Klaipėda", "Šiauliai", "Panevėžys", "Ryga"],
        explanation: "Vilnius — Lietuvos sostinė ir didžiausias miestas.",
      },
    },
  },

  // ======================= VIDUTINIS (Medium) =======================
  {
    id: "geo_me_001",
    category: "geo",
    subTheme: "capitals",
    level: "vidutinis",
    isTrap: true,
    sourceVerified: "World capitals (Australia)",
    emoji: "🦘",
    translations: {
      en: {
        question: "What is the capital of Australia?",
        correct: "Canberra",
        distractors: ["Sydney", "Melbourne", "Brisbane", "Perth", "Auckland"],
        explanation: "Canberra is the capital, not Sydney or Melbourne.",
      },
      lt: {
        question: "Kokia Australijos sostinė?",
        correct: "Kanbera",
        distractors: ["Sidnėjus", "Melburnas", "Brisbenas", "Pertas", "Oklandas"],
        explanation: "Sostinė yra Kanbera, ne Sidnėjus ar Melburnas.",
      },
    },
  },
  {
    id: "geo_me_002",
    category: "geo",
    subTheme: "capitals",
    level: "vidutinis",
    isTrap: true,
    sourceVerified: "World capitals (Canada)",
    emoji: "🍁",
    translations: {
      en: {
        question: "What is the capital of Canada?",
        correct: "Ottawa",
        distractors: ["Toronto", "Vancouver", "Montreal", "Quebec", "Calgary"],
        explanation: "Ottawa is the capital, not Toronto.",
      },
      lt: {
        question: "Kokia Kanados sostinė?",
        correct: "Otava",
        distractors: ["Torontas", "Vankuveris", "Monrealis", "Kvebekas", "Kalgaris"],
        explanation: "Sostinė yra Otava, ne Torontas.",
      },
    },
  },
  {
    id: "geo_me_003",
    category: "geo",
    subTheme: "mountains",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Geography (highest mountain)",
    emoji: "🏔️",
    translations: {
      en: {
        question: "What is the highest mountain in the world?",
        correct: "Mount Everest",
        distractors: ["K2", "Mont Blanc", "Kilimanjaro", "Matterhorn", "Denali"],
        explanation: "Mount Everest is about 8 849 metres tall.",
      },
      lt: {
        question: "Koks aukščiausias kalnas pasaulyje?",
        correct: "Everestas",
        distractors: ["K2", "Monblanas", "Kilimandžaras", "Matterhornas", "Denalis"],
        explanation: "Everestas yra apie 8 849 metrų aukščio.",
      },
    },
  },
  {
    id: "geo_me_004",
    category: "geo",
    subTheme: "capitals",
    level: "vidutinis",
    isTrap: true,
    sourceVerified: "World capitals (Turkey)",
    emoji: "🇹🇷",
    translations: {
      en: {
        question: "What is the capital of Turkey?",
        correct: "Ankara",
        distractors: ["Istanbul", "Izmir", "Antalya", "Bursa", "Athens"],
        explanation: "Ankara is the capital, not Istanbul.",
      },
      lt: {
        question: "Kokia Turkijos sostinė?",
        correct: "Ankara",
        distractors: ["Stambulas", "Izmiras", "Antalija", "Bursa", "Atėnai"],
        explanation: "Sostinė yra Ankara, ne Stambulas.",
      },
    },
  },
  {
    id: "geo_me_005",
    category: "geo",
    subTheme: "records",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Geography (largest country)",
    emoji: "📏",
    translations: {
      en: {
        question: "Which is the largest country by area?",
        correct: "Russia",
        distractors: ["Canada", "China", "USA", "Brazil", "Australia"],
        explanation: "Russia is the largest country, spanning two continents.",
      },
      lt: {
        question: "Kuri šalis didžiausia pagal plotą?",
        correct: "Rusija",
        distractors: ["Kanada", "Kinija", "JAV", "Brazilija", "Australija"],
        explanation: "Rusija — didžiausia šalis, besidriekianti per du žemynus.",
      },
    },
  },
  {
    id: "geo_me_006",
    category: "geo",
    subTheme: "records",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Geography (smallest country)",
    emoji: "⛪",
    translations: {
      en: {
        question: "What is the smallest country in the world?",
        correct: "Vatican City",
        distractors: ["Monaco", "San Marino", "Malta", "Liechtenstein", "Luxembourg"],
        explanation: "Vatican City is the smallest country by area.",
      },
      lt: {
        question: "Kokia mažiausia šalis pasaulyje?",
        correct: "Vatikanas",
        distractors: ["Monakas", "San Marinas", "Malta", "Lichtenšteinas", "Liuksemburgas"],
        explanation: "Vatikanas — mažiausia šalis pagal plotą.",
      },
    },
  },
  {
    id: "geo_me_007",
    category: "geo",
    subTheme: "rivers",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Geography (Nile through Egypt)",
    emoji: "🏞️",
    translations: {
      en: {
        question: "Which river flows through Egypt?",
        correct: "Nile",
        distractors: ["Amazon", "Congo", "Ganges", "Danube", "Volga"],
        explanation: "The Nile flows north through Egypt to the sea.",
      },
      lt: {
        question: "Kuri upė teka per Egiptą?",
        correct: "Nilas",
        distractors: ["Amazonė", "Kongas", "Gangas", "Dunojus", "Volga"],
        explanation: "Nilas teka per Egiptą į šiaurę, link jūros.",
      },
    },
  },
  {
    id: "geo_me_008",
    category: "geo",
    subTheme: "capitals",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "World capitals (Portugal)",
    emoji: "🇵🇹",
    translations: {
      en: {
        question: "What is the capital of Portugal?",
        correct: "Lisbon",
        distractors: ["Porto", "Madrid", "Faro", "Coimbra", "Braga"],
        explanation: "Lisbon is the capital and largest city of Portugal.",
      },
      lt: {
        question: "Kokia Portugalijos sostinė?",
        correct: "Lisabona",
        distractors: ["Portas", "Madridas", "Faras", "Koimbra", "Braga"],
        explanation: "Lisabona — Portugalijos sostinė ir didžiausias miestas.",
      },
    },
  },
  {
    id: "geo_me_009",
    category: "geo",
    subTheme: "capitals",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "World capitals (Sweden)",
    emoji: "🇸🇪",
    translations: {
      en: {
        question: "What is the capital of Sweden?",
        correct: "Stockholm",
        distractors: ["Gothenburg", "Malmö", "Oslo", "Copenhagen", "Helsinki"],
        explanation: "Stockholm is the capital of Sweden.",
      },
      lt: {
        question: "Kokia Švedijos sostinė?",
        correct: "Stokholmas",
        distractors: ["Geteborgas", "Malmė", "Oslas", "Kopenhaga", "Helsinkis"],
        explanation: "Stokholmas — Švedijos sostinė.",
      },
    },
  },
  {
    id: "geo_me_010",
    category: "geo",
    subTheme: "capitals",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "World capitals (Norway)",
    emoji: "🇳🇴",
    translations: {
      en: {
        question: "What is the capital of Norway?",
        correct: "Oslo",
        distractors: ["Bergen", "Stockholm", "Trondheim", "Helsinki", "Reykjavik"],
        explanation: "Oslo is the capital of Norway.",
      },
      lt: {
        question: "Kokia Norvegijos sostinė?",
        correct: "Oslas",
        distractors: ["Bergenas", "Stokholmas", "Trondheimas", "Helsinkis", "Reikjavikas"],
        explanation: "Oslas — Norvegijos sostinė.",
      },
    },
  },
  {
    id: "geo_me_011",
    category: "geo",
    subTheme: "capitals",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "World capitals (Poland)",
    emoji: "🇵🇱",
    translations: {
      en: {
        question: "What is the capital of Poland?",
        correct: "Warsaw",
        distractors: ["Krakow", "Gdansk", "Wroclaw", "Poznan", "Lodz"],
        explanation: "Warsaw is the capital and largest city of Poland.",
      },
      lt: {
        question: "Kokia Lenkijos sostinė?",
        correct: "Varšuva",
        distractors: ["Krokuva", "Gdanskas", "Vroclavas", "Poznanė", "Lodzė"],
        explanation: "Varšuva — Lenkijos sostinė ir didžiausias miestas.",
      },
    },
  },
  {
    id: "geo_me_012",
    category: "geo",
    subTheme: "capitals",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "World capitals (Netherlands)",
    emoji: "🌷",
    translations: {
      en: {
        question: "What is the capital of the Netherlands?",
        correct: "Amsterdam",
        distractors: ["Rotterdam", "The Hague", "Utrecht", "Brussels", "Eindhoven"],
        explanation: "Amsterdam is the capital of the Netherlands.",
      },
      lt: {
        question: "Kokia Nyderlandų sostinė?",
        correct: "Amsterdamas",
        distractors: ["Roterdamas", "Haga", "Utrechtas", "Briuselis", "Eindhovenas"],
        explanation: "Amsterdamas — Nyderlandų sostinė.",
      },
    },
  },
  {
    id: "geo_me_013",
    category: "geo",
    subTheme: "deserts",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Geography (largest hot desert)",
    emoji: "🏜️",
    translations: {
      en: {
        question: "What is the largest hot desert in the world?",
        correct: "Sahara",
        distractors: ["Gobi", "Kalahari", "Arabian", "Mojave", "Atacama"],
        explanation: "The Sahara in Africa is the largest hot desert.",
      },
      lt: {
        question: "Kokia didžiausia karštoji dykuma pasaulyje?",
        correct: "Sachara",
        distractors: ["Gobis", "Kalaharis", "Arabijos", "Modavė", "Atakama"],
        explanation: "Sachara Afrikoje — didžiausia karštoji dykuma.",
      },
    },
  },
  {
    id: "geo_me_014",
    category: "geo",
    subTheme: "capitals",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "World capitals (Egypt)",
    emoji: "🕌",
    translations: {
      en: {
        question: "What is the capital of Egypt?",
        correct: "Cairo",
        distractors: ["Alexandria", "Giza", "Luxor", "Aswan", "Rabat"],
        explanation: "Cairo is the capital and largest city of Egypt.",
      },
      lt: {
        question: "Kokia Egipto sostinė?",
        correct: "Kairas",
        distractors: ["Aleksandrija", "Giza", "Luksoras", "Asuanas", "Rabatas"],
        explanation: "Kairas — Egipto sostinė ir didžiausias miestas.",
      },
    },
  },
  {
    id: "geo_me_015",
    category: "geo",
    subTheme: "capitals",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "World capitals (Latvia)",
    emoji: "🇱🇻",
    translations: {
      en: {
        question: "What is the capital of Latvia?",
        correct: "Riga",
        distractors: ["Vilnius", "Tallinn", "Kaunas", "Minsk", "Warsaw"],
        explanation: "Riga is the capital and largest city of Latvia.",
      },
      lt: {
        question: "Kokia Latvijos sostinė?",
        correct: "Ryga",
        distractors: ["Vilnius", "Talinas", "Kaunas", "Minskas", "Varšuva"],
        explanation: "Ryga — Latvijos sostinė ir didžiausias miestas.",
      },
    },
  },

  // ======================= SUNKUS (Hard) =======================
  {
    id: "geo_su_001",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: true,
    sourceVerified: "World capitals (Switzerland)",
    emoji: "🇨🇭",
    translations: {
      en: {
        question: "What is the capital of Switzerland?",
        correct: "Bern",
        distractors: ["Zurich", "Geneva", "Basel", "Lausanne", "Lucerne"],
        explanation: "Bern is the capital, not Zurich or Geneva.",
      },
      lt: {
        question: "Kokia Šveicarijos sostinė?",
        correct: "Bernas",
        distractors: ["Ciurichas", "Ženeva", "Bazelis", "Lozana", "Liucerna"],
        explanation: "Sostinė yra Bernas, ne Ciurichas ar Ženeva.",
      },
    },
  },
  {
    id: "geo_su_002",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: true,
    sourceVerified: "World capitals (New Zealand)",
    emoji: "🥝",
    translations: {
      en: {
        question: "What is the capital of New Zealand?",
        correct: "Wellington",
        distractors: ["Auckland", "Christchurch", "Hamilton", "Dunedin", "Sydney"],
        explanation: "Wellington is the capital, not Auckland.",
      },
      lt: {
        question: "Kokia Naujosios Zelandijos sostinė?",
        correct: "Velingtonas",
        distractors: ["Oklandas", "Kraistčerčas", "Hamiltonas", "Dunedinas", "Sidnėjus"],
        explanation: "Sostinė yra Velingtonas, ne Oklandas.",
      },
    },
  },
  {
    id: "geo_su_003",
    category: "geo",
    subTheme: "records",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "UN population data (2023, India)",
    emoji: "👥",
    translations: {
      en: {
        question: "Which country has the most people today?",
        correct: "India",
        distractors: ["China", "USA", "Indonesia", "Brazil", "Russia"],
        explanation: "In 2023 India became the most populous country.",
      },
      lt: {
        question: "Kuri šalis šiandien turi daugiausiai gyventojų?",
        correct: "Indija",
        distractors: ["Kinija", "JAV", "Indonezija", "Brazilija", "Rusija"],
        explanation: "2023 m. Indija tapo daugiausiai gyventojų turinčia šalimi.",
      },
    },
  },
  {
    id: "geo_su_004",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "World capitals (Argentina)",
    emoji: "🇦🇷",
    translations: {
      en: {
        question: "What is the capital of Argentina?",
        correct: "Buenos Aires",
        distractors: ["Córdoba", "Rosario", "Santiago", "Lima", "Montevideo"],
        explanation: "Buenos Aires is the capital of Argentina.",
      },
      lt: {
        question: "Kokia Argentinos sostinė?",
        correct: "Buenos Airės",
        distractors: ["Kordoba", "Rosarijus", "Santjagas", "Lima", "Montevidėjas"],
        explanation: "Buenos Airės — Argentinos sostinė.",
      },
    },
  },
  {
    id: "geo_su_005",
    category: "geo",
    subTheme: "records",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Oceanography (Mariana Trench)",
    emoji: "🕳️",
    translations: {
      en: {
        question: "What is the deepest ocean trench?",
        correct: "Mariana Trench",
        distractors: [
          "Tonga Trench",
          "Java Trench",
          "Puerto Rico Trench",
          "Philippine Trench",
          "Kermadec Trench",
        ],
        explanation: "The Mariana Trench reaches almost 11 000 metres deep.",
      },
      lt: {
        question: "Kokia giliausia vandenyno įduba?",
        correct: "Marianų įduba",
        distractors: [
          "Tongos įduba",
          "Javos įduba",
          "Puerto Riko įduba",
          "Filipinų įduba",
          "Kermadeko įduba",
        ],
        explanation: "Marianų įduba siekia beveik 11 000 metrų gylį.",
      },
    },
  },
  {
    id: "geo_su_006",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "World capitals (Iceland)",
    emoji: "🌋",
    translations: {
      en: {
        question: "What is the capital of Iceland?",
        correct: "Reykjavik",
        distractors: ["Oslo", "Helsinki", "Bergen", "Nuuk", "Tórshavn"],
        explanation: "Reykjavik is the world's northernmost capital.",
      },
      lt: {
        question: "Kokia Islandijos sostinė?",
        correct: "Reikjavikas",
        distractors: ["Oslas", "Helsinkis", "Bergenas", "Nukas", "Tórshaunas"],
        explanation: "Reikjavikas — labiausiai į šiaurę esanti sostinė.",
      },
    },
  },
  {
    id: "geo_su_007",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "World capitals (Finland)",
    emoji: "🇫🇮",
    translations: {
      en: {
        question: "What is the capital of Finland?",
        correct: "Helsinki",
        distractors: ["Espoo", "Tampere", "Turku", "Stockholm", "Tallinn"],
        explanation: "Helsinki is the capital of Finland.",
      },
      lt: {
        question: "Kokia Suomijos sostinė?",
        correct: "Helsinkis",
        distractors: ["Espas", "Tamperė", "Turku", "Stokholmas", "Talinas"],
        explanation: "Helsinkis — Suomijos sostinė.",
      },
    },
  },
  {
    id: "geo_su_008",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: true,
    sourceVerified: "World capitals (Morocco)",
    emoji: "🇲🇦",
    translations: {
      en: {
        question: "What is the capital of Morocco?",
        correct: "Rabat",
        distractors: ["Casablanca", "Marrakech", "Fez", "Tangier", "Cairo"],
        explanation: "Rabat is the capital, not Casablanca.",
      },
      lt: {
        question: "Kokia Maroko sostinė?",
        correct: "Rabatas",
        distractors: ["Kasablanka", "Marakešas", "Fesas", "Tangeras", "Kairas"],
        explanation: "Sostinė yra Rabatas, ne Kasablanka.",
      },
    },
  },
  {
    id: "geo_su_009",
    category: "geo",
    subTheme: "records",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Geography (largest island)",
    emoji: "🧊",
    translations: {
      en: {
        question: "What is the largest island in the world?",
        correct: "Greenland",
        distractors: ["New Guinea", "Borneo", "Madagascar", "Iceland", "Australia"],
        explanation: "Greenland is the largest island (Australia is a continent).",
      },
      lt: {
        question: "Kokia didžiausia sala pasaulyje?",
        correct: "Grenlandija",
        distractors: ["Naujoji Gvinėja", "Borneo", "Madagaskaras", "Islandija", "Australija"],
        explanation: "Grenlandija — didžiausia sala (Australija yra žemynas).",
      },
    },
  },
  {
    id: "geo_su_010",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "World capitals (Thailand)",
    emoji: "🇹🇭",
    translations: {
      en: {
        question: "What is the capital of Thailand?",
        correct: "Bangkok",
        distractors: ["Phuket", "Chiang Mai", "Hanoi", "Jakarta", "Manila"],
        explanation: "Bangkok is the capital of Thailand.",
      },
      lt: {
        question: "Kokia Tailando sostinė?",
        correct: "Bankokas",
        distractors: ["Puketas", "Čiangmajus", "Hanojus", "Džakarta", "Manila"],
        explanation: "Bankokas — Tailando sostinė.",
      },
    },
  },
  {
    id: "geo_su_011",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "World capitals (Chile)",
    emoji: "🇨🇱",
    translations: {
      en: {
        question: "What is the capital of Chile?",
        correct: "Santiago",
        distractors: ["Valparaíso", "Lima", "Buenos Aires", "Bogotá", "Quito"],
        explanation: "Santiago is the capital of Chile.",
      },
      lt: {
        question: "Kokia Čilės sostinė?",
        correct: "Santjagas",
        distractors: ["Valparaisas", "Lima", "Buenos Airės", "Bogota", "Kitas"],
        explanation: "Santjagas — Čilės sostinė.",
      },
    },
  },
  {
    id: "geo_su_012",
    category: "geo",
    subTheme: "mountains",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Geography (Ural Mountains)",
    emoji: "⛰️",
    translations: {
      en: {
        question: "Which mountain range separates Europe and Asia?",
        correct: "Ural Mountains",
        distractors: ["Alps", "Andes", "Himalayas", "Caucasus", "Carpathians"],
        explanation: "The Ural Mountains form the Europe-Asia boundary.",
      },
      lt: {
        question: "Kurie kalnai skiria Europą ir Aziją?",
        correct: "Uralo kalnai",
        distractors: ["Alpės", "Andai", "Himalajai", "Kaukazas", "Karpatai"],
        explanation: "Uralo kalnai sudaro Europos ir Azijos ribą.",
      },
    },
  },
  {
    id: "geo_su_013",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "World capitals (Mexico)",
    emoji: "🇲🇽",
    translations: {
      en: {
        question: "What is the capital of Mexico?",
        correct: "Mexico City",
        distractors: ["Cancún", "Guadalajara", "Tijuana", "Lima", "Bogotá"],
        explanation: "Mexico City is the capital of Mexico.",
      },
      lt: {
        question: "Kokia Meksikos sostinė?",
        correct: "Meksikas",
        distractors: ["Kankunas", "Gvadalachara", "Tichuana", "Lima", "Bogota"],
        explanation: "Meksikas (Mexico City) — Meksikos sostinė.",
      },
    },
  },
  {
    id: "geo_su_014",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "World capitals (Ireland)",
    emoji: "☘️",
    translations: {
      en: {
        question: "What is the capital of Ireland?",
        correct: "Dublin",
        distractors: ["Belfast", "Cork", "Galway", "London", "Edinburgh"],
        explanation: "Dublin is the capital of Ireland.",
      },
      lt: {
        question: "Kokia Airijos sostinė?",
        correct: "Dublinas",
        distractors: ["Belfastas", "Korkas", "Golvėjus", "Londonas", "Edinburgas"],
        explanation: "Dublinas — Airijos sostinė.",
      },
    },
  },
  {
    id: "geo_su_015",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: true,
    sourceVerified: "Geography (capital of Brazil)",
    emoji: "🇧🇷",
    translations: {
      en: {
        question: "What is the capital of Brazil?",
        correct: "Brasília",
        distractors: [
          "Rio de Janeiro",
          "São Paulo",
          "Buenos Aires",
          "Lima",
          "Bogotá",
        ],
        explanation: "Brasília was purpose-built and became capital in 1960.",
      },
      lt: {
        question: "Kokia Brazilijos sostinė?",
        correct: "Brazilija (Brasília)",
        distractors: [
          "Rio de Žaneiras",
          "San Paulas",
          "Buenos Airės",
          "Lima",
          "Bogota",
        ],
        explanation: "Brazilija (Brasília) specialiai pastatyta ir sostine tapo 1960 m.",
      },
    },
  },

  // ======================= EKSTREMALUS (Extreme) =======================
  {
    id: "geo_ek_001",
    category: "geo",
    subTheme: "capitals",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "World capitals (Kazakhstan, Astana)",
    emoji: "🇰🇿",
    translations: {
      en: {
        question: "What is the capital of Kazakhstan?",
        correct: "Astana",
        distractors: ["Almaty", "Bishkek", "Tashkent", "Baku", "Samarkand"],
        explanation: "Astana has been the capital since 1997.",
      },
      lt: {
        question: "Kokia Kazachstano sostinė?",
        correct: "Astana",
        distractors: ["Almata", "Biškekas", "Taškentas", "Baku", "Samarkandas"],
        explanation: "Astana yra sostinė nuo 1997 metų.",
      },
    },
  },
  {
    id: "geo_ek_002",
    category: "geo",
    subTheme: "capitals",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "World capitals (Bhutan)",
    emoji: "🇧🇹",
    translations: {
      en: {
        question: "What is the capital of Bhutan?",
        correct: "Thimphu",
        distractors: ["Kathmandu", "Dhaka", "Colombo", "Malé", "Naypyidaw"],
        explanation: "Thimphu is the capital of Bhutan in the Himalayas.",
      },
      lt: {
        question: "Kokia Butano sostinė?",
        correct: "Thimphu",
        distractors: ["Katmandu", "Daka", "Kolombas", "Malė", "Neipidas"],
        explanation: "Thimphu — Butano sostinė Himalajuose.",
      },
    },
  },
  {
    id: "geo_ek_003",
    category: "geo",
    subTheme: "capitals",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "World capitals (Mongolia)",
    emoji: "🇲🇳",
    translations: {
      en: {
        question: "What is the capital of Mongolia?",
        correct: "Ulaanbaatar",
        distractors: ["Astana", "Beijing", "Tashkent", "Bishkek", "Lhasa"],
        explanation: "Ulaanbaatar is the coldest capital city on average.",
      },
      lt: {
        question: "Kokia Mongolijos sostinė?",
        correct: "Ulan Batoras",
        distractors: ["Astana", "Pekinas", "Taškentas", "Biškekas", "Lasa"],
        explanation: "Ulan Batoras — vidutiniškai šalčiausia pasaulio sostinė.",
      },
    },
  },
  {
    id: "geo_ek_004",
    category: "geo",
    subTheme: "mountains",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography (Kilimanjaro in Tanzania)",
    emoji: "🇹🇿",
    translations: {
      en: {
        question: "In which country is Mount Kilimanjaro?",
        correct: "Tanzania",
        distractors: ["Kenya", "Uganda", "Ethiopia", "Morocco", "Egypt"],
        explanation: "Kilimanjaro is the highest mountain in Africa, in Tanzania.",
      },
      lt: {
        question: "Kurioje šalyje yra Kilimandžaro kalnas?",
        correct: "Tanzanija",
        distractors: ["Kenija", "Uganda", "Etiopija", "Marokas", "Egiptas"],
        explanation: "Kilimandžaras — aukščiausias Afrikos kalnas, Tanzanijoje.",
      },
    },
  },
  {
    id: "geo_ek_005",
    category: "geo",
    subTheme: "rivers",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography (Amazon rainforest, Brazil)",
    emoji: "🌳",
    translations: {
      en: {
        question: "The Amazon rainforest is mostly in which country?",
        correct: "Brazil",
        distractors: ["Peru", "Colombia", "Venezuela", "Bolivia", "Ecuador"],
        explanation: "About 60% of the Amazon rainforest is in Brazil.",
      },
      lt: {
        question: "Kurioje šalyje yra didžioji Amazonės miškų dalis?",
        correct: "Brazilija",
        distractors: ["Peru", "Kolumbija", "Venesuela", "Bolivija", "Ekvadoras"],
        explanation: "Apie 60% Amazonės atogrąžų miškų yra Brazilijoje.",
      },
    },
  },
  {
    id: "geo_ek_006",
    category: "geo",
    subTheme: "records",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography (longest coastline, Canada)",
    emoji: "🏖️",
    translations: {
      en: {
        question: "Which country has the longest coastline?",
        correct: "Canada",
        distractors: ["Russia", "Australia", "USA", "Indonesia", "Norway"],
        explanation: "Canada has the longest coastline of any country.",
      },
      lt: {
        question: "Kuri šalis turi ilgiausią pakrantę?",
        correct: "Kanada",
        distractors: ["Rusija", "Australija", "JAV", "Indonezija", "Norvegija"],
        explanation: "Kanada turi ilgiausią pakrantę pasaulyje.",
      },
    },
  },
  {
    id: "geo_ek_007",
    category: "geo",
    subTheme: "capitals",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "World capitals (Iran)",
    emoji: "🇮🇷",
    translations: {
      en: {
        question: "What is the capital of Iran?",
        correct: "Tehran",
        distractors: ["Baghdad", "Riyadh", "Kabul", "Ankara", "Dubai"],
        explanation: "Tehran is the capital and largest city of Iran.",
      },
      lt: {
        question: "Kokia Irano sostinė?",
        correct: "Teheranas",
        distractors: ["Bagdadas", "Rijadas", "Kabulas", "Ankara", "Dubajus"],
        explanation: "Teheranas — Irano sostinė ir didžiausias miestas.",
      },
    },
  },
  {
    id: "geo_ek_008",
    category: "geo",
    subTheme: "records",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography (Lake Baikal, Russia)",
    emoji: "💧",
    translations: {
      en: {
        question: "In which country is Lake Baikal, the deepest lake?",
        correct: "Russia",
        distractors: ["Mongolia", "China", "Kazakhstan", "Canada", "Switzerland"],
        explanation: "Lake Baikal in Russia is the world's deepest lake.",
      },
      lt: {
        question: "Kurioje šalyje yra giliausias ežeras Baikalas?",
        correct: "Rusija",
        distractors: ["Mongolija", "Kinija", "Kazachstanas", "Kanada", "Šveicarija"],
        explanation: "Baikalas Rusijoje — giliausias pasaulio ežeras.",
      },
    },
  },
  {
    id: "geo_ek_009",
    category: "geo",
    subTheme: "capitals",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "World capitals (Peru)",
    emoji: "🦙",
    translations: {
      en: {
        question: "What is the capital of Peru?",
        correct: "Lima",
        distractors: ["Cusco", "Quito", "La Paz", "Bogotá", "Santiago"],
        explanation: "Lima is the capital and largest city of Peru.",
      },
      lt: {
        question: "Kokia Peru sostinė?",
        correct: "Lima",
        distractors: ["Kuskas", "Kitas", "La Pasas", "Bogota", "Santjagas"],
        explanation: "Lima — Peru sostinė ir didžiausias miestas.",
      },
    },
  },
  {
    id: "geo_ek_010",
    category: "geo",
    subTheme: "capitals",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "World capitals (Vietnam)",
    emoji: "🇻🇳",
    translations: {
      en: {
        question: "What is the capital of Vietnam?",
        correct: "Hanoi",
        distractors: [
          "Ho Chi Minh City",
          "Bangkok",
          "Phnom Penh",
          "Vientiane",
          "Manila",
        ],
        explanation: "Hanoi is the capital of Vietnam in the north.",
      },
      lt: {
        question: "Kokia Vietnamo sostinė?",
        correct: "Hanojus",
        distractors: [
          "Hošiminas",
          "Bankokas",
          "Pnompenis",
          "Vientianas",
          "Manila",
        ],
        explanation: "Hanojus — Vietnamo sostinė šiaurėje.",
      },
    },
  },
  {
    id: "geo_ek_011",
    category: "geo",
    subTheme: "seas",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography (Nile to Mediterranean)",
    emoji: "🧭",
    translations: {
      en: {
        question: "Into which sea does the Nile flow?",
        correct: "Mediterranean Sea",
        distractors: [
          "Red Sea",
          "Black Sea",
          "Arabian Sea",
          "Caspian Sea",
          "Dead Sea",
        ],
        explanation: "The Nile empties into the Mediterranean Sea.",
      },
      lt: {
        question: "Į kurią jūrą įteka Nilas?",
        correct: "Viduržemio jūra",
        distractors: [
          "Raudonoji jūra",
          "Juodoji jūra",
          "Arabijos jūra",
          "Kaspijos jūra",
          "Negyvoji jūra",
        ],
        explanation: "Nilas įteka į Viduržemio jūrą.",
      },
    },
  },
  {
    id: "geo_ek_012",
    category: "geo",
    subTheme: "mountains",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography (Mont Blanc in the Alps)",
    emoji: "🗻",
    translations: {
      en: {
        question: "Mont Blanc is the highest peak of which range?",
        correct: "Alps",
        distractors: ["Pyrenees", "Andes", "Carpathians", "Urals", "Caucasus"],
        explanation: "Mont Blanc is the highest mountain in the Alps.",
      },
      lt: {
        question: "Monblanas yra aukščiausia kurių kalnų viršūnė?",
        correct: "Alpės",
        distractors: ["Pirėnai", "Andai", "Karpatai", "Uralas", "Kaukazas"],
        explanation: "Monblanas — aukščiausias Alpių kalnas.",
      },
    },
  },
  {
    id: "geo_ek_013",
    category: "geo",
    subTheme: "records",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography (Great Barrier Reef, Australia)",
    emoji: "🐠",
    translations: {
      en: {
        question: "The Great Barrier Reef lies near which country?",
        correct: "Australia",
        distractors: ["Brazil", "Mexico", "Egypt", "India", "Greece"],
        explanation: "The Great Barrier Reef is off the coast of Australia.",
      },
      lt: {
        question: "Prie kurios šalies yra Didysis Barjerinis rifas?",
        correct: "Australija",
        distractors: ["Brazilija", "Meksika", "Egiptas", "Indija", "Graikija"],
        explanation: "Didysis Barjerinis rifas yra prie Australijos krantų.",
      },
    },
  },
  {
    id: "geo_ek_014",
    category: "geo",
    subTheme: "capitals",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "World capitals (Cuba)",
    emoji: "🇨🇺",
    translations: {
      en: {
        question: "What is the capital of Cuba?",
        correct: "Havana",
        distractors: [
          "Santiago",
          "Kingston",
          "San Juan",
          "Nassau",
          "Santo Domingo",
        ],
        explanation: "Havana is the capital and largest city of Cuba.",
      },
      lt: {
        question: "Kokia Kubos sostinė?",
        correct: "Havana",
        distractors: [
          "Santjagas",
          "Kingstonas",
          "San Chuanas",
          "Nasau",
          "Santo Domingas",
        ],
        explanation: "Havana — Kubos sostinė ir didžiausias miestas.",
      },
    },
  },
  {
    id: "geo_ek_015",
    category: "geo",
    subTheme: "seas",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography (Strait of Gibraltar)",
    emoji: "🚢",
    translations: {
      en: {
        question: "Which strait separates Europe and Africa?",
        correct: "Strait of Gibraltar",
        distractors: [
          "Bosphorus",
          "Suez Canal",
          "Bering Strait",
          "Dardanelles",
          "Panama Canal",
        ],
        explanation: "The Strait of Gibraltar lies between Spain and Morocco.",
      },
      lt: {
        question: "Kuris sąsiauris skiria Europą ir Afriką?",
        correct: "Gibraltaro sąsiauris",
        distractors: [
          "Bosforas",
          "Sueco kanalas",
          "Beringo sąsiauris",
          "Dardanelai",
          "Panamos kanalas",
        ],
        explanation: "Gibraltaro sąsiauris yra tarp Ispanijos ir Maroko.",
      },
    },
  },
  {
    id: "geo_le_016",
    category: "geo",
    subTheme: "capitals",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography (capital of the USA)",
    emoji: "🇺🇸",
    translations: {
      en: {
        question: "What is the capital of the United States?",
        correct: "Washington, D.C.",
        distractors: ["New York", "Los Angeles", "Chicago", "Boston", "Miami"],
        explanation: "Washington, D.C. is the US capital, not New York.",
      },
      lt: {
        question: "Kokia Jungtinių Valstijų sostinė?",
        correct: "Vašingtonas (D.C.)",
        distractors: ["Niujorkas", "Los Andželas", "Čikaga", "Bostonas", "Majamis"],
        explanation: "JAV sostinė yra Vašingtonas, o ne Niujorkas.",
      },
    },
  },
  {
    id: "geo_le_017",
    category: "geo",
    subTheme: "rivers",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography (River Thames in London)",
    emoji: "🌉",
    translations: {
      en: {
        question: "Which river flows through London?",
        correct: "Thames",
        distractors: ["Seine", "Danube", "Rhine", "Tiber", "Volga"],
        explanation: "The River Thames flows through London.",
      },
      lt: {
        question: "Kuri upė teka per Londoną?",
        correct: "Temzė",
        distractors: ["Sena", "Dunojus", "Reinas", "Tibras", "Volga"],
        explanation: "Per Londoną teka Temzės upė.",
      },
    },
  },
  {
    id: "geo_le_018",
    category: "geo",
    subTheme: "continents",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography (Brazil is in South America)",
    emoji: "🌎",
    translations: {
      en: {
        question: "On which continent is Brazil?",
        correct: "South America",
        distractors: ["North America", "Africa", "Asia", "Europe", "Australia"],
        explanation: "Brazil is the largest country in South America.",
      },
      lt: {
        question: "Kuriame žemyne yra Brazilija?",
        correct: "Pietų Amerika",
        distractors: ["Šiaurės Amerika", "Afrika", "Azija", "Europa", "Australija"],
        explanation: "Brazilija — didžiausia Pietų Amerikos šalis.",
      },
    },
  },
  {
    id: "geo_le_019",
    category: "geo",
    subTheme: "landmarks",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography (Eiffel Tower in France)",
    emoji: "🗼",
    translations: {
      en: {
        question: "Which country has the Eiffel Tower?",
        correct: "France",
        distractors: ["Italy", "Spain", "Germany", "Belgium", "Austria"],
        explanation: "The Eiffel Tower stands in Paris, France.",
      },
      lt: {
        question: "Kurioje šalyje yra Eifelio bokštas?",
        correct: "Prancūzija",
        distractors: ["Italija", "Ispanija", "Vokietija", "Belgija", "Austrija"],
        explanation: "Eifelio bokštas stovi Paryžiuje, Prancūzijoje.",
      },
    },
  },
  {
    id: "geo_le_020",
    category: "geo",
    subTheme: "countries",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography (Mexico borders the USA to the south)",
    emoji: "🌵",
    translations: {
      en: {
        question: "Which large country lies just south of the USA?",
        correct: "Mexico",
        distractors: ["Canada", "Brazil", "Cuba", "Peru", "Chile"],
        explanation: "Mexico shares a long border south of the USA.",
      },
      lt: {
        question: "Kuri didelė šalis yra iškart į pietus nuo JAV?",
        correct: "Meksika",
        distractors: ["Kanada", "Brazilija", "Kuba", "Peru", "Čilė"],
        explanation: "Meksika turi ilgą sieną į pietus nuo JAV.",
      },
    },
  },
  {
    id: "geo_le_021",
    category: "geo",
    subTheme: "oceans",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography (Atlantic Ocean)",
    emoji: "🌊",
    translations: {
      en: {
        question: "Which ocean lies between Europe and America?",
        correct: "Atlantic Ocean",
        distractors: [
          "Pacific Ocean",
          "Indian Ocean",
          "Arctic Ocean",
          "Southern Ocean",
          "Mediterranean Sea",
        ],
        explanation: "The Atlantic Ocean separates Europe and America.",
      },
      lt: {
        question: "Kuris vandenynas yra tarp Europos ir Amerikos?",
        correct: "Atlanto vandenynas",
        distractors: [
          "Ramusis vandenynas",
          "Indijos vandenynas",
          "Arkties vandenynas",
          "Pietų vandenynas",
          "Viduržemio jūra",
        ],
        explanation: "Europą ir Ameriką skiria Atlanto vandenynas.",
      },
    },
  },
  {
    id: "geo_le_022",
    category: "geo",
    subTheme: "landmarks",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography (Statue of Liberty in New York)",
    emoji: "🗽",
    translations: {
      en: {
        question: "In which city is the Statue of Liberty?",
        correct: "New York",
        distractors: ["Washington", "Boston", "Chicago", "Los Angeles", "Paris"],
        explanation: "The Statue of Liberty stands in New York harbor.",
      },
      lt: {
        question: "Kuriame mieste yra Laisvės statula?",
        correct: "Niujorkas",
        distractors: ["Vašingtonas", "Bostonas", "Čikaga", "Los Andželas", "Paryžius"],
        explanation: "Laisvės statula stovi Niujorko uoste.",
      },
    },
  },
  {
    id: "geo_le_023",
    category: "geo",
    subTheme: "countries",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography (kangaroos live in Australia)",
    emoji: "🦘",
    translations: {
      en: {
        question: "Which country is home to wild kangaroos?",
        correct: "Australia",
        distractors: ["Brazil", "India", "Kenya", "Canada", "Mexico"],
        explanation: "Kangaroos are native to Australia.",
      },
      lt: {
        question: "Kurioje šalyje laukinėje gamtoje gyvena kengūros?",
        correct: "Australija",
        distractors: ["Brazilija", "Indija", "Kenija", "Kanada", "Meksika"],
        explanation: "Kengūros yra kilusios iš Australijos.",
      },
    },
  },
  {
    id: "geo_le_024",
    category: "geo",
    subTheme: "continents",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography (Antarctica is the coldest continent)",
    emoji: "🧊",
    translations: {
      en: {
        question: "Which is the coldest continent?",
        correct: "Antarctica",
        distractors: ["Asia", "Europe", "North America", "Australia", "Africa"],
        explanation: "Antarctica is the coldest place on Earth.",
      },
      lt: {
        question: "Kuris žemynas yra šalčiausias?",
        correct: "Antarktida",
        distractors: ["Azija", "Europa", "Šiaurės Amerika", "Australija", "Afrika"],
        explanation: "Antarktida — šalčiausia vieta Žemėje.",
      },
    },
  },
  {
    id: "geo_le_025",
    category: "geo",
    subTheme: "mountains",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography (Everest is in the Himalayas)",
    emoji: "🏔️",
    translations: {
      en: {
        question: "Mount Everest is part of which mountain range?",
        correct: "Himalayas",
        distractors: ["Alps", "Andes", "Rockies", "Ural", "Atlas"],
        explanation: "Everest is the highest peak of the Himalayas.",
      },
      lt: {
        question: "Kuriai kalnų grandinei priklauso Everestas?",
        correct: "Himalajai",
        distractors: ["Alpės", "Andai", "Uoliniai kalnai", "Uralas", "Atlasas"],
        explanation: "Everestas — aukščiausia Himalajų viršūnė.",
      },
    },
  },
  {
    id: "geo_le_026",
    category: "geo",
    subTheme: "seas",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography (Mediterranean Sea)",
    emoji: "🏖️",
    translations: {
      en: {
        question: "Which sea lies between southern Europe and Africa?",
        correct: "Mediterranean Sea",
        distractors: [
          "Black Sea",
          "Red Sea",
          "Baltic Sea",
          "North Sea",
          "Caspian Sea",
        ],
        explanation: "The Mediterranean Sea lies south of Europe.",
      },
      lt: {
        question: "Kuri jūra yra tarp pietų Europos ir Afrikos?",
        correct: "Viduržemio jūra",
        distractors: [
          "Juodoji jūra",
          "Raudonoji jūra",
          "Baltijos jūra",
          "Šiaurės jūra",
          "Kaspijos jūra",
        ],
        explanation: "Viduržemio jūra plyti į pietus nuo Europos.",
      },
    },
  },
  {
    id: "geo_le_027",
    category: "geo",
    subTheme: "landmarks",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography (Venice is in Italy)",
    emoji: "🛶",
    translations: {
      en: {
        question: "Venice, a city of canals, is in which country?",
        correct: "Italy",
        distractors: ["France", "Spain", "Greece", "Portugal", "Austria"],
        explanation: "Venice with its canals is in Italy.",
      },
      lt: {
        question: "Venecija, kanalų miestas, yra kurioje šalyje?",
        correct: "Italija",
        distractors: ["Prancūzija", "Ispanija", "Graikija", "Portugalija", "Austrija"],
        explanation: "Venecija su kanalais yra Italijoje.",
      },
    },
  },
  {
    id: "geo_le_028",
    category: "geo",
    subTheme: "continents",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography (Australia is the smallest continent)",
    emoji: "🗺️",
    translations: {
      en: {
        question: "Which is the smallest continent?",
        correct: "Australia",
        distractors: [
          "Europe",
          "Antarctica",
          "South America",
          "North America",
          "Africa",
        ],
        explanation: "Australia is the smallest continent by area.",
      },
      lt: {
        question: "Kuris žemynas yra mažiausias?",
        correct: "Australija",
        distractors: [
          "Europa",
          "Antarktida",
          "Pietų Amerika",
          "Šiaurės Amerika",
          "Afrika",
        ],
        explanation: "Australija — mažiausias žemynas pagal plotą.",
      },
    },
  },
  {
    id: "geo_le_029",
    category: "geo",
    subTheme: "landmarks",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography (Big Ben in London)",
    emoji: "🕰️",
    translations: {
      en: {
        question: "The famous clock Big Ben is in which city?",
        correct: "London",
        distractors: ["Paris", "Rome", "Madrid", "Berlin", "Dublin"],
        explanation: "Big Ben is a famous clock tower in London.",
      },
      lt: {
        question: "Garsus laikrodis „Big Ben” yra kuriame mieste?",
        correct: "Londonas",
        distractors: ["Paryžius", "Roma", "Madridas", "Berlynas", "Dublinas"],
        explanation: "„Big Ben” — garsus laikrodžio bokštas Londone.",
      },
    },
  },
  {
    id: "geo_le_030",
    category: "geo",
    subTheme: "countries",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography (Tokyo and Osaka are in Japan)",
    emoji: "🗾",
    translations: {
      en: {
        question: "Which country has the cities Tokyo and Osaka?",
        correct: "Japan",
        distractors: ["China", "South Korea", "Thailand", "Vietnam", "India"],
        explanation: "Tokyo and Osaka are major cities of Japan.",
      },
      lt: {
        question: "Kurioje šalyje yra miestai Tokijas ir Osaka?",
        correct: "Japonija",
        distractors: ["Kinija", "Pietų Korėja", "Tailandas", "Vietnamas", "Indija"],
        explanation: "Tokijas ir Osaka — dideli Japonijos miestai.",
      },
    },
  },
  {
    id: "geo_me_016",
    category: "geo",
    subTheme: "capitals",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Geography (capital of Austria)",
    emoji: "🎻",
    translations: {
      en: {
        question: "What is the capital of Austria?",
        correct: "Vienna",
        distractors: ["Salzburg", "Zurich", "Munich", "Prague", "Budapest"],
        explanation: "Vienna is the capital of Austria.",
      },
      lt: {
        question: "Kokia Austrijos sostinė?",
        correct: "Viena",
        distractors: ["Zalcburgas", "Ciurichas", "Miunchenas", "Praha", "Budapeštas"],
        explanation: "Austrijos sostinė yra Viena.",
      },
    },
  },
  {
    id: "geo_me_017",
    category: "geo",
    subTheme: "capitals",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Geography (capital of Belgium)",
    emoji: "🧇",
    translations: {
      en: {
        question: "What is the capital of Belgium?",
        correct: "Brussels",
        distractors: ["Antwerp", "Amsterdam", "Luxembourg", "Bruges", "Ghent"],
        explanation: "Brussels is the capital of Belgium.",
      },
      lt: {
        question: "Kokia Belgijos sostinė?",
        correct: "Briuselis",
        distractors: ["Antverpenas", "Amsterdamas", "Liuksemburgas", "Briugė", "Gentas"],
        explanation: "Belgijos sostinė yra Briuselis.",
      },
    },
  },
  {
    id: "geo_me_018",
    category: "geo",
    subTheme: "capitals",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Geography (capital of Denmark)",
    emoji: "🚲",
    translations: {
      en: {
        question: "What is the capital of Denmark?",
        correct: "Copenhagen",
        distractors: ["Oslo", "Stockholm", "Helsinki", "Hamburg", "Bergen"],
        explanation: "Copenhagen is the capital of Denmark.",
      },
      lt: {
        question: "Kokia Danijos sostinė?",
        correct: "Kopenhaga",
        distractors: ["Oslas", "Stokholmas", "Helsinkis", "Hamburgas", "Bergenas"],
        explanation: "Danijos sostinė yra Kopenhaga.",
      },
    },
  },
  {
    id: "geo_me_019",
    category: "geo",
    subTheme: "rivers",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Geography (River Seine in Paris)",
    emoji: "🥐",
    translations: {
      en: {
        question: "Which river flows through Paris?",
        correct: "Seine",
        distractors: ["Loire", "Rhine", "Thames", "Danube", "Rhone"],
        explanation: "The Seine flows through the center of Paris.",
      },
      lt: {
        question: "Kuri upė teka per Paryžių?",
        correct: "Sena",
        distractors: ["Luara", "Reinas", "Temzė", "Dunojus", "Rona"],
        explanation: "Sena teka per Paryžiaus centrą.",
      },
    },
  },
  {
    id: "geo_me_020",
    category: "geo",
    subTheme: "mountains",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Geography (Andes run along South America)",
    emoji: "⛰️",
    translations: {
      en: {
        question: "The Andes mountains run along which continent?",
        correct: "South America",
        distractors: ["North America", "Africa", "Asia", "Europe", "Australia"],
        explanation: "The Andes stretch along western South America.",
      },
      lt: {
        question: "Palei kurį žemyną driekiasi Andų kalnai?",
        correct: "Pietų Amerika",
        distractors: ["Šiaurės Amerika", "Afrika", "Azija", "Europa", "Australija"],
        explanation: "Andai driekiasi palei vakarinę Pietų Ameriką.",
      },
    },
  },
  {
    id: "geo_me_021",
    category: "geo",
    subTheme: "countries",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Geography (Netherlands tulips and windmills)",
    emoji: "🌷",
    translations: {
      en: {
        question: "Which country is famous for tulips and windmills?",
        correct: "Netherlands",
        distractors: ["Belgium", "Denmark", "Germany", "Poland", "Switzerland"],
        explanation: "The Netherlands is known for tulips and windmills.",
      },
      lt: {
        question: "Kuri šalis garsi tulpėmis ir vėjo malūnais?",
        correct: "Nyderlandai",
        distractors: ["Belgija", "Danija", "Vokietija", "Lenkija", "Šveicarija"],
        explanation: "Nyderlandai garsūs tulpėmis ir vėjo malūnais.",
      },
    },
  },
  {
    id: "geo_me_022",
    category: "geo",
    subTheme: "mountains",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Geography (Mount Fuji in Japan)",
    emoji: "🗻",
    translations: {
      en: {
        question: "Mount Fuji is found in which country?",
        correct: "Japan",
        distractors: ["China", "South Korea", "Nepal", "India", "Taiwan"],
        explanation: "Mount Fuji is the highest mountain in Japan.",
      },
      lt: {
        question: "Kurioje šalyje yra Fudžio kalnas?",
        correct: "Japonija",
        distractors: ["Kinija", "Pietų Korėja", "Nepalas", "Indija", "Taivanas"],
        explanation: "Fudžis — aukščiausias Japonijos kalnas.",
      },
    },
  },
  {
    id: "geo_me_023",
    category: "geo",
    subTheme: "countries",
    level: "vidutinis",
    isTrap: true,
    sourceVerified: "Geography (Italy surrounds Vatican City)",
    emoji: "⛪",
    translations: {
      en: {
        question: "Which country surrounds Vatican City?",
        correct: "Italy",
        distractors: ["France", "Spain", "Greece", "Switzerland", "Austria"],
        explanation: "Vatican City sits entirely within Rome, Italy.",
      },
      lt: {
        question: "Kuri šalis supa Vatikaną?",
        correct: "Italija",
        distractors: ["Prancūzija", "Ispanija", "Graikija", "Šveicarija", "Austrija"],
        explanation: "Vatikanas yra Romoje, Italijoje.",
      },
    },
  },
  {
    id: "geo_me_024",
    category: "geo",
    subTheme: "landmarks",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Geography (Niagara Falls USA/Canada)",
    emoji: "💦",
    translations: {
      en: {
        question: "Niagara Falls lies between the USA and which country?",
        correct: "Canada",
        distractors: ["Mexico", "Cuba", "Brazil", "Greenland", "Iceland"],
        explanation: "Niagara Falls sits on the USA-Canada border.",
      },
      lt: {
        question: "Tarp JAV ir kurios šalies yra Niagaros krioklys?",
        correct: "Kanada",
        distractors: ["Meksika", "Kuba", "Brazilija", "Grenlandija", "Islandija"],
        explanation: "Niagaros krioklys yra prie JAV ir Kanados sienos.",
      },
    },
  },
  {
    id: "geo_me_025",
    category: "geo",
    subTheme: "capitals",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Geography (capital of South Korea)",
    emoji: "🏯",
    translations: {
      en: {
        question: "What is the capital of South Korea?",
        correct: "Seoul",
        distractors: ["Busan", "Tokyo", "Beijing", "Incheon", "Osaka"],
        explanation: "Seoul is the capital of South Korea.",
      },
      lt: {
        question: "Kokia Pietų Korėjos sostinė?",
        correct: "Seulas",
        distractors: ["Pusanas", "Tokijas", "Pekinas", "Inčchonas", "Osaka"],
        explanation: "Pietų Korėjos sostinė yra Seulas.",
      },
    },
  },
  {
    id: "geo_me_026",
    category: "geo",
    subTheme: "rivers",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Geography (Amazon River in South America)",
    emoji: "🐊",
    translations: {
      en: {
        question: "The Amazon River is mainly on which continent?",
        correct: "South America",
        distractors: ["Africa", "Asia", "North America", "Australia", "Europe"],
        explanation: "The Amazon flows across South America.",
      },
      lt: {
        question: "Kuriame žemyne daugiausia teka Amazonės upė?",
        correct: "Pietų Amerika",
        distractors: ["Afrika", "Azija", "Šiaurės Amerika", "Australija", "Europa"],
        explanation: "Amazonė teka per Pietų Ameriką.",
      },
    },
  },
  {
    id: "geo_me_027",
    category: "geo",
    subTheme: "deserts",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Geography (Gobi Desert in Asia)",
    emoji: "🏜️",
    translations: {
      en: {
        question: "Which desert covers much of Mongolia and China?",
        correct: "Gobi",
        distractors: ["Sahara", "Kalahari", "Atacama", "Mojave", "Thar"],
        explanation: "The Gobi Desert spans Mongolia and China.",
      },
      lt: {
        question: "Kuri dykuma dengia didelę Mongolijos ir Kinijos dalį?",
        correct: "Gobis",
        distractors: ["Sachara", "Kalaharis", "Atakama", "Mohavė", "Taras"],
        explanation: "Gobio dykuma driekiasi per Mongoliją ir Kiniją.",
      },
    },
  },
  {
    id: "geo_me_028",
    category: "geo",
    subTheme: "capitals",
    level: "vidutinis",
    isTrap: true,
    sourceVerified: "Geography (capital of India)",
    emoji: "🕌",
    translations: {
      en: {
        question: "What is the capital of India?",
        correct: "New Delhi",
        distractors: ["Mumbai", "Kolkata", "Bangalore", "Chennai", "Hyderabad"],
        explanation: "New Delhi is the capital, not Mumbai.",
      },
      lt: {
        question: "Kokia Indijos sostinė?",
        correct: "Naujasis Delis",
        distractors: ["Mumbajus", "Kalkuta", "Bangaloras", "Čenajus", "Haidarabadas"],
        explanation: "Indijos sostinė yra Naujasis Delis, ne Mumbajus.",
      },
    },
  },
  {
    id: "geo_me_029",
    category: "geo",
    subTheme: "countries",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Geography (Turkey spans Europe and Asia)",
    emoji: "🌉",
    translations: {
      en: {
        question: "Which country lies in both Europe and Asia, with Istanbul?",
        correct: "Turkey",
        distractors: ["Russia", "Greece", "Egypt", "Iran", "Georgia"],
        explanation: "Istanbul spans Europe and Asia in Turkey.",
      },
      lt: {
        question: "Kuri šalis su Stambulu yra ir Europoje, ir Azijoje?",
        correct: "Turkija",
        distractors: ["Rusija", "Graikija", "Egiptas", "Iranas", "Gruzija"],
        explanation: "Stambulas Turkijoje plyti Europoje ir Azijoje.",
      },
    },
  },
  {
    id: "geo_me_030",
    category: "geo",
    subTheme: "islands",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Geography (Madagascar near Africa)",
    emoji: "🦎",
    translations: {
      en: {
        question: "Which large island lies southeast of Africa?",
        correct: "Madagascar",
        distractors: ["Sri Lanka", "Cuba", "Iceland", "Cyprus", "Sicily"],
        explanation: "Madagascar lies off Africa's southeast coast.",
      },
      lt: {
        question: "Kuri didelė sala yra į pietryčius nuo Afrikos?",
        correct: "Madagaskaras",
        distractors: ["Šri Lanka", "Kuba", "Islandija", "Kipras", "Sicilija"],
        explanation: "Madagaskaras yra prie Afrikos pietryčių krantų.",
      },
    },
  },
  {
    id: "geo_su_016",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Geography (capital of Hungary)",
    emoji: "🏰",
    translations: {
      en: {
        question: "What is the capital of Hungary?",
        correct: "Budapest",
        distractors: ["Vienna", "Prague", "Bratislava", "Bucharest", "Belgrade"],
        explanation: "Budapest is the capital of Hungary.",
      },
      lt: {
        question: "Kokia Vengrijos sostinė?",
        correct: "Budapeštas",
        distractors: ["Viena", "Praha", "Bratislava", "Bukareštas", "Belgradas"],
        explanation: "Vengrijos sostinė yra Budapeštas.",
      },
    },
  },
  {
    id: "geo_su_017",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Geography (capital of Czechia)",
    emoji: "🍺",
    translations: {
      en: {
        question: "What is the capital of Czechia?",
        correct: "Prague",
        distractors: ["Vienna", "Budapest", "Warsaw", "Bratislava", "Krakow"],
        explanation: "Prague is the capital of Czechia.",
      },
      lt: {
        question: "Kokia Čekijos sostinė?",
        correct: "Praha",
        distractors: ["Viena", "Budapeštas", "Varšuva", "Bratislava", "Krokuva"],
        explanation: "Čekijos sostinė yra Praha.",
      },
    },
  },
  {
    id: "geo_su_018",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Geography (capital of Romania)",
    emoji: "🐺",
    translations: {
      en: {
        question: "What is the capital of Romania?",
        correct: "Bucharest",
        distractors: ["Sofia", "Belgrade", "Budapest", "Chisinau", "Kyiv"],
        explanation: "Bucharest is the capital of Romania.",
      },
      lt: {
        question: "Kokia Rumunijos sostinė?",
        correct: "Bukareštas",
        distractors: ["Sofija", "Belgradas", "Budapeštas", "Kišiniovas", "Kyjivas"],
        explanation: "Rumunijos sostinė yra Bukareštas.",
      },
    },
  },
  {
    id: "geo_su_019",
    category: "geo",
    subTheme: "rivers",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Geography (Amazon longest in South America)",
    emoji: "🌳",
    translations: {
      en: {
        question: "Which is the longest river in South America?",
        correct: "Amazon",
        distractors: ["Paraná", "Orinoco", "Madeira", "Uruguay", "Magdalena"],
        explanation: "The Amazon is South America's longest river.",
      },
      lt: {
        question: "Kuri ilgiausia upė Pietų Amerikoje?",
        correct: "Amazonė",
        distractors: ["Paranā", "Orinokas", "Madeira", "Urugvajus", "Magdalena"],
        explanation: "Amazonė — ilgiausia Pietų Amerikos upė.",
      },
    },
  },
  {
    id: "geo_su_020",
    category: "geo",
    subTheme: "rivers",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Geography (Volga in Russia)",
    emoji: "🚢",
    translations: {
      en: {
        question: "The Volga, Europe's longest river, is in which country?",
        correct: "Russia",
        distractors: ["Ukraine", "Poland", "Germany", "Romania", "Belarus"],
        explanation: "The Volga flows through Russia.",
      },
      lt: {
        question: "Volga, ilgiausia Europos upė, yra kurioje šalyje?",
        correct: "Rusija",
        distractors: ["Ukraina", "Lenkija", "Vokietija", "Rumunija", "Baltarusija"],
        explanation: "Volga teka per Rusiją.",
      },
    },
  },
  {
    id: "geo_su_021",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Geography (capital of Colombia)",
    emoji: "☕",
    translations: {
      en: {
        question: "What is the capital of Colombia?",
        correct: "Bogotá",
        distractors: ["Lima", "Quito", "Caracas", "Medellín", "Cali"],
        explanation: "Bogotá is the capital of Colombia.",
      },
      lt: {
        question: "Kokia Kolumbijos sostinė?",
        correct: "Bogota",
        distractors: ["Lima", "Kitas", "Karakasas", "Medeljinas", "Kalis"],
        explanation: "Kolumbijos sostinė yra Bogota.",
      },
    },
  },
  {
    id: "geo_su_022",
    category: "geo",
    subTheme: "mountains",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Geography (Pyrenees between France and Spain)",
    emoji: "🏔️",
    translations: {
      en: {
        question: "Which mountain range separates France and Spain?",
        correct: "Pyrenees",
        distractors: ["Alps", "Apennines", "Carpathians", "Atlas", "Balkans"],
        explanation: "The Pyrenees lie between France and Spain.",
      },
      lt: {
        question: "Kurie kalnai skiria Prancūziją ir Ispaniją?",
        correct: "Pirėnai",
        distractors: ["Alpės", "Apeninai", "Karpatai", "Atlasas", "Balkanai"],
        explanation: "Pirėnai yra tarp Prancūzijos ir Ispanijos.",
      },
    },
  },
  {
    id: "geo_su_023",
    category: "geo",
    subTheme: "lakes",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Geography (Lake Victoria in Africa)",
    emoji: "🐟",
    translations: {
      en: {
        question: "Lake Victoria, a huge lake, is on which continent?",
        correct: "Africa",
        distractors: ["Asia", "South America", "North America", "Europe", "Australia"],
        explanation: "Lake Victoria is the largest lake in Africa.",
      },
      lt: {
        question: "Viktorijos ežeras, didžiulis ežeras, yra kuriame žemyne?",
        correct: "Afrika",
        distractors: ["Azija", "Pietų Amerika", "Šiaurės Amerika", "Europa", "Australija"],
        explanation: "Viktorijos ežeras — didžiausias Afrikos ežeras.",
      },
    },
  },
  {
    id: "geo_su_024",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Geography (capital of Saudi Arabia)",
    emoji: "🐫",
    translations: {
      en: {
        question: "What is the capital of Saudi Arabia?",
        correct: "Riyadh",
        distractors: ["Jeddah", "Mecca", "Dubai", "Doha", "Manama"],
        explanation: "Riyadh is the capital of Saudi Arabia.",
      },
      lt: {
        question: "Kokia Saudo Arabijos sostinė?",
        correct: "Rijadas",
        distractors: ["Džida", "Meka", "Dubajus", "Doha", "Manama"],
        explanation: "Saudo Arabijos sostinė yra Rijadas.",
      },
    },
  },
  {
    id: "geo_su_025",
    category: "geo",
    subTheme: "rivers",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Geography (Danube empties into Black Sea)",
    emoji: "🌊",
    translations: {
      en: {
        question: "The Danube river flows into which sea?",
        correct: "Black Sea",
        distractors: [
          "Mediterranean Sea",
          "Caspian Sea",
          "Baltic Sea",
          "North Sea",
          "Adriatic Sea",
        ],
        explanation: "The Danube empties into the Black Sea.",
      },
      lt: {
        question: "Į kurią jūrą įteka Dunojaus upė?",
        correct: "Juodoji jūra",
        distractors: [
          "Viduržemio jūra",
          "Kaspijos jūra",
          "Baltijos jūra",
          "Šiaurės jūra",
          "Adrijos jūra",
        ],
        explanation: "Dunojus įteka į Juodąją jūrą.",
      },
    },
  },
  {
    id: "geo_su_026",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Geography (capital of the Philippines)",
    emoji: "🏝️",
    translations: {
      en: {
        question: "What is the capital of the Philippines?",
        correct: "Manila",
        distractors: ["Jakarta", "Bangkok", "Hanoi", "Cebu", "Kuala Lumpur"],
        explanation: "Manila is the capital of the Philippines.",
      },
      lt: {
        question: "Kokia Filipinų sostinė?",
        correct: "Manila",
        distractors: ["Džakarta", "Bankokas", "Hanojus", "Sebu", "Kvala Lumpūras"],
        explanation: "Filipinų sostinė yra Manila.",
      },
    },
  },
  {
    id: "geo_su_027",
    category: "geo",
    subTheme: "seas",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Geography (Bering Strait)",
    emoji: "🧭",
    translations: {
      en: {
        question: "Which strait separates Asia and North America?",
        correct: "Bering Strait",
        distractors: [
          "Strait of Gibraltar",
          "Bosphorus",
          "Strait of Malacca",
          "Strait of Hormuz",
          "Dardanelles",
        ],
        explanation: "The Bering Strait lies between Russia and Alaska.",
      },
      lt: {
        question: "Kuris sąsiauris skiria Aziją ir Šiaurės Ameriką?",
        correct: "Beringo sąsiauris",
        distractors: [
          "Gibraltaro sąsiauris",
          "Bosforas",
          "Malakos sąsiauris",
          "Ormūzo sąsiauris",
          "Dardanelai",
        ],
        explanation: "Beringo sąsiauris yra tarp Rusijos ir Aliaskos.",
      },
    },
  },
  {
    id: "geo_su_028",
    category: "geo",
    subTheme: "deserts",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Geography (Atacama Desert in Chile)",
    emoji: "🏜️",
    translations: {
      en: {
        question: "The Atacama, the driest desert, is in which country?",
        correct: "Chile",
        distractors: ["Peru", "Argentina", "Bolivia", "Mexico", "Brazil"],
        explanation: "The Atacama Desert lies in northern Chile.",
      },
      lt: {
        question: "Atakama, sausiausia dykuma, yra kurioje šalyje?",
        correct: "Čilė",
        distractors: ["Peru", "Argentina", "Bolivija", "Meksika", "Brazilija"],
        explanation: "Atakamos dykuma yra šiaurės Čilėje.",
      },
    },
  },
  {
    id: "geo_su_029",
    category: "geo",
    subTheme: "capitals",
    level: "sunkus",
    isTrap: true,
    sourceVerified: "Geography (capital of Indonesia)",
    emoji: "🛕",
    translations: {
      en: {
        question: "What is the capital of Indonesia?",
        correct: "Jakarta",
        distractors: ["Bali", "Surabaya", "Bangkok", "Manila", "Bandung"],
        explanation: "Jakarta is Indonesia's capital, not Bali.",
      },
      lt: {
        question: "Kokia Indonezijos sostinė?",
        correct: "Džakarta",
        distractors: ["Balis", "Surabaja", "Bankokas", "Manila", "Bandungas"],
        explanation: "Indonezijos sostinė yra Džakarta, ne Balis.",
      },
    },
  },
  {
    id: "geo_su_030",
    category: "geo",
    subTheme: "countries",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Geography (Norway fjords)",
    emoji: "⛵",
    translations: {
      en: {
        question: "Which country is famous for fjords on its west coast?",
        correct: "Norway",
        distractors: ["Sweden", "Finland", "Iceland", "Denmark", "Scotland"],
        explanation: "Norway's west coast is lined with fjords.",
      },
      lt: {
        question: "Kuri šalis garsi fjordais vakarinėje pakrantėje?",
        correct: "Norvegija",
        distractors: ["Švedija", "Suomija", "Islandija", "Danija", "Škotija"],
        explanation: "Norvegijos vakarų pakrantę raižo fjordai.",
      },
    },
  },
  {
    id: "geo_ek_016",
    category: "geo",
    subTheme: "capitals",
    level: "ekstremalus",
    isTrap: true,
    sourceVerified: "Geography (capital of Nigeria)",
    emoji: "🌍",
    translations: {
      en: {
        question: "What is the capital of Nigeria?",
        correct: "Abuja",
        distractors: ["Lagos", "Accra", "Nairobi", "Kano", "Ibadan"],
        explanation: "Abuja is the capital, not the bigger Lagos.",
      },
      lt: {
        question: "Kokia Nigerijos sostinė?",
        correct: "Abudža",
        distractors: ["Lagosas", "Akra", "Nairobis", "Kanas", "Ibadanas"],
        explanation: "Sostinė yra Abudža, ne didesnis Lagosas.",
      },
    },
  },
  {
    id: "geo_ek_017",
    category: "geo",
    subTheme: "capitals",
    level: "ekstremalus",
    isTrap: true,
    sourceVerified: "Geography (capital of Myanmar)",
    emoji: "🛕",
    translations: {
      en: {
        question: "What is the capital of Myanmar?",
        correct: "Naypyidaw",
        distractors: ["Yangon", "Bangkok", "Hanoi", "Mandalay", "Phnom Penh"],
        explanation: "Naypyidaw became the capital, not Yangon.",
      },
      lt: {
        question: "Kokia Mianmaro sostinė?",
        correct: "Neipidas",
        distractors: ["Jangonas", "Bankokas", "Hanojus", "Mandalajus", "Pnompenis"],
        explanation: "Sostine tapo Neipidas, ne Jangonas.",
      },
    },
  },
  {
    id: "geo_ek_018",
    category: "geo",
    subTheme: "capitals",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography (capital of Kenya)",
    emoji: "🦁",
    translations: {
      en: {
        question: "What is the capital of Kenya?",
        correct: "Nairobi",
        distractors: ["Mombasa", "Kampala", "Dar es Salaam", "Addis Ababa", "Lagos"],
        explanation: "Nairobi is the capital of Kenya.",
      },
      lt: {
        question: "Kokia Kenijos sostinė?",
        correct: "Nairobis",
        distractors: ["Mombasa", "Kampala", "Dar es Salamas", "Adis Abeba", "Lagosas"],
        explanation: "Kenijos sostinė yra Nairobis.",
      },
    },
  },
  {
    id: "geo_ek_019",
    category: "geo",
    subTheme: "lakes",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography (Lake Titicaca Peru/Bolivia)",
    emoji: "🚣",
    translations: {
      en: {
        question: "Lake Titicaca borders Peru and which country?",
        correct: "Bolivia",
        distractors: ["Chile", "Ecuador", "Brazil", "Argentina", "Paraguay"],
        explanation: "Lake Titicaca lies between Peru and Bolivia.",
      },
      lt: {
        question: "Titikakos ežeras ribojasi su Peru ir kuria šalimi?",
        correct: "Bolivija",
        distractors: ["Čilė", "Ekvadoras", "Brazilija", "Argentina", "Paragvajus"],
        explanation: "Titikakos ežeras yra tarp Peru ir Bolivijos.",
      },
    },
  },
  {
    id: "geo_ek_020",
    category: "geo",
    subTheme: "rivers",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography (Mekong delta in Vietnam)",
    emoji: "🛥️",
    translations: {
      en: {
        question: "The Mekong River reaches the sea in which country?",
        correct: "Vietnam",
        distractors: ["Thailand", "Cambodia", "Laos", "China", "Myanmar"],
        explanation: "The Mekong delta is in southern Vietnam.",
      },
      lt: {
        question: "Kurioje šalyje Mekongo upė pasiekia jūrą?",
        correct: "Vietnamas",
        distractors: ["Tailandas", "Kambodža", "Laosas", "Kinija", "Mianmaras"],
        explanation: "Mekongo delta yra pietų Vietname.",
      },
    },
  },
  {
    id: "geo_ek_021",
    category: "geo",
    subTheme: "mountains",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography (Aconcagua in Argentina)",
    emoji: "🏔️",
    translations: {
      en: {
        question: "Aconcagua, the highest peak of the Americas, is in which country?",
        correct: "Argentina",
        distractors: ["Chile", "Peru", "Bolivia", "Ecuador", "Colombia"],
        explanation: "Aconcagua stands in Argentina's Andes.",
      },
      lt: {
        question: "Akonkagva, aukščiausia Amerikų viršūnė, yra kurioje šalyje?",
        correct: "Argentina",
        distractors: ["Čilė", "Peru", "Bolivija", "Ekvadoras", "Kolumbija"],
        explanation: "Akonkagva yra Argentinos Anduose.",
      },
    },
  },
  {
    id: "geo_ek_022",
    category: "geo",
    subTheme: "capitals",
    level: "ekstremalus",
    isTrap: true,
    sourceVerified: "Geography (equator through Quito)",
    emoji: "🌐",
    translations: {
      en: {
        question: "The equator passes through which South American capital?",
        correct: "Quito",
        distractors: ["Bogotá", "Lima", "Caracas", "La Paz", "Brasília"],
        explanation: "Quito, Ecuador, sits almost on the equator.",
      },
      lt: {
        question: "Per kurią Pietų Amerikos sostinę eina pusiaujis?",
        correct: "Kitas",
        distractors: ["Bogota", "Lima", "Karakasas", "La Pasas", "Brazilija"],
        explanation: "Kitas (Ekvadoras) yra beveik ant pusiaujo.",
      },
    },
  },
  {
    id: "geo_ek_023",
    category: "geo",
    subTheme: "capitals",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography (capital of Iraq)",
    emoji: "🕌",
    translations: {
      en: {
        question: "What is the capital of Iraq?",
        correct: "Baghdad",
        distractors: ["Tehran", "Damascus", "Amman", "Riyadh", "Kuwait City"],
        explanation: "Baghdad is the capital of Iraq.",
      },
      lt: {
        question: "Kokia Irako sostinė?",
        correct: "Bagdadas",
        distractors: ["Teheranas", "Damaskas", "Amanas", "Rijadas", "Kuveitas"],
        explanation: "Irako sostinė yra Bagdadas.",
      },
    },
  },
  {
    id: "geo_ek_024",
    category: "geo",
    subTheme: "lakes",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography (Dead Sea lowest land point)",
    emoji: "🧂",
    translations: {
      en: {
        question: "Which salty lake is the lowest point on land?",
        correct: "Dead Sea",
        distractors: [
          "Caspian Sea",
          "Aral Sea",
          "Lake Baikal",
          "Great Salt Lake",
          "Lake Eyre",
        ],
        explanation: "The Dead Sea shore is Earth's lowest land point.",
      },
      lt: {
        question: "Kuris sūrus ežeras yra žemiausias sausumos taškas?",
        correct: "Negyvoji jūra",
        distractors: [
          "Kaspijos jūra",
          "Aralo jūra",
          "Baikalas",
          "Didysis Druskos ežeras",
          "Eiro ežeras",
        ],
        explanation: "Negyvosios jūros krantas — žemiausias sausumos taškas.",
      },
    },
  },
  {
    id: "geo_ek_025",
    category: "geo",
    subTheme: "mountains",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography (Ural Mountains in Russia)",
    emoji: "⛰️",
    translations: {
      en: {
        question: "The Ural Mountains run mainly through which country?",
        correct: "Russia",
        distractors: ["Kazakhstan", "Mongolia", "Ukraine", "Georgia", "Turkey"],
        explanation: "The Urals run north to south through Russia.",
      },
      lt: {
        question: "Per kurią šalį daugiausia driekiasi Uralo kalnai?",
        correct: "Rusija",
        distractors: ["Kazachstanas", "Mongolija", "Ukraina", "Gruzija", "Turkija"],
        explanation: "Uralas driekiasi per Rusiją iš šiaurės į pietus.",
      },
    },
  },
  {
    id: "geo_ek_026",
    category: "geo",
    subTheme: "capitals",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography (capital of Ethiopia)",
    emoji: "☕",
    translations: {
      en: {
        question: "What is the capital of Ethiopia?",
        correct: "Addis Ababa",
        distractors: ["Nairobi", "Khartoum", "Cairo", "Asmara", "Kampala"],
        explanation: "Addis Ababa is the capital of Ethiopia.",
      },
      lt: {
        question: "Kokia Etiopijos sostinė?",
        correct: "Adis Abeba",
        distractors: ["Nairobis", "Chartumas", "Kairas", "Asmara", "Kampala"],
        explanation: "Etiopijos sostinė yra Adis Abeba.",
      },
    },
  },
  {
    id: "geo_ek_027",
    category: "geo",
    subTheme: "islands",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography (Greenland is Danish territory)",
    emoji: "🧊",
    translations: {
      en: {
        question: "Greenland is an autonomous territory of which country?",
        correct: "Denmark",
        distractors: ["Norway", "Iceland", "Canada", "Sweden", "Finland"],
        explanation: "Greenland is an autonomous part of Denmark.",
      },
      lt: {
        question: "Grenlandija yra autonominė kurios šalies teritorija?",
        correct: "Danija",
        distractors: ["Norvegija", "Islandija", "Kanada", "Švedija", "Suomija"],
        explanation: "Grenlandija — autonominė Danijos dalis.",
      },
    },
  },
  {
    id: "geo_ek_028",
    category: "geo",
    subTheme: "lakes",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography (Caspian Sea largest lake)",
    emoji: "🌊",
    translations: {
      en: {
        question: "What is the world's largest lake by area?",
        correct: "Caspian Sea",
        distractors: [
          "Lake Superior",
          "Lake Victoria",
          "Lake Baikal",
          "Lake Michigan",
          "Aral Sea",
        ],
        explanation: "The Caspian Sea is the largest lake on Earth.",
      },
      lt: {
        question: "Koks didžiausias ežeras pasaulyje pagal plotą?",
        correct: "Kaspijos jūra",
        distractors: [
          "Aukštutinis ežeras",
          "Viktorijos ežeras",
          "Baikalas",
          "Mičigano ežeras",
          "Aralo jūra",
        ],
        explanation: "Kaspijos jūra — didžiausias Žemės ežeras.",
      },
    },
  },
  {
    id: "geo_ek_029",
    category: "geo",
    subTheme: "capitals",
    level: "ekstremalus",
    isTrap: true,
    sourceVerified: "Geography (capital of Pakistan)",
    emoji: "🕌",
    translations: {
      en: {
        question: "What is the capital of Pakistan?",
        correct: "Islamabad",
        distractors: ["Karachi", "Lahore", "Delhi", "Dhaka", "Kabul"],
        explanation: "Islamabad is the capital, not the bigger Karachi.",
      },
      lt: {
        question: "Kokia Pakistano sostinė?",
        correct: "Islamabadas",
        distractors: ["Karačis", "Lahoras", "Delis", "Daka", "Kabulas"],
        explanation: "Sostinė yra Islamabadas, ne didesnis Karačis.",
      },
    },
  },
  {
    id: "geo_ek_030",
    category: "geo",
    subTheme: "landmarks",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography (Angel Falls in Venezuela)",
    emoji: "💧",
    translations: {
      en: {
        question: "Angel Falls, the world's highest waterfall, is in which country?",
        correct: "Venezuela",
        distractors: ["Brazil", "Colombia", "Peru", "Guyana", "Ecuador"],
        explanation: "Angel Falls plunges from a plateau in Venezuela.",
      },
      lt: {
        question: "Andželo krioklys, aukščiausias pasaulyje, yra kurioje šalyje?",
        correct: "Venesuela",
        distractors: ["Brazilija", "Kolumbija", "Peru", "Gajana", "Ekvadoras"],
        explanation: "Andželo krioklys krenta nuo plokščiakalnio Venesueloje.",
      },
    },
  },
];
