/**
 * historyContent — „Istorija ir atradimai” trivijos klausimai (EN + LT).
 *
 * Po 15 klausimų kiekvienam lygiui (lengvas/vidutinis/sunkus/ekstremalus) = 60.
 * Temos: senovės civilizacijos, išradimai, atradėjai, garsūs įvykiai, mokslas.
 *
 * TAISYKLĖS (Manifestas):
 *   - 1 teisingas + 5 distractors; visi 6 variantai VISOSE kalbose ≤46 simbolių;
 *   - faktai 100% patikrinti (sourceVerified); NEUTRALU (jokios politikos/religijos);
 *   - LT vidinės kabutės tik „...” (ne ASCII); detalės — į explanation, ne į variantą.
 *
 * Formatas — žr. triviaTypes.ts (TriviaQuestion). category visada "history".
 */

import { TriviaQuestion } from "./triviaTypes";

export const HISTORY_QUESTIONS: TriviaQuestion[] = [
  // ======================= LENGVAS (Easy) =======================
  {
    id: "his_le_001",
    category: "history",
    subTheme: "space",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "NASA — Apollo 11 (1969)",
    emoji: "🚀",
    translations: {
      en: {
        question: "Who was the first person to walk on the Moon?",
        correct: "Neil Armstrong",
        distractors: [
          "Buzz Aldrin",
          "Yuri Gagarin",
          "Michael Collins",
          "John Glenn",
          "Alan Shepard",
        ],
        explanation: "Neil Armstrong stepped onto the Moon in 1969.",
      },
      lt: {
        question: "Kas pirmas vaikščiojo Mėnulyje?",
        correct: "Neil Armstrong",
        distractors: [
          "Buzz Aldrin",
          "Jurijus Gagarinas",
          "Michael Collins",
          "John Glenn",
          "Alan Shepard",
        ],
        explanation: "Neil Armstrong žengė ant Mėnulio 1969 metais.",
      },
    },
  },
  {
    id: "his_le_002",
    category: "history",
    subTheme: "ancient",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Ancient Egypt (Giza pyramids)",
    emoji: "🏜️",
    translations: {
      en: {
        question: "In which country were the Giza pyramids built?",
        correct: "Egypt",
        distractors: ["Greece", "Italy", "Mexico", "Iraq", "India"],
        explanation: "The famous pyramids stand near Cairo in Egypt.",
      },
      lt: {
        question: "Kurioje šalyje pastatytos Gizos piramidės?",
        correct: "Egiptas",
        distractors: ["Graikija", "Italija", "Meksika", "Irakas", "Indija"],
        explanation: "Garsiosios piramidės stovi prie Kairo, Egipte.",
      },
    },
  },
  {
    id: "his_le_003",
    category: "history",
    subTheme: "art",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Art history (Mona Lisa)",
    emoji: "🖼️",
    translations: {
      en: {
        question: "Who painted the Mona Lisa?",
        correct: "Leonardo da Vinci",
        distractors: ["Michelangelo", "Picasso", "Van Gogh", "Raphael", "Rembrandt"],
        explanation: "Leonardo da Vinci painted the Mona Lisa around 1503.",
      },
      lt: {
        question: "Kas nutapė Moną Lizą?",
        correct: "Leonardas da Vinčis",
        distractors: ["Mikelandželas", "Pikasas", "Van Gogas", "Rafaelis", "Rembrantas"],
        explanation: "Leonardas da Vinčis nutapė Moną Lizą apie 1503 metus.",
      },
    },
  },
  {
    id: "his_le_004",
    category: "history",
    subTheme: "events",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Titanic (1912)",
    emoji: "🚢",
    translations: {
      en: {
        question: "What did the Titanic hit before it sank?",
        correct: "An iceberg",
        distractors: ["A whale", "A rock", "A storm", "Another ship", "A reef"],
        explanation: "The Titanic struck an iceberg in 1912.",
      },
      lt: {
        question: "Į ką atsitrenkė Titanikas prieš nuskęsdamas?",
        correct: "Į ledkalnį",
        distractors: ["Į banginį", "Į uolą", "Į audrą", "Į kitą laivą", "Į rifą"],
        explanation: "Titanikas atsitrenkė į ledkalnį 1912 metais.",
      },
    },
  },
  {
    id: "his_le_005",
    category: "history",
    subTheme: "ancient",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Ancient Rome (Colosseum)",
    emoji: "🏛️",
    translations: {
      en: {
        question: "Which ancient people built the Colosseum?",
        correct: "Romans",
        distractors: ["Greeks", "Egyptians", "Vikings", "Aztecs", "Persians"],
        explanation: "The Romans built the Colosseum almost 2 000 years ago.",
      },
      lt: {
        question: "Kuri senovės tauta pastatė Koliziejų?",
        correct: "Romėnai",
        distractors: ["Graikai", "Egiptiečiai", "Vikingai", "Actekai", "Persai"],
        explanation: "Romėnai pastatė Koliziejų beveik prieš 2 000 metų.",
      },
    },
  },
  {
    id: "his_le_006",
    category: "history",
    subTheme: "people",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Literature (Shakespeare)",
    emoji: "🎭",
    translations: {
      en: {
        question: "Who wrote the play Romeo and Juliet?",
        correct: "Shakespeare",
        distractors: ["Dickens", "Tolkien", "Twain", "Homer", "Newton"],
        explanation: "William Shakespeare wrote Romeo and Juliet.",
      },
      lt: {
        question: "Kas parašė pjesę Romeo ir Džuljeta?",
        correct: "Šekspyras",
        distractors: ["Dikensas", "Tolkinas", "Tvenas", "Homeras", "Niutonas"],
        explanation: "Viljamas Šekspyras parašė Romeo ir Džuljetą.",
      },
    },
  },
  {
    id: "his_le_007",
    category: "history",
    subTheme: "inventions",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Aviation (Wright brothers, 1903)",
    emoji: "✈️",
    translations: {
      en: {
        question: "Who built the first powered airplane?",
        correct: "Wright brothers",
        distractors: ["Edison", "Ford", "Tesla", "Bell", "Marconi"],
        explanation: "The Wright brothers flew the first airplane in 1903.",
      },
      lt: {
        question: "Kas sukūrė pirmąjį variklinį lėktuvą?",
        correct: "Broliai Raitai",
        distractors: ["Edisonas", "Fordas", "Tesla", "Belas", "Markonis"],
        explanation: "Broliai Raitai pakilo pirmuoju lėktuvu 1903 metais.",
      },
    },
  },
  {
    id: "his_le_008",
    category: "history",
    subTheme: "explorers",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Age of Exploration (Columbus, 1492)",
    emoji: "⛵",
    translations: {
      en: {
        question: "Who sailed to the Americas in 1492?",
        correct: "Christopher Columbus",
        distractors: ["Magellan", "Vasco da Gama", "Marco Polo", "James Cook", "Francis Drake"],
        explanation: "Columbus reached the Americas in 1492.",
      },
      lt: {
        question: "Kas 1492 m. nuplaukė į Ameriką?",
        correct: "Kristupas Kolumbas",
        distractors: ["Magelanas", "Vaskas da Gama", "Markas Polas", "Džeimsas Kukas", "Frensis Dreikas"],
        explanation: "Kolumbas pasiekė Ameriką 1492 metais.",
      },
    },
  },
  {
    id: "his_le_009",
    category: "history",
    subTheme: "ancient",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Great Wall of China",
    emoji: "🧱",
    translations: {
      en: {
        question: "In which country is the Great Wall?",
        correct: "China",
        distractors: ["Japan", "India", "Mongolia", "Korea", "Vietnam"],
        explanation: "The Great Wall stretches across northern China.",
      },
      lt: {
        question: "Kurioje šalyje yra Didžioji siena?",
        correct: "Kinija",
        distractors: ["Japonija", "Indija", "Mongolija", "Korėja", "Vietnamas"],
        explanation: "Didžioji siena driekiasi per šiaurės Kiniją.",
      },
    },
  },
  {
    id: "his_le_010",
    category: "history",
    subTheme: "science",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Isaac Newton (gravity)",
    emoji: "🍎",
    translations: {
      en: {
        question: "Who described gravity after seeing a falling apple?",
        correct: "Isaac Newton",
        distractors: ["Einstein", "Galileo", "Darwin", "Edison", "Tesla"],
        explanation: "Isaac Newton developed the law of gravity.",
      },
      lt: {
        question: "Kas aprašė gravitaciją pamatęs krintantį obuolį?",
        correct: "Izaokas Niutonas",
        distractors: ["Einšteinas", "Galilėjus", "Darvinas", "Edisonas", "Tesla"],
        explanation: "Izaokas Niutonas suformulavo gravitacijos dėsnį.",
      },
    },
  },
  {
    id: "his_le_011",
    category: "history",
    subTheme: "ancient",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Ancient Egypt (writing)",
    emoji: "📜",
    translations: {
      en: {
        question: "How did the ancient Egyptians write?",
        correct: "Hieroglyphs",
        distractors: ["Latin letters", "Runes", "Numbers only", "Braille", "Emoji"],
        explanation: "Egyptians wrote with picture symbols called hieroglyphs.",
      },
      lt: {
        question: "Kuo rašė senovės egiptiečiai?",
        correct: "Hieroglifais",
        distractors: ["Lotynų raidėmis", "Runomis", "Tik skaičiais", "Brailio raštu", "Emoji"],
        explanation: "Egiptiečiai rašė paveikslėliais — hieroglifais.",
      },
    },
  },
  {
    id: "his_le_012",
    category: "history",
    subTheme: "medieval",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Medieval history (knights)",
    emoji: "🛡️",
    translations: {
      en: {
        question: "What did medieval knights wear in battle?",
        correct: "Armor",
        distractors: ["A toga", "A kimono", "Jeans", "A suit", "A robe"],
        explanation: "Knights wore metal armor for protection in battle.",
      },
      lt: {
        question: "Ką viduramžių riteriai vilkėdavo mūšyje?",
        correct: "Šarvus",
        distractors: ["Togą", "Kimono", "Džinsus", "Kostiumą", "Chalatą"],
        explanation: "Riteriai mūšyje vilkėjo metalinius šarvus apsaugai.",
      },
    },
  },
  {
    id: "his_le_013",
    category: "history",
    subTheme: "prehistory",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Paleontology (K-Pg extinction)",
    emoji: "🦕",
    translations: {
      en: {
        question: "Which animals died out about 66 million years ago?",
        correct: "Dinosaurs",
        distractors: ["Mammoths", "Dodos", "Sharks", "Horses", "Eagles"],
        explanation: "The big dinosaurs went extinct about 66 million years ago.",
      },
      lt: {
        question: "Kokie gyvūnai išnyko maždaug prieš 66 mln. metų?",
        correct: "Dinozaurai",
        distractors: ["Mamutai", "Dodo", "Rykliai", "Arkliai", "Ereliai"],
        explanation: "Dideli dinozaurai išnyko maždaug prieš 66 mln. metų.",
      },
    },
  },
  {
    id: "his_le_014",
    category: "history",
    subTheme: "inventions",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Thomas Edison (light bulb)",
    emoji: "💡",
    translations: {
      en: {
        question: "Who made the first practical light bulb?",
        correct: "Thomas Edison",
        distractors: ["Newton", "Einstein", "Bell", "Tesla", "Franklin"],
        explanation: "Thomas Edison made a long-lasting light bulb in 1879.",
      },
      lt: {
        question: "Kas sukūrė pirmąją praktišką elektros lemputę?",
        correct: "Tomas Edisonas",
        distractors: ["Niutonas", "Einšteinas", "Belas", "Tesla", "Franklinas"],
        explanation: "Tomas Edisonas sukūrė ilgaamžę lemputę 1879 metais.",
      },
    },
  },
  {
    id: "his_le_015",
    category: "history",
    subTheme: "ancient",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Ancient Olympics (Greece)",
    emoji: "🏅",
    translations: {
      en: {
        question: "In which ancient country did the Olympic Games begin?",
        correct: "Greece",
        distractors: ["Rome", "Egypt", "Persia", "China", "Spain"],
        explanation: "The ancient Olympic Games began in Greece.",
      },
      lt: {
        question: "Kurioje senovės šalyje prasidėjo Olimpinės žaidynės?",
        correct: "Graikija",
        distractors: ["Roma", "Egiptas", "Persija", "Kinija", "Ispanija"],
        explanation: "Senovės Olimpinės žaidynės prasidėjo Graikijoje.",
      },
    },
  },

  // ======================= VIDUTINIS (Medium) =======================
  {
    id: "his_me_001",
    category: "history",
    subTheme: "events",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "World War II (ended 1945)",
    emoji: "🕊️",
    translations: {
      en: {
        question: "In which year did World War II end?",
        correct: "1945",
        distractors: ["1939", "1918", "1950", "1944", "1941"],
        explanation: "World War II ended in 1945.",
      },
      lt: {
        question: "Kuriais metais baigėsi Antrasis pasaulinis karas?",
        correct: "1945",
        distractors: ["1939", "1918", "1950", "1944", "1941"],
        explanation: "Antrasis pasaulinis karas baigėsi 1945 metais.",
      },
    },
  },
  {
    id: "his_me_002",
    category: "history",
    subTheme: "people",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "US history (first president)",
    emoji: "🎩",
    translations: {
      en: {
        question: "Who was the first President of the United States?",
        correct: "George Washington",
        distractors: ["Abraham Lincoln", "Thomas Jefferson", "John Adams", "Benjamin Franklin", "Theodore Roosevelt"],
        explanation: "George Washington became the first US president in 1789.",
      },
      lt: {
        question: "Kas buvo pirmasis JAV prezidentas?",
        correct: "Džordžas Vašingtonas",
        distractors: ["Abraomas Linkolnas", "Tomas Džefersonas", "Džonas Adamsas", "Bendžaminas Franklinas", "Teodoras Ruzveltas"],
        explanation: "Džordžas Vašingtonas tapo pirmuoju JAV prezidentu 1789 m.",
      },
    },
  },
  {
    id: "his_me_003",
    category: "history",
    subTheme: "explorers",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Magellan expedition (first circumnavigation)",
    emoji: "🧭",
    translations: {
      en: {
        question: "Whose crew first sailed all the way around the world?",
        correct: "Magellan",
        distractors: ["Columbus", "James Cook", "Vasco da Gama", "Francis Drake", "Marco Polo"],
        explanation: "Magellan's expedition first circled the globe (1519–1522).",
      },
      lt: {
        question: "Kieno ekspedicija pirmoji apiplaukė visą pasaulį?",
        correct: "Magelano",
        distractors: ["Kolumbo", "Džeimso Kuko", "Vasko da Gamos", "Frensio Dreiko", "Marko Polo"],
        explanation: "Magelano ekspedicija pirmoji apiplaukė Žemę (1519–1522).",
      },
    },
  },
  {
    id: "his_me_004",
    category: "history",
    subTheme: "landmarks",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Eiffel Tower (1889, Paris)",
    emoji: "🗼",
    translations: {
      en: {
        question: "The Eiffel Tower was built in 1889 for a fair in which city?",
        correct: "Paris",
        distractors: ["London", "Rome", "Berlin", "Vienna", "Madrid"],
        explanation: "The Eiffel Tower was built for the 1889 Paris World's Fair.",
      },
      lt: {
        question: "Eifelio bokštas 1889 m. pastatytas parodai kuriame mieste?",
        correct: "Paryžius",
        distractors: ["Londonas", "Roma", "Berlynas", "Viena", "Madridas"],
        explanation: "Eifelio bokštas pastatytas 1889 m. Paryžiaus parodai.",
      },
    },
  },
  {
    id: "his_me_005",
    category: "history",
    subTheme: "science",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Charles Darwin (evolution)",
    emoji: "🐒",
    translations: {
      en: {
        question: "Who proposed the theory of evolution by natural selection?",
        correct: "Charles Darwin",
        distractors: ["Isaac Newton", "Gregor Mendel", "Louis Pasteur", "Albert Einstein", "Galileo"],
        explanation: "Charles Darwin published the theory of evolution in 1859.",
      },
      lt: {
        question: "Kas pasiūlė evoliucijos per natūralią atranką teoriją?",
        correct: "Čarlzas Darvinas",
        distractors: ["Izaokas Niutonas", "Gregoras Mendelis", "Lui Pastéras", "Albertas Einšteinas", "Galilėjus"],
        explanation: "Čarlzas Darvinas paskelbė evoliucijos teoriją 1859 metais.",
      },
    },
  },
  {
    id: "his_me_006",
    category: "history",
    subTheme: "inventions",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Alexander Graham Bell (telephone)",
    emoji: "☎️",
    translations: {
      en: {
        question: "Who is credited with inventing the telephone?",
        correct: "Alexander Graham Bell",
        distractors: ["Thomas Edison", "Nikola Tesla", "Samuel Morse", "Guglielmo Marconi", "Michael Faraday"],
        explanation: "Bell patented the first telephone in 1876.",
      },
      lt: {
        question: "Kam priskiriamas telefono išradimas?",
        correct: "Aleksandras Grahamas Belas",
        distractors: ["Tomas Edisonas", "Nikola Tesla", "Samuelis Morzė", "Guljelmas Markonis", "Maiklas Faradėjus"],
        explanation: "Belas užpatentavo pirmąjį telefoną 1876 metais.",
      },
    },
  },
  {
    id: "his_me_007",
    category: "history",
    subTheme: "ancient",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Julius Caesar (Roman leader)",
    emoji: "⚔️",
    translations: {
      en: {
        question: "Julius Caesar was a leader of which ancient state?",
        correct: "Rome",
        distractors: ["Greece", "Egypt", "Persia", "Carthage", "Sparta"],
        explanation: "Julius Caesar was a famous Roman general and statesman.",
      },
      lt: {
        question: "Julijus Cezaris buvo kurios senovės valstybės vadas?",
        correct: "Roma",
        distractors: ["Graikija", "Egiptas", "Persija", "Kartagina", "Sparta"],
        explanation: "Julijus Cezaris buvo garsus Romos karvedys ir valstybininkas.",
      },
    },
  },
  {
    id: "his_me_008",
    category: "history",
    subTheme: "inventions",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Gutenberg (printing press)",
    emoji: "📖",
    translations: {
      en: {
        question: "Who invented the movable-type printing press in Europe?",
        correct: "Johannes Gutenberg",
        distractors: ["Leonardo da Vinci", "Isaac Newton", "Benjamin Franklin", "Thomas Edison", "Galileo"],
        explanation: "Gutenberg's press (around 1440) spread printed books.",
      },
      lt: {
        question: "Kas Europoje išrado spaudos presą su renkamuoju šriftu?",
        correct: "Johanas Gutenbergas",
        distractors: ["Leonardas da Vinčis", "Izaokas Niutonas", "Bendžaminas Franklinas", "Tomas Edisonas", "Galilėjus"],
        explanation: "Gutenbergo presas (apie 1440) paskleidė spausdintas knygas.",
      },
    },
  },
  {
    id: "his_me_009",
    category: "history",
    subTheme: "events",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Berlin Wall fell (1989)",
    emoji: "🔨",
    translations: {
      en: {
        question: "In which year did the Berlin Wall fall?",
        correct: "1989",
        distractors: ["1991", "1985", "1979", "1990", "1995"],
        explanation: "The Berlin Wall came down in 1989.",
      },
      lt: {
        question: "Kuriais metais griuvo Berlyno siena?",
        correct: "1989",
        distractors: ["1991", "1985", "1979", "1990", "1995"],
        explanation: "Berlyno siena griuvo 1989 metais.",
      },
    },
  },
  {
    id: "his_me_010",
    category: "history",
    subTheme: "science",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Alexander Fleming (penicillin, 1928)",
    emoji: "💊",
    translations: {
      en: {
        question: "Who discovered penicillin?",
        correct: "Alexander Fleming",
        distractors: ["Louis Pasteur", "Charles Darwin", "Marie Curie", "Joseph Lister", "Robert Koch"],
        explanation: "Alexander Fleming discovered penicillin in 1928.",
      },
      lt: {
        question: "Kas atrado peniciliną?",
        correct: "Aleksandras Flemingas",
        distractors: ["Lui Pastéras", "Čarlzas Darvinas", "Marija Kiuri", "Džozefas Listeris", "Robertas Kochas"],
        explanation: "Aleksandras Flemingas atrado peniciliną 1928 metais.",
      },
    },
  },
  {
    id: "his_me_011",
    category: "history",
    subTheme: "explorers",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Mayflower (1620)",
    emoji: "🛳️",
    translations: {
      en: {
        question: "The Mayflower carried early settlers to which continent?",
        correct: "America",
        distractors: ["Australia", "Asia", "Africa", "Europe", "Antarctica"],
        explanation: "The Mayflower brought settlers to North America in 1620.",
      },
      lt: {
        question: "Mayflower laivas atgabeno naujakurius į kurį žemyną?",
        correct: "Amerika",
        distractors: ["Australija", "Azija", "Afrika", "Europa", "Antarktida"],
        explanation: "Mayflower atgabeno naujakurius į Šiaurės Ameriką 1620 m.",
      },
    },
  },
  {
    id: "his_me_012",
    category: "history",
    subTheme: "science",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Marie Curie (radioactivity)",
    emoji: "⚛️",
    translations: {
      en: {
        question: "Marie Curie won Nobel Prizes for work on what?",
        correct: "Radioactivity",
        distractors: ["Gravity", "Electricity", "Evolution", "Vaccines", "Genetics"],
        explanation: "Marie Curie's research on radioactivity won two Nobel Prizes.",
      },
      lt: {
        question: "Už ką Marija Kiuri gavo Nobelio premijas?",
        correct: "Radioaktyvumą",
        distractors: ["Gravitaciją", "Elektrą", "Evoliuciją", "Vakcinas", "Genetiką"],
        explanation: "Marijos Kiuri radioaktyvumo tyrimai pelnė dvi Nobelio premijas.",
      },
    },
  },
  {
    id: "his_me_013",
    category: "history",
    subTheme: "events",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Great Fire of London (1666)",
    emoji: "🔥",
    translations: {
      en: {
        question: "In which year was the Great Fire of London?",
        correct: "1666",
        distractors: ["1066", "1500", "1750", "1620", "1700"],
        explanation: "The Great Fire of London burned in 1666.",
      },
      lt: {
        question: "Kuriais metais kilo Didysis Londono gaisras?",
        correct: "1666",
        distractors: ["1066", "1500", "1750", "1620", "1700"],
        explanation: "Didysis Londono gaisras kilo 1666 metais.",
      },
    },
  },
  {
    id: "his_me_014",
    category: "history",
    subTheme: "ancient",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Inca (Machu Picchu)",
    emoji: "🗿",
    translations: {
      en: {
        question: "Which civilization built Machu Picchu?",
        correct: "Inca",
        distractors: ["Aztec", "Maya", "Roman", "Egyptian", "Greek"],
        explanation: "The Inca built Machu Picchu in the Andes mountains.",
      },
      lt: {
        question: "Kuri civilizacija pastatė Maču Pikčiu?",
        correct: "Inkai",
        distractors: ["Actekai", "Majai", "Romėnai", "Egiptiečiai", "Graikai"],
        explanation: "Inkai pastatė Maču Pikčiu Andų kalnuose.",
      },
    },
  },
  {
    id: "his_me_015",
    category: "history",
    subTheme: "people",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Beethoven (composer)",
    emoji: "🎼",
    translations: {
      en: {
        question: "Which composer kept writing music while going deaf?",
        correct: "Beethoven",
        distractors: ["Mozart", "Bach", "Chopin", "Vivaldi", "Haydn"],
        explanation: "Beethoven composed great works even as he lost his hearing.",
      },
      lt: {
        question: "Kuris kompozitorius kūrė muziką net kursdamas?",
        correct: "Bethovenas",
        distractors: ["Mocartas", "Bachas", "Šopenas", "Vivaldis", "Haidnas"],
        explanation: "Bethovenas kūrė puikius kūrinius net prarasdamas klausą.",
      },
    },
  },

  // ======================= SUNKUS (Hard) =======================
  {
    id: "his_su_001",
    category: "history",
    subTheme: "space",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Apollo 11 (1969)",
    emoji: "🌕",
    translations: {
      en: {
        question: "In which year did humans first land on the Moon?",
        correct: "1969",
        distractors: ["1965", "1972", "1959", "1961", "1975"],
        explanation: "Apollo 11 landed on the Moon in 1969.",
      },
      lt: {
        question: "Kuriais metais žmonės pirmą kartą nusileido Mėnulyje?",
        correct: "1969",
        distractors: ["1965", "1972", "1959", "1961", "1975"],
        explanation: "Apollo 11 nusileido Mėnulyje 1969 metais.",
      },
    },
  },
  {
    id: "his_su_002",
    category: "history",
    subTheme: "ancient",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Ancient Greek philosophy (Plato)",
    emoji: "📚",
    translations: {
      en: {
        question: "Which Greek philosopher was a student of Socrates?",
        correct: "Plato",
        distractors: ["Aristotle", "Pythagoras", "Homer", "Euclid", "Archimedes"],
        explanation: "Plato studied under Socrates and later taught Aristotle.",
      },
      lt: {
        question: "Kuris graikų filosofas buvo Sokrato mokinys?",
        correct: "Platonas",
        distractors: ["Aristotelis", "Pitagoras", "Homeras", "Euklidas", "Archimedas"],
        explanation: "Platonas mokėsi pas Sokratą, vėliau mokė Aristotelį.",
      },
    },
  },
  {
    id: "his_su_003",
    category: "history",
    subTheme: "events",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Hundred Years' War (England vs France)",
    emoji: "🏹",
    translations: {
      en: {
        question: "The Hundred Years' War was between England and which land?",
        correct: "France",
        distractors: ["Spain", "Germany", "Italy", "Scotland", "Portugal"],
        explanation: "The Hundred Years' War was between England and France.",
      },
      lt: {
        question: "Šimtametis karas vyko tarp Anglijos ir kurios šalies?",
        correct: "Prancūzija",
        distractors: ["Ispanija", "Vokietija", "Italija", "Škotija", "Portugalija"],
        explanation: "Šimtametis karas vyko tarp Anglijos ir Prancūzijos.",
      },
    },
  },
  {
    id: "his_su_004",
    category: "history",
    subTheme: "ancient",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Rosetta Stone (decoding hieroglyphs)",
    emoji: "🪨",
    translations: {
      en: {
        question: "The Rosetta Stone helped scholars decode what writing?",
        correct: "Egyptian hieroglyphs",
        distractors: ["Latin", "Greek runes", "Mayan glyphs", "Cuneiform", "Sanskrit"],
        explanation: "The Rosetta Stone unlocked the meaning of Egyptian hieroglyphs.",
      },
      lt: {
        question: "Rozetės akmuo padėjo iššifruoti kokį raštą?",
        correct: "Egipto hieroglifus",
        distractors: ["Lotynų", "Graikų runas", "Majų ženklus", "Dantiraštį", "Sanskritą"],
        explanation: "Rozetės akmuo atskleidė Egipto hieroglifų prasmę.",
      },
    },
  },
  {
    id: "his_su_005",
    category: "history",
    subTheme: "people",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Mongol Empire (Genghis Khan)",
    emoji: "🐎",
    translations: {
      en: {
        question: "Which empire was founded by Genghis Khan?",
        correct: "Mongol Empire",
        distractors: ["Roman Empire", "Ottoman Empire", "Persian Empire", "Byzantine Empire", "Mughal Empire"],
        explanation: "Genghis Khan founded the Mongol Empire around 1206.",
      },
      lt: {
        question: "Kurią imperiją įkūrė Čingischanas?",
        correct: "Mongolų imperija",
        distractors: ["Romos imperija", "Osmanų imperija", "Persų imperija", "Bizantijos imperija", "Mogolų imperija"],
        explanation: "Čingischanas įkūrė Mongolų imperiją apie 1206 metus.",
      },
    },
  },
  {
    id: "his_su_006",
    category: "history",
    subTheme: "science",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Edward Jenner (smallpox vaccine)",
    emoji: "💉",
    translations: {
      en: {
        question: "Who created the first vaccine, against smallpox?",
        correct: "Edward Jenner",
        distractors: ["Louis Pasteur", "Alexander Fleming", "Joseph Lister", "Robert Koch", "Jonas Salk"],
        explanation: "Edward Jenner made the first smallpox vaccine in 1796.",
      },
      lt: {
        question: "Kas sukūrė pirmąją vakciną nuo raupų?",
        correct: "Edvardas Dženeris",
        distractors: ["Lui Pastéras", "Aleksandras Flemingas", "Džozefas Listeris", "Robertas Kochas", "Jonas Salkas"],
        explanation: "Edvardas Dženeris sukūrė pirmąją raupų vakciną 1796 m.",
      },
    },
  },
  {
    id: "his_su_007",
    category: "history",
    subTheme: "ancient",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Lighthouse of Alexandria",
    emoji: "🌅",
    translations: {
      en: {
        question: "The ancient Lighthouse, a wonder, stood in which city?",
        correct: "Alexandria",
        distractors: ["Athens", "Rome", "Babylon", "Cairo", "Rhodes"],
        explanation: "The Lighthouse of Alexandria was a wonder of the ancient world.",
      },
      lt: {
        question: "Senovės švyturys, vienas stebuklų, stovėjo kuriame mieste?",
        correct: "Aleksandrija",
        distractors: ["Atėnai", "Roma", "Babilonas", "Kairas", "Rodas"],
        explanation: "Aleksandrijos švyturys buvo vienas senovės pasaulio stebuklų.",
      },
    },
  },
  {
    id: "his_su_008",
    category: "history",
    subTheme: "art",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Renaissance (Leonardo da Vinci era)",
    emoji: "🎨",
    translations: {
      en: {
        question: "Leonardo da Vinci lived during which period?",
        correct: "Renaissance",
        distractors: ["Middle Ages", "Stone Age", "Bronze Age", "Iron Age", "Ice Age"],
        explanation: "Leonardo da Vinci was a key figure of the Renaissance.",
      },
      lt: {
        question: "Kuriuo laikotarpiu gyveno Leonardas da Vinčis?",
        correct: "Renesansas",
        distractors: ["Viduramžiai", "Akmens amžius", "Bronzos amžius", "Geležies amžius", "Ledynmetis"],
        explanation: "Leonardas da Vinčis buvo svarbi Renesanso figūra.",
      },
    },
  },
  {
    id: "his_su_009",
    category: "history",
    subTheme: "events",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Magna Carta (1215)",
    emoji: "✍️",
    translations: {
      en: {
        question: "In which year was the Magna Carta signed in England?",
        correct: "1215",
        distractors: ["1066", "1492", "1300", "1100", "1400"],
        explanation: "The Magna Carta was sealed in 1215.",
      },
      lt: {
        question: "Kuriais metais Anglijoje patvirtinta Magna Carta?",
        correct: "1215",
        distractors: ["1066", "1492", "1300", "1100", "1400"],
        explanation: "Magna Carta patvirtinta 1215 metais.",
      },
    },
  },
  {
    id: "his_su_010",
    category: "history",
    subTheme: "people",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Cleopatra (ancient Egypt)",
    emoji: "👑",
    translations: {
      en: {
        question: "Cleopatra was a famous queen of which ancient land?",
        correct: "Egypt",
        distractors: ["Greece", "Rome", "Persia", "Babylon", "Carthage"],
        explanation: "Cleopatra was the last active ruler of ancient Egypt.",
      },
      lt: {
        question: "Kleopatra buvo garsi kurios senovės šalies karalienė?",
        correct: "Egiptas",
        distractors: ["Graikija", "Roma", "Persija", "Babilonas", "Kartagina"],
        explanation: "Kleopatra buvo paskutinė aktyvi senovės Egipto valdovė.",
      },
    },
  },
  {
    id: "his_su_011",
    category: "history",
    subTheme: "inventions",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "James Watt (steam engine improvements)",
    emoji: "⚙️",
    translations: {
      en: {
        question: "Who greatly improved the steam engine in the 1700s?",
        correct: "James Watt",
        distractors: ["Thomas Edison", "Isaac Newton", "Henry Ford", "Rudolf Diesel", "Michael Faraday"],
        explanation: "James Watt's improvements powered the Industrial Revolution.",
      },
      lt: {
        question: "Kas XVIII a. labai patobulino garo mašiną?",
        correct: "Džeimsas Vatas",
        distractors: ["Tomas Edisonas", "Izaokas Niutonas", "Henris Fordas", "Rudolfas Dyzelis", "Maiklas Faradėjus"],
        explanation: "Džeimso Vato patobulinimai paskatino pramonės revoliuciją.",
      },
    },
  },
  {
    id: "his_su_012",
    category: "history",
    subTheme: "ancient",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Aztec capital (Tenochtitlán)",
    emoji: "🦅",
    translations: {
      en: {
        question: "What was the capital of the Aztec Empire?",
        correct: "Tenochtitlán",
        distractors: ["Cusco", "Tikal", "Lima", "Bogotá", "Quito"],
        explanation: "Tenochtitlán stood where Mexico City is today.",
      },
      lt: {
        question: "Kokia buvo Actekų imperijos sostinė?",
        correct: "Tenočtitlanas",
        distractors: ["Kuskas", "Tikalis", "Lima", "Bogota", "Kitas"],
        explanation: "Tenočtitlanas stovėjo ten, kur dabar Meksikas.",
      },
    },
  },
  {
    id: "his_su_013",
    category: "history",
    subTheme: "events",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "World War I (ended 1918)",
    emoji: "🎖️",
    translations: {
      en: {
        question: "Which war ended in 1918?",
        correct: "World War I",
        distractors: ["World War II", "Cold War", "Crimean War", "Vietnam War", "Korean War"],
        explanation: "World War I ended in 1918.",
      },
      lt: {
        question: "Kuris karas baigėsi 1918 metais?",
        correct: "Pirmasis pasaulinis karas",
        distractors: ["Antrasis pasaulinis karas", "Šaltasis karas", "Krymo karas", "Vietnamo karas", "Korėjos karas"],
        explanation: "Pirmasis pasaulinis karas baigėsi 1918 metais.",
      },
    },
  },
  {
    id: "his_su_014",
    category: "history",
    subTheme: "explorers",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Vasco da Gama (sea route to India)",
    emoji: "🗺️",
    translations: {
      en: {
        question: "Vasco da Gama found a sea route from Europe to where?",
        correct: "India",
        distractors: ["China", "America", "Australia", "Japan", "Brazil"],
        explanation: "Vasco da Gama reached India by sea in 1498.",
      },
      lt: {
        question: "Vaskas da Gama atrado jūros kelią iš Europos į kur?",
        correct: "Indija",
        distractors: ["Kinija", "Amerika", "Australija", "Japonija", "Brazilija"],
        explanation: "Vaskas da Gama jūra pasiekė Indiją 1498 metais.",
      },
    },
  },
  {
    id: "his_su_015",
    category: "history",
    subTheme: "science",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Galileo (telescope astronomy)",
    emoji: "🔭",
    translations: {
      en: {
        question: "Who used a telescope to discover moons of Jupiter?",
        correct: "Galileo",
        distractors: ["Newton", "Copernicus", "Kepler", "Einstein", "Halley"],
        explanation: "Galileo discovered Jupiter's four largest moons in 1610.",
      },
      lt: {
        question: "Kas teleskopu atrado Jupiterio palydovus?",
        correct: "Galilėjus",
        distractors: ["Niutonas", "Kopernikas", "Kepleris", "Einšteinas", "Halis"],
        explanation: "Galilėjus 1610 m. atrado keturis didžiausius Jupiterio palydovus.",
      },
    },
  },

  // ======================= EKSTREMALUS (Extreme) =======================
  {
    id: "his_ek_001",
    category: "history",
    subTheme: "explorers",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Columbus (1492)",
    emoji: "🗓️",
    translations: {
      en: {
        question: "In which year did Columbus first reach the Americas?",
        correct: "1492",
        distractors: ["1498", "1500", "1488", "1455", "1510"],
        explanation: "Columbus reached the Americas in 1492.",
      },
      lt: {
        question: "Kuriais metais Kolumbas pirmą kartą pasiekė Ameriką?",
        correct: "1492",
        distractors: ["1498", "1500", "1488", "1455", "1510"],
        explanation: "Kolumbas pasiekė Ameriką 1492 metais.",
      },
    },
  },
  {
    id: "his_ek_002",
    category: "history",
    subTheme: "ancient",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Alexander the Great (Macedon)",
    emoji: "🗡️",
    translations: {
      en: {
        question: "Which Macedonian king built a vast empire by age 30?",
        correct: "Alexander the Great",
        distractors: ["Julius Caesar", "Hannibal", "Cyrus", "Darius", "Leonidas"],
        explanation: "Alexander the Great conquered from Greece to India.",
      },
      lt: {
        question: "Kuris Makedonijos karalius iki 30 metų sukūrė didžiulę imperiją?",
        correct: "Aleksandras Makedonietis",
        distractors: ["Julijus Cezaris", "Hanibalas", "Kyras", "Darijus", "Leonidas"],
        explanation: "Aleksandras Makedonietis užkariavo nuo Graikijos iki Indijos.",
      },
    },
  },
  {
    id: "his_ek_003",
    category: "history",
    subTheme: "events",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "French Revolution (began 1789)",
    emoji: "🔔",
    translations: {
      en: {
        question: "In which year did the French Revolution begin?",
        correct: "1789",
        distractors: ["1776", "1804", "1750", "1815", "1800"],
        explanation: "The French Revolution began in 1789.",
      },
      lt: {
        question: "Kuriais metais prasidėjo Prancūzijos revoliucija?",
        correct: "1789",
        distractors: ["1776", "1804", "1750", "1815", "1800"],
        explanation: "Prancūzijos revoliucija prasidėjo 1789 metais.",
      },
    },
  },
  {
    id: "his_ek_004",
    category: "history",
    subTheme: "ancient",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Qin Shi Huang (first emperor of China)",
    emoji: "🐉",
    translations: {
      en: {
        question: "Who became the first emperor of a unified China?",
        correct: "Qin Shi Huang",
        distractors: ["Kublai Khan", "Confucius", "Sun Tzu", "Han Wudi", "Wu Zetian"],
        explanation: "Qin Shi Huang unified China around 221 BC.",
      },
      lt: {
        question: "Kas tapo pirmuoju suvienytos Kinijos imperatoriumi?",
        correct: "Cin Ši Huangdi",
        distractors: ["Kublajus Chanas", "Konfucijus", "Sun Dzi", "Han Vudis", "Vu Dzetian"],
        explanation: "Cin Ši Huangdi suvienijo Kiniją apie 221 m. pr. Kr.",
      },
    },
  },
  {
    id: "his_ek_005",
    category: "history",
    subTheme: "science",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Albert Einstein (relativity)",
    emoji: "🧠",
    translations: {
      en: {
        question: "Who developed the theory of relativity?",
        correct: "Albert Einstein",
        distractors: ["Isaac Newton", "Niels Bohr", "Max Planck", "Marie Curie", "Stephen Hawking"],
        explanation: "Albert Einstein published relativity in the early 1900s.",
      },
      lt: {
        question: "Kas sukūrė reliatyvumo teoriją?",
        correct: "Albertas Einšteinas",
        distractors: ["Izaokas Niutonas", "Nilsas Boras", "Maksas Plankas", "Marija Kiuri", "Stivenas Hokingas"],
        explanation: "Albertas Einšteinas paskelbė reliatyvumo teoriją XX a. pradžioje.",
      },
    },
  },
  {
    id: "his_ek_006",
    category: "history",
    subTheme: "events",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Fall of Constantinople (1453)",
    emoji: "🏰",
    translations: {
      en: {
        question: "In which year did the Ottomans capture Constantinople?",
        correct: "1453",
        distractors: ["1492", "1517", "1400", "1500", "1066"],
        explanation: "Constantinople fell to the Ottomans in 1453.",
      },
      lt: {
        question: "Kuriais metais osmanai užėmė Konstantinopolį?",
        correct: "1453",
        distractors: ["1492", "1517", "1400", "1500", "1066"],
        explanation: "Konstantinopolis krito osmanams 1453 metais.",
      },
    },
  },
  {
    id: "his_ek_007",
    category: "history",
    subTheme: "ancient",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Sumer (Mesopotamia)",
    emoji: "🛖",
    translations: {
      en: {
        question: "The ancient Sumerians lived in which region?",
        correct: "Mesopotamia",
        distractors: ["Egypt", "Greece", "Persia", "India", "China"],
        explanation: "Sumer was one of the first civilizations, in Mesopotamia.",
      },
      lt: {
        question: "Kuriame regione gyveno senovės šumerai?",
        correct: "Mesopotamija",
        distractors: ["Egiptas", "Graikija", "Persija", "Indija", "Kinija"],
        explanation: "Šumerai — viena pirmųjų civilizacijų, Mesopotamijoje.",
      },
    },
  },
  {
    id: "his_ek_008",
    category: "history",
    subTheme: "science",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Marie Curie (first woman Nobel laureate)",
    emoji: "🏆",
    translations: {
      en: {
        question: "Who was the first woman to win a Nobel Prize?",
        correct: "Marie Curie",
        distractors: ["Rosalind Franklin", "Ada Lovelace", "Florence Nightingale", "Jane Goodall", "Lise Meitner"],
        explanation: "Marie Curie won the Nobel Prize in Physics in 1903.",
      },
      lt: {
        question: "Kas buvo pirmoji moteris, gavusi Nobelio premiją?",
        correct: "Marija Kiuri",
        distractors: ["Rozalinda Franklin", "Ada Lavleis", "Florence Nightingale", "Džeinė Gudal", "Lizė Meitner"],
        explanation: "Marija Kiuri 1903 m. gavo Nobelio fizikos premiją.",
      },
    },
  },
  {
    id: "his_ek_009",
    category: "history",
    subTheme: "inventions",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Wright brothers first flight (1903)",
    emoji: "🛩️",
    translations: {
      en: {
        question: "In which year did the Wright brothers first fly?",
        correct: "1903",
        distractors: ["1890", "1912", "1920", "1885", "1899"],
        explanation: "The first powered flight was in 1903.",
      },
      lt: {
        question: "Kuriais metais broliai Raitai pirmą kartą pakilo?",
        correct: "1903",
        distractors: ["1890", "1912", "1920", "1885", "1899"],
        explanation: "Pirmasis variklinis skrydis įvyko 1903 metais.",
      },
    },
  },
  {
    id: "his_ek_010",
    category: "history",
    subTheme: "events",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Black Death (14th century Europe)",
    emoji: "🐀",
    translations: {
      en: {
        question: "In which century did the Black Death sweep Europe?",
        correct: "14th century",
        distractors: ["10th century", "18th century", "16th century", "12th century", "20th century"],
        explanation: "The Black Death struck Europe in the mid-1300s.",
      },
      lt: {
        question: "Kuriame amžiuje Europą nusiaubė Juodoji mirtis?",
        correct: "XIV amžiuje",
        distractors: ["X amžiuje", "XVIII amžiuje", "XVI amžiuje", "XII amžiuje", "XX amžiuje"],
        explanation: "Juodoji mirtis nusiaubė Europą XIV a. viduryje.",
      },
    },
  },
  {
    id: "his_ek_011",
    category: "history",
    subTheme: "art",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Renaissance began in Italy",
    emoji: "🖌️",
    translations: {
      en: {
        question: "In which country did the Renaissance begin?",
        correct: "Italy",
        distractors: ["France", "England", "Spain", "Germany", "Greece"],
        explanation: "The Renaissance began in Italy in the 14th century.",
      },
      lt: {
        question: "Kurioje šalyje prasidėjo Renesansas?",
        correct: "Italija",
        distractors: ["Prancūzija", "Anglija", "Ispanija", "Vokietija", "Graikija"],
        explanation: "Renesansas prasidėjo Italijoje XIV amžiuje.",
      },
    },
  },
  {
    id: "his_ek_012",
    category: "history",
    subTheme: "inventions",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Telephone patent (1876)",
    emoji: "📞",
    translations: {
      en: {
        question: "In which year was the telephone patented?",
        correct: "1876",
        distractors: ["1850", "1900", "1888", "1865", "1910"],
        explanation: "Alexander Graham Bell patented the telephone in 1876.",
      },
      lt: {
        question: "Kuriais metais užpatentuotas telefonas?",
        correct: "1876",
        distractors: ["1850", "1900", "1888", "1865", "1910"],
        explanation: "Aleksandras Grahamas Belas užpatentavo telefoną 1876 m.",
      },
    },
  },
  {
    id: "his_ek_013",
    category: "history",
    subTheme: "explorers",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Roald Amundsen (South Pole, 1911)",
    emoji: "❄️",
    translations: {
      en: {
        question: "Who was the first to reach the South Pole?",
        correct: "Roald Amundsen",
        distractors: ["Robert Scott", "Ernest Shackleton", "James Cook", "Edmund Hillary", "Fridtjof Nansen"],
        explanation: "Roald Amundsen reached the South Pole in 1911.",
      },
      lt: {
        question: "Kas pirmas pasiekė Pietų ašigalį?",
        correct: "Rualas Amundsenas",
        distractors: ["Robertas Skotas", "Ernestas Šekltonas", "Džeimsas Kukas", "Edmundas Hilaris", "Fridtjofas Nansenas"],
        explanation: "Rualas Amundsenas pasiekė Pietų ašigalį 1911 metais.",
      },
    },
  },
  {
    id: "his_ek_014",
    category: "history",
    subTheme: "ancient",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Colosseum capacity (~50 000)",
    emoji: "🏟️",
    translations: {
      en: {
        question: "About how many spectators could the Colosseum hold?",
        correct: "50 000",
        distractors: ["5 000", "200 000", "1 000", "500 000", "10 000"],
        explanation: "The Colosseum held roughly 50 000 spectators.",
      },
      lt: {
        question: "Maždaug kiek žiūrovų talpino Koliziejus?",
        correct: "50 000",
        distractors: ["5 000", "200 000", "1 000", "500 000", "10 000"],
        explanation: "Koliziejus talpino apie 50 000 žiūrovų.",
      },
    },
  },
  {
    id: "his_ek_015",
    category: "history",
    subTheme: "people",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Florence Nightingale (founder of modern nursing)",
    emoji: "🕯️",
    translations: {
      en: {
        question: "Who is seen as the founder of modern nursing?",
        correct: "Florence Nightingale",
        distractors: ["Marie Curie", "Clara Barton", "Ada Lovelace", "Rosa Parks", "Joan of Arc"],
        explanation: "Florence Nightingale shaped modern nursing in the 1850s.",
      },
      lt: {
        question: "Kas laikomas šiuolaikinės slaugos pradininke?",
        correct: "Florence Nightingale",
        distractors: ["Marija Kiuri", "Klara Barton", "Ada Lavleis", "Rosa Parks", "Žana d’Ark"],
        explanation: "Florence Nightingale XIX a. viduryje sukūrė šiuolaikinę slaugą.",
      },
    },
  },
];
