/**
 * mythologyGreek — ⚡ „Graikų ir romėnų mitai" potemė (tema „Mitologija").
 *
 * MAŽAS FAILAS pagal potemę. 40 klausimų (10/lygiui). Senovės graikų ir romėnų
 * mitologija (dievai, herojai, būtybės). SAUGA: tik SENOVĖS pasakojimai —
 * gyvų religijų neliečiam; neutralu, mokomoji-pramoginė kultūra.
 *
 * TAISYKLĖS: 1 teisingas + 5 distraktoriai; ≤46 simb.; teisingas NE ilgiausias >+5;
 * LT be vidinių kabučių; jokio atsakymo klausime; emoji neišduoda atsakymo.
 */

import { TriviaQuestion } from "./triviaTypes";

export const MYTHOLOGY_GREEK: TriviaQuestion[] = [
  // ===================== LENGVAS (9–12 m. vaikas) =====================
  {
    id: "myt_gr_001",
    category: "mythology",
    subTheme: "greek",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Greek mythology — Zeus, king of the gods",
    emoji: "🏛️",
    translations: {
      en: {
        question: "Who is the king of the Greek gods, ruler of the sky?",
        correct: "Zeus",
        distractors: ["Hades", "Poseidon", "Apollo", "Ares", "Hermes"],
        explanation: "Zeus rules from Mount Olympus and wields thunderbolts.",
      },
      lt: {
        question: "Kas yra graikų dievų karalius, dangaus valdovas?",
        correct: "Dzeusas",
        distractors: ["Hadas", "Poseidonas", "Apolonas", "Aresas", "Hermis"],
        explanation: "Dzeusas valdo iš Olimpo kalno ir svaido žaibus.",
      },
    },
  },
  {
    id: "myt_gr_002",
    category: "mythology",
    subTheme: "greek",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Greek mythology — Poseidon, god of the sea",
    emoji: "🏺",
    translations: {
      en: {
        question: "Which god rules the sea, carrying a three-pronged spear?",
        correct: "Poseidon",
        distractors: ["Zeus", "Hades", "Apollo", "Hermes", "Ares"],
        explanation: "Poseidon's trident can stir up storms and earthquakes.",
      },
      lt: {
        question: "Kuris dievas valdo jūrą ir nešioja trišakę ietį?",
        correct: "Poseidonas",
        distractors: ["Dzeusas", "Hadas", "Apolonas", "Hermis", "Aresas"],
        explanation: "Poseidono trišakis gali kelti audras ir žemės drebėjimus.",
      },
    },
  },
  {
    id: "myt_gr_003",
    category: "mythology",
    subTheme: "greek",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Greek mythology — Mount Olympus, home of the gods",
    emoji: "🏔️",
    translations: {
      en: {
        question: "What tall mountain did the Greeks call the home of the gods?",
        correct: "Mount Olympus",
        distractors: ["Mount Everest", "Mount Fuji", "Mount Etna", "Mount Ida", "Mount Atlas"],
        explanation: "The twelve main gods were said to live atop Mount Olympus.",
      },
      lt: {
        question: "Kurį aukštą kalną graikai vadino dievų namais?",
        correct: "Olimpo kalnas",
        distractors: ["Everestas", "Fudzijama", "Etnos kalnas", "Idos kalnas", "Atlaso kalnas"],
        explanation: "Sakyta, kad dvylika pagrindinių dievų gyvena Olimpo viršūnėje.",
      },
    },
  },
  {
    id: "myt_gr_004",
    category: "mythology",
    subTheme: "greek",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Greek mythology — Heracles (Hercules) and his strength",
    emoji: "🗿",
    translations: {
      en: {
        question: "Which hero is famous for huge strength and twelve labors?",
        correct: "Hercules",
        distractors: ["Perseus", "Achilles", "Jason", "Theseus", "Odysseus"],
        explanation: "Hercules completed twelve near-impossible tasks.",
      },
      lt: {
        question: "Kuris herojus garsus milžiniška jėga ir dvylika žygdarbių?",
        correct: "Heraklis",
        distractors: ["Persėjas", "Achilas", "Jasonas", "Tesėjas", "Odisėjas"],
        explanation: "Heraklis įvykdė dvylika beveik neįmanomų užduočių.",
      },
    },
  },
  {
    id: "myt_gr_005",
    category: "mythology",
    subTheme: "greek",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Greek mythology — the centaur (half man, half horse)",
    emoji: "📜",
    translations: {
      en: {
        question: "What creature has a horse's body and a man's upper half?",
        correct: "A centaur",
        distractors: ["A mermaid", "A dragon", "A giant", "A fairy", "A goblin"],
        explanation: "Centaurs gallop through many Greek myths.",
      },
      lt: {
        question: "Kuri būtybė turi arklio kūną ir žmogaus viršutinę dalį?",
        correct: "Kentauras",
        distractors: ["Undinė", "Drakonas", "Milžinas", "Fėja", "Goblinas"],
        explanation: "Kentaurai šuoliuoja per daugelį graikų mitų.",
      },
    },
  },
  {
    id: "myt_gr_006",
    category: "mythology",
    subTheme: "greek",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Greek mythology — Pegasus, the winged horse",
    emoji: "🪙",
    translations: {
      en: {
        question: "Which famous mythical horse has wings and can fly?",
        correct: "Pegasus",
        distractors: ["A unicorn", "The Phoenix", "A griffin", "The Hydra", "The Sphinx"],
        explanation: "Pegasus is a magnificent winged stallion of Greek myth.",
      },
      lt: {
        question: "Kuris garsus mitinis arklys turi sparnus ir gali skristi?",
        correct: "Pegasas",
        distractors: ["Vienaragis", "Feniksas", "Grifas", "Hidra", "Sfinksas"],
        explanation: "Pegasas — nuostabus sparnuotas graikų mitų žirgas.",
      },
    },
  },
  {
    id: "myt_gr_007",
    category: "mythology",
    subTheme: "greek",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Greek mythology — Hermes, the messenger god",
    emoji: "🎭",
    translations: {
      en: {
        question: "Who is the speedy messenger god with winged sandals?",
        correct: "Hermes",
        distractors: ["Zeus", "Apollo", "Ares", "Hades", "Cronus"],
        explanation: "Hermes carries messages between gods and mortals.",
      },
      lt: {
        question: "Kuris greitas dievas pasiuntinys avi sparnuotus sandalus?",
        correct: "Hermis",
        distractors: ["Dzeusas", "Apolonas", "Aresas", "Hadas", "Kronas"],
        explanation: "Hermis perduoda žinias tarp dievų ir mirtingųjų.",
      },
    },
  },
  {
    id: "myt_gr_008",
    category: "mythology",
    subTheme: "greek",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Greek mythology — the Cyclops, one-eyed giant",
    emoji: "🏟️",
    translations: {
      en: {
        question: "Which giant in Greek myths has just a single eye?",
        correct: "A Cyclops",
        distractors: ["A centaur", "A mermaid", "A fairy", "A dwarf", "An elf"],
        explanation: "The Cyclops Polyphemus traps Odysseus in a famous tale.",
      },
      lt: {
        question: "Kuris milžinas graikų mituose turi tik vieną akį?",
        correct: "Kiklopas",
        distractors: ["Kentauras", "Undinė", "Fėja", "Nykštukas", "Elfas"],
        explanation: "Kiklopas Polifemas garsiajame pasakojime įkalina Odisėją.",
      },
    },
  },
  {
    id: "myt_gr_009",
    category: "mythology",
    subTheme: "greek",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Greek mythology — Apollo, god of the sun and music",
    emoji: "🗝️",
    translations: {
      en: {
        question: "Who is the Greek god of the sun, music and archery?",
        correct: "Apollo",
        distractors: ["Zeus", "Hades", "Ares", "Hermes", "Poseidon"],
        explanation: "Apollo plays a golden lyre and drives the sun across the sky.",
      },
      lt: {
        question: "Kuris graikų dievas globoja saulę, muziką ir šaudymą iš lanko?",
        correct: "Apolonas",
        distractors: ["Dzeusas", "Hadas", "Aresas", "Hermis", "Poseidonas"],
        explanation: "Apolonas groja auksine lyra ir veža saulę per dangų.",
      },
    },
  },
  {
    id: "myt_gr_010",
    category: "mythology",
    subTheme: "greek",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Greek mythology — Hades rules the underworld",
    emoji: "📯",
    translations: {
      en: {
        question: "Which god rules the dark world of the dead below?",
        correct: "Hades",
        distractors: ["Zeus", "Poseidon", "Apollo", "Hermes", "Ares"],
        explanation: "Hades is lord of the underworld, where souls go after death.",
      },
      lt: {
        question: "Kuris dievas valdo tamsų mirusiųjų pasaulį apačioje?",
        correct: "Hadas",
        distractors: ["Dzeusas", "Poseidonas", "Apolonas", "Hermis", "Aresas"],
        explanation: "Hadas — požemio pasaulio valdovas, kur po mirties keliauja sielos.",
      },
    },
  },

  // ===================== VIDUTINIS (12–18 m.) =====================
  {
    id: "myt_gr_011",
    category: "mythology",
    subTheme: "greek",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Greek mythology — Athena, goddess of wisdom",
    emoji: "🏛️",
    translations: {
      en: {
        question: "Which goddess of wisdom sprang from Zeus's own head?",
        correct: "Athena",
        distractors: ["Hera", "Aphrodite", "Artemis", "Demeter", "Hestia"],
        explanation: "Athena burst out fully grown and armored from Zeus's head.",
      },
      lt: {
        question: "Kuri išminties deivė iššoko iš paties Dzeuso galvos?",
        correct: "Atėnė",
        distractors: ["Hera", "Afroditė", "Artemidė", "Demetra", "Hestija"],
        explanation: "Atėnė išniro suaugusi ir su šarvais iš Dzeuso galvos.",
      },
    },
  },
  {
    id: "myt_gr_012",
    category: "mythology",
    subTheme: "greek",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Greek mythology — Cerberus guards the underworld",
    emoji: "🏺",
    translations: {
      en: {
        question: "What three-headed dog guards the gates of the underworld?",
        correct: "Cerberus",
        distractors: ["The Hydra", "The Chimera", "The Sphinx", "The Minotaur", "Pegasus"],
        explanation: "Cerberus lets souls in but never lets them back out.",
      },
      lt: {
        question: "Koks trigalvis šuo saugo požemio pasaulio vartus?",
        correct: "Cerberis",
        distractors: ["Hidra", "Chimera", "Sfinksas", "Minotauras", "Pegasas"],
        explanation: "Cerberis įleidžia sielas, bet niekada neišleidžia atgal.",
      },
    },
  },
  {
    id: "myt_gr_013",
    category: "mythology",
    subTheme: "greek",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Greek mythology — Medusa turns onlookers to stone",
    emoji: "🗿",
    translations: {
      en: {
        question: "Whose gaze was so terrible it turned people to stone?",
        correct: "Medusa",
        distractors: ["Circe", "Pandora", "Athena", "Echo", "Hera"],
        explanation: "Medusa had snakes for hair; one look turned you to stone.",
      },
      lt: {
        question: "Kieno žvilgsnis buvo toks baisus, kad pavertė žmones akmeniu?",
        correct: "Medūza",
        distractors: ["Kirkė", "Pandora", "Atėnė", "Echo", "Hera"],
        explanation: "Medūza vietoj plaukų turėjo gyvates; vienas žvilgsnis paversdavo akmeniu.",
      },
    },
  },
  {
    id: "myt_gr_014",
    category: "mythology",
    subTheme: "greek",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Greek mythology — Theseus and the Minotaur",
    emoji: "🌀",
    translations: {
      en: {
        question: "Which hero killed the Minotaur deep inside the labyrinth?",
        correct: "Theseus",
        distractors: ["Hercules", "Perseus", "Jason", "Achilles", "Odysseus"],
        explanation: "Theseus used a thread to find his way back out of the maze.",
      },
      lt: {
        question: "Kuris herojus nukovė Minotaurą labirinto gilumoje?",
        correct: "Tesėjas",
        distractors: ["Heraklis", "Persėjas", "Jasonas", "Achilas", "Odisėjas"],
        explanation: "Tesėjas siūlu rado kelią atgal iš labirinto.",
      },
    },
  },
  {
    id: "myt_gr_015",
    category: "mythology",
    subTheme: "greek",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Greek mythology — only Hope remained in Pandora's jar",
    emoji: "📦",
    translations: {
      en: {
        question: "When Pandora opened her box, what alone stayed inside?",
        correct: "Hope",
        distractors: ["Gold", "Fire", "Light", "Water", "Fear"],
        explanation: "All the world's troubles escaped, but Hope remained within.",
      },
      lt: {
        question: "Pandorai atvėrus skrynią, kas vienintelis liko viduje?",
        correct: "Viltis",
        distractors: ["Auksas", "Ugnis", "Šviesa", "Vanduo", "Baimė"],
        explanation: "Visos pasaulio bėdos pabiro, bet viduje liko viltis.",
      },
    },
  },
  {
    id: "myt_gr_016",
    category: "mythology",
    subTheme: "greek",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Roman mythology — Jupiter equals the Greek Zeus",
    emoji: "📜",
    translations: {
      en: {
        question: "The Romans called their king of the gods, like Zeus, what?",
        correct: "Jupiter",
        distractors: ["Mars", "Neptune", "Pluto", "Apollo", "Saturn"],
        explanation: "Romans matched their gods to Greek ones; Zeus became Jupiter.",
      },
      lt: {
        question: "Kaip romėnai vadino savo dievų karalių, kaip ir Dzeusą?",
        correct: "Jupiteris",
        distractors: ["Marsas", "Neptūnas", "Plutonas", "Apolonas", "Saturnas"],
        explanation: "Romėnai siejo savo dievus su graikų; Dzeusas tapo Jupiteriu.",
      },
    },
  },
  {
    id: "myt_gr_017",
    category: "mythology",
    subTheme: "greek",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Mythology — Aphrodite is the Roman Venus",
    emoji: "🪙",
    translations: {
      en: {
        question: "Which Greek goddess of love did the Romans call Venus?",
        correct: "Aphrodite",
        distractors: ["Hera", "Athena", "Artemis", "Demeter", "Hestia"],
        explanation: "Aphrodite, goddess of love and beauty, became Roman Venus.",
      },
      lt: {
        question: "Kurią graikų meilės deivę romėnai vadino Venera?",
        correct: "Afroditė",
        distractors: ["Hera", "Atėnė", "Artemidė", "Demetra", "Hestija"],
        explanation: "Afroditė, meilės ir grožio deivė, tapo romėnų Venera.",
      },
    },
  },
  {
    id: "myt_gr_018",
    category: "mythology",
    subTheme: "greek",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Greek mythology — Achilles' only weak spot was his heel",
    emoji: "🎭",
    translations: {
      en: {
        question: "Which warrior had only one weak spot — his heel?",
        correct: "Achilles",
        distractors: ["Hercules", "Perseus", "Theseus", "Jason", "Hector"],
        explanation: "Dipped in a magic river, only his heel stayed unprotected.",
      },
      lt: {
        question: "Kuris karys turėjo tik vieną silpną vietą — kulną?",
        correct: "Achilas",
        distractors: ["Heraklis", "Persėjas", "Tesėjas", "Jasonas", "Hektoras"],
        explanation: "Panardintas stebuklingoje upėje, tik kulnas liko neapsaugotas.",
      },
    },
  },
  {
    id: "myt_gr_019",
    category: "mythology",
    subTheme: "greek",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Greek mythology — Icarus flew too close to the sun",
    emoji: "☀️",
    translations: {
      en: {
        question: "Who flew too close to the sun on wax wings and fell?",
        correct: "Icarus",
        distractors: ["Perseus", "Hermes", "Daedalus", "Apollo", "Bellerophon"],
        explanation: "The sun melted the wax, and Icarus tumbled into the sea.",
      },
      lt: {
        question: "Kas vaškiniais sparnais skrido per arti saulės ir nukrito?",
        correct: "Ikaras",
        distractors: ["Persėjas", "Hermis", "Dedalas", "Apolonas", "Belerofontas"],
        explanation: "Saulė ištirpdė vašką, ir Ikaras nukrito į jūrą.",
      },
    },
  },
  {
    id: "myt_gr_020",
    category: "mythology",
    subTheme: "greek",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Roman mythology — Mars is the god of war (Greek Ares)",
    emoji: "🏟️",
    translations: {
      en: {
        question: "Who was the Roman god of war, matching the Greek Ares?",
        correct: "Mars",
        distractors: ["Jupiter", "Neptune", "Pluto", "Mercury", "Apollo"],
        explanation: "The month March and the planet Mars share his name.",
      },
      lt: {
        question: "Kuris romėnų karo dievas atitiko graikų Aresą?",
        correct: "Marsas",
        distractors: ["Jupiteris", "Neptūnas", "Plutonas", "Merkurijus", "Apolonas"],
        explanation: "Jo vardą turi ir planeta Marsas.",
      },
    },
  },

  // ===================== SUNKUS (suaugę) =====================
  {
    id: "myt_gr_021",
    category: "mythology",
    subTheme: "greek",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Greek mythology — Atlas holds up the sky",
    emoji: "🗝️",
    translations: {
      en: {
        question: "Which Titan was condemned to hold up the sky forever?",
        correct: "Atlas",
        distractors: ["Cronus", "Prometheus", "Helios", "Oceanus", "Hyperion"],
        explanation: "As punishment, Atlas bears the heavens on his shoulders.",
      },
      lt: {
        question: "Kuris titanas buvo nubaustas amžinai laikyti dangų?",
        correct: "Atlasas",
        distractors: ["Kronas", "Prometėjas", "Helijas", "Okeanas", "Hiperionas"],
        explanation: "Už bausmę Atlasas laiko dangų ant pečių.",
      },
    },
  },
  {
    id: "myt_gr_022",
    category: "mythology",
    subTheme: "greek",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Greek mythology — Prometheus stole fire for humankind",
    emoji: "📯",
    translations: {
      en: {
        question: "Which Titan stole fire from the gods to give to humans?",
        correct: "Prometheus",
        distractors: ["Atlas", "Hercules", "Hermes", "Hades", "Cronus"],
        explanation: "For this gift he was chained and punished by Zeus.",
      },
      lt: {
        question: "Kuris titanas pavogė ugnį iš dievų ir atidavė žmonėms?",
        correct: "Prometėjas",
        distractors: ["Atlasas", "Heraklis", "Hermis", "Hadas", "Kronas"],
        explanation: "Už šią dovaną Dzeusas jį prirakino ir nubaudė.",
      },
    },
  },
  {
    id: "myt_gr_023",
    category: "mythology",
    subTheme: "greek",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Greek mythology — the Chimera (lion, goat, serpent)",
    emoji: "🏛️",
    translations: {
      en: {
        question: "Which monster had a lion's head, goat's body and snake's tail?",
        correct: "The Chimera",
        distractors: ["The Hydra", "The Sphinx", "Cerberus", "The Minotaur", "The Kraken"],
        explanation: "The fire-breathing Chimera was slain by the hero Bellerophon.",
      },
      lt: {
        question: "Kuri pabaisa turėjo liūto galvą, ožkos kūną ir gyvatės uodegą?",
        correct: "Chimera",
        distractors: ["Hidra", "Sfinksas", "Cerberis", "Minotauras", "Krakenas"],
        explanation: "Ugnimi alsuojančią Chimerą nukovė herojus Belerofontas.",
      },
    },
  },
  {
    id: "myt_gr_024",
    category: "mythology",
    subTheme: "greek",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Greek mythology — Odysseus, hero of Homer's Odyssey",
    emoji: "⛵",
    translations: {
      en: {
        question: "Which hero's ten-year voyage home is told in the Odyssey?",
        correct: "Odysseus",
        distractors: ["Achilles", "Hercules", "Jason", "Theseus", "Perseus"],
        explanation: "He outwitted monsters and storms on his way back to Ithaca.",
      },
      lt: {
        question: "Kurio herojaus dešimties metų kelionė namo aprašyta Odisėjoje?",
        correct: "Odisėjas",
        distractors: ["Achilas", "Heraklis", "Jasonas", "Tesėjas", "Persėjas"],
        explanation: "Jis pergudravo pabaisas ir audras keliaudamas atgal į Itaką.",
      },
    },
  },
  {
    id: "myt_gr_025",
    category: "mythology",
    subTheme: "greek",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Greek mythology — the Hydra regrew its heads",
    emoji: "🏺",
    translations: {
      en: {
        question: "Which serpent grew two new heads each time one was cut off?",
        correct: "The Hydra",
        distractors: ["Cerberus", "The Chimera", "Medusa", "The Kraken", "The Sphinx"],
        explanation: "Hercules burned each stump so the Hydra's heads couldn't regrow.",
      },
      lt: {
        question: "Kuriai gyvatei vietoj nukirstos galvos išaugdavo dvi naujos?",
        correct: "Hidra",
        distractors: ["Cerberis", "Chimera", "Medūza", "Krakenas", "Sfinksas"],
        explanation: "Heraklis degino kaklus, kad Hidros galvos nebeataugtų.",
      },
    },
  },
  {
    id: "myt_gr_026",
    category: "mythology",
    subTheme: "greek",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Greek mythology — Jason's ship was the Argo",
    emoji: "⛵",
    translations: {
      en: {
        question: "What ship did Jason sail in search of the Golden Fleece?",
        correct: "The Argo",
        distractors: ["The Trident", "The Odyssey", "The Pegasus", "The Nautilus", "The Trojan"],
        explanation: "Its crew of heroes were called the Argonauts.",
      },
      lt: {
        question: "Kokiu laivu Jasonas plaukė ieškoti Auksinės vilnos?",
        correct: "Argo",
        distractors: ["Trišakis", "Odisėja", "Pegasas", "Nautilas", "Trojos"],
        explanation: "Jo herojų įgula buvo vadinama argonautais.",
      },
    },
  },
  {
    id: "myt_gr_027",
    category: "mythology",
    subTheme: "greek",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Greek mythology — the Sphinx posed a deadly riddle",
    emoji: "🦁",
    translations: {
      en: {
        question: "What did the Sphinx demand travelers answer or die?",
        correct: "A riddle",
        distractors: ["A song", "A dance", "A race", "A battle", "A payment"],
        explanation: "Oedipus solved her riddle about the creature on four, two, three legs.",
      },
      lt: {
        question: "Ką keliautojai turėjo įminti Sfinksui, kitaip žūti?",
        correct: "Mįslę",
        distractors: ["Dainą", "Šokį", "Lenktynes", "Mūšį", "Užmokestį"],
        explanation: "Edipas įminė mįslę apie būtybę ant keturių, dviejų, trijų kojų.",
      },
    },
  },
  {
    id: "myt_gr_028",
    category: "mythology",
    subTheme: "greek",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Greek mythology — Orpheus entered the underworld for his wife",
    emoji: "🗿",
    translations: {
      en: {
        question: "Which musician charmed the underworld to rescue his lost wife?",
        correct: "Orpheus",
        distractors: ["Apollo", "Hermes", "Perseus", "Jason", "Theseus"],
        explanation: "His music was so sweet that even Hades let him try.",
      },
      lt: {
        question: "Kuris muzikantas savo muzika sužavėjo požemį, vaduodamas žmoną?",
        correct: "Orfėjas",
        distractors: ["Apolonas", "Hermis", "Persėjas", "Jasonas", "Tesėjas"],
        explanation: "Jo muzika buvo tokia graži, kad net Hadas leido pamėginti.",
      },
    },
  },
  {
    id: "myt_gr_029",
    category: "mythology",
    subTheme: "greek",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Greek mythology — Demeter, goddess of the harvest",
    emoji: "📜",
    translations: {
      en: {
        question: "Which goddess of the harvest is the mother of Persephone?",
        correct: "Demeter",
        distractors: ["Hera", "Athena", "Artemis", "Hestia", "Hecate"],
        explanation: "Her grief for Persephone was said to bring winter to the world.",
      },
      lt: {
        question: "Kuri derliaus deivė yra Persefonės motina?",
        correct: "Demetra",
        distractors: ["Hera", "Atėnė", "Artemidė", "Hestija", "Hekatė"],
        explanation: "Sakoma, kad jos liūdesys dėl Persefonės atnešdavo pasauliui žiemą.",
      },
    },
  },
  {
    id: "myt_gr_030",
    category: "mythology",
    subTheme: "greek",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Greek mythology — Hera, queen of the gods",
    emoji: "🪙",
    translations: {
      en: {
        question: "Who is the queen of the Greek gods and wife of Zeus?",
        correct: "Hera",
        distractors: ["Athena", "Aphrodite", "Demeter", "Artemis", "Hestia"],
        explanation: "Hera is the goddess of marriage and often jealous of Zeus.",
      },
      lt: {
        question: "Kuri yra graikų dievų karalienė ir Dzeuso žmona?",
        correct: "Hera",
        distractors: ["Atėnė", "Afroditė", "Demetra", "Artemidė", "Hestija"],
        explanation: "Hera — santuokos deivė, dažnai pavyduliaujanti Dzeusui.",
      },
    },
  },

  // ===================== EKSTREMALUS (žinovai) =====================
  {
    id: "myt_gr_031",
    category: "mythology",
    subTheme: "greek",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Greek mythology — Cronus, Titan father of Zeus",
    emoji: "🎭",
    translations: {
      en: {
        question: "Which Titan ruled before Zeus and was his own father?",
        correct: "Cronus",
        distractors: ["Atlas", "Uranus", "Oceanus", "Hyperion", "Prometheus"],
        explanation: "Cronus swallowed his children until Zeus overthrew him.",
      },
      lt: {
        question: "Kuris titanas valdė prieš Dzeusą ir buvo jo tėvas?",
        correct: "Kronas",
        distractors: ["Atlasas", "Uranas", "Okeanas", "Hiperionas", "Prometėjas"],
        explanation: "Kronas rijo savo vaikus, kol Dzeusas jį nuvertė.",
      },
    },
  },
  {
    id: "myt_gr_032",
    category: "mythology",
    subTheme: "greek",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Greek mythology — Nike, goddess of victory",
    emoji: "🏟️",
    translations: {
      en: {
        question: "Which winged goddess of victory lends her name to a sports brand?",
        correct: "Nike",
        distractors: ["Iris", "Hebe", "Tyche", "Nemesis", "Eris"],
        explanation: "Nike personified victory in battle and sport.",
      },
      lt: {
        question: "Kurios sparnuotos pergalės deivės vardą turi sporto prekės ženklas?",
        correct: "Nikė",
        distractors: ["Iridė", "Hebė", "Tichė", "Nemezidė", "Eridė"],
        explanation: "Nikė įkūnijo pergalę mūšyje ir sporte.",
      },
    },
  },
  {
    id: "myt_gr_033",
    category: "mythology",
    subTheme: "greek",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Greek mythology — gods swore binding oaths by the river Styx",
    emoji: "🌊",
    translations: {
      en: {
        question: "By which underworld river did the Greek gods swear binding oaths?",
        correct: "The Styx",
        distractors: ["The Nile", "The Tiber", "The Lethe", "The Amazon", "The Jordan"],
        explanation: "An oath sworn on the Styx could never be broken, even by gods.",
      },
      lt: {
        question: "Kuria požemio upe graikų dievai prisiekdavo nesulaužomas priesaikas?",
        correct: "Stiksu",
        distractors: ["Nilu", "Tibru", "Lete", "Amazone", "Jordanu"],
        explanation: "Priesaikos, duotos Stiksu, negalėjo sulaužyti net dievai.",
      },
    },
  },
  {
    id: "myt_gr_034",
    category: "mythology",
    subTheme: "greek",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Greek mythology — Eris threw the golden apple of discord",
    emoji: "🗝️",
    translations: {
      en: {
        question: "Which goddess of discord threw the apple that sparked the Trojan War?",
        correct: "Eris",
        distractors: ["Hera", "Athena", "Aphrodite", "Nemesis", "Hecate"],
        explanation: "Her golden apple, marked 'for the fairest', set goddesses quarreling.",
      },
      lt: {
        question: "Kuri nesantaikos deivė numetė obuolį, įžiebusį Trojos karą?",
        correct: "Eridė",
        distractors: ["Hera", "Atėnė", "Afroditė", "Nemezidė", "Hekatė"],
        explanation: "Jos auksinis obuolys gražiausiajai sukiršino deives.",
      },
    },
  },
  {
    id: "myt_gr_035",
    category: "mythology",
    subTheme: "greek",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Mythology — Hestia is the Greek counterpart of Roman Vesta",
    emoji: "📯",
    translations: {
      en: {
        question: "Which Greek goddess of the hearth matches the Roman Vesta?",
        correct: "Hestia",
        distractors: ["Demeter", "Hera", "Athena", "Artemis", "Gaia"],
        explanation: "Hestia tended the sacred fire of home and city.",
      },
      lt: {
        question: "Kuri graikų židinio deivė atitinka romėnų Vestą?",
        correct: "Hestija",
        distractors: ["Demetra", "Hera", "Atėnė", "Artemidė", "Gaja"],
        explanation: "Hestija saugojo šventą namų ir miesto ugnį.",
      },
    },
  },
  {
    id: "myt_gr_036",
    category: "mythology",
    subTheme: "greek",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Greek mythology — Gaia, primordial personification of Earth",
    emoji: "🏛️",
    translations: {
      en: {
        question: "Who is the primordial Greek goddess who personifies the Earth?",
        correct: "Gaia",
        distractors: ["Rhea", "Hera", "Demeter", "Selene", "Nyx"],
        explanation: "From Gaia came the sky, the seas and the first Titans.",
      },
      lt: {
        question: "Kuri pirmapradė graikų deivė įkūnija Žemę?",
        correct: "Gaja",
        distractors: ["Rėja", "Hera", "Demetra", "Selenė", "Niktė"],
        explanation: "Iš Gajos kilo dangus, jūros ir pirmieji titanai.",
      },
    },
  },
  {
    id: "myt_gr_037",
    category: "mythology",
    subTheme: "greek",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Greek mythology — Perseus beheaded Medusa using a shield",
    emoji: "🏺",
    translations: {
      en: {
        question: "Which hero beheaded Medusa by watching her in a polished shield?",
        correct: "Perseus",
        distractors: ["Theseus", "Hercules", "Jason", "Achilles", "Bellerophon"],
        explanation: "By looking only at her reflection, he avoided being turned to stone.",
      },
      lt: {
        question: "Kuris herojus nukirto Medūzai galvą, stebėdamas ją blizgiame skyde?",
        correct: "Persėjas",
        distractors: ["Tesėjas", "Heraklis", "Jasonas", "Achilas", "Belerofontas"],
        explanation: "Žiūrėdamas tik į atspindį, jis nevirto akmeniu.",
      },
    },
  },
  {
    id: "myt_gr_038",
    category: "mythology",
    subTheme: "greek",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Greek mythology — Bellerophon tamed Pegasus, slew the Chimera",
    emoji: "🗿",
    translations: {
      en: {
        question: "Which hero tamed Pegasus and killed the fire-breathing Chimera?",
        correct: "Bellerophon",
        distractors: ["Perseus", "Theseus", "Jason", "Hercules", "Achilles"],
        explanation: "Riding Pegasus, he attacked the Chimera safely from the air.",
      },
      lt: {
        question: "Kuris herojus prijaukino Pegasą ir nukovė ugnimi alsuojančią Chimerą?",
        correct: "Belerofontas",
        distractors: ["Persėjas", "Tesėjas", "Jasonas", "Heraklis", "Achilas"],
        explanation: "Jodamas Pegasu, jis saugiai puolė Chimerą iš oro.",
      },
    },
  },
  {
    id: "myt_gr_039",
    category: "mythology",
    subTheme: "greek",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Mythology — Minerva is the Roman counterpart of Athena",
    emoji: "📜",
    translations: {
      en: {
        question: "What did the Romans name their goddess of wisdom, like Athena?",
        correct: "Minerva",
        distractors: ["Juno", "Venus", "Diana", "Ceres", "Vesta"],
        explanation: "Minerva, like Athena, was goddess of wisdom and craft.",
      },
      lt: {
        question: "Kaip romėnai vadino savo išminties deivę, kaip ir Atėnę?",
        correct: "Minerva",
        distractors: ["Junona", "Venera", "Diana", "Cerera", "Vesta"],
        explanation: "Minerva, kaip ir Atėnė, buvo išminties ir amatų deivė.",
      },
    },
  },
  {
    id: "myt_gr_040",
    category: "mythology",
    subTheme: "greek",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Greek mythology — Hypnos is the personification of sleep",
    emoji: "🪙",
    translations: {
      en: {
        question: "Which Greek god personified sleep, brother of Death (Thanatos)?",
        correct: "Hypnos",
        distractors: ["Morpheus", "Nyx", "Eros", "Chronos", "Helios"],
        explanation: "Hypnos brought sleep; his son Morpheus shaped dreams.",
      },
      lt: {
        question: "Kuris graikų dievas įkūnijo miegą, Mirties (Tanato) brolis?",
        correct: "Hipnas",
        distractors: ["Morfėjas", "Niktė", "Erotas", "Chronas", "Helijas"],
        explanation: "Hipnas atnešdavo miegą; jo sūnus Morfėjas kūrė sapnus.",
      },
    },
  },
];
