/**
 * mythologyNorse — 🔨 „Šiaurės mitai" potemė (tema „Mitologija").
 *
 * MAŽAS FAILAS pagal potemę. 40 klausimų (10/lygiui). Senovės skandinavų
 * mitologija (Toras, Odinas, Lokis, devyni pasauliai, Ragnarokas).
 * SAUGA: tik SENOVĖS pasakojimai; neutralu. NEKARTOJA graikų potemės.
 *
 * TAISYKLĖS: 1 teisingas + 5 distraktoriai; ≤46 simb.; teisingas NE ilgiausias >+5;
 * LT be vidinių kabučių; jokio atsakymo klausime; emoji neišduoda atsakymo.
 */

import { TriviaQuestion } from "./triviaTypes";

export const MYTHOLOGY_NORSE: TriviaQuestion[] = [
  // ===================== LENGVAS (9–12 m. vaikas) =====================
  {
    id: "myt_no_001",
    category: "mythology",
    subTheme: "norse",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Norse mythology — Thor, god of thunder",
    emoji: "🔨",
    translations: {
      en: {
        question: "Who is the Norse god of thunder who wields a mighty hammer?",
        correct: "Thor",
        distractors: ["Odin", "Loki", "Freya", "Tyr", "Baldr"],
        explanation: "Thor protects gods and humans with his thunderous hammer.",
      },
      lt: {
        question: "Kuris šiaurės dievas valdo griaustinį ir laiko rankoje galingą kūjį?",
        correct: "Toras",
        distractors: ["Odinas", "Lokis", "Frėja", "Tiras", "Baldras"],
        explanation: "Toras gina dievus ir žmones savo griausmingu kūju.",
      },
    },
  },
  {
    id: "myt_no_002",
    category: "mythology",
    subTheme: "norse",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Norse mythology — Thor's hammer Mjolnir",
    emoji: "⚒️",
    translations: {
      en: {
        question: "What is the name of Thor's magical hammer?",
        correct: "Mjolnir",
        distractors: ["Gungnir", "Excalibur", "Durendal", "Trident", "Gram"],
        explanation: "Mjolnir always returns to Thor's hand after he throws it.",
      },
      lt: {
        question: "Kaip vadinasi stebuklingas Toro kūjis?",
        correct: "Mjolniras",
        distractors: ["Gungniras", "Excaliburas", "Durendalis", "Trišakis", "Gramas"],
        explanation: "Mjolniras visada sugrįžta į Toro ranką po metimo.",
      },
    },
  },
  {
    id: "myt_no_003",
    category: "mythology",
    subTheme: "norse",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Norse mythology — Odin, the one-eyed Allfather",
    emoji: "👁️",
    translations: {
      en: {
        question: "Who is the one-eyed king of the Norse gods, the Allfather?",
        correct: "Odin",
        distractors: ["Thor", "Loki", "Tyr", "Baldr", "Heimdall"],
        explanation: "Odin gave up an eye to gain great wisdom.",
      },
      lt: {
        question: "Kuris vienaakis yra šiaurės dievų karalius, Visų Tėvas?",
        correct: "Odinas",
        distractors: ["Toras", "Lokis", "Tiras", "Baldras", "Heimdalis"],
        explanation: "Odinas atidavė akį, kad gautų didžią išmintį.",
      },
    },
  },
  {
    id: "myt_no_004",
    category: "mythology",
    subTheme: "norse",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Norse mythology — Loki the trickster",
    emoji: "🃏",
    translations: {
      en: {
        question: "Which Norse god is a sly trickster always causing mischief?",
        correct: "Loki",
        distractors: ["Thor", "Odin", "Baldr", "Tyr", "Freyr"],
        explanation: "Loki's clever tricks bring the gods both help and trouble.",
      },
      lt: {
        question: "Kuris šiaurės dievas yra gudrus apgavikas, nuolat krečiantis išdaigas?",
        correct: "Lokis",
        distractors: ["Toras", "Odinas", "Baldras", "Tiras", "Freiras"],
        explanation: "Gudrios Lokio išdaigos dievams neša ir pagalbą, ir bėdą.",
      },
    },
  },
  {
    id: "myt_no_005",
    category: "mythology",
    subTheme: "norse",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Norse mythology — Valhalla, hall of fallen warriors",
    emoji: "🛡️",
    translations: {
      en: {
        question: "What is the great hall where brave fallen warriors feast?",
        correct: "Valhalla",
        distractors: ["Olympus", "Atlantis", "Camelot", "Avalon", "Eden"],
        explanation: "Odin welcomes heroes who die bravely into Valhalla.",
      },
      lt: {
        question: "Kaip vadinama didžioji menė, kur puotauja žuvę narsūs kariai?",
        correct: "Valhala",
        distractors: ["Olimpas", "Atlantida", "Kamelotas", "Avalonas", "Edenas"],
        explanation: "Odinas priima narsiai žuvusius didvyrius į Valhalą.",
      },
    },
  },
  {
    id: "myt_no_006",
    category: "mythology",
    subTheme: "norse",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Norse mythology — Asgard, home of the gods",
    emoji: "🏰",
    translations: {
      en: {
        question: "What is the home of the Norse gods called?",
        correct: "Asgard",
        distractors: ["Midgard", "Olympus", "Atlantis", "Avalon", "Eden"],
        explanation: "The gods, called the Aesir, live high up in Asgard.",
      },
      lt: {
        question: "Kaip vadinami šiaurės dievų namai?",
        correct: "Asgardas",
        distractors: ["Midgardas", "Olimpas", "Atlantida", "Avalonas", "Edenas"],
        explanation: "Dievai, vadinami asais, gyvena aukštai Asgarde.",
      },
    },
  },
  {
    id: "myt_no_007",
    category: "mythology",
    subTheme: "norse",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Etymology — Thursday is named after Thor",
    emoji: "📅",
    translations: {
      en: {
        question: "Which day of the week is named after the god Thor?",
        correct: "Thursday",
        distractors: ["Monday", "Sunday", "Saturday", "Friday", "Tuesday"],
        explanation: "Thursday comes from 'Thor's day' in old languages.",
      },
      lt: {
        question: "Kuri savaitės diena anglų kalboje pavadinta dievo Toro vardu?",
        correct: "Ketvirtadienis",
        distractors: ["Pirmadienis", "Sekmadienis", "Šeštadienis", "Penktadienis", "Antradienis"],
        explanation: "Angliškas Thursday kilęs iš Toro dienos senosiose kalbose.",
      },
    },
  },
  {
    id: "myt_no_008",
    category: "mythology",
    subTheme: "norse",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Norse mythology — Valkyries carry the slain to Valhalla",
    emoji: "🪽",
    translations: {
      en: {
        question: "What do we call the warrior maidens who carry heroes to Valhalla?",
        correct: "Valkyries",
        distractors: ["Mermaids", "Fairies", "Witches", "Nymphs", "Sirens"],
        explanation: "Valkyries choose which fallen warriors will feast with Odin.",
      },
      lt: {
        question: "Kaip vadinamos karės mergelės, nešančios didvyrius į Valhalą?",
        correct: "Valkirijos",
        distractors: ["Undinės", "Fėjos", "Raganos", "Nimfos", "Sirenos"],
        explanation: "Valkirijos pasirenka, kurie žuvę kariai puotaus su Odinu.",
      },
    },
  },
  {
    id: "myt_no_009",
    category: "mythology",
    subTheme: "norse",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Norse mythology — the Bifrost rainbow bridge",
    emoji: "🌈",
    translations: {
      en: {
        question: "What kind of bridge links the gods' world to ours in Norse myth?",
        correct: "A rainbow bridge",
        distractors: ["A stone bridge", "A rope bridge", "An ice bridge", "A gold bridge", "A wooden bridge"],
        explanation: "The shimmering rainbow bridge is named Bifrost.",
      },
      lt: {
        question: "Koks tiltas šiaurės mituose jungia dievų pasaulį su mūsiškiu?",
        correct: "Vaivorykštės tiltas",
        distractors: ["Akmeninis tiltas", "Virvinis tiltas", "Ledo tiltas", "Auksinis tiltas", "Medinis tiltas"],
        explanation: "Žėrintis vaivorykštės tiltas vadinamas Bifrostu.",
      },
    },
  },
  {
    id: "myt_no_010",
    category: "mythology",
    subTheme: "norse",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "History of myth — Norse myths come from Scandinavia",
    emoji: "🗺️",
    translations: {
      en: {
        question: "Which part of the world do the Norse myths come from?",
        correct: "Scandinavia",
        distractors: ["Egypt", "Greece", "China", "India", "Australia"],
        explanation: "Norse myths come from the cold lands of northern Europe.",
      },
      lt: {
        question: "Iš kurio pasaulio krašto kilę šiaurės (skandinavų) mitai?",
        correct: "Skandinavija",
        distractors: ["Egiptas", "Graikija", "Kinija", "Indija", "Australija"],
        explanation: "Šiaurės mitai kilę iš šaltų Šiaurės Europos kraštų.",
      },
    },
  },

  // ===================== VIDUTINIS (12–18 m.) =====================
  {
    id: "myt_no_011",
    category: "mythology",
    subTheme: "norse",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Norse mythology — Yggdrasil, the world tree",
    emoji: "🌳",
    translations: {
      en: {
        question: "What giant ash tree holds together the nine Norse worlds?",
        correct: "Yggdrasil",
        distractors: ["Bifrost", "Valhalla", "Mjolnir", "Gungnir", "Sleipnir"],
        explanation: "Yggdrasil's roots and branches link all nine realms.",
      },
      lt: {
        question: "Koks milžiniškas uosis laiko sujungtus devynis šiaurės pasaulius?",
        correct: "Igdrasilis",
        distractors: ["Bifrostas", "Valhala", "Mjolniras", "Gungniras", "Sleipniras"],
        explanation: "Igdrasilio šaknys ir šakos jungia visus devynis pasaulius.",
      },
    },
  },
  {
    id: "myt_no_012",
    category: "mythology",
    subTheme: "norse",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Norse mythology — Ragnarok, the doom of the gods",
    emoji: "⚔️",
    translations: {
      en: {
        question: "What is the great final battle that ends the Norse world called?",
        correct: "Ragnarok",
        distractors: ["Armageddon", "The Great Flood", "Doomsday", "The Eclipse", "The Reckoning"],
        explanation: "At Ragnarok gods and monsters clash and the world is reborn.",
      },
      lt: {
        question: "Kaip vadinamas didysis paskutinis mūšis, užbaigiantis šiaurės pasaulį?",
        correct: "Ragnarokas",
        distractors: ["Armagedonas", "Didysis tvanas", "Pasaulio pabaiga", "Užtemimas", "Atpildas"],
        explanation: "Per Ragnaroką dievai ir pabaisos susiremia, o pasaulis atgimsta.",
      },
    },
  },
  {
    id: "myt_no_013",
    category: "mythology",
    subTheme: "norse",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Norse mythology — Freya, goddess of love and beauty",
    emoji: "💛",
    translations: {
      en: {
        question: "Which Norse goddess of love and beauty rides a cat-drawn chariot?",
        correct: "Freya",
        distractors: ["Frigg", "Sif", "Idun", "Skadi", "Hel"],
        explanation: "Freya is also linked with magic and chooses some fallen warriors.",
      },
      lt: {
        question: "Kuri šiaurės meilės ir grožio deivė važiuoja kačių traukiamu vežimu?",
        correct: "Frėja",
        distractors: ["Friga", "Sifa", "Idūna", "Skadė", "Hela"],
        explanation: "Frėja siejama ir su magija; ji renkasi dalį žuvusių karių.",
      },
    },
  },
  {
    id: "myt_no_014",
    category: "mythology",
    subTheme: "norse",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Norse mythology — Bifrost is the rainbow bridge's name",
    emoji: "🌉",
    translations: {
      en: {
        question: "What is the actual name of the rainbow bridge to Asgard?",
        correct: "Bifrost",
        distractors: ["Yggdrasil", "Gjallarhorn", "Sleipnir", "Gungnir", "Valhalla"],
        explanation: "Bifrost burns with rainbow fire and is guarded day and night.",
      },
      lt: {
        question: "Koks tikrasis vaivorykštės tilto į Asgardą vardas?",
        correct: "Bifrostas",
        distractors: ["Igdrasilis", "Gjalarhornas", "Sleipniras", "Gungniras", "Valhala"],
        explanation: "Bifrostas dega vaivorykštės ugnimi ir saugomas dieną naktį.",
      },
    },
  },
  {
    id: "myt_no_015",
    category: "mythology",
    subTheme: "norse",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Norse mythology — Heimdall guards the Bifrost",
    emoji: "📯",
    translations: {
      en: {
        question: "Which watchful god guards the rainbow bridge with a great horn?",
        correct: "Heimdall",
        distractors: ["Thor", "Loki", "Tyr", "Baldr", "Freyr"],
        explanation: "Heimdall can hear grass grow and sees for miles.",
      },
      lt: {
        question: "Kuris budrus dievas su didžiuliu ragu saugo vaivorykštės tiltą?",
        correct: "Heimdalis",
        distractors: ["Toras", "Lokis", "Tiras", "Baldras", "Freiras"],
        explanation: "Heimdalis girdi, kaip auga žolė, ir mato už mylių.",
      },
    },
  },
  {
    id: "myt_no_016",
    category: "mythology",
    subTheme: "norse",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Norse mythology — Midgard is the human world",
    emoji: "🌍",
    translations: {
      en: {
        question: "What is the world of humans called in Norse mythology?",
        correct: "Midgard",
        distractors: ["Asgard", "Valhalla", "Helheim", "Jotunheim", "Alfheim"],
        explanation: "Midgard, our world, sits in the middle of the nine realms.",
      },
      lt: {
        question: "Kaip šiaurės mitologijoje vadinamas žmonių pasaulis?",
        correct: "Midgardas",
        distractors: ["Asgardas", "Valhala", "Helheimas", "Jotunheimas", "Alfheimas"],
        explanation: "Midgardas, mūsų pasaulis, yra devynių pasaulių viduryje.",
      },
    },
  },
  {
    id: "myt_no_017",
    category: "mythology",
    subTheme: "norse",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Etymology — Wednesday is named after Odin (Woden)",
    emoji: "📅",
    translations: {
      en: {
        question: "Which weekday in English comes from Odin (Woden)?",
        correct: "Wednesday",
        distractors: ["Monday", "Friday", "Sunday", "Tuesday", "Saturday"],
        explanation: "Wednesday means 'Woden's day' — Woden is another name for Odin.",
      },
      lt: {
        question: "Kuri savaitės diena anglų kalboje kilo iš Odino (Wodeno)?",
        correct: "Trečiadienis",
        distractors: ["Pirmadienis", "Penktadienis", "Sekmadienis", "Antradienis", "Šeštadienis"],
        explanation: "Wednesday reiškia Wodeno dieną — Wodenas yra kitas Odino vardas.",
      },
    },
  },
  {
    id: "myt_no_018",
    category: "mythology",
    subTheme: "norse",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Norse mythology — Gungnir, Odin's spear",
    emoji: "🔱",
    translations: {
      en: {
        question: "What is the name of Odin's spear that never misses its mark?",
        correct: "Gungnir",
        distractors: ["Mjolnir", "Excalibur", "Gram", "Trident", "Tyrfing"],
        explanation: "Gungnir was forged by skilled dwarves for Odin.",
      },
      lt: {
        question: "Kaip vadinasi Odino ietis, kuri niekada nepraleidžia taikinio?",
        correct: "Gungniras",
        distractors: ["Mjolniras", "Excaliburas", "Gramas", "Trišakis", "Tirfingas"],
        explanation: "Gungnirą Odinui nukalė įgudę nykštukai.",
      },
    },
  },
  {
    id: "myt_no_019",
    category: "mythology",
    subTheme: "norse",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Norse mythology — Sleipnir, Odin's eight-legged horse",
    emoji: "🐎",
    translations: {
      en: {
        question: "How many legs does Odin's swift horse Sleipnir have?",
        correct: "Eight",
        distractors: ["Four", "Six", "Two", "Ten", "Twelve"],
        explanation: "Eight-legged Sleipnir can gallop over land, sea and sky.",
      },
      lt: {
        question: "Kiek kojų turi greitas Odino žirgas Sleipniras?",
        correct: "Aštuonias",
        distractors: ["Keturias", "Šešias", "Dvi", "Dešimt", "Dvylika"],
        explanation: "Aštuonkojis Sleipniras šuoliuoja per žemę, jūrą ir dangų.",
      },
    },
  },
  {
    id: "myt_no_020",
    category: "mythology",
    subTheme: "norse",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Norse mythology — Tyr lost his hand to the wolf Fenrir",
    emoji: "✋",
    translations: {
      en: {
        question: "Which brave Norse god lost his hand to a giant wolf?",
        correct: "Tyr",
        distractors: ["Thor", "Odin", "Loki", "Baldr", "Heimdall"],
        explanation: "Tyr placed his hand in the wolf's jaws as a pledge of trust.",
      },
      lt: {
        question: "Kuriam narsiam šiaurės dievui milžiniškas vilkas nukando ranką?",
        correct: "Tiras",
        distractors: ["Toras", "Odinas", "Lokis", "Baldras", "Heimdalis"],
        explanation: "Tiras įdėjo ranką vilkui į nasrus kaip pasitikėjimo ženklą.",
      },
    },
  },

  // ===================== SUNKUS (suaugę) =====================
  {
    id: "myt_no_021",
    category: "mythology",
    subTheme: "norse",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Norse mythology — Fenrir, the monstrous wolf",
    emoji: "🐺",
    translations: {
      en: {
        question: "Which giant wolf, son of Loki, is fated to kill Odin at Ragnarok?",
        correct: "Fenrir",
        distractors: ["Garmr", "Skoll", "Hati", "Geri", "Freki"],
        explanation: "The gods chained Fenrir with a magical, unbreakable ribbon.",
      },
      lt: {
        question: "Kuris milžiniškas vilkas, Lokio sūnus, nukaus Odiną per Ragnaroką?",
        correct: "Fenriras",
        distractors: ["Garmas", "Skolis", "Hatis", "Geris", "Frekis"],
        explanation: "Dievai sukaustė Fenrirą stebuklingu, nenutraukiamu raiščiu.",
      },
    },
  },
  {
    id: "myt_no_022",
    category: "mythology",
    subTheme: "norse",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Norse mythology — Jormungandr, the world serpent",
    emoji: "🐍",
    translations: {
      en: {
        question: "What enormous serpent coils around the whole world of Midgard?",
        correct: "Jormungandr",
        distractors: ["Fenrir", "Nidhogg", "Ladon", "Python", "Apophis"],
        explanation: "The world serpent is so long it bites its own tail.",
      },
      lt: {
        question: "Kokia milžiniška gyvatė apsiveja aplink visą Midgardo pasaulį?",
        correct: "Jormungandas",
        distractors: ["Fenriras", "Nidhogas", "Ladonas", "Pitonas", "Apofis"],
        explanation: "Pasaulio gyvatė tokia ilga, kad įsikanda sau į uodegą.",
      },
    },
  },
  {
    id: "myt_no_023",
    category: "mythology",
    subTheme: "norse",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Norse mythology — Baldr was killed by mistletoe",
    emoji: "🌿",
    translations: {
      en: {
        question: "Which beloved Norse god was slain by a dart of mistletoe?",
        correct: "Baldr",
        distractors: ["Thor", "Tyr", "Heimdall", "Bragi", "Forseti"],
        explanation: "Loki tricked a blind god into throwing the deadly mistletoe.",
      },
      lt: {
        question: "Kuris mylimas šiaurės dievas žuvo nuo amalo strėlės?",
        correct: "Baldras",
        distractors: ["Toras", "Tiras", "Heimdalis", "Bragis", "Forsetis"],
        explanation: "Lokis apgavo aklą dievą, kad šis sviestų mirtiną amalą.",
      },
    },
  },
  {
    id: "myt_no_024",
    category: "mythology",
    subTheme: "norse",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Norse mythology — the Norns weave fate",
    emoji: "🧵",
    translations: {
      en: {
        question: "What do we call the three Norse beings who weave everyone's fate?",
        correct: "The Norns",
        distractors: ["The Fates", "The Valkyries", "The Muses", "The Graces", "The Furies"],
        explanation: "The Norns tend the world tree and decide gods' and mortals' destinies.",
      },
      lt: {
        question: "Kaip vadinamos trys šiaurės būtybės, audžiančios visų likimą?",
        correct: "Nornos",
        distractors: ["Moiros", "Valkirijos", "Mūzos", "Charitės", "Erinijos"],
        explanation: "Nornos prižiūri pasaulio medį ir lemia dievų bei mirtingųjų likimus.",
      },
    },
  },
  {
    id: "myt_no_025",
    category: "mythology",
    subTheme: "norse",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Norse mythology — Gjallarhorn signals Ragnarok",
    emoji: "📯",
    translations: {
      en: {
        question: "What horn will Heimdall blow to warn that Ragnarok has begun?",
        correct: "Gjallarhorn",
        distractors: ["Gungnir", "Mjolnir", "Bifrost", "Gleipnir", "Draupnir"],
        explanation: "Its blast will be heard across all nine worlds.",
      },
      lt: {
        question: "Kokiu ragu Heimdalis sutrimituos, įspėdamas, kad prasidėjo Ragnarokas?",
        correct: "Gjalarhornas",
        distractors: ["Gungniras", "Mjolniras", "Bifrostas", "Gleipniras", "Draupniras"],
        explanation: "Jo gausmas nuaidės per visus devynis pasaulius.",
      },
    },
  },
  {
    id: "myt_no_026",
    category: "mythology",
    subTheme: "norse",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Norse mythology — Hel rules the underworld",
    emoji: "💀",
    translations: {
      en: {
        question: "Which daughter of Loki rules over the Norse land of the dead?",
        correct: "Hel",
        distractors: ["Freya", "Frigg", "Skadi", "Sif", "Idun"],
        explanation: "Half her face is living, half is that of a corpse.",
      },
      lt: {
        question: "Kuri Lokio dukra valdo šiaurės mirusiųjų kraštą?",
        correct: "Hela",
        distractors: ["Frėja", "Friga", "Skadė", "Sifa", "Idūna"],
        explanation: "Pusė jos veido gyva, pusė — kaip lavono.",
      },
    },
  },
  {
    id: "myt_no_027",
    category: "mythology",
    subTheme: "norse",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Norse mythology — Odin's ravens Huginn and Muninn",
    emoji: "🐦‍⬛",
    translations: {
      en: {
        question: "Which two ravens fly the world and whisper news to Odin?",
        correct: "Huginn and Muninn",
        distractors: ["Geri and Freki", "Skoll and Hati", "Hugin and Thor", "Munin and Loki", "Odin and Vili"],
        explanation: "Their names mean 'Thought' and 'Memory'.",
      },
      lt: {
        question: "Kurie du varnai apskrieja pasaulį ir šnabžda Odinui naujienas?",
        correct: "Huginas ir Muninas",
        distractors: ["Geris ir Frekis", "Skolis ir Hatis", "Huginas ir Toras", "Muninas ir Lokis", "Odinas ir Vilis"],
        explanation: "Jų vardai reiškia Mintį ir Atmintį.",
      },
    },
  },
  {
    id: "myt_no_028",
    category: "mythology",
    subTheme: "norse",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Norse mythology — the Jotnar (giants) oppose the gods",
    emoji: "🗿",
    translations: {
      en: {
        question: "What do we call the giant foes of the gods in Norse myth?",
        correct: "Jotnar",
        distractors: ["Titans", "Cyclopes", "Trolls", "Elves", "Dwarves"],
        explanation: "These giants live in Jotunheim and often clash with the Aesir.",
      },
      lt: {
        question: "Kaip vadinami milžinai, dievų priešai šiaurės mituose?",
        correct: "Jotunai",
        distractors: ["Titanai", "Kiklopai", "Troliai", "Elfai", "Nykštukai"],
        explanation: "Šie milžinai gyvena Jotunheime ir dažnai kaunasi su asais.",
      },
    },
  },
  {
    id: "myt_no_029",
    category: "mythology",
    subTheme: "norse",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Etymology — Tuesday is named after the god Tyr (Tiw)",
    emoji: "📅",
    translations: {
      en: {
        question: "Which weekday in English is named after the war god Tyr?",
        correct: "Tuesday",
        distractors: ["Monday", "Wednesday", "Friday", "Sunday", "Thursday"],
        explanation: "Tuesday comes from 'Tiw's day' — Tiw is the old name for Tyr.",
      },
      lt: {
        question: "Kuri savaitės diena anglų kalboje pavadinta karo dievo Tiro vardu?",
        correct: "Antradienis",
        distractors: ["Pirmadienis", "Trečiadienis", "Penktadienis", "Sekmadienis", "Ketvirtadienis"],
        explanation: "Tuesday kilęs iš Tiwo dienos — Tiwas yra senas Tiro vardas.",
      },
    },
  },
  {
    id: "myt_no_030",
    category: "mythology",
    subTheme: "norse",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Norse mythology — Draupnir, Odin's self-multiplying ring",
    emoji: "💍",
    translations: {
      en: {
        question: "What golden ring of Odin dripped eight new rings every ninth night?",
        correct: "Draupnir",
        distractors: ["Andvaranaut", "Gungnir", "Gleipnir", "Mjolnir", "The One Ring"],
        explanation: "Dwarves forged Draupnir as a symbol of endless wealth.",
      },
      lt: {
        question: "Koks auksinis Odino žiedas kas devintą naktį numesdavo aštuonis naujus?",
        correct: "Draupniras",
        distractors: ["Andvaranautas", "Gungniras", "Gleipniras", "Mjolniras", "Galios žiedas"],
        explanation: "Nykštukai nukalė Draupnirą kaip begalinio turto simbolį.",
      },
    },
  },

  // ===================== EKSTREMALUS (žinovai) =====================
  {
    id: "myt_no_031",
    category: "mythology",
    subTheme: "norse",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Norse cosmology — Muspelheim, realm of fire",
    emoji: "🔥",
    translations: {
      en: {
        question: "What is the blazing realm of the fire giants in Norse myth?",
        correct: "Muspelheim",
        distractors: ["Niflheim", "Jotunheim", "Alfheim", "Vanaheim", "Svartalfheim"],
        explanation: "Muspelheim's heat helped form the world out of the great void.",
      },
      lt: {
        question: "Koks liepsnojantis ugnies milžinų pasaulis yra šiaurės mituose?",
        correct: "Muspelheimas",
        distractors: ["Niflheimas", "Jotunheimas", "Alfheimas", "Vanaheimas", "Svartalfheimas"],
        explanation: "Muspelheimo karštis padėjo iš didžiosios tuštumos kurti pasaulį.",
      },
    },
  },
  {
    id: "myt_no_032",
    category: "mythology",
    subTheme: "norse",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Norse cosmology — Niflheim, realm of ice and mist",
    emoji: "❄️",
    translations: {
      en: {
        question: "What is the cold, misty realm of ice in Norse cosmology?",
        correct: "Niflheim",
        distractors: ["Muspelheim", "Asgard", "Midgard", "Vanaheim", "Alfheim"],
        explanation: "Where Niflheim's ice met Muspelheim's fire, life first stirred.",
      },
      lt: {
        question: "Koks šaltas, miglotas ledo pasaulis yra šiaurės kosmologijoje?",
        correct: "Niflheimas",
        distractors: ["Muspelheimas", "Asgardas", "Midgardas", "Vanaheimas", "Alfheimas"],
        explanation: "Kur Niflheimo ledas sutiko Muspelheimo ugnį, užgimė gyvybė.",
      },
    },
  },
  {
    id: "myt_no_033",
    category: "mythology",
    subTheme: "norse",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Norse mythology — Surtr, fire giant of Ragnarok",
    emoji: "🔥",
    translations: {
      en: {
        question: "Which fire giant will engulf the world in flame at Ragnarok?",
        correct: "Surtr",
        distractors: ["Ymir", "Fenrir", "Thrym", "Hrungnir", "Mimir"],
        explanation: "Surtr's flaming sword sets the nine worlds ablaze.",
      },
      lt: {
        question: "Kuris ugnies milžinas per Ragnaroką apims pasaulį liepsnomis?",
        correct: "Surtas",
        distractors: ["Ymiras", "Fenriras", "Trimas", "Hrungniras", "Mimiras"],
        explanation: "Liepsnojantis Surto kalavijas padega visus devynis pasaulius.",
      },
    },
  },
  {
    id: "myt_no_034",
    category: "mythology",
    subTheme: "norse",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Norse mythology — Ymir, the first primeval giant",
    emoji: "🗿",
    translations: {
      en: {
        question: "From whose giant body did the Norse gods shape the world?",
        correct: "Ymir",
        distractors: ["Odin", "Surtr", "Buri", "Mimir", "Bor"],
        explanation: "From Ymir's flesh came earth, from his blood the seas.",
      },
      lt: {
        question: "Iš kurio milžino kūno šiaurės dievai sukūrė pasaulį?",
        correct: "Ymiras",
        distractors: ["Odinas", "Surtas", "Buris", "Mimiras", "Boras"],
        explanation: "Iš Ymiro kūno atsirado žemė, iš kraujo — jūros.",
      },
    },
  },
  {
    id: "myt_no_035",
    category: "mythology",
    subTheme: "norse",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Norse mythology — Skoll and Hati chase the sun and moon",
    emoji: "🌗",
    translations: {
      en: {
        question: "Which two wolves endlessly chase the sun and the moon?",
        correct: "Skoll and Hati",
        distractors: ["Geri and Freki", "Huginn and Muninn", "Fenrir and Garmr", "Sleipnir and Grani", "Vili and Ve"],
        explanation: "At Ragnarok the wolves finally catch and swallow them.",
      },
      lt: {
        question: "Kurie du vilkai be perstojo vejasi saulę ir mėnulį?",
        correct: "Skolis ir Hatis",
        distractors: ["Geris ir Frekis", "Huginas ir Muninas", "Fenriras ir Garmas", "Sleipniras ir Granis", "Vilis ir Vė"],
        explanation: "Per Ragnaroką vilkai pagaliau juos pagauna ir praryja.",
      },
    },
  },
  {
    id: "myt_no_036",
    category: "mythology",
    subTheme: "norse",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Norse mythology — Gleipnir binds the wolf Fenrir",
    emoji: "⛓️",
    translations: {
      en: {
        question: "What magical ribbon, light as silk, binds the wolf Fenrir?",
        correct: "Gleipnir",
        distractors: ["Gungnir", "Gjallarhorn", "Draupnir", "Andvaranaut", "Mjolnir"],
        explanation: "Dwarves wove Gleipnir from six impossible things, like a cat's footfall.",
      },
      lt: {
        question: "Koks stebuklingas, lengvas kaip šilkas raištis sukausto vilką Fenrirą?",
        correct: "Gleipniras",
        distractors: ["Gungniras", "Gjalarhornas", "Draupniras", "Andvaranautas", "Mjolniras"],
        explanation: "Nykštukai Gleipnirą nuaudė iš šešių neįmanomų dalykų.",
      },
    },
  },
  {
    id: "myt_no_037",
    category: "mythology",
    subTheme: "norse",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Norse mythology — Odin gave an eye at Mimir's well",
    emoji: "🧿",
    translations: {
      en: {
        question: "At whose well of wisdom did Odin sacrifice one of his eyes?",
        correct: "Mimir's",
        distractors: ["Kvasir's", "Heimdall's", "Bragi's", "Hoenir's", "Vili's"],
        explanation: "Odin traded an eye for a drink of deep knowledge.",
      },
      lt: {
        question: "Prie kieno išminties šaltinio Odinas paaukojo vieną savo akį?",
        correct: "Mimiro",
        distractors: ["Kvasyro", "Heimdalio", "Bragio", "Hionyro", "Vilio"],
        explanation: "Odinas iškeitė akį į gurkšnį gilios išminties.",
      },
    },
  },
  {
    id: "myt_no_038",
    category: "mythology",
    subTheme: "norse",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Norse mythology — the Vanir, gods of fertility",
    emoji: "🌾",
    translations: {
      en: {
        question: "What group of fertility gods, including Freya, differs from the Aesir?",
        correct: "The Vanir",
        distractors: ["The Aesir", "The Jotnar", "The Norns", "The Einherjar", "The Alfar"],
        explanation: "After a war, the Vanir and Aesir made peace and traded hostages.",
      },
      lt: {
        question: "Kokia vaisingumo dievų grupė, kuriai priklauso Frėja, skiriasi nuo asų?",
        correct: "Vanai",
        distractors: ["Asai", "Jotunai", "Nornos", "Einherjai", "Alfai"],
        explanation: "Po karo vanai ir asai susitaikė ir apsikeitė įkaitais.",
      },
    },
  },
  {
    id: "myt_no_039",
    category: "mythology",
    subTheme: "norse",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Norse mythology — the Einherjar feast in Valhalla",
    emoji: "🍖",
    translations: {
      en: {
        question: "What are the chosen slain warriors who feast in Valhalla called?",
        correct: "The Einherjar",
        distractors: ["The Valkyries", "The Berserkers", "The Jotnar", "The Draugr", "The Vikings"],
        explanation: "The Einherjar train daily for the final battle of Ragnarok.",
      },
      lt: {
        question: "Kaip vadinami išrinktieji žuvę kariai, puotaujantys Valhaloje?",
        correct: "Einherjai",
        distractors: ["Valkirijos", "Berserkai", "Jotunai", "Draugai", "Vikingai"],
        explanation: "Einherjai kasdien treniruojasi paskutiniam Ragnaroko mūšiui.",
      },
    },
  },
  {
    id: "myt_no_040",
    category: "mythology",
    subTheme: "norse",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Norse mythology — Bragi, god of poetry",
    emoji: "🎶",
    translations: {
      en: {
        question: "Which Norse god, husband of Idun, is the god of poetry?",
        correct: "Bragi",
        distractors: ["Baldr", "Forseti", "Vidar", "Vali", "Hodr"],
        explanation: "Bragi greets heroes with verses as they arrive in Valhalla.",
      },
      lt: {
        question: "Kuris šiaurės dievas, Idūnos vyras, yra poezijos dievas?",
        correct: "Bragis",
        distractors: ["Baldras", "Forsetis", "Vidaras", "Valis", "Hodras"],
        explanation: "Bragis pasitinka didvyrius eilėmis, jiems atvykus į Valhalą.",
      },
    },
  },
];
