/**
 * mythologyCreatures — 🐉 „Būtybės ir legendos" potemė (tema „Mitologija").
 *
 * MAŽAS FAILAS pagal potemę. 40 klausimų (10/lygiui). Legendinės būtybės ir
 * pasakojimai iš viso pasaulio folkloro: drakonai, vienaragiai, karalius Artūras,
 * Atlantida, kriptidai (Nesė, jetis), Keltų/japonų/persų legendos.
 * SAUGA: tik legendos/folkloras/literatūra; jokių gyvų religijų (vengiau Gralio,
 * golemo, religinių džinų ir pan.). NEKARTOJA graikų/skandinavų/egipto potemių.
 *
 * TAISYKLĖS: 1 teisingas + 5 distraktoriai; ≤46 simb.; teisingas NE ilgiausias >+5;
 * LT be vidinių kabučių; jokio atsakymo klausime; emoji neišduoda atsakymo.
 */

import { TriviaQuestion } from "./triviaTypes";

export const MYTHOLOGY_CREATURES: TriviaQuestion[] = [
  // ===================== LENGVAS (9–12 m. vaikas) =====================
  {
    id: "myt_cr_001",
    category: "mythology",
    subTheme: "creatures",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Folklore — dragons are fire-breathing winged reptiles",
    emoji: "🐉",
    translations: {
      en: {
        question: "What fire-breathing winged reptile appears in legends worldwide?",
        correct: "A dragon",
        distractors: ["A unicorn", "A phoenix", "A griffin", "A mermaid", "A troll"],
        explanation: "Dragons appear in stories from Europe to China.",
      },
      lt: {
        question: "Koks ugnimi alsuojantis sparnuotas roplys sutinkamas viso pasaulio legendose?",
        correct: "Drakonas",
        distractors: ["Vienaragis", "Feniksas", "Grifas", "Undinė", "Trolis"],
        explanation: "Drakonai sutinkami pasakojimuose nuo Europos iki Kinijos.",
      },
    },
  },
  {
    id: "myt_cr_002",
    category: "mythology",
    subTheme: "creatures",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Folklore — the unicorn, a horse with one horn",
    emoji: "✨",
    translations: {
      en: {
        question: "Which legendary horse-like creature has a single horn on its head?",
        correct: "A unicorn",
        distractors: ["A dragon", "A centaur", "A pegasus", "A griffin", "A goblin"],
        explanation: "The unicorn is a symbol of purity in many old tales.",
      },
      lt: {
        question: "Kuri legendinė į arklį panaši būtybė turi vieną ragą kaktoje?",
        correct: "Vienaragis",
        distractors: ["Drakonas", "Kentauras", "Pegasas", "Grifas", "Goblinas"],
        explanation: "Vienaragis daugelyje senų pasakojimų simbolizuoja tyrumą.",
      },
    },
  },
  {
    id: "myt_cr_003",
    category: "mythology",
    subTheme: "creatures",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Folklore — the phoenix is reborn from its ashes",
    emoji: "🔥",
    translations: {
      en: {
        question: "Which mythical bird bursts into flame and is reborn from its ashes?",
        correct: "A phoenix",
        distractors: ["An eagle", "A dragon", "An owl", "A peacock", "A raven"],
        explanation: "The phoenix rises young again from the ashes of the old.",
      },
      lt: {
        question: "Kuris mitinis paukštis užsidega ir atgimsta iš savo pelenų?",
        correct: "Feniksas",
        distractors: ["Erelis", "Drakonas", "Pelėda", "Povas", "Varnas"],
        explanation: "Feniksas iš senųjų pelenų vėl pakyla jaunas.",
      },
    },
  },
  {
    id: "myt_cr_004",
    category: "mythology",
    subTheme: "creatures",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Folklore — a mermaid is half woman, half fish",
    emoji: "🐉",
    translations: {
      en: {
        question: "What do we call a legendary creature that is half woman, half fish?",
        correct: "A mermaid",
        distractors: ["A fairy", "A witch", "A nymph", "A goblin", "A giant"],
        explanation: "Sailors told of mermaids singing from the rocks.",
      },
      lt: {
        question: "Kaip vadinama legendinė būtybė, pusiau moteris, pusiau žuvis?",
        correct: "Undinė",
        distractors: ["Fėja", "Ragana", "Nimfa", "Goblinas", "Milžinas"],
        explanation: "Jūreiviai pasakojo apie undines, dainuojančias ant uolų.",
      },
    },
  },
  {
    id: "myt_cr_005",
    category: "mythology",
    subTheme: "creatures",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Arthurian legend — Arthur pulled the sword from the stone",
    emoji: "🗡️",
    translations: {
      en: {
        question: "Which legendary king pulled a sword from a stone to prove he was king?",
        correct: "King Arthur",
        distractors: ["Robin Hood", "Merlin", "Lancelot", "Hercules", "King Midas"],
        explanation: "Only the true king could free the sword from the stone.",
      },
      lt: {
        question: "Kuris legendinis karalius ištraukė kalaviją iš akmens ir taip įrodė esąs karalius?",
        correct: "Karalius Artūras",
        distractors: ["Robinas Hudas", "Merlinas", "Lanselotas", "Heraklis", "Karalius Midas"],
        explanation: "Tik tikrasis karalius galėjo ištraukti kalaviją iš akmens.",
      },
    },
  },
  {
    id: "myt_cr_006",
    category: "mythology",
    subTheme: "creatures",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Arthurian legend — Excalibur, King Arthur's sword",
    emoji: "⚔️",
    translations: {
      en: {
        question: "What is the name of King Arthur's famous magical sword?",
        correct: "Excalibur",
        distractors: ["Mjolnir", "Gungnir", "Gram", "Durendal", "Tyrfing"],
        explanation: "Excalibur was said to shine bright and never fail its king.",
      },
      lt: {
        question: "Kaip vadinasi garsus stebuklingas karaliaus Artūro kalavijas?",
        correct: "Excaliburas",
        distractors: ["Mjolniras", "Gungniras", "Gramas", "Durendalis", "Tirfingas"],
        explanation: "Sakyta, kad Excaliburas ryškiai spindi ir niekada nenuvilia savo karaliaus.",
      },
    },
  },
  {
    id: "myt_cr_007",
    category: "mythology",
    subTheme: "creatures",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Cryptid folklore — Bigfoot of North American forests",
    emoji: "📖",
    translations: {
      en: {
        question: "Which legend tells of a big, hairy ape-man in North American forests?",
        correct: "Bigfoot",
        distractors: ["A mermaid", "A vampire", "A fairy", "A genie", "A dragon"],
        explanation: "Bigfoot, or Sasquatch, supposedly leaves giant footprints.",
      },
      lt: {
        question: "Kuri legenda pasakoja apie didelį, gauruotą beždžionžmogį Š. Amerikos miškuose?",
        correct: "Bigfutas",
        distractors: ["Undinė", "Vampyras", "Fėja", "Džinas", "Drakonas"],
        explanation: "Bigfutas (Sakvačas) esą palieka milžiniškus pėdsakus.",
      },
    },
  },
  {
    id: "myt_cr_008",
    category: "mythology",
    subTheme: "creatures",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Irish folklore — leprechauns guard a pot of gold",
    emoji: "🔮",
    translations: {
      en: {
        question: "Which little magical being guards a pot of gold in Irish legend?",
        correct: "A leprechaun",
        distractors: ["A giant", "A troll", "A dragon", "A mermaid", "A wizard"],
        explanation: "Catch a leprechaun and he must reveal his hidden gold.",
      },
      lt: {
        question: "Kuri maža magiška būtybė airių legendoje saugo aukso puodą?",
        correct: "Leprekonas",
        distractors: ["Milžinas", "Trolis", "Drakonas", "Undinė", "Burtininkas"],
        explanation: "Pagavus leprekoną, jis turi atskleisti paslėptą auksą.",
      },
    },
  },
  {
    id: "myt_cr_009",
    category: "mythology",
    subTheme: "creatures",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Cryptid folklore — Nessie of Loch Ness, Scotland",
    emoji: "🌫️",
    translations: {
      en: {
        question: "What nickname is given to the monster said to live in a Scottish lake?",
        correct: "Nessie",
        distractors: ["The Kraken", "A mermaid", "A dragon", "Bigfoot", "A vampire"],
        explanation: "People claim to spot Nessie in deep, cold Loch Ness.",
      },
      lt: {
        question: "Kokia pravarde vadinama pabaisa, esą gyvenanti Škotijos ežere?",
        correct: "Nesė",
        distractors: ["Krakenas", "Undinė", "Drakonas", "Bigfutas", "Vampyras"],
        explanation: "Žmonės teigia matę Nesę giliame, šaltame Loch Neso ežere.",
      },
    },
  },
  {
    id: "myt_cr_010",
    category: "mythology",
    subTheme: "creatures",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Folklore — the Kraken, a giant tentacled sea monster",
    emoji: "🪄",
    translations: {
      en: {
        question: "Which huge legendary sea monster attacks ships with giant tentacles?",
        correct: "The Kraken",
        distractors: ["A mermaid", "A dolphin", "A whale", "A shark", "A seahorse"],
        explanation: "Old sailors feared the Kraken could drag a ship under.",
      },
      lt: {
        question: "Kuri didžiulė legendinė jūros pabaisa puola laivus milžiniškais čiuptuvais?",
        correct: "Krakenas",
        distractors: ["Undinė", "Delfinas", "Banginis", "Ryklys", "Jūrų arkliukas"],
        explanation: "Senieji jūreiviai bijojo, kad Krakenas nutemps laivą į gelmę.",
      },
    },
  },

  // ===================== VIDUTINIS (12–18 m.) =====================
  {
    id: "myt_cr_011",
    category: "mythology",
    subTheme: "creatures",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Legend — Atlantis, the lost sunken city",
    emoji: "🌊",
    translations: {
      en: {
        question: "What is the legendary lost city said to have sunk beneath the sea?",
        correct: "Atlantis",
        distractors: ["El Dorado", "Camelot", "Troy", "Pompeii", "Avalon"],
        explanation: "The philosopher Plato first wrote of the lost Atlantis.",
      },
      lt: {
        question: "Koks legendinis dingęs miestas esą nugrimzdo po jūra?",
        correct: "Atlantida",
        distractors: ["El Doradas", "Kamelotas", "Troja", "Pompėja", "Avalonas"],
        explanation: "Apie dingusią Atlantidą pirmasis rašė filosofas Platonas.",
      },
    },
  },
  {
    id: "myt_cr_012",
    category: "mythology",
    subTheme: "creatures",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Arthurian legend — Merlin the wizard",
    emoji: "🧙",
    translations: {
      en: {
        question: "Who was King Arthur's wise wizard and advisor?",
        correct: "Merlin",
        distractors: ["Gandalf", "Lancelot", "Galahad", "Mordred", "Gawain"],
        explanation: "Merlin's magic helped Arthur become king of Britain.",
      },
      lt: {
        question: "Kas buvo karaliaus Artūro išmintingas burtininkas ir patarėjas?",
        correct: "Merlinas",
        distractors: ["Gendalfas", "Lanselotas", "Galahadas", "Mordredas", "Gavenas"],
        explanation: "Merlino magija padėjo Artūrui tapti Britanijos karaliumi.",
      },
    },
  },
  {
    id: "myt_cr_013",
    category: "mythology",
    subTheme: "creatures",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Arthurian legend — Camelot, Arthur's court",
    emoji: "🪨",
    translations: {
      en: {
        question: "What was the name of King Arthur's famous castle and court?",
        correct: "Camelot",
        distractors: ["Atlantis", "Avalon", "Asgard", "Olympus", "El Dorado"],
        explanation: "Camelot stood for the golden age of Arthur's kingdom.",
      },
      lt: {
        question: "Kaip vadinosi garsi karaliaus Artūro pilis ir dvaras?",
        correct: "Kamelotas",
        distractors: ["Atlantida", "Avalonas", "Asgardas", "Olimpas", "El Doradas"],
        explanation: "Kamelotas simbolizavo auksinį Artūro karalystės amžių.",
      },
    },
  },
  {
    id: "myt_cr_014",
    category: "mythology",
    subTheme: "creatures",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Arthurian legend — the Round Table of equal knights",
    emoji: "🪙",
    translations: {
      en: {
        question: "At what special table did Arthur's knights sit as equals?",
        correct: "The Round Table",
        distractors: ["The Long Table", "The Stone Table", "The Golden Table", "The High Table", "The Oak Table"],
        explanation: "A round shape meant no knight sat above the others.",
      },
      lt: {
        question: "Prie kokio ypatingo stalo Artūro riteriai sėdėjo kaip lygūs?",
        correct: "Apskritasis stalas",
        distractors: ["Ilgasis stalas", "Akmeninis stalas", "Auksinis stalas", "Aukštasis stalas", "Ąžuolinis stalas"],
        explanation: "Apvali forma reiškė, kad nė vienas riteris nesėdi aukščiau kitų.",
      },
    },
  },
  {
    id: "myt_cr_015",
    category: "mythology",
    subTheme: "creatures",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Folklore — the griffin (lion body, eagle head and wings)",
    emoji: "✨",
    translations: {
      en: {
        question: "Which creature has a lion's body and an eagle's head and wings?",
        correct: "A griffin",
        distractors: ["A dragon", "A phoenix", "A sphinx", "A chimera", "A pegasus"],
        explanation: "Griffins were said to fiercely guard piles of gold.",
      },
      lt: {
        question: "Kuri būtybė turi liūto kūną ir erelio galvą bei sparnus?",
        correct: "Grifas",
        distractors: ["Drakonas", "Feniksas", "Sfinksas", "Chimera", "Pegasas"],
        explanation: "Sakyta, kad grifai įnirtingai saugo aukso krūvas.",
      },
    },
  },
  {
    id: "myt_cr_016",
    category: "mythology",
    subTheme: "creatures",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Legend — El Dorado, the lost city of gold",
    emoji: "🏆",
    translations: {
      en: {
        question: "What legendary city of gold did explorers seek in South America?",
        correct: "El Dorado",
        distractors: ["Atlantis", "Camelot", "Shangri-La", "Avalon", "Troy"],
        explanation: "El Dorado lured many treasure hunters who never found it.",
      },
      lt: {
        question: "Kokio legendinio aukso miesto tyrinėtojai ieškojo Pietų Amerikoje?",
        correct: "El Doradas",
        distractors: ["Atlantida", "Kamelotas", "Šangri La", "Avalonas", "Troja"],
        explanation: "El Doradas viliojo daugybę lobių ieškotojų, bet niekad nebuvo rastas.",
      },
    },
  },
  {
    id: "myt_cr_017",
    category: "mythology",
    subTheme: "creatures",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Folklore — a werewolf changes shape at the full moon",
    emoji: "🐉",
    translations: {
      en: {
        question: "In folklore, what creature turns from a human into a wolf at full moon?",
        correct: "A werewolf",
        distractors: ["A vampire", "A zombie", "A ghost", "A goblin", "A troll"],
        explanation: "Legends say a werewolf can only be hurt by silver.",
      },
      lt: {
        question: "Kuri folkloro būtybė per pilnatį iš žmogaus virsta vilku?",
        correct: "Vilkolakis",
        distractors: ["Vampyras", "Zombis", "Vaiduoklis", "Goblinas", "Trolis"],
        explanation: "Legendos sako, kad vilkolakį sužeisti gali tik sidabras.",
      },
    },
  },
  {
    id: "myt_cr_018",
    category: "mythology",
    subTheme: "creatures",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "English legend — Robin Hood robbed the rich for the poor",
    emoji: "🏹",
    translations: {
      en: {
        question: "Which legendary English outlaw robbed the rich to help the poor?",
        correct: "Robin Hood",
        distractors: ["King Arthur", "Merlin", "William Tell", "Lancelot", "Ivanhoe"],
        explanation: "Robin Hood and his Merry Men lived in Sherwood Forest.",
      },
      lt: {
        question: "Kuris legendinis anglų plėšikas apiplėšdavo turtuolius, kad padėtų vargšams?",
        correct: "Robinas Hudas",
        distractors: ["Karalius Artūras", "Merlinas", "Vilius Telis", "Lanselotas", "Aivenhas"],
        explanation: "Robinas Hudas su bičiuliais gyveno Šervudo girioje.",
      },
    },
  },
  {
    id: "myt_cr_019",
    category: "mythology",
    subTheme: "creatures",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Cryptid folklore — the Yeti of the Himalayas",
    emoji: "📖",
    translations: {
      en: {
        question: "Which snow-dwelling ape-creature is said to roam the Himalayas?",
        correct: "The Yeti",
        distractors: ["Bigfoot", "The Kraken", "A dragon", "A troll", "A genie"],
        explanation: "The Yeti is also called the Abominable Snowman.",
      },
      lt: {
        question: "Kuri sniege gyvenanti beždžionės būtybė esą klaidžioja Himalajuose?",
        correct: "Jetis",
        distractors: ["Bigfutas", "Krakenas", "Drakonas", "Trolis", "Džinas"],
        explanation: "Jetis dar vadinamas Bjauriuoju sniego žmogumi.",
      },
    },
  },
  {
    id: "myt_cr_020",
    category: "mythology",
    subTheme: "creatures",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Folklore/literature — a genie grants wishes from a lamp",
    emoji: "🔮",
    translations: {
      en: {
        question: "In old tales, what magical being grants wishes from a lamp?",
        correct: "A genie",
        distractors: ["A fairy", "A wizard", "A ghost", "An elf", "A goblin"],
        explanation: "The lamp genie is famous from the tales of 1001 Nights.",
      },
      lt: {
        question: "Senuose pasakojimuose kuri magiška būtybė iš lempos pildo norus?",
        correct: "Džinas",
        distractors: ["Fėja", "Burtininkas", "Vaiduoklis", "Elfas", "Goblinas"],
        explanation: "Lempos džinas garsus iš 1001 nakties pasakų.",
      },
    },
  },

  // ===================== SUNKUS (suaugę) =====================
  {
    id: "myt_cr_021",
    category: "mythology",
    subTheme: "creatures",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Heraldry/folklore — the wyvern, a two-legged winged dragon",
    emoji: "🐲",
    translations: {
      en: {
        question: "Which two-legged winged dragon appears on many heraldic shields?",
        correct: "A wyvern",
        distractors: ["A griffin", "A phoenix", "A basilisk", "A chimera", "A hydra"],
        explanation: "A wyvern has two legs, unlike the four-legged classic dragon.",
      },
      lt: {
        question: "Kuris dvikojis sparnuotas drakonas vaizduojamas daugelyje herbų?",
        correct: "Vyvernas",
        distractors: ["Grifas", "Feniksas", "Baziliskas", "Chimera", "Hidra"],
        explanation: "Vyvernas turi dvi kojas, skirtingai nei klasikinis keturkojis drakonas.",
      },
    },
  },
  {
    id: "myt_cr_022",
    category: "mythology",
    subTheme: "creatures",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Legend — the Fountain of Youth restores youth",
    emoji: "⛲",
    translations: {
      en: {
        question: "Which legendary fountain was said to restore youth to those who drank it?",
        correct: "The Fountain of Youth",
        distractors: ["The Wishing Well", "The Spring of Life", "The Magic Lake", "The Trevi Fountain", "The Crystal Pool"],
        explanation: "Explorers like Ponce de Leon were said to seek it.",
      },
      lt: {
        question: "Koks legendinis šaltinis esą grąžindavo jaunystę tam, kas iš jo atsigerdavo?",
        correct: "Jaunystės šaltinis",
        distractors: ["Norų šulinys", "Gyvybės versmė", "Stebuklingas ežeras", "Trevi fontanas", "Krištolinis tvenkinys"],
        explanation: "Sakoma, kad jo ieškojo tokie keliautojai kaip Ponce de Leonas.",
      },
    },
  },
  {
    id: "myt_cr_023",
    category: "mythology",
    subTheme: "creatures",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Middle Eastern legend — the Roc, a giant bird",
    emoji: "🪺",
    translations: {
      en: {
        question: "Which giant bird of Eastern tales was big enough to carry an elephant?",
        correct: "The Roc",
        distractors: ["The Phoenix", "The Griffin", "The Thunderbird", "The Harpy", "The Owl"],
        explanation: "Sinbad the Sailor met the mighty Roc on his voyages.",
      },
      lt: {
        question: "Kuris milžiniškas Rytų pasakų paukštis buvo toks didelis, kad galėjo panešti dramblį?",
        correct: "Rukas",
        distractors: ["Feniksas", "Grifas", "Griaustinio paukštis", "Harpija", "Pelėda"],
        explanation: "Jūreivis Sindbadas savo kelionėse sutiko galingąjį Ruką.",
      },
    },
  },
  {
    id: "myt_cr_024",
    category: "mythology",
    subTheme: "creatures",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Folklore — a vampire is an undead that drinks blood",
    emoji: "🧛",
    translations: {
      en: {
        question: "In legend, what undead being rises from the grave to drink blood?",
        correct: "A vampire",
        distractors: ["A werewolf", "A zombie", "A ghost", "A skeleton", "A wraith"],
        explanation: "The most famous vampire tale is Bram Stoker's Dracula.",
      },
      lt: {
        question: "Kuri legendinė nemirėlių būtybė kyla iš kapo gerti kraujo?",
        correct: "Vampyras",
        distractors: ["Vilkolakis", "Zombis", "Vaiduoklis", "Skeletas", "Šmėkla"],
        explanation: "Garsiausias vampyro pasakojimas — Bramo Stokerio Drakula.",
      },
    },
  },
  {
    id: "myt_cr_025",
    category: "mythology",
    subTheme: "creatures",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Arthurian legend — Avalon, where Arthur was taken to heal",
    emoji: "🌫️",
    translations: {
      en: {
        question: "To which legendary island was King Arthur taken to be healed?",
        correct: "Avalon",
        distractors: ["Atlantis", "Camelot", "El Dorado", "Lyonesse", "Shangri-La"],
        explanation: "Legend says Arthur rests in Avalon, ready to return one day.",
      },
      lt: {
        question: "Į kurią legendinę salą karalius Artūras buvo nugabentas gydytis?",
        correct: "Avalonas",
        distractors: ["Atlantida", "Kamelotas", "El Doradas", "Lionesas", "Šangri La"],
        explanation: "Legenda sako, kad Artūras ilsisi Avalone ir kada nors sugrįš.",
      },
    },
  },
  {
    id: "myt_cr_026",
    category: "mythology",
    subTheme: "creatures",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Latin American folklore — the Chupacabra",
    emoji: "🪄",
    translations: {
      en: {
        question: "Which Latin American legend describes a creature that drains goats' blood?",
        correct: "The Chupacabra",
        distractors: ["Bigfoot", "The Yeti", "Nessie", "The Kraken", "The Banshee"],
        explanation: "Its name means 'goat-sucker' in Spanish.",
      },
      lt: {
        question: "Kuri Lotynų Amerikos legenda pasakoja apie ožkų kraują siurbiantį padarą?",
        correct: "Čupakabra",
        distractors: ["Bigfutas", "Jetis", "Nesė", "Krakenas", "Banšė"],
        explanation: "Jos pavadinimas ispaniškai reiškia ožkų siurbėją.",
      },
    },
  },
  {
    id: "myt_cr_027",
    category: "mythology",
    subTheme: "creatures",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Literature — Shangri-La from the novel Lost Horizon",
    emoji: "⛰️",
    translations: {
      en: {
        question: "Which legendary hidden paradise valley appears in the novel Lost Horizon?",
        correct: "Shangri-La",
        distractors: ["El Dorado", "Atlantis", "Avalon", "Camelot", "Valhalla"],
        explanation: "Shangri-La became a byword for a perfect, peaceful place.",
      },
      lt: {
        question: "Koks legendinis paslėptas rojaus slėnis aprašytas romane Prarastas horizontas?",
        correct: "Šangri La",
        distractors: ["El Doradas", "Atlantida", "Avalonas", "Kamelotas", "Valhala"],
        explanation: "Šangri La tapo tobulos, ramios vietos sinonimu.",
      },
    },
  },
  {
    id: "myt_cr_028",
    category: "mythology",
    subTheme: "creatures",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Japanese folklore — the Kitsune, a shapeshifting fox spirit",
    emoji: "🪨",
    translations: {
      en: {
        question: "What shape-shifting fox spirit appears in Japanese folklore?",
        correct: "The Kitsune",
        distractors: ["The Tengu", "The Kappa", "The Oni", "The Tanuki", "The Dragon"],
        explanation: "Powerful kitsune were said to grow extra tails with age.",
      },
      lt: {
        question: "Kokia pavidalą keičianti lapės dvasia sutinkama japonų folklore?",
        correct: "Kicunė",
        distractors: ["Tengu", "Kapa", "Onis", "Tanukis", "Drakonas"],
        explanation: "Galingos kicunės esą su amžiumi išsiaugindavo papildomas uodegas.",
      },
    },
  },
  {
    id: "myt_cr_029",
    category: "mythology",
    subTheme: "creatures",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Irish folklore — the banshee wails to foretell a death",
    emoji: "👻",
    translations: {
      en: {
        question: "Which wailing woman of Irish legend foretells a coming death?",
        correct: "The Banshee",
        distractors: ["The Siren", "The Valkyrie", "The Nymph", "The Harpy", "The Witch"],
        explanation: "Hearing the banshee's cry was said to warn of loss.",
      },
      lt: {
        question: "Kuri raudanti airių legendos moteris pranašauja artėjančią mirtį?",
        correct: "Banšė",
        distractors: ["Sirena", "Valkirija", "Nimfa", "Harpija", "Ragana"],
        explanation: "Sakyta, kad išgirdus banšės klyksmą artėja netektis.",
      },
    },
  },
  {
    id: "myt_cr_030",
    category: "mythology",
    subTheme: "creatures",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Maritime legend — the Flying Dutchman, a ghost ship",
    emoji: "⛵",
    translations: {
      en: {
        question: "Which legendary ghost ship is doomed to sail the seas forever?",
        correct: "The Flying Dutchman",
        distractors: ["The Mary Celeste", "The Argo", "The Black Pearl", "The Santa Maria", "The Titanic"],
        explanation: "Sailors believed seeing it was a sign of doom.",
      },
      lt: {
        question: "Kuris legendinis vaiduoklių laivas pasmerktas amžinai plaukioti jūromis?",
        correct: "Skraidantysis olandas",
        distractors: ["Mary Celeste", "Argo", "Piratų Juodasis perlas", "Santa Marija", "Titanikas"],
        explanation: "Jūreiviai tikėjo, kad jį pamatyti — pražūties ženklas.",
      },
    },
  },

  // ===================== EKSTREMALUS (žinovai) =====================
  {
    id: "myt_cr_031",
    category: "mythology",
    subTheme: "creatures",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Arthurian legend — Lancelot, greatest knight, loved Guinevere",
    emoji: "🛡️",
    translations: {
      en: {
        question: "Who was the greatest knight of Arthur's court, in love with Queen Guinevere?",
        correct: "Lancelot",
        distractors: ["Galahad", "Gawain", "Percival", "Mordred", "Tristan"],
        explanation: "Lancelot's love for the queen helped bring Camelot's downfall.",
      },
      lt: {
        question: "Kas buvo geriausias Artūro dvaro riteris, įsimylėjęs karalienę Gvinevrą?",
        correct: "Lanselotas",
        distractors: ["Galahadas", "Gavenas", "Persivalis", "Mordredas", "Tristanas"],
        explanation: "Lanseloto meilė karalienei prisidėjo prie Kameloto žlugimo.",
      },
    },
  },
  {
    id: "myt_cr_032",
    category: "mythology",
    subTheme: "creatures",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Australian folklore — the Bunyip, a swamp monster",
    emoji: "🐊",
    translations: {
      en: {
        question: "Which Australian legend tells of a monster lurking in swamps and billabongs?",
        correct: "The Bunyip",
        distractors: ["The Yowie", "Nessie", "The Kraken", "The Wendigo", "The Kelpie"],
        explanation: "The bunyip was said to bellow at night near the water.",
      },
      lt: {
        question: "Kuri Australijos legenda pasakoja apie pelkėse tykantį pabaisą?",
        correct: "Bunjipas",
        distractors: ["Jovis", "Nesė", "Krakenas", "Vendigas", "Kelpis"],
        explanation: "Sakyta, kad bunjipas naktimis baubdavo prie vandens.",
      },
    },
  },
  {
    id: "myt_cr_033",
    category: "mythology",
    subTheme: "creatures",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Slavic folklore — Baba Yaga lives in a hut on chicken legs",
    emoji: "🏚️",
    translations: {
      en: {
        question: "In Slavic folklore, which witch lives in a hut that stands on chicken legs?",
        correct: "Baba Yaga",
        distractors: ["Morgana", "Circe", "The Banshee", "Hecate", "Medusa"],
        explanation: "Baba Yaga flies in a giant mortar, steering with a pestle.",
      },
      lt: {
        question: "Slavų folklore kuri ragana gyvena trobelėje ant vištos kojų?",
        correct: "Baba Jaga",
        distractors: ["Morgana", "Kirkė", "Banšė", "Hekatė", "Medūza"],
        explanation: "Baba Jaga skraido milžiniška grūstuve ir vairuoja ją grūstuvėliu.",
      },
    },
  },
  {
    id: "myt_cr_034",
    category: "mythology",
    subTheme: "creatures",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Persian legend — the manticore (lion, scorpion tail, human face)",
    emoji: "🪙",
    translations: {
      en: {
        question: "Which Persian legend creature is a lion with a scorpion's tail and a human face?",
        correct: "The Manticore",
        distractors: ["The Chimera", "The Sphinx", "The Griffin", "The Basilisk", "The Wyvern"],
        explanation: "The manticore was said to devour its prey whole.",
      },
      lt: {
        question: "Kuri persų legendos būtybė yra liūtas su skorpiono uodega ir žmogaus veidu?",
        correct: "Manticora",
        distractors: ["Chimera", "Sfinksas", "Grifas", "Baziliskas", "Vyvernas"],
        explanation: "Sakyta, kad manticora prarydavo savo grobį visą.",
      },
    },
  },
  {
    id: "myt_cr_035",
    category: "mythology",
    subTheme: "creatures",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Greek-rooted legend — Sirens lured sailors with song",
    emoji: "🎶",
    translations: {
      en: {
        question: "In Greek myth, which creatures lured sailors to their doom with song?",
        correct: "Sirens",
        distractors: ["Gorgons", "Nymphs", "Harpies", "Banshees", "Valkyries"],
        explanation: "Odysseus had himself tied to the mast to resist the Sirens.",
      },
      lt: {
        question: "Kurios graikų mito būtybės daina viliojo jūreivius į pražūtį?",
        correct: "Sirenos",
        distractors: ["Gorgonės", "Nimfos", "Harpijos", "Banšės", "Valkirijos"],
        explanation: "Odisėjas liepėsi prisirišti prie stiebo, kad atsispirtų sirenoms.",
      },
    },
  },
  {
    id: "myt_cr_036",
    category: "mythology",
    subTheme: "creatures",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Celtic folklore — the kelpie, a water horse that drowns riders",
    emoji: "🐴",
    translations: {
      en: {
        question: "Which Celtic water horse lures riders onto its back, then drowns them?",
        correct: "The Kelpie",
        distractors: ["The Selkie", "The Naiad", "Nessie", "The Banshee", "The Centaur"],
        explanation: "The kelpie haunts Scottish rivers and lochs in legend.",
      },
      lt: {
        question: "Kuris keltų vandens arklys privilioja raitelius ant nugaros ir juos nuskandina?",
        correct: "Kelpis",
        distractors: ["Selkis", "Najadė", "Nesė", "Banšė", "Kentauras"],
        explanation: "Kelpis legendose tūno Škotijos upėse ir ežeruose.",
      },
    },
  },
  {
    id: "myt_cr_037",
    category: "mythology",
    subTheme: "creatures",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Scottish/Irish folklore — selkies shed seal skin to become human",
    emoji: "✨",
    translations: {
      en: {
        question: "Which legendary sea folk can shed their seal skin to become human?",
        correct: "Selkies",
        distractors: ["Mermaids", "Sirens", "Nymphs", "Kelpies", "Naiads"],
        explanation: "A selkie who loses its skin is bound to the land.",
      },
      lt: {
        question: "Kurios legendinės jūros būtybės gali nusivilkti ruonio kailį ir tapti žmonėmis?",
        correct: "Selkiai",
        distractors: ["Undinės", "Sirenos", "Nimfos", "Kelpiai", "Najadės"],
        explanation: "Selkis, praradęs kailį, lieka prirakintas prie sausumos.",
      },
    },
  },
  {
    id: "myt_cr_038",
    category: "mythology",
    subTheme: "creatures",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Persian myth — the Simurgh, an ancient wise bird",
    emoji: "🦚",
    translations: {
      en: {
        question: "Which enormous, wise and ancient bird comes from Persian myth?",
        correct: "The Simurgh",
        distractors: ["The Roc", "The Phoenix", "The Thunderbird", "The Griffin", "The Harpy"],
        explanation: "The Simurgh was said to be old enough to have seen the world end thrice.",
      },
      lt: {
        question: "Kuris milžiniškas, išmintingas ir senas paukštis kilęs iš persų mito?",
        correct: "Simurgas",
        distractors: ["Rukas", "Feniksas", "Griaustinio paukštis", "Grifas", "Harpija"],
        explanation: "Sakyta, kad Simurgas toks senas, jog tris kartus matė pasaulio pabaigą.",
      },
    },
  },
  {
    id: "myt_cr_039",
    category: "mythology",
    subTheme: "creatures",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Medieval bestiary — the salamander was said to live in fire",
    emoji: "🔥",
    translations: {
      en: {
        question: "Which creature of medieval legend was believed to live in and survive fire?",
        correct: "The Salamander",
        distractors: ["The Basilisk", "The Wyvern", "The Phoenix", "The Newt", "The Gecko"],
        explanation: "Medieval writers thought the salamander could quench flames.",
      },
      lt: {
        question: "Kuri viduramžių legendos būtybė esą gyvendavo ugnyje ir ją išgyvendavo?",
        correct: "Salamandra",
        distractors: ["Baziliskas", "Vyvernas", "Feniksas", "Tritonas", "Gekonas"],
        explanation: "Viduramžių rašytojai manė, kad salamandra gali gesinti liepsnas.",
      },
    },
  },
  {
    id: "myt_cr_040",
    category: "mythology",
    subTheme: "creatures",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Canadian cryptid folklore — Ogopogo of Okanagan Lake",
    emoji: "🐍",
    translations: {
      en: {
        question: "Which lake monster is said to swim in Canada's Okanagan Lake?",
        correct: "Ogopogo",
        distractors: ["Nessie", "Champ", "The Kraken", "The Bunyip", "Mokele"],
        explanation: "Ogopogo is Canada's most famous lake-monster legend.",
      },
      lt: {
        question: "Kuri ežero pabaisa esą plaukioja Kanados Okanagano ežere?",
        correct: "Ogopogas",
        distractors: ["Nesė", "Čempas", "Krakenas", "Bunjipas", "Mokelė"],
        explanation: "Ogopogas — garsiausia Kanados ežero pabaisos legenda.",
      },
    },
  },
];
