/**
 * mythologyEgypt — 🐫 „Egiptas ir Rytai" potemė (tema „Mitologija").
 *
 * MAŽAS FAILAS pagal potemę. 40 klausimų (10/lygiui). Senovės Egipto dievai/mitai
 * + Mesopotamija (Gilgamešas, Marduk, Tiamatė). SAUGA: tik SENOVĖS mitologija,
 * jokių gyvų religijų; net distraktoriai neutralūs (jokių dabartinių šventraščių).
 * NEKARTOJA graikų/skandinavų potemių.
 *
 * TAISYKLĖS: 1 teisingas + 5 distraktoriai; ≤46 simb.; teisingas NE ilgiausias >+5;
 * LT be vidinių kabučių; jokio atsakymo klausime; emoji neišduoda atsakymo.
 */

import { TriviaQuestion } from "./triviaTypes";

export const MYTHOLOGY_EGYPT: TriviaQuestion[] = [
  // ===================== LENGVAS (9–12 m. vaikas) =====================
  {
    id: "myt_eg_001",
    category: "mythology",
    subTheme: "egypt",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Egyptian mythology — Anubis, jackal-headed god of the dead",
    emoji: "🐺",
    translations: {
      en: {
        question: "Which Egyptian god has a jackal's head and guards the dead?",
        correct: "Anubis",
        distractors: ["Ra", "Horus", "Set", "Thoth", "Osiris"],
        explanation: "Anubis watched over mummies and guided souls to the afterlife.",
      },
      lt: {
        question: "Kuris Egipto dievas turi šakalo galvą ir saugo mirusiuosius?",
        correct: "Anubis",
        distractors: ["Ra", "Horas", "Setas", "Totas", "Ozyris"],
        explanation: "Anubis sergėjo mumijas ir vedė sielas į pomirtinį pasaulį.",
      },
    },
  },
  {
    id: "myt_eg_002",
    category: "mythology",
    subTheme: "egypt",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Egyptian mythology — Ra, the sun god",
    emoji: "☀️",
    translations: {
      en: {
        question: "Who is the Egyptian sun god, king of the gods?",
        correct: "Ra",
        distractors: ["Anubis", "Horus", "Set", "Thoth", "Geb"],
        explanation: "Ra sailed the sun across the sky in his boat each day.",
      },
      lt: {
        question: "Kuris yra Egipto saulės dievas, dievų karalius?",
        correct: "Ra",
        distractors: ["Anubis", "Horas", "Setas", "Totas", "Gebas"],
        explanation: "Ra kasdien savo valtimi plukdė saulę per dangų.",
      },
    },
  },
  {
    id: "myt_eg_003",
    category: "mythology",
    subTheme: "egypt",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Ancient Egypt — mummification preserved the dead",
    emoji: "🧻",
    translations: {
      en: {
        question: "What did ancient Egyptians turn dead bodies into to preserve them?",
        correct: "Mummies",
        distractors: ["Statues", "Fossils", "Stones", "Robots", "Diamonds"],
        explanation: "Bodies were dried and wrapped so the soul could live on.",
      },
      lt: {
        question: "Į ką senovės egiptiečiai vertė mirusiųjų kūnus, kad išsaugotų?",
        correct: "Mumijas",
        distractors: ["Statulas", "Fosilijas", "Akmenis", "Robotus", "Deimantus"],
        explanation: "Kūnai buvo džiovinami ir vyniojami, kad siela gyventų toliau.",
      },
    },
  },
  {
    id: "myt_eg_004",
    category: "mythology",
    subTheme: "egypt",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Egyptian mythology — Horus, the falcon-headed sky god",
    emoji: "🦅",
    translations: {
      en: {
        question: "Which Egyptian sky god has the head of a falcon?",
        correct: "Horus",
        distractors: ["Anubis", "Bastet", "Set", "Thoth", "Sobek"],
        explanation: "Horus is shown as a falcon or a man with a falcon's head.",
      },
      lt: {
        question: "Kuris Egipto dangaus dievas turi sakalo galvą?",
        correct: "Horas",
        distractors: ["Anubis", "Bastetė", "Setas", "Totas", "Sobekas"],
        explanation: "Horas vaizduojamas kaip sakalas arba žmogus su sakalo galva.",
      },
    },
  },
  {
    id: "myt_eg_005",
    category: "mythology",
    subTheme: "egypt",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Ancient Egypt — cats were sacred (goddess Bastet)",
    emoji: "🐈",
    translations: {
      en: {
        question: "Which animal was especially sacred to the Egyptian goddess Bastet?",
        correct: "The cat",
        distractors: ["The dog", "The horse", "The wolf", "The bear", "The goat"],
        explanation: "Cats were linked to the goddess Bastet and deeply respected.",
      },
      lt: {
        question: "Kuris gyvūnas buvo ypač šventas Egipto deivei Bastetei?",
        correct: "Katę",
        distractors: ["Šunį", "Arklį", "Vilką", "Lokį", "Ožką"],
        explanation: "Katės buvo siejamos su deive Bastete ir labai gerbiamos.",
      },
    },
  },
  {
    id: "myt_eg_006",
    category: "mythology",
    subTheme: "egypt",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Egyptian symbol — the ankh means life",
    emoji: "🔑",
    translations: {
      en: {
        question: "Which Egyptian symbol, a cross with a loop on top, means life?",
        correct: "The ankh",
        distractors: ["A star", "A heart", "A circle", "A square", "A spiral"],
        explanation: "Gods are often drawn holding the ankh, the key of life.",
      },
      lt: {
        question: "Koks Egipto simbolis, kryžius su kilpa viršuje, reiškia gyvybę?",
        correct: "Ankhas",
        distractors: ["Žvaigždė", "Širdis", "Apskritimas", "Kvadratas", "Spiralė"],
        explanation: "Dievai dažnai vaizduojami laikantys ankhą — gyvybės raktą.",
      },
    },
  },
  {
    id: "myt_eg_007",
    category: "mythology",
    subTheme: "egypt",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography/history — the Nile was central to Egypt",
    emoji: "🏞️",
    translations: {
      en: {
        question: "Which great river was the lifeline of ancient Egypt?",
        correct: "The Nile",
        distractors: ["The Amazon", "The Thames", "The Ganges", "The Volga", "The Danube"],
        explanation: "Egyptians believed the gods blessed the flooding Nile each year.",
      },
      lt: {
        question: "Kuri didžioji upė buvo senovės Egipto gyvybės gysla?",
        correct: "Nilas",
        distractors: ["Amazonė", "Temzė", "Gangas", "Volga", "Dunojus"],
        explanation: "Egiptiečiai tikėjo, kad dievai kasmet laimina Nilo potvynį.",
      },
    },
  },
  {
    id: "myt_eg_008",
    category: "mythology",
    subTheme: "egypt",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Ancient Egypt — the Great Sphinx (lion body, human head)",
    emoji: "🦁",
    translations: {
      en: {
        question: "Which huge statue has a lion's body and a human head in Egypt?",
        correct: "The Sphinx",
        distractors: ["A dragon", "A centaur", "A mermaid", "A griffin", "A phoenix"],
        explanation: "The Great Sphinx of Giza has guarded the desert for ages.",
      },
      lt: {
        question: "Kuri milžiniška statula Egipte turi liūto kūną ir žmogaus galvą?",
        correct: "Sfinksas",
        distractors: ["Drakonas", "Kentauras", "Undinė", "Grifas", "Feniksas"],
        explanation: "Didysis Gizos sfinksas dykumą saugo jau tūkstantmečius.",
      },
    },
  },
  {
    id: "myt_eg_009",
    category: "mythology",
    subTheme: "egypt",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Ancient Egypt — pharaohs were seen as god-kings",
    emoji: "👑",
    translations: {
      en: {
        question: "What do we call a king of ancient Egypt, seen as a living god?",
        correct: "A pharaoh",
        distractors: ["A knight", "A samurai", "A duke", "A wizard", "A chief"],
        explanation: "Egyptians believed the pharaoh was a god in human form.",
      },
      lt: {
        question: "Kaip vadinamas senovės Egipto karalius, laikytas gyvu dievu?",
        correct: "Faraonas",
        distractors: ["Riteris", "Samurajus", "Hercogas", "Burtininkas", "Vadas"],
        explanation: "Egiptiečiai tikėjo, kad faraonas — dievas žmogaus pavidalu.",
      },
    },
  },
  {
    id: "myt_eg_010",
    category: "mythology",
    subTheme: "egypt",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Egyptian symbol — the scarab beetle (rebirth, luck)",
    emoji: "🪲",
    translations: {
      en: {
        question: "Which beetle did Egyptians treasure as a lucky symbol of rebirth?",
        correct: "The scarab",
        distractors: ["The spider", "The ant", "The bee", "The fly", "The moth"],
        explanation: "The scarab rolling dung was linked to the sun rolling across the sky.",
      },
      lt: {
        question: "Kurį vabalą egiptiečiai brangino kaip laimės ir atgimimo simbolį?",
        correct: "Skarabėjų",
        distractors: ["Vorą", "Skruzdėlę", "Bitę", "Musę", "Kandį"],
        explanation: "Mėšlą ridenantis skarabėjus buvo siejamas su saule danguje.",
      },
    },
  },

  // ===================== VIDUTINIS (12–18 m.) =====================
  {
    id: "myt_eg_011",
    category: "mythology",
    subTheme: "egypt",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Egyptian mythology — Osiris, lord of the afterlife",
    emoji: "🌾",
    translations: {
      en: {
        question: "Who is the Egyptian god of the afterlife and king of the underworld?",
        correct: "Osiris",
        distractors: ["Ra", "Anubis", "Set", "Horus", "Thoth"],
        explanation: "Osiris judges the dead in the Egyptian underworld.",
      },
      lt: {
        question: "Kuris yra Egipto pomirtinio pasaulio dievas, požemio karalius?",
        correct: "Ozyris",
        distractors: ["Ra", "Anubis", "Setas", "Horas", "Totas"],
        explanation: "Ozyris teisia mirusiuosius Egipto požemio pasaulyje.",
      },
    },
  },
  {
    id: "myt_eg_012",
    category: "mythology",
    subTheme: "egypt",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Egyptian mythology — Isis, goddess of magic, wife of Osiris",
    emoji: "✨",
    translations: {
      en: {
        question: "Which Egyptian goddess of magic was the devoted wife of Osiris?",
        correct: "Isis",
        distractors: ["Hathor", "Bastet", "Sekhmet", "Nut", "Maat"],
        explanation: "Isis used powerful magic to restore her husband Osiris.",
      },
      lt: {
        question: "Kuri Egipto magijos deivė buvo ištikima Ozyrio žmona?",
        correct: "Izidė",
        distractors: ["Hator", "Bastetė", "Sechmetė", "Nutė", "Maat"],
        explanation: "Izidė galinga magija sugrąžino savo vyrą Ozyrį.",
      },
    },
  },
  {
    id: "myt_eg_013",
    category: "mythology",
    subTheme: "egypt",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Egyptian mythology — Set, god of chaos, killed Osiris",
    emoji: "🏜️",
    translations: {
      en: {
        question: "Which Egyptian god of chaos murdered his own brother Osiris?",
        correct: "Set",
        distractors: ["Horus", "Anubis", "Thoth", "Ra", "Geb"],
        explanation: "Jealous Set tricked and killed Osiris to seize the throne.",
      },
      lt: {
        question: "Kuris Egipto chaoso dievas nužudė savo brolį Ozyrį?",
        correct: "Setas",
        distractors: ["Horas", "Anubis", "Totas", "Ra", "Gebas"],
        explanation: "Pavydus Setas apgaule nužudė Ozyrį, kad pagrobtų sostą.",
      },
    },
  },
  {
    id: "myt_eg_014",
    category: "mythology",
    subTheme: "egypt",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Egyptian mythology — Thoth, ibis-headed god of wisdom",
    emoji: "🪶",
    translations: {
      en: {
        question: "Which wise Egyptian god has the head of an ibis bird?",
        correct: "Thoth",
        distractors: ["Ra", "Anubis", "Horus", "Set", "Sobek"],
        explanation: "Thoth invented writing and recorded the deeds of gods.",
      },
      lt: {
        question: "Kuris išmintingas Egipto dievas turi ibio paukščio galvą?",
        correct: "Totas",
        distractors: ["Ra", "Anubis", "Horas", "Setas", "Sobekas"],
        explanation: "Totas sugalvojo raštą ir užrašydavo dievų darbus.",
      },
    },
  },
  {
    id: "myt_eg_015",
    category: "mythology",
    subTheme: "egypt",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Egyptian mythology — heart weighed against Maat's feather",
    emoji: "⚖️",
    translations: {
      en: {
        question: "In the afterlife, the heart was weighed against a feather of which goddess?",
        correct: "Maat",
        distractors: ["Isis", "Hathor", "Bastet", "Nut", "Sekhmet"],
        explanation: "If the heart was lighter than Maat's feather, the soul passed on.",
      },
      lt: {
        question: "Pomirtiniame teisme širdis buvo sveriama prieš kurios deivės plunksną?",
        correct: "Maat",
        distractors: ["Izidė", "Hator", "Bastetė", "Nutė", "Sechmetė"],
        explanation: "Jei širdis lengvesnė už Maat plunksną, siela keliaudavo toliau.",
      },
    },
  },
  {
    id: "myt_eg_016",
    category: "mythology",
    subTheme: "egypt",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Ancient Egypt — the Book of the Dead guided souls",
    emoji: "📜",
    translations: {
      en: {
        question: "Which guidebook of spells helped Egyptian souls in the afterlife?",
        correct: "The Book of the Dead",
        distractors: ["The Sun Scroll", "The Spell Map", "The Royal Diary", "The Star Chart", "The Pyramid Plan"],
        explanation: "It held spells to help the soul safely cross the underworld.",
      },
      lt: {
        question: "Kuris burtų vadovas padėjo Egipto sieloms pomirtiniame pasaulyje?",
        correct: "Mirusiųjų knyga",
        distractors: ["Saulės ritinys", "Burtų žemėlapis", "Karaliaus dienoraštis", "Žvaigždžių lentelė", "Piramidės planas"],
        explanation: "Joje surašyti burtai padėdavo sielai saugiai pereiti požemį.",
      },
    },
  },
  {
    id: "myt_eg_017",
    category: "mythology",
    subTheme: "egypt",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Egyptian mythology — Sekhmet, lioness war goddess",
    emoji: "🦁",
    translations: {
      en: {
        question: "Which fierce Egyptian goddess of war was shown as a lioness?",
        correct: "Sekhmet",
        distractors: ["Bastet", "Isis", "Hathor", "Maat", "Nut"],
        explanation: "Sekhmet's fiery breath was said to bring war and healing alike.",
      },
      lt: {
        question: "Kuri nuožmi Egipto karo deivė buvo vaizduojama kaip liūtė?",
        correct: "Sechmetė",
        distractors: ["Bastetė", "Izidė", "Hator", "Maat", "Nutė"],
        explanation: "Sakyta, kad ugninis Sechmetės alsavimas neša ir karą, ir gydymą.",
      },
    },
  },
  {
    id: "myt_eg_018",
    category: "mythology",
    subTheme: "egypt",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Egyptian mythology — Sobek, crocodile-headed god",
    emoji: "🐊",
    translations: {
      en: {
        question: "Which Egyptian god has the head of a crocodile?",
        correct: "Sobek",
        distractors: ["Anubis", "Horus", "Thoth", "Set", "Ra"],
        explanation: "Sobek of the Nile stood for the river's power and fertility.",
      },
      lt: {
        question: "Kuris Egipto dievas turi krokodilo galvą?",
        correct: "Sobekas",
        distractors: ["Anubis", "Horas", "Totas", "Setas", "Ra"],
        explanation: "Nilo dievas Sobekas reiškė upės galią ir vaisingumą.",
      },
    },
  },
  {
    id: "myt_eg_019",
    category: "mythology",
    subTheme: "egypt",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Egyptian symbol — the protective Eye of Horus",
    emoji: "👁️",
    translations: {
      en: {
        question: "The protective Eye amulet belongs to which falcon-headed god?",
        correct: "Horus",
        distractors: ["Anubis", "Set", "Thoth", "Sobek", "Geb"],
        explanation: "The Eye of Horus was worn as a charm for health and safety.",
      },
      lt: {
        question: "Apsauginis Akies amuletas priklauso kuriam sakalagalviui dievui?",
        correct: "Horui",
        distractors: ["Anubiui", "Setui", "Totui", "Sobekui", "Gebui"],
        explanation: "Horo akis buvo nešiojama kaip sveikatos ir saugumo talismanas.",
      },
    },
  },
  {
    id: "myt_eg_020",
    category: "mythology",
    subTheme: "egypt",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Mesopotamian mythology — Gilgamesh, hero of the oldest epic",
    emoji: "📖",
    translations: {
      en: {
        question: "Who is the hero-king of the world's oldest great epic poem?",
        correct: "Gilgamesh",
        distractors: ["Hercules", "Achilles", "Odysseus", "Beowulf", "Sinbad"],
        explanation: "The Epic of Gilgamesh was written in Mesopotamia long ago.",
      },
      lt: {
        question: "Kas yra seniausios pasaulio epinės poemos herojus karalius?",
        correct: "Gilgamešas",
        distractors: ["Heraklis", "Achilas", "Odisėjas", "Beovulfas", "Sindbadas"],
        explanation: "Epas apie Gilgamešą seniai užrašytas Mesopotamijoje.",
      },
    },
  },

  // ===================== SUNKUS (suaugę) =====================
  {
    id: "myt_eg_021",
    category: "mythology",
    subTheme: "egypt",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Mesopotamian mythology — Ishtar (Inanna), love and war",
    emoji: "💕",
    translations: {
      en: {
        question: "Which Mesopotamian goddess of love and war was also called Inanna?",
        correct: "Ishtar",
        distractors: ["Tiamat", "Isis", "Hathor", "Astarte", "Nut"],
        explanation: "Ishtar was one of the most worshipped of the ancient eastern deities.",
      },
      lt: {
        question: "Kuri Mesopotamijos meilės ir karo deivė dar vadinta Inana?",
        correct: "Ištarė",
        distractors: ["Tiamatė", "Izidė", "Hator", "Astartė", "Nutė"],
        explanation: "Ištarė buvo viena labiausiai garbintų senovės Rytų dievybių.",
      },
    },
  },
  {
    id: "myt_eg_022",
    category: "mythology",
    subTheme: "egypt",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Babylonian mythology — Marduk defeated Tiamat",
    emoji: "⚔️",
    translations: {
      en: {
        question: "Which Babylonian chief god defeated the chaos dragon Tiamat?",
        correct: "Marduk",
        distractors: ["Enlil", "Enki", "Anu", "Nabu", "Shamash"],
        explanation: "Marduk split Tiamat's body to form the sky and the earth.",
      },
      lt: {
        question: "Kuris Babilono vyriausiasis dievas nugalėjo chaoso slibiną Tiamatę?",
        correct: "Mardukas",
        distractors: ["Enlilis", "Enkis", "Anu", "Nabu", "Šamašas"],
        explanation: "Mardukas perskėlė Tiamatės kūną ir sukūrė dangų bei žemę.",
      },
    },
  },
  {
    id: "myt_eg_023",
    category: "mythology",
    subTheme: "egypt",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Mesopotamian mythology — Tiamat, primeval sea dragon",
    emoji: "🐉",
    translations: {
      en: {
        question: "What is the name of the saltwater chaos dragon in Mesopotamian myth?",
        correct: "Tiamat",
        distractors: ["Apep", "Jormungandr", "Typhon", "Leviathan", "Hydra"],
        explanation: "From Tiamat's defeated body the world itself was made.",
      },
      lt: {
        question: "Koks vardas chaoso slibinės iš sūraus vandens Mesopotamijos mite?",
        correct: "Tiamatė",
        distractors: ["Apepas", "Jormungandas", "Tifonas", "Leviatanas", "Hidra"],
        explanation: "Iš nugalėtos Tiamatės kūno buvo sukurtas pats pasaulis.",
      },
    },
  },
  {
    id: "myt_eg_024",
    category: "mythology",
    subTheme: "egypt",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Egyptian mythology — Apep (Apophis), serpent of chaos vs Ra",
    emoji: "🐍",
    translations: {
      en: {
        question: "Which giant serpent of chaos battles the sun god Ra every night?",
        correct: "Apep",
        distractors: ["Sobek", "Set", "Tiamat", "Jormungandr", "Python"],
        explanation: "Each night Ra must defeat Apep so the sun can rise again.",
      },
      lt: {
        question: "Kuri milžiniška chaoso gyvatė kas naktį kaunasi su saulės dievu Ra?",
        correct: "Apepas",
        distractors: ["Sobekas", "Setas", "Tiamatė", "Jormungandas", "Pitonas"],
        explanation: "Kas naktį Ra turi nugalėti Apepą, kad saulė vėl pakiltų.",
      },
    },
  },
  {
    id: "myt_eg_025",
    category: "mythology",
    subTheme: "egypt",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Mesopotamia — ziggurats were stepped temple-towers",
    emoji: "🛕",
    translations: {
      en: {
        question: "What do we call the stepped pyramid-temples of ancient Mesopotamia?",
        correct: "Ziggurats",
        distractors: ["Pagodas", "Obelisks", "Pyramids", "Stupas", "Minarets"],
        explanation: "Ziggurats rose in steps with a shrine to a god at the top.",
      },
      lt: {
        question: "Kaip vadinamos senovės Mesopotamijos pakopinės šventyklos bokštai?",
        correct: "Ziguratai",
        distractors: ["Pagodos", "Obeliskai", "Piramidės", "Stupos", "Minaretai"],
        explanation: "Ziguratai kilo pakopomis, o viršuje stovėjo dievo šventovė.",
      },
    },
  },
  {
    id: "myt_eg_026",
    category: "mythology",
    subTheme: "egypt",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Egyptian mythology — Bastet, cat goddess, protector",
    emoji: "🐈‍⬛",
    translations: {
      en: {
        question: "Which gentle Egyptian goddess of home was shown as a cat?",
        correct: "Bastet",
        distractors: ["Sekhmet", "Isis", "Hathor", "Maat", "Nut"],
        explanation: "Bastet protected households, children and joy.",
      },
      lt: {
        question: "Kuri švelni Egipto namų deivė buvo vaizduojama kaip katė?",
        correct: "Bastetė",
        distractors: ["Sechmetė", "Izidė", "Hator", "Maat", "Nutė"],
        explanation: "Bastetė saugojo namus, vaikus ir džiaugsmą.",
      },
    },
  },
  {
    id: "myt_eg_027",
    category: "mythology",
    subTheme: "egypt",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Egyptian mythology — Hathor, cow-horned goddess of love",
    emoji: "🐄",
    translations: {
      en: {
        question: "Which joyful Egyptian goddess of love wore cow horns and a sun disk?",
        correct: "Hathor",
        distractors: ["Isis", "Bastet", "Sekhmet", "Maat", "Nut"],
        explanation: "Hathor was goddess of music, love and motherly joy.",
      },
      lt: {
        question: "Kuri linksma Egipto meilės deivė nešiojo karvės ragus ir saulės diską?",
        correct: "Hator",
        distractors: ["Izidė", "Bastetė", "Sechmetė", "Maat", "Nutė"],
        explanation: "Hator buvo muzikos, meilės ir motiniško džiaugsmo deivė.",
      },
    },
  },
  {
    id: "myt_eg_028",
    category: "mythology",
    subTheme: "egypt",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Mesopotamian mythology — the Epic of Gilgamesh's flood story",
    emoji: "🌊",
    translations: {
      en: {
        question: "The Epic of Gilgamesh includes an early famous story of a great...?",
        correct: "Flood",
        distractors: ["War", "Famine", "Plague", "Earthquake", "Eclipse"],
        explanation: "Its flood tale is one of the oldest ever written down.",
      },
      lt: {
        question: "Epe apie Gilgamešą yra ankstyva garsi istorija apie didįjį...?",
        correct: "Tvaną",
        distractors: ["Karą", "Badmetį", "Marą", "Žemės drebėjimą", "Užtemimą"],
        explanation: "Jo tvano pasakojimas — vienas seniausių kada nors užrašytų.",
      },
    },
  },
  {
    id: "myt_eg_029",
    category: "mythology",
    subTheme: "egypt",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Egyptian mythology — Nut, the sky goddess arching over earth",
    emoji: "🌌",
    translations: {
      en: {
        question: "Which Egyptian sky goddess arched her star-covered body over the earth?",
        correct: "Nut",
        distractors: ["Isis", "Hathor", "Maat", "Bastet", "Sekhmet"],
        explanation: "Each night Nut swallowed the sun, giving birth to it at dawn.",
      },
      lt: {
        question: "Kuri Egipto dangaus deivė žvaigždėtu kūnu išsilenkė virš žemės?",
        correct: "Nutė",
        distractors: ["Izidė", "Hator", "Maat", "Bastetė", "Sechmetė"],
        explanation: "Kas naktį Nutė prarydavo saulę ir aušroje ją vėl pagimdydavo.",
      },
    },
  },
  {
    id: "myt_eg_030",
    category: "mythology",
    subTheme: "egypt",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Egyptian mythology — Geb, the earth god, husband of Nut",
    emoji: "🌍",
    translations: {
      en: {
        question: "Which Egyptian god of the earth was the husband of the sky goddess Nut?",
        correct: "Geb",
        distractors: ["Ra", "Set", "Osiris", "Thoth", "Sobek"],
        explanation: "Egyptians pictured the earth as the body of the god Geb.",
      },
      lt: {
        question: "Kuris Egipto žemės dievas buvo dangaus deivės Nutės vyras?",
        correct: "Gebas",
        distractors: ["Ra", "Setas", "Ozyris", "Totas", "Sobekas"],
        explanation: "Egiptiečiai žemę įsivaizdavo kaip dievo Gebo kūną.",
      },
    },
  },

  // ===================== EKSTREMALUS (žinovai) =====================
  {
    id: "myt_eg_031",
    category: "mythology",
    subTheme: "egypt",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Egyptian mythology — Khepri, scarab god of the dawn sun",
    emoji: "🪲",
    translations: {
      en: {
        question: "Which scarab-headed god rolled the morning sun into the sky?",
        correct: "Khepri",
        distractors: ["Ra", "Atum", "Horus", "Aten", "Amun"],
        explanation: "Khepri was the rising sun; Atum the setting sun.",
      },
      lt: {
        question: "Kuris skarabėjagalvis dievas ridendavo rytinę saulę į dangų?",
        correct: "Khepris",
        distractors: ["Ra", "Atumas", "Horas", "Atenas", "Amonas"],
        explanation: "Khepris buvo tekanti saulė, o Atumas — besileidžianti.",
      },
    },
  },
  {
    id: "myt_eg_032",
    category: "mythology",
    subTheme: "egypt",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Egyptian mythology — Amun (Amun-Ra), king of the gods of Thebes",
    emoji: "🌞",
    translations: {
      en: {
        question: "Which hidden creator-god of Thebes rose to become king of the gods?",
        correct: "Amun",
        distractors: ["Ptah", "Atum", "Khnum", "Geb", "Set"],
        explanation: "Merged with Ra as Amun-Ra, he became Egypt's supreme god.",
      },
      lt: {
        question: "Kuris paslėptas Tebų kūrėjas dievas tapo dievų karaliumi?",
        correct: "Amonas",
        distractors: ["Ptahas", "Atumas", "Khnumas", "Gebas", "Setas"],
        explanation: "Susiliejęs su Ra kaip Amonas-Ra, jis tapo aukščiausiu Egipto dievu.",
      },
    },
  },
  {
    id: "myt_eg_033",
    category: "mythology",
    subTheme: "egypt",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Egyptian mythology — Khnum shaped humans on a potter's wheel",
    emoji: "🏺",
    translations: {
      en: {
        question: "Which ram-headed god shaped human bodies on a potter's wheel?",
        correct: "Khnum",
        distractors: ["Thoth", "Anubis", "Sobek", "Horus", "Ptah"],
        explanation: "Khnum molded each person's body from Nile clay.",
      },
      lt: {
        question: "Kuris avinagalvis dievas lipdė žmonių kūnus ant puodžiaus rato?",
        correct: "Khnumas",
        distractors: ["Totas", "Anubis", "Sobekas", "Horas", "Ptahas"],
        explanation: "Khnumas kiekvieno žmogaus kūną nulipdydavo iš Nilo molio.",
      },
    },
  },
  {
    id: "myt_eg_034",
    category: "mythology",
    subTheme: "egypt",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Ancient Egypt — canopic jars held the organs of the dead",
    emoji: "⚱️",
    translations: {
      en: {
        question: "In what special jars did Egyptians store a mummy's organs?",
        correct: "Canopic jars",
        distractors: ["Clay urns", "Amphorae", "Sarcophagi", "Glass vases", "Bronze cauldrons"],
        explanation: "Four jars, watched by the sons of Horus, held the organs.",
      },
      lt: {
        question: "Kokiose specialiose urnose egiptiečiai laikė mumijos organus?",
        correct: "Kanopinėse urnose",
        distractors: ["Molio puoduose", "Amforose", "Sarkofaguose", "Stiklo vazose", "Bronzos katiluose"],
        explanation: "Keturias urnas, saugomas Horo sūnų, užpildydavo organai.",
      },
    },
  },
  {
    id: "myt_eg_035",
    category: "mythology",
    subTheme: "egypt",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Mesopotamian mythology — Enki (Ea), god of wisdom and water",
    emoji: "💧",
    translations: {
      en: {
        question: "Which Mesopotamian god of wisdom and water was called Enki or Ea?",
        correct: "Enki",
        distractors: ["Enlil", "Anu", "Marduk", "Nabu", "Shamash"],
        explanation: "Enki was a clever helper of humankind in eastern myth.",
      },
      lt: {
        question: "Kuris Mesopotamijos išminties ir vandens dievas vadintas Enkiu ar Ėja?",
        correct: "Enkis",
        distractors: ["Enlilis", "Anu", "Mardukas", "Nabu", "Šamašas"],
        explanation: "Enkis Rytų mituose buvo gudrus žmonijos pagalbininkas.",
      },
    },
  },
  {
    id: "myt_eg_036",
    category: "mythology",
    subTheme: "egypt",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Mesopotamian mythology — Enkidu, Gilgamesh's companion made of clay",
    emoji: "🪨",
    translations: {
      en: {
        question: "Who was Gilgamesh's wild friend, created by the gods from clay?",
        correct: "Enkidu",
        distractors: ["Humbaba", "Utnapishtim", "Marduk", "Lugalbanda", "Nabu"],
        explanation: "Enkidu lived among animals before befriending Gilgamesh.",
      },
      lt: {
        question: "Kas buvo laukinis Gilgamešo draugas, dievų sukurtas iš molio?",
        correct: "Enkidu",
        distractors: ["Humbaba", "Utnapištimas", "Mardukas", "Lugalbanda", "Nabu"],
        explanation: "Enkidu gyveno tarp žvėrių, kol susidraugavo su Gilgamešu.",
      },
    },
  },
  {
    id: "myt_eg_037",
    category: "mythology",
    subTheme: "egypt",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Mesopotamian mythology — Utnapishtim survived the flood",
    emoji: "🛶",
    translations: {
      en: {
        question: "In the Epic of Gilgamesh, who survived the flood and gained immortality?",
        correct: "Utnapishtim",
        distractors: ["Gilgamesh", "Enkidu", "Humbaba", "Marduk", "Ishtar"],
        explanation: "He built a great boat and was rewarded with eternal life.",
      },
      lt: {
        question: "Epe apie Gilgamešą kas išgyveno tvaną ir gavo nemirtingumą?",
        correct: "Utnapištimas",
        distractors: ["Gilgamešas", "Enkidu", "Humbaba", "Mardukas", "Ištarė"],
        explanation: "Jis pastatė didelį laivą ir buvo apdovanotas amžinu gyvenimu.",
      },
    },
  },
  {
    id: "myt_eg_038",
    category: "mythology",
    subTheme: "egypt",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Mesopotamian mythology — Humbaba guarded the Cedar Forest",
    emoji: "🌲",
    translations: {
      en: {
        question: "Which monstrous guardian of the Cedar Forest did Gilgamesh slay?",
        correct: "Humbaba",
        distractors: ["Tiamat", "Apep", "Marduk", "Anzu", "Pazuzu"],
        explanation: "Humbaba's roar was said to shake the mountains.",
      },
      lt: {
        question: "Kurį baisų Kedrų miško sergėtoją nukovė Gilgamešas?",
        correct: "Humbaba",
        distractors: ["Tiamatė", "Apepas", "Mardukas", "Anzu", "Pazuzu"],
        explanation: "Sakyta, kad Humbabos riaumojimas drebina kalnus.",
      },
    },
  },
  {
    id: "myt_eg_039",
    category: "mythology",
    subTheme: "egypt",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Egyptian mythology — Ptah, creator god of craftsmen",
    emoji: "🔨",
    translations: {
      en: {
        question: "Which Egyptian patron of craftsmen was said to create by speaking?",
        correct: "Ptah",
        distractors: ["Khnum", "Thoth", "Amun", "Atum", "Sobek"],
        explanation: "Ptah was believed to bring things into being with his words.",
      },
      lt: {
        question: "Kuris Egipto amatininkų globėjas esą kūrė vien tardamas žodžius?",
        correct: "Ptahas",
        distractors: ["Khnumas", "Totas", "Amonas", "Atumas", "Sobekas"],
        explanation: "Tikėta, kad Ptahas daiktus sukurdavo savo žodžiais.",
      },
    },
  },
  {
    id: "myt_eg_040",
    category: "mythology",
    subTheme: "egypt",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Egyptian mythology — the Duat, the underworld",
    emoji: "🌑",
    translations: {
      en: {
        question: "What was the Egyptian underworld, crossed by the sun each night, called?",
        correct: "The Duat",
        distractors: ["Hades", "Helheim", "The Styx", "Olympus", "Elysium"],
        explanation: "The sun god sailed through the Duat before rising at dawn.",
      },
      lt: {
        question: "Kaip vadinosi Egipto požemio pasaulis, per kurį naktį keliavo saulė?",
        correct: "Duatas",
        distractors: ["Hadas", "Helheimas", "Stiksas", "Olimpas", "Elizijus"],
        explanation: "Saulės dievas perplaukdavo Duatą, kol aušroje vėl pakildavo.",
      },
    },
  },
];
