/**
 * natureMinds — 🧠 „Gyvūnų protas" potemė (tema „Gamta ir gyvūnai").
 *
 * MAŽAS FAILAS. 40 klausimų (10/lygiui). Gyvūnų PROTAS/ELGESYS: įrankiai, bendravimas,
 * atmintis, socialumas, savimonė. SKIRIASI nuo „supergalių" (kūnas/gebėjimai) ir nuo
 * esamų gamtos „faktų" — čia tik smegenys/elgesys.
 *
 * topic: "minds" (NatureTopic) — startNatureGame filtruoja pagal `topic`.
 * TAISYKLĖS: 1 teisingas + 5 distraktoriai; ≤46 simb.; teisingas NE ilgiausias >+5;
 * LT natūrali; jokio atsakymo klausime; EMOJI NEUTRALUS (apie protą, ne apie gyvūną).
 */

import { TriviaQuestion } from "./triviaTypes";

export const NATURE_MINDS: TriviaQuestion[] = [
  // ===================== LENGVAS (9–12 m. vaikas) =====================
  {
    id: "nat_min_001",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Parrots can mimic human speech — encyclopedic",
    emoji: "🗣️",
    translations: {
      en: {
        question: "The bird famous for copying human words",
        correct: "Parrot",
        distractors: ["Sparrow", "Pigeon", "Duck", "Owl", "Robin"],
        explanation: "Some parrots learn hundreds of words and even short phrases.",
      },
      lt: {
        question: "Paukštis, garsus žmogaus žodžių mėgdžiojimu",
        correct: "Papūga",
        distractors: ["Žvirblis", "Balandis", "Antis", "Pelėda", "Liepsnelė"],
        explanation: "Kai kurios papūgos išmoksta šimtus žodžių ir net trumpas frazes.",
      },
    },
  },
  {
    id: "nat_min_002",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Elephants have long, strong memories — encyclopedic",
    emoji: "🧠",
    translations: {
      en: {
        question: "Which animal is famous for 'never forgetting' thanks to a great memory?",
        correct: "Elephant",
        distractors: ["Mouse", "Rabbit", "Chicken", "Goldfish", "Frog"],
        explanation: "Herds remember faraway water holes and old friends for decades.",
      },
      lt: {
        question: "Kuris gyvūnas dėl puikios atminties garsėja tuo, kad niekada nepamiršta?",
        correct: "Dramblys",
        distractors: ["Pelė", "Triušis", "Višta", "Auksinė žuvelė", "Varlė"],
        explanation: "Bandos dešimtmečiais atsimena tolimas vandens vietas ir senus draugus.",
      },
    },
  },
  {
    id: "nat_min_003",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Dolphins are highly intelligent and communicate with clicks/whistles — encyclopedic",
    emoji: "💡",
    translations: {
      en: {
        question: "The clever sea animal that 'talks' in clicks and learns tricks fast",
        correct: "Dolphin",
        distractors: ["Tuna", "Shark", "Jellyfish", "Crab", "Seahorse"],
        explanation: "Dolphins are among the smartest animals in the ocean.",
      },
      lt: {
        question: "Gudrus jūros gyvūnas, spragsėjimais kalbantis ir greit išmokstantis triukų",
        correct: "Delfinas",
        distractors: ["Tunas", "Ryklys", "Medūza", "Krabas", "Jūrų arkliukas"],
        explanation: "Delfinai yra vieni protingiausių vandenyno gyvūnų.",
      },
    },
  },
  {
    id: "nat_min_004",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Dogs are unusually good at following human pointing gestures — cognition research",
    emoji: "🧠",
    translations: {
      en: {
        question: "Dogs are surprisingly good at understanding which human signal?",
        correct: "Pointing",
        distractors: ["Colours", "Maths", "Maps", "Music", "Reading"],
        explanation: "Dogs follow a pointing finger easily — even clever chimps struggle with it.",
      },
      lt: {
        question: "Kurį žmogaus ženklą šunys supranta nuostabiai gerai?",
        correct: "Rodymą pirštu",
        distractors: ["Spalvas", "Matematiką", "Žemėlapius", "Muziką", "Skaitymą"],
        explanation: "Šuo lengvai seka rodantį pirštą — net gudrioms šimpanzėms tai sunku.",
      },
    },
  },
  {
    id: "nat_min_005",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Squirrels cache nuts and recover them later — encyclopedic",
    emoji: "🧩",
    translations: {
      en: {
        question: "The animal that hides nuts and digs them up again later",
        correct: "Squirrel",
        distractors: ["Rabbit", "Mouse", "Hedgehog", "Mole", "Fox"],
        explanation: "It uses memory and smell to find food it buried months ago.",
      },
      lt: {
        question: "Gyvūnas, slepiantis riešutus ir vėliau juos vėl atsikasantis",
        correct: "Voverė",
        distractors: ["Triušis", "Pelė", "Ežys", "Kurmis", "Lapė"],
        explanation: "Ji pasitelkia atmintį ir uoslę, kad rastų prieš mėnesius užkastą maistą.",
      },
    },
  },
  {
    id: "nat_min_006",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Crows are among the smartest birds, solving puzzles — encyclopedic",
    emoji: "🧠",
    translations: {
      en: {
        question: "Which black bird is famous for being clever and solving puzzles?",
        correct: "Crow",
        distractors: ["Sparrow", "Pigeon", "Duck", "Chicken", "Robin"],
        explanation: "Crows can work out tricky problems to reach a treat.",
      },
      lt: {
        question: "Kuris juodas paukštis garsus gudrumu ir galvosūkių sprendimu?",
        correct: "Varna",
        distractors: ["Žvirblis", "Balandis", "Antis", "Višta", "Liepsnelė"],
        explanation: "Varnos sugeba išspręsti keblias užduotis, kad pasiektų skanėstą.",
      },
    },
  },
  {
    id: "nat_min_007",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Honeybees communicate flower locations with the waggle dance — encyclopedic",
    emoji: "💡",
    translations: {
      en: {
        question: "How do honeybees tell each other where flowers are?",
        correct: "A special dance",
        distractors: ["A song", "A smell", "A colour", "A call", "A chalk drawing"],
        explanation: "The 'waggle dance' points hive-mates toward the food.",
      },
      lt: {
        question: "Kaip bitės viena kitai pasako, kur yra gėlės?",
        correct: "Ypatingu šokiu",
        distractors: ["Daina", "Kvapu", "Spalva", "Šūksniu", "Spalvotu piešiniu"],
        explanation: "Vingiuojantis šokis nukreipia avilio drauges link maisto.",
      },
    },
  },
  {
    id: "nat_min_008",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Pigs are highly intelligent farm animals — encyclopedic",
    emoji: "🧠",
    translations: {
      en: {
        question: "The farm animal far smarter than people expect, learning tricks fast",
        correct: "Pig",
        distractors: ["Sheep", "Cow", "Duck", "Goat", "Hen"],
        explanation: "Pigs can learn their name, simple games and even tidy their pen.",
      },
      lt: {
        question: "Ūkio gyvūnas, kur kas protingesnis, nei manoma, ir greit išmokstantis triukų",
        correct: "Kiaulė",
        distractors: ["Avis", "Karvė", "Antis", "Ožka", "Višta"],
        explanation: "Kiaulės išmoksta savo vardą, paprastus žaidimus ir net susitvarko gardą.",
      },
    },
  },
  {
    id: "nat_min_009",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Beavers build dams and lodges — encyclopedic",
    emoji: "🧩",
    translations: {
      en: {
        question: "The animal that teams up to build dams across streams",
        correct: "Beaver",
        distractors: ["Otter", "Duck", "Frog", "Fish", "Turtle"],
        explanation: "Beavers fell trees and stack them to flood a safe pond home.",
      },
      lt: {
        question: "Gyvūnas, drauge statantis užtvankas per upelius",
        correct: "Bebras",
        distractors: ["Ūdra", "Antis", "Varlė", "Žuvis", "Vėžlys"],
        explanation: "Bebrai verčia medžius ir juos krauna, kad užtvindytų saugų tvenkinį-namus.",
      },
    },
  },
  {
    id: "nat_min_010",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Octopuses can open jars to reach food — encyclopedic",
    emoji: "🧩",
    translations: {
      en: {
        question: "Octopuses are so clever they can do what with a closed jar?",
        correct: "Open it",
        distractors: ["Eat it", "Paint it", "Stack it", "Float it", "Bury it"],
        explanation: "It works out how to twist the lid to get the snack inside.",
      },
      lt: {
        question: "Ką su uždaru stiklainiu sugeba padaryti gudrieji aštuonkojai?",
        correct: "Jį atidaryti",
        distractors: ["Jį suėsti", "Jį nudažyti", "Jį sukrauti", "Jį plukdyti", "Jį užkasti"],
        explanation: "Jis sugalvoja, kaip pasukti dangtelį, kad pasiektų viduje esantį skanėstą.",
      },
    },
  },

  // ===================== VIDUTINIS (12–18 m. paauglys) =====================
  {
    id: "nat_min_011",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Gorilla Koko learned over 1,000 sign-language signs — widely reported",
    emoji: "🗣️",
    translations: {
      en: {
        question: "Which ape became famous for being taught hundreds of sign-language signs?",
        correct: "Gorilla",
        distractors: ["Orangutan", "Baboon", "Gibbon", "Lemur", "Macaque"],
        explanation: "A gorilla named Koko reportedly used hundreds of signs to share feelings and wants.",
      },
      lt: {
        question: "Kuri beždžionė išgarsėjo išmokyta šimtų gestų kalbos ženklų?",
        correct: "Gorila",
        distractors: ["Orangutanas", "Babuinas", "Gibonas", "Lemūras", "Makaka"],
        explanation: "Pasakojama, kad gorila vardu Koko šimtais gestų dalijosi jausmais ir norais.",
      },
    },
  },
  {
    id: "nat_min_012",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Rats emit ultrasonic 'laughter' when tickled/playing — peer-reviewed",
    emoji: "🧠",
    translations: {
      en: {
        question: "Studies show that rats, when tickled and playing, seem to do what?",
        correct: "Laugh",
        distractors: ["Cry", "Sing", "Dance", "Glow", "Sleep"],
        explanation: "They make happy ultrasonic squeaks too high for us to hear.",
      },
      lt: {
        question: "Ką, tyrimų duomenimis, kutenamos ir žaidžiančios žiurkės tarsi daro?",
        correct: "Juokiasi",
        distractors: ["Verkia", "Dainuoja", "Šoka", "Švyti", "Miega"],
        explanation: "Jos cypsi laimingais ultragarsais, per aukštais mūsų ausiai.",
      },
    },
  },
  {
    id: "nat_min_013",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Sea otters use rocks to crack open shellfish — encyclopedic",
    emoji: "🛠️",
    translations: {
      en: {
        question: "The animal that uses a rock as a tool to crack open shellfish",
        correct: "Sea otter",
        distractors: ["Seal", "Dolphin", "Penguin", "Walrus", "Beaver"],
        explanation: "It floats on its back and bangs the shell on a stone on its chest.",
      },
      lt: {
        question: "Gyvūnas, naudojantis akmenį kaip įrankį moliuskams skelti",
        correct: "Jūrų ūdra",
        distractors: ["Ruonis", "Delfinas", "Pingvinas", "Vėplys", "Bebras"],
        explanation: "Ji plūduriuoja ant nugaros ir daužo kiautą į akmenį ant krūtinės.",
      },
    },
  },
  {
    id: "nat_min_014",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Clark's nutcracker remembers thousands of hidden seed caches — ornithology",
    emoji: "🧩",
    translations: {
      en: {
        question: "The bird that hides thousands of seeds and recalls the spots months later",
        correct: "Nutcracker",
        distractors: ["Pigeon", "Duck", "Swan", "Sparrow", "Seagull"],
        explanation: "Its astonishing memory maps thousands of buried snacks.",
      },
      lt: {
        question: "Paukštis, paslepiantis tūkstančius sėklų ir po mėnesių prisimenantis vietas",
        correct: "Riešutinė",
        distractors: ["Balandis", "Antis", "Gulbė", "Žvirblis", "Žuvėdra"],
        explanation: "Jos nuostabi atmintis žymi tūkstančius užkastų skanėstų.",
      },
    },
  },
  {
    id: "nat_min_015",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Elephants show grieving behaviour over dead herd members — behavioural research",
    emoji: "🧠",
    translations: {
      en: {
        question: "Elephants are known to do what when a herd member dies?",
        correct: "Seem to mourn",
        distractors: ["Ignore it", "Eat more", "Migrate at once", "Sing", "Fall asleep"],
        explanation: "They gently touch the bones and stay quietly by the body.",
      },
      lt: {
        question: "Ką, kaip žinoma, drambliai daro, kai miršta bandos narys?",
        correct: "Tarsi gedi",
        distractors: ["Nekreipia dėmesio", "Daugiau ėda", "Tuoj iškeliauja", "Dainuoja", "Užmiega"],
        explanation: "Jie švelniai liečia kaulus ir tyliai stovi prie kūno.",
      },
    },
  },
  {
    id: "nat_min_016",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Chimpanzees fish for termites with stripped sticks — Jane Goodall / encyclopedic",
    emoji: "🛠️",
    translations: {
      en: {
        question: "Chimpanzees use a thin stick as a tool to do what?",
        correct: "Fish for termites",
        distractors: ["Comb hair", "Make fire", "Draw", "Count", "Brush its own teeth"],
        explanation: "They poke a stick into a mound and lick off the clinging termites.",
      },
      lt: {
        question: "Kam šimpanzės naudoja ploną pagaliuką kaip įrankį?",
        correct: "Gaudytų termitus",
        distractors: ["Šukuotų plaukus", "Kurtų ugnį", "Pieštų", "Skaičiuotų", "Valytų dantis"],
        explanation: "Jos kiša pagaliuką į termityną ir nulaižo prilipusius termitus.",
      },
    },
  },
  {
    id: "nat_min_017",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Sheep can recognise and remember many individual faces — research",
    emoji: "🧠",
    translations: {
      en: {
        question: "Which farm animal can recognise and remember dozens of faces for years?",
        correct: "Sheep",
        distractors: ["Cow", "Pig", "Goat", "Horse", "Duck"],
        explanation: "Tests show sheep remember about 50 faces of friends and people.",
      },
      lt: {
        question: "Kuris ūkio gyvūnas gali atpažinti ir metų metus atsiminti dešimtis veidų?",
        correct: "Avis",
        distractors: ["Karvė", "Kiaulė", "Ožka", "Arklys", "Antis"],
        explanation: "Tyrimai rodo, kad avys atsimena apie 50 draugų ir žmonių veidų.",
      },
    },
  },
  {
    id: "nat_min_018",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Dolphins use unique 'signature whistles' like names — peer-reviewed",
    emoji: "🗣️",
    translations: {
      en: {
        question: "Dolphins call each other using a unique whistle that works like a what?",
        correct: "Name",
        distractors: ["Song", "Colour", "Bubble", "Smell", "Dance"],
        explanation: "Each dolphin invents its own whistle and others use it to call it.",
      },
      lt: {
        question: "Kuo delfinams tampa unikalus švilpesys, kuriuo jie šaukia vienas kitą?",
        correct: "Vardas",
        distractors: ["Daina", "Spalva", "Burbulas", "Kvapas", "Šokis"],
        explanation: "Kiekvienas delfinas sukuria savo švilpesį, kiti juo jį pasišaukia.",
      },
    },
  },
  {
    id: "nat_min_019",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Pigeons have been trained to spot tumours in medical images — published study",
    emoji: "🧠",
    translations: {
      en: {
        question: "Pigeons have surprised scientists by learning to spot what in images?",
        correct: "Tumours",
        distractors: ["Bones", "Colours", "Names", "Dates", "Letters"],
        explanation: "Trained pigeons could pick out cancer in scans almost like experts.",
      },
      lt: {
        question: "Ką balandžiai nustebino mokslininkus išmokę pastebėti medicininiuose vaizduose?",
        correct: "Navikus",
        distractors: ["Kaulus", "Spalvas", "Vardus", "Datas", "Raides"],
        explanation: "Apmokyti balandžiai vėžį skenuose atpažino beveik kaip ekspertai.",
      },
    },
  },
  {
    id: "nat_min_020",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Japanese macaques learned to wash sweet potatoes and spread it culturally — primatology",
    emoji: "🧩",
    translations: {
      en: {
        question: "Japanese macaques learned a new habit from each other — washing their what?",
        correct: "Food",
        distractors: ["Hands only", "Babies", "Stones", "Fur only", "Tools"],
        explanation: "One monkey washed sandy potatoes; soon the whole troop copied it.",
      },
      lt: {
        question: "Ką japonų makakos viena iš kitos išmoko plauti, perimdamos naują įprotį?",
        correct: "Maistą",
        distractors: ["Tik rankas", "Mažylius", "Akmenis", "Tik kailį", "Įrankius"],
        explanation: "Viena beždžionė nuplovė smėlėtas bulves; netrukus visa banda ją pamėgdžiojo.",
      },
    },
  },

  // ===================== SUNKUS (suaugęs, kuris domisi) =====================
  {
    id: "nat_min_021",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Magpies were the first birds shown to pass the mirror self-recognition test — study",
    emoji: "🪞",
    translations: {
      en: {
        question: "The first bird shown to recognise itself in a mirror",
        correct: "Magpie",
        distractors: ["Sparrow", "Pigeon", "Robin", "Crow", "Duck"],
        explanation: "In a famous 2008 study a marked magpie seemed to use the mirror to reach the spot — though later attempts were mixed.",
      },
      lt: {
        question: "Paukštis, pirmas pasižymėjęs gebėjimu atpažinti save veidrodyje",
        correct: "Šarka",
        distractors: ["Žvirblis", "Balandis", "Liepsnelė", "Varna", "Antis"],
        explanation: "Garsiame 2008 m. tyrime pažymėta šarka tarsi naudojosi veidrodžiu, kad pasiektų dėmę, nors vėlesni bandymai buvo nevienodi.",
      },
    },
  },
  {
    id: "nat_min_022",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "New Caledonian crows craft hooked tools from twigs and leaves — peer-reviewed",
    emoji: "🛠️",
    translations: {
      en: {
        question: "New Caledonian crows are famous for making hooked tools out of what?",
        correct: "Twigs and leaves",
        distractors: ["Carved stone", "Bone", "Mud", "Wax", "Shell"],
        explanation: "They shape a tiny hook to fish grubs out of holes — rare in animals.",
      },
      lt: {
        question: "Iš ko Naujosios Kaledonijos varnos garsėja gamindamos kabliukus?",
        correct: "Šakelių ir lapų",
        distractors: ["Skaldyto akmens", "Kaulo", "Purvo", "Vaško", "Kiauto"],
        explanation: "Jos suformuoja mažytį kabliuką lervoms iš skylių traukti — reta tarp gyvūnų.",
      },
    },
  },
  {
    id: "nat_min_023",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Scrub jays remember what, where and when they cached food — Clayton & Dickinson",
    emoji: "🧩",
    translations: {
      en: {
        question: "Scrub jays recall not just where they hid food, but also what?",
        correct: "When they hid it",
        distractors: ["The weather", "The finder", "The colour", "The price", "Nothing else"],
        explanation: "They retrieve perishable food first, before it can rot — a memory of time.",
      },
      lt: {
        question: "Ką, be paslėpto maisto vietos, krūmžylės dar prisimena?",
        correct: "Kada jį paslėpė",
        distractors: ["Kokie buvo orai", "Kas jį ras", "Spalvą", "Kainą", "Nieko daugiau"],
        explanation: "Greit gendantį maistą jos pasiima pirma, kol nesugedo — tai laiko atmintis.",
      },
    },
  },
  {
    id: "nat_min_024",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Orcas pass on distinct hunting techniques across generations (culture) — marine biology",
    emoji: "🧠",
    translations: {
      en: {
        question: "The animal that teaches its young special hunting tricks, passing on 'culture'",
        correct: "Orca",
        distractors: ["Tuna", "Jellyfish", "Crab", "Seahorse", "Eel"],
        explanation: "Different pods have their own methods, taught from parent to calf.",
      },
      lt: {
        question: "Gyvūnas, mokantis jauniklius ypatingų medžioklės gudrybių ir taip perduodantis kultūrą",
        correct: "Orka",
        distractors: ["Tunas", "Medūza", "Krabas", "Jūrų arkliukas", "Ungurys"],
        explanation: "Skirtingi būriai turi savo būdus, perduodamus iš tėvų jaunikliams.",
      },
    },
  },
  {
    id: "nat_min_025",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Leafcutter ants farm fungus on cut leaves — encyclopedic",
    emoji: "🧩",
    translations: {
      en: {
        question: "Which insects 'farm', growing fungus to eat on chewed-up leaves?",
        correct: "Leafcutter ants",
        distractors: ["Rhino beetles", "Moths", "Flies", "Wasps", "Crickets"],
        explanation: "Their huge colonies run underground gardens with different jobs for each ant.",
      },
      lt: {
        question: "Kurie vabzdžiai ūkininkauja — augina grybus maistui ant sukramtytų lapų?",
        correct: "Lapdorės skruzdėlės",
        distractors: ["Raganosiniai vabalai", "Drugiai", "Musės", "Vapsvos", "Naktiniai svirpliai"],
        explanation: "Jų didžiulės kolonijos valdo požeminius sodus su skirtingais darbais kiekvienai.",
      },
    },
  },
  {
    id: "nat_min_026",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "About two-thirds of an octopus's neurons are in its arms — neuroscience",
    emoji: "🧠",
    translations: {
      en: {
        question: "Most of an octopus's brain cells are surprisingly located where?",
        correct: "In its arms",
        distractors: ["In the eyes", "In the skin", "In the heart", "In the gills", "In the suckers"],
        explanation: "Each arm can taste, feel and partly 'think' almost on its own.",
      },
      lt: {
        question: "Kur netikėtai yra daugiausia aštuonkojo smegenų ląstelių?",
        correct: "Jo rankose",
        distractors: ["Akyse", "Odoje", "Širdyje", "Žiaunose", "Siurbtukuose"],
        explanation: "Kiekviena ranka gali ragauti, jausti ir iš dalies tarsi mąstyti pati.",
      },
    },
  },
  {
    id: "nat_min_027",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Lions assess the number of roaring rivals before deciding to approach — behavioural study",
    emoji: "🧠",
    translations: {
      en: {
        question: "Lions seem to 'count' something before deciding whether to fight — what?",
        correct: "Roaring rivals",
        distractors: ["Stars", "Their cubs", "Trees", "Days", "Steps"],
        explanation: "By the number of roars they hear, they judge if their side outnumbers the others.",
      },
      lt: {
        question: "Ką liūtai tarsi suskaičiuoja prieš nuspręsdami, ar kautis?",
        correct: "Riaumojančius varžovus",
        distractors: ["Žvaigždes", "Savo bandos jauniklius", "Medžius", "Dienas", "Žingsnius"],
        explanation: "Pagal girdimų riaumojimų skaičių jie sprendžia, ar jų pusė gausesnė.",
      },
    },
  },
  {
    id: "nat_min_028",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Dogs can be trained to detect diseases like cancer by smell — medical research",
    emoji: "🧠",
    translations: {
      en: {
        question: "Dogs are clever and keen-nosed enough to be trained to sniff out what?",
        correct: "Diseases",
        distractors: ["Lies", "Ghosts", "Wi-Fi", "Metals", "Numbers"],
        explanation: "Some dogs can smell cancer or warn of a coming seizure.",
      },
      lt: {
        question: "Ką užuosti gali būti išmokyti šunys, kurie yra gudrūs ir uoslūs?",
        correct: "Ligas",
        distractors: ["Melą", "Vaiduoklius", "Wi-Fi", "Metalus", "Skaičius"],
        explanation: "Kai kurie šunys užuodžia vėžį ar perspėja apie artėjantį priepuolį.",
      },
    },
  },
  {
    id: "nat_min_029",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Chimpanzees make leaf 'sponges' to soak up drinking water — primatology",
    emoji: "🛠️",
    translations: {
      en: {
        question: "Chimpanzees chew leaves into a 'sponge' in order to do what?",
        correct: "Soak up water",
        distractors: ["Build a nest", "Make a hat", "Clean wounds", "Catch ants", "Start fire"],
        explanation: "They dip the leaf sponge into a hollow and squeeze the water into their mouth.",
      },
      lt: {
        question: "Kam šimpanzės sukramto lapus į kempinę?",
        correct: "Pasisemti vandens",
        distractors: ["Susukti lizdą", "Pasidaryti kepurę", "Valyti žaizdas", "Gaudyti skruzdes", "Įkurti ugnį"],
        explanation: "Lapų kempinę jos pamerkia į įdubą ir vandenį išspaudžia į burną.",
      },
    },
  },
  {
    id: "nat_min_030",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Capuchin monkeys reject unequal pay (fairness experiment) — Frans de Waal",
    emoji: "🧠",
    translations: {
      en: {
        question: "Capuchin monkeys show a sense of 'fairness' by refusing what?",
        correct: "Unequal rewards",
        distractors: ["All of their food", "Water", "Toys", "Sleep", "Company"],
        explanation: "If a partner gets a tastier treat for the same task, they protest and refuse.",
      },
      lt: {
        question: "Ko atsisakydami kapucinai parodo teisingumo jausmą?",
        correct: "Nelygaus atlygio",
        distractors: ["Viso maisto", "Vandens", "Žaislų", "Miego", "Draugijos"],
        explanation: "Jei partneris už tą patį darbą gauna skanesnį skanėstą, jie protestuoja ir atsisako.",
      },
    },
  },

  // ===================== EKSTREMALUS (srities žinovas) =====================
  {
    id: "nat_min_031",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Alex the African grey parrot understood numbers, colours and concepts — Pepperberg",
    emoji: "🗣️",
    translations: {
      en: {
        question: "Alex the African grey parrot famously could do what, rare for a bird?",
        correct: "Count and name colours",
        distractors: ["Only mimic", "Read books", "Write words", "Solve maths equations", "Sing operas"],
        explanation: "He answered questions about number, shape and colour with real understanding.",
      },
      lt: {
        question: "Ką, paukščiui retai būdinga, pagarsėjo mokanti pilkoji žako papūga Aleksas?",
        correct: "Skaičiuoti ir vardyti spalvas",
        distractors: ["Tik mėgdžioti", "Skaityti knygas", "Rašyti žodžius", "Spręsti sudėtingas lygtis", "Dainuoti operas"],
        explanation: "Jis tikrai suprasdamas atsakydavo apie skaičių, formą ir spalvą.",
      },
    },
  },
  {
    id: "nat_min_032",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Cleaner wrasse fish passed a version of the mirror mark test — 2019 study",
    emoji: "🪞",
    translations: {
      en: {
        question: "Surprisingly, a cleaner wrasse recently passed a version of which test?",
        correct: "The mirror test",
        distractors: ["A maze test", "A hearing test", "A counting test", "A speed test", "A taste test"],
        explanation: "It tried to remove a mark it could only see in a mirror — a first for a fish.",
      },
      lt: {
        question: "Kurio testo versiją netikėtai neseniai išlaikė valytoja lūpažuvė?",
        correct: "Veidrodžio testą",
        distractors: ["Labirinto testą", "Klausos testą", "Skaičiavimo testą", "Greičio testą", "Skonio testą"],
        explanation: "Ji bandė pašalinti dėmę, kurią matė tik veidrodyje — pirmas toks atvejis žuviai.",
      },
    },
  },
  {
    id: "nat_min_033",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Apes and dolphins show 'metacognition' — awareness of their own uncertainty — research",
    emoji: "🧠",
    translations: {
      en: {
        question: "Apes and dolphins show 'metacognition' — they seem to know when they what?",
        correct: "Don't know an answer",
        distractors: ["Are hungry", "Are tired", "Are being watched closely", "Are cold", "Are old"],
        explanation: "Given a hard test, they choose to 'skip' it, sensing their own uncertainty.",
      },
      lt: {
        question: "Ką beždžionės ir delfinai, rodydami metapažinimą, tarsi žino apie save?",
        correct: "Nežino atsakymo",
        distractors: ["Yra alkani", "Yra pavargę", "Yra stebimi", "Yra sušalę", "Yra seni"],
        explanation: "Gavę sunkią užduotį, jie pasirenka ją praleisti, nujausdami savo netikrumą.",
      },
    },
  },
  {
    id: "nat_min_034",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Cuttlefish passed a delayed-gratification ('marshmallow') style test — 2021 study",
    emoji: "🧩",
    translations: {
      en: {
        question: "Cuttlefish showed self-control by resisting a snack to get a better one — like which test?",
        correct: "The marshmallow test",
        distractors: ["The mirror test", "The maze test", "The Turing test", "The hearing test", "The vision test"],
        explanation: "They waited for a tastier shrimp instead of grabbing an instant snack.",
      },
      lt: {
        question: "Į kurį testą panašiai sepijos parodė savitvardą, dėl geresnio kąsnio atsispyrusios prastesniam?",
        correct: "Zefyro testą",
        distractors: ["Veidrodžio testą", "Labirinto testą", "Tiuringo testą", "Klausos testą", "Regos testą"],
        explanation: "Jos laukė skanesnės krevetės, užuot stvėrusios momentinį užkandį.",
      },
    },
  },
  {
    id: "nat_min_035",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Bumblebees learned to roll a ball to a goal for reward, and learned by watching — 2017 study",
    emoji: "🧩",
    translations: {
      en: {
        question: "Bumblebees surprised scientists by learning to roll a ball for a reward by doing what?",
        correct: "Watching others",
        distractors: ["Pure luck", "Smelling it", "Being born with it", "Random tries", "Copying humans"],
        explanation: "Bees that watched a trained bee learned the trick far faster — true social learning.",
      },
      lt: {
        question: "Kaip kamanės, nustebinusios mokslininkus, išmoko riedinti kamuoliuką dėl atlygio?",
        correct: "Stebėdamos kitas",
        distractors: ["Gryna sėkme", "Užuosdamos", "Iš prigimties", "Atsitiktinai", "Mėgdžiodamos žmones"],
        explanation: "Stebėjusios apmokytą kamanę išmoko triuką kur kas greičiau — tikras mokymasis stebint.",
      },
    },
  },
  {
    id: "nat_min_036",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Border collie 'Chaser' learned the names of over 1,000 objects — published study",
    emoji: "🗣️",
    translations: {
      en: {
        question: "A border collie named Chaser famously learned the names of over 1,000 what?",
        correct: "Toys",
        distractors: ["People", "Smells", "Tricks", "Routes", "Colours"],
        explanation: "She could fetch each toy by name, and even infer a new name by elimination.",
      },
      lt: {
        question: "Ko daugiau nei 1000 pavadinimų pagarsėjo išmokęs škotų aviganis Čeiseris?",
        correct: "Žaislų",
        distractors: ["Žmonių", "Kvapų", "Triukų", "Maršrutų", "Spalvų"],
        explanation: "Ji atnešdavo kiekvieną žaislą pagal pavadinimą, net atspėdavo naują iš atmetimo.",
      },
    },
  },
  {
    id: "nat_min_037",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Archerfish were trained to discriminate human faces — 2016 study",
    emoji: "🧠",
    translations: {
      en: {
        question: "The fish trained to tell different human faces apart",
        correct: "Archerfish",
        distractors: ["Tuna", "Cod", "Salmon", "Herring", "Carp"],
        explanation: "It spat at the correct face for a reward, sorting dozens of them.",
      },
      lt: {
        question: "Žuvis, išmokyta atskirti skirtingus žmonių veidus",
        correct: "Šaulė žuvis",
        distractors: ["Tunas", "Menkė", "Lašiša", "Silkė", "Karpis"],
        explanation: "Už atlygį ji spjaudavo į teisingą veidą, atskirdama dešimtis jų.",
      },
    },
  },
  {
    id: "nat_min_038",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Ravens remember individuals who treated them unfairly — behavioural study",
    emoji: "🧠",
    translations: {
      en: {
        question: "Ravens are smart enough to remember and hold a grudge against who?",
        correct: "Unfair individuals",
        distractors: ["All strangers", "Only family", "Loud birds", "Bright colours", "Tall people"],
        explanation: "After an unfair trade, a raven will avoid that cheater later on.",
      },
      lt: {
        question: "Ant ko krankliai, būdami gudrūs, atsimena ir laiko pyktį?",
        correct: "Nesąžiningų individų",
        distractors: ["Visų svetimų", "Tik šeimos", "Triukšmingų paukščių", "Ryškių spalvų", "Aukštų žmonių"],
        explanation: "Po nesąžiningų mainų kranklys vėliau vengs to apgaviko.",
      },
    },
  },
  {
    id: "nat_min_039",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Chimp 'Ayumu' outperforms humans at a rapid number-memory task — Kyoto study",
    emoji: "🧩",
    translations: {
      en: {
        question: "A chimp named Ayumu beats most humans at quickly remembering what?",
        correct: "Numbers on a screen",
        distractors: ["Songs", "Smells", "Faces", "Words", "Colours and shapes"],
        explanation: "He recalls the positions of flashed digits in a fraction of a second.",
      },
      lt: {
        question: "Ką greitai įsimindama šimpanzė vardu Ajumu įveikia daugumą žmonių?",
        correct: "Skaičius ekrane",
        distractors: ["Mėgstamas dainas", "Kvapus", "Veidus", "Žodžius", "Spalvas"],
        explanation: "Jis atsimena blykstelėjusių skaitmenų vietas per sekundės dalį.",
      },
    },
  },
  {
    id: "nat_min_040",
    category: "nature",
    subTheme: "minds",
    topic: "minds",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Whale songs have regional 'dialects' that change over time — marine biology",
    emoji: "🗣️",
    translations: {
      en: {
        question: "The animals with regional 'dialects' in their calls, like accents",
        correct: "Whales",
        distractors: ["Snakes", "Frogs", "Crabs", "Jellyfish", "Snails"],
        explanation: "Groups in different areas sing differently, and the songs slowly change like fashions.",
      },
      lt: {
        question: "Gyvūnai, turintys vietinius garsų dialektus, tarsi akcentus",
        correct: "Banginiai",
        distractors: ["Gyvatės", "Varlės", "Krabai", "Medūzos", "Sraigės"],
        explanation: "Skirtingų vietų grupės dainuoja kitaip, o dainos lėtai kinta tarsi mados.",
      },
    },
  },
];
