/**
 * natureSuperpowers — 🧬 „Gyvūnų supergalios" potemė (tema „Gamta ir gyvūnai").
 *
 * MAŽAS FAILAS. 40 klausimų (10/lygiui). Gyvūnų FIZINIAI gebėjimai/mechanizmai:
 * nuodai, kamufliažas, echolokacija, regeneracija, elektra, išgyvenimas.
 * NEkartoti esamų gamtos „faktų"/„rekordų" — čia duodam KITUS kampus (kaip veikia).
 *
 * topic: "superpowers" (NatureTopic) — startNatureGame filtruoja pagal `topic`.
 * TAISYKLĖS: 1 teisingas + 5 distraktoriai; ≤46 simb.; teisingas NE ilgiausias >+5;
 * LT natūrali; jokio atsakymo klausime; EMOJI NEUTRALUS.
 */

import { TriviaQuestion } from "./triviaTypes";

export const NATURE_SUPERPOWERS: TriviaQuestion[] = [
  // ===================== LENGVAS (9–12 m. vaikas) =====================
  {
    id: "nat_sup_001",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Chameleons change skin colour (communication/mood/temperature) — encyclopedic zoology",
    emoji: "🎨",
    translations: {
      en: {
        question: "Which reptile is famous for changing its skin colour?",
        correct: "Chameleon",
        distractors: ["Iguana", "Gecko", "Skink", "Turtle", "Crocodile"],
        explanation: "It shifts colour mostly to show mood and warm up, not just to hide.",
      },
      lt: {
        question: "Kuris ropliukas garsus tuo, kad keičia odos spalvą?",
        correct: "Chameleonas",
        distractors: ["Iguana", "Gekonas", "Scinkas", "Vėžlys", "Krokodilas"],
        explanation: "Spalvą keičia daugiausia parodydamas nuotaiką ir šildydamasis, ne tik slėpdamasis.",
      },
    },
  },
  {
    id: "nat_sup_002",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Skunks spray a strong-smelling liquid for defence — encyclopedic",
    emoji: "🛡️",
    translations: {
      en: {
        question: "Which animal sprays a horrible smell to scare off enemies?",
        correct: "Skunk",
        distractors: ["Fox", "Badger", "Raccoon", "Weasel", "Otter"],
        explanation: "Its spray can be smelled from far away and stings the eyes.",
      },
      lt: {
        question: "Kuris gyvūnas purškia bjaurų kvapą, kad atbaidytų priešus?",
        correct: "Skunkas",
        distractors: ["Lapė", "Barsukas", "Meškėnas", "Žebenkštis", "Ūdra"],
        explanation: "Jo purslą galima užuosti iš toli, jis graužia akis.",
      },
    },
  },
  {
    id: "nat_sup_003",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Bats navigate and hunt by echolocation — encyclopedic",
    emoji: "🔊",
    translations: {
      en: {
        question: "Which flying animal hunts in the dark using sound echoes?",
        correct: "Bat",
        distractors: ["Owl", "Moth", "Eagle", "Sparrow", "Swallow"],
        explanation: "It sends out squeaks and listens to the echoes to 'see' insects.",
      },
      lt: {
        question: "Kuris skraidantis gyvūnas medžioja tamsoje pagal garso aidą?",
        correct: "Šikšnosparnis",
        distractors: ["Pelėda", "Drugys", "Erelis", "Žvirblis", "Kregždė"],
        explanation: "Jis siunčia cypsėjimus ir pagal aidą tarsi mato vabzdžius.",
      },
    },
  },
  {
    id: "nat_sup_004",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Ants can lift many times their own body weight — encyclopedic",
    emoji: "💪",
    translations: {
      en: {
        question: "Which tiny insect can lift many times its own body weight?",
        correct: "Ant",
        distractors: ["Butterfly", "Fly", "Mosquito", "Moth", "Ladybug"],
        explanation: "Its small muscles are very strong compared to its size.",
      },
      lt: {
        question: "Kuris mažytis vabzdys gali pakelti daugkart už save sunkesnį svorį?",
        correct: "Skruzdėlė",
        distractors: ["Drugelis", "Musė", "Uodas", "Kandis", "Boružė"],
        explanation: "Jos maži raumenys, palyginti su dydžiu, labai stiprūs.",
      },
    },
  },
  {
    id: "nat_sup_005",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Many lizards can drop and regrow their tail (autotomy) — encyclopedic",
    emoji: "♻️",
    translations: {
      en: {
        question: "Which animal can grow back a tail it has lost?",
        correct: "Lizard",
        distractors: ["Frog", "Snake", "Turtle", "Bird", "Mouse"],
        explanation: "It can drop its tail to escape, then slowly grow a new one.",
      },
      lt: {
        question: "Kuris gyvūnas gali užsiauginti naują nukritusią uodegą?",
        correct: "Driežas",
        distractors: ["Varlė", "Gyvatė", "Vėžlys", "Paukštis", "Pelė"],
        explanation: "Jis gali numesti uodegą pabėgdamas, o paskui lėtai užsiauginti naują.",
      },
    },
  },
  {
    id: "nat_sup_006",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Electric eels generate strong electric discharges — encyclopedic",
    emoji: "⚡",
    translations: {
      en: {
        question: "Which water animal can give a powerful electric shock?",
        correct: "Electric eel",
        distractors: ["Shark", "Tuna", "Salmon", "Cod", "Clownfish"],
        explanation: "It uses the shock to stun small fish and to defend itself.",
      },
      lt: {
        question: "Kuris vandens gyvūnas gali smogti galingu elektros smūgiu?",
        correct: "Elektrinis ungurys",
        distractors: ["Ryklys", "Tunas", "Lašiša", "Menkė", "Vaivorykštinis upėtakis"],
        explanation: "Smūgiu jis apsvaigina mažas žuvis ir ginasi.",
      },
    },
  },
  {
    id: "nat_sup_007",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Fireflies produce light by bioluminescence — encyclopedic",
    emoji: "🌟",
    translations: {
      en: {
        question: "Which insect can make its own glowing light at night?",
        correct: "Firefly",
        distractors: ["Ant", "Bee", "Spider", "Moth", "Wasp"],
        explanation: "A chemical reaction in its body produces cool, glowing light.",
      },
      lt: {
        question: "Kuris vabzdys naktį gali sukurti savo švytinčią šviesą?",
        correct: "Jonvabalis",
        distractors: ["Skruzdėlė", "Bitė", "Voras", "Kandis", "Vapsva"],
        explanation: "Cheminė reakcija jo kūne sukuria šaltą, švytinčią šviesą.",
      },
    },
  },
  {
    id: "nat_sup_008",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Hedgehogs roll into a spiny ball for defence — encyclopedic",
    emoji: "🛡️",
    translations: {
      en: {
        question: "Which animal rolls into a spiky ball when it feels scared?",
        correct: "Hedgehog",
        distractors: ["Porcupine", "Mole", "Rat", "Rabbit", "Squirrel"],
        explanation: "Curling up hides its soft belly and shows only sharp spines.",
      },
      lt: {
        question: "Kuris gyvūnas išsigandęs susiriečia į dygliuotą kamuoliuką?",
        correct: "Ežys",
        distractors: ["Dygliatriušis", "Kurmis", "Žiurkė", "Triušis", "Voverė"],
        explanation: "Susirietęs paslepia minkštą pilvuką ir rodo tik aštrius spyglius.",
      },
    },
  },
  {
    id: "nat_sup_009",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Pufferfish inflate with water to deter predators — encyclopedic",
    emoji: "🌊",
    translations: {
      en: {
        question: "Which fish puffs up into a spiky ball to avoid being eaten?",
        correct: "Pufferfish",
        distractors: ["Jellyfish", "Crab", "Seahorse", "Starfish", "Eel"],
        explanation: "It gulps water and swells up so it is too big and prickly to swallow.",
      },
      lt: {
        question: "Kuri žuvis išsipučia į dygliuotą kamuolį, kad jos nesuėstų?",
        correct: "Kamuolinė žuvis",
        distractors: ["Medūza", "Krabas", "Jūrų arkliukas", "Jūrų žvaigždė", "Ungurys"],
        explanation: "Ji prisiryja vandens ir taip išsipučia, kad tampa per didelė ir dygli.",
      },
    },
  },
  {
    id: "nat_sup_010",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geckos climb smooth surfaces using setae on their toe pads — encyclopedic",
    emoji: "✨",
    translations: {
      en: {
        question: "Which lizard can climb up smooth glass with its sticky toes?",
        correct: "Gecko",
        distractors: ["Iguana", "Chameleon", "Skink", "Snake", "Turtle"],
        explanation: "Millions of tiny hairs on its toes grip even shiny surfaces.",
      },
      lt: {
        question: "Kuris driežas lipniomis kojų pagalvėlėmis užlipa net stiklu?",
        correct: "Gekonas",
        distractors: ["Iguana", "Chameleonas", "Scinkas", "Gyvatė", "Vėžlys"],
        explanation: "Milijonai mažyčių plaukelių ant pirštų sukimba net su lygiu paviršiumi.",
      },
    },
  },

  // ===================== VIDUTINIS (12–18 m. paauglys) =====================
  {
    id: "nat_sup_011",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Mantis shrimp strike with one of the fastest, most powerful punches — Smithsonian",
    emoji: "💥",
    translations: {
      en: {
        question: "The mantis shrimp is famous for an incredibly powerful what?",
        correct: "Punch",
        distractors: ["Bite", "Sting", "Kick", "Grip", "Squeeze"],
        explanation: "Its club-like arms hit so fast they can crack a crab's shell.",
      },
      lt: {
        question: "Kuo neįtikėtinai galingu garsus mantišrimpas (rievžegė)?",
        correct: "Smūgiu",
        distractors: ["Įkandimu", "Gėlimu", "Spyriu", "Gniaužtu", "Suspaudimu"],
        explanation: "Jo lazdiškos letenos smogia taip greitai, kad sutrupina krabo kiautą.",
      },
    },
  },
  {
    id: "nat_sup_012",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Wood frogs freeze solid in winter and thaw back to life — Nat Geo / NSF",
    emoji: "🧊",
    translations: {
      en: {
        question: "Which animal can freeze almost solid in winter and thaw back alive?",
        correct: "Wood frog",
        distractors: ["Toad", "Newt", "Lizard", "Snail", "Turtle"],
        explanation: "Natural antifreeze protects its cells while its heart even stops.",
      },
      lt: {
        question: "Kuris gyvūnas žiemą gali beveik užšalti ir atšilęs vėl atgyti?",
        correct: "Miško varlė",
        distractors: ["Rupūžė", "Tritonas", "Driežas", "Sraigė", "Vėžlys"],
        explanation: "Natūralus antifrizas saugo ląsteles, nors širdis net sustoja.",
      },
    },
  },
  {
    id: "nat_sup_013",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Bombardier beetles spray a hot, near-boiling chemical defence — encyclopedic",
    emoji: "💥",
    translations: {
      en: {
        question: "The bombardier beetle shoots a defensive spray that is nearly what?",
        correct: "Boiling hot",
        distractors: ["Ice cold", "Glue-like", "Sweet", "Glowing", "Frozen"],
        explanation: "It mixes two chemicals that react and burst out almost boiling.",
      },
      lt: {
        question: "Koks yra gynybinis purslas, kurį šaudo bombardyrvabalis?",
        correct: "Verdantis karštas",
        distractors: ["Ledinis", "Klijingas", "Saldus kaip medus", "Švytintis", "Užšaldytas"],
        explanation: "Jis sumaišo dvi medžiagas, kurios sureaguoja ir išsiveržia beveik verdančios.",
      },
    },
  },
  {
    id: "nat_sup_014",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Sharks sense prey's electric fields via ampullae of Lorenzini — encyclopedic",
    emoji: "⚡",
    translations: {
      en: {
        question: "Which fish can sense the faint electric fields of hidden prey?",
        correct: "Shark",
        distractors: ["Tuna", "Salmon", "Cod", "Herring", "Mackerel"],
        explanation: "Tiny jelly-filled pores in its snout detect prey's muscle signals.",
      },
      lt: {
        question: "Kuri žuvis junta silpną pasislėpusio grobio elektrinį lauką?",
        correct: "Ryklys",
        distractors: ["Tunas", "Lašiša", "Menkė", "Silkė", "Skumbrė"],
        explanation: "Mažytės poros snukyje pajunta grobio raumenų signalus.",
      },
    },
  },
  {
    id: "nat_sup_015",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Axolotls regenerate whole limbs — encyclopedic / regeneration biology",
    emoji: "♻️",
    translations: {
      en: {
        question: "The axolotl amazes scientists because it can regrow entire what?",
        correct: "Limbs",
        distractors: ["Only skin", "Only scales", "Only fur", "Nothing", "Only teeth"],
        explanation: "It can rebuild whole legs, perfectly, again and again.",
      },
      lt: {
        question: "Ką ištisą gali ataugti aksolotlis, stebinantis mokslininkus?",
        correct: "Galūnes",
        distractors: ["Tik odą", "Tik žvynus", "Tik kailį", "Nieko", "Tik dantis"],
        explanation: "Jis gali tobulai atstatyti visas kojas, ir vėl, ir vėl.",
      },
    },
  },
  {
    id: "nat_sup_016",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Sea turtles use Earth's magnetic field to return to their birth beach — Nat Geo",
    emoji: "🧭",
    translations: {
      en: {
        question: "Which animal uses Earth's magnetic field to find its birth beach?",
        correct: "Sea turtle",
        distractors: ["Dolphin", "Shark", "Penguin", "Seal", "Crab"],
        explanation: "Decades later it returns across the ocean to where it hatched.",
      },
      lt: {
        question: "Kuris gyvūnas pagal Žemės magnetinį lauką randa savo gimtąjį paplūdimį?",
        correct: "Jūrų vėžlys",
        distractors: ["Delfinas", "Ryklys", "Pingvinas", "Ruonis", "Krabas"],
        explanation: "Po dešimtmečių jis grįžta per vandenyną ten, kur išsirito.",
      },
    },
  },
  {
    id: "nat_sup_017",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Spiders spin silk webs to trap prey — encyclopedic",
    emoji: "🕸️",
    translations: {
      en: {
        question: "Which animal spins a sticky silk web to trap its food?",
        correct: "Spider",
        distractors: ["Ant", "Bee", "Beetle", "Snail", "Worm"],
        explanation: "Its silk is, for its weight, stronger than steel.",
      },
      lt: {
        question: "Kuris gyvūnas pina lipnų šilko tinklą maistui sugauti?",
        correct: "Voras",
        distractors: ["Skruzdėlė", "Bitė", "Vabalas", "Sraigė", "Sliekas"],
        explanation: "Jo šilkas, palyginti su svoriu, stipresnis už plieną.",
      },
    },
  },
  {
    id: "nat_sup_018",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Octopuses change colour AND skin texture to camouflage — encyclopedic",
    emoji: "🎨",
    translations: {
      en: {
        question: "Which sea animal can change both colour and skin texture to hide?",
        correct: "Octopus",
        distractors: ["Tuna", "Crab", "Jellyfish", "Seahorse", "Eel"],
        explanation: "In a blink it can match coral, sand or rock almost perfectly.",
      },
      lt: {
        question: "Kuris jūros gyvūnas slėpdamasis keičia ir spalvą, ir odos faktūrą?",
        correct: "Aštuonkojis",
        distractors: ["Tunas", "Krabas", "Medūza", "Jūrų arkliukas", "Ungurys"],
        explanation: "Per akimirką jis beveik tobulai pamėgdžioja koralą, smėlį ar akmenį.",
      },
    },
  },
  {
    id: "nat_sup_019",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Pit vipers detect warm prey via infrared pit organs — encyclopedic",
    emoji: "🌡️",
    translations: {
      en: {
        question: "Pit vipers can 'see' warm prey in the dark using what?",
        correct: "Heat sensors",
        distractors: ["Sound", "Smell only", "Whiskers", "Sonar", "Glowing eyes"],
        explanation: "Special pits between eye and nostril feel the body heat of prey.",
      },
      lt: {
        question: "Ką naudodamos duobagalvės gyvatės tamsoje junta šiltą grobį?",
        correct: "Šilumos jutiklius",
        distractors: ["Garsą", "Tik kvapą", "Ūsus", "Sonarą", "Švytinčias akis"],
        explanation: "Ypatingos duobutės tarp akies ir šnervės junta grobio kūno šilumą.",
      },
    },
  },
  {
    id: "nat_sup_020",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Tardigrades survive vacuum, extreme heat and cold — encyclopedic",
    emoji: "🧊",
    translations: {
      en: {
        question: "Which tiny creature can survive the vacuum of space and extreme cold?",
        correct: "Tardigrade",
        distractors: ["Ant", "Tick", "Flea", "Mite", "Louse"],
        explanation: "It dries out into a tough state and revives when water returns.",
      },
      lt: {
        question: "Kuris mažytis padaras išgyvena kosmoso vakuumą ir didžiulį šaltį?",
        correct: "Tardigradas",
        distractors: ["Skruzdėlė", "Erkė", "Blusa", "Erkutė", "Utėlė"],
        explanation: "Jis išdžiūsta į atsparią būseną ir atgyja, kai grįžta vanduo.",
      },
    },
  },

  // ===================== SUNKUS (suaugęs, kuris domisi) =====================
  {
    id: "nat_sup_021",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Mantis shrimp have around 12 colour-receptor types vs humans' 3 — Smithsonian",
    emoji: "👁️",
    translations: {
      en: {
        question: "Humans have 3 colour receptors; the mantis shrimp has about how many?",
        correct: "12",
        distractors: ["3", "5", "8", "16", "20"],
        explanation: "It has about 12 colour-detecting receptor types, yet is oddly not better at telling colours apart than we are.",
      },
      lt: {
        question: "Žmogus turi 3 spalvų receptorius; o kiek jų maždaug turi mantišrimpas?",
        correct: "12",
        distractors: ["3", "5", "8", "16", "20"],
        explanation: "Jis turi apie 12 spalvas jaučiančių receptorių rūšių, bet, kad ir keista, spalvas skiria ne geriau nei mes.",
      },
    },
  },
  {
    id: "nat_sup_022",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Platypus detects prey by electroreception in its bill — encyclopedic",
    emoji: "⚡",
    translations: {
      en: {
        question: "Which mammal finds underwater prey using electric sensors in its bill?",
        correct: "Platypus",
        distractors: ["Otter", "Beaver", "Seal", "Dolphin", "Walrus"],
        explanation: "It hunts with eyes shut, sensing the tiny electric pulses of prey.",
      },
      lt: {
        question: "Kuris žinduolis vandenyje grobį randa snapo elektros jutikliais?",
        correct: "Ančiasnapis",
        distractors: ["Ūdra", "Bebras", "Ruonis", "Delfinas", "Vėplys"],
        explanation: "Jis medžioja užmerktomis akimis, jausdamas mažyčius grobio impulsus.",
      },
    },
  },
  {
    id: "nat_sup_023",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Hagfish release vast amounts of defensive slime — encyclopedic",
    emoji: "🌊",
    translations: {
      en: {
        question: "Hagfish escape predators by suddenly producing huge amounts of what?",
        correct: "Slime",
        distractors: ["Ink", "Foam", "Oil", "Wax", "Sand"],
        explanation: "In seconds it makes litres of slime that clog a predator's gills.",
      },
      lt: {
        question: "Ko didžiulį kiekį staiga pagamina negyvėdės (hagfish), kad pabėgtų?",
        correct: "Gleivių",
        distractors: ["Rašalo", "Putų", "Aliejaus", "Vaško", "Smėlio"],
        explanation: "Per sekundes ji pagamina litrus gleivių, kurios užkemša plėšrūno žiaunas.",
      },
    },
  },
  {
    id: "nat_sup_024",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Turritopsis (immortal jellyfish) reverts to its polyp stage — peer-reviewed biology",
    emoji: "♻️",
    translations: {
      en: {
        question: "The 'immortal' jellyfish can escape death by doing what?",
        correct: "Reverting to a baby",
        distractors: ["Splitting in two", "Growing a shell", "Freezing solid", "Glowing forever", "Cloning an army"],
        explanation: "When hurt or old it rewinds into its young form and starts over.",
      },
      lt: {
        question: "Ką darydama nemirtinga medūza gali išvengti mirties?",
        correct: "Grįždama į kūdikystę",
        distractors: ["Dalydamasi pusiau", "Užsiaugindama kiautą", "Užšaldama", "Amžinai švytėdama", "Klonuodama armiją"],
        explanation: "Sužeista ar pasenusi ji tarsi atsuka laiką į jauną pavidalą ir pradeda iš naujo.",
      },
    },
  },
  {
    id: "nat_sup_025",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Antarctic icefish have antifreeze proteins and clear, haemoglobin-free blood — encyclopedic",
    emoji: "🧊",
    translations: {
      en: {
        question: "Which fish makes antifreeze proteins to live in icy Antarctic seas?",
        correct: "Icefish",
        distractors: ["Tuna", "Marlin", "Herring", "Mackerel", "Anchovy"],
        explanation: "Its blood is even clear, with no red cells, yet it thrives in the cold.",
      },
      lt: {
        question: "Kuri žuvis gamina antifrizo baltymus, kad gyventų ledinėse Antarktidos jūrose?",
        correct: "Ledžuvė",
        distractors: ["Tunas", "Marlinas", "Silkė", "Skumbrė", "Ančiuvis"],
        explanation: "Jos kraujas net skaidrus, be raudonųjų ląstelių, bet šaltyje ji klesti.",
      },
    },
  },
  {
    id: "nat_sup_026",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Electric eels can discharge around 600 volts — encyclopedic",
    emoji: "⚡",
    translations: {
      en: {
        question: "An electric eel's shock is typically around how many volts?",
        correct: "600",
        distractors: ["12", "50", "120", "1200", "5000"],
        explanation: "That is strong enough to stun fish and deter much larger animals.",
      },
      lt: {
        question: "Elektrinio ungurio smūgis paprastai būna maždaug kiek voltų?",
        correct: "600",
        distractors: ["12", "50", "120", "1200", "5000"],
        explanation: "To pakanka apsvaiginti žuvis ir atbaidyti gerokai didesnius gyvūnus.",
      },
    },
  },
  {
    id: "nat_sup_027",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Sea cucumbers eject internal organs (evisceration) and regrow them — encyclopedic",
    emoji: "🛡️",
    translations: {
      en: {
        question: "How does a sea cucumber startle a predator and then survive?",
        correct: "Ejects its own guts",
        distractors: ["Bites hard", "Sprays venom", "Grows spikes", "Plays dead", "Turns to stone"],
        explanation: "It shoots out its insides as a decoy, then slowly regrows them.",
      },
      lt: {
        question: "Kaip jūros agurkas išgąsdina plėšrūną ir vis tiek išgyvena?",
        correct: "Išsviedžia savo vidurius",
        distractors: ["Stipriai įkanda", "Purškia nuodus", "Užsiaugina spyglius", "Apsimeta negyvas", "Pavirsta akmeniu"],
        explanation: "Jis išmeta vidurius kaip apgaulę, o paskui lėtai juos atsiaugina.",
      },
    },
  },
  {
    id: "nat_sup_028",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Dung beetles can pull over 1000 times their own body weight — Guinness/zoology",
    emoji: "💪",
    translations: {
      en: {
        question: "Which insect can pull over 1000 times its own body weight?",
        correct: "Dung beetle",
        distractors: ["Stag beetle", "Ladybug", "Weevil", "Firefly", "Cricket"],
        explanation: "Relative to its size, it is one of the strongest animals alive.",
      },
      lt: {
        question: "Kuris vabzdys gali patempti daugiau nei 1000 kartų už save sunkesnį svorį?",
        correct: "Mėšlavabalis",
        distractors: ["Elniavabalis", "Boružė", "Straubliukas", "Jonvabalis", "Svirplys"],
        explanation: "Pagal savo dydį jis vienas stipriausių gyvūnų pasaulyje.",
      },
    },
  },
  {
    id: "nat_sup_029",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Golden poison frog skin carries one of nature's strongest toxins — encyclopedic",
    emoji: "☠️",
    translations: {
      en: {
        question: "Which small frog carries one of nature's deadliest toxins on its skin?",
        correct: "Poison dart frog",
        distractors: ["Common tree frog", "Bullfrog", "Toad", "Tadpole", "Glass frog"],
        explanation: "Its bright colours warn predators not to touch it.",
      },
      lt: {
        question: "Kuri maža varlė ant odos turi vieną mirtiniausių gamtos nuodų?",
        correct: "Strėlinė varlė",
        distractors: ["Medvarlė", "Jautvarlė", "Rupūžė", "Buožgalvis", "Stiklinė varlė"],
        explanation: "Ryškios spalvos įspėja plėšrūnus jos neliesti.",
      },
    },
  },
  {
    id: "nat_sup_030",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Planarian flatworms regenerate a whole body from tiny fragments — regeneration biology",
    emoji: "♻️",
    translations: {
      en: {
        question: "Which creature can grow a whole new body from just a tiny piece?",
        correct: "Planarian worm",
        distractors: ["Frog", "Mouse", "Snake", "A pet goldfish", "Sparrow"],
        explanation: "Cut into pieces, each piece can rebuild a complete worm, head and all.",
      },
      lt: {
        question: "Kuris padaras gali užsiauginti visą naują kūną vos iš mažo gabalėlio?",
        correct: "Plokščioji kirmėlė",
        distractors: ["Varlė", "Pelė", "Gyvatė", "Auksinė žuvelė", "Žvirblis"],
        explanation: "Supjaustyta į dalis, kiekviena dalis atstato visą kirmėlę su galva.",
      },
    },
  },

  // ===================== EKSTREMALUS (srities žinovas) =====================
  {
    id: "nat_sup_031",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Pompeii worm tolerates deep-sea vent temperatures up to ~80°C — marine biology",
    emoji: "🌋",
    translations: {
      en: {
        question: "The Pompeii worm lives by deep-sea vents at temperatures up to about?",
        correct: "80°C",
        distractors: ["20°C", "40°C", "200°C", "400°C", "5°C"],
        explanation: "It lives next to water up to about 80°C and is among the most heat-tolerant animals known.",
      },
      lt: {
        question: "Iki kokios maždaug temperatūros įkaista gelmių versmės, prie kurių gyvena Pompėjos kirmėlė?",
        correct: "80°C",
        distractors: ["20°C", "40°C", "200°C", "400°C", "5°C"],
        explanation: "Ji gyvena šalia vandens, įkaistančio iki apie 80°C, ir yra viena atspariausių karščiui gyvūnų, kokius žinome.",
      },
    },
  },
  {
    id: "nat_sup_032",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Diving bell spider lives underwater inside an air bubble it carries — encyclopedic",
    emoji: "🫧",
    translations: {
      en: {
        question: "How does the diving bell spider live its whole life underwater?",
        correct: "In an air bubble",
        distractors: ["By holding breath", "With gills", "In a shell", "By not breathing", "In dry pockets"],
        explanation: "It traps a bubble of air among fine hairs and refreshes it like a tank.",
      },
      lt: {
        question: "Kaip vandeninis voras visą gyvenimą praleidžia po vandeniu?",
        correct: "Oro burbule",
        distractors: ["Sulaikęs kvapą", "Su žiaunomis", "Kiaute", "Visai nekvėpuodamas", "Sausose kišenėse"],
        explanation: "Tarp plonų plaukelių jis sulaiko oro burbulą ir jį atnaujina tarsi balioną.",
      },
    },
  },
  {
    id: "nat_sup_033",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Axolotls can regenerate parts of the heart and even brain — regeneration research",
    emoji: "♻️",
    translations: {
      en: {
        question: "Besides limbs, the axolotl can even regrow parts of which organs?",
        correct: "Heart and brain",
        distractors: ["Only skin", "Only tail", "Nothing else", "Only eyes", "Only bones"],
        explanation: "This is why researchers study it to understand healing.",
      },
      lt: {
        question: "Kurių organų dalis, be galūnių, gali atsiauginti aksolotlis?",
        correct: "Širdies ir smegenų",
        distractors: ["Tik odos", "Tik uodegos galiuko", "Nieko kito", "Tik akių", "Tik kaulų"],
        explanation: "Todėl tyrėjai jį tiria norėdami suprasti gijimą.",
      },
    },
  },
  {
    id: "nat_sup_034",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Iberian ribbed newt pushes its ribs through its skin as defensive spines — encyclopedic",
    emoji: "🛡️",
    translations: {
      en: {
        question: "The Iberian ribbed newt defends itself by pushing out its own what?",
        correct: "Ribs",
        distractors: ["Teeth", "Claws", "Horns", "Wings", "Gills"],
        explanation: "The ribs poke through its skin as sharp, poison-coated spines.",
      },
      lt: {
        question: "Ką savo paties išstumdamas ginasi Iberijos šonkaulinis tritonas?",
        correct: "Šonkaulius",
        distractors: ["Dantis", "Nagus", "Ragus", "Sparnus", "Žiaunas"],
        explanation: "Šonkauliai prasibrauna pro odą kaip aštrūs, nuodais padengti spygliai.",
      },
    },
  },
  {
    id: "nat_sup_035",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "African lungfish survive drought by aestivating in a mud cocoon — encyclopedic",
    emoji: "🟫",
    translations: {
      en: {
        question: "How does the African lungfish survive months without water?",
        correct: "Sleeps in a mud cocoon",
        distractors: ["Climbs trees", "Flies away", "Turns to stone", "Walks to the nearest river", "Freezes itself"],
        explanation: "It wraps in dried mud and slows its body almost to a stop until rain.",
      },
      lt: {
        question: "Kaip Afrikos plautžuvė išgyvena mėnesius be vandens?",
        correct: "Miega purvo kokone",
        distractors: ["Lipa į medžius", "Nuskrenda", "Pavirsta akmeniu", "Nueina iki upės", "Užsišaldo"],
        explanation: "Ji apsivelka išdžiūvusiu purvu ir kūną sulėtina beveik iki sustojimo, kol palis.",
      },
    },
  },
  {
    id: "nat_sup_036",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Sharks continuously replace teeth throughout life — encyclopedic",
    emoji: "🦈",
    translations: {
      en: {
        question: "Which animal endlessly grows fresh teeth, replacing lost ones for life?",
        correct: "Shark",
        distractors: ["Lion", "Wolf", "Bear", "Tiger", "Horse"],
        explanation: "Rows of spare teeth roll forward, so it never runs out.",
      },
      lt: {
        question: "Kuris gyvūnas be perstojo augina naujus dantis, visą gyvenimą keisdamas prarastus?",
        correct: "Ryklys",
        distractors: ["Liūtas", "Vilkas", "Lokys", "Tigras", "Arklys"],
        explanation: "Atsarginių dantų eilės slenka į priekį, tad jų niekada netrūksta.",
      },
    },
  },
  {
    id: "nat_sup_037",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Some nudibranchs sequester stinging cells from prey for their own defence — marine biology",
    emoji: "🌊",
    translations: {
      en: {
        question: "Which sea slug steals and reuses the stingers of the animals it eats?",
        correct: "Nudibranch",
        distractors: ["Octopus", "Seahorse", "Clownfish", "Starfish", "Crab"],
        explanation: "It moves a jellyfish's sting cells into its own body to fight back.",
      },
      lt: {
        question: "Kuris jūrų šliužas pavagia ir panaudoja suėstų gyvūnų geluonis?",
        correct: "Nudibranchas",
        distractors: ["Aštuonkojis", "Jūrų arkliukas", "Klounžuvė", "Jūrų žvaigždė", "Krabas"],
        explanation: "Medūzos gėlimo ląsteles jis perkelia į savo kūną, kad galėtų gintis.",
      },
    },
  },
  {
    id: "nat_sup_038",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "The mimic octopus impersonates other animals like lionfish and sea snakes — marine biology",
    emoji: "🎭",
    translations: {
      en: {
        question: "The mimic octopus has the rare power to impersonate other what?",
        correct: "Animals",
        distractors: ["Rocks", "Plants", "Colours only", "Sounds", "Smells"],
        explanation: "It can shape itself to look like a venomous lionfish or sea snake.",
      },
      lt: {
        question: "Kuo kitu turi retą galią apsimesti aštuonkojis mėgdžiotojas?",
        correct: "Gyvūnais",
        distractors: ["Akmenimis", "Augalais", "Tik spalvomis", "Garsais", "Kvapais"],
        explanation: "Jis gali persiformuoti į nuodingą liūtažuvę ar jūrų gyvatę.",
      },
    },
  },
  {
    id: "nat_sup_039",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "The diabolical ironclad beetle survives crushing forces (even being run over) — research 2020",
    emoji: "🛡️",
    translations: {
      en: {
        question: "Which beetle's armour is so tough it can survive being run over by a car?",
        correct: "Ironclad beetle",
        distractors: ["Stag beetle", "Ladybug", "Firefly", "Weevil", "Scarab"],
        explanation: "Its interlocking shell spreads the force so the beetle is not crushed.",
      },
      lt: {
        question: "Kurio vabalo šarvas toks tvirtas, kad išgyvena net automobiliui pervažiavus?",
        correct: "Šarvuotasis vabalas",
        distractors: ["Didysis elniavabalis", "Boružė", "Jonvabalis", "Straubliukas", "Skarabėjas"],
        explanation: "Susikabinęs kiautas paskirsto jėgą, tad vabalas nesutraiškomas.",
      },
    },
  },
  {
    id: "nat_sup_040",
    category: "nature",
    subTheme: "superpowers",
    topic: "superpowers",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "The hairy ('horror') frog breaks its toe bones to push out claws — encyclopedic",
    emoji: "🛡️",
    translations: {
      en: {
        question: "The hairy 'horror' frog defends itself by breaking bones to make what?",
        correct: "Claws",
        distractors: ["Wings", "Teeth", "Horns", "A shell", "Spikes on its back"],
        explanation: "It snaps its toe bones so they pierce the skin as sharp claws.",
      },
      lt: {
        question: "Ką laužydama kaulus pasidaro plaukuotoji varlė, kad apsigintų?",
        correct: "Nagus",
        distractors: ["Sparnus", "Dantis", "Ragus", "Kiautą", "Spyglius ant nugaros"],
        explanation: "Ji nulaužia kojų pirštų kaulus, kad jie pro odą iškiltų kaip aštrūs nagai.",
      },
    },
  },
];
