/**
 * popContent — „Pop kultūra ir pramogos” trivijos klausimai (EN + LT).
 *
 * Po 15 klausimų kiekvienam lygiui (lengvas/vidutinis/sunkus/ekstremalus) = 60.
 * Temos: klasikiniai filmai, ikoniniai personažai, animacija, žaidimai, muzika.
 * SVARBU: VENGIAME greitai senstančių faktų (dabartinių topų, „naujausių”) —
 * tik tvarūs, įsitvirtinę faktai, kurie nepasens.
 *
 * TAISYKLĖS (Manifestas):
 *   - 1 teisingas + 5 distractors; visi 6 variantai VISOSE kalbose ≤46 simbolių;
 *   - faktai 100% patikrinti (sourceVerified); neutralu (jokios politikos/religijos);
 *   - LT vidinės kabutės tik „...” (ne ASCII "); detalės — į explanation, ne į variantą.
 *
 * Formatas — žr. triviaTypes.ts (TriviaQuestion). category visada "pop".
 */

import { TriviaQuestion } from "./triviaTypes";

export const POP_QUESTIONS: TriviaQuestion[] = [
  // ======================= LENGVAS (Easy) =======================
  {
    id: "pop_le_001",
    category: "pop",
    subTheme: "characters",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Disney (Mickey Mouse is a mouse)",
    emoji: "🐭",
    translations: {
      en: {
        question: "What kind of animal is Mickey Mouse?",
        correct: "Mouse",
        distractors: ["Cat", "Dog", "Rabbit", "Bear", "Duck"],
        explanation: "Mickey Mouse is Disney's famous cartoon mouse.",
      },
      lt: {
        question: "Koks gyvūnas yra Peliukas Mikis?",
        correct: "Pelė",
        distractors: ["Katė", "Šuo", "Triušis", "Lokys", "Antis"],
        explanation: "Peliukas Mikis — garsi Disnėjaus animacinė pelė.",
      },
    },
  },
  {
    id: "pop_le_002",
    category: "pop",
    subTheme: "movies",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Film (The Lion King setting)",
    emoji: "🦁",
    translations: {
      en: {
        question: "Which animal is the hero Simba in The Lion King?",
        correct: "Lion",
        distractors: ["Tiger", "Leopard", "Cheetah", "Wolf", "Bear"],
        explanation: "Simba is a lion cub in The Lion King.",
      },
      lt: {
        question: "Koks gyvūnas yra herojus Simba filme „Liūtas karalius”?",
        correct: "Liūtas",
        distractors: ["Tigras", "Leopardas", "Gepardas", "Vilkas", "Lokys"],
        explanation: "Simba — liūtukas filme „Liūtas karalius”.",
      },
    },
  },
  {
    id: "pop_le_003",
    category: "pop",
    subTheme: "games",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Video games (Mario is a plumber)",
    emoji: "🍄",
    translations: {
      en: {
        question: "What is the job of the video game hero Mario?",
        correct: "Plumber",
        distractors: ["Doctor", "Pilot", "Chef", "Teacher", "Soldier"],
        explanation: "Mario is famously a plumber in Nintendo games.",
      },
      lt: {
        question: "Kokia yra žaidimų herojaus Mario profesija?",
        correct: "Santechnikas",
        distractors: ["Gydytojas", "Pilotas", "Virėjas", "Mokytojas", "Karys"],
        explanation: "Mario Nintendo žaidimuose yra santechnikas.",
      },
    },
  },
  {
    id: "pop_le_004",
    category: "pop",
    subTheme: "characters",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Cartoon (SpongeBob lives underwater)",
    emoji: "🧽",
    translations: {
      en: {
        question: "Where does SpongeBob SquarePants live?",
        correct: "Underwater",
        distractors: ["On a mountain", "In space", "In a desert", "In a forest", "On the Moon"],
        explanation: "SpongeBob lives in the underwater town of Bikini Bottom.",
      },
      lt: {
        question: "Kur gyvena Kempiniukas Plačiakelnis?",
        correct: "Po vandeniu",
        distractors: ["Ant kalno", "Kosmose", "Dykumoje", "Miške", "Ant Mėnulio"],
        explanation: "Kempiniukas gyvena povandeniniame miestelyje.",
      },
    },
  },
  {
    id: "pop_le_005",
    category: "pop",
    subTheme: "superheroes",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Comics (Spider-Man powers)",
    emoji: "🕷️",
    translations: {
      en: {
        question: "Which animal gives Spider-Man his name?",
        correct: "Spider",
        distractors: ["Bat", "Ant", "Scorpion", "Beetle", "Fly"],
        explanation: "Spider-Man is named after a spider.",
      },
      lt: {
        question: "Pagal kurį gyvūną pavadintas Žmogus-voras?",
        correct: "Voras",
        distractors: ["Šikšnosparnis", "Skruzdėlė", "Skorpionas", "Vabalas", "Musė"],
        explanation: "Žmogus-voras pavadintas pagal vorą.",
      },
    },
  },
  {
    id: "pop_le_006",
    category: "pop",
    subTheme: "superheroes",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Comics (Batman city is Gotham)",
    emoji: "🦇",
    translations: {
      en: {
        question: "Which animal inspires Batman's costume?",
        correct: "Bat",
        distractors: ["Cat", "Owl", "Crow", "Wolf", "Spider"],
        explanation: "Batman's costume is based on a bat.",
      },
      lt: {
        question: "Pagal kurį gyvūną sukurtas Betmeno kostiumas?",
        correct: "Šikšnosparnis",
        distractors: ["Katė", "Pelėda", "Varna", "Vilkas", "Voras"],
        explanation: "Betmeno kostiumas pagrįstas šikšnosparniu.",
      },
    },
  },
  {
    id: "pop_le_007",
    category: "pop",
    subTheme: "movies",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Film (Frozen sisters)",
    emoji: "❄️",
    translations: {
      en: {
        question: "In Frozen, Elsa has the power to control what?",
        correct: "Ice and snow",
        distractors: ["Fire", "Water", "Wind", "Lightning", "Sand"],
        explanation: "Elsa can create and control ice and snow.",
      },
      lt: {
        question: "Filme „Ledo šalis” Elza valdo ką?",
        correct: "Ledą ir sniegą",
        distractors: ["Ugnį", "Vandenį", "Vėją", "Žaibą", "Smėlį"],
        explanation: "Elza kuria ir valdo ledą bei sniegą.",
      },
    },
  },
  {
    id: "pop_le_008",
    category: "pop",
    subTheme: "characters",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Cartoon (Pikachu is yellow)",
    emoji: "⚡",
    translations: {
      en: {
        question: "What color is Pikachu from Pokemon?",
        correct: "Yellow",
        distractors: ["Blue", "Red", "Green", "Pink", "Purple"],
        explanation: "Pikachu is a yellow electric Pokemon.",
      },
      lt: {
        question: "Kokios spalvos yra Pikachu iš Pokemon?",
        correct: "Geltonas",
        distractors: ["Mėlynas", "Raudonas", "Žalias", "Rožinis", "Violetinis"],
        explanation: "Pikachu — geltonas elektrinis pokemonas.",
      },
    },
  },
  {
    id: "pop_le_009",
    category: "pop",
    subTheme: "music",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Music (guitar is string instrument)",
    emoji: "🎸",
    translations: {
      en: {
        question: "Which of these is a string instrument?",
        correct: "Guitar",
        distractors: ["Drum", "Flute", "Trumpet", "Whistle", "Tambourine"],
        explanation: "A guitar makes sound from vibrating strings.",
      },
      lt: {
        question: "Kuris iš šių yra styginis instrumentas?",
        correct: "Gitara",
        distractors: ["Būgnas", "Fleita", "Trimitas", "Švilpukas", "Tamburinas"],
        explanation: "Gitara skleidžia garsą iš virpančių stygų.",
      },
    },
  },
  {
    id: "pop_le_010",
    category: "pop",
    subTheme: "movies",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Film (Toy Story toys)",
    emoji: "🤠",
    translations: {
      en: {
        question: "Toy Story is a film about toys that can do what?",
        correct: "Come alive",
        distractors: ["Fly planes", "Cook food", "Drive cars", "Swim deep", "Build houses"],
        explanation: "In Toy Story the toys come alive when no one looks.",
      },
      lt: {
        question: "„Žaislų istorija” — filmas apie žaislus, kurie geba ką?",
        correct: "Atgyti",
        distractors: ["Skraidyti lėktuvais", "Gaminti maistą", "Vairuoti", "Nardyti", "Statyti namus"],
        explanation: "„Žaislų istorijoje” žaislai atgyja, kai niekas nemato.",
      },
    },
  },
  {
    id: "pop_le_011",
    category: "pop",
    subTheme: "characters",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Cartoon (Tom and Jerry, cat and mouse)",
    emoji: "🐱",
    translations: {
      en: {
        question: "In Tom and Jerry, Tom is what animal?",
        correct: "Cat",
        distractors: ["Mouse", "Dog", "Bird", "Fish", "Rabbit"],
        explanation: "Tom is the cat who chases Jerry the mouse.",
      },
      lt: {
        question: "Animaciniame „Tomas ir Džeris” Tomas yra koks gyvūnas?",
        correct: "Katė",
        distractors: ["Pelė", "Šuo", "Paukštis", "Žuvis", "Triušis"],
        explanation: "Tomas — katinas, vejantis pelę Džerį.",
      },
    },
  },
  {
    id: "pop_le_012",
    category: "pop",
    subTheme: "games",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Games (Minecraft is block-building)",
    emoji: "⛏️",
    translations: {
      en: {
        question: "The game Minecraft is famous for building with what?",
        correct: "Blocks",
        distractors: ["Cards", "Balls", "Ropes", "Bricks of gold", "Paper"],
        explanation: "Minecraft is built from cube-shaped blocks.",
      },
      lt: {
        question: "Žaidimas „Minecraft” garsus statymu iš ko?",
        correct: "Blokų",
        distractors: ["Kortų", "Kamuolių", "Virvių", "Aukso plytų", "Popieriaus"],
        explanation: "„Minecraft” statoma iš kubo formos blokų.",
      },
    },
  },
  {
    id: "pop_le_013",
    category: "pop",
    subTheme: "movies",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Film (Star Wars laser sword)",
    emoji: "⚔️",
    translations: {
      en: {
        question: "What is the glowing sword in Star Wars called?",
        correct: "Lightsaber",
        distractors: ["Laser bow", "Plasma axe", "Beam spear", "Star blade", "Glow knife"],
        explanation: "Jedi and Sith fight with lightsabers.",
      },
      lt: {
        question: "Kaip vadinamas švytintis kardas filme „Žvaigždžių karai”?",
        correct: "Šviesos kardas",
        distractors: ["Lazerio lankas", "Plazmos kirvis", "Spindulio ietis", "Žvaigždės geležtė", "Švytintis peilis"],
        explanation: "Džedajai ir sithai kaunasi šviesos kardais.",
      },
    },
  },
  {
    id: "pop_le_014",
    category: "pop",
    subTheme: "characters",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Cartoon (Winnie the Pooh loves honey)",
    emoji: "🍯",
    translations: {
      en: {
        question: "What food does Winnie the Pooh love most?",
        correct: "Honey",
        distractors: ["Carrots", "Fish", "Bananas", "Cheese", "Bread"],
        explanation: "Winnie the Pooh is famous for loving honey.",
      },
      lt: {
        question: "Kokį maistą labiausiai mėgsta Mikė Pūkuotukas?",
        correct: "Medų",
        distractors: ["Morkas", "Žuvį", "Bananus", "Sūrį", "Duoną"],
        explanation: "Mikė Pūkuotukas garsėja meilę medui.",
      },
    },
  },
  {
    id: "pop_le_015",
    category: "pop",
    subTheme: "movies",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Film (Harry Potter is a wizard)",
    emoji: "🧙",
    translations: {
      en: {
        question: "What is Harry Potter trained to become?",
        correct: "A wizard",
        distractors: ["A pirate", "A knight", "A pilot", "A doctor", "A king"],
        explanation: "Harry Potter studies to become a wizard.",
      },
      lt: {
        question: "Kuo mokomas tapti Haris Poteris?",
        correct: "Burtininku",
        distractors: ["Piratu", "Riteriu", "Pilotu", "Gydytoju", "Karaliumi"],
        explanation: "Haris Poteris mokosi tapti burtininku.",
      },
    },
  },

  // ======================= VIDUTINIS (Medium) =======================
  {
    id: "pop_me_001",
    category: "pop",
    subTheme: "movies",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Film studio (Pixar made Toy Story)",
    emoji: "🎬",
    translations: {
      en: {
        question: "Which studio made the first fully computer-animated feature film?",
        correct: "Pixar",
        distractors: ["Disney only", "Warner Bros", "DreamWorks", "Sony", "Universal"],
        explanation: "Pixar made Toy Story, the first CGI feature, in 1995.",
      },
      lt: {
        question: "Kuri studija sukūrė pirmą pilnai kompiuterinį animacinį filmą?",
        correct: "Pixar",
        distractors: ["Tik Disney", "Warner Bros", "DreamWorks", "Sony", "Universal"],
        explanation: "Pixar 1995 m. sukūrė „Žaislų istoriją”, pirmą CGI filmą.",
      },
    },
  },
  {
    id: "pop_me_002",
    category: "pop",
    subTheme: "music",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Music (The Beatles from Liverpool)",
    emoji: "🎵",
    translations: {
      en: {
        question: "The famous band The Beatles came from which city?",
        correct: "Liverpool",
        distractors: ["London", "Manchester", "Dublin", "Glasgow", "Leeds"],
        explanation: "The Beatles formed in Liverpool, England.",
      },
      lt: {
        question: "Iš kurio miesto kilo garsioji grupė „The Beatles”?",
        correct: "Liverpulis",
        distractors: ["Londonas", "Mančesteris", "Dublinas", "Glazgas", "Lidsas"],
        explanation: "„The Beatles” susikūrė Liverpulyje, Anglijoje.",
      },
    },
  },
  {
    id: "pop_me_003",
    category: "pop",
    subTheme: "superheroes",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Comics (Superman home planet Krypton)",
    emoji: "🦸",
    translations: {
      en: {
        question: "What is the home planet of Superman?",
        correct: "Krypton",
        distractors: ["Mars", "Tatooine", "Vulcan", "Asgard", "Saturn"],
        explanation: "Superman was born on the planet Krypton.",
      },
      lt: {
        question: "Kokia yra Supermeno gimtoji planeta?",
        correct: "Kriptonas",
        distractors: ["Marsas", "Tatuinas", "Vulkanas", "Asgardas", "Saturnas"],
        explanation: "Supermenas gimė planetoje Kriptonas.",
      },
    },
  },
  {
    id: "pop_me_004",
    category: "pop",
    subTheme: "games",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Games (Tetris falling shapes)",
    emoji: "🟦",
    translations: {
      en: {
        question: "In the game Tetris, you arrange falling what?",
        correct: "Blocks",
        distractors: ["Cards", "Bubbles", "Coins", "Stars", "Letters"],
        explanation: "Tetris is about fitting falling block shapes.",
      },
      lt: {
        question: "Žaidime „Tetris” dėliojami krintantys kas?",
        correct: "Blokai",
        distractors: ["Kortos", "Burbulai", "Monetos", "Žvaigždės", "Raidės"],
        explanation: "„Tetris” — krintančių blokų dėliojimas.",
      },
    },
  },
  {
    id: "pop_me_005",
    category: "pop",
    subTheme: "movies",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Film (Jurassic Park dinosaurs)",
    emoji: "🦖",
    translations: {
      en: {
        question: "The Jurassic Park films are famous for bringing back what?",
        correct: "Dinosaurs",
        distractors: ["Robots", "Aliens", "Dragons", "Pirates", "Vampires"],
        explanation: "Jurassic Park is about recreated dinosaurs.",
      },
      lt: {
        question: "Filmai „Juros periodo parkas” garsūs sugrąžinę ką?",
        correct: "Dinozaurus",
        distractors: ["Robotus", "Ateivius", "Drakonus", "Piratus", "Vampyrus"],
        explanation: "„Juros periodo parkas” — apie atkurtus dinozaurus.",
      },
    },
  },
  {
    id: "pop_me_006",
    category: "pop",
    subTheme: "characters",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Cartoon (Simpsons hometown Springfield)",
    emoji: "🍩",
    translations: {
      en: {
        question: "In which town does The Simpsons take place?",
        correct: "Springfield",
        distractors: ["Gotham", "Bedrock", "Quahog", "Shelbyville", "Metropolis"],
        explanation: "The Simpsons live in the town of Springfield.",
      },
      lt: {
        question: "Kuriame miestelyje vyksta „Simpsonų” veiksmas?",
        correct: "Springfildas",
        distractors: ["Gotamas", "Bedrokas", "Kvahogas", "Šelbivilis", "Metropolis"],
        explanation: "Simpsonai gyvena Springfildo miestelyje.",
      },
    },
  },
  {
    id: "pop_me_007",
    category: "pop",
    subTheme: "music",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Music (piano has black and white keys)",
    emoji: "🎹",
    translations: {
      en: {
        question: "A piano is played by pressing what?",
        correct: "Keys",
        distractors: ["Strings only", "Pedals only", "Buttons of brass", "Frets", "Valves"],
        explanation: "A piano is played using its black and white keys.",
      },
      lt: {
        question: "Pianinu grojama spaudžiant ką?",
        correct: "Klavišus",
        distractors: ["Tik stygas", "Tik pedalus", "Žalvario mygtukus", "Ladus", "Vožtuvus"],
        explanation: "Pianinu grojama spaudžiant juodus ir baltus klavišus.",
      },
    },
  },
  {
    id: "pop_me_008",
    category: "pop",
    subTheme: "movies",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Film (E.T. is an alien)",
    emoji: "👽",
    translations: {
      en: {
        question: "In the classic film E.T., what is E.T.?",
        correct: "An alien",
        distractors: ["A robot", "A ghost", "A wizard", "A dinosaur", "A pirate"],
        explanation: "E.T. is a friendly alien stranded on Earth.",
      },
      lt: {
        question: "Klasikiniame filme „E.T.” kas yra E.T.?",
        correct: "Ateivis",
        distractors: ["Robotas", "Vaiduoklis", "Burtininkas", "Dinozauras", "Piratas"],
        explanation: "E.T. — draugiškas ateivis, įstrigęs Žemėje.",
      },
    },
  },
  {
    id: "pop_me_009",
    category: "pop",
    subTheme: "characters",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Games (Sonic is a hedgehog)",
    emoji: "💨",
    translations: {
      en: {
        question: "What kind of animal is the game character Sonic?",
        correct: "Hedgehog",
        distractors: ["Fox", "Squirrel", "Rabbit", "Mouse", "Cat"],
        explanation: "Sonic is a fast blue hedgehog.",
      },
      lt: {
        question: "Koks gyvūnas yra žaidimų personažas Sonikas?",
        correct: "Ežys",
        distractors: ["Lapė", "Voverė", "Triušis", "Pelė", "Katė"],
        explanation: "Sonikas — greitas mėlynas ežys.",
      },
    },
  },
  {
    id: "pop_me_010",
    category: "pop",
    subTheme: "movies",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Film (Shrek is an ogre)",
    emoji: "🟢",
    translations: {
      en: {
        question: "What kind of creature is Shrek?",
        correct: "Ogre",
        distractors: ["Troll", "Goblin", "Giant", "Dragon", "Wizard"],
        explanation: "Shrek is a green ogre in the DreamWorks films.",
      },
      lt: {
        question: "Kokia būtybė yra Šrekas?",
        correct: "Ogras",
        distractors: ["Trolis", "Goblinas", "Milžinas", "Drakonas", "Burtininkas"],
        explanation: "Šrekas — žalias ogras DreamWorks filmuose.",
      },
    },
  },
  {
    id: "pop_me_011",
    category: "pop",
    subTheme: "superheroes",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Comics (Iron Man wears a suit)",
    emoji: "🤖",
    translations: {
      en: {
        question: "Iron Man's powers mainly come from what?",
        correct: "A powered suit",
        distractors: ["A magic ring", "A spider bite", "A hammer", "A potion", "A cape"],
        explanation: "Iron Man uses a high-tech powered armor suit.",
      },
      lt: {
        question: "Iš ko daugiausia kyla Geležinio žmogaus galios?",
        correct: "Galingo kostiumo",
        distractors: ["Magiško žiedo", "Voro įkandimo", "Kūjo", "Eliksyro", "Apsiausto"],
        explanation: "Geležinis žmogus naudoja aukštųjų technologijų šarvus.",
      },
    },
  },
  {
    id: "pop_me_012",
    category: "pop",
    subTheme: "movies",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Film (Finding Nemo, clownfish)",
    emoji: "🐠",
    translations: {
      en: {
        question: "In Finding Nemo, what kind of fish is Nemo?",
        correct: "Clownfish",
        distractors: ["Goldfish", "Shark", "Tuna", "Salmon", "Catfish"],
        explanation: "Nemo is a small orange clownfish.",
      },
      lt: {
        question: "Filme „Žuviukas Nemo” kokia žuvis yra Nemo?",
        correct: "Klounžuvė",
        distractors: ["Auksinė žuvelė", "Ryklys", "Tunas", "Lašiša", "Šamas"],
        explanation: "Nemo — maža oranžinė klounžuvė.",
      },
    },
  },
  {
    id: "pop_me_013",
    category: "pop",
    subTheme: "characters",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Cartoon (Scooby-Doo is a dog)",
    emoji: "🐕",
    translations: {
      en: {
        question: "What kind of animal is Scooby-Doo?",
        correct: "Dog",
        distractors: ["Cat", "Horse", "Bear", "Wolf", "Fox"],
        explanation: "Scooby-Doo is a large Great Dane dog.",
      },
      lt: {
        question: "Koks gyvūnas yra Skubis Dū?",
        correct: "Šuo",
        distractors: ["Katė", "Arklys", "Lokys", "Vilkas", "Lapė"],
        explanation: "Skubis Dū — didelis dogo veislės šuo.",
      },
    },
  },
  {
    id: "pop_me_014",
    category: "pop",
    subTheme: "games",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Games (Pac-Man eats dots)",
    emoji: "🟡",
    translations: {
      en: {
        question: "In the arcade game Pac-Man, the hero eats dots and avoids what?",
        correct: "Ghosts",
        distractors: ["Robots", "Snakes", "Spiders", "Cars", "Bombs"],
        explanation: "Pac-Man eats dots while avoiding ghosts.",
      },
      lt: {
        question: "Žaidime „Pac-Man” herojus ėda taškus ir vengia ko?",
        correct: "Vaiduoklių",
        distractors: ["Robotų", "Gyvačių", "Vorų", "Automobilių", "Bombų"],
        explanation: "„Pac-Man” ėda taškus vengdamas vaiduoklių.",
      },
    },
  },
  {
    id: "pop_me_015",
    category: "pop",
    subTheme: "movies",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Film (The Wizard of Oz, ruby slippers)",
    emoji: "👠",
    translations: {
      en: {
        question: "In The Wizard of Oz, Dorothy follows a road of what color?",
        correct: "Yellow",
        distractors: ["Red", "Blue", "Green", "Silver", "Gold"],
        explanation: "Dorothy follows the yellow brick road.",
      },
      lt: {
        question: "Filme „Ozo šalies burtininkas” Dorotė eina kokios spalvos keliu?",
        correct: "Geltonu",
        distractors: ["Raudonu", "Mėlynu", "Žaliu", "Sidabriniu", "Auksiniu"],
        explanation: "Dorotė eina geltonų plytų keliu.",
      },
    },
  },

  // ======================= SUNKUS (Hard) =======================
  {
    id: "pop_su_001",
    category: "pop",
    subTheme: "movies",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Film (King Kong is a giant ape)",
    emoji: "🦍",
    translations: {
      en: {
        question: "The classic movie monster King Kong is a giant what?",
        correct: "Ape",
        distractors: ["Lizard", "Bear", "Spider", "Shark", "Snake"],
        explanation: "King Kong is a giant ape from 1933 cinema.",
      },
      lt: {
        question: "Klasikinis kino monstras King Kongas yra milžiniškas kas?",
        correct: "Beždžionė",
        distractors: ["Driežas", "Lokys", "Voras", "Ryklys", "Gyvatė"],
        explanation: "King Kongas — milžiniška beždžionė iš 1933 m. kino.",
      },
    },
  },
  {
    id: "pop_su_002",
    category: "pop",
    subTheme: "music",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Music (Mozart was a composer)",
    emoji: "🎼",
    translations: {
      en: {
        question: "Wolfgang Amadeus Mozart is famous as a what?",
        correct: "Composer",
        distractors: ["Painter", "Poet", "Actor", "Sculptor", "Architect"],
        explanation: "Mozart was a famous classical music composer.",
      },
      lt: {
        question: "Volfgangas Amadėjus Mocartas garsus kaip kas?",
        correct: "Kompozitorius",
        distractors: ["Dailininkas", "Poetas", "Aktorius", "Skulptorius", "Architektas"],
        explanation: "Mocartas — garsus klasikinės muzikos kompozitorius.",
      },
    },
  },
  {
    id: "pop_su_003",
    category: "pop",
    subTheme: "movies",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Film (Jaws is about a shark)",
    emoji: "🦈",
    translations: {
      en: {
        question: "The classic thriller Jaws features which creature?",
        correct: "Shark",
        distractors: ["Whale", "Octopus", "Crocodile", "Eel", "Dolphin"],
        explanation: "Jaws is about a great white shark.",
      },
      lt: {
        question: "Klasikiniame trileryje „Nasrai” pagrindinė būtybė yra kuri?",
        correct: "Ryklys",
        distractors: ["Banginis", "Aštonkojis", "Krokodilas", "Ungurys", "Delfinas"],
        explanation: "„Nasrai” — apie didįjį baltąjį ryklį.",
      },
    },
  },
  {
    id: "pop_su_004",
    category: "pop",
    subTheme: "characters",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Books (Sherlock Holmes is a detective)",
    emoji: "🔍",
    translations: {
      en: {
        question: "What is the profession of Sherlock Holmes?",
        correct: "Detective",
        distractors: ["Doctor", "Lawyer", "Captain", "Professor", "Banker"],
        explanation: "Sherlock Holmes is a famous fictional detective.",
      },
      lt: {
        question: "Kokia yra Šerloko Holmso profesija?",
        correct: "Detektyvas",
        distractors: ["Gydytojas", "Advokatas", "Kapitonas", "Profesorius", "Bankininkas"],
        explanation: "Šerlokas Holmsas — garsus literatūrinis detektyvas.",
      },
    },
  },
  {
    id: "pop_su_005",
    category: "pop",
    subTheme: "games",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Games (Zelda hero is Link)",
    emoji: "🗡️",
    translations: {
      en: {
        question: "In The Legend of Zelda games, what is the hero's name?",
        correct: "Link",
        distractors: ["Zelda", "Ganon", "Mario", "Kirby", "Samus"],
        explanation: "The hero of Zelda games is named Link.",
      },
      lt: {
        question: "Žaidimuose „The Legend of Zelda” koks herojaus vardas?",
        correct: "Link",
        distractors: ["Zelda", "Ganon", "Mario", "Kirby", "Samus"],
        explanation: "„Zelda” žaidimų herojus vadinasi Link.",
      },
    },
  },
  {
    id: "pop_su_006",
    category: "pop",
    subTheme: "movies",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Film (Back to the Future time machine car)",
    emoji: "🚗",
    translations: {
      en: {
        question: "In Back to the Future, the time machine is built into a what?",
        correct: "Car",
        distractors: ["Train", "Boat", "Plane", "Phone booth", "Bicycle"],
        explanation: "The time machine is a DeLorean car.",
      },
      lt: {
        question: "Filme „Atgal į ateitį” laiko mašina įmontuota į ką?",
        correct: "Automobilį",
        distractors: ["Traukinį", "Valtį", "Lėktuvą", "Telefono būdelę", "Dviratį"],
        explanation: "Laiko mašina — DeLorean automobilis.",
      },
    },
  },
  {
    id: "pop_su_007",
    category: "pop",
    subTheme: "characters",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Books (Tarzan raised in jungle)",
    emoji: "🌴",
    translations: {
      en: {
        question: "The character Tarzan was raised in the jungle by what?",
        correct: "Apes",
        distractors: ["Wolves", "Lions", "Bears", "Elephants", "Snakes"],
        explanation: "Tarzan was raised by apes in the jungle.",
      },
      lt: {
        question: "Personažą Tarzaną džiunglėse užaugino kas?",
        correct: "Beždžionės",
        distractors: ["Vilkai", "Liūtai", "Lokiai", "Drambliai", "Gyvatės"],
        explanation: "Tarzaną džiunglėse užaugino beždžionės.",
      },
    },
  },
  {
    id: "pop_su_008",
    category: "pop",
    subTheme: "music",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Music (orchestra led by conductor)",
    emoji: "🎻",
    translations: {
      en: {
        question: "Who leads a symphony orchestra?",
        correct: "Conductor",
        distractors: ["Drummer", "Singer", "Pianist", "Producer", "Manager"],
        explanation: "A conductor leads and guides the orchestra.",
      },
      lt: {
        question: "Kas vadovauja simfoniniam orkestrui?",
        correct: "Dirigentas",
        distractors: ["Būgnininkas", "Dainininkas", "Pianistas", "Prodiuseris", "Vadybininkas"],
        explanation: "Dirigentas vadovauja ir veda orkestrą.",
      },
    },
  },
  {
    id: "pop_su_009",
    category: "pop",
    subTheme: "movies",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Film (The Matrix red and blue pill)",
    emoji: "💊",
    translations: {
      en: {
        question: "In The Matrix, Neo is offered a blue pill and which other color?",
        correct: "Red",
        distractors: ["Green", "Yellow", "Black", "White", "Purple"],
        explanation: "Neo chooses between a red and a blue pill.",
      },
      lt: {
        question: "Filme „Matrica” Neo siūloma mėlyna tabletė ir kurios kitos spalvos?",
        correct: "Raudona",
        distractors: ["Žalia", "Geltona", "Juoda", "Balta", "Violetinė"],
        explanation: "Neo renkasi tarp raudonos ir mėlynos tabletės.",
      },
    },
  },
  {
    id: "pop_su_010",
    category: "pop",
    subTheme: "characters",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Books (Pinocchio nose grows)",
    emoji: "👃",
    translations: {
      en: {
        question: "In the story, what happens to Pinocchio's nose when he lies?",
        correct: "It grows longer",
        distractors: ["It turns red", "It falls off", "It shrinks", "It glows", "It bends"],
        explanation: "Pinocchio's nose grows longer when he lies.",
      },
      lt: {
        question: "Pasakoje kas nutinka Pinokio nosiai, kai jis meluoja?",
        correct: "Pailgėja",
        distractors: ["Parausta", "Nukrenta", "Susitraukia", "Švyti", "Sulinksta"],
        explanation: "Pinokio nosis pailgėja, kai jis meluoja.",
      },
    },
  },
  {
    id: "pop_su_011",
    category: "pop",
    subTheme: "games",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Games (Angry Birds launch with slingshot)",
    emoji: "🐦",
    translations: {
      en: {
        question: "In Angry Birds, the birds are launched using a what?",
        correct: "Slingshot",
        distractors: ["Cannon", "Catapult arm", "Bow", "Spring", "Rocket"],
        explanation: "Angry Birds are flung from a slingshot.",
      },
      lt: {
        question: "Žaidime „Angry Birds” paukščiai paleidžiami naudojant ką?",
        correct: "Laidynę",
        distractors: ["Patranką", "Katapultą", "Lanką", "Spyruoklę", "Raketą"],
        explanation: "„Angry Birds” paukščiai paleidžiami iš laidynės.",
      },
    },
  },
  {
    id: "pop_su_012",
    category: "pop",
    subTheme: "movies",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Film (Ghostbusters catch ghosts)",
    emoji: "👻",
    translations: {
      en: {
        question: "In Ghostbusters, the team's job is to catch what?",
        correct: "Ghosts",
        distractors: ["Aliens", "Robots", "Thieves", "Sharks", "Spies"],
        explanation: "The Ghostbusters capture ghosts.",
      },
      lt: {
        question: "Filme „Vaiduoklių medžiotojai” komandos darbas — gaudyti ką?",
        correct: "Vaiduoklius",
        distractors: ["Ateivius", "Robotus", "Vagis", "Ryklius", "Šnipus"],
        explanation: "„Vaiduoklių medžiotojai” gaudo vaiduoklius.",
      },
    },
  },
  {
    id: "pop_su_013",
    category: "pop",
    subTheme: "characters",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Books (Dracula is a vampire)",
    emoji: "🧛",
    translations: {
      en: {
        question: "The famous character Count Dracula is what kind of creature?",
        correct: "Vampire",
        distractors: ["Werewolf", "Ghost", "Zombie", "Wizard", "Goblin"],
        explanation: "Count Dracula is a classic literary vampire.",
      },
      lt: {
        question: "Garsus personažas grafas Drakula yra kokia būtybė?",
        correct: "Vampyras",
        distractors: ["Vilkolakis", "Vaiduoklis", "Zombis", "Burtininkas", "Goblinas"],
        explanation: "Grafas Drakula — klasikinis literatūrinis vampyras.",
      },
    },
  },
  {
    id: "pop_su_014",
    category: "pop",
    subTheme: "movies",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Film (Indiana Jones is an archaeologist)",
    emoji: "🤠",
    translations: {
      en: {
        question: "What is the profession of adventurer Indiana Jones?",
        correct: "Archaeologist",
        distractors: ["Pilot", "Soldier", "Doctor", "Sailor", "Banker"],
        explanation: "Indiana Jones is an adventurous archaeologist.",
      },
      lt: {
        question: "Kokia yra nuotykių ieškotojo Indianos Džonso profesija?",
        correct: "Archeologas",
        distractors: ["Pilotas", "Karys", "Gydytojas", "Jūreivis", "Bankininkas"],
        explanation: "Indiana Džonsas — nuotykių ieškantis archeologas.",
      },
    },
  },
  {
    id: "pop_su_015",
    category: "pop",
    subTheme: "music",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Music (violin played with a bow)",
    emoji: "🎻",
    translations: {
      en: {
        question: "A violin is usually played using a what?",
        correct: "Bow",
        distractors: ["Stick", "Pick", "Hammer", "Mallet", "Brush"],
        explanation: "A violin is played by drawing a bow across strings.",
      },
      lt: {
        question: "Smuiku paprastai grojama naudojant ką?",
        correct: "Stryką",
        distractors: ["Lazdelę", "Mediatorių", "Plaktuką", "Kūjelį", "Šepetėlį"],
        explanation: "Smuiku grojama stryku braukiant per stygas.",
      },
    },
  },

  // ======================= EKSTREMALUS (Extreme) =======================
  {
    id: "pop_ek_001",
    category: "pop",
    subTheme: "movies",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Film history (first sound feature, 1927)",
    emoji: "🎞️",
    translations: {
      en: {
        question: "Early cinema before the late 1920s mostly lacked what?",
        correct: "Sound",
        distractors: ["Actors", "Cameras", "Film", "Scripts", "Lights"],
        explanation: "Early films were silent; sync sound arrived around 1927.",
      },
      lt: {
        question: "Ankstyvame kine iki XX a. 3-iojo dešimtmečio pabaigos dažniausiai trūko ko?",
        correct: "Garso",
        distractors: ["Aktorių", "Kamerų", "Juostos", "Scenarijų", "Šviesų"],
        explanation: "Ankstyvi filmai buvo nebylūs; garsas atėjo apie 1927 m.",
      },
    },
  },
  {
    id: "pop_ek_002",
    category: "pop",
    subTheme: "music",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Music (Beethoven composed while deaf)",
    emoji: "🎼",
    translations: {
      en: {
        question: "Which famous composer kept working after going deaf?",
        correct: "Beethoven",
        distractors: ["Mozart", "Bach", "Chopin", "Vivaldi", "Haydn"],
        explanation: "Beethoven composed major works while deaf.",
      },
      lt: {
        question: "Kuris garsus kompozitorius kūrė apkurtęs?",
        correct: "Bethovenas",
        distractors: ["Mocartas", "Bachas", "Šopenas", "Vivaldis", "Haidnas"],
        explanation: "Bethovenas kūrė svarbius kūrinius būdamas kurčias.",
      },
    },
  },
  {
    id: "pop_ek_003",
    category: "pop",
    subTheme: "games",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Games (Tetris created in 1984, USSR)",
    emoji: "🟦",
    translations: {
      en: {
        question: "The puzzle game Tetris was originally created in which country?",
        correct: "Soviet Union",
        distractors: ["Japan", "USA", "Germany", "France", "Sweden"],
        explanation: "Tetris was created in 1984 in the Soviet Union.",
      },
      lt: {
        question: "Galvosūkis „Tetris” iš pradžių sukurtas kurioje šalyje?",
        correct: "Sovietų Sąjungoje",
        distractors: ["Japonijoje", "JAV", "Vokietijoje", "Prancūzijoje", "Švedijoje"],
        explanation: "„Tetris” sukurtas 1984 m. Sovietų Sąjungoje.",
      },
    },
  },
  {
    id: "pop_ek_004",
    category: "pop",
    subTheme: "characters",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Books (Frankenstein author Mary Shelley)",
    emoji: "📖",
    translations: {
      en: {
        question: "Who wrote the classic novel Frankenstein?",
        correct: "Mary Shelley",
        distractors: ["Bram Stoker", "Jane Austen", "Jules Verne", "Edgar Poe", "H. G. Wells"],
        explanation: "Mary Shelley wrote Frankenstein in 1818.",
      },
      lt: {
        question: "Kas parašė klasikinį romaną „Frankenšteinas”?",
        correct: "Mary Shelley",
        distractors: ["Bram Stoker", "Jane Austen", "Žiulis Vernas", "Edgaras Po", "H. G. Wells"],
        explanation: "Mary Shelley parašė „Frankenšteiną” 1818 m.",
      },
    },
  },
  {
    id: "pop_ek_005",
    category: "pop",
    subTheme: "movies",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Film (Psycho director Hitchcock)",
    emoji: "🎬",
    translations: {
      en: {
        question: "Which director was known as the Master of Suspense?",
        correct: "Hitchcock",
        distractors: ["Spielberg", "Kubrick", "Chaplin", "Lucas", "Disney"],
        explanation: "Alfred Hitchcock was called the Master of Suspense.",
      },
      lt: {
        question: "Kuris režisierius vadintas įtampos meistru?",
        correct: "Hitchcock",
        distractors: ["Spielberg", "Kubrick", "Chaplin", "Lucas", "Disney"],
        explanation: "Alfredas Hičkokas vadintas įtampos (suspense) meistru.",
      },
    },
  },
  {
    id: "pop_ek_006",
    category: "pop",
    subTheme: "music",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Music (Elvis Presley King of Rock and Roll)",
    emoji: "🎤",
    translations: {
      en: {
        question: "Which singer was nicknamed the King of Rock and Roll?",
        correct: "Elvis Presley",
        distractors: ["Frank Sinatra", "Chuck Berry", "Buddy Holly", "Ray Charles", "Roy Orbison"],
        explanation: "Elvis Presley was called the King of Rock and Roll.",
      },
      lt: {
        question: "Kuris dainininkas vadintas roko karaliumi?",
        correct: "Elvis Presley",
        distractors: ["Frank Sinatra", "Chuck Berry", "Buddy Holly", "Ray Charles", "Roy Orbison"],
        explanation: "Elvis Presley vadintas roko ir rolo karaliumi.",
      },
    },
  },
  {
    id: "pop_ek_007",
    category: "pop",
    subTheme: "characters",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Books (Dracula author Bram Stoker)",
    emoji: "🧛",
    translations: {
      en: {
        question: "Who wrote the classic novel Dracula?",
        correct: "Bram Stoker",
        distractors: ["Mary Shelley", "Edgar Poe", "Oscar Wilde", "Jules Verne", "Mark Twain"],
        explanation: "Bram Stoker published Dracula in 1897.",
      },
      lt: {
        question: "Kas parašė klasikinį romaną „Drakula”?",
        correct: "Bram Stoker",
        distractors: ["Mary Shelley", "Edgaras Po", "Oscar Wilde", "Žiulis Vernas", "Mark Twain"],
        explanation: "Bram Stoker išleido „Drakulą” 1897 m.",
      },
    },
  },
  {
    id: "pop_ek_008",
    category: "pop",
    subTheme: "movies",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Animation (Snow White first Disney feature 1937)",
    emoji: "🍎",
    translations: {
      en: {
        question: "Which was Disney's first full-length animated feature?",
        correct: "Snow White",
        distractors: ["Cinderella", "Bambi", "Pinocchio", "Dumbo", "Peter Pan"],
        explanation: "Snow White (1937) was Disney's first animated feature.",
      },
      lt: {
        question: "Kuris buvo pirmas pilnametražis Disnėjaus animacinis filmas?",
        correct: "Snieguolė",
        distractors: ["Pelenė", "Bembis", "Pinokis", "Dambo", "Piteris Penas"],
        explanation: "„Snieguolė” (1937) — pirmas Disnėjaus animacinis filmas.",
      },
    },
  },
  {
    id: "pop_ek_009",
    category: "pop",
    subTheme: "games",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Games (Pong early arcade game)",
    emoji: "🏓",
    translations: {
      en: {
        question: "The early arcade game Pong is based on which sport?",
        correct: "Table tennis",
        distractors: ["Football", "Boxing", "Golf", "Racing", "Bowling"],
        explanation: "Pong simulates simple table tennis.",
      },
      lt: {
        question: "Ankstyvas žaidimas „Pong” pagrįstas kuriuo sportu?",
        correct: "Stalo tenisu",
        distractors: ["Futbolu", "Boksu", "Golfu", "Lenktynėmis", "Boulingu"],
        explanation: "„Pong” imituoja paprastą stalo tenisą.",
      },
    },
  },
  {
    id: "pop_ek_010",
    category: "pop",
    subTheme: "characters",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Books (Robinson Crusoe stranded on island)",
    emoji: "🏝️",
    translations: {
      en: {
        question: "The classic character Robinson Crusoe is stranded where?",
        correct: "On an island",
        distractors: ["In a desert", "In a cave", "On a mountain", "In a city", "On a ship only"],
        explanation: "Robinson Crusoe is shipwrecked on a deserted island.",
      },
      lt: {
        question: "Klasikinis personažas Robinzonas Kruzas atsiduria kur?",
        correct: "Saloje",
        distractors: ["Dykumoje", "Oloje", "Ant kalno", "Mieste", "Tik laive"],
        explanation: "Robinzonas Kruzas patiria laivo avariją negyvenamoje saloje.",
      },
    },
  },
  {
    id: "pop_ek_011",
    category: "pop",
    subTheme: "music",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Music (full-size piano has 88 keys)",
    emoji: "🎹",
    translations: {
      en: {
        question: "How many keys does a standard full-size piano have?",
        correct: "88",
        distractors: ["61", "76", "92", "100", "64"],
        explanation: "A full-size piano has 88 keys: 52 white and 36 black.",
      },
      lt: {
        question: "Kiek klavišų turi standartinis pilno dydžio pianinas?",
        correct: "88",
        distractors: ["61", "76", "92", "100", "64"],
        explanation: "Pilno dydžio pianinas turi 88 klavišus: 52 baltus ir 36 juodus.",
      },
    },
  },
  {
    id: "pop_ek_012",
    category: "pop",
    subTheme: "movies",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Film (Charlie Chaplin silent comedy)",
    emoji: "🎩",
    translations: {
      en: {
        question: "Charlie Chaplin became famous in which film era?",
        correct: "Silent films",
        distractors: ["3D films", "Color films", "Sound films", "Digital films", "Online films"],
        explanation: "Chaplin was a star of the silent film era.",
      },
      lt: {
        question: "Čarlis Čaplinas išgarsėjo kuria kino era?",
        correct: "Nebyliais filmais",
        distractors: ["3D filmais", "Spalvotais filmais", "Garsiniais filmais", "Skaitmeniniais", "Internetiniais"],
        explanation: "Čaplinas — nebyliojo kino eros žvaigždė.",
      },
    },
  },
  {
    id: "pop_ek_013",
    category: "pop",
    subTheme: "characters",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Books (Alice in Wonderland by Lewis Carroll)",
    emoji: "🐇",
    translations: {
      en: {
        question: "In Alice in Wonderland, Alice follows which animal down a hole?",
        correct: "White Rabbit",
        distractors: ["Cat", "Mouse", "Fox", "Owl", "Frog"],
        explanation: "Alice follows the White Rabbit into Wonderland.",
      },
      lt: {
        question: "„Alisoje stebuklų šalyje” Alisa seka kurį gyvūną į urvą?",
        correct: "Baltąjį triušį",
        distractors: ["Katę", "Pelę", "Lapę", "Pelėdą", "Varlę"],
        explanation: "Alisa seka Baltąjį triušį į stebuklų šalį.",
      },
    },
  },
  {
    id: "pop_ek_014",
    category: "pop",
    subTheme: "games",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Games (Mario created by Nintendo, Japan)",
    emoji: "🎮",
    translations: {
      en: {
        question: "Which company created the character Mario?",
        correct: "Nintendo",
        distractors: ["Sega", "Sony", "Atari", "Microsoft", "Capcom"],
        explanation: "Mario is Nintendo's flagship character.",
      },
      lt: {
        question: "Kuri kompanija sukūrė personažą Mario?",
        correct: "Nintendo",
        distractors: ["Sega", "Sony", "Atari", "Microsoft", "Capcom"],
        explanation: "Mario — pagrindinis Nintendo personažas.",
      },
    },
  },
  {
    id: "pop_ek_015",
    category: "pop",
    subTheme: "movies",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Film (The Lord of the Rings by Tolkien)",
    emoji: "💍",
    translations: {
      en: {
        question: "The Lord of the Rings is based on books by which author?",
        correct: "Tolkien",
        distractors: ["C. S. Lewis", "George Orwell", "Roald Dahl", "Ian Fleming", "Stephen King"],
        explanation: "The Lord of the Rings was written by J. R. R. Tolkien.",
      },
      lt: {
        question: "„Žiedų valdovas” paremtas kurio autoriaus knygomis?",
        correct: "Tolkien",
        distractors: ["C. S. Lewis", "George Orwell", "Roald Dahl", "Ian Fleming", "Stephen King"],
        explanation: "„Žiedų valdovą” parašė J. R. R. Tolkienas.",
      },
    },
  },
];
