/**
 * popContent — „Pop kultūra ir pramogos” trivijos klausimai (EN + LT).
 *
 * Po 15 klausimų kiekvienam lygiui (lengvas/vidutinis/sunkus/ekstremalus) = 60.
 * Temos: klasikiniai filmai, ikoniniai personažai, animacija, žaidimai, muzika.
 * SVARBU: VENGIAME greitai senstančių faktų (dabartinių topų, „naujausių”) —
 * tik tvarūs, įsitvirtinę faktai, kurie nepasens.
 *
 * TAISYKLĖS (Manifestas):
 *   - 1 teisingas + 5 distractors; visi 6 variantai VISOSE kalbose ≤46 simbolių;
 *   - faktai 100% patikrinti (sourceVerified); neutralu (jokios politikos/religijos);
 *   - LT vidinės kabutės tik „...” (ne ASCII "); detalės — į explanation, ne į variantą.
 *
 * Formatas — žr. triviaTypes.ts (TriviaQuestion). category visada "pop".
 */

import { TriviaQuestion } from "./triviaTypes";

export const POP_QUESTIONS: TriviaQuestion[] = [
  // ======================= LENGVAS (Easy) =======================
  {
    id: "pop_le_001",
    category: "pop",
    subTheme: "characters",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Disney (Mickey Mouse is a mouse)",
    emoji: "🐭",
    translations: {
      en: {
        question: "What kind of animal is Mickey Mouse?",
        correct: "Mouse",
        distractors: ["Cat", "Dog", "Rabbit", "Bear", "Duck"],
        explanation: "Mickey Mouse is Disney's famous cartoon mouse.",
      },
      lt: {
        question: "Koks gyvūnas yra Peliukas Mikis?",
        correct: "Pelė",
        distractors: ["Katė", "Šuo", "Triušis", "Lokys", "Antis"],
        explanation: "Peliukas Mikis — garsi Disnėjaus animacinė pelė.",
      },
    },
  },
  {
    id: "pop_le_002",
    category: "pop",
    subTheme: "movies",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Film (The Lion King setting)",
    emoji: "🦁",
    translations: {
      en: {
        question: "Which animal is the hero Simba in The Lion King?",
        correct: "Lion",
        distractors: ["Tiger", "Leopard", "Cheetah", "Wolf", "Bear"],
        explanation: "Simba is a lion cub in The Lion King.",
      },
      lt: {
        question: "Koks gyvūnas yra herojus Simba filme „Liūtas karalius”?",
        correct: "Liūtas",
        distractors: ["Tigras", "Leopardas", "Gepardas", "Vilkas", "Lokys"],
        explanation: "Simba — liūtukas filme „Liūtas karalius”.",
      },
    },
  },
  {
    id: "pop_le_003",
    category: "pop",
    subTheme: "games",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Video games (Mario is a plumber)",
    emoji: "🍄",
    translations: {
      en: {
        question: "What is the job of the video game hero Mario?",
        correct: "Plumber",
        distractors: ["Doctor", "Pilot", "Chef", "Teacher", "Soldier"],
        explanation: "Mario is famously a plumber in Nintendo games.",
      },
      lt: {
        question: "Kokia yra žaidimų herojaus Mario profesija?",
        correct: "Santechnikas",
        distractors: ["Gydytojas", "Pilotas", "Virėjas", "Mokytojas", "Karys"],
        explanation: "Mario Nintendo žaidimuose yra santechnikas.",
      },
    },
  },
  {
    id: "pop_le_004",
    category: "pop",
    subTheme: "characters",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Cartoon (SpongeBob lives underwater)",
    emoji: "🧽",
    translations: {
      en: {
        question: "Where does SpongeBob SquarePants live?",
        correct: "Underwater",
        distractors: ["On a mountain", "In space", "In a desert", "In a forest", "On the Moon"],
        explanation: "SpongeBob lives in the underwater town of Bikini Bottom.",
      },
      lt: {
        question: "Kur gyvena Kempiniukas Plačiakelnis?",
        correct: "Po vandeniu",
        distractors: ["Ant kalno", "Kosmose", "Dykumoje", "Miške", "Ant Mėnulio"],
        explanation: "Kempiniukas gyvena povandeniniame miestelyje.",
      },
    },
  },
  {
    id: "pop_le_005",
    category: "pop",
    subTheme: "superheroes",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Comics (Spider-Man powers)",
    emoji: "🕷️",
    translations: {
      en: {
        question: "Which animal gives Spider-Man his name?",
        correct: "Spider",
        distractors: ["Bat", "Ant", "Scorpion", "Beetle", "Fly"],
        explanation: "Spider-Man is named after a spider.",
      },
      lt: {
        question: "Pagal kurį gyvūną pavadintas Žmogus-voras?",
        correct: "Voras",
        distractors: ["Šikšnosparnis", "Skruzdėlė", "Skorpionas", "Vabalas", "Musė"],
        explanation: "Žmogus-voras pavadintas pagal vorą.",
      },
    },
  },
  {
    id: "pop_le_006",
    category: "pop",
    subTheme: "superheroes",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Comics (Batman city is Gotham)",
    emoji: "🦇",
    translations: {
      en: {
        question: "Which animal inspires Batman's costume?",
        correct: "Bat",
        distractors: ["Cat", "Owl", "Crow", "Wolf", "Spider"],
        explanation: "Batman's costume is based on a bat.",
      },
      lt: {
        question: "Pagal kurį gyvūną sukurtas Betmeno kostiumas?",
        correct: "Šikšnosparnis",
        distractors: ["Katė", "Pelėda", "Varna", "Vilkas", "Voras"],
        explanation: "Betmeno kostiumas pagrįstas šikšnosparniu.",
      },
    },
  },
  {
    id: "pop_le_007",
    category: "pop",
    subTheme: "movies",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Film (Frozen sisters)",
    emoji: "❄️",
    translations: {
      en: {
        question: "In Frozen, Elsa has the power to control what?",
        correct: "Ice and snow",
        distractors: ["Fire", "Water", "Wind", "Lightning", "Sand"],
        explanation: "Elsa can create and control ice and snow.",
      },
      lt: {
        question: "Ką filme „Ledo šalis” valdo Elza?",
        correct: "Ledą ir sniegą",
        distractors: ["Ugnį", "Vandenį", "Vėją", "Žaibą", "Smėlį"],
        explanation: "Elza kuria ir valdo ledą bei sniegą.",
      },
    },
  },
  {
    id: "pop_le_008",
    category: "pop",
    subTheme: "characters",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Cartoon (Pikachu is yellow)",
    emoji: "⚡",
    translations: {
      en: {
        question: "What color is Pikachu from Pokemon?",
        correct: "Yellow",
        distractors: ["Blue", "Red", "Green", "Pink", "Purple"],
        explanation: "Pikachu is a yellow electric Pokemon.",
      },
      lt: {
        question: "Kokios spalvos yra Pikachu iš Pokemon?",
        correct: "Geltonas",
        distractors: ["Mėlynas", "Raudonas", "Žalias", "Rožinis", "Violetinis"],
        explanation: "Pikachu — geltonas elektrinis pokemonas.",
      },
    },
  },
  {
    id: "pop_le_009",
    category: "pop",
    subTheme: "music",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Music (guitar is string instrument)",
    emoji: "🎸",
    translations: {
      en: {
        question: "Which of these is a string instrument?",
        correct: "Guitar",
        distractors: ["Drum", "Flute", "Trumpet", "Whistle", "Tambourine"],
        explanation: "A guitar makes sound from vibrating strings.",
      },
      lt: {
        question: "Kuris iš šių yra styginis instrumentas?",
        correct: "Gitara",
        distractors: ["Būgnas", "Fleita", "Trimitas", "Švilpukas", "Tamburinas"],
        explanation: "Gitara skleidžia garsą iš virpančių stygų.",
      },
    },
  },
  {
    id: "pop_le_010",
    category: "pop",
    subTheme: "movies",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Film (Toy Story toys)",
    emoji: "🤠",
    translations: {
      en: {
        question: "Toy Story is a film about toys that can do what?",
        correct: "Come alive",
        distractors: ["Fly planes", "Cook food", "Drive cars", "Swim deep", "Build houses"],
        explanation: "In Toy Story the toys come alive when no one looks.",
      },
      lt: {
        question: "Ką geba žaislai filme „Žaislų istorija”?",
        correct: "Atgyti",
        distractors: ["Skraidyti lėktuvais", "Gaminti maistą", "Vairuoti", "Nardyti", "Statyti namus"],
        explanation: "„Žaislų istorijoje” žaislai atgyja, kai niekas nemato.",
      },
    },
  },
  {
    id: "pop_le_011",
    category: "pop",
    subTheme: "characters",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Cartoon (Tom and Jerry, cat and mouse)",
    emoji: "🐱",
    translations: {
      en: {
        question: "In Tom and Jerry, Tom is what animal?",
        correct: "Cat",
        distractors: ["Mouse", "Dog", "Bird", "Fish", "Rabbit"],
        explanation: "Tom is the cat who chases Jerry the mouse.",
      },
      lt: {
        question: "Animaciniame „Tomas ir Džeris” Tomas yra koks gyvūnas?",
        correct: "Katė",
        distractors: ["Pelė", "Šuo", "Paukštis", "Žuvis", "Triušis"],
        explanation: "Tomas — katinas, vejantis pelę Džerį.",
      },
    },
  },
  {
    id: "pop_le_012",
    category: "pop",
    subTheme: "games",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Games (Minecraft is block-building)",
    emoji: "⛏️",
    translations: {
      en: {
        question: "The game Minecraft is famous for building with what?",
        correct: "Blocks",
        distractors: ["Cards", "Balls", "Ropes", "Bricks of gold", "Paper"],
        explanation: "Minecraft is built from cube-shaped blocks.",
      },
      lt: {
        question: "Žaidimas „Minecraft” garsus statymu iš ko?",
        correct: "Blokų",
        distractors: ["Kortų", "Kamuolių", "Virvių", "Aukso plytų", "Popieriaus"],
        explanation: "„Minecraft” statoma iš kubo formos blokų.",
      },
    },
  },
  {
    id: "pop_le_013",
    category: "pop",
    subTheme: "movies",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Film (Star Wars laser sword)",
    emoji: "⚔️",
    translations: {
      en: {
        question: "What is the glowing sword in Star Wars called?",
        correct: "Lightsaber",
        distractors: ["Laser bow", "Plasma axe", "Beam spear", "Star blade", "Glow knife"],
        explanation: "Jedi and Sith fight with lightsabers.",
      },
      lt: {
        question: "Kaip vadinamas švytintis kardas filme „Žvaigždžių karai”?",
        correct: "Šviesos kardas",
        distractors: ["Lazerio lankas", "Plazmos kirvis", "Spindulio ietis", "Žvaigždės geležtė", "Švytintis peilis"],
        explanation: "Džedajai ir sithai kaunasi šviesos kardais.",
      },
    },
  },
  {
    id: "pop_le_014",
    category: "pop",
    subTheme: "characters",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Cartoon (Winnie the Pooh loves honey)",
    emoji: "🍯",
    translations: {
      en: {
        question: "What food does Winnie the Pooh love most?",
        correct: "Honey",
        distractors: ["Carrots", "Fish", "Bananas", "Cheese", "Bread"],
        explanation: "Winnie the Pooh is famous for loving honey.",
      },
      lt: {
        question: "Kokį maistą labiausiai mėgsta Mikė Pūkuotukas?",
        correct: "Medų",
        distractors: ["Morkas", "Žuvį", "Bananus", "Sūrį", "Duoną"],
        explanation: "Mikė Pūkuotukas garsėja meile medui.",
      },
    },
  },
  {
    id: "pop_le_015",
    category: "pop",
    subTheme: "movies",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Film (Harry Potter is a wizard)",
    emoji: "🧙",
    translations: {
      en: {
        question: "What is Harry Potter trained to become?",
        correct: "A wizard",
        distractors: ["A pirate", "A knight", "A pilot", "A doctor", "A king"],
        explanation: "Harry Potter studies to become a wizard.",
      },
      lt: {
        question: "Kuo mokomas tapti Haris Poteris?",
        correct: "Burtininku",
        distractors: ["Piratu", "Riteriu", "Pilotu", "Gydytoju", "Karaliumi"],
        explanation: "Haris Poteris mokosi tapti burtininku.",
      },
    },
  },

  // ======================= VIDUTINIS (Medium) =======================
  {
    id: "pop_me_001",
    category: "pop",
    subTheme: "movies",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Film studio (Pixar made Toy Story)",
    emoji: "🎬",
    translations: {
      en: {
        question: "Which studio made the first fully computer-animated feature film?",
        correct: "Pixar",
        distractors: ["Disney only", "Warner Bros", "DreamWorks", "Sony", "Universal"],
        explanation: "Pixar made Toy Story, the first CGI feature, in 1995.",
      },
      lt: {
        question: "Kuri studija sukūrė pirmą pilnai kompiuterinį animacinį filmą?",
        correct: "Pixar",
        distractors: ["Tik Disney", "Warner Bros", "DreamWorks", "Sony", "Universal"],
        explanation: "Pixar 1995 m. sukūrė „Žaislų istoriją”, pirmą CGI filmą.",
      },
    },
  },
  {
    id: "pop_me_002",
    category: "pop",
    subTheme: "music",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Music (The Beatles from Liverpool)",
    emoji: "🎵",
    translations: {
      en: {
        question: "The famous band The Beatles came from which city?",
        correct: "Liverpool",
        distractors: ["London", "Manchester", "Dublin", "Glasgow", "Leeds"],
        explanation: "The Beatles formed in Liverpool, England.",
      },
      lt: {
        question: "Iš kurio miesto kilo garsioji grupė „The Beatles”?",
        correct: "Liverpulis",
        distractors: ["Londonas", "Mančesteris", "Dublinas", "Glazgas", "Lidsas"],
        explanation: "„The Beatles” susikūrė Liverpulyje, Anglijoje.",
      },
    },
  },
  {
    id: "pop_me_003",
    category: "pop",
    subTheme: "superheroes",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Comics (Superman home planet Krypton)",
    emoji: "🦸",
    translations: {
      en: {
        question: "What is the home planet of Superman?",
        correct: "Krypton",
        distractors: ["Mars", "Tatooine", "Vulcan", "Asgard", "Saturn"],
        explanation: "Superman was born on the planet Krypton.",
      },
      lt: {
        question: "Kokia yra Supermeno gimtoji planeta?",
        correct: "Kriptonas",
        distractors: ["Marsas", "Tatuinas", "Vulkanas", "Asgardas", "Saturnas"],
        explanation: "Supermenas gimė planetoje Kriptonas.",
      },
    },
  },
  {
    id: "pop_me_004",
    category: "pop",
    subTheme: "games",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Games (Tetris falling shapes)",
    emoji: "🟦",
    translations: {
      en: {
        question: "In the game Tetris, you arrange falling what?",
        correct: "Blocks",
        distractors: ["Cards", "Bubbles", "Coins", "Stars", "Letters"],
        explanation: "Tetris is about fitting falling block shapes.",
      },
      lt: {
        question: "Kokie krintantys daiktai dėliojami žaidime „Tetris”?",
        correct: "Blokai",
        distractors: ["Kortos", "Burbulai", "Monetos", "Žvaigždės", "Raidės"],
        explanation: "„Tetris” — krintančių blokų dėliojimas.",
      },
    },
  },
  {
    id: "pop_me_005",
    category: "pop",
    subTheme: "movies",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Film (Jurassic Park dinosaurs)",
    emoji: "🦖",
    translations: {
      en: {
        question: "The Jurassic Park films are famous for bringing back what?",
        correct: "Dinosaurs",
        distractors: ["Robots", "Aliens", "Dragons", "Pirates", "Vampires"],
        explanation: "Jurassic Park is about recreated dinosaurs.",
      },
      lt: {
        question: "Kokius gyvūnus atgaivino filmai „Juros periodo parkas”?",
        correct: "Dinozaurus",
        distractors: ["Robotus", "Ateivius", "Drakonus", "Piratus", "Vampyrus"],
        explanation: "„Juros periodo parkas” — apie atkurtus dinozaurus.",
      },
    },
  },
  {
    id: "pop_me_006",
    category: "pop",
    subTheme: "characters",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Cartoon (Simpsons hometown Springfield)",
    emoji: "🍩",
    translations: {
      en: {
        question: "In which town does The Simpsons take place?",
        correct: "Springfield",
        distractors: ["Gotham", "Bedrock", "Quahog", "Shelbyville", "Metropolis"],
        explanation: "The Simpsons live in the town of Springfield.",
      },
      lt: {
        question: "Kuriame miestelyje vyksta „Simpsonų” veiksmas?",
        correct: "Springfildas",
        distractors: ["Gotamas", "Bedrokas", "Kvahogas", "Šelbivilis", "Metropolis"],
        explanation: "Simpsonai gyvena Springfildo miestelyje.",
      },
    },
  },
  {
    id: "pop_me_007",
    category: "pop",
    subTheme: "music",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Music (piano has black and white keys)",
    emoji: "🎹",
    translations: {
      en: {
        question: "A piano is played by pressing what?",
        correct: "Keys",
        distractors: ["Strings only", "Pedals only", "Buttons of brass", "Frets", "Valves"],
        explanation: "A piano is played using its black and white keys.",
      },
      lt: {
        question: "Ką spaudžiant grojama pianinu?",
        correct: "Klavišus",
        distractors: ["Tik stygas", "Tik pedalus", "Žalvario mygtukus", "Ladus", "Vožtuvus"],
        explanation: "Pianinu grojama spaudžiant juodus ir baltus klavišus.",
      },
    },
  },
  {
    id: "pop_me_008",
    category: "pop",
    subTheme: "movies",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Film (E.T. is an alien)",
    emoji: "👽",
    translations: {
      en: {
        question: "In the classic film E.T., what is E.T.?",
        correct: "An alien",
        distractors: ["A robot", "A ghost", "A wizard", "A dinosaur", "A pirate"],
        explanation: "E.T. is a friendly alien stranded on Earth.",
      },
      lt: {
        question: "Klasikiniame filme „E.T.” kas yra E.T.?",
        correct: "Ateivis",
        distractors: ["Robotas", "Vaiduoklis", "Burtininkas", "Dinozauras", "Piratas"],
        explanation: "E.T. — draugiškas ateivis, įstrigęs Žemėje.",
      },
    },
  },
  {
    id: "pop_me_009",
    category: "pop",
    subTheme: "characters",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Games (Sonic is a hedgehog)",
    emoji: "💨",
    translations: {
      en: {
        question: "What kind of animal is the game character Sonic?",
        correct: "Hedgehog",
        distractors: ["Fox", "Squirrel", "Rabbit", "Mouse", "Cat"],
        explanation: "Sonic is a fast blue hedgehog.",
      },
      lt: {
        question: "Koks gyvūnas yra žaidimų personažas Sonikas?",
        correct: "Ežys",
        distractors: ["Lapė", "Voverė", "Triušis", "Pelė", "Katė"],
        explanation: "Sonikas — greitas mėlynas ežys.",
      },
    },
  },
  {
    id: "pop_me_010",
    category: "pop",
    subTheme: "movies",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Film (Shrek is an ogre)",
    emoji: "🟢",
    translations: {
      en: {
        question: "What kind of creature is Shrek?",
        correct: "Ogre",
        distractors: ["Troll", "Goblin", "Giant", "Dragon", "Wizard"],
        explanation: "Shrek is a green ogre in the DreamWorks films.",
      },
      lt: {
        question: "Kokia būtybė yra Šrekas?",
        correct: "Ogras",
        distractors: ["Trolis", "Goblinas", "Milžinas", "Drakonas", "Burtininkas"],
        explanation: "Šrekas — žalias ogras DreamWorks filmuose.",
      },
    },
  },
  {
    id: "pop_me_011",
    category: "pop",
    subTheme: "superheroes",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Comics (Iron Man wears a suit)",
    emoji: "🤖",
    translations: {
      en: {
        question: "Iron Man's powers mainly come from what?",
        correct: "A powered suit",
        distractors: ["A magic ring", "A spider bite", "A hammer", "A potion", "A cape"],
        explanation: "Iron Man uses a high-tech powered armor suit.",
      },
      lt: {
        question: "Iš ko daugiausia kyla Geležinio žmogaus galios?",
        correct: "Galingo kostiumo",
        distractors: ["Magiško žiedo", "Voro įkandimo", "Kūjo", "Eliksyro", "Apsiausto"],
        explanation: "Geležinis žmogus naudoja aukštųjų technologijų šarvus.",
      },
    },
  },
  {
    id: "pop_me_012",
    category: "pop",
    subTheme: "movies",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Film (Finding Nemo, clownfish)",
    emoji: "🐠",
    translations: {
      en: {
        question: "In Finding Nemo, what kind of fish is Nemo?",
        correct: "Clownfish",
        distractors: ["Goldfish", "Shark", "Tuna", "Salmon", "Catfish"],
        explanation: "Nemo is a small orange clownfish.",
      },
      lt: {
        question: "Filme „Žuviukas Nemo” kokia žuvis yra Nemo?",
        correct: "Klounžuvė",
        distractors: ["Auksinė žuvelė", "Ryklys", "Tunas", "Lašiša", "Šamas"],
        explanation: "Nemo — maža oranžinė klounžuvė.",
      },
    },
  },
  {
    id: "pop_me_013",
    category: "pop",
    subTheme: "characters",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Cartoon (Scooby-Doo is a dog)",
    emoji: "🐕",
    translations: {
      en: {
        question: "What kind of animal is Scooby-Doo?",
        correct: "Dog",
        distractors: ["Cat", "Horse", "Bear", "Wolf", "Fox"],
        explanation: "Scooby-Doo is a large Great Dane dog.",
      },
      lt: {
        question: "Koks gyvūnas yra Skubis Dū?",
        correct: "Šuo",
        distractors: ["Katė", "Arklys", "Lokys", "Vilkas", "Lapė"],
        explanation: "Skubis Dū — didelis dogo veislės šuo.",
      },
    },
  },
  {
    id: "pop_me_014",
    category: "pop",
    subTheme: "games",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Games (Pac-Man eats dots)",
    emoji: "🟡",
    translations: {
      en: {
        question: "In the arcade game Pac-Man, the hero eats dots and avoids what?",
        correct: "Ghosts",
        distractors: ["Robots", "Snakes", "Spiders", "Cars", "Bombs"],
        explanation: "Pac-Man eats dots while avoiding ghosts.",
      },
      lt: {
        question: "Žaidime „Pac-Man” herojus ėda taškus ir vengia ko?",
        correct: "Vaiduoklių",
        distractors: ["Robotų", "Gyvačių", "Vorų", "Automobilių", "Bombų"],
        explanation: "„Pac-Man” ėda taškus vengdamas vaiduoklių.",
      },
    },
  },
  {
    id: "pop_me_015",
    category: "pop",
    subTheme: "movies",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Film (The Wizard of Oz, ruby slippers)",
    emoji: "👠",
    translations: {
      en: {
        question: "In The Wizard of Oz, Dorothy follows a road of what color?",
        correct: "Yellow",
        distractors: ["Red", "Blue", "Green", "Silver", "Gold"],
        explanation: "Dorothy follows the yellow brick road.",
      },
      lt: {
        question: "Filme „Ozo šalies burtininkas” Dorotė eina kokios spalvos keliu?",
        correct: "Geltonu",
        distractors: ["Raudonu", "Mėlynu", "Žaliu", "Sidabriniu", "Auksiniu"],
        explanation: "Dorotė eina geltonų plytų keliu.",
      },
    },
  },

  // ======================= SUNKUS (Hard) =======================
  {
    id: "pop_su_001",
    category: "pop",
    subTheme: "movies",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Film (King Kong is a giant ape)",
    emoji: "🦍",
    translations: {
      en: {
        question: "The classic movie monster King Kong is a giant what?",
        correct: "Ape",
        distractors: ["Lizard", "Bear", "Spider", "Shark", "Snake"],
        explanation: "King Kong is a giant ape from 1933 cinema.",
      },
      lt: {
        question: "Koks milžiniškas gyvūnas yra kino monstras King Kongas?",
        correct: "Beždžionė",
        distractors: ["Driežas", "Lokys", "Voras", "Ryklys", "Gyvatė"],
        explanation: "King Kongas — milžiniška beždžionė iš 1933 m. kino.",
      },
    },
  },
  {
    id: "pop_su_002",
    category: "pop",
    subTheme: "music",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Music (Mozart was a composer)",
    emoji: "🎼",
    translations: {
      en: {
        question: "Wolfgang Amadeus Mozart is famous as a what?",
        correct: "Composer",
        distractors: ["Painter", "Poet", "Actor", "Sculptor", "Architect"],
        explanation: "Mozart was a famous classical music composer.",
      },
      lt: {
        question: "Volfgangas Amadėjus Mocartas labiausiai žinomas kaip...?",
        correct: "Kompozitorius",
        distractors: ["Dailininkas", "Poetas", "Aktorius", "Skulptorius", "Architektas"],
        explanation: "Mocartas — garsus klasikinės muzikos kompozitorius.",
      },
    },
  },
  {
    id: "pop_su_003",
    category: "pop",
    subTheme: "movies",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Film (Jaws is about a shark)",
    emoji: "🦈",
    translations: {
      en: {
        question: "The classic thriller Jaws features which creature?",
        correct: "Shark",
        distractors: ["Whale", "Octopus", "Crocodile", "Eel", "Dolphin"],
        explanation: "Jaws is about a great white shark.",
      },
      lt: {
        question: "Kokia būtybė yra pagrindinė klasikiniame trileryje „Nasrai”?",
        correct: "Ryklys",
        distractors: ["Banginis", "Aštuonkojis", "Krokodilas", "Ungurys", "Delfinas"],
        explanation: "„Nasrai” — apie didįjį baltąjį ryklį.",
      },
    },
  },
  {
    id: "pop_su_004",
    category: "pop",
    subTheme: "characters",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Books (Sherlock Holmes is a detective)",
    emoji: "🔍",
    translations: {
      en: {
        question: "What is the profession of Sherlock Holmes?",
        correct: "Detective",
        distractors: ["Doctor", "Lawyer", "Captain", "Professor", "Banker"],
        explanation: "Sherlock Holmes is a famous fictional detective.",
      },
      lt: {
        question: "Kokia yra Šerloko Holmso profesija?",
        correct: "Detektyvas",
        distractors: ["Gydytojas", "Advokatas", "Kapitonas", "Profesorius", "Bankininkas"],
        explanation: "Šerlokas Holmsas — garsus literatūrinis detektyvas.",
      },
    },
  },
  {
    id: "pop_su_005",
    category: "pop",
    subTheme: "games",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Games (Zelda hero is Link)",
    emoji: "🗡️",
    translations: {
      en: {
        question: "In The Legend of Zelda games, what is the hero's name?",
        correct: "Link",
        distractors: ["Zelda", "Ganon", "Mario", "Kirby", "Samus"],
        explanation: "The hero of Zelda games is named Link.",
      },
      lt: {
        question: "Žaidimuose „The Legend of Zelda” koks herojaus vardas?",
        correct: "Link",
        distractors: ["Zelda", "Ganon", "Mario", "Kirby", "Samus"],
        explanation: "„Zelda” žaidimų herojus vadinasi Link.",
      },
    },
  },
  {
    id: "pop_su_006",
    category: "pop",
    subTheme: "movies",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Film (Back to the Future time machine car)",
    emoji: "🚗",
    translations: {
      en: {
        question: "In Back to the Future, the time machine is built into a what?",
        correct: "Car",
        distractors: ["Train", "Boat", "Plane", "Phone booth", "Bicycle"],
        explanation: "The time machine is a DeLorean car.",
      },
      lt: {
        question: "Į ką filme „Atgal į ateitį” įmontuota laiko mašina?",
        correct: "Automobilį",
        distractors: ["Traukinį", "Valtį", "Lėktuvą", "Telefono būdelę", "Dviratį"],
        explanation: "Laiko mašina — DeLorean automobilis.",
      },
    },
  },
  {
    id: "pop_su_007",
    category: "pop",
    subTheme: "characters",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Books (Tarzan raised in jungle)",
    emoji: "🌴",
    translations: {
      en: {
        question: "The character Tarzan was raised in the jungle by what?",
        correct: "Apes",
        distractors: ["Wolves", "Lions", "Bears", "Elephants", "Snakes"],
        explanation: "Tarzan was raised by apes in the jungle.",
      },
      lt: {
        question: "Kas džiunglėse užaugino personažą Tarzaną?",
        correct: "Beždžionės",
        distractors: ["Vilkai", "Liūtai", "Lokiai", "Drambliai", "Gyvatės"],
        explanation: "Tarzaną džiunglėse užaugino beždžionės.",
      },
    },
  },
  {
    id: "pop_su_008",
    category: "pop",
    subTheme: "music",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Music (orchestra led by conductor)",
    emoji: "🎻",
    translations: {
      en: {
        question: "Who leads a symphony orchestra?",
        correct: "Conductor",
        distractors: ["Drummer", "Singer", "Pianist", "Producer", "Manager"],
        explanation: "A conductor leads and guides the orchestra.",
      },
      lt: {
        question: "Kas vadovauja simfoniniam orkestrui?",
        correct: "Dirigentas",
        distractors: ["Būgnininkas", "Dainininkas", "Pianistas", "Prodiuseris", "Vadybininkas"],
        explanation: "Dirigentas vadovauja ir veda orkestrą.",
      },
    },
  },
  {
    id: "pop_su_009",
    category: "pop",
    subTheme: "movies",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Film (The Matrix red and blue pill)",
    emoji: "💊",
    translations: {
      en: {
        question: "In The Matrix, Neo is offered a blue pill and which other color?",
        correct: "Red",
        distractors: ["Green", "Yellow", "Black", "White", "Purple"],
        explanation: "Neo chooses between a red and a blue pill.",
      },
      lt: {
        question: "Filme „Matrica” Neo siūloma mėlyna tabletė ir kurios kitos spalvos?",
        correct: "Raudona",
        distractors: ["Žalia", "Geltona", "Juoda", "Balta", "Violetinė"],
        explanation: "Neo renkasi tarp raudonos ir mėlynos tabletės.",
      },
    },
  },
  {
    id: "pop_su_010",
    category: "pop",
    subTheme: "characters",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Books (Pinocchio nose grows)",
    emoji: "👃",
    translations: {
      en: {
        question: "In the story, what happens to Pinocchio's nose when he lies?",
        correct: "It grows longer",
        distractors: ["It turns red", "It falls off", "It shrinks", "It glows", "It bends"],
        explanation: "Pinocchio's nose grows longer when he lies.",
      },
      lt: {
        question: "Pasakoje kas nutinka Pinokio nosiai, kai jis meluoja?",
        correct: "Pailgėja",
        distractors: ["Parausta", "Nukrenta", "Susitraukia", "Švyti", "Sulinksta"],
        explanation: "Pinokio nosis pailgėja, kai jis meluoja.",
      },
    },
  },
  {
    id: "pop_su_011",
    category: "pop",
    subTheme: "games",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Games (Angry Birds launch with slingshot)",
    emoji: "🐦",
    translations: {
      en: {
        question: "In Angry Birds, the birds are launched using a what?",
        correct: "Slingshot",
        distractors: ["Cannon", "Catapult arm", "Bow", "Spring", "Rocket"],
        explanation: "Angry Birds are flung from a slingshot.",
      },
      lt: {
        question: "Ką naudojant žaidime „Angry Birds” paleidžiami paukščiai?",
        correct: "Laidynę",
        distractors: ["Patranką", "Katapultą", "Lanką", "Spyruoklę", "Raketą"],
        explanation: "„Angry Birds” paukščiai paleidžiami iš laidynės.",
      },
    },
  },
  {
    id: "pop_su_012",
    category: "pop",
    subTheme: "movies",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Film (Ghostbusters catch ghosts)",
    emoji: "👻",
    translations: {
      en: {
        question: "In Ghostbusters, the team's job is to catch what?",
        correct: "Ghosts",
        distractors: ["Aliens", "Robots", "Thieves", "Sharks", "Spies"],
        explanation: "The Ghostbusters capture ghosts.",
      },
      lt: {
        question: "Ką gaudo komanda filme „Vaiduoklių medžiotojai”?",
        correct: "Vaiduoklius",
        distractors: ["Ateivius", "Robotus", "Vagis", "Ryklius", "Šnipus"],
        explanation: "„Vaiduoklių medžiotojai” gaudo vaiduoklius.",
      },
    },
  },
  {
    id: "pop_su_013",
    category: "pop",
    subTheme: "characters",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Books (Dracula is a vampire)",
    emoji: "🧛",
    translations: {
      en: {
        question: "The famous character Count Dracula is what kind of creature?",
        correct: "Vampire",
        distractors: ["Werewolf", "Ghost", "Zombie", "Wizard", "Goblin"],
        explanation: "Count Dracula is a classic literary vampire.",
      },
      lt: {
        question: "Garsus personažas grafas Drakula yra kokia būtybė?",
        correct: "Vampyras",
        distractors: ["Vilkolakis", "Vaiduoklis", "Zombis", "Burtininkas", "Goblinas"],
        explanation: "Grafas Drakula — klasikinis literatūrinis vampyras.",
      },
    },
  },
  {
    id: "pop_su_014",
    category: "pop",
    subTheme: "movies",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Film (Indiana Jones is an archaeologist)",
    emoji: "🤠",
    translations: {
      en: {
        question: "What is the profession of adventurer Indiana Jones?",
        correct: "Archaeologist",
        distractors: ["Pilot", "Soldier", "Doctor", "Sailor", "Banker"],
        explanation: "Indiana Jones is an adventurous archaeologist.",
      },
      lt: {
        question: "Kokia yra nuotykių ieškotojo Indianos Džonso profesija?",
        correct: "Archeologas",
        distractors: ["Pilotas", "Karys", "Gydytojas", "Jūreivis", "Bankininkas"],
        explanation: "Indiana Džonsas — nuotykių ieškantis archeologas.",
      },
    },
  },
  {
    id: "pop_su_015",
    category: "pop",
    subTheme: "music",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Music (violin played with a bow)",
    emoji: "🎻",
    translations: {
      en: {
        question: "A violin is usually played using a what?",
        correct: "Bow",
        distractors: ["Stick", "Pick", "Hammer", "Mallet", "Brush"],
        explanation: "A violin is played by drawing a bow across strings.",
      },
      lt: {
        question: "Ką naudojant paprastai grojama smuiku?",
        correct: "Stryką",
        distractors: ["Lazdelę", "Mediatorių", "Plaktuką", "Kūjelį", "Šepetėlį"],
        explanation: "Smuiku grojama stryku braukiant per stygas.",
      },
    },
  },

  // ======================= EKSTREMALUS (Extreme) =======================
  {
    id: "pop_ek_001",
    category: "pop",
    subTheme: "movies",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Film history (first sound feature, 1927)",
    emoji: "🎞️",
    translations: {
      en: {
        question: "Early cinema before the late 1920s mostly lacked what?",
        correct: "Sound",
        distractors: ["Actors", "Cameras", "Film", "Scripts", "Lights"],
        explanation: "Early films were silent; sync sound arrived around 1927.",
      },
      lt: {
        question: "Ankstyvame kine iki XX a. 3-iojo dešimtmečio pabaigos dažniausiai trūko ko?",
        correct: "Garso",
        distractors: ["Aktorių", "Kamerų", "Juostos", "Scenarijų", "Šviesų"],
        explanation: "Ankstyvi filmai buvo nebylūs; garsas atėjo apie 1927 m.",
      },
    },
  },
  {
    id: "pop_ek_002",
    category: "pop",
    subTheme: "music",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Music (Beethoven composed while deaf)",
    emoji: "🎼",
    translations: {
      en: {
        question: "Which famous composer kept working after going deaf?",
        correct: "Beethoven",
        distractors: ["Mozart", "Bach", "Chopin", "Vivaldi", "Haydn"],
        explanation: "Beethoven composed major works while deaf.",
      },
      lt: {
        question: "Kuris garsus kompozitorius kūrė apkurtęs?",
        correct: "Bethovenas",
        distractors: ["Mocartas", "Bachas", "Šopenas", "Vivaldis", "Haidnas"],
        explanation: "Bethovenas kūrė svarbius kūrinius būdamas kurčias.",
      },
    },
  },
  {
    id: "pop_ek_003",
    category: "pop",
    subTheme: "games",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Games (Tetris created in 1984, USSR)",
    emoji: "🟦",
    translations: {
      en: {
        question: "The puzzle game Tetris was originally created in which country?",
        correct: "Soviet Union",
        distractors: ["Japan", "USA", "Germany", "France", "Sweden"],
        explanation: "Tetris was created in 1984 in the Soviet Union.",
      },
      lt: {
        question: "Galvosūkis „Tetris” iš pradžių sukurtas kurioje šalyje?",
        correct: "Sovietų Sąjungoje",
        distractors: ["Japonijoje", "JAV", "Vokietijoje", "Prancūzijoje", "Švedijoje"],
        explanation: "„Tetris” sukurtas 1984 m. Sovietų Sąjungoje.",
      },
    },
  },
  {
    id: "pop_ek_004",
    category: "pop",
    subTheme: "characters",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Books (Frankenstein author Mary Shelley)",
    emoji: "📖",
    translations: {
      en: {
        question: "Who wrote the classic novel Frankenstein?",
        correct: "Mary Shelley",
        distractors: ["Bram Stoker", "Jane Austen", "Jules Verne", "Edgar Poe", "H. G. Wells"],
        explanation: "Mary Shelley wrote Frankenstein in 1818.",
      },
      lt: {
        question: "Kas parašė klasikinį romaną „Frankenšteinas”?",
        correct: "Mary Shelley",
        distractors: ["Bram Stoker", "Jane Austen", "Žiulis Vernas", "Edgaras Po", "H. G. Wells"],
        explanation: "Mary Shelley parašė „Frankenšteiną” 1818 m.",
      },
    },
  },
  {
    id: "pop_ek_005",
    category: "pop",
    subTheme: "movies",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Film (Psycho director Hitchcock)",
    emoji: "🎬",
    translations: {
      en: {
        question: "Which director was known as the Master of Suspense?",
        correct: "Hitchcock",
        distractors: ["Spielberg", "Kubrick", "Chaplin", "Lucas", "Disney"],
        explanation: "Alfred Hitchcock was called the Master of Suspense.",
      },
      lt: {
        question: "Kuris režisierius vadintas įtampos meistru?",
        correct: "Hitchcock",
        distractors: ["Spielberg", "Kubrick", "Chaplin", "Lucas", "Disney"],
        explanation: "Alfredas Hičkokas vadintas įtampos (suspense) meistru.",
      },
    },
  },
  {
    id: "pop_ek_006",
    category: "pop",
    subTheme: "music",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Music (Elvis Presley King of Rock and Roll)",
    emoji: "🎤",
    translations: {
      en: {
        question: "Which singer was nicknamed the King of Rock and Roll?",
        correct: "Elvis Presley",
        distractors: ["Frank Sinatra", "Chuck Berry", "Buddy Holly", "Ray Charles", "Roy Orbison"],
        explanation: "Elvis Presley was called the King of Rock and Roll.",
      },
      lt: {
        question: "Kuris dainininkas vadintas roko karaliumi?",
        correct: "Elvis Presley",
        distractors: ["Frank Sinatra", "Chuck Berry", "Buddy Holly", "Ray Charles", "Roy Orbison"],
        explanation: "Elvis Presley vadintas roko ir rolo karaliumi.",
      },
    },
  },
  {
    id: "pop_ek_007",
    category: "pop",
    subTheme: "characters",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Books (Dracula author Bram Stoker)",
    emoji: "🧛",
    translations: {
      en: {
        question: "Who wrote the classic novel Dracula?",
        correct: "Bram Stoker",
        distractors: ["Mary Shelley", "Edgar Poe", "Oscar Wilde", "Jules Verne", "Mark Twain"],
        explanation: "Bram Stoker published Dracula in 1897.",
      },
      lt: {
        question: "Kas parašė klasikinį romaną „Drakula”?",
        correct: "Bram Stoker",
        distractors: ["Mary Shelley", "Edgaras Po", "Oscar Wilde", "Žiulis Vernas", "Mark Twain"],
        explanation: "Bram Stoker išleido „Drakulą” 1897 m.",
      },
    },
  },
  {
    id: "pop_ek_008",
    category: "pop",
    subTheme: "movies",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Animation (Snow White first Disney feature 1937)",
    emoji: "🍎",
    translations: {
      en: {
        question: "Which was Disney's first full-length animated feature?",
        correct: "Snow White",
        distractors: ["Cinderella", "Bambi", "Pinocchio", "Dumbo", "Peter Pan"],
        explanation: "Snow White (1937) was Disney's first animated feature.",
      },
      lt: {
        question: "Kuris buvo pirmas pilnametražis Disnėjaus animacinis filmas?",
        correct: "Snieguolė",
        distractors: ["Pelenė", "Bembis", "Pinokis", "Dambo", "Piteris Penas"],
        explanation: "„Snieguolė” (1937) — pirmas Disnėjaus animacinis filmas.",
      },
    },
  },
  {
    id: "pop_ek_009",
    category: "pop",
    subTheme: "games",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Games (Pong early arcade game)",
    emoji: "🏓",
    translations: {
      en: {
        question: "The early arcade game Pong is based on which sport?",
        correct: "Table tennis",
        distractors: ["Football", "Boxing", "Golf", "Racing", "Bowling"],
        explanation: "Pong simulates simple table tennis.",
      },
      lt: {
        question: "Ankstyvas žaidimas „Pong” pagrįstas kuriuo sportu?",
        correct: "Stalo tenisu",
        distractors: ["Futbolu", "Boksu", "Golfu", "Lenktynėmis", "Boulingu"],
        explanation: "„Pong” imituoja paprastą stalo tenisą.",
      },
    },
  },
  {
    id: "pop_ek_010",
    category: "pop",
    subTheme: "characters",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Books (Robinson Crusoe stranded on island)",
    emoji: "🏝️",
    translations: {
      en: {
        question: "The classic character Robinson Crusoe is stranded where?",
        correct: "On an island",
        distractors: ["In a desert", "In a cave", "On a mountain", "In a city", "On a ship only"],
        explanation: "Robinson Crusoe is shipwrecked on a deserted island.",
      },
      lt: {
        question: "Kur atsiduria klasikinis personažas Robinzonas Kruzas?",
        correct: "Saloje",
        distractors: ["Dykumoje", "Oloje", "Ant kalno", "Mieste", "Tik laive"],
        explanation: "Robinzonas Kruzas patiria laivo avariją negyvenamoje saloje.",
      },
    },
  },
  {
    id: "pop_ek_011",
    category: "pop",
    subTheme: "music",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Music (full-size piano has 88 keys)",
    emoji: "🎹",
    translations: {
      en: {
        question: "How many keys does a standard full-size piano have?",
        correct: "88",
        distractors: ["61", "76", "92", "100", "64"],
        explanation: "A full-size piano has 88 keys: 52 white and 36 black.",
      },
      lt: {
        question: "Kiek klavišų turi standartinis pilno dydžio pianinas?",
        correct: "88",
        distractors: ["61", "76", "92", "100", "64"],
        explanation: "Pilno dydžio pianinas turi 88 klavišus: 52 baltus ir 36 juodus.",
      },
    },
  },
  {
    id: "pop_ek_012",
    category: "pop",
    subTheme: "movies",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Film (Charlie Chaplin silent comedy)",
    emoji: "🎩",
    translations: {
      en: {
        question: "Charlie Chaplin became famous in which film era?",
        correct: "Silent films",
        distractors: ["3D films", "Color films", "Sound films", "Digital films", "Online films"],
        explanation: "Chaplin was a star of the silent film era.",
      },
      lt: {
        question: "Kokiais filmais išgarsėjo Čarlis Čaplinas?",
        correct: "Nebyliais filmais",
        distractors: ["3D filmais", "Spalvotais filmais", "Garsiniais filmais", "Skaitmeniniais", "Internetiniais"],
        explanation: "Čaplinas — nebyliojo kino eros žvaigždė.",
      },
    },
  },
  {
    id: "pop_ek_013",
    category: "pop",
    subTheme: "characters",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Books (Alice in Wonderland by Lewis Carroll)",
    emoji: "🐇",
    translations: {
      en: {
        question: "In Alice in Wonderland, Alice follows which animal down a hole?",
        correct: "White Rabbit",
        distractors: ["Cat", "Mouse", "Fox", "Owl", "Frog"],
        explanation: "Alice follows the White Rabbit into Wonderland.",
      },
      lt: {
        question: "„Alisoje stebuklų šalyje” Alisa seka kurį gyvūną į urvą?",
        correct: "Baltąjį triušį",
        distractors: ["Katę", "Pelę", "Lapę", "Pelėdą", "Varlę"],
        explanation: "Alisa seka Baltąjį triušį į stebuklų šalį.",
      },
    },
  },
  {
    id: "pop_ek_014",
    category: "pop",
    subTheme: "games",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Games (Mario created by Nintendo, Japan)",
    emoji: "🎮",
    translations: {
      en: {
        question: "Which company created the character Mario?",
        correct: "Nintendo",
        distractors: ["Sega", "Sony", "Atari", "Microsoft", "Capcom"],
        explanation: "Mario is Nintendo's flagship character.",
      },
      lt: {
        question: "Kuri kompanija sukūrė personažą Mario?",
        correct: "Nintendo",
        distractors: ["Sega", "Sony", "Atari", "Microsoft", "Capcom"],
        explanation: "Mario — pagrindinis Nintendo personažas.",
      },
    },
  },
  {
    id: "pop_ek_015",
    category: "pop",
    subTheme: "movies",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Film (The Lord of the Rings by Tolkien)",
    emoji: "💍",
    translations: {
      en: {
        question: "The Lord of the Rings is based on books by which author?",
        correct: "Tolkien",
        distractors: ["C. S. Lewis", "George Orwell", "Roald Dahl", "Ian Fleming", "Stephen King"],
        explanation: "The Lord of the Rings was written by J. R. R. Tolkien.",
      },
      lt: {
        question: "„Žiedų valdovas” paremtas kurio autoriaus knygomis?",
        correct: "Tolkien",
        distractors: ["C. S. Lewis", "George Orwell", "Roald Dahl", "Ian Fleming", "Stephen King"],
        explanation: "„Žiedų valdovą” parašė J. R. R. Tolkienas.",
      },
    },
  },
  {
    id: "pop_le_016",
    category: "pop",
    subTheme: "cartoons",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Cookie Monster is blue",
    emoji: "🍪",
    translations: {
      en: {
        question: "What color is the Cookie Monster from Sesame Street?",
        correct: "Blue",
        distractors: ["Red", "Green", "Yellow", "Purple", "Orange"],
        explanation: "Cookie Monster is a furry blue character.",
      },
      lt: {
        question: "Kokios spalvos yra Sausainių Pabaisa iš „Sezamo gatvės”?",
        correct: "Mėlyna",
        distractors: ["Raudona", "Žalia", "Geltona", "Violetinė", "Oranžinė"],
        explanation: "Sausainių Pabaisa — mėlynas pūkuotas personažas.",
      },
    },
  },
  {
    id: "pop_le_017",
    category: "pop",
    subTheme: "cartoons",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Bugs Bunny is a rabbit",
    emoji: "🐰",
    translations: {
      en: {
        question: "What kind of animal is Bugs Bunny?",
        correct: "Rabbit",
        distractors: ["Mouse", "Cat", "Dog", "Duck", "Fox"],
        explanation: "Bugs Bunny is a cartoon rabbit.",
      },
      lt: {
        question: "Koks gyvūnas yra Bugs Bunny?",
        correct: "Triušis",
        distractors: ["Pelė", "Katė", "Šuo", "Antis", "Lapė"],
        explanation: "Bugs Bunny — animacinis triušis.",
      },
    },
  },
  {
    id: "pop_le_018",
    category: "pop",
    subTheme: "movies",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Cinderella loses a glass slipper",
    emoji: "👠",
    translations: {
      en: {
        question: "In Cinderella, what does she lose at midnight?",
        correct: "A glass slipper",
        distractors: ["A crown", "A ring", "A necklace", "A glove", "A cape"],
        explanation: "Cinderella leaves behind a glass slipper.",
      },
      lt: {
        question: "Ką Pelenė pameta vidurnaktį?",
        correct: "Stiklinę šlepetę",
        distractors: ["Karūną", "Žiedą", "Vėrinį", "Pirštinę", "Apsiaustą"],
        explanation: "Pelenė palieka stiklinę šlepetę.",
      },
    },
  },
  {
    id: "pop_le_019",
    category: "pop",
    subTheme: "movies",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Snow White and seven dwarfs",
    emoji: "7️⃣",
    translations: {
      en: {
        question: "Snow White is befriended by how many dwarfs?",
        correct: "Seven",
        distractors: ["Five", "Six", "Three", "Eight", "Ten"],
        explanation: "Snow White lives with seven dwarfs.",
      },
      lt: {
        question: "Su kiek nykštukų draugauja Snieguolė?",
        correct: "Septyniais",
        distractors: ["Penkiais", "Šešiais", "Trimis", "Aštuoniais", "Dešimčia"],
        explanation: "Snieguolė gyvena su septyniais nykštukais.",
      },
    },
  },
  {
    id: "pop_le_020",
    category: "pop",
    subTheme: "cartoons",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Donald Duck is a duck",
    emoji: "🦆",
    translations: {
      en: {
        question: "What kind of animal is Donald Duck?",
        correct: "Duck",
        distractors: ["Goose", "Chicken", "Swan", "Turkey", "Eagle"],
        explanation: "Donald Duck is a cartoon duck.",
      },
      lt: {
        question: "Koks gyvūnas yra Donaldas Antinas?",
        correct: "Antis",
        distractors: ["Žąsis", "Višta", "Gulbė", "Kalakutas", "Erelis"],
        explanation: "Donaldas Antinas — animacinė antis.",
      },
    },
  },
  {
    id: "pop_le_021",
    category: "pop",
    subTheme: "music",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Drummer hits drums",
    emoji: "🥁",
    translations: {
      en: {
        question: "What does a drummer hit to make sound?",
        correct: "Drums",
        distractors: ["Strings", "Keys", "Pedals", "Buttons", "Reeds"],
        explanation: "A drummer plays by hitting drums.",
      },
      lt: {
        question: "Į ką muša būgnininkas, kad pasigirstų garsas?",
        correct: "Būgnus",
        distractors: ["Stygas", "Klavišus", "Pedalus", "Mygtukus", "Liežuvėlius"],
        explanation: "Būgnininkas groja mušdamas būgnus.",
      },
    },
  },
  {
    id: "pop_le_022",
    category: "pop",
    subTheme: "movies",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Peter Pan fairy is Tinker Bell",
    emoji: "✨",
    translations: {
      en: {
        question: "In Peter Pan, who is the little fairy companion?",
        correct: "Tinker Bell",
        distractors: ["Wendy", "Alice", "Cinderella", "Snow White", "Belle"],
        explanation: "Tinker Bell is Peter Pan's fairy friend.",
      },
      lt: {
        question: "Kas yra mažoji fėja iš „Piterio Peno”?",
        correct: "Žvangutė",
        distractors: ["Vendė", "Alisa", "Pelenė", "Snieguolė", "Belė"],
        explanation: "Žvangutė — Piterio Peno fėja draugė.",
      },
    },
  },
  {
    id: "pop_le_023",
    category: "pop",
    subTheme: "cartoons",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Garfield is a cat",
    emoji: "🐱",
    translations: {
      en: {
        question: "What kind of animal is Garfield?",
        correct: "Cat",
        distractors: ["Dog", "Mouse", "Rabbit", "Lion", "Tiger"],
        explanation: "Garfield is a lazy orange cat.",
      },
      lt: {
        question: "Koks gyvūnas yra Garfildas?",
        correct: "Katė",
        distractors: ["Šuo", "Pelė", "Triušis", "Liūtas", "Tigras"],
        explanation: "Garfildas — tingi oranžinė katė.",
      },
    },
  },
  {
    id: "pop_le_024",
    category: "pop",
    subTheme: "heroes",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "The Hulk is green",
    emoji: "💚",
    translations: {
      en: {
        question: "What color is the comic hero the Hulk?",
        correct: "Green",
        distractors: ["Red", "Blue", "Yellow", "Purple", "Grey"],
        explanation: "The Hulk is a big green superhero.",
      },
      lt: {
        question: "Kokios spalvos yra komiksų herojus Halkas?",
        correct: "Žalia",
        distractors: ["Raudona", "Mėlyna", "Geltona", "Violetinė", "Pilka"],
        explanation: "Halkas — didelis žalias superherojus.",
      },
    },
  },
  {
    id: "pop_le_025",
    category: "pop",
    subTheme: "music",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Saxophone is a wind instrument",
    emoji: "🎷",
    translations: {
      en: {
        question: "Which instrument do you blow into and is common in jazz?",
        correct: "Saxophone",
        distractors: ["Violin", "Piano", "Drums", "Harp", "Guitar"],
        explanation: "The saxophone is a wind instrument used in jazz.",
      },
      lt: {
        question: "Į kurį instrumentą pučiama ir jis dažnas džiaze?",
        correct: "Saksofonas",
        distractors: ["Smuikas", "Pianinas", "Būgnai", "Arfa", "Gitara"],
        explanation: "Saksofonas — pučiamasis instrumentas, dažnas džiaze.",
      },
    },
  },
  {
    id: "pop_le_026",
    category: "pop",
    subTheme: "movies",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Beauty and the Beast heroine is Belle",
    emoji: "🌹",
    translations: {
      en: {
        question: "In Beauty and the Beast, what is the heroine's name?",
        correct: "Belle",
        distractors: ["Ariel", "Jasmine", "Aurora", "Mulan", "Tiana"],
        explanation: "Belle is the heroine of Beauty and the Beast.",
      },
      lt: {
        question: "Koks pagrindinės herojės vardas filme „Gražuolė ir pabaisa”?",
        correct: "Belė",
        distractors: ["Arielė", "Jasminė", "Aurora", "Mulan", "Tiana"],
        explanation: "Belė — „Gražuolės ir pabaisos” herojė.",
      },
    },
  },
  {
    id: "pop_le_027",
    category: "pop",
    subTheme: "movies",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Dumbo is an elephant",
    emoji: "🐘",
    translations: {
      en: {
        question: "What kind of animal is Disney's Dumbo?",
        correct: "Elephant",
        distractors: ["Mouse", "Bird", "Horse", "Bear", "Pig"],
        explanation: "Dumbo is a young elephant with big ears.",
      },
      lt: {
        question: "Koks gyvūnas yra Disnėjaus Dambo?",
        correct: "Dramblys",
        distractors: ["Pelė", "Paukštis", "Arklys", "Lokys", "Kiaulė"],
        explanation: "Dambo — drambliukas didelėmis ausimis.",
      },
    },
  },
  {
    id: "pop_le_028",
    category: "pop",
    subTheme: "movies",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Ariel is a mermaid",
    emoji: "🧜",
    translations: {
      en: {
        question: "In The Little Mermaid, Ariel is a what?",
        correct: "Mermaid",
        distractors: ["Fairy", "Witch", "Pirate", "Ghost", "Princess on land"],
        explanation: "Ariel is a mermaid who wants to live on land.",
      },
      lt: {
        question: "Kas yra Arielė filme „Undinėlė”?",
        correct: "Undinė",
        distractors: ["Fėja", "Ragana", "Piratė", "Vaiduoklis", "Sausumos princesė"],
        explanation: "Arielė — undinė, norinti gyventi sausumoje.",
      },
    },
  },
  {
    id: "pop_le_029",
    category: "pop",
    subTheme: "movies",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "An actor performs in films",
    emoji: "🎬",
    translations: {
      en: {
        question: "What do you call a person who performs in films?",
        correct: "Actor",
        distractors: ["Director", "Painter", "Singer", "Dancer", "Writer"],
        explanation: "An actor performs roles in films and plays.",
      },
      lt: {
        question: "Kaip vadinamas žmogus, vaidinantis filmuose?",
        correct: "Aktorius",
        distractors: ["Režisierius", "Dailininkas", "Dainininkas", "Šokėjas", "Rašytojas"],
        explanation: "Aktorius vaidina vaidmenis filmuose ir spektakliuose.",
      },
    },
  },
  {
    id: "pop_le_030",
    category: "pop",
    subTheme: "music",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Guitar has 6 strings",
    emoji: "🎸",
    translations: {
      en: {
        question: "Which 6-stringed instrument is strummed in pop music?",
        correct: "Guitar",
        distractors: ["Violin", "Piano", "Flute", "Drums", "Trumpet"],
        explanation: "The guitar usually has six strings.",
      },
      lt: {
        question: "Kuris 6 stygų instrumentas brazdinamas pop muzikoje?",
        correct: "Gitara",
        distractors: ["Smuikas", "Pianinas", "Fleita", "Būgnai", "Trimitas"],
        explanation: "Gitara paprastai turi šešias stygas.",
      },
    },
  },
  {
    id: "pop_me_016",
    category: "pop",
    subTheme: "art",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Mona Lisa by Leonardo da Vinci",
    emoji: "🎨",
    translations: {
      en: {
        question: "Who painted the Mona Lisa?",
        correct: "Leonardo da Vinci",
        distractors: ["Michelangelo", "Picasso", "Van Gogh", "Rembrandt", "Raphael"],
        explanation: "The Mona Lisa was painted by Leonardo da Vinci.",
      },
      lt: {
        question: "Kas nutapė Moną Lizą?",
        correct: "Leonardas da Vinčis",
        distractors: ["Mikelandželas", "Pikasas", "Van Gogas", "Rembrantas", "Rafaelis"],
        explanation: "Moną Lizą nutapė Leonardas da Vinčis.",
      },
    },
  },
  {
    id: "pop_me_017",
    category: "pop",
    subTheme: "myth",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Icarus flew too close to the sun",
    emoji: "☀️",
    translations: {
      en: {
        question: "In Greek myth, who flew too close to the sun with wax wings?",
        correct: "Icarus",
        distractors: ["Hercules", "Perseus", "Achilles", "Zeus", "Orpheus"],
        explanation: "Icarus's wax wings melted near the sun.",
      },
      lt: {
        question: "Graikų mite kas su vaškiniais sparnais skrido per arti saulės?",
        correct: "Ikaras",
        distractors: ["Heraklis", "Persėjas", "Achilas", "Dzeusas", "Orfėjas"],
        explanation: "Ikaro vaškiniai sparnai ištirpo prie saulės.",
      },
    },
  },
  {
    id: "pop_me_018",
    category: "pop",
    subTheme: "books",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Brothers Grimm wrote fairy tales",
    emoji: "📖",
    translations: {
      en: {
        question: "Which brothers wrote classic tales like Hansel and Gretel?",
        correct: "The Brothers Grimm",
        distractors: ["Andersen", "Aesop", "Perrault", "Tolkien", "Dahl"],
        explanation: "The Brothers Grimm collected many classic fairy tales.",
      },
      lt: {
        question: "Kurie broliai užrašė klasikines pasakas kaip „Jonukas ir Grytutė”?",
        correct: "Broliai Grimai",
        distractors: ["Andersenas", "Ezopas", "Pero", "Tolkienas", "Dahlas"],
        explanation: "Broliai Grimai surinko daug klasikinių pasakų.",
      },
    },
  },
  {
    id: "pop_me_019",
    category: "pop",
    subTheme: "books",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Shakespeare wrote Romeo and Juliet",
    emoji: "🎭",
    translations: {
      en: {
        question: "Who wrote the play Romeo and Juliet?",
        correct: "William Shakespeare",
        distractors: ["Charles Dickens", "Mark Twain", "Jane Austen", "Homer", "Tolstoy"],
        explanation: "Romeo and Juliet was written by William Shakespeare.",
      },
      lt: {
        question: "Kas parašė pjesę „Romeo ir Džuljeta”?",
        correct: "Viljamas Šekspyras",
        distractors: ["Čarlzas Dikensas", "Markas Tvenas", "Džeinė Ostin", "Homeras", "Tolstojus"],
        explanation: "„Romeo ir Džuljetą” parašė Viljamas Šekspyras.",
      },
    },
  },
  {
    id: "pop_me_020",
    category: "pop",
    subTheme: "myth",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Thor is Norse god of thunder",
    emoji: "⚡",
    translations: {
      en: {
        question: "In Norse myth, who is the god of thunder with a hammer?",
        correct: "Thor",
        distractors: ["Odin", "Loki", "Zeus", "Apollo", "Hermes"],
        explanation: "Thor wields a hammer and rules thunder in Norse myth.",
      },
      lt: {
        question: "Skandinavų mite kas yra griaustinio dievas su kūju?",
        correct: "Toras",
        distractors: ["Odinas", "Lokis", "Dzeusas", "Apolonas", "Hermis"],
        explanation: "Toras valdo griaustinį ir nešioja kūjį.",
      },
    },
  },
  {
    id: "pop_me_021",
    category: "pop",
    subTheme: "art",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Rodin sculpted The Thinker",
    emoji: "🗿",
    translations: {
      en: {
        question: "Which sculptor created the famous statue The Thinker?",
        correct: "Auguste Rodin",
        distractors: ["Michelangelo", "Donatello", "Bernini", "Canova", "Picasso"],
        explanation: "The Thinker was sculpted by Auguste Rodin.",
      },
      lt: {
        question: "Kuris skulptorius sukūrė garsiąją skulptūrą „Mąstytojas”?",
        correct: "Ogiustas Rodenas",
        distractors: ["Mikelandželas", "Donatelas", "Berninis", "Kanova", "Pikasas"],
        explanation: "„Mąstytoją” sukūrė Ogiustas Rodenas.",
      },
    },
  },
  {
    id: "pop_me_022",
    category: "pop",
    subTheme: "music",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Violin has 4 strings",
    emoji: "🎻",
    translations: {
      en: {
        question: "How many strings does a standard violin have?",
        correct: "4",
        distractors: ["6", "5", "3", "7", "8"],
        explanation: "A standard violin has four strings.",
      },
      lt: {
        question: "Kiek stygų turi standartinis smuikas?",
        correct: "4",
        distractors: ["6", "5", "3", "7", "8"],
        explanation: "Standartinis smuikas turi keturias stygas.",
      },
    },
  },
  {
    id: "pop_me_023",
    category: "pop",
    subTheme: "books",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Tortoise beats the hare fable",
    emoji: "🐢",
    translations: {
      en: {
        question: "In Aesop's fable, which slow animal beats the hare in a race?",
        correct: "The tortoise",
        distractors: ["The fox", "The dog", "The rabbit", "The deer", "The horse"],
        explanation: "The steady tortoise beats the overconfident hare.",
      },
      lt: {
        question: "Ezopo pasakėčioje koks lėtas gyvūnas lenktynėse nugali kiškį?",
        correct: "Vėžlys",
        distractors: ["Lapė", "Šuo", "Triušis", "Elnias", "Arklys"],
        explanation: "Atkaklus vėžlys nugali per daug pasitikintį kiškį.",
      },
    },
  },
  {
    id: "pop_me_024",
    category: "pop",
    subTheme: "books",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Treasure Island by Stevenson",
    emoji: "🗺️",
    translations: {
      en: {
        question: "Who wrote the adventure novel Treasure Island?",
        correct: "Robert Louis Stevenson",
        distractors: ["Jules Verne", "Mark Twain", "Daniel Defoe", "Jack London", "H. G. Wells"],
        explanation: "Treasure Island was written by Robert Louis Stevenson.",
      },
      lt: {
        question: "Kas parašė nuotykių romaną „Lobių sala”?",
        correct: "Robertas Luisas Styvensonas",
        distractors: ["Žiulis Vernas", "Markas Tvenas", "Danielis Defo", "Džekas Londonas", "H. G. Velsas"],
        explanation: "„Lobių salą” parašė Robertas Luisas Styvensonas.",
      },
    },
  },
  {
    id: "pop_me_025",
    category: "pop",
    subTheme: "myth",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Medusa had snakes for hair",
    emoji: "🐍",
    translations: {
      en: {
        question: "In Greek myth, what was Medusa's hair made of?",
        correct: "Snakes",
        distractors: ["Fire", "Gold", "Water", "Leaves", "Feathers"],
        explanation: "Medusa had living snakes instead of hair.",
      },
      lt: {
        question: "Graikų mite iš ko buvo Medūzos plaukai?",
        correct: "Gyvatės",
        distractors: ["Ugnis", "Auksas", "Vanduo", "Lapai", "Plunksnos"],
        explanation: "Vietoj plaukų Medūza turėjo gyvas gyvates.",
      },
    },
  },
  {
    id: "pop_me_026",
    category: "pop",
    subTheme: "music",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Vivaldi wrote The Four Seasons",
    emoji: "🎼",
    translations: {
      en: {
        question: "Which composer wrote The Four Seasons?",
        correct: "Vivaldi",
        distractors: ["Bach", "Mozart", "Beethoven", "Chopin", "Handel"],
        explanation: "The Four Seasons was composed by Antonio Vivaldi.",
      },
      lt: {
        question: "Kuris kompozitorius sukūrė „Keturis metų laikus”?",
        correct: "Vivaldis",
        distractors: ["Bachas", "Mocartas", "Bethovenas", "Šopenas", "Hendelis"],
        explanation: "„Keturis metų laikus” sukūrė Antonijus Vivaldis.",
      },
    },
  },
  {
    id: "pop_me_027",
    category: "pop",
    subTheme: "books",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Poirot created by Agatha Christie",
    emoji: "🕵️",
    translations: {
      en: {
        question: "Which mustached Belgian detective did Agatha Christie create?",
        correct: "Hercule Poirot",
        distractors: ["Sherlock Holmes", "Miss Marple", "Dr Watson", "Columbo", "Maigret"],
        explanation: "Hercule Poirot is Agatha Christie's Belgian detective.",
      },
      lt: {
        question: "Kurį ūsuotą belgų detektyvą sukūrė Agata Kristi?",
        correct: "Erkiulis Puaro",
        distractors: ["Šerlokas Holmsas", "Panelė Marpl", "Daktaras Vatsonas", "Kolombas", "Megrė"],
        explanation: "Erkiulis Puaro — Agatos Kristi belgų detektyvas.",
      },
    },
  },
  {
    id: "pop_me_028",
    category: "pop",
    subTheme: "music",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "The Nutcracker ballet",
    emoji: "🩰",
    translations: {
      en: {
        question: "Which ballet features a girl named Clara and a Nutcracker?",
        correct: "The Nutcracker",
        distractors: ["Swan Lake", "Sleeping Beauty", "Giselle", "Coppelia", "Cinderella"],
        explanation: "The Nutcracker is a famous Christmas ballet.",
      },
      lt: {
        question: "Kuriame balete pasakojama apie mergaitę Klarą ir Spragtuką?",
        correct: "Spragtukas",
        distractors: ["Gulbių ežeras", "Miegančioji gražuolė", "Žizel", "Kopelija", "Pelenė"],
        explanation: "„Spragtukas” — garsus kalėdinis baletas.",
      },
    },
  },
  {
    id: "pop_me_029",
    category: "pop",
    subTheme: "books",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "A Christmas Carol by Dickens",
    emoji: "🎄",
    translations: {
      en: {
        question: "Who wrote A Christmas Carol, featuring Scrooge?",
        correct: "Charles Dickens",
        distractors: ["Shakespeare", "Tolkien", "Jane Austen", "Mark Twain", "Lewis Carroll"],
        explanation: "A Christmas Carol was written by Charles Dickens.",
      },
      lt: {
        question: "Kas parašė „Kalėdų giesmę” su personažu Skrudžu?",
        correct: "Čarlzas Dikensas",
        distractors: ["Šekspyras", "Tolkienas", "Džeinė Ostin", "Markas Tvenas", "Luisas Kerolis"],
        explanation: "„Kalėdų giesmę” parašė Čarlzas Dikensas.",
      },
    },
  },
  {
    id: "pop_me_030",
    category: "pop",
    subTheme: "movies",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Aladdin's lamp holds a genie",
    emoji: "🪔",
    translations: {
      en: {
        question: "In Aladdin, which object holds a wish-granting genie?",
        correct: "A lamp",
        distractors: ["A ring", "A mirror", "A carpet", "A sword", "A book"],
        explanation: "Aladdin rubs a magic lamp to free the genie.",
      },
      lt: {
        question: "Kuriame daikte „Aladine” gyvena norus pildantis džinas?",
        correct: "Lempoje",
        distractors: ["Žiede", "Veidrodyje", "Kilime", "Karde", "Knygoje"],
        explanation: "Aladinas patrina stebuklingą lempą ir išlaisvina džiną.",
      },
    },
  },
  {
    id: "pop_su_016",
    category: "pop",
    subTheme: "music",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Mozart composed The Magic Flute",
    emoji: "🎼",
    translations: {
      en: {
        question: "Who composed the opera The Magic Flute?",
        correct: "Mozart",
        distractors: ["Verdi", "Wagner", "Puccini", "Rossini", "Bizet"],
        explanation: "The Magic Flute was composed by Mozart.",
      },
      lt: {
        question: "Kas sukūrė operą „Užburtoji fleita”?",
        correct: "Mocartas",
        distractors: ["Verdis", "Vagneris", "Pučinis", "Rosinis", "Bizė"],
        explanation: "„Užburtąją fleitą” sukūrė Mocartas.",
      },
    },
  },
  {
    id: "pop_su_017",
    category: "pop",
    subTheme: "art",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "The Starry Night by Van Gogh",
    emoji: "🌌",
    translations: {
      en: {
        question: "Which artist painted The Starry Night?",
        correct: "Vincent van Gogh",
        distractors: ["Monet", "Picasso", "Klimt", "Munch", "Cezanne"],
        explanation: "The Starry Night was painted by Vincent van Gogh.",
      },
      lt: {
        question: "Kuris dailininkas nutapė „Žvaigždėtą naktį”?",
        correct: "Vinsentas van Gogas",
        distractors: ["Monė", "Pikasas", "Klimtas", "Munkas", "Sezanas"],
        explanation: "„Žvaigždėtą naktį” nutapė Vinsentas van Gogas.",
      },
    },
  },
  {
    id: "pop_su_018",
    category: "pop",
    subTheme: "myth",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Oedipus solved the Sphinx's riddle",
    emoji: "🦁",
    translations: {
      en: {
        question: "In Greek myth, who solved the riddle of the Sphinx?",
        correct: "Oedipus",
        distractors: ["Theseus", "Jason", "Hercules", "Perseus", "Achilles"],
        explanation: "Oedipus answered the Sphinx's famous riddle.",
      },
      lt: {
        question: "Graikų mite kas įminė Sfinkso mįslę?",
        correct: "Edipas",
        distractors: ["Tesėjas", "Jasonas", "Heraklis", "Persėjas", "Achilas"],
        explanation: "Edipas įminė garsiąją Sfinkso mįslę.",
      },
    },
  },
  {
    id: "pop_su_019",
    category: "pop",
    subTheme: "books",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Homer wrote the Iliad and Odyssey",
    emoji: "📜",
    translations: {
      en: {
        question: "Who is credited with the epics the Iliad and the Odyssey?",
        correct: "Homer",
        distractors: ["Virgil", "Sophocles", "Plato", "Ovid", "Aesop"],
        explanation: "The Iliad and Odyssey are attributed to Homer.",
      },
      lt: {
        question: "Kam priskiriamos epinės poemos „Iliada” ir „Odisėja”?",
        correct: "Homeras",
        distractors: ["Vergilijus", "Sofoklis", "Platonas", "Ovidijus", "Ezopas"],
        explanation: "„Iliada” ir „Odisėja” priskiriamos Homerui.",
      },
    },
  },
  {
    id: "pop_su_020",
    category: "pop",
    subTheme: "art",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Dali painted melting clocks",
    emoji: "🕰️",
    translations: {
      en: {
        question: "Which surrealist painted melting clocks in his art?",
        correct: "Salvador Dali",
        distractors: ["Picasso", "Magritte", "Miro", "Kandinsky", "Pollock"],
        explanation: "Salvador Dali painted the famous melting clocks.",
      },
      lt: {
        question: "Kuris siurrealistas savo darbuose tapė tirpstančius laikrodžius?",
        correct: "Salvadoras Dali",
        distractors: ["Pikasas", "Magritas", "Miro", "Kandinskis", "Polokas"],
        explanation: "Tirpstančius laikrodžius nutapė Salvadoras Dali.",
      },
    },
  },
  {
    id: "pop_su_021",
    category: "pop",
    subTheme: "music",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Beethoven's Ninth has Ode to Joy",
    emoji: "🎵",
    translations: {
      en: {
        question: "Whose Ninth Symphony includes the Ode to Joy?",
        correct: "Beethoven",
        distractors: ["Mozart", "Bach", "Brahms", "Schubert", "Haydn"],
        explanation: "Beethoven's Ninth Symphony features the Ode to Joy.",
      },
      lt: {
        question: "Kurio kompozitoriaus Devintojoje simfonijoje skamba „Odė džiaugsmui”?",
        correct: "Bethovenas",
        distractors: ["Mocartas", "Bachas", "Bramsas", "Šubertas", "Haidnas"],
        explanation: "Bethoveno Devintojoje simfonijoje skamba „Odė džiaugsmui”.",
      },
    },
  },
  {
    id: "pop_su_022",
    category: "pop",
    subTheme: "myth",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Jupiter is Roman king of gods",
    emoji: "⚡",
    translations: {
      en: {
        question: "In Roman mythology, who is the king of the gods?",
        correct: "Jupiter",
        distractors: ["Neptune", "Mars", "Apollo", "Mercury", "Saturn"],
        explanation: "Jupiter is the chief god in Roman mythology.",
      },
      lt: {
        question: "Romėnų mitologijoje kas yra dievų karalius?",
        correct: "Jupiteris",
        distractors: ["Neptūnas", "Marsas", "Apolonas", "Merkurijus", "Saturnas"],
        explanation: "Jupiteris — vyriausias romėnų dievas.",
      },
    },
  },
  {
    id: "pop_su_023",
    category: "pop",
    subTheme: "books",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Don Quixote by Cervantes",
    emoji: "📖",
    translations: {
      en: {
        question: "Who wrote the classic novel Don Quixote?",
        correct: "Miguel de Cervantes",
        distractors: ["Dante", "Voltaire", "Victor Hugo", "Dumas", "Goethe"],
        explanation: "Don Quixote was written by Miguel de Cervantes.",
      },
      lt: {
        question: "Kas parašė klasikinį romaną „Don Kichotas”?",
        correct: "Migelis de Servantesas",
        distractors: ["Dantė", "Volteras", "Viktoras Hugo", "Diuma", "Gėtė"],
        explanation: "„Don Kichotą” parašė Migelis de Servantesas.",
      },
    },
  },
  {
    id: "pop_su_024",
    category: "pop",
    subTheme: "art",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Michelangelo painted Sistine Chapel ceiling",
    emoji: "🎨",
    translations: {
      en: {
        question: "Who painted the ceiling of the Sistine Chapel?",
        correct: "Michelangelo",
        distractors: ["Leonardo", "Raphael", "Botticelli", "Caravaggio", "Titian"],
        explanation: "Michelangelo painted the Sistine Chapel ceiling.",
      },
      lt: {
        question: "Kas ištapė Siksto koplyčios lubas?",
        correct: "Mikelandželas",
        distractors: ["Leonardas", "Rafaelis", "Botičelis", "Karavadžas", "Ticianas"],
        explanation: "Siksto koplyčios lubas ištapė Mikelandželas.",
      },
    },
  },
  {
    id: "pop_su_025",
    category: "pop",
    subTheme: "books",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Haiku has 3 lines",
    emoji: "🍃",
    translations: {
      en: {
        question: "How many lines does a traditional Japanese haiku have?",
        correct: "3",
        distractors: ["4", "5", "2", "7", "14"],
        explanation: "A haiku has three lines (5-7-5 syllables).",
      },
      lt: {
        question: "Kiek eilučių turi tradicinė japonų haiku?",
        correct: "3",
        distractors: ["4", "5", "2", "7", "14"],
        explanation: "Haiku turi tris eilutes (5-7-5 skiemenys).",
      },
    },
  },
  {
    id: "pop_su_026",
    category: "pop",
    subTheme: "music",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Swan Lake ballet",
    emoji: "🦢",
    translations: {
      en: {
        question: "Which ballet features a princess turned into a swan?",
        correct: "Swan Lake",
        distractors: ["The Nutcracker", "Giselle", "Coppelia", "Sleeping Beauty", "Cinderella"],
        explanation: "Swan Lake tells of a princess cursed into a swan.",
      },
      lt: {
        question: "Kuriame balete princesė paversta gulbe?",
        correct: "Gulbių ežeras",
        distractors: ["Spragtukas", "Žizel", "Kopelija", "Miegančioji gražuolė", "Pelenė"],
        explanation: "„Gulbių ežeras” pasakoja apie princesę, paverstą gulbe.",
      },
    },
  },
  {
    id: "pop_su_027",
    category: "pop",
    subTheme: "music",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Bridal Chorus by Wagner",
    emoji: "💍",
    translations: {
      en: {
        question: "The Bridal Chorus, Here Comes the Bride, is from an opera by whom?",
        correct: "Wagner",
        distractors: ["Mendelssohn", "Bach", "Mozart", "Handel", "Verdi"],
        explanation: "Here Comes the Bride is Wagner's Bridal Chorus from Lohengrin.",
      },
      lt: {
        question: "„Štai ateina nuotaka” vestuvių choras yra iš kurio kompozitoriaus operos?",
        correct: "Vagneris",
        distractors: ["Mendelsonas", "Bachas", "Mocartas", "Hendelis", "Verdis"],
        explanation: "Šis choras — Vagnerio kūrinys iš operos „Loengrinas”.",
      },
    },
  },
  {
    id: "pop_su_028",
    category: "pop",
    subTheme: "art",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Origami associated with Japan",
    emoji: "📄",
    translations: {
      en: {
        question: "In which country did the art of paper folding, origami, flourish?",
        correct: "Japan",
        distractors: ["China", "Korea", "India", "Thailand", "Vietnam"],
        explanation: "Origami is the Japanese art of paper folding.",
      },
      lt: {
        question: "Kurioje šalyje suklestėjo popieriaus lankstymo menas origamis?",
        correct: "Japonija",
        distractors: ["Kinija", "Korėja", "Indija", "Tailandas", "Vietnamas"],
        explanation: "Origamis — japonų popieriaus lankstymo menas.",
      },
    },
  },
  {
    id: "pop_su_029",
    category: "pop",
    subTheme: "art",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "The Scream by Edvard Munch",
    emoji: "😱",
    translations: {
      en: {
        question: "The famous painting The Scream was created by which artist?",
        correct: "Edvard Munch",
        distractors: ["Van Gogh", "Picasso", "Dali", "Klimt", "Monet"],
        explanation: "The Scream was painted by Edvard Munch.",
      },
      lt: {
        question: "Garsųjį paveikslą „Klyksmas” sukūrė kuris dailininkas?",
        correct: "Edvardas Munkas",
        distractors: ["Van Gogas", "Pikasas", "Dali", "Klimtas", "Monė"],
        explanation: "„Klyksmą” nutapė Edvardas Munkas.",
      },
    },
  },
  {
    id: "pop_su_030",
    category: "pop",
    subTheme: "music",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "1812 Overture by Tchaikovsky",
    emoji: "🎆",
    translations: {
      en: {
        question: "Which Russian composer wrote the 1812 Overture?",
        correct: "Tchaikovsky",
        distractors: ["Stravinsky", "Rachmaninoff", "Prokofiev", "Borodin", "Mussorgsky"],
        explanation: "The 1812 Overture was composed by Tchaikovsky.",
      },
      lt: {
        question: "Kuris rusų kompozitorius sukūrė „1812 metų uvertiūrą”?",
        correct: "Čaikovskis",
        distractors: ["Stravinskis", "Rachmaninovas", "Prokofjevas", "Borodinas", "Musorgskis"],
        explanation: "„1812 metų uvertiūrą” sukūrė Čaikovskis.",
      },
    },
  },
  {
    id: "pop_ek_016",
    category: "pop",
    subTheme: "art",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "The Night Watch by Rembrandt",
    emoji: "🎨",
    translations: {
      en: {
        question: "Which Dutch master painted The Night Watch?",
        correct: "Rembrandt",
        distractors: ["Vermeer", "Van Gogh", "Bosch", "Brueghel", "Mondrian"],
        explanation: "The Night Watch was painted by Rembrandt.",
      },
      lt: {
        question: "Kuris olandų meistras nutapė „Naktinę sargybą”?",
        correct: "Rembrantas",
        distractors: ["Vermejeris", "Van Gogas", "Boschas", "Brėigelis", "Mondrianas"],
        explanation: "„Naktinę sargybą” nutapė Rembrantas.",
      },
    },
  },
  {
    id: "pop_ek_017",
    category: "pop",
    subTheme: "myth",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Heracles completed 12 labors",
    emoji: "🦁",
    translations: {
      en: {
        question: "In Greek myth, how many labors did Heracles complete?",
        correct: "12",
        distractors: ["7", "10", "9", "3", "24"],
        explanation: "Heracles famously completed twelve labors.",
      },
      lt: {
        question: "Graikų mite kiek žygdarbių atliko Heraklis?",
        correct: "12",
        distractors: ["7", "10", "9", "3", "24"],
        explanation: "Heraklis garsėja dvylika žygdarbių.",
      },
    },
  },
  {
    id: "pop_ek_018",
    category: "pop",
    subTheme: "art",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "The Birth of Venus by Botticelli",
    emoji: "🐚",
    translations: {
      en: {
        question: "Which Renaissance artist painted The Birth of Venus?",
        correct: "Botticelli",
        distractors: ["Raphael", "Titian", "Caravaggio", "Giotto", "Donatello"],
        explanation: "The Birth of Venus was painted by Sandro Botticelli.",
      },
      lt: {
        question: "Kuris Renesanso dailininkas nutapė „Veneros gimimą”?",
        correct: "Botičelis",
        distractors: ["Rafaelis", "Ticianas", "Karavadžas", "Džotas", "Donatelas"],
        explanation: "„Veneros gimimą” nutapė Sandras Botičelis.",
      },
    },
  },
  {
    id: "pop_ek_019",
    category: "pop",
    subTheme: "books",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Divine Comedy by Dante",
    emoji: "📖",
    translations: {
      en: {
        question: "Who wrote the epic poem the Divine Comedy?",
        correct: "Dante Alighieri",
        distractors: ["Petrarch", "Boccaccio", "Virgil", "Milton", "Chaucer"],
        explanation: "The Divine Comedy was written by Dante Alighieri.",
      },
      lt: {
        question: "Kas parašė epinę poemą „Dieviškoji komedija”?",
        correct: "Dantė Aligjeris",
        distractors: ["Petrarka", "Bokačas", "Vergilijus", "Miltonas", "Čoseris"],
        explanation: "„Dieviškąją komediją” parašė Dantė Aligjeris.",
      },
    },
  },
  {
    id: "pop_ek_020",
    category: "pop",
    subTheme: "music",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Well-Tempered Clavier by Bach",
    emoji: "🎹",
    translations: {
      en: {
        question: "Who composed The Well-Tempered Clavier?",
        correct: "Johann Sebastian Bach",
        distractors: ["Handel", "Vivaldi", "Telemann", "Scarlatti", "Corelli"],
        explanation: "The Well-Tempered Clavier was composed by J. S. Bach.",
      },
      lt: {
        question: "Kas sukūrė „Gerai temperuotą klavyrą”?",
        correct: "Johanas Sebastijonas Bachas",
        distractors: ["Hendelis", "Vivaldis", "Telemanas", "Skarlatis", "Korelis"],
        explanation: "„Gerai temperuotą klavyrą” sukūrė J. S. Bachas.",
      },
    },
  },
  {
    id: "pop_ek_021",
    category: "pop",
    subTheme: "myth",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Bifrost is the Norse rainbow bridge",
    emoji: "🌈",
    translations: {
      en: {
        question: "In Norse myth, what is the rainbow bridge to Asgard called?",
        correct: "Bifrost",
        distractors: ["Valhalla", "Yggdrasil", "Midgard", "Ragnarok", "Mjolnir"],
        explanation: "Bifrost is the rainbow bridge in Norse mythology.",
      },
      lt: {
        question: "Skandinavų mite kaip vadinamas vaivorykštės tiltas į Asgardą?",
        correct: "Bifrostas",
        distractors: ["Valhala", "Igdrasilis", "Midgardas", "Ragnarokas", "Mjölniras"],
        explanation: "Bifrostas — vaivorykštės tiltas skandinavų mitologijoje.",
      },
    },
  },
  {
    id: "pop_ek_022",
    category: "pop",
    subTheme: "art",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Picasso pioneered Cubism",
    emoji: "🎨",
    translations: {
      en: {
        question: "Which painter pioneered Cubism with Georges Braque?",
        correct: "Pablo Picasso",
        distractors: ["Matisse", "Dali", "Kandinsky", "Cezanne", "Duchamp"],
        explanation: "Picasso and Braque pioneered the Cubist movement.",
      },
      lt: {
        question: "Kuris dailininkas kartu su Žoržu Braku pradėjo kubizmą?",
        correct: "Pablas Pikasas",
        distractors: ["Matisas", "Dali", "Kandinskis", "Sezanas", "Diušanas"],
        explanation: "Pikasas ir Brakas pradėjo kubizmo judėjimą.",
      },
    },
  },
  {
    id: "pop_ek_023",
    category: "pop",
    subTheme: "books",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Faust by Goethe",
    emoji: "📖",
    translations: {
      en: {
        question: "Who wrote the classic tragedy Faust?",
        correct: "Goethe",
        distractors: ["Schiller", "Kafka", "Thomas Mann", "Hesse", "Nietzsche"],
        explanation: "Faust was written by Johann Wolfgang von Goethe.",
      },
      lt: {
        question: "Kas parašė klasikinę tragediją „Faustas”?",
        correct: "Gėtė",
        distractors: ["Šileris", "Kafka", "Tomas Manas", "Hesė", "Nyčė"],
        explanation: "„Faustą” parašė Johanas Volfgangas fon Gėtė.",
      },
    },
  },
  {
    id: "pop_ek_024",
    category: "pop",
    subTheme: "music",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Haydn called Father of the Symphony",
    emoji: "🎻",
    translations: {
      en: {
        question: "Which composer is called the Father of the Symphony?",
        correct: "Joseph Haydn",
        distractors: ["Mozart", "Schubert", "Bruckner", "Mahler", "Strauss"],
        explanation: "Joseph Haydn shaped the classical symphony form.",
      },
      lt: {
        question: "Kuris kompozitorius vadinamas simfonijos tėvu?",
        correct: "Jozefas Haidnas",
        distractors: ["Mocartas", "Šubertas", "Brukneris", "Maleris", "Štrausas"],
        explanation: "Jozefas Haidnas išplėtojo klasikinės simfonijos formą.",
      },
    },
  },
  {
    id: "pop_ek_025",
    category: "pop",
    subTheme: "music",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "String quartet has 4 players",
    emoji: "🎻",
    translations: {
      en: {
        question: "How many musicians play in a string quartet?",
        correct: "4",
        distractors: ["3", "5", "2", "6", "8"],
        explanation: "A string quartet has four musicians.",
      },
      lt: {
        question: "Kiek muzikantų groja styginių kvartete?",
        correct: "4",
        distractors: ["3", "5", "2", "6", "8"],
        explanation: "Styginių kvartete groja keturi muzikantai.",
      },
    },
  },
  {
    id: "pop_ek_026",
    category: "pop",
    subTheme: "books",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Aesop wrote moral animal fables",
    emoji: "🐢",
    translations: {
      en: {
        question: "Which ancient Greek is famed for moral animal fables?",
        correct: "Aesop",
        distractors: ["Homer", "Plato", "Sophocles", "Herodotus", "Euripides"],
        explanation: "Aesop is credited with many moral fables.",
      },
      lt: {
        question: "Kuris senovės graikas garsus moralinėmis pasakėčiomis apie gyvūnus?",
        correct: "Ezopas",
        distractors: ["Homeras", "Platonas", "Sofoklis", "Herodotas", "Euripidas"],
        explanation: "Ezopui priskiriama daug moralinių pasakėčių.",
      },
    },
  },
  {
    id: "pop_ek_027",
    category: "pop",
    subTheme: "books",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "A Doll's House by Ibsen",
    emoji: "🎭",
    translations: {
      en: {
        question: "Which Norwegian playwright wrote A Doll's House?",
        correct: "Henrik Ibsen",
        distractors: ["Strindberg", "Chekhov", "Bernard Shaw", "Oscar Wilde", "Brecht"],
        explanation: "A Doll's House was written by Henrik Ibsen.",
      },
      lt: {
        question: "Kuris norvegų dramaturgas parašė „Noros namus” (Lėlių namus)?",
        correct: "Henrikas Ibsenas",
        distractors: ["Strindbergas", "Čechovas", "Bernardas Šo", "Oskaras Vaildas", "Brechtas"],
        explanation: "„Lėlių namus” parašė Henrikas Ibsenas.",
      },
    },
  },
  {
    id: "pop_ek_028",
    category: "pop",
    subTheme: "books",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "War and Peace by Tolstoy",
    emoji: "📚",
    translations: {
      en: {
        question: "Which Russian author wrote the novel War and Peace?",
        correct: "Leo Tolstoy",
        distractors: ["Dostoevsky", "Chekhov", "Pushkin", "Turgenev", "Gogol"],
        explanation: "War and Peace was written by Leo Tolstoy.",
      },
      lt: {
        question: "Kuris rusų rašytojas parašė romaną „Karas ir taika”?",
        correct: "Levas Tolstojus",
        distractors: ["Dostojevskis", "Čechovas", "Puškinas", "Turgenevas", "Gogolis"],
        explanation: "„Karą ir taiką” parašė Levas Tolstojus.",
      },
    },
  },
  {
    id: "pop_ek_029",
    category: "pop",
    subTheme: "music",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Pianissimo means very soft",
    emoji: "🎵",
    translations: {
      en: {
        question: "In music, what does the term pianissimo mean?",
        correct: "Very soft",
        distractors: ["Very fast", "Very slow", "Very loud", "Medium", "Sharp"],
        explanation: "Pianissimo means to play very softly.",
      },
      lt: {
        question: "Muzikoje ką reiškia terminas pianissimo?",
        correct: "Labai tyliai",
        distractors: ["Labai greitai", "Labai lėtai", "Labai garsiai", "Vidutiniškai", "Aštriai"],
        explanation: "Pianissimo reiškia groti labai tyliai.",
      },
    },
  },
  {
    id: "pop_ek_030",
    category: "pop",
    subTheme: "art",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Monet painted Water Lilies, founded Impressionism",
    emoji: "🎨",
    translations: {
      en: {
        question: "Which painter founded Impressionism and painted Water Lilies?",
        correct: "Claude Monet",
        distractors: ["Renoir", "Degas", "Manet", "Pissarro", "Sisley"],
        explanation: "Claude Monet was a founder of Impressionism.",
      },
      lt: {
        question: "Kuris dailininkas pradėjo impresionizmą ir nutapė „Vandens lelijas”?",
        correct: "Klodas Monė",
        distractors: ["Renuaras", "Degas", "Manė", "Pisaro", "Sislė"],
        explanation: "Klodas Monė buvo vienas impresionizmo pradininkų.",
      },
    },
  },
];
