/**
 * recordsObjects — 💎 „Daiktų ir maisto rekordai" potemė (tema „Rekordai ir keistenybės").
 *
 * MAŽAS FAILAS pagal potemę. 40 klausimų (10/lygiui). Brangiausi/didžiausi daiktai +
 * ĮDOMŪS faktai, KAIP rekordai buvo pasiekti (savininko idėja). Faktai per tyrimo
 * Workflow su patikimais šaltiniais (Guinness, Christie's/Sotheby's, muziejai).
 * AKTUALUMAS: rinktasi STABILŪS istoriniai rekordai (savininkas: rekordai negali būti pasenę).
 *
 * TAISYKLĖS: 1 teisingas + 5 distraktoriai; ≤46 simb.; teisingas NE ilgiausias >+5;
 * LT be vidinių kabučių; jokio atsakymo klausime; EMOJI NEUTRALUS (neišduoda atsakymo).
 */

import { TriviaQuestion } from "./triviaTypes";

export const RECORDS_OBJECTS: TriviaQuestion[] = [
  // ===================== LENGVAS (9–12 m. vaikas) =====================
  {
    id: "rec_ob_001",
    category: "records",
    subTheme: "objects",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Christie's 2017 — Salvator Mundi, most expensive painting sold",
    emoji: "🖼️",
    translations: {
      en: {
        question: "Which Leonardo painting is the most expensive ever sold at auction?",
        correct: "Salvator Mundi",
        distractors: ["The Last Supper", "Vitruvian Man", "The Starry Night", "The Scream", "Sunflowers"],
        explanation: "Bought for about 1,000 dollars in 2005, it later sold for 450 million.",
      },
      lt: {
        question: "Kuris Leonardo paveikslas yra brangiausias kada nors parduotas aukcione?",
        correct: "Salvator Mundi",
        distractors: ["Paskutinė vakarienė", "Vitruvijaus žmogus", "Žvaigždėtoji naktis", "Klyksmas", "Saulėgrąžos"],
        explanation: "2005 m. nupirktas už maždaug 1 000 dolerių, vėliau parduotas už 450 milijonų.",
      },
    },
  },
  {
    id: "rec_ob_002",
    category: "records",
    subTheme: "objects",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Guinness — Mona Lisa, highest insurance valuation for a painting",
    emoji: "🎨",
    translations: {
      en: {
        question: "Which painting holds the record for the highest insurance value ever?",
        correct: "The Mona Lisa",
        distractors: ["The Scream", "Guernica", "The Starry Night", "Sunflowers", "Water Lilies"],
        explanation: "Valued at 100 million in 1962, but no policy was bought — guards cost less.",
      },
      lt: {
        question: "Kuris paveikslas turi didžiausią draudimo vertę istorijoje?",
        correct: "Mona Liza",
        distractors: ["Klyksmas", "Gernika", "Žvaigždėtoji naktis", "Saulėgrąžos", "Vandens lelijos"],
        explanation: "1962 m. įvertintas 100 mln., bet draudimas nepirktas — apsauga kainavo mažiau.",
      },
    },
  },
  {
    id: "rec_ob_003",
    category: "records",
    subTheme: "objects",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Guinness/Britannica — Cullinan, largest rough diamond ever found",
    emoji: "💎",
    translations: {
      en: {
        question: "What is the largest gem-quality rough diamond ever found?",
        correct: "The Cullinan",
        distractors: ["The Hope", "The Koh-i-Noor", "The Orlov", "The Regent", "The Sancy"],
        explanation: "It was so big the mine manager first thought it was a worthless piece of glass.",
      },
      lt: {
        question: "Koks didžiausias kada nors rastas brangakmenio kokybės deimantas?",
        correct: "Kalinano deimantas",
        distractors: ["Hope deimantas", "Koh-i-Noor", "Orlovo deimantas", "Regento deimantas", "Sansi deimantas"],
        explanation: "Jis buvo toks didelis, kad kasyklos vadovas iš pradžių palaikė jį stiklu.",
      },
    },
  },
  {
    id: "rec_ob_004",
    category: "records",
    subTheme: "objects",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "RM Sotheby's 2022 — Mercedes 300 SLR, most expensive car sold",
    emoji: "🚗",
    translations: {
      en: {
        question: "Which brand built the most expensive car ever sold at auction?",
        correct: "Mercedes-Benz",
        distractors: ["Ferrari", "Bugatti", "Rolls-Royce", "Lamborghini", "Porsche"],
        explanation: "A 1955 300 SLR sold for 135 million euros — only two were ever built.",
      },
      lt: {
        question: "Kurios markės yra brangiausias kada nors aukcione parduotas automobilis?",
        correct: "Mercedes-Benz",
        distractors: ["Ferrari", "Bugatti", "Rolls-Royce", "Lamborghini", "Porsche"],
        explanation: "1955 m. 300 SLR parduotas už 135 mln. eurų — pagaminti tik du.",
      },
    },
  },
  {
    id: "rec_ob_005",
    category: "records",
    subTheme: "objects",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Guinness — largest LEGO sculpture, Tower Bridge replica",
    emoji: "🧱",
    translations: {
      en: {
        question: "The largest LEGO brick sculpture is a replica of which landmark?",
        correct: "Tower Bridge",
        distractors: ["The Eiffel Tower", "Big Ben", "The Colosseum", "The Taj Mahal", "Brandenburg Gate"],
        explanation: "Built from over 5.8 million bricks by a team of more than 100 people.",
      },
      lt: {
        question: "Didžiausia LEGO kaladėlių skulptūra yra kurio objekto kopija?",
        correct: "Tauerio tiltas",
        distractors: ["Eifelio bokštas", "Big Benas", "Koliziejus", "Tadž Mahalas", "Brandenburgo vartai"],
        explanation: "Pastatyta iš daugiau nei 5,8 mln. kaladėlių, dirbo per 100 žmonių.",
      },
    },
  },
  {
    id: "rec_ob_006",
    category: "records",
    subTheme: "objects",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Guinness 2023 — largest pizza, Los Angeles, USA",
    emoji: "🍕",
    translations: {
      en: {
        question: "The largest pizza ever made was baked in which country?",
        correct: "The USA",
        distractors: ["Italy", "Brazil", "India", "Spain", "Mexico"],
        explanation: "It used about 630,000 pepperoni slices and was given to food charities.",
      },
      lt: {
        question: "Kurioje šalyje iškepta didžiausia kada nors pica?",
        correct: "JAV",
        distractors: ["Italijoje", "Brazilijoje", "Indijoje", "Ispanijoje", "Meksikoje"],
        explanation: "Panaudota apie 630 000 pepperoni griežinėlių, atiduota labdarai.",
      },
    },
  },
  {
    id: "rec_ob_007",
    category: "records",
    subTheme: "objects",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Guinness 2021 — tallest sandcastle, Blokhus, Denmark",
    emoji: "🏖️",
    translations: {
      en: {
        question: "The tallest sandcastle ever was sand mixed with what to hold its shape?",
        correct: "Clay",
        distractors: ["Cement", "Glue", "Salt", "Sugar", "Ice"],
        explanation: "About a tenth was clay; the 21 m tower was built to last six months.",
      },
      lt: {
        question: "Su kuo buvo sumaišytas smėlis, kad aukščiausia smėlio pilis išliktų?",
        correct: "Su moliu",
        distractors: ["Su cementu", "Su klijais", "Su druska", "Su cukrumi", "Su ledu"],
        explanation: "Apie dešimtadalį sudarė molis; 21 m bokštas pastatytas pusmečiui.",
      },
    },
  },
  {
    id: "rec_ob_008",
    category: "records",
    subTheme: "objects",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Museums Victoria — Welcome Stranger, largest gold nugget",
    emoji: "⛏️",
    translations: {
      en: {
        question: "The largest gold nugget ever found was dug up in which country?",
        correct: "Australia",
        distractors: ["The USA", "South Africa", "Canada", "Russia", "Brazil"],
        explanation: "It was too big for the bank's scales, so it was broken up on an anvil.",
      },
      lt: {
        question: "Kurioje šalyje iškastas didžiausias kada nors rastas aukso grynuolis?",
        correct: "Australijoje",
        distractors: ["JAV", "Pietų Afrikoje", "Kanadoje", "Rusijoje", "Brazilijoje"],
        explanation: "Jis netilpo ant banko svarstyklių, tad buvo sukapotas ant priekalo.",
      },
    },
  },
  {
    id: "rec_ob_009",
    category: "records",
    subTheme: "objects",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Tarisio 2011 — Lady Blunt Stradivarius, most expensive instrument at auction",
    emoji: "🎶",
    translations: {
      en: {
        question: "The most expensive musical instrument ever sold at auction is a 1721 what?",
        correct: "Stradivarius violin",
        distractors: ["Steinway piano", "Fender guitar", "Gold saxophone", "Grand harp", "Antique cello"],
        explanation: "All the money from the sale went to help Japan after the 2011 tsunami.",
      },
      lt: {
        question: "Brangiausias kada nors aukcione parduotas muzikos instrumentas yra 1721 m. koks?",
        correct: "Stradivarijaus smuikas",
        distractors: ["Steinway pianinas", "Fender gitara", "Auksinis saksofonas", "Didžioji arfa", "Senovinė violončelė"],
        explanation: "Visi pinigai iš pardavimo skirti Japonijai padėti po 2011 m. cunamio.",
      },
    },
  },
  {
    id: "rec_ob_010",
    category: "records",
    subTheme: "objects",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Guinness 1995 — largest cheese (cow's milk), Canada",
    emoji: "🧀",
    translations: {
      en: {
        question: "The largest cheese ever made came from which animal's milk?",
        correct: "A cow",
        distractors: ["A goat", "A sheep", "A buffalo", "A camel", "A yak"],
        explanation: "The single giant cheddar weighed about 26 tonnes, made in Canada in 1995.",
      },
      lt: {
        question: "Didžiausias kada nors pagamintas sūris buvo iš kurio gyvūno pieno?",
        correct: "Karvės",
        distractors: ["Ožkos", "Avies", "Buivolo", "Kupranugario", "Jako"],
        explanation: "Vienas milžiniškas čederis svėrė apie 26 tonas, pagamintas Kanadoje 1995 m.",
      },
    },
  },

  // ===================== VIDUTINIS (12–18 m.) =====================
  {
    id: "rec_ob_011",
    category: "records",
    subTheme: "objects",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "RM Sotheby's 2022 — 1955 Mercedes 300 SLR Uhlenhaut",
    emoji: "🚙",
    translations: {
      en: {
        question: "Which classic model is the most expensive car ever sold at auction?",
        correct: "Mercedes 300 SLR",
        distractors: ["Ferrari 250 GTO", "Bugatti Royale", "Jaguar E-Type", "Aston Martin DB5", "Porsche 917"],
        explanation: "Only two were built; it was an engineer's personal company car, never raced.",
      },
      lt: {
        question: "Kuris klasikinis modelis yra brangiausias kada nors parduotas automobilis?",
        correct: "Mercedes 300 SLR",
        distractors: ["Ferrari 250 GTO", "Bugatti Royale", "Jaguar E-Type", "Aston Martin DB5", "Porsche 917"],
        explanation: "Pagaminti tik du; tai buvo inžinieriaus tarnybinis automobilis, niekada nelenktyniavęs.",
      },
    },
  },
  {
    id: "rec_ob_012",
    category: "records",
    subTheme: "objects",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "RM Sotheby's 2023 — 1962 Ferrari 250 GTO record",
    emoji: "🏎️",
    translations: {
      en: {
        question: "Which Ferrari model is the most expensive Ferrari ever sold?",
        correct: "250 GTO",
        distractors: ["Testarossa", "F40", "LaFerrari", "Enzo", "488 GTB"],
        explanation: "Only 36 were ever built, and remarkably all of them still survive today.",
      },
      lt: {
        question: "Kuris Ferrari modelis yra brangiausias kada nors parduotas Ferrari?",
        correct: "250 GTO",
        distractors: ["Testarossa", "F40", "LaFerrari", "Enzo", "488 GTB"],
        explanation: "Pagaminti tik 36, ir nuostabu, kad visi iki šiol išlikę.",
      },
    },
  },
  {
    id: "rec_ob_013",
    category: "records",
    subTheme: "objects",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Christie's 2019 — Patek Philippe Grandmaster Chime",
    emoji: "⌚",
    translations: {
      en: {
        question: "Which brand made the most expensive wristwatch ever sold?",
        correct: "Patek Philippe",
        distractors: ["Rolex", "Omega", "Cartier", "Audemars Piguet", "Breguet"],
        explanation: "The one-of-a-kind steel Grandmaster Chime was sold for charity.",
      },
      lt: {
        question: "Kuri markė pagamino brangiausią kada nors parduotą rankinį laikrodį?",
        correct: "Patek Philippe",
        distractors: ["Rolex", "Omega", "Cartier", "Audemars Piguet", "Breguet"],
        explanation: "Vienintelis plieninis Grandmaster Chime parduotas labdarai.",
      },
    },
  },
  {
    id: "rec_ob_014",
    category: "records",
    subTheme: "objects",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Sotheby's 2021 — 1933 Saint-Gaudens Double Eagle",
    emoji: "🪙",
    translations: {
      en: {
        question: "The most expensive coin ever sold is a 1933 American what?",
        correct: "Double Eagle",
        distractors: ["Silver Dollar", "Gold Buffalo", "Liberty Head", "Eagle Cent", "Half Dollar"],
        explanation: "Almost all were melted down; this is the only one legal to privately own.",
      },
      lt: {
        question: "Brangiausia kada nors parduota moneta yra 1933 m. amerikietiška kokia?",
        correct: "Double Eagle",
        distractors: ["Sidabro doleris", "Gold Buffalo", "Liberty Head", "Eagle Cent", "Half Dollar"],
        explanation: "Beveik visos buvo perlydytos; ši vienintelė teisėta turėti privačiai.",
      },
    },
  },
  {
    id: "rec_ob_015",
    category: "records",
    subTheme: "objects",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Julien's 2020 — Kurt Cobain's MTV Unplugged Martin D-18E ($6.01M)",
    emoji: "🎸",
    translations: {
      en: {
        question: "Whose 1993 MTV Unplugged guitar sold for over 6 million dollars?",
        correct: "Kurt Cobain",
        distractors: ["Jimi Hendrix", "John Lennon", "Elvis Presley", "David Bowie", "Eric Clapton"],
        explanation: "The Martin D-18E from Nirvana's Unplugged set sold at auction in 2020.",
      },
      lt: {
        question: "Kieno 1993 m. MTV Unplugged gitara parduota už daugiau nei 6 milijonus dolerių?",
        correct: "Kurt Cobain",
        distractors: ["Jimi Hendrix", "John Lennon", "Elvis Presley", "David Bowie", "Eric Clapton"],
        explanation: "Nirvanos Unplugged koncerto Martin D-18E gitara parduota aukcione 2020 m.",
      },
    },
  },
  {
    id: "rec_ob_016",
    category: "records",
    subTheme: "objects",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Sotheby's 2023 — Michael Jordan 1998 Finals Air Jordan 13",
    emoji: "👟",
    translations: {
      en: {
        question: "The most expensive sneakers ever sold were worn by whom?",
        correct: "Michael Jordan",
        distractors: ["Kobe Bryant", "LeBron James", "Usain Bolt", "Pelé", "Muhammad Ali"],
        explanation: "He wore and signed them in Game 2 of the 1998 NBA Finals.",
      },
      lt: {
        question: "Kas avėjo brangiausius kada nors parduotus sportbačius?",
        correct: "Michael Jordan",
        distractors: ["Kobe Bryant", "LeBron James", "Usain Bolt", "Pelé", "Muhammad Ali"],
        explanation: "Juos jis avėjo ir pasirašė per 1998 m. NBA finalo antrąsias rungtynes.",
      },
    },
  },
  {
    id: "rec_ob_017",
    category: "records",
    subTheme: "objects",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Guinness 2011 — longest sandwich, Beirut, Lebanon",
    emoji: "🥪",
    translations: {
      en: {
        question: "The longest sandwich ever made was created in which country?",
        correct: "Lebanon",
        distractors: ["The USA", "Italy", "Mexico", "Turkey", "Greece"],
        explanation: "Special movable ovens baked one single 735-metre loaf.",
      },
      lt: {
        question: "Kurioje šalyje pagamintas ilgiausias kada nors sumuštinis?",
        correct: "Libane",
        distractors: ["JAV", "Italijoje", "Meksikoje", "Turkijoje", "Graikijoje"],
        explanation: "Specialios judančios krosnys iškepė vieną ištisą 735 metrų kepalą.",
      },
    },
  },
  {
    id: "rec_ob_018",
    category: "records",
    subTheme: "objects",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Perth Mint — world's largest gold coin (one tonne)",
    emoji: "💰",
    translations: {
      en: {
        question: "The world's largest gold coin, weighing a tonne, was made by which country?",
        correct: "Australia",
        distractors: ["Canada", "The USA", "China", "Switzerland", "South Africa"],
        explanation: "The Perth Mint took the title from Canada's smaller 100 kg coin.",
      },
      lt: {
        question: "Didžiausią pasaulio aukso monetą, sveriančią toną, pagamino kuri šalis?",
        correct: "Australija",
        distractors: ["Kanada", "JAV", "Kinija", "Šveicarija", "Pietų Afrika"],
        explanation: "Perto monetų kalykla atėmė titulą iš mažesnės Kanados 100 kg monetos.",
      },
    },
  },
  {
    id: "rec_ob_019",
    category: "records",
    subTheme: "objects",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Sotheby's 2025 — Jane Birkin's original Hermès Birkin",
    emoji: "👜",
    translations: {
      en: {
        question: "The most expensive handbag ever sold was the original what?",
        correct: "Hermès Birkin",
        distractors: ["Chanel Flap", "Louis Vuitton trunk", "Gucci tote", "Prada clutch", "Dior Saddle"],
        explanation: "It was the very first Birkin, made after Jane Birkin met the boss on a flight.",
      },
      lt: {
        question: "Koks buvo brangiausios kada nors parduotos rankinės modelis?",
        correct: "Hermès Birkin",
        distractors: ["Chanel Flap", "Louis Vuitton kufaras", "Gucci krepšys", "Prada vokas", "Dior Saddle"],
        explanation: "Tai pirmoji Birkin, pagaminta po to, kai Jane Birkin lėktuve sutiko vadovą.",
      },
    },
  },
  {
    id: "rec_ob_020",
    category: "records",
    subTheme: "objects",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Guinness — Giga Pearl, largest natural pearl",
    emoji: "🐚",
    translations: {
      en: {
        question: "The world's largest natural pearl was grown inside what?",
        correct: "A giant clam",
        distractors: ["An oyster", "A mussel", "A sea snail", "A scallop", "A sea urchin"],
        explanation: "Unlike oyster pearls, this 27 kg pearl has a porcelain-like surface.",
      },
      lt: {
        question: "Kieno viduje užaugo didžiausias pasaulio natūralus perlas?",
        correct: "Milžiniškos kriauklės",
        distractors: ["Austrės", "Midijos", "Didelės jūros sraigės", "Šukutės", "Jūros ežio"],
        explanation: "Skirtingai nei austrės perlai, šis 27 kg perlas turi porceliano paviršių.",
      },
    },
  },

  // ===================== SUNKUS (suaugę) =====================
  {
    id: "rec_ob_021",
    category: "records",
    subTheme: "objects",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Christie's 2017 — Salvator Mundi sold for $450.3M",
    emoji: "🖼️",
    translations: {
      en: {
        question: "About how much did the record painting Salvator Mundi sell for?",
        correct: "About 450 million",
        distractors: ["About 45 million", "About 90 million", "About 200 million", "About 1 billion", "About 20 million"],
        explanation: "Two dealers had bought it for only about 1,000 dollars in 2005.",
      },
      lt: {
        question: "Maždaug už kiek parduotas rekordinis paveikslas Salvator Mundi?",
        correct: "Apie 450 milijonų",
        distractors: ["Apie 45 milijonus", "Apie 90 milijonų", "Apie 200 milijonų", "Apie 1 milijardą", "Apie 20 milijonų"],
        explanation: "Du meno prekiautojai jį buvo nupirkę tik už maždaug 1 000 dolerių 2005 m.",
      },
    },
  },
  {
    id: "rec_ob_022",
    category: "records",
    subTheme: "objects",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Cape Town Diamond Museum — Cullinan first thought to be glass",
    emoji: "💠",
    translations: {
      en: {
        question: "When found, the giant Cullinan diamond was first thought to be what?",
        correct: "A piece of glass",
        distractors: ["A lump of coal", "A quartz crystal", "A bottle shard", "An ice cube", "A river pebble"],
        explanation: "It lay just below the surface at the Premier Mine in South Africa.",
      },
      lt: {
        question: "Rastas milžiniškas Kalinano deimantas iš pradžių palaikytas kuo?",
        correct: "Stiklo gabalu",
        distractors: ["Anglies gabalu", "Kvarco kristalu", "Butelio šuke", "Ledo gabalėliu", "Upės akmenuku"],
        explanation: "Jis gulėjo vos po žemės paviršiumi Premier kasykloje Pietų Afrikoje.",
      },
    },
  },
  {
    id: "rec_ob_023",
    category: "records",
    subTheme: "objects",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Smithsonian — Hope Diamond blue color from boron",
    emoji: "🔷",
    translations: {
      en: {
        question: "The Hope Diamond's rare blue color comes from traces of which element?",
        correct: "Boron",
        distractors: ["Iron", "Copper", "Nitrogen", "Sulphur", "Cobalt"],
        explanation: "A jeweller once mailed it to a museum in brown paper for 2.44 dollars.",
      },
      lt: {
        question: "Hope deimanto reta mėlyna spalva atsiranda dėl kurio elemento priemaišų?",
        correct: "Boro",
        distractors: ["Geležies", "Vario", "Azoto", "Sieros", "Kobalto"],
        explanation: "Juvelyras kadaise jį išsiuntė muziejui rudame popieriuje už 2,44 dolerio.",
      },
    },
  },
  {
    id: "rec_ob_024",
    category: "records",
    subTheme: "objects",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Guinness 2023 — largest pizza area 1,296 m²",
    emoji: "🍕",
    translations: {
      en: {
        question: "About how large in area was the largest pizza ever made?",
        correct: "About 1,300 m²",
        distractors: ["About 100 m²", "About 10 m²", "About 50 m²", "About 500 m²", "About 5,000 m²"],
        explanation: "It used thousands of kilos of dough and cheese and was donated to charity.",
      },
      lt: {
        question: "Maždaug kokio ploto buvo didžiausia kada nors pagaminta pica?",
        correct: "Apie 1 300 m²",
        distractors: ["Apie 100 m²", "Apie 10 m²", "Apie 50 m²", "Apie 500 m²", "Apie 5 000 m²"],
        explanation: "Panaudota tūkstančiai kilogramų tešlos ir sūrio, atiduota labdarai.",
      },
    },
  },
  {
    id: "rec_ob_025",
    category: "records",
    subTheme: "objects",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "RM Sotheby's 2022 — Mercedes 300 SLR €135M",
    emoji: "🚗",
    translations: {
      en: {
        question: "About how much did the record Mercedes 300 SLR sell for?",
        correct: "About 135 million euros",
        distractors: ["About 15 million euros", "About 50 million euros", "About 500 million euros", "About 5 million euros", "About 1 billion euros"],
        explanation: "The money went to fund a worldwide Mercedes-Benz scholarship programme.",
      },
      lt: {
        question: "Maždaug už kiek parduotas rekordinis Mercedes 300 SLR?",
        correct: "Apie 135 mln. eurų",
        distractors: ["Apie 15 mln. eurų", "Apie 50 mln. eurų", "Apie 500 mln. eurų", "Apie 5 mln. eurų", "Apie 1 mlrd. eurų"],
        explanation: "Pinigai skirti pasaulinei Mercedes-Benz stipendijų programai.",
      },
    },
  },
  {
    id: "rec_ob_026",
    category: "records",
    subTheme: "objects",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "BBC 2011 — Lady Blunt Stradivarius proceeds to Japan relief",
    emoji: "🎵",
    translations: {
      en: {
        question: "Money from the record Stradivarius sale was given to which cause?",
        correct: "Japan tsunami relief",
        distractors: ["A children's hospital", "Cancer research", "A new opera house", "Famine relief", "Animal shelters"],
        explanation: "The Lady Blunt is the best-preserved Stradivarius in existence.",
      },
      lt: {
        question: "Pinigai iš rekordinio Stradivarijaus pardavimo skirti kuriam tikslui?",
        correct: "Japonijos cunamio aukoms",
        distractors: ["Vaikų ligoninei", "Vėžio tyrimams", "Naujam operos teatrui", "Bado aukoms", "Gyvūnų prieglaudoms"],
        explanation: "Lady Blunt yra geriausiai išsilaikęs Stradivarijus pasaulyje.",
      },
    },
  },
  {
    id: "rec_ob_027",
    category: "records",
    subTheme: "objects",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Guinness — Great Stalacpipe Organ, largest natural instrument",
    emoji: "🎼",
    translations: {
      en: {
        question: "The world's largest natural instrument makes sound by tapping what?",
        correct: "Cave stalactites",
        distractors: ["Glass pipes", "Metal bars", "Stretched strings", "Water jars", "Wooden blocks"],
        explanation: "A mathematician tuned 37 cave stalactites over three years.",
      },
      lt: {
        question: "Didžiausias pasaulio natūralus instrumentas skleidžia garsą bakstelint į ką?",
        correct: "Urvo stalaktitus",
        distractors: ["Stiklo vamzdžius", "Metalo strypus", "Įtemptas stygas", "Vandens ąsočius", "Medinius blokus"],
        explanation: "Matematikas tris metus derino 37 urvo stalaktitus.",
      },
    },
  },
  {
    id: "rec_ob_028",
    category: "records",
    subTheme: "objects",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Guinness — Golden Jubilee diamond given to King of Thailand",
    emoji: "💍",
    translations: {
      en: {
        question: "The world's largest cut diamond, the Golden Jubilee, was given to whom?",
        correct: "The King of Thailand",
        distractors: ["The Queen of England", "The Pope", "A US museum", "The Sultan of Brunei", "The Emperor of Japan"],
        explanation: "It was cut from a flawed brown stone used to test new cutting tools.",
      },
      lt: {
        question: "Didžiausias pasaulio briaunuotas deimantas Golden Jubilee buvo padovanotas kam?",
        correct: "Tailando karaliui",
        distractors: ["Anglijos karalienei", "Popiežiui", "JAV muziejui", "Brunėjaus sultonui", "Japonijos imperatoriui"],
        explanation: "Jis išpjautas iš netobulo rudo akmens, naudoto naujiems įrankiams išbandyti.",
      },
    },
  },
  {
    id: "rec_ob_029",
    category: "records",
    subTheme: "objects",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Guinness — David Hockney, most expensive living-artist painting",
    emoji: "🖌️",
    translations: {
      en: {
        question: "Which artist set the auction record for a living artist with a pool painting?",
        correct: "David Hockney",
        distractors: ["Jeff Koons", "Damien Hirst", "Banksy", "Gerhard Richter", "Yayoi Kusama"],
        explanation: "He painted it by combining two photos he found on his studio floor.",
      },
      lt: {
        question: "Kuris menininkas pasiekė gyvo menininko aukciono rekordą paveikslu su baseinu?",
        correct: "David Hockney",
        distractors: ["Jeff Koons", "Damien Hirst", "Banksy", "Gerhard Richter", "Yayoi Kusama"],
        explanation: "Jį nutapė sujungęs dvi nuotraukas, rastas ant savo studijos grindų.",
      },
    },
  },
  {
    id: "rec_ob_030",
    category: "records",
    subTheme: "objects",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Sotheby's 2023 — Macallan 1926, most expensive whisky",
    emoji: "🥃",
    translations: {
      en: {
        question: "The most expensive bottle of whisky ever sold was which brand?",
        correct: "Macallan",
        distractors: ["Glenfiddich", "Johnnie Walker", "Dalmore", "Yamazaki", "Bowmore"],
        explanation: "The 1926 vintage spent 60 years in a cask; only 40 bottles were made.",
      },
      lt: {
        question: "Brangiausias kada nors parduotas viskio butelis buvo kurios markės?",
        correct: "Macallan",
        distractors: ["Glenfiddich", "Johnnie Walker", "Dalmore", "Yamazaki", "Bowmore"],
        explanation: "1926 m. derlius 60 metų brendo statinėje; pagaminti tik 40 butelių.",
      },
    },
  },

  // ===================== EKSTREMALUS (žinovai) =====================
  {
    id: "rec_ob_031",
    category: "records",
    subTheme: "objects",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Royal Collection Trust — Cullinan cut into 9 major stones",
    emoji: "✨",
    translations: {
      en: {
        question: "The giant Cullinan diamond was cut into how many major stones?",
        correct: "Nine",
        distractors: ["Three", "Five", "Twelve", "Twenty", "Two"],
        explanation: "The largest, Cullinan I, sits in the British Sovereign's Sceptre.",
      },
      lt: {
        question: "Milžiniškas Kalinano deimantas buvo išpjautas į kiek didelių akmenų?",
        correct: "Devynis",
        distractors: ["Tris", "Penkis", "Dvylika", "Dvidešimt", "Du"],
        explanation: "Didžiausias, Kalinanas I, puošia Britanijos valdovo skeptrą.",
      },
    },
  },
  {
    id: "rec_ob_032",
    category: "records",
    subTheme: "objects",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Guinness — Golden Jubilee, largest cut diamond",
    emoji: "💎",
    translations: {
      en: {
        question: "What is the name of the largest cut and faceted diamond in the world?",
        correct: "The Golden Jubilee",
        distractors: ["The Cullinan I", "The Hope", "The Koh-i-Noor", "The Pink Star", "The Orlov"],
        explanation: "At about 546 carats it is 15 carats heavier than Cullinan I.",
      },
      lt: {
        question: "Koks didžiausio pasaulyje briaunuoto deimanto pavadinimas?",
        correct: "Golden Jubilee",
        distractors: ["Kalinanas I", "Hope deimantas", "Koh-i-Noor", "Pink Star", "Orlovo deimantas"],
        explanation: "Maždaug 546 karatų — 15 karatų sunkesnis už Kalinaną I.",
      },
    },
  },
  {
    id: "rec_ob_033",
    category: "records",
    subTheme: "objects",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Sotheby's 2017 — CTF Pink Star, most expensive gemstone",
    emoji: "💠",
    translations: {
      en: {
        question: "The most expensive gemstone ever sold at auction is which diamond?",
        correct: "The Pink Star",
        distractors: ["The Hope", "The Cullinan", "The Blue Moon", "The Oppenheimer", "The Graff Pink"],
        explanation: "The 59.6-carat pink stone took about two years to cut and polish.",
      },
      lt: {
        question: "Brangiausias kada nors aukcione parduotas brangakmenis yra kuris deimantas?",
        correct: "Pink Star",
        distractors: ["Hope deimantas", "Kalinano deimantas", "Blue Moon", "Oppenheimer", "Graff Pink"],
        explanation: "59,6 karato rožinį akmenį pjovė ir poliravo apie dvejus metus.",
      },
    },
  },
  {
    id: "rec_ob_034",
    category: "records",
    subTheme: "objects",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Guinness — Giga Pearl ~27.65 kg",
    emoji: "🌊",
    translations: {
      en: {
        question: "About how heavy is the world's largest natural pearl?",
        correct: "About 27 kg",
        distractors: ["About 270 g", "About 2.7 kg", "About 100 kg", "About 1 kg", "About 5 kg"],
        explanation: "It was grown by a giant clam and has a porcelain-like surface.",
      },
      lt: {
        question: "Maždaug kiek sveria didžiausias pasaulio natūralus perlas?",
        correct: "Apie 27 kg",
        distractors: ["Apie 270 g", "Apie 2,7 kg", "Apie 100 kg", "Apie 1 kg", "Apie 5 kg"],
        explanation: "Jį užaugino milžiniška geldelė; paviršius primena porcelianą.",
      },
    },
  },
  {
    id: "rec_ob_035",
    category: "records",
    subTheme: "objects",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Christie's 2022 — Warhol Shot Sage Blue Marilyn",
    emoji: "🎨",
    translations: {
      en: {
        question: "Warhol's record Marilyn is called Shot because someone did what to the canvases?",
        correct: "Fired a gun at them",
        distractors: ["Photographed them", "Burned them", "Tore them", "Painted over them", "Threw ink at them"],
        explanation: "A visitor fired a revolver through a stack of the Marilyn canvases.",
      },
      lt: {
        question: "Ką kažkas padarė su Warholo Merilin drobėmis, kad jos vadinamos Shot?",
        correct: "Iššovė į jas",
        distractors: ["Nufotografavo", "Sudegino", "Suplėšė", "Užtepė dažais", "Apliejo rašalu"],
        explanation: "Lankytoja iššovė iš revolverio per Merilin drobių krūvą.",
      },
    },
  },
  {
    id: "rec_ob_036",
    category: "records",
    subTheme: "objects",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Guinness 2011 — longest hot dog, Paraguay",
    emoji: "🌭",
    translations: {
      en: {
        question: "The longest hot dog ever made was created in which country?",
        correct: "Paraguay",
        distractors: ["Germany", "The USA", "Brazil", "Argentina", "Austria"],
        explanation: "Made for the country's 200th birthday, then cut into 2,000 portions.",
      },
      lt: {
        question: "Kurioje šalyje pagamintas ilgiausias kada nors dešrainis?",
        correct: "Paragvajuje",
        distractors: ["Vokietijoje", "JAV", "Brazilijoje", "Argentinoje", "Austrijoje"],
        explanation: "Pagamintas šalies 200-mečiui, paskui supjaustytas į 2 000 porcijų.",
      },
    },
  },
  {
    id: "rec_ob_037",
    category: "records",
    subTheme: "objects",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Guinness — Megaton rubber band ball ~700,000 bands",
    emoji: "🧶",
    translations: {
      en: {
        question: "About how many rubber bands are in the largest rubber band ball?",
        correct: "About 700,000",
        distractors: ["About 7,000", "About 70,000", "About 7 million", "About 1,000", "About 70"],
        explanation: "One man wound them over about four and a half years; a crane moved it.",
      },
      lt: {
        question: "Maždaug kiek gumyčių yra didžiausiame gumyčių kamuolyje?",
        correct: "Apie 700 000",
        distractors: ["Apie 7 000", "Apie 70 000", "Apie 7 milijonus", "Apie 1 000", "Apie 70"],
        explanation: "Vienas vyras jas vyniojo apie ketverius su puse metų; kėlė kranu.",
      },
    },
  },
  {
    id: "rec_ob_038",
    category: "records",
    subTheme: "objects",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Guinness — longest scarf knitted by one person ~4.5 km",
    emoji: "🧣",
    translations: {
      en: {
        question: "The longest scarf knitted by one person is about how long?",
        correct: "Over 4 km",
        distractors: ["About 40 m", "About 400 m", "About 40 km", "About 4 m", "About 400 km"],
        explanation: "A Norwegian man hand-knitted the whole thing himself over many years.",
      },
      lt: {
        question: "Ilgiausias vieno žmogaus numegztas šalikas yra maždaug kokio ilgio?",
        correct: "Daugiau nei 4 km",
        distractors: ["Apie 40 m", "Apie 400 m", "Apie 40 km", "Apie 4 m", "Apie 400 km"],
        explanation: "Norvegas visą jį numezgė pats per daugelį metų.",
      },
    },
  },
  {
    id: "rec_ob_039",
    category: "records",
    subTheme: "objects",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Guinness 2011 — jigsaw with most pieces, 551,232",
    emoji: "🧩",
    translations: {
      en: {
        question: "The jigsaw puzzle with the most pieces ever assembled had about how many?",
        correct: "Over 500,000",
        distractors: ["About 5,000", "About 50,000", "About 5 million", "About 1,000", "About 100"],
        explanation: "About 1,600 students put it together in a stadium in around 17 hours.",
      },
      lt: {
        question: "Maždaug iš kiek detalių sudaryta daugiausiai dalių turinti kada nors sudėliota dėlionė?",
        correct: "Daugiau nei 500 000",
        distractors: ["Apie 5 000", "Apie 50 000", "Apie 5 milijonus", "Apie 1 000", "Apie 100"],
        explanation: "Apie 1 600 studentų ją sudėjo stadione maždaug per 17 valandų.",
      },
    },
  },
  {
    id: "rec_ob_040",
    category: "records",
    subTheme: "objects",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "De Beers — Golden Jubilee cut by Gabi Tolkowsky as a test stone",
    emoji: "⛏️",
    translations: {
      en: {
        question: "The largest cut diamond began as a rough stone of what unusual color?",
        correct: "Brown",
        distractors: ["Blue", "Pink", "Green", "Black", "Red"],
        explanation: "The flawed brown rough was used to test new diamond-cutting tools.",
      },
      lt: {
        question: "Didžiausias briaunuotas deimantas pradžioje buvo kokios neįprastos spalvos žaliava?",
        correct: "Ruda",
        distractors: ["Mėlyna", "Rožinė", "Žalia", "Juoda", "Raudona"],
        explanation: "Netobula ruda žaliava naudota naujiems deimantų pjovimo įrankiams išbandyti.",
      },
    },
  },
];
