/**
 * recordsHuman — 🏆 „Žmonių rekordai" potemė (tema „Rekordai ir keistenybės").
 *
 * MAŽAS FAILAS pagal potemę. 40 klausimų (10/lygiui). STABILŪS rekordai (istoriniai
 * Gineso, kurie NEsensta: aukščiausias/žemiausias žmogus, 100 m bėgimo WR, seniausias
 * žmogus ir pan.). Vengiama greitai kintančių (gyvas rekordininkas, populiacija).
 * Gyvūnų rekordai — GAMTOS temoje (čia nekartojama).
 *
 * TAISYKLĖS: 1 teisingas + 5 distraktoriai; ≤46 simb.; teisingas NE ilgiausias >+5;
 * LT be vidinių kabučių; jokio atsakymo klausime; emoji neišduoda atsakymo.
 */

import { TriviaQuestion } from "./triviaTypes";

export const RECORDS_HUMAN: TriviaQuestion[] = [
  // ===================== LENGVAS (9–12 m. vaikas) =====================
  {
    id: "rec_hu_001",
    category: "records",
    subTheme: "human",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Guinness — Robert Wadlow, tallest man ever (272 cm)",
    emoji: "📏",
    translations: {
      en: {
        question: "About how tall was the tallest man ever recorded?",
        correct: "About 2.7 meters",
        distractors: ["About 1.5 meters", "About 2 meters", "About 4 meters", "About 6 meters", "About 1 meter"],
        explanation: "He was far taller than any door — about 2.7 m (8 ft 11 in).",
      },
      lt: {
        question: "Maždaug kokio ūgio buvo aukščiausias kada nors užfiksuotas žmogus?",
        correct: "Apie 2,7 metro",
        distractors: ["Apie 1,5 metro", "Apie 2 metrus", "Apie 4 metrus", "Apie 6 metrus", "Apie 1 metrą"],
        explanation: "Jis buvo daug aukštesnis už bet kurias duris — apie 2,7 m.",
      },
    },
  },
  {
    id: "rec_hu_002",
    category: "records",
    subTheme: "human",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Guinness World Records — the famous records book",
    emoji: "📕",
    translations: {
      en: {
        question: "What famous book lists the world's official records each year?",
        correct: "Guinness World Records",
        distractors: ["A picture dictionary", "A phone book", "A comic book", "A cookbook", "An atlas"],
        explanation: "Guinness World Records has been published since 1955.",
      },
      lt: {
        question: "Kuri garsi knyga kasmet surašo oficialius pasaulio rekordus?",
        correct: "Gineso rekordų knyga",
        distractors: ["Paveikslėlių žodynas", "Telefonų knyga", "Komiksų knyga", "Receptų knyga", "Atlasas"],
        explanation: "Gineso rekordų knyga leidžiama nuo 1955 metų.",
      },
    },
  },
  {
    id: "rec_hu_003",
    category: "records",
    subTheme: "human",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Athletics — 100 m world record is 9.58 s (under 10 s)",
    emoji: "🏃",
    translations: {
      en: {
        question: "The fastest person ever ran 100 meters in under how many seconds?",
        correct: "Under 10 seconds",
        distractors: ["Under 9 seconds", "Under 9.5 seconds", "Under 8 seconds", "Under 5 seconds", "Under 2 seconds"],
        explanation: "The world record is 9.58 seconds — blink and it's over.",
      },
      lt: {
        question: "Greičiausias žmogus 100 metrų nubėgo greičiau nei per kiek sekundžių?",
        correct: "Greičiau nei 10 s",
        distractors: ["Greičiau nei 9 s", "Greičiau nei 9,5 s", "Greičiau nei 8 s", "Greičiau nei 5 s", "Greičiau nei 2 s"],
        explanation: "Pasaulio rekordas — 9,58 sekundės; nespėsi mirktelėti.",
      },
    },
  },
  {
    id: "rec_hu_004",
    category: "records",
    subTheme: "human",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Guinness — oldest verified person lived to 122",
    emoji: "🎂",
    translations: {
      en: {
        question: "The oldest people ever verified lived to be over how old?",
        correct: "Over 120 years",
        distractors: ["Over 130 years", "Over 140 years", "Over 150 years", "Over 200 years", "Over 300 years"],
        explanation: "The oldest verified person reached 122 years of age.",
      },
      lt: {
        question: "Seniausi kada nors patvirtinti žmonės sulaukė daugiau nei kiek metų?",
        correct: "Daugiau nei 120 metų",
        distractors: ["Daugiau nei 130 metų", "Daugiau nei 140 metų", "Daugiau nei 150 metų", "Daugiau nei 200 metų", "Daugiau nei 300 metų"],
        explanation: "Seniausias patvirtintas žmogus sulaukė 122 metų.",
      },
    },
  },
  {
    id: "rec_hu_005",
    category: "records",
    subTheme: "human",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Guinness — Chandra Bahadur Dangi, shortest man (54.6 cm)",
    emoji: "📐",
    translations: {
      en: {
        question: "The shortest grown man ever was only about how tall?",
        correct: "About 55 cm",
        distractors: ["About 10 cm", "About 1 meter", "About 1.5 meters", "About 30 cm", "About 5 cm"],
        explanation: "He was about 55 cm — shorter than many toddlers.",
      },
      lt: {
        question: "Žemiausias kada nors suaugęs vyras buvo vos apie kokio ūgio?",
        correct: "Apie 55 cm",
        distractors: ["Apie 10 cm", "Apie 1 metrą", "Apie 1,5 metro", "Apie 30 cm", "Apie 5 cm"],
        explanation: "Jis buvo apie 55 cm — žemesnis nei daugelis mažylių.",
      },
    },
  },
  {
    id: "rec_hu_006",
    category: "records",
    subTheme: "human",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Guinness — Hans Langseth, longest beard (~5.3 m)",
    emoji: "🧔",
    translations: {
      en: {
        question: "Roughly how long was the longest human beard ever recorded?",
        correct: "About 5 meters",
        distractors: ["About 5 cm", "About 50 cm", "About 1 meter", "About 50 meters", "About 20 meters"],
        explanation: "The longest beard ever measured about 5.3 meters!",
      },
      lt: {
        question: "Maždaug kokio ilgio buvo ilgiausia kada nors užfiksuota žmogaus barzda?",
        correct: "Apie 5 metrus",
        distractors: ["Apie 5 cm", "Apie 50 cm", "Apie 1 metrą", "Apie 50 metrų", "Apie 20 metrų"],
        explanation: "Ilgiausia kada nors barzda buvo apie 5,3 metro!",
      },
    },
  },
  {
    id: "rec_hu_007",
    category: "records",
    subTheme: "human",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Guinness — longest tongue can touch the nose",
    emoji: "👅",
    translations: {
      en: {
        question: "A record-long human tongue can easily reach up to the...?",
        correct: "Nose",
        distractors: ["Knee", "Shoulder", "Ear", "Foot", "Back"],
        explanation: "The longest tongues stretch past the lips to the nose.",
      },
      lt: {
        question: "Rekordiškai ilgas žmogaus liežuvis lengvai pasiekia iki...?",
        correct: "Nosies",
        distractors: ["Kelio", "Peties", "Ausies", "Pėdos", "Nugaros"],
        explanation: "Ilgiausi liežuviai prasilenkia pro lūpas iki pat nosies.",
      },
    },
  },
  {
    id: "rec_hu_008",
    category: "records",
    subTheme: "human",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Guinness — record holders grow extremely long fingernails",
    emoji: "💅",
    translations: {
      en: {
        question: "Which body part do some record holders grow incredibly long?",
        correct: "Fingernails",
        distractors: ["Ears", "Noses", "Teeth", "Eyelashes", "Knees"],
        explanation: "Record fingernails can grow several meters in total!",
      },
      lt: {
        question: "Kurią kūno dalį kai kurie rekordininkai užsiaugina neįtikėtinai ilgą?",
        correct: "Nagus",
        distractors: ["Ausis", "Nosis", "Dantis", "Blakstienas", "Kelius"],
        explanation: "Rekordiniai nagai iš viso gali nuaugti kelis metrus!",
      },
    },
  },
  {
    id: "rec_hu_009",
    category: "records",
    subTheme: "human",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Competitive eating — hot-dog eating contests set records",
    emoji: "🌭",
    translations: {
      en: {
        question: "In which contest do people set records for how much they can eat fast?",
        correct: "An eating contest",
        distractors: ["A spelling bee", "A running race", "A quiz show", "A dance-off", "A singing contest"],
        explanation: "Champions can eat dozens of hot dogs in just ten minutes.",
      },
      lt: {
        question: "Kuriose varžybose žmonės muša rekordus, kiek greitai gali suvalgyti?",
        correct: "Valgymo varžybose",
        distractors: ["Diktanto konkurse", "Bėgimo lenktynėse", "Protų mūšyje", "Šokių varžybose", "Dainavimo konkurse"],
        explanation: "Čempionai per dešimt minučių suvalgo dešimtis dešrainių.",
      },
    },
  },
  {
    id: "rec_hu_010",
    category: "records",
    subTheme: "human",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Concept — setting a record means beating the best result",
    emoji: "🥇",
    translations: {
      en: {
        question: "What do we call beating the best result anyone has ever done?",
        correct: "Setting a record",
        distractors: ["Losing a game", "Making a draw", "Taking a break", "Breaking a rule", "Telling a joke"],
        explanation: "A new record beats every result that came before it.",
      },
      lt: {
        question: "Kaip vadinama, kai pranoksti geriausią kada nors pasiektą rezultatą?",
        correct: "Rekordo pasiekimas",
        distractors: ["Pralaimėjimas", "Lygiosios", "Pertrauka", "Taisyklės laužymas", "Pokšto pasakymas"],
        explanation: "Naujas rekordas pranoksta visus ankstesnius rezultatus.",
      },
    },
  },

  // ===================== VIDUTINIS (12–18 m.) =====================
  {
    id: "rec_hu_011",
    category: "records",
    subTheme: "human",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Athletics — Usain Bolt holds the men's 100 m world record",
    emoji: "⚡",
    translations: {
      en: {
        question: "Who holds the men's 100 m world record of 9.58 seconds?",
        correct: "Usain Bolt",
        distractors: ["Carl Lewis", "Tyson Gay", "Asafa Powell", "Justin Gatlin", "Mo Farah"],
        explanation: "Bolt set the 9.58 s record in Berlin in 2009.",
      },
      lt: {
        question: "Kam priklauso vyrų 100 m pasaulio rekordas — 9,58 sekundės?",
        correct: "Usain Bolt",
        distractors: ["Carl Lewis", "Tyson Gay", "Asafa Powell", "Justin Gatlin", "Mo Farah"],
        explanation: "Boltas 9,58 s rekordą pasiekė Berlyne 2009 m.",
      },
    },
  },
  {
    id: "rec_hu_012",
    category: "records",
    subTheme: "human",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Guinness — Robert Wadlow, tallest man ever",
    emoji: "📏",
    translations: {
      en: {
        question: "What is the name of the tallest man ever recorded?",
        correct: "Robert Wadlow",
        distractors: ["Sultan Kosen", "Andre the Giant", "Yao Ming", "Shaquille O'Neal", "Manute Bol"],
        explanation: "Wadlow reached 272 cm and was still growing when he died.",
      },
      lt: {
        question: "Kaip vadinosi aukščiausias kada nors užfiksuotas žmogus?",
        correct: "Robert Wadlow",
        distractors: ["Sultan Kosen", "Andre the Giant", "Yao Ming", "Shaquille O'Neal", "Manute Bol"],
        explanation: "Vadlou pasiekė 272 cm ir, mirdamas, vis dar augo.",
      },
    },
  },
  {
    id: "rec_hu_013",
    category: "records",
    subTheme: "human",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Guinness — Jeanne Calment lived to 122 years",
    emoji: "🎂",
    translations: {
      en: {
        question: "To what age did the oldest verified person, Jeanne Calment, live?",
        correct: "122 years",
        distractors: ["100 years", "110 years", "116 years", "130 years", "150 years"],
        explanation: "Frenchwoman Jeanne Calment reached 122 years and 164 days.",
      },
      lt: {
        question: "Kiek metų sulaukė seniausias patvirtintas žmogus Jeanne Calment?",
        correct: "122 metų",
        distractors: ["100 metų", "110 metų", "116 metų", "130 metų", "150 metų"],
        explanation: "Prancūzė Jeanne Calment sulaukė 122 metų ir 164 dienų.",
      },
    },
  },
  {
    id: "rec_hu_014",
    category: "records",
    subTheme: "human",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Athletics — Mike Powell, long jump world record 8.95 m (1991)",
    emoji: "🦘",
    translations: {
      en: {
        question: "Who set the long jump world record of 8.95 m back in 1991?",
        correct: "Mike Powell",
        distractors: ["Carl Lewis", "Bob Beamon", "Jesse Owens", "Usain Bolt", "Greg Rutherford"],
        explanation: "Powell's 8.95 m leap has stood as the record for decades.",
      },
      lt: {
        question: "Kas 1991 m. pasiekė šuolio į tolį pasaulio rekordą — 8,95 m?",
        correct: "Mike Powell",
        distractors: ["Carl Lewis", "Bob Beamon", "Jesse Owens", "Usain Bolt", "Greg Rutherford"],
        explanation: "Pauelo 8,95 m šuolis rekordu išliko jau dešimtmečius.",
      },
    },
  },
  {
    id: "rec_hu_015",
    category: "records",
    subTheme: "human",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Freediving — top static apnea breath-holds exceed 10 minutes",
    emoji: "🤿",
    translations: {
      en: {
        question: "How long can the very best free-divers hold their breath?",
        correct: "Over 10 minutes",
        distractors: ["About 30 seconds", "About 1 minute", "About 3 minutes", "About 1 hour", "About 5 seconds"],
        explanation: "Trained free-divers can hold their breath for over 11 minutes.",
      },
      lt: {
        question: "Kiek laiko geriausi narai gali sulaikyti kvėpavimą?",
        correct: "Daugiau nei 10 min",
        distractors: ["Apie 30 sekundžių", "Apie 1 minutę", "Apie 3 minutes", "Apie 1 valandą", "Apie 5 sekundes"],
        explanation: "Treniruoti narai kvapą sulaiko ilgiau nei 11 minučių.",
      },
    },
  },
  {
    id: "rec_hu_016",
    category: "records",
    subTheme: "human",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Mountaineering — most Everest climbs held by Sherpa guides",
    emoji: "🏔️",
    translations: {
      en: {
        question: "People who set the record for most Everest climbs usually work as...?",
        correct: "Sherpa guides",
        distractors: ["Airline pilots", "Doctors", "Teachers", "Sailors", "Chefs"],
        explanation: "Nepali Sherpa guides have summited Everest over 25 times.",
      },
      lt: {
        question: "Žmonės, pasiekę daugiausiai Everesto kopimų rekordą, paprastai dirba...?",
        correct: "Šerpais gidais",
        distractors: ["Lėktuvų pilotais", "Gydytojais", "Mokytojais", "Jūreiviais", "Virėjais"],
        explanation: "Nepalo šerpai gidai į Everestą yra užkopę daugiau nei 25 kartus.",
      },
    },
  },
  {
    id: "rec_hu_017",
    category: "records",
    subTheme: "human",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Guinness — Charles Osborne hiccuped for about 68 years",
    emoji: "😮",
    translations: {
      en: {
        question: "The longest recorded bout of hiccups lasted roughly how long?",
        correct: "About 68 years",
        distractors: ["About 1 day", "About 1 week", "About 1 month", "About 6 years", "About 100 years"],
        explanation: "One man hiccuped from 1922 until 1990 — about 68 years!",
      },
      lt: {
        question: "Ilgiausias užfiksuotas žagsėjimo priepuolis truko maždaug kiek?",
        correct: "Apie 68 metus",
        distractors: ["Apie 1 dieną", "Apie 1 savaitę", "Apie 1 mėnesį", "Apie 6 metus", "Apie 100 metų"],
        explanation: "Vienas vyras žagsėjo nuo 1922 iki 1990 — apie 68 metus!",
      },
    },
  },
  {
    id: "rec_hu_018",
    category: "records",
    subTheme: "human",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Athletics — marathon world record is just over 2 hours",
    emoji: "🏅",
    translations: {
      en: {
        question: "The fastest official marathon (42 km) is run in just over how long?",
        correct: "Just over 2 hours",
        distractors: ["About 1 hour", "About 4 hours", "About 6 hours", "About 30 minutes", "About 10 hours"],
        explanation: "Elite runners finish the marathon in a little over two hours.",
      },
      lt: {
        question: "Greičiausias oficialus maratonas (42 km) nubėgamas vos per kiek laiko?",
        correct: "Vos per 2 valandas",
        distractors: ["Apie 1 valandą", "Apie 4 valandas", "Apie 6 valandas", "Apie 30 minučių", "Apie 10 valandų"],
        explanation: "Geriausi bėgikai maratoną įveikia kiek daugiau nei per dvi valandas.",
      },
    },
  },
  {
    id: "rec_hu_019",
    category: "records",
    subTheme: "human",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Guinness — Robert Wadlow needed huge custom shoes",
    emoji: "👞",
    translations: {
      en: {
        question: "Because of his record height, Robert Wadlow needed huge custom-made...?",
        correct: "Shoes",
        distractors: ["Glasses", "Hats", "Gloves", "Watches", "Belts"],
        explanation: "His feet were so big that ordinary shoes never fit him.",
      },
      lt: {
        question: "Dėl rekordinio ūgio Robertui Vadlou reikėjo milžiniškų, specialiai pagamintų...?",
        correct: "Batų",
        distractors: ["Akinių", "Kepurių", "Pirštinių", "Laikrodžių", "Diržų"],
        explanation: "Jo pėdos buvo tokios didelės, kad paprasti batai netiko.",
      },
    },
  },
  {
    id: "rec_hu_020",
    category: "records",
    subTheme: "human",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Athletics — Florence Griffith-Joyner, women's 100 m WR (1988)",
    emoji: "🏃‍♀️",
    translations: {
      en: {
        question: "Who set the women's 100 m world record back in 1988?",
        correct: "Florence Griffith-Joyner",
        distractors: ["Shelly-Ann Fraser-Pryce", "Elaine Thompson-Herah", "Marion Jones", "Allyson Felix", "Dina Asher-Smith"],
        explanation: "Her 10.49 s sprint has stood as the record since 1988.",
      },
      lt: {
        question: "Kas 1988 m. pasiekė moterų 100 m pasaulio rekordą?",
        correct: "Florence Griffith-Joyner",
        distractors: ["Shelly-Ann Fraser-Pryce", "Elaine Thompson-Herah", "Marion Jones", "Allyson Felix", "Dina Asher-Smith"],
        explanation: "Jos 10,49 s bėgimas rekordu išlieka nuo 1988 m.",
      },
    },
  },

  // ===================== SUNKUS (suaugę) =====================
  {
    id: "rec_hu_021",
    category: "records",
    subTheme: "human",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Olympics — Michael Phelps won a record 23 gold medals",
    emoji: "🏊",
    translations: {
      en: {
        question: "Who won a record 23 Olympic gold medals?",
        correct: "Michael Phelps",
        distractors: ["Usain Bolt", "Carl Lewis", "Mark Spitz", "Larisa Latynina", "Simone Biles"],
        explanation: "Swimmer Michael Phelps collected 23 Olympic golds in all.",
      },
      lt: {
        question: "Kas iškovojo rekordinius 23 olimpinius aukso medalius?",
        correct: "Michael Phelps",
        distractors: ["Usain Bolt", "Carl Lewis", "Mark Spitz", "Larisa Latynina", "Simone Biles"],
        explanation: "Plaukikas Michaelas Phelpsas iš viso surinko 23 olimpinius auksus.",
      },
    },
  },
  {
    id: "rec_hu_022",
    category: "records",
    subTheme: "human",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Athletics — Javier Sotomayor, high jump WR 2.45 m (1993)",
    emoji: "🦵",
    translations: {
      en: {
        question: "Who set the high jump world record of 2.45 m in 1993?",
        correct: "Javier Sotomayor",
        distractors: ["Mutaz Barshim", "Dick Fosbury", "Carl Lewis", "Usain Bolt", "Stefan Holm"],
        explanation: "Cuban Sotomayor's 2.45 m leap still tops the high jump.",
      },
      lt: {
        question: "Kas 1993 m. pasiekė šuolio į aukštį pasaulio rekordą — 2,45 m?",
        correct: "Javier Sotomayor",
        distractors: ["Mutaz Barshim", "Dick Fosbury", "Carl Lewis", "Usain Bolt", "Stefan Holm"],
        explanation: "Kubiečio Sotomajoro 2,45 m šuolis vis dar yra aukščiausias.",
      },
    },
  },
  {
    id: "rec_hu_023",
    category: "records",
    subTheme: "human",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Athletics — Bob Beamon's 1968 long jump stood 23 years",
    emoji: "⏳",
    translations: {
      en: {
        question: "Bob Beamon's famous 1968 long jump stayed a world record for how long?",
        correct: "About 23 years",
        distractors: ["About 1 year", "About 5 years", "About 50 years", "About 100 years", "About 10 years"],
        explanation: "His huge 8.90 m jump stood until Mike Powell beat it in 1991.",
      },
      lt: {
        question: "Garsusis Bobo Beamono 1968 m. šuolis į tolį pasaulio rekordu išliko kiek?",
        correct: "Apie 23 metus",
        distractors: ["Apie 1 metus", "Apie 5 metus", "Apie 50 metų", "Apie 100 metų", "Apie 10 metų"],
        explanation: "Jo 8,90 m šuolis išliko, kol 1991 m. jį pranoko Mike Powell.",
      },
    },
  },
  {
    id: "rec_hu_024",
    category: "records",
    subTheme: "human",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Endurance — Wim Hof set records in extreme cold",
    emoji: "❄️",
    translations: {
      en: {
        question: "Wim Hof set many records by enduring extreme...?",
        correct: "Cold",
        distractors: ["Heat", "Height", "Speed", "Hunger", "Noise"],
        explanation: "Nicknamed 'The Iceman', he sat in ice and swam under it.",
      },
      lt: {
        question: "Wim Hof pasiekė daug rekordų ištverdamas ekstremalų...?",
        correct: "Šaltį",
        distractors: ["Karštį", "Aukštį", "Greitį", "Alkį", "Triukšmą"],
        explanation: "Pravarde Ledo žmogus jis sėdėjo lede ir plaukė po juo.",
      },
    },
  },
  {
    id: "rec_hu_025",
    category: "records",
    subTheme: "human",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Athletics — the 9.58 s 100 m record was set in 2009",
    emoji: "📅",
    translations: {
      en: {
        question: "In which year was the 9.58 s 100 m world record set?",
        correct: "2009",
        distractors: ["1999", "2012", "1988", "2016", "2004"],
        explanation: "Usain Bolt ran 9.58 s at the 2009 World Championships in Berlin.",
      },
      lt: {
        question: "Kuriais metais pasiektas 9,58 s 100 m pasaulio rekordas?",
        correct: "2009",
        distractors: ["1999", "2012", "1988", "2016", "2004"],
        explanation: "Usain Bolt 9,58 s nubėgo 2009 m. pasaulio čempionate Berlyne.",
      },
    },
  },
  {
    id: "rec_hu_026",
    category: "records",
    subTheme: "human",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Athletics — Eliud Kipchoge first ran a marathon under 2 hours (2019)",
    emoji: "🏃",
    translations: {
      en: {
        question: "Who was first to run a marathon distance in under 2 hours (2019)?",
        correct: "Eliud Kipchoge",
        distractors: ["Mo Farah", "Haile Gebrselassie", "Usain Bolt", "Kenenisa Bekele", "Paula Radcliffe"],
        explanation: "Kipchoge ran 1:59:40 in a special event in Vienna in 2019.",
      },
      lt: {
        question: "Kas pirmas maratono nuotolį įveikė greičiau nei per 2 valandas (2019)?",
        correct: "Eliud Kipchoge",
        distractors: ["Mo Farah", "Haile Gebrselassie", "Usain Bolt", "Kenenisa Bekele", "Paula Radcliffe"],
        explanation: "Kipchoge 1:59:40 nubėgo per specialų renginį Vienoje 2019 m.",
      },
    },
  },
  {
    id: "rec_hu_027",
    category: "records",
    subTheme: "human",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Guinness — the loudest human shout exceeds 120 decibels",
    emoji: "📢",
    translations: {
      en: {
        question: "About how loud is the record for the loudest human shout?",
        correct: "Over 120 decibels",
        distractors: ["About 30 decibels", "About 50 decibels", "About 70 decibels", "About 200 decibels", "About 300 decibels"],
        explanation: "The loudest shout was as loud as a roaring jet engine.",
      },
      lt: {
        question: "Maždaug koks garsumo rekordas garsiausiam žmogaus šūksniui?",
        correct: "Daugiau nei 120 dB",
        distractors: ["Apie 30 dB", "Apie 50 dB", "Apie 70 dB", "Apie 200 decibelų", "Apie 300 dB"],
        explanation: "Garsiausias šūksnis prilygo riaumojančiam reaktyviniam varikliui.",
      },
    },
  },
  {
    id: "rec_hu_028",
    category: "records",
    subTheme: "human",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Guinness — longest fingernails grew over decades",
    emoji: "💅",
    translations: {
      en: {
        question: "The longest fingernails ever took roughly how long to grow?",
        correct: "Over 25 years",
        distractors: ["A few months", "About 1 year", "About 5 years", "About 200 years", "About 1 week"],
        explanation: "Some record holders grew their nails for decades without cutting.",
      },
      lt: {
        question: "Ilgiausi kada nors nagai augo maždaug kiek laiko?",
        correct: "Daugiau nei 25 metus",
        distractors: ["Vos kelis mėnesius", "Apie 1 metus", "Apie 5 metus", "Apie 200 metų", "Apie 1 savaitę"],
        explanation: "Kai kurie rekordininkai nagų nekirpo dešimtmečiais.",
      },
    },
  },
  {
    id: "rec_hu_029",
    category: "records",
    subTheme: "human",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Guinness — Robert Wadlow was from the United States",
    emoji: "🌎",
    translations: {
      en: {
        question: "Which country was the tallest man ever, Robert Wadlow, from?",
        correct: "The USA",
        distractors: ["China", "Turkey", "Ukraine", "Germany", "Brazil"],
        explanation: "Wadlow was born in Alton, Illinois, in the USA.",
      },
      lt: {
        question: "Iš kurios šalies buvo aukščiausias kada nors žmogus Robertas Vadlou?",
        correct: "JAV",
        distractors: ["Kinijos", "Turkijos", "Ukrainos", "Vokietijos", "Brazilijos"],
        explanation: "Vadlou gimė Altone, Ilinojaus valstijoje, JAV.",
      },
    },
  },
  {
    id: "rec_hu_030",
    category: "records",
    subTheme: "human",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Athletics — Armand Duplantis is the pole vault record star",
    emoji: "🤸",
    translations: {
      en: {
        question: "In which event does record-breaker Armand Duplantis compete?",
        correct: "Pole vault",
        distractors: ["High jump", "Long jump", "100 m sprint", "Marathon", "Shot put"],
        explanation: "Duplantis keeps raising his own pole vault world record.",
      },
      lt: {
        question: "Kurioje rungtyje varžosi rekordininkas Armand Duplantis?",
        correct: "Šuolyje su kartimi",
        distractors: ["Šuolyje į aukštį", "Šuolyje į tolį", "100 m bėgime", "Maratone", "Rutulio stūmime"],
        explanation: "Duplantis vis kelia savo paties šuolio su kartimi rekordą.",
      },
    },
  },

  // ===================== EKSTREMALUS (žinovai) =====================
  {
    id: "rec_hu_031",
    category: "records",
    subTheme: "human",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Guinness — Robert Wadlow measured 272 cm",
    emoji: "📏",
    translations: {
      en: {
        question: "What was the exact height of the tallest man ever, Robert Wadlow?",
        correct: "272 cm",
        distractors: ["251 cm", "230 cm", "290 cm", "210 cm", "305 cm"],
        explanation: "Wadlow was measured at 272 cm (8 ft 11.1 in) in 1940.",
      },
      lt: {
        question: "Koks buvo tikslus aukščiausio žmogaus Roberto Vadlou ūgis?",
        correct: "272 cm",
        distractors: ["251 cm", "230 cm", "290 cm", "210 cm", "305 cm"],
        explanation: "1940 m. Vadlou išmatuotas 272 cm ūgis.",
      },
    },
  },
  {
    id: "rec_hu_032",
    category: "records",
    subTheme: "human",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Guinness — Chandra Bahadur Dangi measured 54.6 cm",
    emoji: "📐",
    translations: {
      en: {
        question: "How tall was the shortest verified adult man, Chandra Dangi?",
        correct: "About 54.6 cm",
        distractors: ["About 21 cm", "About 75 cm", "About 90 cm", "About 40 cm", "About 100 cm"],
        explanation: "Nepal's Chandra Bahadur Dangi measured just 54.6 cm.",
      },
      lt: {
        question: "Kokio ūgio buvo žemiausias patvirtintas suaugęs vyras Chandra Dangis?",
        correct: "Apie 54,6 cm",
        distractors: ["Apie 21 cm", "Apie 75 cm", "Apie 90 cm", "Apie 40 cm", "Apie 100 cm"],
        explanation: "Nepalietis Chandra Bahaduras Dangis buvo vos 54,6 cm.",
      },
    },
  },
  {
    id: "rec_hu_033",
    category: "records",
    subTheme: "human",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Guinness — Jeanne Calment was from France",
    emoji: "🇫🇷",
    translations: {
      en: {
        question: "In which country did the oldest person ever, Jeanne Calment, live?",
        correct: "France",
        distractors: ["Japan", "Italy", "The USA", "Spain", "Britain"],
        explanation: "Calment lived her whole life in Arles, in southern France.",
      },
      lt: {
        question: "Kurioje šalyje gyveno seniausias kada nors žmogus Jeanne Calment?",
        correct: "Prancūzijoje",
        distractors: ["Japonijoje", "Italijoje", "JAV", "Ispanijoje", "Britanijoje"],
        explanation: "Calment visą gyvenimą praleido Arlyje, pietų Prancūzijoje.",
      },
    },
  },
  {
    id: "rec_hu_034",
    category: "records",
    subTheme: "human",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "History anecdote — Jeanne Calment recalled meeting Van Gogh",
    emoji: "🎨",
    translations: {
      en: {
        question: "As a girl, Jeanne Calment said she once met which famous painter?",
        correct: "Vincent van Gogh",
        distractors: ["Pablo Picasso", "Claude Monet", "Salvador Dali", "Leonardo da Vinci", "Rembrandt"],
        explanation: "She claimed to have sold pencils to Van Gogh in Arles around 1888.",
      },
      lt: {
        question: "Jeanne Calment pasakojo mergaitė sutikusi kurį garsų dailininką?",
        correct: "Vincentą van Gogą",
        distractors: ["Pablą Pikasą", "Klodą Monė", "Salvadorą Dali", "Leonardą da Vinčį", "Rembrandtą"],
        explanation: "Ji teigė apie 1888 m. Arlyje pardavusi van Gogui pieštukų.",
      },
    },
  },
  {
    id: "rec_hu_035",
    category: "records",
    subTheme: "human",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Athletics — Usain Bolt's top speed was about 44 km/h",
    emoji: "💨",
    translations: {
      en: {
        question: "About what top speed did Usain Bolt reach during his 9.58 s run?",
        correct: "About 44 km/h",
        distractors: ["About 25 km/h", "About 60 km/h", "About 100 km/h", "About 30 km/h", "About 80 km/h"],
        explanation: "For a few strides Bolt hit nearly 44.7 km/h.",
      },
      lt: {
        question: "Maždaug kokį didžiausią greitį Usain Bolt pasiekė per 9,58 s bėgimą?",
        correct: "Apie 44 km/h",
        distractors: ["Apie 25 km/h", "Apie 60 km/h", "Apie 100 km/h", "Apie 30 km/h", "Apie 80 km/h"],
        explanation: "Kelis žingsnius Boltas lėkė beveik 44,7 km/h greičiu.",
      },
    },
  },
  {
    id: "rec_hu_036",
    category: "records",
    subTheme: "human",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Olympics — Michael Phelps's record was in swimming",
    emoji: "🏊",
    translations: {
      en: {
        question: "In which sport did Michael Phelps win his record 23 gold medals?",
        correct: "Swimming",
        distractors: ["Athletics", "Gymnastics", "Cycling", "Rowing", "Diving"],
        explanation: "All 23 of Phelps's Olympic golds came in the pool.",
      },
      lt: {
        question: "Kurioje sporto šakoje Michael Phelps iškovojo rekordinius 23 auksus?",
        correct: "Plaukime",
        distractors: ["Lengvojoje atletikoje", "Gimnastikoje", "Dviračių sporte", "Irklavime", "Šuoliuose į vandenį"],
        explanation: "Visi 23 Phelpso olimpiniai auksai iškovoti baseine.",
      },
    },
  },
  {
    id: "rec_hu_037",
    category: "records",
    subTheme: "human",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Endurance — Wim Hof's nickname is 'The Iceman'",
    emoji: "🧊",
    translations: {
      en: {
        question: "What is the nickname of cold-endurance record holder Wim Hof?",
        correct: "The Iceman",
        distractors: ["The Flash", "The Rock", "The Tank", "The Bullet", "The Storm"],
        explanation: "He earned 'The Iceman' for his icy feats of endurance.",
      },
      lt: {
        question: "Kokia šalčio ištvermės rekordininko Wim Hof pravardė?",
        correct: "Ledo žmogus",
        distractors: ["Žaibas", "Uola", "Tankas", "Kulka", "Audra"],
        explanation: "Pravardę Ledo žmogus jis pelnė už ledinius ištvermės žygdarbius.",
      },
    },
  },
  {
    id: "rec_hu_038",
    category: "records",
    subTheme: "human",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Athletics — Bob Beamon's 1968 jump was at the Mexico City Olympics",
    emoji: "🏟️",
    translations: {
      en: {
        question: "At which 1968 Olympic city did Bob Beamon make his giant long jump?",
        correct: "Mexico City",
        distractors: ["Tokyo", "Munich", "Montreal", "Rome", "Seoul"],
        explanation: "The thin high-altitude air of Mexico City helped his huge leap.",
      },
      lt: {
        question: "Kuriame 1968 m. olimpiniame mieste Bob Beamon atliko milžinišką šuolį į tolį?",
        correct: "Meksike",
        distractors: ["Tokijuje", "Miunchene", "Monrealyje", "Romoje", "Seule"],
        explanation: "Retas Meksiko aukštumų oras padėjo jo milžiniškam šuoliui.",
      },
    },
  },
  {
    id: "rec_hu_039",
    category: "records",
    subTheme: "human",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Athletics — Florence Griffith-Joyner's 100 m record is 10.49 s",
    emoji: "⏱️",
    translations: {
      en: {
        question: "What is the women's 100 m world record time, set in 1988?",
        correct: "10.49 seconds",
        distractors: ["11.5 seconds", "9.58 seconds", "12.2 seconds", "10.99 seconds", "9.99 seconds"],
        explanation: "Florence Griffith-Joyner's 10.49 s has stood since 1988.",
      },
      lt: {
        question: "Koks moterų 100 m pasaulio rekordas, pasiektas 1988 m.?",
        correct: "10,49 sekundės",
        distractors: ["11,5 sekundės", "9,58 sekundės", "12,2 sekundės", "10,99 sekundės", "9,99 sekundės"],
        explanation: "Florence Griffith-Joyner 10,49 s rekordas išlieka nuo 1988 m.",
      },
    },
  },
  {
    id: "rec_hu_040",
    category: "records",
    subTheme: "human",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Mountaineering — Kami Rita Sherpa holds most Everest summits",
    emoji: "🗻",
    translations: {
      en: {
        question: "The record for most Everest summits is held by a guide from which country?",
        correct: "Nepal",
        distractors: ["India", "China", "Switzerland", "Japan", "Russia"],
        explanation: "Nepali Sherpa Kami Rita has reached the summit nearly 30 times.",
      },
      lt: {
        question: "Daugiausiai užkopimų į Everestą rekordą laiko gidas iš kurios šalies?",
        correct: "Nepalo",
        distractors: ["Indijos", "Kinijos", "Šveicarijos", "Japonijos", "Rusijos"],
        explanation: "Nepalo šerpas Kami Rita į viršūnę užkopė beveik 30 kartų.",
      },
    },
  },
];
