/**
 * recordsLaws — 🤪 „Keisti įstatymai ir tradicijos" potemė (tema „Rekordai ir keistenybės").
 *
 * MAŽAS FAILAS pagal potemę. 40 klausimų (10/lygiui). TIKRI, galiojantys, neutralūs,
 * juokingi įstatymai/tradicijos iš viso pasaulio. Visi faktai patikrinti patikimuose
 * šaltiniuose (naujienų agentūros, oficialūs puslapiai) — JOKIŲ mitų ar satyros.
 * SAUGA: be politikos/religijos/įžeidimų — tik lengvas „oho/ha-ha" efektas.
 *
 * TAISYKLĖS: 1 teisingas + 5 distraktoriai; ≤46 simb.; teisingas NE ilgiausias >+5;
 * LT be vidinių kabučių; jokio atsakymo klausime; EMOJI NEUTRALUS — neišduoda atsakymo
 * (JOKIŲ vėliavų, kai atsakymas yra šalis; jokio daikto, kai jis ir yra atsakymas).
 */

import { TriviaQuestion } from "./triviaTypes";

export const RECORDS_LAWS: TriviaQuestion[] = [
  // ===================== LENGVAS (9–12 m. vaikas) =====================
  {
    id: "rec_la_001",
    category: "records",
    subTheme: "laws",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Singapore Statutes — chewing gum sales ban (since 1992)",
    emoji: "⚖️",
    translations: {
      en: {
        question: "In Singapore, selling which everyday item is banned?",
        correct: "Chewing gum",
        distractors: ["Coffee", "Ice cream", "Bottled water", "Newspapers", "Umbrellas"],
        explanation: "Selling gum has been banned in Singapore since 1992; chewing it is fine.",
      },
      lt: {
        question: "Kurį kasdienį daiktą Singapūre draudžiama pardavinėti?",
        correct: "Kramtomąją gumą",
        distractors: ["Kavą", "Ledus", "Vandenį buteliuose", "Laikraščius", "Skėčius"],
        explanation: "Gumą Singapūre pardavinėti draudžiama nuo 1992 m.; kramtyti galima.",
      },
    },
  },
  {
    id: "rec_la_002",
    category: "records",
    subTheme: "laws",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "HISTORY.com, tomatina.es — La Tomatina festival, Bunol, Spain",
    emoji: "🍅",
    translations: {
      en: {
        question: "In which country do thousands throw tomatoes in the huge La Tomatina fight?",
        correct: "Spain",
        distractors: ["Italy", "Mexico", "Portugal", "Greece", "India"],
        explanation: "La Tomatina is held each August in Bunol, near Valencia, Spain.",
      },
      lt: {
        question: "Kurioje šalyje tūkstančiai mėto pomidorus per didžiulę La Tomatina kovą?",
        correct: "Ispanijoje",
        distractors: ["Italijoje", "Meksikoje", "Portugalijoje", "Graikijoje", "Indijoje"],
        explanation: "La Tomatina kasmet vyksta rugpjūtį Bunolyje prie Valensijos, Ispanijoje.",
      },
    },
  },
  {
    id: "rec_la_003",
    category: "records",
    subTheme: "laws",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Guinness World Records, BBC — Cooper's Hill cheese rolling",
    emoji: "🧀",
    translations: {
      en: {
        question: "In which country do people chase a rolling wheel of cheese down a steep hill?",
        correct: "England",
        distractors: ["Switzerland", "France", "Netherlands", "Austria", "Ireland"],
        explanation: "Cooper's Hill cheese rolling in Gloucestershire is centuries old.",
      },
      lt: {
        question: "Kurioje šalyje žmonės leidžiasi nuo stataus kalno vydamiesi riedantį sūrį?",
        correct: "Anglijoje",
        distractors: ["Šveicarijoje", "Prancūzijoje", "Nyderlanduose", "Austrijoje", "Airijoje"],
        explanation: "Sūrio ritinimo lenktynės Kuperio kalvoje vyksta jau šimtmečius.",
      },
    },
  },
  {
    id: "rec_la_004",
    category: "records",
    subTheme: "laws",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Seattle Times, NBC News — Venice pigeon-feeding ban (2007)",
    emoji: "🏛️",
    translations: {
      en: {
        question: "In Venice, feeding which birds in St Mark's Square is banned?",
        correct: "Pigeons",
        distractors: ["Robins", "Ducks", "Swans", "Crows", "Sparrows"],
        explanation: "Venice banned feeding pigeons in 2007 to protect its old monuments.",
      },
      lt: {
        question: "Kuriuos paukščius draudžiama lesinti Venecijos Šv. Morkaus aikštėje?",
        correct: "Balandžius",
        distractors: ["Liepsneles", "Antis", "Gulbes", "Varnas", "Žvirblius"],
        explanation: "Venecija 2007 m. uždraudė lesinti balandžius, kad apsaugotų paminklus.",
      },
    },
  },
  {
    id: "rec_la_005",
    category: "records",
    subTheme: "laws",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Korea.net, VisitKorea — Boryeong Mud Festival",
    emoji: "🏖️",
    translations: {
      en: {
        question: "In which country is there a huge festival for covering yourself in mud at the beach?",
        correct: "South Korea",
        distractors: ["Thailand", "Japan", "Vietnam", "India", "Philippines"],
        explanation: "The Boryeong Mud Festival on Daecheon Beach draws huge summer crowds.",
      },
      lt: {
        question: "Kurioje šalyje vyksta didelė šventė, kur paplūdimyje tepamasi purvu?",
        correct: "Pietų Korėjoje",
        distractors: ["Tailande", "Japonijoje", "Vietname", "Indijoje", "Filipinuose"],
        explanation: "Borjongo purvo festivalis Dečono paplūdimyje sutraukia minias.",
      },
    },
  },
  {
    id: "rec_la_006",
    category: "records",
    subTheme: "laws",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "eukonkanto.fi, Wikipedia — Wife-Carrying World Championship",
    emoji: "🏃",
    translations: {
      en: {
        question: "Which country hosts the famous Wife-Carrying World Championship?",
        correct: "Finland",
        distractors: ["Sweden", "Norway", "Estonia", "Denmark", "Germany"],
        explanation: "The race has been held in Sonkajarvi, Finland, since 1992.",
      },
      lt: {
        question: "Kurioje šalyje vyksta garsus žmonų nešimo pasaulio čempionatas?",
        correct: "Suomijoje",
        distractors: ["Švedijoje", "Norvegijoje", "Estijoje", "Danijoje", "Vokietijoje"],
        explanation: "Lenktynės Sonkajarvyje, Suomijoje, vyksta nuo 1992 m.",
      },
    },
  },
  {
    id: "rec_la_007",
    category: "records",
    subTheme: "laws",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "JNTO, Japan govt tourist hotline — tipping etiquette",
    emoji: "🍽️",
    translations: {
      en: {
        question: "In Japan, doing what in a restaurant can confuse or even offend the staff?",
        correct: "Leaving a tip",
        distractors: ["Bowing", "Saying thanks", "Finishing your food", "Taking off shoes", "Pouring tea"],
        explanation: "In Japan good service is standard, so a tip can seem confusing.",
      },
      lt: {
        question: "Ką padarius restorane Japonijoje galima sugluminti ar net įžeisti darbuotojus?",
        correct: "Palikti arbatpinigių",
        distractors: ["Nusilenkti", "Padėkoti", "Suvalgyti viską", "Nusiauti batus", "Įpilti arbatos"],
        explanation: "Japonijoje geras aptarnavimas savaime suprantamas, tad arbatpinigiai glumina.",
      },
    },
  },
  {
    id: "rec_la_008",
    category: "records",
    subTheme: "laws",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Wikipedia, storicocarnevaleivrea.it — Battle of the Oranges, Ivrea",
    emoji: "🍊",
    translations: {
      en: {
        question: "In which country do carnival teams pelt each other with tonnes of oranges?",
        correct: "Italy",
        distractors: ["Belgium", "Greece", "France", "Croatia", "Turkey"],
        explanation: "The Battle of the Oranges is part of the historic Carnival of Ivrea.",
      },
      lt: {
        question: "Kurioje šalyje per karnavalą komandos svaidosi tonomis apelsinų?",
        correct: "Italijoje",
        distractors: ["Belgijoje", "Graikijoje", "Prancūzijoje", "Kroatijoje", "Turkijoje"],
        explanation: "Apelsinų mūšis yra istorinio Ivrėjos karnavalo dalis.",
      },
    },
  },
  {
    id: "rec_la_009",
    category: "records",
    subTheme: "laws",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "The Local Germany — Autobahn no-stopping rule",
    emoji: "🛣️",
    translations: {
      en: {
        question: "On Germany's Autobahn, doing what is treated as an illegal, avoidable stop?",
        correct: "Running out of fuel",
        distractors: ["Driving too fast", "Changing a tyre", "Using the radio", "Eating a snack", "Opening a window"],
        explanation: "Stopping on the Autobahn is risky, so an empty tank counts as avoidable.",
      },
      lt: {
        question: "Kas Vokietijos automagistralėje laikoma neteisėtu, išvengiamu sustojimu?",
        correct: "Pasibaigęs kuras",
        distractors: ["Greitas važiavimas", "Rato keitimas", "Radijo klausymas", "Užkandžiavimas", "Atidarytas langas"],
        explanation: "Sustoti magistralėje pavojinga, tad tuščias bakas laikomas išvengiamu.",
      },
    },
  },
  {
    id: "rec_la_010",
    category: "records",
    subTheme: "laws",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "The Local Spain — municipal swimwear bylaws",
    emoji: "👮",
    translations: {
      en: {
        question: "In many Spanish towns, you can be fined for walking the streets in only your...?",
        correct: "Swimwear",
        distractors: ["Pyjamas", "Football kit", "Raincoat", "Slippers", "Sunglasses"],
        explanation: "Several Spanish towns fine people for wearing swimwear away from the beach.",
      },
      lt: {
        question: "Daugelyje Ispanijos miestų galima gauti baudą už vaikščiojimą gatvėmis vien su...?",
        correct: "Maudymosi kostiumu",
        distractors: ["Pižama", "Futbolo apranga", "Lietpalčiu", "Šlepetėmis", "Akiniais"],
        explanation: "Kai kurie Ispanijos miestai baudžia už maudymukus toliau nuo paplūdimio.",
      },
    },
  },

  // ===================== VIDUTINIS (12–18 m.) =====================
  {
    id: "rec_la_011",
    category: "records",
    subTheme: "laws",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "swissinfo.ch, Swiss Animal Protection Ordinance — social pets",
    emoji: "⚖️",
    translations: {
      en: {
        question: "Swiss law says you may not keep just one of which social pet alone?",
        correct: "A guinea pig",
        distractors: ["A cat", "A dog", "A hamster", "A turtle", "A snake"],
        explanation: "Switzerland treats guinea pigs as social, so they need a companion.",
      },
      lt: {
        question: "Kurį gyvūną Šveicarijoje draudžiama laikyti vieną, be poros?",
        correct: "Jūrų kiaulytę",
        distractors: ["Katę", "Šunį", "Žiurkėną", "Vėžlį", "Gyvatę"],
        explanation: "Šveicarijoje jūrų kiaulytės laikomos socialiomis — joms reikia draugo.",
      },
    },
  },
  {
    id: "rec_la_012",
    category: "records",
    subTheme: "laws",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "NPR — high heels banned at Greek ancient sites (2009)",
    emoji: "🏛️",
    translations: {
      en: {
        question: "At Greece's ancient sites like the Acropolis, wearing what is banned?",
        correct: "High heels",
        distractors: ["Watches", "Sandals", "Sunglasses", "Hats", "Gloves"],
        explanation: "Pointed heels can crack the old marble, so they are not allowed.",
      },
      lt: {
        question: "Graikijos senovės vietose, pavyzdžiui, Akropolyje, draudžiama avėti...?",
        correct: "Aukštakulnius",
        distractors: ["Laikrodžius", "Basutes", "Akinius", "Skrybėles", "Pirštines"],
        explanation: "Smaili kulnai gali įskelti senovinį marmurą, todėl jie neleidžiami.",
      },
    },
  },
  {
    id: "rec_la_013",
    category: "records",
    subTheme: "laws",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "NBC News, Afar — Rome bans sitting on the Spanish Steps (2019)",
    emoji: "🏛️",
    translations: {
      en: {
        question: "In Rome, you can be fined for sitting on which famous landmark?",
        correct: "The Spanish Steps",
        distractors: ["The Colosseum", "The Pantheon", "Castel Sant'Angelo", "St Peter's dome", "The Forum"],
        explanation: "Sitting on the 18th-century Spanish Steps was banned in 2019.",
      },
      lt: {
        question: "Romoje galima gauti baudą už sėdėjimą ant kurio garsaus objekto?",
        correct: "Ispaniškų laiptų",
        distractors: ["Koliziejaus", "Panteono", "Šv. Angelo pilies", "Šv. Petro kupolo", "Forumo"],
        explanation: "Sėdėti ant XVIII a. Ispaniškų laiptų uždrausta 2019 m.",
      },
    },
  },
  {
    id: "rec_la_014",
    category: "records",
    subTheme: "laws",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "legislation.gov.uk — Salmon Act 1986, Section 32",
    emoji: "⚖️",
    translations: {
      en: {
        question: "A real UK law makes it an offence to handle which animal in suspicious circumstances?",
        correct: "A salmon",
        distractors: ["A swan", "A badger", "A fox", "A deer", "A hare"],
        explanation: "The Salmon Act 1986 targets fish poaching, despite its funny wording.",
      },
      lt: {
        question: "Tikras Jungtinės Karalystės įstatymas baudžia įtartinai elgtis su kuriuo gyvūnu?",
        correct: "Su lašiša",
        distractors: ["Su gulbe", "Su barsuku", "Su lape", "Su elniu", "Su kiškiu"],
        explanation: "1986 m. Lašišų įstatymas kovoja su brakonieriavimu, nors skamba juokingai.",
      },
    },
  },
  {
    id: "rec_la_015",
    category: "records",
    subTheme: "laws",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "CNN, Britannica — Switzerland bans boiling live lobsters (2018)",
    emoji: "🦞",
    translations: {
      en: {
        question: "In Switzerland, what must you do to a lobster before boiling it?",
        correct: "Stun it first",
        distractors: ["Freeze it first", "Weigh it first", "Name it first", "Photograph it", "Wash it twice"],
        explanation: "Since 2018 Switzerland requires lobsters to be stunned before cooking.",
      },
      lt: {
        question: "Ką Šveicarijoje privaloma padaryti omarui prieš jį verdant?",
        correct: "Pirma apsvaiginti",
        distractors: ["Pirma užšaldyti", "Pirma pasverti", "Pirma pavadinti", "Nufotografuoti", "Du kartus nuplauti"],
        explanation: "Nuo 2018 m. Šveicarijoje omarus prieš gaminant privalu apsvaiginti.",
      },
    },
  },
  {
    id: "rec_la_016",
    category: "records",
    subTheme: "laws",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "royal.uk — Crown owns unmarked mute swans",
    emoji: "👑",
    translations: {
      en: {
        question: "In England, the King can legally claim all unmarked wild...?",
        correct: "Mute swans",
        distractors: ["Foxes", "Red deer", "Pigeons", "Wild horses", "Salmon"],
        explanation: "This royal right over open-water mute swans dates back to medieval times.",
      },
      lt: {
        question: "Anglijoje karalius gali teisėtai pasisavinti visas nepaženklintas laukines...?",
        correct: "Gulbes nebyles",
        distractors: ["Lapes", "Tauriuosius elnius", "Balandžius", "Laukinius arklius", "Lašišas"],
        explanation: "Ši karaliaus teisė į atvirų vandenų gulbes siekia viduramžius.",
      },
    },
  },
  {
    id: "rec_la_017",
    category: "records",
    subTheme: "laws",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "RAC country guide — Denmark daytime running lights (since 1990)",
    emoji: "🚗",
    translations: {
      en: {
        question: "In Denmark, cars must always drive with what on, even at noon?",
        correct: "Headlights",
        distractors: ["Hazard lights", "Wipers", "Fog lights", "Indicators", "Interior lights"],
        explanation: "Denmark has required daytime headlights for all cars since 1990.",
      },
      lt: {
        question: "Danijoje automobiliai visada turi važiuoti su kuo įjungtu, net vidurdienį?",
        correct: "Žibintais",
        distractors: ["Avariniais žibintais", "Valytuvais", "Rūko žibintais", "Posūkiais", "Salono šviesa"],
        explanation: "Danijoje dieniniai žibintai visiems automobiliams privalomi nuo 1990 m.",
      },
    },
  },
  {
    id: "rec_la_018",
    category: "records",
    subTheme: "laws",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Spain DGT (Majorca Daily Bulletin) — horn-use rule",
    emoji: "📣",
    translations: {
      en: {
        question: "In Spain, using your car horn is allowed without a fine only to...?",
        correct: "Warn of danger",
        distractors: ["Say hello", "Show anger", "Greet a friend", "Hurry others", "Celebrate"],
        explanation: "Spain's traffic rules allow the horn only to warn of real danger.",
      },
      lt: {
        question: "Ispanijoje automobilio signalą be baudos galima naudoti tik norint...?",
        correct: "Įspėti apie pavojų",
        distractors: ["Pasisveikinti", "Parodyti pyktį", "Pasveikinti draugą", "Paraginti kitus", "Pasidžiaugti"],
        explanation: "Ispanijos taisyklės leidžia signalą tik tikram pavojui įspėti.",
      },
    },
  },
  {
    id: "rec_la_019",
    category: "records",
    subTheme: "laws",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Lonely Planet, Afar — Cinque Terre footwear safety rule (2019)",
    emoji: "⛰️",
    translations: {
      en: {
        question: "In Italy's Cinque Terre park, hiking the trails in what can bring a fine?",
        correct: "Flip-flops",
        distractors: ["Hiking boots", "Trainers", "Trail shoes", "Sneakers", "Walking boots"],
        explanation: "Unsuitable footwear like flip-flops is fined for safety on steep trails.",
      },
      lt: {
        question: "Italijos Činkvė Terės parke ėjimas takais su kokia avalyne gali užtraukti baudą?",
        correct: "Šlepetėmis",
        distractors: ["Žygio batais", "Sportbačiais", "Takų batais", "Bėgimo bateliais", "Žygio aulinukais"],
        explanation: "Netinkama avalynė, kaip šlepetės, baudžiama dėl saugumo stačiuose takuose.",
      },
    },
  },
  {
    id: "rec_la_020",
    category: "records",
    subTheme: "laws",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "CNN — Florence bans eating on certain streets at meal times",
    emoji: "🏙️",
    translations: {
      en: {
        question: "In central Florence, doing what on some streets at meal times is banned?",
        correct: "Eating food",
        distractors: ["Singing", "Cycling", "Smoking", "Filming", "Skateboarding"],
        explanation: "Florence bans eating on a few busy old streets during lunch and dinner.",
      },
      lt: {
        question: "Florencijos centre, kai kuriose gatvėse valgymo metu draudžiama...?",
        correct: "Valgyti maistą",
        distractors: ["Dainuoti", "Važiuoti dviračiu", "Rūkyti", "Filmuoti", "Riedlentėmis"],
        explanation: "Florencija draudžia valgyti keliose judriose senose gatvėse per pietus ir vakarienę.",
      },
    },
  },

  // ===================== SUNKUS (suaugę) =====================
  {
    id: "rec_la_021",
    category: "records",
    subTheme: "laws",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Snopes, New York Times — Japan's Metabo Law (since 2008)",
    emoji: "🏥",
    translations: {
      en: {
        question: "Japan's health law has companies measure adults' yearly...?",
        correct: "Waistline",
        distractors: ["Eyesight", "Hearing", "Height", "Blood type", "Memory"],
        explanation: "The 2008 Metabo Law checks waistlines of adults aged 40 to 74.",
      },
      lt: {
        question: "Japonijos sveikatos įstatymas liepia įmonėms kasmet matuoti suaugusiųjų...?",
        correct: "Liemens apimtį",
        distractors: ["Regėjimą", "Klausą", "Ūgį", "Kraujo grupę", "Atmintį"],
        explanation: "2008 m. Metabo įstatymas tikrina 40–74 m. suaugusiųjų liemens apimtį.",
      },
    },
  },
  {
    id: "rec_la_022",
    category: "records",
    subTheme: "laws",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "WWD, city tourism page — Carmel-by-the-Sea high-heel permit",
    emoji: "📜",
    translations: {
      en: {
        question: "In Carmel, California, you need a free city permit to wear what on the streets?",
        correct: "High heels",
        distractors: ["Roller skates", "Costumes", "Backpacks", "Sandals", "Sunglasses"],
        explanation: "A 1963 rule needs a permit for tall heels, blamed on bumpy sidewalks.",
      },
      lt: {
        question: "Karmelyje (Kalifornija) reikia nemokamo leidimo gatvėse avėti...?",
        correct: "Aukštakulnius",
        distractors: ["Riedučius", "Kostiumus", "Kuprines", "Basutes", "Akinius"],
        explanation: "1963 m. taisyklė reikalauja leidimo aukštiems kulnams dėl nelygių šaligatvių.",
      },
    },
  },
  {
    id: "rec_la_023",
    category: "records",
    subTheme: "laws",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Stewart, Melvin & Frost (law firm) — Gainesville, Georgia ordinance",
    emoji: "🍗",
    translations: {
      en: {
        question: "A town in Georgia, USA, has a fun rule to eat fried chicken only with your...?",
        correct: "Hands",
        distractors: ["Fork", "Spoon", "Chopsticks", "Knife", "Gloves"],
        explanation: "Gainesville's 1961 rule celebrates it as the poultry capital of the world.",
      },
      lt: {
        question: "Vienos JAV Džordžijos valstijos miesto linksma taisyklė liepia keptą vištieną valgyti tik...?",
        correct: "Rankomis",
        distractors: ["Šakute", "Šaukštu", "Lazdelėmis", "Peiliu", "Pirštinėmis"],
        explanation: "Geinsvilio 1961 m. taisyklė garsina jį kaip paukštienos sostinę.",
      },
    },
  },
  {
    id: "rec_la_024",
    category: "records",
    subTheme: "laws",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Canada Currency Act, Section 8 (legal-tender limits)",
    emoji: "🍁",
    translations: {
      en: {
        question: "In Canada, the law limits how many of what you can use in a single payment?",
        correct: "Coins",
        distractors: ["Banknotes", "Cheques", "Cards", "Stamps", "Gift cards"],
        explanation: "Canada's Currency Act caps coin payments, e.g. only 25 cents in pennies.",
      },
      lt: {
        question: "Kanadoje įstatymas riboja, kiek ko galima panaudoti vienam mokėjimui?",
        correct: "Monetų",
        distractors: ["Banknotų", "Čekių", "Kortelių", "Pašto ženklų", "Dovanų kuponų"],
        explanation: "Kanados valiutos įstatymas riboja mokėjimus monetomis, pvz. centais iki 25 ct.",
      },
    },
  },
  {
    id: "rec_la_025",
    category: "records",
    subTheme: "laws",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "UNESCO, Snopes — Brazil 'Remission for Reading' program",
    emoji: "🔒",
    translations: {
      en: {
        question: "In Brazil, prisoners can shorten their sentence by doing what?",
        correct: "Reading books",
        distractors: ["Watching TV", "Sleeping more", "Growing a beard", "Telling jokes", "Daydreaming"],
        explanation: "Brazil cuts four days off a sentence for each approved book review.",
      },
      lt: {
        question: "Brazilijoje kaliniai gali sutrumpinti bausmę darydami ką?",
        correct: "Skaitydami knygas",
        distractors: ["Žiūrėdami televizorių", "Ilgiau miegodami", "Augindami barzdą", "Pasakodami juokus", "Svajodami"],
        explanation: "Brazilija už kiekvieną patvirtintą knygos apžvalgą atima keturias dienas.",
      },
    },
  },
  {
    id: "rec_la_026",
    category: "records",
    subTheme: "laws",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Earth Island Journal — India bans dolphin entertainment (2013)",
    emoji: "🚫",
    translations: {
      en: {
        question: "India uniquely classed which animals as non-human persons and banned their shows?",
        correct: "Dolphins",
        distractors: ["Horses", "Camels", "Pigeons", "Goats", "Donkeys"],
        explanation: "India's 2013 policy rejects dolphinariums on moral grounds.",
      },
      lt: {
        question: "Indija kaip vienintelė pripažino kuriuos gyvūnus prilygstančiais asmenims ir uždraudė jų pasirodymus?",
        correct: "Delfinus",
        distractors: ["Arklius", "Kupranugarius", "Karvelius", "Ožkas", "Asilus"],
        explanation: "Indijos 2013 m. politika atmeta delfinariumus dėl moralinių priežasčių.",
      },
    },
  },
  {
    id: "rec_la_027",
    category: "records",
    subTheme: "laws",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "TODAY/NBC — Denmark's Law on Personal Names",
    emoji: "👶",
    translations: {
      en: {
        question: "In Denmark, parents usually must pick a baby's first name from an official...?",
        correct: "Approved list",
        distractors: ["Family tree", "Old calendar", "Dictionary", "Bible", "Lottery draw"],
        explanation: "Unusual names not on Denmark's list need special government approval.",
      },
      lt: {
        question: "Danijoje tėvai kūdikio vardą paprastai turi rinktis iš oficialaus...?",
        correct: "Patvirtinto sąrašo",
        distractors: ["Giminės medžio", "Seno kalendoriaus", "Žodyno", "Šventraščio", "Loterijos"],
        explanation: "Neįprastiems vardams, kurių nėra sąraše, reikia atskiro valdžios leidimo.",
      },
    },
  },
  {
    id: "rec_la_028",
    category: "records",
    subTheme: "laws",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "EFTM, Yahoo Finance AU — leaving car unsecured fine (NSW/QLD)",
    emoji: "🚗",
    translations: {
      en: {
        question: "In parts of Australia, you can be fined for leaving your parked car...?",
        correct: "Unlocked",
        distractors: ["Dirty", "Dented", "In the sun", "Facing uphill", "Without plates"],
        explanation: "If you step away with the car unlocked, some states issue a small fine.",
      },
      lt: {
        question: "Kai kur Australijoje galima gauti baudą už pastatytą automobilį, paliktą...?",
        correct: "Neužrakintą",
        distractors: ["Nešvarų", "Įlenktą", "Saulėkaitoje", "Atsuktą į kalną", "Be numerių"],
        explanation: "Jei nutolsti palikęs neužrakintą automobilį, kai kurios valstijos baudžia.",
      },
    },
  },
  {
    id: "rec_la_029",
    category: "records",
    subTheme: "laws",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "A-Z Animals, LegalClarity — Key West protects wild chickens",
    emoji: "🚫",
    translations: {
      en: {
        question: "In Key West, Florida, it is illegal to harm or feed the free-roaming...?",
        correct: "Chickens",
        distractors: ["Cats", "Parrots", "Iguanas", "Squirrels", "Seagulls"],
        explanation: "Key West protects its wandering chickens as part of local character.",
      },
      lt: {
        question: "Ki Veste (Florida) draudžiama skriausti ar lesinti laisvai vaikštančias...?",
        correct: "Vištas",
        distractors: ["Kates", "Papūgas", "Iguanas", "Voveres", "Žuvėdras"],
        explanation: "Ki Vestas saugo savo klajojančias vištas kaip vietos savitumo dalį.",
      },
    },
  },
  {
    id: "rec_la_030",
    category: "records",
    subTheme: "laws",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Singapore Environmental Public Health Regulations — toilet flushing",
    emoji: "🚻",
    translations: {
      en: {
        question: "In Singapore, forgetting to do what in a public toilet can bring a fine?",
        correct: "Flush it",
        distractors: ["Wash your hands", "Lock the door", "Turn off the tap", "Queue politely", "Wipe the seat"],
        explanation: "Forgetting to flush a public toilet in Singapore can bring a real fine.",
      },
      lt: {
        question: "Ką pamiršus padaryti viešajame Singapūro tualete galima gauti baudą?",
        correct: "Nuleisti vandenį",
        distractors: ["Nusiplauti rankas", "Užrakinti duris", "Užsukti čiaupą", "Tvarkingai stovėti eilėje", "Nuvalyti dangtį"],
        explanation: "Pamiršus nuleisti vandenį viešajame Singapūro tualete galima gauti tikrą baudą.",
      },
    },
  },

  // ===================== EKSTREMALUS (žinovai) =====================
  {
    id: "rec_la_031",
    category: "records",
    subTheme: "laws",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "VinePair, eukonkanto.fi — Wife-Carrying prize",
    emoji: "🏆",
    translations: {
      en: {
        question: "Finland's Wife-Carrying champion famously wins the wife's weight in what?",
        correct: "Beer",
        distractors: ["Gold", "Chocolate", "Coffee", "Honey", "Cheese"],
        explanation: "The widely reported prize is the partner's weight in beer.",
      },
      lt: {
        question: "Suomijos žmonų nešimo nugalėtojas tradiciškai laimi žmonos svorį kuo?",
        correct: "Alumi",
        distractors: ["Auksu", "Šokoladu", "Kava", "Medumi", "Sūriu"],
        explanation: "Plačiai minimas prizas — alaus kiekis, lygus partnerės svoriui.",
      },
    },
  },
  {
    id: "rec_la_032",
    category: "records",
    subTheme: "laws",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Shetland.org, BBC — Up Helly Aa fire festival",
    emoji: "🔥",
    translations: {
      en: {
        question: "At Scotland's Up Helly Aa fire festival, crowds set ablaze a full-size...?",
        correct: "Viking longship",
        distractors: ["Wicker man", "Castle model", "Straw bull", "Wooden dragon", "Bonfire tower"],
        explanation: "Torch-bearers burn a Viking longship each January in Shetland.",
      },
      lt: {
        question: "Per Škotijos Up Helly Aa ugnies šventę minios padega tikro dydžio...?",
        correct: "Vikingų laivą",
        distractors: ["Pintą žmogų", "Pilies maketą", "Šiaudų jautį", "Medinį drakoną", "Laužo bokštą"],
        explanation: "Deglų nešėjai kasmet sausį Šetlande sudegina vikingų laivą.",
      },
    },
  },
  {
    id: "rec_la_033",
    category: "records",
    subTheme: "laws",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Visit Wales, BBC — Bog Snorkelling World Championships",
    emoji: "🤿",
    translations: {
      en: {
        question: "Wales hosts a world championship for snorkelling through a...?",
        correct: "Peat bog trench",
        distractors: ["Frozen lake", "Sewer pipe", "Cave river", "Flooded mine", "Mud volcano"],
        explanation: "Competitors flipper through a muddy bog trench near Llanwrtyd Wells.",
      },
      lt: {
        question: "Velse vyksta pasaulio čempionatas nardant su vamzdeliu per...?",
        correct: "Durpyno griovį",
        distractors: ["Užšalusį ežerą", "Kanalizaciją", "Urvo upę", "Užtvindytą kasyklą", "Purvo ugnikalnį"],
        explanation: "Dalyviai plaukia su pelekais per purviną durpyno griovį prie Lanvrtid miestelio.",
      },
    },
  },
  {
    id: "rec_la_034",
    category: "records",
    subTheme: "laws",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "NPR, VisitFinland — Air Guitar World Championships, Oulu",
    emoji: "🎶",
    translations: {
      en: {
        question: "Finland hosts a world championship for playing which imaginary instrument?",
        correct: "Air guitar",
        distractors: ["Air drums", "Air piano", "Air violin", "Air flute", "Air trumpet"],
        explanation: "The Air Guitar World Championships are held every August in Oulu.",
      },
      lt: {
        question: "Suomijoje vyksta pasaulio čempionatas grojant kuriuo įsivaizduojamu instrumentu?",
        correct: "Oro gitara",
        distractors: ["Oro būgnais", "Oro pianinu", "Oro smuiku", "Oro fleita", "Oro trimitu"],
        explanation: "Oro gitaros pasaulio čempionatas kasmet rugpjūtį vyksta Ouluje.",
      },
    },
  },
  {
    id: "rec_la_035",
    category: "records",
    subTheme: "laws",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Historic Royal Palaces — Tower of London ravens rule",
    emoji: "🏰",
    translations: {
      en: {
        question: "At least how many ravens must always be kept at the Tower of London?",
        correct: "Six",
        distractors: ["Two", "Four", "Ten", "Twelve", "Twenty"],
        explanation: "Legend says if the six ravens leave, the kingdom will fall.",
      },
      lt: {
        question: "Kiek mažiausiai varnų visada turi būti laikoma Londono Taueryje?",
        correct: "Šešios",
        distractors: ["Dvi", "Keturios", "Dešimt", "Dvylika", "Dvidešimt"],
        explanation: "Legenda sako: jei šešios varnos pasitrauks, karalystė žlugs.",
      },
    },
  },
  {
    id: "rec_la_036",
    category: "records",
    subTheme: "laws",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "The Register, NBC — Singapore Computer Misuse Act case",
    emoji: "💻",
    translations: {
      en: {
        question: "In Singapore, using a neighbour's open what without permission counts as hacking?",
        correct: "Wi-Fi",
        distractors: ["Garden", "Bin", "Parking spot", "Mailbox", "Doorbell"],
        explanation: "A teenager was actually convicted for using an open Wi-Fi network.",
      },
      lt: {
        question: "Singapūre kaimyno atvirą ką naudoti be leidimo prilyginama įsilaužimui?",
        correct: "Wi-Fi",
        distractors: ["Sodą", "Šiukšliadėžę", "Stovėjimo vietą", "Pašto dėžutę", "Durų skambutį"],
        explanation: "Paauglys iš tikro buvo nuteistas už naudojimąsi atviru Wi-Fi tinklu.",
      },
    },
  },
  {
    id: "rec_la_037",
    category: "records",
    subTheme: "laws",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "NBC News, NPR — Turin dog-walking bylaw (2005)",
    emoji: "🐕",
    translations: {
      en: {
        question: "In Turin, Italy, owners can be fined for not walking their dog how often?",
        correct: "Three times a day",
        distractors: ["Once a week", "Twice a month", "Every hour", "Once a day", "Five times a day"],
        explanation: "A 2005 Turin bylaw asks owners to walk their dogs three times daily.",
      },
      lt: {
        question: "Turine (Italija) šeimininkai gali būti baudžiami už šuns nevedžiojimą kaip dažnai?",
        correct: "Tris kartus per dieną",
        distractors: ["Kartą per savaitę", "Du kartus per mėnesį", "Kas valandą", "Kartą per dieną", "Penkis kartus"],
        explanation: "2005 m. Turino taisyklė prašo šunis vedžioti tris kartus per dieną.",
      },
    },
  },
  {
    id: "rec_la_038",
    category: "records",
    subTheme: "laws",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "CBC, Washington Post — Rome/Monza ban round goldfish bowls",
    emoji: "🐟",
    translations: {
      en: {
        question: "An Italian city banned keeping pet goldfish in what, calling it cruel?",
        correct: "Round bowls",
        distractors: ["Cold water", "Small tanks", "Plastic bags", "Glass jars", "Garden ponds"],
        explanation: "Officials said round bowls give fish a distorted, stressful view.",
      },
      lt: {
        question: "Vienas Italijos miestas uždraudė laikyti auksines žuveles kame, vadindamas tai žiauriu?",
        correct: "Apvaliuose induose",
        distractors: ["Šaltame vandenyje", "Mažuose akvariumuose", "Plastiko maišeliuose", "Stiklainiuose", "Sodo tvenkiniuose"],
        explanation: "Valdininkai teigė, kad apvalūs indai žuvims iškreipia vaizdą ir kelia stresą.",
      },
    },
  },
  {
    id: "rec_la_039",
    category: "records",
    subTheme: "laws",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Japan Local Government Center — Chiyoda Ward street-smoking ban",
    emoji: "🏙️",
    translations: {
      en: {
        question: "Many Japanese city districts give on-the-spot fines for doing what on the street?",
        correct: "Smoking while walking",
        distractors: ["Eating while walking", "Whistling", "Carrying an umbrella", "Window shopping", "Wearing sunglasses"],
        explanation: "Districts like Tokyo's Chiyoda fine walking-and-smoking outside set areas.",
      },
      lt: {
        question: "Daugelis Japonijos miesto rajonų vietoje baudžia už ką gatvėje?",
        correct: "Rūkymą einant",
        distractors: ["Valgymą einant", "Švilpavimą", "Skėčio nešimą", "Vitrinų žiūrinėjimą", "Akinių nešiojimą"],
        explanation: "Tokijo Čijodos rajone baudžiama už rūkymą einant ne tam skirtose vietose.",
      },
    },
  },
  {
    id: "rec_la_040",
    category: "records",
    subTheme: "laws",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "ch.ch (official Swiss portal) — Sunday quiet-hours rules",
    emoji: "🤫",
    translations: {
      en: {
        question: "In Switzerland, doing what on a Sunday can break neighbourhood quiet rules?",
        correct: "Mowing the lawn",
        distractors: ["Reading a book", "Cooking dinner", "Watching TV", "Walking the dog", "Baking bread"],
        explanation: "Swiss quiet-hour customs discourage loud chores like mowing on Sundays.",
      },
      lt: {
        question: "Šveicarijoje ką darant sekmadienį galima pažeisti kaimynų ramybės taisykles?",
        correct: "Pjaunant veją",
        distractors: ["Skaitant knygą", "Gaminant vakarienę", "Žiūrint televizorių", "Vedžiojant šunį", "Kepant duoną"],
        explanation: "Šveicarų ramybės papročiai sekmadienį nepritaria triukšmingiems darbams.",
      },
    },
  },
];
