/**
 * recordsWorld — 🌍 „Pasaulio rekordai" potemė (tema „Rekordai ir keistenybės").
 *
 * MAŽAS FAILAS pagal potemę. 40 klausimų (10/lygiui). STABILŪS pasaulio rekordai
 * (geografiniai ir žmogaus sukurti superlatyvai, kurie NEsensta: aukščiausias
 * pastatas, didžiausia šalis, giliausia vieta vandenyne ir pan.). Vengiama
 * ginčytinų (ilgiausia upė) ir greitai kintančių (populiacija, dabartiniai lyderiai).
 * Gyvūnų rekordai — GAMTOS temoje (čia nekartojama).
 *
 * TAISYKLĖS: 1 teisingas + 5 distraktoriai; ≤46 simb.; teisingas NE ilgiausias >+5;
 * LT be vidinių kabučių; jokio atsakymo klausime; emoji neišduoda atsakymo.
 * Kur subjektas kartojasi su geografijos tema, čia pateikiamas KITU faktu/dydžiu.
 */

import { TriviaQuestion } from "./triviaTypes";

export const RECORDS_WORLD: TriviaQuestion[] = [
  // ===================== LENGVAS (9–12 m. vaikas) =====================
  {
    id: "rec_wo_001",
    category: "records",
    subTheme: "world",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Guinness — Burj Khalifa, tallest building (828 m)",
    emoji: "🏙️",
    translations: {
      en: {
        question: "What is the tallest building in the world?",
        correct: "Burj Khalifa",
        distractors: ["The Eiffel Tower", "Empire State Building", "Big Ben", "The Statue of Liberty", "Tokyo Tower"],
        explanation: "The Burj Khalifa in Dubai rises over 800 metres.",
      },
      lt: {
        question: "Koks aukščiausias pastatas pasaulyje?",
        correct: "Burdž Chalifa",
        distractors: ["Eifelio bokštas", "Empire State Building", "Big Benas", "Laisvės statula", "Tokijo bokštas"],
        explanation: "Burdž Chalifa Dubajuje kyla daugiau nei 800 metrų.",
      },
    },
  },
  {
    id: "rec_wo_002",
    category: "records",
    subTheme: "world",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography — Russia is the largest country by area (~17M km²)",
    emoji: "🗺️",
    translations: {
      en: {
        question: "Which country covers the largest area on Earth?",
        correct: "Russia",
        distractors: ["Canada", "China", "Brazil", "Australia", "India"],
        explanation: "Russia covers about 17 million square kilometres in total.",
      },
      lt: {
        question: "Kuri šalis užima didžiausią plotą Žemėje?",
        correct: "Rusija",
        distractors: ["Kanada", "Kinija", "Brazilija", "Australija", "Indija"],
        explanation: "Rusijos plotas — maždaug 17 milijonų kvadratinių kilometrų.",
      },
    },
  },
  {
    id: "rec_wo_003",
    category: "records",
    subTheme: "world",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography — Vatican City is the smallest country (0.49 km²)",
    emoji: "🤏",
    translations: {
      en: {
        question: "Which is the smallest country in the world?",
        correct: "Vatican City",
        distractors: ["Monaco", "San Marino", "Malta", "Luxembourg", "Liechtenstein"],
        explanation: "Vatican City is smaller than many city parks.",
      },
      lt: {
        question: "Kuri mažiausia šalis pasaulyje?",
        correct: "Vatikanas",
        distractors: ["Monakas", "San Marinas", "Malta", "Liuksemburgas", "Lichtenšteinas"],
        explanation: "Vatikanas mažesnis už daugelį miesto parkų.",
      },
    },
  },
  {
    id: "rec_wo_004",
    category: "records",
    subTheme: "world",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography — Mount Everest is the highest mountain (8,849 m)",
    emoji: "🏔️",
    translations: {
      en: {
        question: "What is the highest mountain above sea level?",
        correct: "Mount Everest",
        distractors: ["K2", "Mont Blanc", "Kilimanjaro", "Mount Fuji", "The Matterhorn"],
        explanation: "Mount Everest reaches about 8,849 metres high.",
      },
      lt: {
        question: "Koks aukščiausias kalnas virš jūros lygio?",
        correct: "Everestas",
        distractors: ["K2", "Monblanas", "Kilimandžaras", "Fudžis", "Materhornas"],
        explanation: "Everestas siekia maždaug 8 849 metrus.",
      },
    },
  },
  {
    id: "rec_wo_005",
    category: "records",
    subTheme: "world",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Oceanography — the Pacific is the largest ocean",
    emoji: "🌊",
    translations: {
      en: {
        question: "Which is the largest ocean on Earth?",
        correct: "The Pacific Ocean",
        distractors: ["The Atlantic Ocean", "The Indian Ocean", "The Arctic Ocean", "The Southern Ocean", "The Baltic Sea"],
        explanation: "The Pacific Ocean covers about a third of the planet.",
      },
      lt: {
        question: "Koks didžiausias vandenynas Žemėje?",
        correct: "Ramusis vandenynas",
        distractors: ["Atlanto vandenynas", "Indijos vandenynas", "Arkties vandenynas", "Pietų vandenynas", "Baltijos jūra"],
        explanation: "Ramusis vandenynas dengia maždaug trečdalį planetos.",
      },
    },
  },
  {
    id: "rec_wo_006",
    category: "records",
    subTheme: "world",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography — the Sahara is the largest hot desert",
    emoji: "🏜️",
    translations: {
      en: {
        question: "Which is the largest hot desert in the world?",
        correct: "The Sahara",
        distractors: ["The Gobi", "The Kalahari", "The Mojave", "The Arabian", "The Namib"],
        explanation: "The Sahara stretches across most of northern Africa.",
      },
      lt: {
        question: "Kuri didžiausia karšta dykuma pasaulyje?",
        correct: "Sachara",
        distractors: ["Gobis", "Kalaharis", "Mohavė", "Arabijos dykuma", "Namibas"],
        explanation: "Sachara driekiasi per didžiąją Šiaurės Afrikos dalį.",
      },
    },
  },
  {
    id: "rec_wo_007",
    category: "records",
    subTheme: "world",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Guinness — Angel Falls, tallest waterfall (979 m)",
    emoji: "💧",
    translations: {
      en: {
        question: "What is the tallest waterfall in the world?",
        correct: "Angel Falls",
        distractors: ["Niagara Falls", "Victoria Falls", "Iguazu Falls", "Yosemite Falls", "Rhine Falls"],
        explanation: "Angel Falls in Venezuela drops nearly 980 metres.",
      },
      lt: {
        question: "Koks aukščiausias krioklys pasaulyje?",
        correct: "Andželo krioklys",
        distractors: ["Niagaros krioklys", "Viktorijos krioklys", "Igvasų krioklys", "Josemičio krioklys", "Reino krioklys"],
        explanation: "Andželo krioklys Venesueloje krenta beveik 980 metrų.",
      },
    },
  },
  {
    id: "rec_wo_008",
    category: "records",
    subTheme: "world",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography — Greenland is the largest island (Australia is a continent)",
    emoji: "🏝️",
    translations: {
      en: {
        question: "Which is the largest island in the world?",
        correct: "Greenland",
        distractors: ["Madagascar", "Borneo", "New Guinea", "Iceland", "Great Britain"],
        explanation: "Greenland is the largest island; Australia counts as a continent.",
      },
      lt: {
        question: "Kuri didžiausia sala pasaulyje?",
        correct: "Grenlandija",
        distractors: ["Madagaskaras", "Borneo", "Naujoji Gvinėja", "Islandija", "Didžioji Britanija"],
        explanation: "Grenlandija — didžiausia sala; Australija laikoma žemynu.",
      },
    },
  },
  {
    id: "rec_wo_009",
    category: "records",
    subTheme: "world",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Geography — the Amazon is the largest rainforest",
    emoji: "🌳",
    translations: {
      en: {
        question: "Which is the largest rainforest on Earth?",
        correct: "The Amazon",
        distractors: ["The Congo", "Borneo forest", "The Taiga", "Daintree forest", "The Sundarbans"],
        explanation: "The Amazon rainforest is larger than most countries.",
      },
      lt: {
        question: "Koks didžiausias atogrąžų miškas Žemėje?",
        correct: "Amazonės miškas",
        distractors: ["Kongo miškas", "Borneo miškas", "Taiga", "Daintrio miškas", "Sundarbansas"],
        explanation: "Amazonės miškas didesnis už daugumą šalių.",
      },
    },
  },
  {
    id: "rec_wo_010",
    category: "records",
    subTheme: "world",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "History — the Great Wall of China is the longest wall ever built",
    emoji: "🧱",
    translations: {
      en: {
        question: "What is the longest wall ever built?",
        correct: "Great Wall of China",
        distractors: ["The Berlin Wall", "Hadrian's Wall", "Walls of Babylon", "The Western Wall", "Wall of Troy"],
        explanation: "The Great Wall of China stretches over 20,000 km in total.",
      },
      lt: {
        question: "Koks ilgiausias kada nors pastatytas mūras?",
        correct: "Kinijos siena",
        distractors: ["Berlyno siena", "Adriano siena", "Babilono sienos", "Vakarų siena", "Trojos siena"],
        explanation: "Kinijos siena iš viso driekiasi per daugiau nei 20 000 km.",
      },
    },
  },

  // ===================== VIDUTINIS (12–18 m.) =====================
  {
    id: "rec_wo_011",
    category: "records",
    subTheme: "world",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Oceanography — the Mariana Trench is the deepest ocean point",
    emoji: "🌊",
    translations: {
      en: {
        question: "What is the deepest known place in the ocean?",
        correct: "The Mariana Trench",
        distractors: ["The Tonga Trench", "The Java Trench", "The Puerto Rico Trench", "The Red Sea", "The Bermuda Triangle"],
        explanation: "The Mariana Trench reaches almost 11,000 metres down.",
      },
      lt: {
        question: "Kuri giliausia žinoma vieta vandenyne?",
        correct: "Marianos įduba",
        distractors: ["Tongos įduba", "Javos įduba", "Puerto Riko įduba", "Raudonoji jūra", "Bermudų trikampis"],
        explanation: "Marianos įduba siekia beveik 11 000 metrų gylį.",
      },
    },
  },
  {
    id: "rec_wo_012",
    category: "records",
    subTheme: "world",
    level: "vidutinis",
    isTrap: true,
    sourceVerified: "Geography — Antarctica is the largest desert overall (cold desert)",
    emoji: "🏜️",
    translations: {
      en: {
        question: "What is the largest desert of any kind on Earth?",
        correct: "Antarctica",
        distractors: ["The Sahara", "The Gobi", "The Arabian", "The Kalahari", "The Mojave"],
        explanation: "A desert just means very little rain — icy Antarctica is the biggest.",
      },
      lt: {
        question: "Kuri didžiausia bet kokios rūšies dykuma Žemėje?",
        correct: "Antarktida",
        distractors: ["Sachara", "Gobis", "Arabijos dykuma", "Kalaharis", "Mohavė"],
        explanation: "Dykuma reiškia labai mažai kritulių — ledinė Antarktida yra didžiausia.",
      },
    },
  },
  {
    id: "rec_wo_013",
    category: "records",
    subTheme: "world",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "WMO — Death Valley holds the officially recognized highest air temperature",
    emoji: "🌡️",
    translations: {
      en: {
        question: "Which place holds the record for the highest air temperature?",
        correct: "Death Valley",
        distractors: ["The Sahara", "Dubai", "Baghdad", "Cairo", "Kuwait City"],
        explanation: "Death Valley holds the official record, about 57 °C set in 1913.",
      },
      lt: {
        question: "Kuriai vietai priklauso aukščiausios oro temperatūros rekordas?",
        correct: "Mirties slėnis",
        distractors: ["Sachara", "Dubajus", "Bagdadas", "Kairas", "Kuveito miestas"],
        explanation: "Mirties slėnyje JAV užfiksuotas oficialus rekordas — apie 57 °C (1913 m.).",
      },
    },
  },
  {
    id: "rec_wo_014",
    category: "records",
    subTheme: "world",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Geography — Lake Baikal is the deepest lake (1,642 m)",
    emoji: "🏞️",
    translations: {
      en: {
        question: "Which is the deepest lake in the world?",
        correct: "Lake Baikal",
        distractors: ["Lake Tanganyika", "Caspian Sea", "Lake Superior", "Lake Victoria", "Crater Lake"],
        explanation: "Lake Baikal in Siberia plunges over 1,600 metres deep.",
      },
      lt: {
        question: "Kuris giliausias ežeras pasaulyje?",
        correct: "Baikalas",
        distractors: ["Tanganika", "Kaspijos jūra", "Aukštutinis ežeras", "Viktorijos ežeras", "Kraterio ežeras"],
        explanation: "Baikalas Sibire siekia daugiau nei 1 600 metrų gylį.",
      },
    },
  },
  {
    id: "rec_wo_015",
    category: "records",
    subTheme: "world",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "History — the Great Pyramid of Giza is the only surviving ancient wonder",
    emoji: "🏺",
    translations: {
      en: {
        question: "Which ancient wonder of the world is the only one still standing?",
        correct: "The Great Pyramid",
        distractors: ["The Hanging Gardens", "The Colossus of Rhodes", "The Lighthouse of Pharos", "The Statue of Zeus", "The Temple of Artemis"],
        explanation: "The Great Pyramid of Giza is the last ancient wonder left.",
      },
      lt: {
        question: "Kuris senovės pasaulio stebuklas vienintelis tebestovi?",
        correct: "Didžioji piramidė",
        distractors: ["Kabantieji sodai", "Rodo kolosas", "Faro švyturys", "Dzeuso statula", "Artemidės šventykla"],
        explanation: "Gizos Didžioji piramidė — paskutinis išlikęs senovės stebuklas.",
      },
    },
  },
  {
    id: "rec_wo_016",
    category: "records",
    subTheme: "world",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Guinness — Statue of Unity (India) is the tallest statue (182 m)",
    emoji: "🗽",
    translations: {
      en: {
        question: "The world's tallest statue stands in which country?",
        correct: "India",
        distractors: ["China", "The USA", "Brazil", "Egypt", "Russia"],
        explanation: "India's Statue of Unity rises 182 metres — twice the Statue of Liberty.",
      },
      lt: {
        question: "Kurioje šalyje stovi aukščiausia pasaulio statula?",
        correct: "Indijoje",
        distractors: ["Kinijoje", "JAV", "Brazilijoje", "Egipte", "Rusijoje"],
        explanation: "Indijos Vienybės statula siekia 182 m — dvigubai už Laisvės statulą.",
      },
    },
  },
  {
    id: "rec_wo_017",
    category: "records",
    subTheme: "world",
    level: "vidutinis",
    isTrap: true,
    sourceVerified: "Geography — Mauna Kea is tallest from base to peak (~10,210 m)",
    emoji: "🏔️",
    translations: {
      en: {
        question: "Measured from its base, which is the tallest mountain on Earth?",
        correct: "Mauna Kea",
        distractors: ["Mount Everest", "K2", "Kilimanjaro", "Mont Blanc", "Denali"],
        explanation: "Mauna Kea rises taller than Everest, but most of it is underwater.",
      },
      lt: {
        question: "Matuojant nuo pagrindo, koks aukščiausias kalnas Žemėje?",
        correct: "Mauna Kea",
        distractors: ["Everestas", "K2", "Kilimandžaras", "Monblanas", "Denalis"],
        explanation: "Mauna Kea aukštesnis už Everestą, bet didžioji dalis po vandeniu.",
      },
    },
  },
  {
    id: "rec_wo_018",
    category: "records",
    subTheme: "world",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Engineering — the world's longest bridge is in China (Danyang–Kunshan)",
    emoji: "🌉",
    translations: {
      en: {
        question: "The world's longest bridge was built in which country?",
        correct: "China",
        distractors: ["The USA", "Japan", "India", "Russia", "Brazil"],
        explanation: "China's Danyang–Kunshan bridge runs for about 165 km.",
      },
      lt: {
        question: "Kurioje šalyje pastatytas ilgiausias pasaulio tiltas?",
        correct: "Kinijoje",
        distractors: ["JAV", "Japonijoje", "Indijoje", "Rusijoje", "Brazilijoje"],
        explanation: "Kinijos Danjang–Kunšano tiltas tęsiasi apie 165 km.",
      },
    },
  },
  {
    id: "rec_wo_019",
    category: "records",
    subTheme: "world",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Geography — the Atacama is the driest non-polar desert",
    emoji: "🏜️",
    translations: {
      en: {
        question: "Which desert is known as the driest on Earth?",
        correct: "The Atacama",
        distractors: ["The Sahara", "The Gobi", "The Kalahari", "The Mojave", "The Namib"],
        explanation: "Parts of Chile's Atacama have gone years without any rain.",
      },
      lt: {
        question: "Kuri dykuma laikoma sausiausia Žemėje?",
        correct: "Atakama",
        distractors: ["Sachara", "Gobis", "Kalaharis", "Mohavė", "Namibas"],
        explanation: "Kai kuriose Čilės Atakamos vietose metų metus nelyja.",
      },
    },
  },
  {
    id: "rec_wo_020",
    category: "records",
    subTheme: "world",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Geography — the Andes are the longest mountain range on land",
    emoji: "⛰️",
    translations: {
      en: {
        question: "Which is the longest mountain range on land?",
        correct: "The Andes",
        distractors: ["The Himalayas", "The Rockies", "The Alps", "The Urals", "The Atlas"],
        explanation: "The Andes stretch about 7,000 km along South America.",
      },
      lt: {
        question: "Kuri ilgiausia kalnų grandinė sausumoje?",
        correct: "Andai",
        distractors: ["Himalajai", "Uoliniai kalnai", "Alpės", "Uralas", "Atlaso kalnai"],
        explanation: "Andai driekiasi apie 7 000 km išilgai Pietų Amerikos.",
      },
    },
  },

  // ===================== SUNKUS (suaugę) =====================
  {
    id: "rec_wo_021",
    category: "records",
    subTheme: "world",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Guinness — Burj Khalifa is 828 m tall",
    emoji: "📏",
    translations: {
      en: {
        question: "About how tall is the Burj Khalifa, the tallest building?",
        correct: "About 830 m",
        distractors: ["About 330 m", "About 550 m", "About 1,200 m", "About 200 m", "About 450 m"],
        explanation: "The Burj Khalifa stands 828 metres tall in Dubai.",
      },
      lt: {
        question: "Maždaug koks aukščiausio pastato Burdž Chalifos aukštis?",
        correct: "Apie 830 m",
        distractors: ["Apie 330 m", "Apie 550 m", "Apie 1 200 m", "Apie 200 m", "Apie 450 m"],
        explanation: "Burdž Chalifa Dubajuje yra 828 metrų aukščio.",
      },
    },
  },
  {
    id: "rec_wo_022",
    category: "records",
    subTheme: "world",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Geography — Mount Everest is 8,849 m above sea level",
    emoji: "🏔️",
    translations: {
      en: {
        question: "How high is Mount Everest above sea level?",
        correct: "About 8,849 m",
        distractors: ["About 8,611 m", "About 7,500 m", "About 9,200 m", "About 8,000 m", "About 6,500 m"],
        explanation: "Everest's summit sits 8,849 metres above the sea.",
      },
      lt: {
        question: "Koks Everesto aukštis virš jūros lygio?",
        correct: "Apie 8 849 m",
        distractors: ["Apie 8 611 m", "Apie 7 500 m", "Apie 9 200 m", "Apie 8 000 m", "Apie 6 500 m"],
        explanation: "Everesto viršūnė yra 8 849 metrų virš jūros lygio.",
      },
    },
  },
  {
    id: "rec_wo_023",
    category: "records",
    subTheme: "world",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Oceanography — the Mariana Trench is about 11 km deep",
    emoji: "🌊",
    translations: {
      en: {
        question: "About how deep is the Mariana Trench, the ocean's deepest point?",
        correct: "About 11 km",
        distractors: ["About 3 km", "About 5 km", "About 8 km", "About 15 km", "About 20 km"],
        explanation: "Its deepest spot lies almost 11 km below the surface.",
      },
      lt: {
        question: "Maždaug koks giliausios vandenyno vietos, Marianos įdubos, gylis?",
        correct: "Apie 11 km",
        distractors: ["Apie 3 km", "Apie 5 km", "Apie 8 km", "Apie 15 km", "Apie 20 km"],
        explanation: "Giliausia jos vieta — beveik 11 km po vandeniu.",
      },
    },
  },
  {
    id: "rec_wo_024",
    category: "records",
    subTheme: "world",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Geography — Russia's area is about 17 million km²",
    emoji: "🗺️",
    translations: {
      en: {
        question: "About how large is Russia, the world's biggest country?",
        correct: "About 17 million km²",
        distractors: ["About 5 million km²", "About 10 million km²", "About 25 million km²", "About 50 million km²", "About 2 million km²"],
        explanation: "Russia covers around 17 million square kilometres.",
      },
      lt: {
        question: "Maždaug koks didžiausios šalies Rusijos plotas?",
        correct: "Apie 17 mln. km²",
        distractors: ["Apie 5 mln. km²", "Apie 10 mln. km²", "Apie 25 mln. km²", "Apie 50 mln. km²", "Apie 2 mln. km²"],
        explanation: "Rusija užima apie 17 milijonų kvadratinių kilometrų.",
      },
    },
  },
  {
    id: "rec_wo_025",
    category: "records",
    subTheme: "world",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Guinness — Angel Falls is about 979 m tall",
    emoji: "💧",
    translations: {
      en: {
        question: "About how tall is Angel Falls, the highest waterfall?",
        correct: "About 980 m",
        distractors: ["About 180 m", "About 500 m", "About 1,500 m", "About 300 m", "About 700 m"],
        explanation: "Angel Falls drops about 979 metres in Venezuela.",
      },
      lt: {
        question: "Kiek metrų krenta aukščiausias pasaulio krioklys Andželas?",
        correct: "Apie 980 m",
        distractors: ["Apie 180 m", "Apie 500 m", "Apie 1 500 m", "Apie 300 m", "Apie 700 m"],
        explanation: "Andželo krioklys Venesueloje yra apie 979 metrų aukščio.",
      },
    },
  },
  {
    id: "rec_wo_026",
    category: "records",
    subTheme: "world",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Geography — the Atacama Desert is in Chile",
    emoji: "🏜️",
    translations: {
      en: {
        question: "In which country is the Atacama, the driest desert?",
        correct: "Chile",
        distractors: ["Peru", "Mexico", "Egypt", "Namibia", "Australia"],
        explanation: "The Atacama runs along the Pacific coast of Chile.",
      },
      lt: {
        question: "Kurioje šalyje yra sausiausia dykuma Atakama?",
        correct: "Čilėje",
        distractors: ["Peru", "Meksikoje", "Egipte", "Namibijoje", "Australijoje"],
        explanation: "Atakama driekiasi Čilės Ramiojo vandenyno pakrante.",
      },
    },
  },
  {
    id: "rec_wo_027",
    category: "records",
    subTheme: "world",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Geography — Greenland is an autonomous territory of Denmark",
    emoji: "🏝️",
    translations: {
      en: {
        question: "The largest island, Greenland, belongs to which country?",
        correct: "Denmark",
        distractors: ["Canada", "Norway", "Iceland", "Sweden", "Finland"],
        explanation: "Greenland is a self-governing territory of Denmark.",
      },
      lt: {
        question: "Kuriai šaliai priklauso didžiausia sala Grenlandija?",
        correct: "Danijai",
        distractors: ["Kanadai", "Norvegijai", "Islandijai", "Švedijai", "Suomijai"],
        explanation: "Grenlandija — savivaldi Danijos teritorija.",
      },
    },
  },
  {
    id: "rec_wo_028",
    category: "records",
    subTheme: "world",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Geography — Lake Superior is the largest freshwater lake by area",
    emoji: "🏞️",
    translations: {
      en: {
        question: "Which is the largest freshwater lake by surface area?",
        correct: "Lake Superior",
        distractors: ["Lake Baikal", "Lake Victoria", "Lake Huron", "Lake Michigan", "Lake Tanganyika"],
        explanation: "Lake Superior in North America has the biggest freshwater surface.",
      },
      lt: {
        question: "Kuris didžiausias gėlavandenis ežeras pagal plotą?",
        correct: "Aukštutinis ežeras",
        distractors: ["Baikalas", "Viktorijos ežeras", "Hurono ežeras", "Mičigano ežeras", "Tanganika"],
        explanation: "Aukštutinis ežeras Šiaurės Amerikoje turi didžiausią gėlo vandens plotą.",
      },
    },
  },
  {
    id: "rec_wo_029",
    category: "records",
    subTheme: "world",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Geography — the Dead Sea shore is the lowest dry land on Earth",
    emoji: "🗺️",
    translations: {
      en: {
        question: "Which place is the lowest dry land on Earth?",
        correct: "The Dead Sea shore",
        distractors: ["Death Valley", "The Caspian shore", "The Sahara", "The Grand Canyon", "The Turpan Depression"],
        explanation: "The Dead Sea shore lies about 430 metres below sea level.",
      },
      lt: {
        question: "Kuri vieta yra žemiausia sausuma Žemėje?",
        correct: "Negyvosios jūros krantas",
        distractors: ["Mirties slėnis", "Kaspijos jūros krantas", "Sachara", "Didysis kanjonas", "Turfano įduba"],
        explanation: "Negyvosios jūros krantas yra apie 430 metrų žemiau jūros lygio.",
      },
    },
  },
  {
    id: "rec_wo_030",
    category: "records",
    subTheme: "world",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Geography — the Caspian Sea is the largest lake by area",
    emoji: "🌊",
    translations: {
      en: {
        question: "Which is the largest lake in the world by surface area?",
        correct: "The Caspian Sea",
        distractors: ["Lake Superior", "Lake Baikal", "Lake Victoria", "Lake Huron", "Lake Michigan"],
        explanation: "Despite its name, the Caspian Sea is the world's biggest lake.",
      },
      lt: {
        question: "Kuris didžiausias pasaulio ežeras pagal plotą?",
        correct: "Kaspijos jūra",
        distractors: ["Aukštutinis ežeras", "Baikalas", "Viktorijos ežeras", "Hurono ežeras", "Mičigano ežeras"],
        explanation: "Nepaisant pavadinimo, Kaspijos jūra yra didžiausias pasaulio ežeras.",
      },
    },
  },

  // ===================== EKSTREMALUS (žinovai) =====================
  {
    id: "rec_wo_031",
    category: "records",
    subTheme: "world",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "WMO — highest officially recognized air temperature 56.7 °C (Death Valley, 1913)",
    emoji: "🌡️",
    translations: {
      en: {
        question: "What is the highest air temperature ever reliably recorded?",
        correct: "About 57 °C",
        distractors: ["About 40 °C", "About 47 °C", "About 70 °C", "About 90 °C", "About 35 °C"],
        explanation: "Death Valley hit 56.7 °C (134 °F) in July 1913.",
      },
      lt: {
        question: "Kokia aukščiausia patikimai užfiksuota oro temperatūra?",
        correct: "Apie 57 °C",
        distractors: ["Apie 40 °C", "Apie 47 °C", "Apie 70 °C", "Apie 90 °C", "Apie 35 °C"],
        explanation: "Mirties slėnyje 1913 m. liepą buvo 56,7 °C.",
      },
    },
  },
  {
    id: "rec_wo_032",
    category: "records",
    subTheme: "world",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Meteorology — lowest natural temperature -89.2 °C (Vostok, 1983)",
    emoji: "🌡️",
    translations: {
      en: {
        question: "What is the lowest natural air temperature ever recorded?",
        correct: "About -89 °C",
        distractors: ["About -40 °C", "About -60 °C", "About -120 °C", "About -200 °C", "About -30 °C"],
        explanation: "Russia's Vostok Station in Antarctica logged -89.2 °C in 1983.",
      },
      lt: {
        question: "Kokia žemiausia kada nors užfiksuota natūrali oro temperatūra?",
        correct: "Apie -89 °C",
        distractors: ["Apie -40 °C", "Apie -60 °C", "Apie -120 °C", "Apie -200 °C", "Apie -30 °C"],
        explanation: "Vostoko stotis Antarktidoje 1983 m. užfiksavo -89,2 °C.",
      },
    },
  },
  {
    id: "rec_wo_033",
    category: "records",
    subTheme: "world",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Oceanography — Challenger Deep is the deepest point of the Mariana Trench",
    emoji: "🌊",
    translations: {
      en: {
        question: "What is the name of the single deepest point in the Mariana Trench?",
        correct: "Challenger Deep",
        distractors: ["Brownson Deep", "Horizon Deep", "Galathea Depth", "Meteor Deep", "Vityaz Deep"],
        explanation: "Challenger Deep sits almost 11 km below the surface.",
      },
      lt: {
        question: "Kaip vadinama giliausia Marianos įdubos vieta?",
        correct: "Challenger Deep",
        distractors: ["Brownson Deep", "Horizon Deep", "Galathea gelmė", "Meteor Deep", "Vityaz Deep"],
        explanation: "Challenger Deep yra beveik 11 km po vandens paviršiumi.",
      },
    },
  },
  {
    id: "rec_wo_034",
    category: "records",
    subTheme: "world",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography — Mauna Kea is about 10,210 m from base to peak",
    emoji: "🌋",
    translations: {
      en: {
        question: "Measured from its seafloor base, how tall is Mauna Kea?",
        correct: "About 10 km",
        distractors: ["About 4 km", "About 6 km", "About 8 km", "About 15 km", "About 20 km"],
        explanation: "From base to peak Mauna Kea is over 10 km — taller than Everest.",
      },
      lt: {
        question: "Matuojant nuo pagrindo jūros dugne, koks yra Mauna Kea aukštis?",
        correct: "Apie 10 km",
        distractors: ["Apie 4 km", "Apie 6 km", "Apie 8 km", "Apie 15 km", "Apie 20 km"],
        explanation: "Nuo pagrindo iki viršūnės Mauna Kea aukštesnis nei 10 km — aukštesnis už Everestą.",
      },
    },
  },
  {
    id: "rec_wo_035",
    category: "records",
    subTheme: "world",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography — K2 is the second-highest mountain (8,611 m)",
    emoji: "⛰️",
    translations: {
      en: {
        question: "How tall is K2, the world's second-highest mountain?",
        correct: "About 8,600 m",
        distractors: ["About 8,849 m", "About 7,200 m", "About 9,000 m", "About 6,500 m", "About 8,000 m"],
        explanation: "K2 reaches 8,611 metres, just below Everest.",
      },
      lt: {
        question: "Kokio aukščio yra K2 — antras pagal aukštį pasaulio kalnas?",
        correct: "Apie 8 600 m",
        distractors: ["Apie 8 849 m", "Apie 7 200 m", "Apie 9 000 m", "Apie 6 500 m", "Apie 8 000 m"],
        explanation: "K2 siekia 8 611 metrų, vos žemiau už Everestą.",
      },
    },
  },
  {
    id: "rec_wo_036",
    category: "records",
    subTheme: "world",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography — the Dead Sea is about 430 m below sea level",
    emoji: "📏",
    translations: {
      en: {
        question: "About how far below sea level is the shore of the Dead Sea?",
        correct: "About 430 m",
        distractors: ["About 50 m", "About 150 m", "About 1,000 m", "About 250 m", "About 700 m"],
        explanation: "The Dead Sea shore is the lowest exposed land, ~430 m down.",
      },
      lt: {
        question: "Maždaug kiek žemiau jūros lygio yra Negyvosios jūros krantas?",
        correct: "Apie 430 m",
        distractors: ["Apie 50 m", "Apie 150 m", "Apie 1 000 m", "Apie 250 m", "Apie 700 m"],
        explanation: "Negyvosios jūros krantas — žemiausia atvira sausuma, apie 430 m žemyn.",
      },
    },
  },
  {
    id: "rec_wo_037",
    category: "records",
    subTheme: "world",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography — Lake Baikal is about 1,642 m deep",
    emoji: "🏞️",
    translations: {
      en: {
        question: "About how deep is Lake Baikal, the deepest lake?",
        correct: "About 1,600 m",
        distractors: ["About 300 m", "About 700 m", "About 3,000 m", "About 500 m", "About 5,000 m"],
        explanation: "Lake Baikal reaches around 1,642 metres at its deepest.",
      },
      lt: {
        question: "Maždaug koks giliausio ežero Baikalo gylis?",
        correct: "Apie 1 600 m",
        distractors: ["Apie 300 m", "Apie 700 m", "Apie 3 000 m", "Apie 500 m", "Apie 5 000 m"],
        explanation: "Giliausioje vietoje Baikalas siekia apie 1 642 metrus.",
      },
    },
  },
  {
    id: "rec_wo_038",
    category: "records",
    subTheme: "world",
    level: "ekstremalus",
    isTrap: true,
    sourceVerified: "Geography — the mid-ocean ridge is the longest mountain range overall",
    emoji: "🏔️",
    translations: {
      en: {
        question: "Including underwater, which is the longest mountain range on Earth?",
        correct: "The mid-ocean ridge",
        distractors: ["The Andes", "The Himalayas", "The Scandinavian Mountains", "The Atlas range", "The Ural range"],
        explanation: "The underwater mid-ocean ridge winds about 65,000 km around the globe.",
      },
      lt: {
        question: "Įskaitant povandenines, kuri ilgiausia kalnų grandinė Žemėje?",
        correct: "Vandenynų kalnagūbris",
        distractors: ["Andai", "Himalajai", "Skandinavijos kalnai", "Atlaso kalnai", "Uralo kalnai"],
        explanation: "Povandeninis vandenynų kalnagūbris vingiuoja apie 65 000 km aplink Žemę.",
      },
    },
  },
  {
    id: "rec_wo_039",
    category: "records",
    subTheme: "world",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Geography — the Sahara (~9.2M km²) is roughly the size of the USA",
    emoji: "🏜️",
    translations: {
      en: {
        question: "The Sahara desert is roughly as large as which country?",
        correct: "The USA",
        distractors: ["Italy", "France", "Japan", "The UK", "Spain"],
        explanation: "The Sahara covers about 9 million km² — nearly the size of the USA.",
      },
      lt: {
        question: "Sacharos dykuma yra maždaug tokio dydžio kaip kuri šalis?",
        correct: "JAV",
        distractors: ["Italija", "Prancūzija", "Japonija", "Jungtinė Karalystė", "Ispanija"],
        explanation: "Sachara užima apie 9 milijonus km² — beveik kaip visa JAV.",
      },
    },
  },
  {
    id: "rec_wo_040",
    category: "records",
    subTheme: "world",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Guinness — Burj Khalifa has 163 usable floors",
    emoji: "🏢",
    translations: {
      en: {
        question: "About how many floors does the Burj Khalifa have?",
        correct: "About 160 floors",
        distractors: ["About 50 floors", "About 80 floors", "About 300 floors", "About 100 floors", "About 500 floors"],
        explanation: "The Burj Khalifa has 163 usable floors above ground.",
      },
      lt: {
        question: "Maždaug kiek aukštų turi Burdž Chalifa?",
        correct: "Apie 160 aukštų",
        distractors: ["Apie 50 aukštų", "Apie 80 aukštų", "Apie 300 aukštų", "Apie 100 aukštų", "Apie 500 aukštų"],
        explanation: "Burdž Chalifa virš žemės turi 163 naudojamus aukštus.",
      },
    },
  },
];
