/**
 * sportContent — „Sportas” trivijos klausimai (EN + LT).
 *
 * Po 15 klausimų kiekvienam lygiui (lengvas/vidutinis/sunkus/ekstremalus) = 60.
 * Temos: olimpinės žaidynės, populiarūs sportai, taisyklės, istoriniai faktai.
 * Vengiame greitai senstančių faktų (dabartiniai čempionai) — tik tvarūs faktai.
 *
 * TAISYKLĖS (Manifestas):
 *   - 1 teisingas + 5 distractors; visi 6 variantai VISOSE kalbose ≤46 simbolių;
 *   - faktai 100% patikrinti (sourceVerified); neutralu (jokios politikos/religijos);
 *   - LT vidinės kabutės tik „...” (ne ASCII "); detalės — į explanation, ne į variantą.
 *
 * Formatas — žr. triviaTypes.ts (TriviaQuestion). category visada "sport".
 */

import { TriviaQuestion } from "./triviaTypes";

export const SPORT_QUESTIONS: TriviaQuestion[] = [
  // ======================= LENGVAS (Easy) =======================
  {
    id: "spo_le_001",
    category: "sport",
    subTheme: "rules",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Football basics (11 players)",
    emoji: "⚽",
    translations: {
      en: {
        question: "How many players are on a football (soccer) team on the field?",
        correct: "11",
        distractors: ["9", "10", "12", "5", "7"],
        explanation: "A football team fields 11 players including the keeper.",
      },
      lt: {
        question: "Kiek žaidėjų aikštėje turi futbolo komanda?",
        correct: "11",
        distractors: ["9", "10", "12", "5", "7"],
        explanation: "Futbolo komandoje aikštėje 11 žaidėjų su vartininku.",
      },
    },
  },
  {
    id: "spo_le_002",
    category: "sport",
    subTheme: "equipment",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Basketball basics (hoop)",
    emoji: "🏀",
    translations: {
      en: {
        question: "In basketball, you score by putting the ball where?",
        correct: "Through the hoop",
        distractors: ["In a net goal", "Over a bar", "In a hole", "Past a line", "Into a box"],
        explanation: "Points are scored by shooting through the hoop.",
      },
      lt: {
        question: "Kur įmetus kamuolį krepšinyje pelnomi taškai?",
        correct: "Pro krepšį",
        distractors: ["Į vartus", "Virš kartelės", "Į duobutę", "Už linijos", "Į dėžę"],
        explanation: "Taškai pelnomi įmetus kamuolį pro krepšį.",
      },
    },
  },
  {
    id: "spo_le_003",
    category: "sport",
    subTheme: "olympics",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Olympic symbol (five rings)",
    emoji: "🏅",
    translations: {
      en: {
        question: "How many rings are on the Olympic flag?",
        correct: "5",
        distractors: ["3", "4", "6", "7", "8"],
        explanation: "The Olympic flag has five interlocking rings.",
      },
      lt: {
        question: "Kiek žiedų yra olimpinėje vėliavoje?",
        correct: "5",
        distractors: ["3", "4", "6", "7", "8"],
        explanation: "Olimpinėje vėliavoje yra penki susikabinę žiedai.",
      },
    },
  },
  {
    id: "spo_le_004",
    category: "sport",
    subTheme: "equipment",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Tennis basics (racket)",
    emoji: "🎾",
    translations: {
      en: {
        question: "Which tool do you use to hit a tennis ball?",
        correct: "Racket",
        distractors: ["Bat", "Club", "Stick", "Paddle", "Cue"],
        explanation: "Tennis is played with a stringed racket.",
      },
      lt: {
        question: "Kuo mušamas teniso kamuoliukas?",
        correct: "Rakete",
        distractors: ["Lazda", "Vėzdu", "Pagaliuku", "Mentele", "Kiju"],
        explanation: "Tenisas žaidžiamas su rakete.",
      },
    },
  },
  {
    id: "spo_le_005",
    category: "sport",
    subTheme: "rules",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Football scoring (goal)",
    emoji: "🥅",
    translations: {
      en: {
        question: "In football, scoring is called what?",
        correct: "A goal",
        distractors: ["A point", "A run", "A basket", "A try", "A touchdown"],
        explanation: "Putting the ball in the net is called a goal.",
      },
      lt: {
        question: "Kaip futbole vadinamas pelnytas taškas?",
        correct: "Įvartis",
        distractors: ["Taškas", "Perbėgimas", "Metimas", "Bandymas", "Smūgis"],
        explanation: "Kamuolio įmušimas į vartus vadinamas įvarčiu.",
      },
    },
  },
  {
    id: "spo_le_006",
    category: "sport",
    subTheme: "sports",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Swimming basics (water sport)",
    emoji: "🏊",
    translations: {
      en: {
        question: "Which sport takes place in a pool?",
        correct: "Swimming",
        distractors: ["Cycling", "Boxing", "Archery", "Skiing", "Fencing"],
        explanation: "Swimming races are held in pools.",
      },
      lt: {
        question: "Kuri sporto šaka vyksta baseine?",
        correct: "Plaukimas",
        distractors: ["Dviračiai", "Boksas", "Šaudymas iš lanko", "Slidinėjimas", "Fechtavimas"],
        explanation: "Plaukimo varžybos vyksta baseinuose.",
      },
    },
  },
  {
    id: "spo_le_007",
    category: "sport",
    subTheme: "equipment",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Golf basics (hole)",
    emoji: "⛳",
    translations: {
      en: {
        question: "In golf, you hit the ball into a what?",
        correct: "Hole",
        distractors: ["Net", "Basket", "Goal", "Pocket", "Ring"],
        explanation: "Golfers aim to hit the ball into holes.",
      },
      lt: {
        question: "Į ką golfe varomas kamuoliukas?",
        correct: "Duobutę",
        distractors: ["Tinklą", "Krepšį", "Vartus", "Kišenę", "Žiedą"],
        explanation: "Golfo tikslas — įvaryti kamuoliuką į duobutes.",
      },
    },
  },
  {
    id: "spo_le_008",
    category: "sport",
    subTheme: "sports",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Cycling basics (bicycle)",
    emoji: "🚴",
    translations: {
      en: {
        question: "Which sport uses a bicycle?",
        correct: "Cycling",
        distractors: ["Rowing", "Boxing", "Diving", "Wrestling", "Sailing"],
        explanation: "Cycling is racing on bicycles.",
      },
      lt: {
        question: "Kurioje sporto šakoje varžomasi dviračiais?",
        correct: "Dviračių sportas",
        distractors: ["Irklavimas", "Boksas", "Šuoliai į vandenį", "Imtynės", "Buriavimas"],
        explanation: "Dviračių sportas — lenktynės dviračiais.",
      },
    },
  },
  {
    id: "spo_le_009",
    category: "sport",
    subTheme: "rules",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Boxing basics (ring)",
    emoji: "🥊",
    translations: {
      en: {
        question: "Where does a boxing match take place?",
        correct: "A ring",
        distractors: ["A court", "A pitch", "A track", "A pool", "A rink"],
        explanation: "Boxers compete inside a square ring.",
      },
      lt: {
        question: "Kur vyksta bokso kova?",
        correct: "Ringe",
        distractors: ["Aikštelėje", "Aikštėje", "Bėgimo take", "Baseine", "Čiuožykloje"],
        explanation: "Boksininkai kaunasi kvadratiniame ringe.",
      },
    },
  },
  {
    id: "spo_le_010",
    category: "sport",
    subTheme: "sports",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Ice hockey basics (puck)",
    emoji: "🏒",
    translations: {
      en: {
        question: "In ice hockey, players hit a what?",
        correct: "Puck",
        distractors: ["Ball", "Shuttle", "Disc of clay", "Ring", "Cone"],
        explanation: "Ice hockey is played with a rubber puck.",
      },
      lt: {
        question: "Ką muša ledo ritulio žaidėjai?",
        correct: "Ritulį",
        distractors: ["Kamuolį", "Plunksniuką", "Molio diską", "Žiedą", "Kūgį"],
        explanation: "Ledo ritulys žaidžiamas guminiu rituliu.",
      },
    },
  },
  {
    id: "spo_le_011",
    category: "sport",
    subTheme: "rules",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Marathon distance (about 42 km)",
    emoji: "🏃",
    translations: {
      en: {
        question: "A marathon is roughly how many kilometers?",
        correct: "42",
        distractors: ["10", "21", "30", "50", "100"],
        explanation: "A marathon is about 42.2 kilometers.",
      },
      lt: {
        question: "Kiek maždaug kilometrų yra maratonas?",
        correct: "42",
        distractors: ["10", "21", "30", "50", "100"],
        explanation: "Maratonas yra apie 42,2 kilometro.",
      },
    },
  },
  {
    id: "spo_le_012",
    category: "sport",
    subTheme: "equipment",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Baseball basics (bat)",
    emoji: "⚾",
    translations: {
      en: {
        question: "In baseball, what is used to hit the ball?",
        correct: "Bat",
        distractors: ["Racket", "Club", "Stick", "Paddle", "Cue"],
        explanation: "Baseball batters swing a wooden or metal bat.",
      },
      lt: {
        question: "Kuo beisbole mušamas kamuolys?",
        correct: "Lazda",
        distractors: ["Rakete", "Vėzdu", "Pagaliuku", "Mentele", "Kiju"],
        explanation: "Beisbolo mušėjai naudoja medinę ar metalinę lazdą.",
      },
    },
  },
  {
    id: "spo_le_013",
    category: "sport",
    subTheme: "sports",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Skiing basics (snow sport)",
    emoji: "⛷️",
    translations: {
      en: {
        question: "Skiing is usually done on what surface?",
        correct: "Snow",
        distractors: ["Sand", "Water", "Grass", "Ice rink", "Clay"],
        explanation: "Alpine skiing is done on snowy slopes.",
      },
      lt: {
        question: "Ant kokio paviršiaus dažniausiai slidinėjama?",
        correct: "Sniego",
        distractors: ["Smėlio", "Vandens", "Žolės", "Ledo", "Molio"],
        explanation: "Kalnų slidinėjimas vyksta apsnigtais šlaitais.",
      },
    },
  },
  {
    id: "spo_le_014",
    category: "sport",
    subTheme: "rules",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Football match halves (two)",
    emoji: "⏱️",
    translations: {
      en: {
        question: "A football match is split into how many halves?",
        correct: "2",
        distractors: ["3", "4", "1", "5", "6"],
        explanation: "Football has two halves of 45 minutes.",
      },
      lt: {
        question: "Į kiek kėlinių dalijamos futbolo rungtynės?",
        correct: "2",
        distractors: ["3", "4", "1", "5", "6"],
        explanation: "Futbole yra du 45 minučių kėliniai.",
      },
    },
  },
  {
    id: "spo_le_015",
    category: "sport",
    subTheme: "sports",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Volleyball basics (net)",
    emoji: "🏐",
    translations: {
      en: {
        question: "Volleyball is played over a what?",
        correct: "Net",
        distractors: ["Wall", "Goal", "Bar", "Fence", "Rope ring"],
        explanation: "Volleyball teams hit the ball over a high net.",
      },
      lt: {
        question: "Per ką žaidžiamas tinklinis?",
        correct: "Tinklą",
        distractors: ["Sieną", "Vartus", "Kartelę", "Tvorą", "Žiedą"],
        explanation: "Tinklinio komandos muša kamuolį per aukštą tinklą.",
      },
    },
  },

  // ======================= VIDUTINIS (Medium) =======================
  {
    id: "spo_me_001",
    category: "sport",
    subTheme: "olympics",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Olympic history (Athens 1896)",
    emoji: "🏛️",
    translations: {
      en: {
        question: "The first modern Olympics in 1896 were held in which city?",
        correct: "Athens",
        distractors: ["Paris", "London", "Rome", "Berlin", "Stockholm"],
        explanation: "The first modern Olympic Games were in Athens, 1896.",
      },
      lt: {
        question: "Kuriame mieste vyko pirmosios moderniosios olimpinės 1896 m.?",
        correct: "Atėnai",
        distractors: ["Paryžius", "Londonas", "Roma", "Berlynas", "Stokholmas"],
        explanation: "Pirmosios moderniosios olimpinės vyko Atėnuose, 1896 m.",
      },
    },
  },
  {
    id: "spo_me_002",
    category: "sport",
    subTheme: "rules",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Basketball scoring (free throw = 1)",
    emoji: "🏀",
    translations: {
      en: {
        question: "How many points is a basketball free throw worth?",
        correct: "1",
        distractors: ["2", "3", "4", "5", "0"],
        explanation: "A made free throw is worth one point.",
      },
      lt: {
        question: "Kiek taškų krepšinyje vertas baudos metimas?",
        correct: "1",
        distractors: ["2", "3", "4", "5", "0"],
        explanation: "Pataikytas baudos metimas vertas vieno taško.",
      },
    },
  },
  {
    id: "spo_me_003",
    category: "sport",
    subTheme: "tennis",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Tennis venue (Wimbledon, London)",
    emoji: "🎾",
    translations: {
      en: {
        question: "The Wimbledon tennis tournament is held in which country?",
        correct: "England",
        distractors: ["France", "USA", "Australia", "Spain", "Germany"],
        explanation: "Wimbledon is played in London, England.",
      },
      lt: {
        question: "Kurioje šalyje vyksta Vimbldono teniso turnyras?",
        correct: "Anglija",
        distractors: ["Prancūzija", "JAV", "Australija", "Ispanija", "Vokietija"],
        explanation: "Vimbldonas žaidžiamas Londone, Anglijoje.",
      },
    },
  },
  {
    id: "spo_me_004",
    category: "sport",
    subTheme: "football",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "FIFA World Cup frequency (every 4 years)",
    emoji: "🏆",
    translations: {
      en: {
        question: "How often is the FIFA World Cup normally held?",
        correct: "Every 4 years",
        distractors: ["Every year", "Every 2 years", "Every 3 years", "Every 5 years", "Every 6 years"],
        explanation: "The World Cup is held every four years.",
      },
      lt: {
        question: "Kas kiek paprastai vyksta FIFA pasaulio futbolo čempionatas?",
        correct: "Kas 4 metus",
        distractors: ["Kasmet", "Kas 2 metus", "Kas 3 metus", "Kas 5 metus", "Kas 6 metus"],
        explanation: "Pasaulio čempionatas vyksta kas ketverius metus.",
      },
    },
  },
  {
    id: "spo_me_005",
    category: "sport",
    subTheme: "rules",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Rugby team size (15)",
    emoji: "🏉",
    translations: {
      en: {
        question: "How many players are in a rugby union team on the field?",
        correct: "15",
        distractors: ["11", "13", "12", "9", "7"],
        explanation: "Rugby union teams field 15 players.",
      },
      lt: {
        question: "Kiek žaidėjų aikštėje turi regbio komanda?",
        correct: "15",
        distractors: ["11", "13", "12", "9", "7"],
        explanation: "Regbio (union) komandoje aikštėje 15 žaidėjų.",
      },
    },
  },
  {
    id: "spo_me_006",
    category: "sport",
    subTheme: "olympics",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Olympic medals order (gold first)",
    emoji: "🥇",
    translations: {
      en: {
        question: "Which Olympic medal is awarded for first place?",
        correct: "Gold",
        distractors: ["Silver", "Bronze", "Platinum", "Diamond", "Copper"],
        explanation: "First place earns the gold medal.",
      },
      lt: {
        question: "Kuris olimpinis medalis skiriamas už pirmą vietą?",
        correct: "Auksas",
        distractors: ["Sidabras", "Bronza", "Platina", "Deimantas", "Varis"],
        explanation: "Už pirmą vietą skiriamas aukso medalis.",
      },
    },
  },
  {
    id: "spo_me_007",
    category: "sport",
    subTheme: "sports",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Badminton equipment (shuttlecock)",
    emoji: "🏸",
    translations: {
      en: {
        question: "Badminton is played by hitting a what?",
        correct: "Shuttlecock",
        distractors: ["Ball", "Puck", "Ring", "Disc", "Cork ball"],
        explanation: "Badminton uses a feathered shuttlecock.",
      },
      lt: {
        question: "Ką muša badmintono žaidėjai?",
        correct: "Plunksniuką",
        distractors: ["Kamuolį", "Ritulį", "Žiedą", "Diską", "Kamštį"],
        explanation: "Badmintone naudojamas plunksnuotas plunksniukas.",
      },
    },
  },
  {
    id: "spo_me_008",
    category: "sport",
    subTheme: "football",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Football card (red = sent off)",
    emoji: "🟥",
    translations: {
      en: {
        question: "Which card sends a football player off the field?",
        correct: "Red card",
        distractors: ["Yellow card", "Blue card", "Green card", "Black card", "White card"],
        explanation: "A red card means the player is sent off.",
      },
      lt: {
        question: "Kuri kortelė pašalina futbolininką iš aikštės?",
        correct: "Raudona kortelė",
        distractors: ["Geltona kortelė", "Mėlyna kortelė", "Žalia kortelė", "Juoda kortelė", "Balta kortelė"],
        explanation: "Raudona kortelė reiškia žaidėjo pašalinimą.",
      },
    },
  },
  {
    id: "spo_me_009",
    category: "sport",
    subTheme: "sports",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Formula 1 (motor racing)",
    emoji: "🏎️",
    translations: {
      en: {
        question: "Formula 1 is a top level of what sport?",
        correct: "Car racing",
        distractors: ["Cycling", "Sailing", "Horse racing", "Running", "Rowing"],
        explanation: "Formula 1 is elite open-wheel car racing.",
      },
      lt: {
        question: "Formulė 1 yra aukščiausias kurio sporto lygis?",
        correct: "Automobilių lenktynės",
        distractors: ["Dviračių", "Buriavimo", "Žirgų lenktynių", "Bėgimo", "Irklavimo"],
        explanation: "Formulė 1 — elitinės atvirų ratų automobilių lenktynės.",
      },
    },
  },
  {
    id: "spo_me_010",
    category: "sport",
    subTheme: "rules",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Tennis scoring (love = 0)",
    emoji: "🎾",
    translations: {
      en: {
        question: "In tennis, the term love means what score?",
        correct: "Zero",
        distractors: ["One", "Fifteen", "Forty", "Match point", "Deuce"],
        explanation: "In tennis, love means a score of zero.",
      },
      lt: {
        question: "Ką tenise reiškia terminas „love”?",
        correct: "Nulį",
        distractors: ["Vieną", "Penkiolika", "Keturiasdešimt", "Mečbolą", "Lygiąsias"],
        explanation: "Tenise „love” reiškia nulinį rezultatą.",
      },
    },
  },
  {
    id: "spo_me_011",
    category: "sport",
    subTheme: "olympics",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Winter Olympics sports (figure skating)",
    emoji: "⛸️",
    translations: {
      en: {
        question: "Which of these is a Winter Olympic sport?",
        correct: "Figure skating",
        distractors: ["Beach volleyball", "Surfing", "Rowing", "Field hockey", "Water polo"],
        explanation: "Figure skating is a Winter Olympic event.",
      },
      lt: {
        question: "Kuris iš šių yra žiemos olimpinis sportas?",
        correct: "Dailusis čiuožimas",
        distractors: ["Paplūdimio tinklinis", "Banglentės", "Irklavimas", "Žolės riedulys", "Vandensvydis"],
        explanation: "Dailusis čiuožimas — žiemos olimpinė šaka.",
      },
    },
  },
  {
    id: "spo_me_012",
    category: "sport",
    subTheme: "basketball",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Basketball origin (USA, Naismith)",
    emoji: "🏀",
    translations: {
      en: {
        question: "In which country was basketball invented?",
        correct: "USA",
        distractors: ["Canada", "England", "France", "Spain", "Italy"],
        explanation: "Basketball was invented in the USA in 1891.",
      },
      lt: {
        question: "Kurioje šalyje sukurtas krepšinis?",
        correct: "JAV",
        distractors: ["Kanada", "Anglija", "Prancūzija", "Ispanija", "Italija"],
        explanation: "Krepšinis sukurtas JAV 1891 metais.",
      },
    },
  },
  {
    id: "spo_me_013",
    category: "sport",
    subTheme: "sports",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Athletics (sprint distance 100 m)",
    emoji: "🏃",
    translations: {
      en: {
        question: "What is the shortest standard Olympic sprint distance?",
        correct: "100 meters",
        distractors: ["50 meters", "200 meters", "400 meters", "60 meters", "150 meters"],
        explanation: "The 100 meters is the shortest standard Olympic sprint.",
      },
      lt: {
        question: "Koks trumpiausias standartinis olimpinis sprinto nuotolis?",
        correct: "100 metrų",
        distractors: ["50 metrų", "200 metrų", "400 metrų", "60 metrų", "150 metrų"],
        explanation: "100 metrų — trumpiausias standartinis olimpinis sprintas.",
      },
    },
  },
  {
    id: "spo_me_014",
    category: "sport",
    subTheme: "football",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Football venue term (pitch)",
    emoji: "🟩",
    translations: {
      en: {
        question: "What is the football playing field called?",
        correct: "Pitch",
        distractors: ["Court", "Rink", "Track", "Ring", "Diamond"],
        explanation: "A football field is commonly called a pitch.",
      },
      lt: {
        question: "Kaip vadinama futbolo žaidimo aikštė?",
        correct: "Aikštė",
        distractors: ["Kortas", "Čiuožykla", "Takas", "Ringas", "Deimantas"],
        explanation: "Futbolo žaidimo plotas vadinamas aikšte.",
      },
    },
  },
  {
    id: "spo_me_015",
    category: "sport",
    subTheme: "sports",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Gymnastics apparatus (balance beam)",
    emoji: "🤸",
    translations: {
      en: {
        question: "The balance beam is used in which sport?",
        correct: "Gymnastics",
        distractors: ["Diving", "Boxing", "Fencing", "Rowing", "Archery"],
        explanation: "The balance beam is a gymnastics apparatus.",
      },
      lt: {
        question: "Kurioje sporto šakoje naudojamas pusiausvyros suolelis?",
        correct: "Gimnastika",
        distractors: ["Šuoliai į vandenį", "Boksas", "Fechtavimas", "Irklavimas", "Šaudymas iš lanko"],
        explanation: "Pusiausvyros suolelis — gimnastikos įrankis.",
      },
    },
  },

  // ======================= SUNKUS (Hard) =======================
  {
    id: "spo_su_001",
    category: "sport",
    subTheme: "olympics",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Olympic host (Tokyo 1964 first in Asia)",
    emoji: "🗼",
    translations: {
      en: {
        question: "Which city hosted the first Olympics held in Asia, in 1964?",
        correct: "Tokyo",
        distractors: ["Beijing", "Seoul", "Bangkok", "Delhi", "Osaka"],
        explanation: "Tokyo hosted Asia's first Olympics in 1964.",
      },
      lt: {
        question: "Kuris miestas 1964 m. surengė pirmąsias olimpines Azijoje?",
        correct: "Tokijas",
        distractors: ["Pekinas", "Seulas", "Bankokas", "Delis", "Osaka"],
        explanation: "Tokijas surengė pirmąsias olimpines Azijoje 1964 m.",
      },
    },
  },
  {
    id: "spo_su_002",
    category: "sport",
    subTheme: "rules",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Cricket basics (wickets, bat-and-ball)",
    emoji: "🏏",
    translations: {
      en: {
        question: "In which sport do players defend wickets?",
        correct: "Cricket",
        distractors: ["Baseball", "Hockey", "Polo", "Lacrosse", "Softball"],
        explanation: "Wickets are defended in the sport of cricket.",
      },
      lt: {
        question: "Kuriame sporte žaidėjai gina vartelius (wickets)?",
        correct: "Kriketas",
        distractors: ["Beisbolas", "Riedulys", "Polas", "Lakrosas", "Softbolas"],
        explanation: "Varteliai ginami kriketo žaidime.",
      },
    },
  },
  {
    id: "spo_su_003",
    category: "sport",
    subTheme: "football",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Football term (hat-trick = three goals)",
    emoji: "⚽",
    translations: {
      en: {
        question: "A hat-trick means one player scores how many goals?",
        correct: "Three",
        distractors: ["Two", "Four", "Five", "Six", "Seven"],
        explanation: "A hat-trick is three goals by one player in a match.",
      },
      lt: {
        question: "„Hat-trick” reiškia, kad vienas žaidėjas pelno kiek įvarčių?",
        correct: "Tris",
        distractors: ["Du", "Keturis", "Penkis", "Šešis", "Septynis"],
        explanation: "Hat-trickas — trys vieno žaidėjo įvarčiai per rungtynes.",
      },
    },
  },
  {
    id: "spo_su_004",
    category: "sport",
    subTheme: "tennis",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Tennis surface (Roland Garros clay)",
    emoji: "🎾",
    translations: {
      en: {
        question: "The French Open is played on which surface?",
        correct: "Clay",
        distractors: ["Grass", "Hard court", "Carpet", "Wood", "Concrete"],
        explanation: "The French Open is played on clay courts.",
      },
      lt: {
        question: "Ant kokios dangos žaidžiamas Prancūzijos atvirasis (French Open)?",
        correct: "Molio",
        distractors: ["Žolės", "Kieto korto", "Kilimo", "Medžio", "Betono"],
        explanation: "Prancūzijos atvirasis žaidžiamas ant molio kortų.",
      },
    },
  },
  {
    id: "spo_su_005",
    category: "sport",
    subTheme: "sports",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Cycling event (Tour de France, road race)",
    emoji: "🚴",
    translations: {
      en: {
        question: "The Tour de France is a major race in which sport?",
        correct: "Cycling",
        distractors: ["Running", "Motorsport", "Rowing", "Triathlon", "Skating"],
        explanation: "The Tour de France is a famous cycling race.",
      },
      lt: {
        question: "Tour de France yra svarbios kurios sporto šakos lenktynės?",
        correct: "Dviračių",
        distractors: ["Bėgimo", "Automobilių", "Irklavimo", "Triatlono", "Čiuožimo"],
        explanation: "Tour de France — garsios dviračių lenktynės.",
      },
    },
  },
  {
    id: "spo_su_006",
    category: "sport",
    subTheme: "rules",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Volleyball set points (25)",
    emoji: "🏐",
    translations: {
      en: {
        question: "A standard volleyball set is usually played to how many points?",
        correct: "25",
        distractors: ["15", "21", "11", "30", "20"],
        explanation: "Volleyball sets are usually played to 25 points.",
      },
      lt: {
        question: "Iki kiek taškų paprastai žaidžiamas tinklinio setas?",
        correct: "25",
        distractors: ["15", "21", "11", "30", "20"],
        explanation: "Tinklinio setai paprastai žaidžiami iki 25 taškų.",
      },
    },
  },
  {
    id: "spo_su_007",
    category: "sport",
    subTheme: "olympics",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Olympic motto (Faster, Higher, Stronger)",
    emoji: "🏅",
    translations: {
      en: {
        question: "The classic Olympic motto begins with which word?",
        correct: "Faster",
        distractors: ["Braver", "Bigger", "Bolder", "Smarter", "Longer"],
        explanation: "The motto is Faster, Higher, Stronger.",
      },
      lt: {
        question: "Kuriuo žodžiu prasideda klasikinis olimpinis šūkis?",
        correct: "Greičiau",
        distractors: ["Drąsiau", "Didžiau", "Smarkiau", "Protingiau", "Ilgiau"],
        explanation: "Šūkis — „Greičiau, aukščiau, stipriau”.",
      },
    },
  },
  {
    id: "spo_su_008",
    category: "sport",
    subTheme: "sports",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Triathlon disciplines (swim-bike-run)",
    emoji: "🏊",
    translations: {
      en: {
        question: "A triathlon combines swimming, cycling and what?",
        correct: "Running",
        distractors: ["Rowing", "Skiing", "Boxing", "Jumping", "Climbing"],
        explanation: "Triathlon is swimming, cycling and running.",
      },
      lt: {
        question: "Be plaukimo ir dviračių, ką dar jungia triatlonas?",
        correct: "Bėgimą",
        distractors: ["Irklavimą", "Slidinėjimą", "Boksą", "Šokimą", "Laipiojimą"],
        explanation: "Triatlonas — plaukimas, dviračiai ir bėgimas.",
      },
    },
  },
  {
    id: "spo_su_009",
    category: "sport",
    subTheme: "football",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Football pitch markings (penalty spot ~11 m)",
    emoji: "⚽",
    translations: {
      en: {
        question: "A football penalty kick is taken about how far from goal?",
        correct: "11 meters",
        distractors: ["5 meters", "9 meters", "16 meters", "20 meters", "7 meters"],
        explanation: "The penalty spot is about 11 meters from goal.",
      },
      lt: {
        question: "Iš maždaug kokio atstumo mušamas futbolo baudinys?",
        correct: "11 metrų",
        distractors: ["5 metrų", "9 metrų", "16 metrų", "20 metrų", "7 metrų"],
        explanation: "Baudinio taškas yra maždaug 11 metrų nuo vartų.",
      },
    },
  },
  {
    id: "spo_su_010",
    category: "sport",
    subTheme: "sports",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Fencing weapons (foil, epee, sabre)",
    emoji: "🤺",
    translations: {
      en: {
        question: "Which of these is a fencing weapon?",
        correct: "Sabre",
        distractors: ["Javelin", "Baton", "Discus", "Mallet", "Cue"],
        explanation: "Foil, epee and sabre are fencing weapons.",
      },
      lt: {
        question: "Kuris iš šių yra fechtavimo ginklas?",
        correct: "Kardas",
        distractors: ["Ietis", "Lazdelė", "Diskas", "Plaktukas", "Kijus"],
        explanation: "Rapyra, špaga ir kardas — fechtavimo ginklai.",
      },
    },
  },
  {
    id: "spo_su_011",
    category: "sport",
    subTheme: "basketball",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Basketball rim height (3.05 m)",
    emoji: "🏀",
    translations: {
      en: {
        question: "How high is a standard basketball hoop?",
        correct: "3.05 meters",
        distractors: ["2.5 meters", "3.5 meters", "4 meters", "2 meters", "3.65 meters"],
        explanation: "A basketball rim sits 3.05 meters (10 ft) high.",
      },
      lt: {
        question: "Kokiame aukštyje yra standartinis krepšinio lankas?",
        correct: "3,05 metro",
        distractors: ["2,5 metro", "3,5 metro", "4 metrų", "2 metrų", "3,65 metro"],
        explanation: "Krepšinio lankas yra 3,05 metro (10 pėdų) aukštyje.",
      },
    },
  },
  {
    id: "spo_su_012",
    category: "sport",
    subTheme: "sports",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Golf term (one under par = birdie)",
    emoji: "⛳",
    translations: {
      en: {
        question: "In golf, one stroke under par on a hole is called a what?",
        correct: "Birdie",
        distractors: ["Bogey", "Eagle", "Par", "Albatross", "Ace"],
        explanation: "One under par on a hole is a birdie.",
      },
      lt: {
        question: "Golfe vienas smūgis mažiau už par duobutėje vadinamas kaip?",
        correct: "Birdie",
        distractors: ["Bogey", "Eagle", "Par", "Albatross", "Ace"],
        explanation: "Vienas smūgis mažiau už par duobutėje — birdie.",
      },
    },
  },
  {
    id: "spo_su_013",
    category: "sport",
    subTheme: "olympics",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Olympic flame origin (Olympia, Greece)",
    emoji: "🔥",
    translations: {
      en: {
        question: "The Olympic flame is traditionally lit in which country?",
        correct: "Greece",
        distractors: ["France", "Italy", "Switzerland", "Egypt", "Turkey"],
        explanation: "The Olympic flame is lit in Olympia, Greece.",
      },
      lt: {
        question: "Kurioje šalyje tradiciškai įžiebiama olimpinė ugnis?",
        correct: "Graikija",
        distractors: ["Prancūzija", "Italija", "Šveicarija", "Egiptas", "Turkija"],
        explanation: "Olimpinė ugnis įžiebiama Olimpijoje, Graikijoje.",
      },
    },
  },
  {
    id: "spo_su_014",
    category: "sport",
    subTheme: "rules",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Ice hockey team size (6 with goalie)",
    emoji: "🏒",
    translations: {
      en: {
        question: "How many players per team are on the ice in hockey?",
        correct: "6",
        distractors: ["5", "7", "8", "11", "4"],
        explanation: "Ice hockey teams have 6 players including the goalie.",
      },
      lt: {
        question: "Kiek vienos komandos žaidėjų yra ant ledo ritulyje?",
        correct: "6",
        distractors: ["5", "7", "8", "11", "4"],
        explanation: "Ledo ritulyje komandoje 6 žaidėjai su vartininku.",
      },
    },
  },
  {
    id: "spo_su_015",
    category: "sport",
    subTheme: "sports",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Athletics (decathlon = 10 events)",
    emoji: "🏟️",
    translations: {
      en: {
        question: "How many events make up the athletics decathlon?",
        correct: "10",
        distractors: ["5", "7", "8", "12", "15"],
        explanation: "A decathlon is made up of ten track and field events.",
      },
      lt: {
        question: "Iš kiek rungčių sudaryta lengvosios atletikos dešimtkovė?",
        correct: "10",
        distractors: ["5", "7", "8", "12", "15"],
        explanation: "Dešimtkovę sudaro dešimt lengvosios atletikos rungčių.",
      },
    },
  },

  // ======================= EKSTREMALUS (Extreme) =======================
  {
    id: "spo_ek_001",
    category: "sport",
    subTheme: "olympics",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Olympic history (1924 first Winter Games, Chamonix)",
    emoji: "🏔️",
    translations: {
      en: {
        question: "The first Winter Olympics in 1924 were held in which country?",
        correct: "France",
        distractors: ["Switzerland", "Norway", "Austria", "Italy", "Canada"],
        explanation: "The first Winter Olympics were in Chamonix, France.",
      },
      lt: {
        question: "Kurioje šalyje vyko pirmosios žiemos olimpinės 1924 m.?",
        correct: "Prancūzija",
        distractors: ["Šveicarija", "Norvegija", "Austrija", "Italija", "Kanada"],
        explanation: "Pirmosios žiemos olimpinės vyko Šamoni, Prancūzijoje.",
      },
    },
  },
  {
    id: "spo_ek_002",
    category: "sport",
    subTheme: "tennis",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Tennis Grand Slam count (4 tournaments)",
    emoji: "🎾",
    translations: {
      en: {
        question: "How many tournaments make up the tennis Grand Slam?",
        correct: "4",
        distractors: ["3", "5", "6", "2", "8"],
        explanation: "The Grand Slam has four major tournaments.",
      },
      lt: {
        question: "Iš kiek turnyrų sudarytas teniso Didysis kirtis (Grand Slam)?",
        correct: "4",
        distractors: ["3", "5", "6", "2", "8"],
        explanation: "Didįjį kirtį sudaro keturi dideli turnyrai.",
      },
    },
  },
  {
    id: "spo_ek_003",
    category: "sport",
    subTheme: "football",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Football history (first World Cup 1930, Uruguay)",
    emoji: "🏆",
    translations: {
      en: {
        question: "Which country hosted the first FIFA World Cup in 1930?",
        correct: "Uruguay",
        distractors: ["Brazil", "Italy", "Argentina", "France", "England"],
        explanation: "Uruguay hosted and won the first World Cup in 1930.",
      },
      lt: {
        question: "Kuri šalis surengė pirmąjį FIFA pasaulio čempionatą 1930 m.?",
        correct: "Urugvajus",
        distractors: ["Brazilija", "Italija", "Argentina", "Prancūzija", "Anglija"],
        explanation: "Urugvajus surengė ir laimėjo pirmąjį čempionatą 1930 m.",
      },
    },
  },
  {
    id: "spo_ek_004",
    category: "sport",
    subTheme: "sports",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Athletics (Usain Bolt sprint records)",
    emoji: "⚡",
    translations: {
      en: {
        question: "Usain Bolt set world records in which athletics event?",
        correct: "Sprinting",
        distractors: ["Marathon", "High jump", "Shot put", "Pole vault", "Hurdles"],
        explanation: "Bolt set 100 m and 200 m sprint world records.",
      },
      lt: {
        question: "Kurioje atletikos rungtyje pasaulio rekordus pasiekė Usain Bolt?",
        correct: "Sprinte",
        distractors: ["Maratone", "Šuolyje į aukštį", "Rutulio stūmime", "Šuolyje su kartimi", "Barjeruose"],
        explanation: "Bolt pasiekė 100 m ir 200 m sprinto pasaulio rekordus.",
      },
    },
  },
  {
    id: "spo_ek_005",
    category: "sport",
    subTheme: "rules",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Chess board (64 squares)",
    emoji: "♟️",
    translations: {
      en: {
        question: "How many squares are on a standard chess board?",
        correct: "64",
        distractors: ["32", "48", "81", "100", "56"],
        explanation: "A chess board has 8 by 8, that is 64 squares.",
      },
      lt: {
        question: "Kiek langelių yra standartinėje šachmatų lentoje?",
        correct: "64",
        distractors: ["32", "48", "81", "100", "56"],
        explanation: "Šachmatų lentoje 8 kartus 8, tai yra 64 langeliai.",
      },
    },
  },
  {
    id: "spo_ek_006",
    category: "sport",
    subTheme: "basketball",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Basketball history (invented 1891)",
    emoji: "🏀",
    translations: {
      en: {
        question: "In which decade was basketball invented?",
        correct: "1890s",
        distractors: ["1850s", "1870s", "1910s", "1920s", "1940s"],
        explanation: "Basketball was invented in 1891, the 1890s.",
      },
      lt: {
        question: "Kuriame dešimtmetyje sukurtas krepšinis?",
        correct: "1890-aisiais",
        distractors: ["1850-aisiais", "1870-aisiais", "1910-aisiais", "1920-aisiais", "1940-aisiais"],
        explanation: "Krepšinis sukurtas 1891 m., tai yra 1890-aisiais.",
      },
    },
  },
  {
    id: "spo_ek_007",
    category: "sport",
    subTheme: "sports",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Swimming strokes (butterfly one of four)",
    emoji: "🦋",
    translations: {
      en: {
        question: "Which of these is an official competitive swimming stroke?",
        correct: "Butterfly",
        distractors: ["Dolphin spin", "Side glide", "Otter kick", "Frog dive", "Whale roll"],
        explanation: "Butterfly is one of the four competitive strokes.",
      },
      lt: {
        question: "Kuris iš šių yra oficialus varžybinis plaukimo stilius?",
        correct: "Peteliškė",
        distractors: ["Delfino sukinys", "Šoninis slydimas", "Ūdros spyris", "Varlės nėrimas", "Banginio ritinys"],
        explanation: "Peteliškė — vienas iš keturių varžybinių stilių.",
      },
    },
  },
  {
    id: "spo_ek_008",
    category: "sport",
    subTheme: "olympics",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Marathon distance fixed 1908 (42.195 km)",
    emoji: "🏃",
    translations: {
      en: {
        question: "The exact marathon distance is how many kilometers?",
        correct: "42.195",
        distractors: ["40.000", "41.500", "43.000", "42.500", "45.000"],
        explanation: "The official marathon distance is 42.195 km.",
      },
      lt: {
        question: "Koks tikslus maratono nuotolis kilometrais?",
        correct: "42,195",
        distractors: ["40,000", "41,500", "43,000", "42,500", "45,000"],
        explanation: "Oficialus maratono nuotolis — 42,195 km.",
      },
    },
  },
  {
    id: "spo_ek_009",
    category: "sport",
    subTheme: "football",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Football rules (goal width 7.32 m)",
    emoji: "🥅",
    translations: {
      en: {
        question: "How wide is a standard football goal?",
        correct: "7.32 meters",
        distractors: [
          "5 meters",
          "6 meters",
          "8 meters",
          "9.15 meters",
          "11 meters",
        ],
        explanation: "A standard goal is 7.32 m wide and 2.44 m high.",
      },
      lt: {
        question: "Koks standartinių futbolo vartų plotis?",
        correct: "7,32 metro",
        distractors: [
          "5 metrai",
          "6 metrai",
          "8 metrai",
          "9,15 metro",
          "11 metrų",
        ],
        explanation: "Standartiniai vartai yra 7,32 m pločio ir 2,44 m aukščio.",
      },
    },
  },
  {
    id: "spo_ek_010",
    category: "sport",
    subTheme: "sports",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Motorsport (Le Mans 24-hour race)",
    emoji: "🏎️",
    translations: {
      en: {
        question: "The famous Le Mans race lasts how long?",
        correct: "24 hours",
        distractors: ["6 hours", "12 hours", "48 hours", "1 hour", "8 hours"],
        explanation: "The 24 Hours of Le Mans is a day-long endurance race.",
      },
      lt: {
        question: "Kiek trunka garsiosios Le Mano lenktynės?",
        correct: "24 valandas",
        distractors: ["6 valandas", "12 valandų", "48 valandas", "1 valandą", "8 valandas"],
        explanation: "24 Le Mano valandos — parą trunkančios ištvermės lenktynės.",
      },
    },
  },
  {
    id: "spo_ek_011",
    category: "sport",
    subTheme: "rules",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Tennis tie-break scoring (to 7, win by 2)",
    emoji: "🎾",
    translations: {
      en: {
        question: "A standard tennis tie-break is first to how many points?",
        correct: "7",
        distractors: ["5", "6", "10", "11", "4"],
        explanation: "A tie-break is won at 7 points, by two clear points.",
      },
      lt: {
        question: "Iki kiek taškų žaidžiamas standartinis teniso pratęsimas (tie-break)?",
        correct: "7",
        distractors: ["5", "6", "10", "11", "4"],
        explanation: "Tie-breakas laimimas surinkus 7 taškus dviejų skirtumu.",
      },
    },
  },
  {
    id: "spo_ek_012",
    category: "sport",
    subTheme: "sports",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Cycling jersey (Tour de France yellow leader)",
    emoji: "🟨",
    translations: {
      en: {
        question: "What color jersey does the Tour de France leader wear?",
        correct: "Yellow",
        distractors: ["Green", "Red", "Blue", "White", "Black"],
        explanation: "The race leader wears the yellow jersey.",
      },
      lt: {
        question: "Kokios spalvos marškinėlius vilki Tour de France lyderis?",
        correct: "Geltonus",
        distractors: ["Žalius", "Raudonus", "Mėlynus", "Baltus", "Juodus"],
        explanation: "Lenktynių lyderis vilki geltonus marškinėlius.",
      },
    },
  },
  {
    id: "spo_ek_013",
    category: "sport",
    subTheme: "olympics",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Olympic city (Paris 1900, 1924, 2024)",
    emoji: "🗼",
    translations: {
      en: {
        question: "Which European capital hosted the Summer Olympics three times?",
        correct: "Paris",
        distractors: ["Rome", "Madrid", "Berlin", "Vienna", "Lisbon"],
        explanation: "Paris hosted the Summer Olympics in 1900, 1924 and 2024.",
      },
      lt: {
        question: "Kuri Europos sostinė vasaros olimpines rengė tris kartus?",
        correct: "Paryžius",
        distractors: ["Roma", "Madridas", "Berlynas", "Viena", "Lisabona"],
        explanation: "Paryžius vasaros olimpines rengė 1900, 1924 ir 2024 m.",
      },
    },
  },
  {
    id: "spo_ek_014",
    category: "sport",
    subTheme: "sports",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Basketball pro league (NBA, North America)",
    emoji: "🏀",
    translations: {
      en: {
        question: "The NBA is the top basketball league based in which region?",
        correct: "North America",
        distractors: ["Europe", "Asia", "South America", "Africa", "Oceania"],
        explanation: "The NBA is based in North America.",
      },
      lt: {
        question: "NBA — aukščiausia krepšinio lyga — yra kuriame regione?",
        correct: "Šiaurės Amerikoje",
        distractors: ["Europoje", "Azijoje", "Pietų Amerikoje", "Afrikoje", "Okeanijoje"],
        explanation: "NBA įsikūrusi Šiaurės Amerikoje.",
      },
    },
  },
  {
    id: "spo_ek_015",
    category: "sport",
    subTheme: "rules",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Basketball rules (shot clock 24 seconds)",
    emoji: "⏱️",
    translations: {
      en: {
        question: "How many seconds does a team have to shoot in pro basketball?",
        correct: "24 seconds",
        distractors: [
          "20 seconds",
          "30 seconds",
          "35 seconds",
          "15 seconds",
          "45 seconds",
        ],
        explanation: "The shot clock in pro basketball is 24 seconds.",
      },
      lt: {
        question: "Per kiek sekundžių komanda turi atlikti metimą profesionaliame krepšinyje?",
        correct: "24 sekundės",
        distractors: [
          "20 sekundžių",
          "30 sekundžių",
          "35 sekundės",
          "15 sekundžių",
          "45 sekundės",
        ],
        explanation: "Atakos laikrodis profesionaliame krepšinyje yra 24 sekundės.",
      },
    },
  },
  {
    id: "spo_le_016",
    category: "sport",
    subTheme: "rules",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Basketball 5 players on court",
    emoji: "🏀",
    translations: {
      en: {
        question: "How many players from one team are on a basketball court?",
        correct: "5",
        distractors: ["6", "7", "4", "3", "11"],
        explanation: "A basketball team has 5 players on the court.",
      },
      lt: {
        question: "Kiek vienos komandos žaidėjų yra krepšinio aikštėje?",
        correct: "5",
        distractors: ["6", "7", "4", "3", "11"],
        explanation: "Krepšinio komandoje aikštėje žaidžia 5 žaidėjai.",
      },
    },
  },
  {
    id: "spo_le_017",
    category: "sport",
    subTheme: "identify",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Table tennis with paddles",
    emoji: "🏓",
    translations: {
      en: {
        question: "Which sport uses small paddles and a light ball on a table?",
        correct: "Table tennis",
        distractors: ["Tennis", "Volleyball", "Badminton", "Squash", "Golf"],
        explanation: "Table tennis is played with paddles on a table.",
      },
      lt: {
        question: "Kurioje sporto šakoje žaidžiama mažomis raketėmis ir lengvu kamuoliuku ant stalo?",
        correct: "Stalo tenisas",
        distractors: ["Tenisas", "Tinklinis", "Badmintonas", "Skvošas", "Golfas"],
        explanation: "Stalo tenisas žaidžiamas raketėmis ant stalo.",
      },
    },
  },
  {
    id: "spo_le_018",
    category: "sport",
    subTheme: "rules",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Goalkeeper in football",
    emoji: "⚽",
    translations: {
      en: {
        question: "A goalkeeper is a position in which sport?",
        correct: "Football",
        distractors: ["Tennis", "Golf", "Swimming", "Cycling", "Boxing"],
        explanation: "The goalkeeper guards the goal in football.",
      },
      lt: {
        question: "Vartininkas yra pozicija kuriame sporte?",
        correct: "Futbolas",
        distractors: ["Tenisas", "Golfas", "Plaukimas", "Dviračiai", "Boksas"],
        explanation: "Vartininkas futbole saugo vartus.",
      },
    },
  },
  {
    id: "spo_le_019",
    category: "sport",
    subTheme: "identify",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Tennis at Wimbledon",
    emoji: "🎾",
    translations: {
      en: {
        question: "Which sport is played at Wimbledon?",
        correct: "Tennis",
        distractors: ["Golf", "Cricket", "Rugby", "Football", "Hockey"],
        explanation: "Wimbledon is a famous tennis tournament.",
      },
      lt: {
        question: "Kuri sporto šaka žaidžiama Vimbldone?",
        correct: "Tenisas",
        distractors: ["Golfas", "Kriketas", "Regbis", "Futbolas", "Ritulys"],
        explanation: "Vimbldonas — garsus teniso turnyras.",
      },
    },
  },
  {
    id: "spo_le_020",
    category: "sport",
    subTheme: "rules",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Bicycle has 2 wheels",
    emoji: "🚲",
    translations: {
      en: {
        question: "How many wheels does a standard bicycle have?",
        correct: "2",
        distractors: ["3", "4", "1", "5", "6"],
        explanation: "A standard bicycle has two wheels.",
      },
      lt: {
        question: "Kiek ratų turi įprastas dviratis?",
        correct: "2",
        distractors: ["3", "4", "1", "5", "6"],
        explanation: "Įprastas dviratis turi du ratus.",
      },
    },
  },
  {
    id: "spo_le_021",
    category: "sport",
    subTheme: "rules",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Boxers wear gloves on hands",
    emoji: "🥊",
    translations: {
      en: {
        question: "Boxers wear gloves on which part of the body?",
        correct: "Hands",
        distractors: ["Feet", "Head", "Legs", "Knees", "Elbows"],
        explanation: "Boxers wear padded gloves on their hands.",
      },
      lt: {
        question: "Ant kurios kūno dalies boksininkai mūvi pirštines?",
        correct: "Rankų",
        distractors: ["Kojų", "Galvos", "Blauzdų", "Kelių", "Alkūnių"],
        explanation: "Boksininkai mūvi minkštas pirštines ant rankų.",
      },
    },
  },
  {
    id: "spo_le_022",
    category: "sport",
    subTheme: "rules",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Football is round",
    emoji: "⚽",
    translations: {
      en: {
        question: "What shape is a standard football (soccer ball)?",
        correct: "Round",
        distractors: ["Square", "Oval", "Flat", "Cube", "Triangle"],
        explanation: "A soccer ball is round (a sphere).",
      },
      lt: {
        question: "Kokios formos yra įprastas futbolo kamuolys?",
        correct: "Apvalus",
        distractors: ["Kvadratinis", "Ovalus", "Plokščias", "Kubas", "Trikampis"],
        explanation: "Futbolo kamuolys yra apvalus (sfera).",
      },
    },
  },
  {
    id: "spo_le_023",
    category: "sport",
    subTheme: "identify",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Sprint is running",
    emoji: "🏃",
    translations: {
      en: {
        question: "In athletics, a sprint is a type of what?",
        correct: "Running",
        distractors: ["Jumping", "Throwing", "Swimming", "Cycling", "Lifting"],
        explanation: "A sprint is a short, fast run.",
      },
      lt: {
        question: "Lengvojoje atletikoje sprintas yra kokia veikla?",
        correct: "Bėgimas",
        distractors: ["Šuoliai", "Metimai", "Plaukimas", "Dviračiai", "Kilnojimas"],
        explanation: "Sprintas — trumpas greitas bėgimas.",
      },
    },
  },
  {
    id: "spo_le_024",
    category: "sport",
    subTheme: "identify",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Golf uses clubs",
    emoji: "⛳",
    translations: {
      en: {
        question: "Which sport uses clubs to hit a small ball into holes?",
        correct: "Golf",
        distractors: ["Hockey", "Cricket", "Baseball", "Tennis", "Polo"],
        explanation: "Golfers use clubs to hit balls into holes.",
      },
      lt: {
        question: "Kurioje sporto šakoje lazdomis mažas kamuoliukas varomas į duobutes?",
        correct: "Golfas",
        distractors: ["Ritulys", "Kriketas", "Beisbolas", "Tenisas", "Polas"],
        explanation: "Golfe lazdomis kamuoliukas varomas į duobutes.",
      },
    },
  },
  {
    id: "spo_le_025",
    category: "sport",
    subTheme: "rules",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Referee uses a whistle",
    emoji: "📣",
    translations: {
      en: {
        question: "What does a referee blow to stop play in many sports?",
        correct: "Whistle",
        distractors: ["Bell", "Horn", "Drum", "Flag", "Card"],
        explanation: "Referees blow a whistle to signal play.",
      },
      lt: {
        question: "Į ką pučia teisėjas, kad sustabdytų žaidimą daugelyje sporto šakų?",
        correct: "Švilpukas",
        distractors: ["Varpas", "Ragas", "Būgnas", "Vėliava", "Kortelė"],
        explanation: "Teisėjai pučia švilpuką žaidimui signalizuoti.",
      },
    },
  },
  {
    id: "spo_le_026",
    category: "sport",
    subTheme: "identify",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Ice hockey uses stick and puck",
    emoji: "🏒",
    translations: {
      en: {
        question: "In which sport do players score using a stick and a puck?",
        correct: "Ice hockey",
        distractors: ["Football", "Cricket", "Tennis", "Golf", "Rowing"],
        explanation: "Ice hockey is played with sticks and a puck.",
      },
      lt: {
        question: "Kuriame sporte taškai pelnomi lazda ir guminiu disku?",
        correct: "Ledo ritulys",
        distractors: ["Futbolas", "Kriketas", "Tenisas", "Golfas", "Irklavimas"],
        explanation: "Ledo ritulys žaidžiamas lazdomis ir guminiu disku.",
      },
    },
  },
  {
    id: "spo_le_027",
    category: "sport",
    subTheme: "rules",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Medals for top finishers",
    emoji: "🏅",
    translations: {
      en: {
        question: "What do athletes win for finishing first, second or third?",
        correct: "Medals",
        distractors: ["Flags", "Cards", "Coins", "Ribbons", "Hats"],
        explanation: "Top three finishers usually receive medals.",
      },
      lt: {
        question: "Ką sportininkai laimi užėmę pirmą, antrą ar trečią vietą?",
        correct: "Medalius",
        distractors: ["Vėliavas", "Korteles", "Monetas", "Kaspinus", "Kepures"],
        explanation: "Trys geriausi paprastai gauna medalius.",
      },
    },
  },
  {
    id: "spo_le_028",
    category: "sport",
    subTheme: "rules",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Chess board two colors",
    emoji: "♟️",
    translations: {
      en: {
        question: "A chessboard has squares of how many colors?",
        correct: "2",
        distractors: ["1", "3", "4", "6", "8"],
        explanation: "A chessboard has light and dark squares — two colors.",
      },
      lt: {
        question: "Iš kiek spalvų langelių sudaryta šachmatų lenta?",
        correct: "2",
        distractors: ["1", "3", "4", "6", "8"],
        explanation: "Šachmatų lentoje yra šviesūs ir tamsūs langeliai — dvi spalvos.",
      },
    },
  },
  {
    id: "spo_le_029",
    category: "sport",
    subTheme: "identify",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Surfers ride waves",
    emoji: "🏄",
    translations: {
      en: {
        question: "Surfers ride on what?",
        correct: "Waves",
        distractors: ["Snow", "Sand", "Ice", "Grass", "Roads"],
        explanation: "Surfers ride ocean waves on a board.",
      },
      lt: {
        question: "Ant ko slysta banglentininkai?",
        correct: "Bangų",
        distractors: ["Sniego", "Smėlio", "Ledo", "Žolės", "Kelių"],
        explanation: "Banglentininkai lentomis slysta vandenyno bangomis.",
      },
    },
  },
  {
    id: "spo_le_030",
    category: "sport",
    subTheme: "identify",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Jockey rides a horse",
    emoji: "🐎",
    translations: {
      en: {
        question: "In horse racing, a jockey rides which animal?",
        correct: "Horse",
        distractors: ["Camel", "Dog", "Donkey", "Cow", "Goat"],
        explanation: "A jockey rides a horse in racing.",
      },
      lt: {
        question: "Žirgų lenktynėse žokėjas joja ant kurio gyvūno?",
        correct: "Žirgo",
        distractors: ["Kupranugario", "Šuns", "Asilo", "Karvės", "Ožkos"],
        explanation: "Žokėjas lenktynėse joja žirgu.",
      },
    },
  },
  {
    id: "spo_me_016",
    category: "sport",
    subTheme: "rules",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Volleyball 6 players",
    emoji: "🏐",
    translations: {
      en: {
        question: "How many players from one team are on a volleyball court?",
        correct: "6",
        distractors: ["5", "7", "8", "4", "9"],
        explanation: "A volleyball team has 6 players on court.",
      },
      lt: {
        question: "Kiek vienos komandos žaidėjų yra tinklinio aikštėje?",
        correct: "6",
        distractors: ["5", "7", "8", "4", "9"],
        explanation: "Tinklinio komandoje aikštėje žaidžia 6 žaidėjai.",
      },
    },
  },
  {
    id: "spo_me_017",
    category: "sport",
    subTheme: "history",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "The Ashes: England vs Australia",
    emoji: "🏏",
    translations: {
      en: {
        question: "The Ashes cricket series is between England and which country?",
        correct: "Australia",
        distractors: ["India", "South Africa", "New Zealand", "Pakistan", "Sri Lanka"],
        explanation: "The Ashes is contested by England and Australia.",
      },
      lt: {
        question: "Kriketo serija „The Ashes” vyksta tarp Anglijos ir kurios šalies?",
        correct: "Australija",
        distractors: ["Indija", "Pietų Afrika", "Naujoji Zelandija", "Pakistanas", "Šri Lanka"],
        explanation: "„The Ashes” varžosi Anglija ir Australija.",
      },
    },
  },
  {
    id: "spo_me_018",
    category: "sport",
    subTheme: "identify",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Stanley Cup in ice hockey",
    emoji: "🏒",
    translations: {
      en: {
        question: "In which sport is the Stanley Cup awarded?",
        correct: "Ice hockey",
        distractors: ["Basketball", "Baseball", "American football", "Soccer", "Rugby"],
        explanation: "The Stanley Cup is ice hockey's top trophy.",
      },
      lt: {
        question: "Kurioje sporto šakoje įteikiama Stenlio taurė?",
        correct: "Ledo ritulys",
        distractors: ["Krepšinis", "Beisbolas", "Amerikietiškas futbolas", "Futbolas", "Regbis"],
        explanation: "Stenlio taurė — pagrindinis ledo ritulio trofėjus.",
      },
    },
  },
  {
    id: "spo_me_019",
    category: "sport",
    subTheme: "rules",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Rugby try worth 5 points",
    emoji: "🏉",
    translations: {
      en: {
        question: "How many points is a try worth in rugby union?",
        correct: "5",
        distractors: ["3", "6", "4", "7", "2"],
        explanation: "A try is worth 5 points in rugby union.",
      },
      lt: {
        question: "Kiek taškų regbyje (union) vertas pelnytas „try”?",
        correct: "5",
        distractors: ["3", "6", "4", "7", "2"],
        explanation: "„Try” regbyje vertas 5 taškų.",
      },
    },
  },
  {
    id: "spo_me_020",
    category: "sport",
    subTheme: "identify",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Tour de France in France",
    emoji: "🚴",
    translations: {
      en: {
        question: "The Tour de France cycling race mainly takes place in which country?",
        correct: "France",
        distractors: ["Italy", "Spain", "Belgium", "Germany", "Switzerland"],
        explanation: "The Tour de France is held mostly in France.",
      },
      lt: {
        question: "Dviračių lenktynės Tour de France daugiausia vyksta kurioje šalyje?",
        correct: "Prancūzija",
        distractors: ["Italija", "Ispanija", "Belgija", "Vokietija", "Šveicarija"],
        explanation: "Tour de France daugiausia vyksta Prancūzijoje.",
      },
    },
  },
  {
    id: "spo_me_021",
    category: "sport",
    subTheme: "rules",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Tennis 40-40 is deuce",
    emoji: "🎾",
    translations: {
      en: {
        question: "In tennis, what is the score 40-40 called?",
        correct: "Deuce",
        distractors: ["Ace", "Love", "Set", "Fault", "Match"],
        explanation: "A 40-40 score in tennis is called deuce.",
      },
      lt: {
        question: "Kaip tenise vadinamas rezultatas 40-40?",
        correct: "Deuce (lygu)",
        distractors: ["Ace", "Love", "Setas", "Klaida", "Mečas"],
        explanation: "Rezultatas 40-40 tenise vadinamas „deuce” (lygu).",
      },
    },
  },
  {
    id: "spo_me_022",
    category: "sport",
    subTheme: "identify",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Judo from Japan, throws and holds",
    emoji: "🥋",
    translations: {
      en: {
        question: "Which Japanese martial art focuses on throws and holds?",
        correct: "Judo",
        distractors: ["Karate", "Taekwondo", "Kung fu", "Capoeira", "Muay Thai"],
        explanation: "Judo uses throws and grappling holds.",
      },
      lt: {
        question: "Kuris japonų kovos menas remiasi metimais ir laikymais?",
        correct: "Dziudo",
        distractors: ["Karatė", "Tekvondas", "Kung fu", "Kapoeira", "Muay Thai"],
        explanation: "Dziude naudojami metimai ir laikymo veiksmai.",
      },
    },
  },
  {
    id: "spo_me_023",
    category: "sport",
    subTheme: "rules",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Golf standard round 18 holes",
    emoji: "⛳",
    translations: {
      en: {
        question: "How many holes are played in a standard round of golf?",
        correct: "18",
        distractors: ["9", "12", "16", "20", "24"],
        explanation: "A standard round of golf is 18 holes.",
      },
      lt: {
        question: "Kiek duobučių žaidžiama standartiniame golfo raunde?",
        correct: "18",
        distractors: ["9", "12", "16", "20", "24"],
        explanation: "Standartinis golfo raundas — 18 duobučių.",
      },
    },
  },
  {
    id: "spo_me_024",
    category: "sport",
    subTheme: "rules",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Baseball home run",
    emoji: "⚾",
    translations: {
      en: {
        question: "In baseball, hitting the ball out of the field to score is called a what?",
        correct: "Home run",
        distractors: ["Touchdown", "Goal", "Ace", "Birdie", "Slam dunk"],
        explanation: "A home run lets the batter circle all bases to score.",
      },
      lt: {
        question: "Kaip beisbole vadinamas kamuolio nubloškimas už aikštės ribų pelnant taškus?",
        correct: "Home run",
        distractors: ["Touchdown", "Įvartis", "Ace", "Birdie", "Slam dunk"],
        explanation: "„Home run” leidžia mušėjui apibėgti visas bazes ir pelnyti tašką.",
      },
    },
  },
  {
    id: "spo_me_025",
    category: "sport",
    subTheme: "rules",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Olympics every 4 years",
    emoji: "🔥",
    translations: {
      en: {
        question: "The Summer Olympic Games are normally held every how many years?",
        correct: "4",
        distractors: ["2", "3", "5", "6", "8"],
        explanation: "The Olympics are held every four years.",
      },
      lt: {
        question: "Kas kiek metų paprastai rengiamos vasaros olimpinės žaidynės?",
        correct: "4",
        distractors: ["2", "3", "5", "6", "8"],
        explanation: "Olimpinės žaidynės vyksta kas ketverius metus.",
      },
    },
  },
  {
    id: "spo_me_026",
    category: "sport",
    subTheme: "history",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Brazil most World Cups (5)",
    emoji: "⚽",
    translations: {
      en: {
        question: "Which country has won the most FIFA World Cups?",
        correct: "Brazil",
        distractors: ["Germany", "Italy", "Argentina", "France", "Spain"],
        explanation: "Brazil has won the World Cup five times.",
      },
      lt: {
        question: "Kuri šalis yra laimėjusi daugiausia FIFA pasaulio čempionatų?",
        correct: "Brazilija",
        distractors: ["Vokietija", "Italija", "Argentina", "Prancūzija", "Ispanija"],
        explanation: "Brazilija pasaulio čempionatą laimėjo penkis kartus.",
      },
    },
  },
  {
    id: "spo_me_027",
    category: "sport",
    subTheme: "identify",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Slam dunk in basketball",
    emoji: "🏀",
    translations: {
      en: {
        question: "In which sport do players perform a slam dunk?",
        correct: "Basketball",
        distractors: ["Volleyball", "Handball", "Netball", "Tennis", "Rugby"],
        explanation: "A slam dunk is scored in basketball.",
      },
      lt: {
        question: "Kuriame sporte atliekamas „slam dunk” (kimštukas)?",
        correct: "Krepšinis",
        distractors: ["Tinklinis", "Rankinis", "Netbolas", "Tenisas", "Regbis"],
        explanation: "Kimštukas pelnomas krepšinyje.",
      },
    },
  },
  {
    id: "spo_me_028",
    category: "sport",
    subTheme: "history",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Marathon named after place in Greece",
    emoji: "🏛️",
    translations: {
      en: {
        question: "The marathon race is named after a place in which country?",
        correct: "Greece",
        distractors: ["Italy", "Egypt", "Turkey", "Spain", "France"],
        explanation: "The race is named after Marathon in Greece.",
      },
      lt: {
        question: "Maratono bėgimas pavadintas pagal vietovę kurioje šalyje?",
        correct: "Graikija",
        distractors: ["Italija", "Egiptas", "Turkija", "Ispanija", "Prancūzija"],
        explanation: "Bėgimas pavadintas pagal Maratono vietovę Graikijoje.",
      },
    },
  },
  {
    id: "spo_me_029",
    category: "sport",
    subTheme: "identify",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Bowling uses strike and spare",
    emoji: "🎳",
    translations: {
      en: {
        question: "Which sport uses the terms strike and spare?",
        correct: "Bowling",
        distractors: ["Baseball", "Cricket", "Darts", "Curling", "Snooker"],
        explanation: "Strike and spare are bowling scoring terms.",
      },
      lt: {
        question: "Kurioje sporto šakoje vartojami terminai „strike” ir „spare”?",
        correct: "Boulingas",
        distractors: ["Beisbolas", "Kriketas", "Smiginis", "Kerlingas", "Snukeris"],
        explanation: "„Strike” ir „spare” — boulingo taškų terminai.",
      },
    },
  },
  {
    id: "spo_me_030",
    category: "sport",
    subTheme: "rules",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "American football 11 players",
    emoji: "🏈",
    translations: {
      en: {
        question: "How many players per team are on the field in American football?",
        correct: "11",
        distractors: ["9", "10", "12", "7", "15"],
        explanation: "American football teams field 11 players each.",
      },
      lt: {
        question: "Kiek vienos komandos žaidėjų yra aikštėje amerikietiškame futbole?",
        correct: "11",
        distractors: ["9", "10", "12", "7", "15"],
        explanation: "Amerikietiškame futbole kiekviena komanda turi po 11 žaidėjų.",
      },
    },
  },
  {
    id: "spo_su_016",
    category: "sport",
    subTheme: "history",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "USA hosted most Summer Olympics",
    emoji: "🏟️",
    translations: {
      en: {
        question: "Which country has hosted the Summer Olympics the most times?",
        correct: "United States",
        distractors: ["France", "United Kingdom", "Greece", "Germany", "Australia"],
        explanation: "The United States has hosted the most Summer Games.",
      },
      lt: {
        question: "Kuri šalis daugiausia kartų surengė vasaros olimpines žaidynes?",
        correct: "Jungtinės Valstijos",
        distractors: ["Prancūzija", "Jungtinė Karalystė", "Graikija", "Vokietija", "Australija"],
        explanation: "Daugiausia vasaros žaidynių surengė Jungtinės Valstijos.",
      },
    },
  },
  {
    id: "spo_su_017",
    category: "sport",
    subTheme: "rules",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Cricket century is 100 runs",
    emoji: "🏏",
    translations: {
      en: {
        question: "In cricket, a score of 100 runs by one batsman is called a what?",
        correct: "Century",
        distractors: ["Double", "Boundary", "Hat-trick", "Innings", "Over"],
        explanation: "100 runs by one batsman is a century.",
      },
      lt: {
        question: "Kaip krikete vadinamas vieno mušėjo pelnytas 100 bėgimų rezultatas?",
        correct: "Šimtukas (century)",
        distractors: ["Dvigubas", "Riba", "Hat-trick", "Inningas", "Overas"],
        explanation: "Vieno mušėjo 100 bėgimų vadinami „century”.",
      },
    },
  },
  {
    id: "spo_su_018",
    category: "sport",
    subTheme: "rules",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Fosbury Flop in high jump",
    emoji: "🤸",
    translations: {
      en: {
        question: "The Fosbury Flop is a technique used in which event?",
        correct: "High jump",
        distractors: ["Long jump", "Pole vault", "Shot put", "Hurdles", "Triple jump"],
        explanation: "The Fosbury Flop revolutionized the high jump.",
      },
      lt: {
        question: "„Fosbury Flop” technika naudojama kurioje rungtyje?",
        correct: "Šuolis į aukštį",
        distractors: ["Šuolis į tolį", "Šuolis su kartimi", "Rutulio stūmimas", "Barjerai", "Trišuolis"],
        explanation: "„Fosbury Flop” pakeitė šuolį į aukštį.",
      },
    },
  },
  {
    id: "spo_su_019",
    category: "sport",
    subTheme: "rules",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Olympic pool is 50 meters",
    emoji: "🏊",
    translations: {
      en: {
        question: "How long is a standard Olympic swimming pool?",
        correct: "50 meters",
        distractors: ["25 meters", "100 meters", "75 meters", "60 meters", "33 meters"],
        explanation: "An Olympic pool is 50 meters long.",
      },
      lt: {
        question: "Koks standartinio olimpinio baseino ilgis?",
        correct: "50 metrų",
        distractors: ["25 metrai", "100 metrų", "75 metrai", "60 metrų", "33 metrai"],
        explanation: "Olimpinis baseinas yra 50 metrų ilgio.",
      },
    },
  },
  {
    id: "spo_su_020",
    category: "sport",
    subTheme: "identify",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Salchow in figure skating",
    emoji: "⛸️",
    translations: {
      en: {
        question: "In which sport would you perform a Salchow?",
        correct: "Figure skating",
        distractors: ["Gymnastics", "Diving", "Skiing", "Snowboarding", "Surfing"],
        explanation: "The Salchow is a figure skating jump.",
      },
      lt: {
        question: "Kuriame sporte atliekamas „Salchow” elementas?",
        correct: "Dailusis čiuožimas",
        distractors: ["Gimnastika", "Šuoliai į vandenį", "Slidinėjimas", "Snieglentės", "Banglentės"],
        explanation: "„Salchow” — dailiojo čiuožimo šuolis.",
      },
    },
  },
  {
    id: "spo_su_021",
    category: "sport",
    subTheme: "rules",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Handball 7 players",
    emoji: "🤾",
    translations: {
      en: {
        question: "How many players from one team are on a handball court?",
        correct: "7",
        distractors: ["6", "5", "8", "9", "11"],
        explanation: "A handball team has 7 players, including the goalkeeper.",
      },
      lt: {
        question: "Kiek vienos komandos žaidėjų yra rankinio aikštėje?",
        correct: "7",
        distractors: ["6", "5", "8", "9", "11"],
        explanation: "Rankinio komandoje aikštėje yra 7 žaidėjai su vartininku.",
      },
    },
  },
  {
    id: "spo_su_022",
    category: "sport",
    subTheme: "identify",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Davis Cup in tennis",
    emoji: "🎾",
    translations: {
      en: {
        question: "The Davis Cup is a team competition in which sport?",
        correct: "Tennis",
        distractors: ["Golf", "Cricket", "Rugby", "Sailing", "Rowing"],
        explanation: "The Davis Cup is tennis's top team event.",
      },
      lt: {
        question: "Deiviso taurė yra komandinės varžybos kurioje sporto šakoje?",
        correct: "Tenisas",
        distractors: ["Golfas", "Kriketas", "Regbis", "Buriavimas", "Irklavimas"],
        explanation: "Deiviso taurė — pagrindinės teniso komandinės varžybos.",
      },
    },
  },
  {
    id: "spo_su_023",
    category: "sport",
    subTheme: "rules",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Decathlon over 2 days",
    emoji: "🏃",
    translations: {
      en: {
        question: "Over how many days is the athletics decathlon contested?",
        correct: "2",
        distractors: ["1", "3", "4", "5", "7"],
        explanation: "The decathlon's ten events are held over two days.",
      },
      lt: {
        question: "Per kiek dienų vyksta lengvosios atletikos dešimtkovė?",
        correct: "2",
        distractors: ["1", "3", "4", "5", "7"],
        explanation: "Dešimt dešimtkovės rungčių vyksta per dvi dienas.",
      },
    },
  },
  {
    id: "spo_su_024",
    category: "sport",
    subTheme: "identify",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Wimbledon played on grass",
    emoji: "🎾",
    translations: {
      en: {
        question: "Which tennis Grand Slam is played on grass courts?",
        correct: "Wimbledon",
        distractors: ["French Open", "US Open", "Australian Open", "Davis Cup", "Olympics"],
        explanation: "Wimbledon is the only Grand Slam played on grass.",
      },
      lt: {
        question: "Kuris teniso Didžiojo kirčio turnyras žaidžiamas ant žolės?",
        correct: "Vimbldonas",
        distractors: ["French Open", "US Open", "Australian Open", "Deiviso taurė", "Olimpinės"],
        explanation: "Vimbldonas — vienintelis Didžiojo kirčio turnyras ant žolės.",
      },
    },
  },
  {
    id: "spo_su_025",
    category: "sport",
    subTheme: "rules",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Golf eagle is two under par",
    emoji: "⛳",
    translations: {
      en: {
        question: "In golf, scoring two strokes under par on a hole is called a what?",
        correct: "Eagle",
        distractors: ["Birdie", "Bogey", "Albatross", "Par", "Ace"],
        explanation: "Two under par on a hole is an eagle.",
      },
      lt: {
        question: "Kaip golfe vadinamas duobutės rezultatas dviem smūgiais žemiau par?",
        correct: "Eagle (erelis)",
        distractors: ["Birdie", "Bogey", "Albatross", "Par", "Ace"],
        explanation: "Du smūgiai žemiau par vienoje duobutėje — „eagle”.",
      },
    },
  },
  {
    id: "spo_su_026",
    category: "sport",
    subTheme: "identify",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Peloton in cycling",
    emoji: "🚴",
    translations: {
      en: {
        question: "The term peloton is used in which sport?",
        correct: "Cycling",
        distractors: ["Rowing", "Running", "Swimming", "Sailing", "Skiing"],
        explanation: "The peloton is the main pack of riders in cycling.",
      },
      lt: {
        question: "Terminas „peletonas” vartojamas kurioje sporto šakoje?",
        correct: "Dviračių sportas",
        distractors: ["Irklavimas", "Bėgimas", "Plaukimas", "Buriavimas", "Slidinėjimas"],
        explanation: "Peletonas — pagrindinė dviratininkų grupė lenktynėse.",
      },
    },
  },
  {
    id: "spo_su_027",
    category: "sport",
    subTheme: "rules",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Football match 90 minutes",
    emoji: "⚽",
    translations: {
      en: {
        question: "How many minutes is a standard football match, before stoppage time?",
        correct: "90",
        distractors: ["80", "100", "120", "60", "70"],
        explanation: "A football match is 90 minutes plus stoppage time.",
      },
      lt: {
        question: "Kiek minučių trunka standartinės futbolo rungtynės be pridėto laiko?",
        correct: "90",
        distractors: ["80", "100", "120", "60", "70"],
        explanation: "Futbolo rungtynės trunka 90 minučių plius pridėtas laikas.",
      },
    },
  },
  {
    id: "spo_su_028",
    category: "sport",
    subTheme: "rules",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Heavyweight is heaviest boxing class",
    emoji: "🥊",
    translations: {
      en: {
        question: "Which boxing weight class is the heaviest?",
        correct: "Heavyweight",
        distractors: ["Lightweight", "Middleweight", "Welterweight", "Featherweight", "Bantamweight"],
        explanation: "Heavyweight is the top, heaviest boxing class.",
      },
      lt: {
        question: "Kuri bokso svorio kategorija yra sunkiausia?",
        correct: "Sunkus svoris",
        distractors: ["Lengvas svoris", "Vidutinis svoris", "Pusvidutinis svoris", "Plunksnos svoris", "Bantamo svoris"],
        explanation: "Sunkus svoris — aukščiausia ir sunkiausia bokso kategorija.",
      },
    },
  },
  {
    id: "spo_su_029",
    category: "sport",
    subTheme: "rules",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Ironman swim is 3.8 km",
    emoji: "🏊",
    translations: {
      en: {
        question: "The Ironman triathlon swim is about how long?",
        correct: "3.8 km",
        distractors: ["1.5 km", "5 km", "2 km", "10 km", "0.5 km"],
        explanation: "The Ironman swim leg is about 3.8 kilometers.",
      },
      lt: {
        question: "Maždaug kokio ilgio yra „Ironman” triatlono plaukimo etapas?",
        correct: "3,8 km",
        distractors: ["1,5 km", "5 km", "2 km", "10 km", "0,5 km"],
        explanation: "„Ironman” plaukimo etapas — apie 3,8 kilometro.",
      },
    },
  },
  {
    id: "spo_su_030",
    category: "sport",
    subTheme: "rules",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Snooker black ball worth most",
    emoji: "🎱",
    translations: {
      en: {
        question: "In snooker, which ball is worth the most points?",
        correct: "Black",
        distractors: ["Red", "Blue", "Pink", "Yellow", "Green"],
        explanation: "The black ball is worth 7 points, the most.",
      },
      lt: {
        question: "Kuris snukerio rutulys vertas daugiausia taškų?",
        correct: "Juodas",
        distractors: ["Raudonas", "Mėlynas", "Rožinis", "Geltonas", "Žalias"],
        explanation: "Juodas rutulys vertas 7 taškų — daugiausia.",
      },
    },
  },
  {
    id: "spo_ek_016",
    category: "sport",
    subTheme: "rules",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Standard outdoor track is 400 m",
    emoji: "🏟️",
    translations: {
      en: {
        question: "What is the length of a standard outdoor running track?",
        correct: "400 meters",
        distractors: ["440 meters", "350 meters", "500 meters", "300 meters", "200 meters"],
        explanation: "A standard outdoor track is 400 meters per lap.",
      },
      lt: {
        question: "Koks standartinio lauko bėgimo tako ilgis?",
        correct: "400 metrų",
        distractors: ["440 metrų", "350 metrų", "500 metrų", "300 metrų", "200 metrų"],
        explanation: "Standartinis lauko takas — 400 metrų ratas.",
      },
    },
  },
  {
    id: "spo_ek_017",
    category: "sport",
    subTheme: "rules",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Triple jump phases hop step jump",
    emoji: "🤸",
    translations: {
      en: {
        question: "The triple jump phases are hop, step and what?",
        correct: "Jump",
        distractors: ["Run", "Leap", "Bound", "Skip", "Stride"],
        explanation: "The triple jump is hop, step and jump.",
      },
      lt: {
        question: "Be šuoliuko ir žingsnio, kuri trečia trišuolio fazė?",
        correct: "Šuolis",
        distractors: ["Bėgimas", "Pašokimas", "Atsispyrimas", "Šuoliavimas", "Žingsniavimas"],
        explanation: "Trišuolis — šuoliukas, žingsnis ir šuolis.",
      },
    },
  },
  {
    id: "spo_ek_018",
    category: "sport",
    subTheme: "history",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Marathon 42.195 km set at 1908 London",
    emoji: "🏃",
    translations: {
      en: {
        question: "The 42.195 km marathon length was set at which 1908 Olympics city?",
        correct: "London",
        distractors: ["Paris", "Athens", "Stockholm", "Antwerp", "Berlin"],
        explanation: "The exact marathon distance was fixed at London 1908.",
      },
      lt: {
        question: "42,195 km maratono ilgis nustatytas kurio miesto 1908 m. olimpinėse?",
        correct: "Londonas",
        distractors: ["Paryžius", "Atėnai", "Stokholmas", "Antverpenas", "Berlynas"],
        explanation: "Tikslus maratono nuotolis nustatytas Londone 1908 m.",
      },
    },
  },
  {
    id: "spo_ek_019",
    category: "sport",
    subTheme: "rules",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "F1 qualifying decides pole position",
    emoji: "🏎️",
    translations: {
      en: {
        question: "In Formula 1, the fastest qualifying lap earns what?",
        correct: "Pole position",
        distractors: ["Fastest lap point", "Grid penalty", "Pit order", "Bonus points", "Podium"],
        explanation: "The fastest qualifier starts from pole position.",
      },
      lt: {
        question: "Ką Formulėje 1 suteikia greičiausias kvalifikacijos ratas?",
        correct: "Pole poziciją",
        distractors: ["Greičiausio rato tašką", "Starto baudą", "Aptarnavimo eilę", "Premijinius taškus", "Podiumą"],
        explanation: "Greičiausias kvalifikacijoje startuoja iš pole pozicijos.",
      },
    },
  },
  {
    id: "spo_ek_020",
    category: "sport",
    subTheme: "rules",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Perfect game 300 in bowling",
    emoji: "🎳",
    translations: {
      en: {
        question: "A perfect score of 300 is possible in which sport?",
        correct: "Bowling",
        distractors: ["Darts", "Snooker", "Archery", "Curling", "Golf"],
        explanation: "A perfect game in bowling scores 300 points.",
      },
      lt: {
        question: "Tobulas 300 taškų rezultatas įmanomas kurioje sporto šakoje?",
        correct: "Boulingas",
        distractors: ["Smiginis", "Snukeris", "Lankininkystė", "Kerlingas", "Golfas"],
        explanation: "Tobulas boulingo žaidimas — 300 taškų.",
      },
    },
  },
  {
    id: "spo_ek_021",
    category: "sport",
    subTheme: "rules",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Archery inner gold worth 10",
    emoji: "🎯",
    translations: {
      en: {
        question: "In archery, the inner gold ring of a target is worth how many points?",
        correct: "10",
        distractors: ["9", "8", "12", "5", "100"],
        explanation: "The innermost gold ring scores 10 points.",
      },
      lt: {
        question: "Lankininkystėje vidinis auksinis taikinio žiedas vertas kiek taškų?",
        correct: "10",
        distractors: ["9", "8", "12", "5", "100"],
        explanation: "Vidinis auksinis žiedas vertas 10 taškų.",
      },
    },
  },
  {
    id: "spo_ek_022",
    category: "sport",
    subTheme: "rules",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Pommel horse is men's gymnastics",
    emoji: "🤸",
    translations: {
      en: {
        question: "Which gymnastics apparatus is used only by male artistic gymnasts?",
        correct: "Pommel horse",
        distractors: ["Balance beam", "Uneven bars", "Trampoline", "Hoop", "Ribbon"],
        explanation: "The pommel horse is a men's artistic gymnastics event.",
      },
      lt: {
        question: "Kuris gimnastikos įrankis naudojamas tik vyrų sportinėje gimnastikoje?",
        correct: "Žirgas su rankenomis",
        distractors: ["Pusiausvyros suolelis", "Skirtingo aukščio sijos", "Batutas", "Lankas", "Kaspinas"],
        explanation: "Žirgas su rankenomis — vyrų sportinės gimnastikos rungtis.",
      },
    },
  },
  {
    id: "spo_ek_023",
    category: "sport",
    subTheme: "rules",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Bishop moves diagonally in chess",
    emoji: "♟️",
    translations: {
      en: {
        question: "In chess, which piece moves only diagonally?",
        correct: "Bishop",
        distractors: ["Rook", "Knight", "Queen", "King", "Pawn"],
        explanation: "The bishop moves any number of squares diagonally.",
      },
      lt: {
        question: "Šachmatuose kuri figūra juda tik įstrižai?",
        correct: "Rikis",
        distractors: ["Bokštas", "Žirgas", "Valdovė", "Karalius", "Pėstininkas"],
        explanation: "Rikis juda įstrižai bet kiek langelių.",
      },
    },
  },
  {
    id: "spo_ek_024",
    category: "sport",
    subTheme: "history",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Haka by New Zealand rugby team",
    emoji: "🏉",
    translations: {
      en: {
        question: "The haka is performed before matches by which country's rugby team?",
        correct: "New Zealand",
        distractors: ["Australia", "South Africa", "England", "Fiji", "Samoa"],
        explanation: "New Zealand's rugby team performs the haka.",
      },
      lt: {
        question: "Haka prieš rungtynes atlieka kurios šalies regbio komanda?",
        correct: "Naujoji Zelandija",
        distractors: ["Australija", "Pietų Afrika", "Anglija", "Fidžis", "Samoa"],
        explanation: "Haka atlieka Naujosios Zelandijos regbio komanda.",
      },
    },
  },
  {
    id: "spo_ek_025",
    category: "sport",
    subTheme: "rules",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Tennis ace is untouched serve",
    emoji: "🎾",
    translations: {
      en: {
        question: "In tennis, a serve the opponent cannot touch is called a what?",
        correct: "Ace",
        distractors: ["Deuce", "Let", "Fault", "Lob", "Volley"],
        explanation: "An ace is a serve won without the opponent touching it.",
      },
      lt: {
        question: "Kaip tenise vadinamas padavimas, kurio varžovas net nepaliečia?",
        correct: "Ace",
        distractors: ["Deuce", "Let", "Klaida", "Lob", "Volėjus"],
        explanation: "„Ace” — padavimas, laimėtas varžovui jo nepalietus.",
      },
    },
  },
  {
    id: "spo_ek_026",
    category: "sport",
    subTheme: "rules",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Knight controls 8 squares from center",
    emoji: "♞",
    translations: {
      en: {
        question: "From the center of a chessboard, a knight can move to how many squares?",
        correct: "8",
        distractors: ["6", "4", "2", "10", "12"],
        explanation: "A centrally placed knight reaches 8 squares.",
      },
      lt: {
        question: "Iš šachmatų lentos centro žirgas gali šokti į kiek langelių?",
        correct: "8",
        distractors: ["6", "4", "2", "10", "12"],
        explanation: "Centre stovintis žirgas pasiekia 8 langelius.",
      },
    },
  },
  {
    id: "spo_ek_027",
    category: "sport",
    subTheme: "history",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Lord Stanley was Governor General of Canada",
    emoji: "🏒",
    translations: {
      en: {
        question: "The Stanley Cup is named after a man who held which role in Canada?",
        correct: "Governor General",
        distractors: ["Prime Minister", "Mayor", "King", "President", "Senator"],
        explanation: "Lord Stanley was Canada's Governor General.",
      },
      lt: {
        question: "Stenlio taurė pavadinta žmogaus, ėjusio kurias pareigas Kanadoje, garbei?",
        correct: "Generalgubernatorius",
        distractors: ["Ministras pirmininkas", "Meras", "Karalius", "Prezidentas", "Senatorius"],
        explanation: "Lordas Stenlis buvo Kanados generalgubernatorius.",
      },
    },
  },
  {
    id: "spo_ek_028",
    category: "sport",
    subTheme: "rules",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Tour de France climber jersey is polka dot",
    emoji: "🚵",
    translations: {
      en: {
        question: "What pattern is the Tour de France King of the Mountains jersey?",
        correct: "Red polka dots",
        distractors: ["Solid yellow", "Solid green", "Solid white", "Blue stripes", "Solid black"],
        explanation: "The best climber wears a white jersey with red polka dots.",
      },
      lt: {
        question: "Kokio rašto yra Tour de France kalnų karaliaus marškinėliai?",
        correct: "Raudoni taškeliai",
        distractors: ["Vientisai geltoni", "Vientisai žali", "Vientisai balti", "Mėlyni dryžiai", "Vientisai juodi"],
        explanation: "Geriausias kalnų lipikas vilki baltus marškinėlius su raudonais taškeliais.",
      },
    },
  },
  {
    id: "spo_ek_029",
    category: "sport",
    subTheme: "rules",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Modern pentathlon five events",
    emoji: "🤺",
    translations: {
      en: {
        question: "Which of these is NOT one of the five modern pentathlon events?",
        correct: "Cycling",
        distractors: ["Fencing", "Swimming", "Shooting", "Running", "Horse riding"],
        explanation: "Cycling is not part of the modern pentathlon.",
      },
      lt: {
        question: "Kuri iš šių NĖRA viena iš penkių šiuolaikinės penkiakovės rungčių?",
        correct: "Dviračiai",
        distractors: ["Fechtavimas", "Plaukimas", "Šaudymas", "Bėgimas", "Jojimas"],
        explanation: "Dviračiai nėra šiuolaikinės penkiakovės dalis.",
      },
    },
  },
  {
    id: "spo_ek_030",
    category: "sport",
    subTheme: "rules",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Rugby penalty kick worth 3",
    emoji: "🏉",
    translations: {
      en: {
        question: "In rugby union, how many points is a successful penalty kick worth?",
        correct: "3",
        distractors: ["2", "5", "4", "6", "7"],
        explanation: "A penalty kick in rugby union scores 3 points.",
      },
      lt: {
        question: "Regbyje (union) kiek taškų vertas sėkmingas baudos spyris?",
        correct: "3",
        distractors: ["2", "5", "4", "6", "7"],
        explanation: "Baudos spyris regbyje vertas 3 taškų.",
      },
    },
  },
];
