/**
 * sportContent — „Sportas” trivijos klausimai (EN + LT).
 *
 * Po 15 klausimų kiekvienam lygiui (lengvas/vidutinis/sunkus/ekstremalus) = 60.
 * Temos: olimpinės žaidynės, populiarūs sportai, taisyklės, istoriniai faktai.
 * Vengiame greitai senstančių faktų (dabartiniai čempionai) — tik tvarūs faktai.
 *
 * TAISYKLĖS (Manifestas):
 *   - 1 teisingas + 5 distractors; visi 6 variantai VISOSE kalbose ≤46 simbolių;
 *   - faktai 100% patikrinti (sourceVerified); neutralu (jokios politikos/religijos);
 *   - LT vidinės kabutės tik „...” (ne ASCII "); detalės — į explanation, ne į variantą.
 *
 * Formatas — žr. triviaTypes.ts (TriviaQuestion). category visada "sport".
 */

import { TriviaQuestion } from "./triviaTypes";

export const SPORT_QUESTIONS: TriviaQuestion[] = [
  // ======================= LENGVAS (Easy) =======================
  {
    id: "spo_le_001",
    category: "sport",
    subTheme: "rules",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Football basics (11 players)",
    emoji: "⚽",
    translations: {
      en: {
        question: "How many players are on a football (soccer) team on the field?",
        correct: "11",
        distractors: ["9", "10", "12", "5", "7"],
        explanation: "A football team fields 11 players including the keeper.",
      },
      lt: {
        question: "Kiek žaidėjų aikštėje turi futbolo komanda?",
        correct: "11",
        distractors: ["9", "10", "12", "5", "7"],
        explanation: "Futbolo komandoje aikštėje 11 žaidėjų su vartininku.",
      },
    },
  },
  {
    id: "spo_le_002",
    category: "sport",
    subTheme: "equipment",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Basketball basics (hoop)",
    emoji: "🏀",
    translations: {
      en: {
        question: "In basketball, you score by putting the ball where?",
        correct: "Through the hoop",
        distractors: ["In a net goal", "Over a bar", "In a hole", "Past a line", "Into a box"],
        explanation: "Points are scored by shooting through the hoop.",
      },
      lt: {
        question: "Krepšinyje taškai pelnomi įmetus kamuolį kur?",
        correct: "Pro krepšį",
        distractors: ["Į vartus", "Virš kartelės", "Į duobutę", "Už linijos", "Į dėžę"],
        explanation: "Taškai pelnomi įmetus kamuolį pro krepšį.",
      },
    },
  },
  {
    id: "spo_le_003",
    category: "sport",
    subTheme: "olympics",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Olympic symbol (five rings)",
    emoji: "🏅",
    translations: {
      en: {
        question: "How many rings are on the Olympic flag?",
        correct: "5",
        distractors: ["3", "4", "6", "7", "8"],
        explanation: "The Olympic flag has five interlocking rings.",
      },
      lt: {
        question: "Kiek žiedų yra olimpinėje vėliavoje?",
        correct: "5",
        distractors: ["3", "4", "6", "7", "8"],
        explanation: "Olimpinėje vėliavoje yra penki susikabinę žiedai.",
      },
    },
  },
  {
    id: "spo_le_004",
    category: "sport",
    subTheme: "equipment",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Tennis basics (racket)",
    emoji: "🎾",
    translations: {
      en: {
        question: "Which tool do you use to hit a tennis ball?",
        correct: "Racket",
        distractors: ["Bat", "Club", "Stick", "Paddle", "Cue"],
        explanation: "Tennis is played with a stringed racket.",
      },
      lt: {
        question: "Kuo mušamas teniso kamuoliukas?",
        correct: "Rakete",
        distractors: ["Lazda", "Bita", "Pagaliuku", "Mentele", "Kiju"],
        explanation: "Tenisas žaidžiamas su rakete.",
      },
    },
  },
  {
    id: "spo_le_005",
    category: "sport",
    subTheme: "rules",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Football scoring (goal)",
    emoji: "🥅",
    translations: {
      en: {
        question: "In football, scoring is called what?",
        correct: "A goal",
        distractors: ["A point", "A run", "A basket", "A try", "A touchdown"],
        explanation: "Putting the ball in the net is called a goal.",
      },
      lt: {
        question: "Kaip futbole vadinamas pelnytas taškas?",
        correct: "Įvartis",
        distractors: ["Taškas", "Perbėgimas", "Metimas", "Bandymas", "Smūgis"],
        explanation: "Kamuolio įmušimas į vartus vadinamas įvarčiu.",
      },
    },
  },
  {
    id: "spo_le_006",
    category: "sport",
    subTheme: "sports",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Swimming basics (water sport)",
    emoji: "🏊",
    translations: {
      en: {
        question: "Which sport takes place in a pool?",
        correct: "Swimming",
        distractors: ["Cycling", "Boxing", "Archery", "Skiing", "Fencing"],
        explanation: "Swimming races are held in pools.",
      },
      lt: {
        question: "Kuri sporto šaka vyksta baseine?",
        correct: "Plaukimas",
        distractors: ["Dviračiai", "Boksas", "Šaudymas iš lanko", "Slidinėjimas", "Fechtavimas"],
        explanation: "Plaukimo varžybos vyksta baseinuose.",
      },
    },
  },
  {
    id: "spo_le_007",
    category: "sport",
    subTheme: "equipment",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Golf basics (hole)",
    emoji: "⛳",
    translations: {
      en: {
        question: "In golf, you hit the ball into a what?",
        correct: "Hole",
        distractors: ["Net", "Basket", "Goal", "Pocket", "Ring"],
        explanation: "Golfers aim to hit the ball into holes.",
      },
      lt: {
        question: "Golfe kamuoliukas varomas į ką?",
        correct: "Duobutę",
        distractors: ["Tinklą", "Krepšį", "Vartus", "Kišenę", "Žiedą"],
        explanation: "Golfo tikslas — įvaryti kamuoliuką į duobutes.",
      },
    },
  },
  {
    id: "spo_le_008",
    category: "sport",
    subTheme: "sports",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Cycling basics (bicycle)",
    emoji: "🚴",
    translations: {
      en: {
        question: "Which sport uses a bicycle?",
        correct: "Cycling",
        distractors: ["Rowing", "Boxing", "Diving", "Wrestling", "Sailing"],
        explanation: "Cycling is racing on bicycles.",
      },
      lt: {
        question: "Kuri sporto šaka naudoja dviratį?",
        correct: "Dviračių sportas",
        distractors: ["Irklavimas", "Boksas", "Šuoliai į vandenį", "Imtynės", "Buriavimas"],
        explanation: "Dviračių sportas — lenktynės dviračiais.",
      },
    },
  },
  {
    id: "spo_le_009",
    category: "sport",
    subTheme: "rules",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Boxing basics (ring)",
    emoji: "🥊",
    translations: {
      en: {
        question: "Where does a boxing match take place?",
        correct: "A ring",
        distractors: ["A court", "A pitch", "A track", "A pool", "A rink"],
        explanation: "Boxers compete inside a square ring.",
      },
      lt: {
        question: "Kur vyksta bokso kova?",
        correct: "Ringe",
        distractors: ["Aikštelėje", "Aikštėje", "Take", "Baseine", "Čiuožykloje"],
        explanation: "Boksininkai kaunasi kvadratiniame ringe.",
      },
    },
  },
  {
    id: "spo_le_010",
    category: "sport",
    subTheme: "sports",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Ice hockey basics (puck)",
    emoji: "🏒",
    translations: {
      en: {
        question: "In ice hockey, players hit a what?",
        correct: "Puck",
        distractors: ["Ball", "Shuttle", "Disc of clay", "Ring", "Cone"],
        explanation: "Ice hockey is played with a rubber puck.",
      },
      lt: {
        question: "Ką muša ledo ritulio žaidėjai?",
        correct: "Ritulį",
        distractors: ["Kamuolį", "Plunksniuką", "Molio diską", "Žiedą", "Kūgį"],
        explanation: "Ledo ritulys žaidžiamas guminiu rituliu.",
      },
    },
  },
  {
    id: "spo_le_011",
    category: "sport",
    subTheme: "rules",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Marathon distance (about 42 km)",
    emoji: "🏃",
    translations: {
      en: {
        question: "A marathon is roughly how many kilometers?",
        correct: "42",
        distractors: ["10", "21", "30", "50", "100"],
        explanation: "A marathon is about 42.2 kilometers.",
      },
      lt: {
        question: "Kiek maždaug kilometrų yra maratonas?",
        correct: "42",
        distractors: ["10", "21", "30", "50", "100"],
        explanation: "Maratonas yra apie 42,2 kilometro.",
      },
    },
  },
  {
    id: "spo_le_012",
    category: "sport",
    subTheme: "equipment",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Baseball basics (bat)",
    emoji: "⚾",
    translations: {
      en: {
        question: "In baseball, the ball is hit with a what?",
        correct: "Bat",
        distractors: ["Racket", "Club", "Stick", "Paddle", "Cue"],
        explanation: "Baseball batters swing a wooden or metal bat.",
      },
      lt: {
        question: "Kuo beisbole mušamas kamuolys?",
        correct: "Bita",
        distractors: ["Rakete", "Lazda", "Pagaliuku", "Mentele", "Kiju"],
        explanation: "Beisbolo mušėjai naudoja medinę ar metalinę bitą.",
      },
    },
  },
  {
    id: "spo_le_013",
    category: "sport",
    subTheme: "sports",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Skiing basics (snow sport)",
    emoji: "⛷️",
    translations: {
      en: {
        question: "Skiing is usually done on what surface?",
        correct: "Snow",
        distractors: ["Sand", "Water", "Grass", "Ice rink", "Clay"],
        explanation: "Alpine skiing is done on snowy slopes.",
      },
      lt: {
        question: "Ant kokio paviršiaus dažniausiai slidinėjama?",
        correct: "Sniego",
        distractors: ["Smėlio", "Vandens", "Žolės", "Ledo", "Molio"],
        explanation: "Kalnų slidinėjimas vyksta apsnigtais šlaitais.",
      },
    },
  },
  {
    id: "spo_le_014",
    category: "sport",
    subTheme: "rules",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Football match halves (two)",
    emoji: "⏱️",
    translations: {
      en: {
        question: "A football match is split into how many halves?",
        correct: "2",
        distractors: ["3", "4", "1", "5", "6"],
        explanation: "Football has two halves of 45 minutes.",
      },
      lt: {
        question: "Į kiek kėlinių dalijamos futbolo rungtynės?",
        correct: "2",
        distractors: ["3", "4", "1", "5", "6"],
        explanation: "Futbole yra du 45 minučių kėliniai.",
      },
    },
  },
  {
    id: "spo_le_015",
    category: "sport",
    subTheme: "sports",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Volleyball basics (net)",
    emoji: "🏐",
    translations: {
      en: {
        question: "Volleyball is played over a what?",
        correct: "Net",
        distractors: ["Wall", "Goal", "Bar", "Fence", "Rope ring"],
        explanation: "Volleyball teams hit the ball over a high net.",
      },
      lt: {
        question: "Per ką žaidžiamas tinklinis?",
        correct: "Tinklą",
        distractors: ["Sieną", "Vartus", "Kartelę", "Tvorą", "Žiedą"],
        explanation: "Tinklinio komandos muša kamuolį per aukštą tinklą.",
      },
    },
  },

  // ======================= VIDUTINIS (Medium) =======================
  {
    id: "spo_me_001",
    category: "sport",
    subTheme: "olympics",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Olympic history (Athens 1896)",
    emoji: "🏛️",
    translations: {
      en: {
        question: "The first modern Olympics in 1896 were held in which city?",
        correct: "Athens",
        distractors: ["Paris", "London", "Rome", "Berlin", "Stockholm"],
        explanation: "The first modern Olympic Games were in Athens, 1896.",
      },
      lt: {
        question: "Kuriame mieste vyko pirmosios moderniosios olimpinės 1896 m.?",
        correct: "Atėnai",
        distractors: ["Paryžius", "Londonas", "Roma", "Berlynas", "Stokholmas"],
        explanation: "Pirmosios moderniosios olimpinės vyko Atėnuose, 1896 m.",
      },
    },
  },
  {
    id: "spo_me_002",
    category: "sport",
    subTheme: "rules",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Basketball scoring (free throw = 1)",
    emoji: "🏀",
    translations: {
      en: {
        question: "How many points is a basketball free throw worth?",
        correct: "1",
        distractors: ["2", "3", "4", "5", "0"],
        explanation: "A made free throw is worth one point.",
      },
      lt: {
        question: "Kiek taškų krepšinyje vertas baudos metimas?",
        correct: "1",
        distractors: ["2", "3", "4", "5", "0"],
        explanation: "Pataikytas baudos metimas vertas vieno taško.",
      },
    },
  },
  {
    id: "spo_me_003",
    category: "sport",
    subTheme: "tennis",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Tennis venue (Wimbledon, London)",
    emoji: "🎾",
    translations: {
      en: {
        question: "The Wimbledon tennis tournament is held in which country?",
        correct: "England",
        distractors: ["France", "USA", "Australia", "Spain", "Germany"],
        explanation: "Wimbledon is played in London, England.",
      },
      lt: {
        question: "Kurioje šalyje vyksta Vimbldono teniso turnyras?",
        correct: "Anglija",
        distractors: ["Prancūzija", "JAV", "Australija", "Ispanija", "Vokietija"],
        explanation: "Vimbldonas žaidžiamas Londone, Anglijoje.",
      },
    },
  },
  {
    id: "spo_me_004",
    category: "sport",
    subTheme: "football",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "FIFA World Cup frequency (every 4 years)",
    emoji: "🏆",
    translations: {
      en: {
        question: "How often is the FIFA World Cup normally held?",
        correct: "Every 4 years",
        distractors: ["Every year", "Every 2 years", "Every 3 years", "Every 5 years", "Every 6 years"],
        explanation: "The World Cup is held every four years.",
      },
      lt: {
        question: "Kas kiek paprastai vyksta FIFA pasaulio futbolo čempionatas?",
        correct: "Kas 4 metus",
        distractors: ["Kasmet", "Kas 2 metus", "Kas 3 metus", "Kas 5 metus", "Kas 6 metus"],
        explanation: "Pasaulio čempionatas vyksta kas ketverius metus.",
      },
    },
  },
  {
    id: "spo_me_005",
    category: "sport",
    subTheme: "rules",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Rugby team size (15)",
    emoji: "🏉",
    translations: {
      en: {
        question: "How many players are in a rugby union team on the field?",
        correct: "15",
        distractors: ["11", "13", "12", "9", "7"],
        explanation: "Rugby union teams field 15 players.",
      },
      lt: {
        question: "Kiek žaidėjų aikštėje turi regbio komanda?",
        correct: "15",
        distractors: ["11", "13", "12", "9", "7"],
        explanation: "Regbio (union) komandoje aikštėje 15 žaidėjų.",
      },
    },
  },
  {
    id: "spo_me_006",
    category: "sport",
    subTheme: "olympics",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Olympic medals order (gold first)",
    emoji: "🥇",
    translations: {
      en: {
        question: "Which Olympic medal is awarded for first place?",
        correct: "Gold",
        distractors: ["Silver", "Bronze", "Platinum", "Diamond", "Copper"],
        explanation: "First place earns the gold medal.",
      },
      lt: {
        question: "Kuris olimpinis medalis skiriamas už pirmą vietą?",
        correct: "Auksas",
        distractors: ["Sidabras", "Bronza", "Platina", "Deimantas", "Varis"],
        explanation: "Už pirmą vietą skiriamas aukso medalis.",
      },
    },
  },
  {
    id: "spo_me_007",
    category: "sport",
    subTheme: "sports",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Badminton equipment (shuttlecock)",
    emoji: "🏸",
    translations: {
      en: {
        question: "Badminton is played by hitting a what?",
        correct: "Shuttlecock",
        distractors: ["Ball", "Puck", "Ring", "Disc", "Cork ball"],
        explanation: "Badminton uses a feathered shuttlecock.",
      },
      lt: {
        question: "Ką muša badmintono žaidėjai?",
        correct: "Plunksniuką",
        distractors: ["Kamuolį", "Ritulį", "Žiedą", "Diską", "Kamštį"],
        explanation: "Badmintone naudojamas plunksnuotas plunksniukas.",
      },
    },
  },
  {
    id: "spo_me_008",
    category: "sport",
    subTheme: "football",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Football card (red = sent off)",
    emoji: "🟥",
    translations: {
      en: {
        question: "Which card sends a football player off the field?",
        correct: "Red card",
        distractors: ["Yellow card", "Blue card", "Green card", "Black card", "White card"],
        explanation: "A red card means the player is sent off.",
      },
      lt: {
        question: "Kuri kortelė pašalina futbolininką iš aikštės?",
        correct: "Raudona kortelė",
        distractors: ["Geltona kortelė", "Mėlyna kortelė", "Žalia kortelė", "Juoda kortelė", "Balta kortelė"],
        explanation: "Raudona kortelė reiškia žaidėjo pašalinimą.",
      },
    },
  },
  {
    id: "spo_me_009",
    category: "sport",
    subTheme: "sports",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Formula 1 (motor racing)",
    emoji: "🏎️",
    translations: {
      en: {
        question: "Formula 1 is a top level of what sport?",
        correct: "Car racing",
        distractors: ["Cycling", "Sailing", "Horse racing", "Running", "Rowing"],
        explanation: "Formula 1 is elite open-wheel car racing.",
      },
      lt: {
        question: "Formulė 1 yra aukščiausias kurio sporto lygis?",
        correct: "Automobilių lenktynės",
        distractors: ["Dviračių", "Buriavimo", "Žirgų lenktynių", "Bėgimo", "Irklavimo"],
        explanation: "Formulė 1 — elitinės atvirų ratų automobilių lenktynės.",
      },
    },
  },
  {
    id: "spo_me_010",
    category: "sport",
    subTheme: "rules",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Tennis scoring (love = 0)",
    emoji: "🎾",
    translations: {
      en: {
        question: "In tennis, the term love means what score?",
        correct: "Zero",
        distractors: ["One", "Fifteen", "Forty", "Match point", "Deuce"],
        explanation: "In tennis, love means a score of zero.",
      },
      lt: {
        question: "Ką tenise reiškia terminas „love”?",
        correct: "Nulį",
        distractors: ["Vieną", "Penkiolika", "Keturiasdešimt", "Mečbolą", "Lygiąsias"],
        explanation: "Tenise „love” reiškia nulinį rezultatą.",
      },
    },
  },
  {
    id: "spo_me_011",
    category: "sport",
    subTheme: "olympics",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Winter Olympics sports (figure skating)",
    emoji: "⛸️",
    translations: {
      en: {
        question: "Which of these is a Winter Olympic sport?",
        correct: "Figure skating",
        distractors: ["Beach volleyball", "Surfing", "Rowing", "Field hockey", "Water polo"],
        explanation: "Figure skating is a Winter Olympic event.",
      },
      lt: {
        question: "Kuris iš šių yra žiemos olimpinis sportas?",
        correct: "Dailusis čiuožimas",
        distractors: ["Paplūdimio tinklinis", "Banglentės", "Irklavimas", "Žolės riedulys", "Vandensvydis"],
        explanation: "Dailusis čiuožimas — žiemos olimpinė šaka.",
      },
    },
  },
  {
    id: "spo_me_012",
    category: "sport",
    subTheme: "basketball",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Basketball origin (USA, Naismith)",
    emoji: "🏀",
    translations: {
      en: {
        question: "In which country was basketball invented?",
        correct: "USA",
        distractors: ["Canada", "England", "France", "Spain", "Italy"],
        explanation: "Basketball was invented in the USA in 1891.",
      },
      lt: {
        question: "Kurioje šalyje sukurtas krepšinis?",
        correct: "JAV",
        distractors: ["Kanada", "Anglija", "Prancūzija", "Ispanija", "Italija"],
        explanation: "Krepšinis sukurtas JAV 1891 metais.",
      },
    },
  },
  {
    id: "spo_me_013",
    category: "sport",
    subTheme: "sports",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Athletics (sprint distance 100 m)",
    emoji: "🏃",
    translations: {
      en: {
        question: "What is the shortest standard Olympic sprint distance?",
        correct: "100 meters",
        distractors: ["50 meters", "200 meters", "400 meters", "60 meters", "150 meters"],
        explanation: "The 100 meters is the shortest standard Olympic sprint.",
      },
      lt: {
        question: "Koks trumpiausias standartinis olimpinis sprinto nuotolis?",
        correct: "100 metrų",
        distractors: ["50 metrų", "200 metrų", "400 metrų", "60 metrų", "150 metrų"],
        explanation: "100 metrų — trumpiausias standartinis olimpinis sprintas.",
      },
    },
  },
  {
    id: "spo_me_014",
    category: "sport",
    subTheme: "football",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Football venue term (pitch)",
    emoji: "🟩",
    translations: {
      en: {
        question: "What is the football playing field called?",
        correct: "Pitch",
        distractors: ["Court", "Rink", "Track", "Ring", "Diamond"],
        explanation: "A football field is commonly called a pitch.",
      },
      lt: {
        question: "Kaip vadinama futbolo žaidimo aikštė?",
        correct: "Aikštė",
        distractors: ["Kortas", "Čiuožykla", "Takas", "Ringas", "Deimantas"],
        explanation: "Futbolo žaidimo plotas vadinamas aikšte.",
      },
    },
  },
  {
    id: "spo_me_015",
    category: "sport",
    subTheme: "sports",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Gymnastics apparatus (balance beam)",
    emoji: "🤸",
    translations: {
      en: {
        question: "The balance beam is used in which sport?",
        correct: "Gymnastics",
        distractors: ["Diving", "Boxing", "Fencing", "Rowing", "Archery"],
        explanation: "The balance beam is a gymnastics apparatus.",
      },
      lt: {
        question: "Kurioje sporto šakoje naudojamas pusiausvyros suolelis?",
        correct: "Gimnastika",
        distractors: ["Šuoliai į vandenį", "Boksas", "Fechtavimas", "Irklavimas", "Šaudymas iš lanko"],
        explanation: "Pusiausvyros suolelis — gimnastikos įrankis.",
      },
    },
  },

  // ======================= SUNKUS (Hard) =======================
  {
    id: "spo_su_001",
    category: "sport",
    subTheme: "olympics",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Olympic host (Tokyo 1964 first in Asia)",
    emoji: "🗼",
    translations: {
      en: {
        question: "Which city hosted the first Olympics held in Asia, in 1964?",
        correct: "Tokyo",
        distractors: ["Beijing", "Seoul", "Bangkok", "Delhi", "Osaka"],
        explanation: "Tokyo hosted Asia's first Olympics in 1964.",
      },
      lt: {
        question: "Kuris miestas 1964 m. surengė pirmąsias olimpines Azijoje?",
        correct: "Tokijas",
        distractors: ["Pekinas", "Seulas", "Bankokas", "Delis", "Osaka"],
        explanation: "Tokijas surengė pirmąsias olimpines Azijoje 1964 m.",
      },
    },
  },
  {
    id: "spo_su_002",
    category: "sport",
    subTheme: "rules",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Cricket basics (wickets, bat-and-ball)",
    emoji: "🏏",
    translations: {
      en: {
        question: "In which sport do players defend wickets?",
        correct: "Cricket",
        distractors: ["Baseball", "Hockey", "Polo", "Lacrosse", "Softball"],
        explanation: "Wickets are defended in the sport of cricket.",
      },
      lt: {
        question: "Kuriame sporte žaidėjai gina vartelius (wickets)?",
        correct: "Kriketas",
        distractors: ["Beisbolas", "Riedulys", "Polas", "Lakrosas", "Softbolas"],
        explanation: "Varteliai ginami kriketo žaidime.",
      },
    },
  },
  {
    id: "spo_su_003",
    category: "sport",
    subTheme: "football",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Football term (hat-trick = three goals)",
    emoji: "⚽",
    translations: {
      en: {
        question: "A hat-trick means one player scores how many goals?",
        correct: "Three",
        distractors: ["Two", "Four", "Five", "Six", "Seven"],
        explanation: "A hat-trick is three goals by one player in a match.",
      },
      lt: {
        question: "„Hat-trick” reiškia, kad vienas žaidėjas pelno kiek įvarčių?",
        correct: "Tris",
        distractors: ["Du", "Keturis", "Penkis", "Šešis", "Septynis"],
        explanation: "Hat-trickas — trys vieno žaidėjo įvarčiai per rungtynes.",
      },
    },
  },
  {
    id: "spo_su_004",
    category: "sport",
    subTheme: "tennis",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Tennis surface (Roland Garros clay)",
    emoji: "🎾",
    translations: {
      en: {
        question: "The French Open is played on which surface?",
        correct: "Clay",
        distractors: ["Grass", "Hard court", "Carpet", "Wood", "Concrete"],
        explanation: "The French Open is played on clay courts.",
      },
      lt: {
        question: "Ant kokios dangos žaidžiamas Prancūzijos atvirasis (French Open)?",
        correct: "Molio",
        distractors: ["Žolės", "Kieto korto", "Kilimo", "Medžio", "Betono"],
        explanation: "Prancūzijos atvirasis žaidžiamas ant molio kortų.",
      },
    },
  },
  {
    id: "spo_su_005",
    category: "sport",
    subTheme: "sports",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Cycling event (Tour de France, road race)",
    emoji: "🚴",
    translations: {
      en: {
        question: "The Tour de France is a major race in which sport?",
        correct: "Cycling",
        distractors: ["Running", "Motorsport", "Rowing", "Triathlon", "Skating"],
        explanation: "The Tour de France is a famous cycling race.",
      },
      lt: {
        question: "Tour de France yra svarbios kurios sporto šakos lenktynės?",
        correct: "Dviračių",
        distractors: ["Bėgimo", "Automobilių", "Irklavimo", "Triatlono", "Čiuožimo"],
        explanation: "Tour de France — garsios dviračių lenktynės.",
      },
    },
  },
  {
    id: "spo_su_006",
    category: "sport",
    subTheme: "rules",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Volleyball set points (25)",
    emoji: "🏐",
    translations: {
      en: {
        question: "A standard volleyball set is usually played to how many points?",
        correct: "25",
        distractors: ["15", "21", "11", "30", "20"],
        explanation: "Volleyball sets are usually played to 25 points.",
      },
      lt: {
        question: "Iki kiek taškų paprastai žaidžiamas tinklinio setas?",
        correct: "25",
        distractors: ["15", "21", "11", "30", "20"],
        explanation: "Tinklinio setai paprastai žaidžiami iki 25 taškų.",
      },
    },
  },
  {
    id: "spo_su_007",
    category: "sport",
    subTheme: "olympics",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Olympic motto (Faster, Higher, Stronger)",
    emoji: "🏅",
    translations: {
      en: {
        question: "The classic Olympic motto begins with which word?",
        correct: "Faster",
        distractors: ["Braver", "Bigger", "Bolder", "Smarter", "Longer"],
        explanation: "The motto is Faster, Higher, Stronger.",
      },
      lt: {
        question: "Kuriuo žodžiu prasideda klasikinis olimpinis šūkis?",
        correct: "Greičiau",
        distractors: ["Drąsiau", "Didžiau", "Smarkiau", "Protingiau", "Ilgiau"],
        explanation: "Šūkis — „Greičiau, aukščiau, stipriau”.",
      },
    },
  },
  {
    id: "spo_su_008",
    category: "sport",
    subTheme: "sports",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Triathlon disciplines (swim-bike-run)",
    emoji: "🏊",
    translations: {
      en: {
        question: "A triathlon combines swimming, cycling and what?",
        correct: "Running",
        distractors: ["Rowing", "Skiing", "Boxing", "Jumping", "Climbing"],
        explanation: "Triathlon is swimming, cycling and running.",
      },
      lt: {
        question: "Triatlonas jungia plaukimą, dviračius ir ką?",
        correct: "Bėgimą",
        distractors: ["Irklavimą", "Slidinėjimą", "Boksą", "Šokimą", "Laipiojimą"],
        explanation: "Triatlonas — plaukimas, dviračiai ir bėgimas.",
      },
    },
  },
  {
    id: "spo_su_009",
    category: "sport",
    subTheme: "football",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Football pitch markings (penalty spot ~11 m)",
    emoji: "⚽",
    translations: {
      en: {
        question: "A football penalty kick is taken about how far from goal?",
        correct: "11 meters",
        distractors: ["5 meters", "9 meters", "16 meters", "20 meters", "7 meters"],
        explanation: "The penalty spot is about 11 meters from goal.",
      },
      lt: {
        question: "Iš maždaug kokio atstumo mušamas futbolo baudinys?",
        correct: "11 metrų",
        distractors: ["5 metrų", "9 metrų", "16 metrų", "20 metrų", "7 metrų"],
        explanation: "Baudinio taškas yra maždaug 11 metrų nuo vartų.",
      },
    },
  },
  {
    id: "spo_su_010",
    category: "sport",
    subTheme: "sports",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Fencing weapons (foil, epee, sabre)",
    emoji: "🤺",
    translations: {
      en: {
        question: "Which of these is a fencing weapon?",
        correct: "Sabre",
        distractors: ["Javelin", "Baton", "Discus", "Mallet", "Cue"],
        explanation: "Foil, epee and sabre are fencing weapons.",
      },
      lt: {
        question: "Kuris iš šių yra fechtavimo ginklas?",
        correct: "Kardas",
        distractors: ["Ietis", "Lazdelė", "Diskas", "Plaktukas", "Kijus"],
        explanation: "Rapyra, špaga ir kardas — fechtavimo ginklai.",
      },
    },
  },
  {
    id: "spo_su_011",
    category: "sport",
    subTheme: "basketball",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Basketball rim height (3.05 m)",
    emoji: "🏀",
    translations: {
      en: {
        question: "How high is a standard basketball hoop?",
        correct: "3.05 meters",
        distractors: ["2.5 meters", "3.5 meters", "4 meters", "2 meters", "3.65 meters"],
        explanation: "A basketball rim sits 3.05 meters (10 ft) high.",
      },
      lt: {
        question: "Kokiame aukštyje yra standartinis krepšinio lankas?",
        correct: "3,05 metro",
        distractors: ["2,5 metro", "3,5 metro", "4 metrų", "2 metrų", "3,65 metro"],
        explanation: "Krepšinio lankas yra 3,05 metro (10 pėdų) aukštyje.",
      },
    },
  },
  {
    id: "spo_su_012",
    category: "sport",
    subTheme: "sports",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Golf term (one under par = birdie)",
    emoji: "⛳",
    translations: {
      en: {
        question: "In golf, one stroke under par on a hole is called a what?",
        correct: "Birdie",
        distractors: ["Bogey", "Eagle", "Par", "Albatross", "Ace"],
        explanation: "One under par on a hole is a birdie.",
      },
      lt: {
        question: "Golfe vienas smūgis mažiau už par duobutėje vadinamas kaip?",
        correct: "Birdie",
        distractors: ["Bogey", "Eagle", "Par", "Albatross", "Ace"],
        explanation: "Vienas smūgis mažiau už par duobutėje — birdie.",
      },
    },
  },
  {
    id: "spo_su_013",
    category: "sport",
    subTheme: "olympics",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Olympic flame origin (Olympia, Greece)",
    emoji: "🔥",
    translations: {
      en: {
        question: "The Olympic flame is traditionally lit in which country?",
        correct: "Greece",
        distractors: ["France", "Italy", "Switzerland", "Egypt", "Turkey"],
        explanation: "The Olympic flame is lit in Olympia, Greece.",
      },
      lt: {
        question: "Kurioje šalyje tradiciškai įžiebiama olimpinė ugnis?",
        correct: "Graikija",
        distractors: ["Prancūzija", "Italija", "Šveicarija", "Egiptas", "Turkija"],
        explanation: "Olimpinė ugnis įžiebiama Olimpijoje, Graikijoje.",
      },
    },
  },
  {
    id: "spo_su_014",
    category: "sport",
    subTheme: "rules",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Ice hockey team size (6 with goalie)",
    emoji: "🏒",
    translations: {
      en: {
        question: "How many players per team are on the ice in hockey?",
        correct: "6",
        distractors: ["5", "7", "8", "11", "4"],
        explanation: "Ice hockey teams have 6 players including the goalie.",
      },
      lt: {
        question: "Kiek vienos komandos žaidėjų yra ant ledo ritulyje?",
        correct: "6",
        distractors: ["5", "7", "8", "11", "4"],
        explanation: "Ledo ritulyje komandoje 6 žaidėjai su vartininku.",
      },
    },
  },
  {
    id: "spo_su_015",
    category: "sport",
    subTheme: "sports",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Athletics (decathlon = 10 events)",
    emoji: "🏟️",
    translations: {
      en: {
        question: "How many events make up the athletics decathlon?",
        correct: "10",
        distractors: ["5", "7", "8", "12", "15"],
        explanation: "A decathlon is made up of ten track and field events.",
      },
      lt: {
        question: "Iš kiek rungčių sudaryta lengvosios atletikos dešimtkovė?",
        correct: "10",
        distractors: ["5", "7", "8", "12", "15"],
        explanation: "Dešimtkovę sudaro dešimt lengvosios atletikos rungčių.",
      },
    },
  },

  // ======================= EKSTREMALUS (Extreme) =======================
  {
    id: "spo_ek_001",
    category: "sport",
    subTheme: "olympics",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Olympic history (1924 first Winter Games, Chamonix)",
    emoji: "🏔️",
    translations: {
      en: {
        question: "The first Winter Olympics in 1924 were held in which country?",
        correct: "France",
        distractors: ["Switzerland", "Norway", "Austria", "Italy", "Canada"],
        explanation: "The first Winter Olympics were in Chamonix, France.",
      },
      lt: {
        question: "Kurioje šalyje vyko pirmosios žiemos olimpinės 1924 m.?",
        correct: "Prancūzija",
        distractors: ["Šveicarija", "Norvegija", "Austrija", "Italija", "Kanada"],
        explanation: "Pirmosios žiemos olimpinės vyko Šamoni, Prancūzijoje.",
      },
    },
  },
  {
    id: "spo_ek_002",
    category: "sport",
    subTheme: "tennis",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Tennis Grand Slam count (4 tournaments)",
    emoji: "🎾",
    translations: {
      en: {
        question: "How many tournaments make up the tennis Grand Slam?",
        correct: "4",
        distractors: ["3", "5", "6", "2", "8"],
        explanation: "The Grand Slam has four major tournaments.",
      },
      lt: {
        question: "Iš kiek turnyrų sudarytas teniso Didysis kirtis (Grand Slam)?",
        correct: "4",
        distractors: ["3", "5", "6", "2", "8"],
        explanation: "Didįjį kirtį sudaro keturi dideli turnyrai.",
      },
    },
  },
  {
    id: "spo_ek_003",
    category: "sport",
    subTheme: "football",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Football history (first World Cup 1930, Uruguay)",
    emoji: "🏆",
    translations: {
      en: {
        question: "Which country hosted the first FIFA World Cup in 1930?",
        correct: "Uruguay",
        distractors: ["Brazil", "Italy", "Argentina", "France", "England"],
        explanation: "Uruguay hosted and won the first World Cup in 1930.",
      },
      lt: {
        question: "Kuri šalis surengė pirmąjį FIFA pasaulio čempionatą 1930 m.?",
        correct: "Urugvajus",
        distractors: ["Brazilija", "Italija", "Argentina", "Prancūzija", "Anglija"],
        explanation: "Urugvajus surengė ir laimėjo pirmąjį čempionatą 1930 m.",
      },
    },
  },
  {
    id: "spo_ek_004",
    category: "sport",
    subTheme: "sports",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Athletics (Usain Bolt sprint records)",
    emoji: "⚡",
    translations: {
      en: {
        question: "Usain Bolt set world records in which athletics event?",
        correct: "Sprinting",
        distractors: ["Marathon", "High jump", "Shot put", "Pole vault", "Hurdles"],
        explanation: "Bolt set 100 m and 200 m sprint world records.",
      },
      lt: {
        question: "Kurioje atletikos rungtyje pasaulio rekordus pasiekė Usain Bolt?",
        correct: "Sprinte",
        distractors: ["Maratone", "Šuolyje į aukštį", "Rutulio stūmime", "Šuolyje su kartimi", "Barjeruose"],
        explanation: "Bolt pasiekė 100 m ir 200 m sprinto pasaulio rekordus.",
      },
    },
  },
  {
    id: "spo_ek_005",
    category: "sport",
    subTheme: "rules",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Chess board (64 squares)",
    emoji: "♟️",
    translations: {
      en: {
        question: "How many squares are on a standard chess board?",
        correct: "64",
        distractors: ["32", "48", "81", "100", "56"],
        explanation: "A chess board has 8 by 8, that is 64 squares.",
      },
      lt: {
        question: "Kiek langelių yra standartinėje šachmatų lentoje?",
        correct: "64",
        distractors: ["32", "48", "81", "100", "56"],
        explanation: "Šachmatų lentoje 8 kartus 8, tai yra 64 langeliai.",
      },
    },
  },
  {
    id: "spo_ek_006",
    category: "sport",
    subTheme: "basketball",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Basketball history (invented 1891)",
    emoji: "🏀",
    translations: {
      en: {
        question: "In which decade was basketball invented?",
        correct: "1890s",
        distractors: ["1850s", "1870s", "1910s", "1920s", "1940s"],
        explanation: "Basketball was invented in 1891, the 1890s.",
      },
      lt: {
        question: "Kuriame dešimtmetyje sukurtas krepšinis?",
        correct: "1890-aisiais",
        distractors: ["1850-aisiais", "1870-aisiais", "1910-aisiais", "1920-aisiais", "1940-aisiais"],
        explanation: "Krepšinis sukurtas 1891 m., tai yra 1890-aisiais.",
      },
    },
  },
  {
    id: "spo_ek_007",
    category: "sport",
    subTheme: "sports",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Swimming strokes (butterfly one of four)",
    emoji: "🦋",
    translations: {
      en: {
        question: "Which of these is an official competitive swimming stroke?",
        correct: "Butterfly",
        distractors: ["Dolphin spin", "Side glide", "Otter kick", "Frog dive", "Whale roll"],
        explanation: "Butterfly is one of the four competitive strokes.",
      },
      lt: {
        question: "Kuris iš šių yra oficialus varžybinis plaukimo stilius?",
        correct: "Peteliškė",
        distractors: ["Delfino sukinys", "Šoninis slydimas", "Ūdros spyris", "Varlės nėrimas", "Banginio ritinys"],
        explanation: "Peteliškė — vienas iš keturių varžybinių stilių.",
      },
    },
  },
  {
    id: "spo_ek_008",
    category: "sport",
    subTheme: "olympics",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Marathon distance fixed 1908 (42.195 km)",
    emoji: "🏃",
    translations: {
      en: {
        question: "The exact marathon distance is how many kilometers?",
        correct: "42.195",
        distractors: ["40.000", "41.500", "43.000", "42.500", "45.000"],
        explanation: "The official marathon distance is 42.195 km.",
      },
      lt: {
        question: "Koks tikslus maratono nuotolis kilometrais?",
        correct: "42,195",
        distractors: ["40,000", "41,500", "43,000", "42,500", "45,000"],
        explanation: "Oficialus maratono nuotolis — 42,195 km.",
      },
    },
  },
  {
    id: "spo_ek_009",
    category: "sport",
    subTheme: "football",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Football rules (goal width 7.32 m)",
    emoji: "🥅",
    translations: {
      en: {
        question: "How wide is a standard football goal?",
        correct: "7.32 meters",
        distractors: [
          "5 meters",
          "6 meters",
          "8 meters",
          "9.15 meters",
          "11 meters",
        ],
        explanation: "A standard goal is 7.32 m wide and 2.44 m high.",
      },
      lt: {
        question: "Koks standartinių futbolo vartų plotis?",
        correct: "7,32 metro",
        distractors: [
          "5 metrai",
          "6 metrai",
          "8 metrai",
          "9,15 metro",
          "11 metrų",
        ],
        explanation: "Standartiniai vartai yra 7,32 m pločio ir 2,44 m aukščio.",
      },
    },
  },
  {
    id: "spo_ek_010",
    category: "sport",
    subTheme: "sports",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Motorsport (Le Mans 24-hour race)",
    emoji: "🏎️",
    translations: {
      en: {
        question: "The famous Le Mans race lasts how long?",
        correct: "24 hours",
        distractors: ["6 hours", "12 hours", "48 hours", "1 hour", "8 hours"],
        explanation: "The 24 Hours of Le Mans is a day-long endurance race.",
      },
      lt: {
        question: "Kiek trunka garsiosios Le Mano lenktynės?",
        correct: "24 valandas",
        distractors: ["6 valandas", "12 valandų", "48 valandas", "1 valandą", "8 valandas"],
        explanation: "24 Le Mano valandos — parą trunkančios ištvermės lenktynės.",
      },
    },
  },
  {
    id: "spo_ek_011",
    category: "sport",
    subTheme: "rules",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Tennis tie-break scoring (to 7, win by 2)",
    emoji: "🎾",
    translations: {
      en: {
        question: "A standard tennis tie-break is first to how many points?",
        correct: "7",
        distractors: ["5", "6", "10", "11", "4"],
        explanation: "A tie-break is won at 7 points, by two clear points.",
      },
      lt: {
        question: "Iki kiek taškų žaidžiamas standartinis teniso pratęsimas (tie-break)?",
        correct: "7",
        distractors: ["5", "6", "10", "11", "4"],
        explanation: "Tie-breakas laimimas surinkus 7 taškus dviejų skirtumu.",
      },
    },
  },
  {
    id: "spo_ek_012",
    category: "sport",
    subTheme: "sports",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Cycling jersey (Tour de France yellow leader)",
    emoji: "🟨",
    translations: {
      en: {
        question: "What color jersey does the Tour de France leader wear?",
        correct: "Yellow",
        distractors: ["Green", "Red", "Blue", "White", "Black"],
        explanation: "The race leader wears the yellow jersey.",
      },
      lt: {
        question: "Kokios spalvos marškinėlius vilki Tour de France lyderis?",
        correct: "Geltonus",
        distractors: ["Žalius", "Raudonus", "Mėlynus", "Baltus", "Juodus"],
        explanation: "Lenktynių lyderis vilki geltonus marškinėlius.",
      },
    },
  },
  {
    id: "spo_ek_013",
    category: "sport",
    subTheme: "olympics",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Olympic city (Paris 1900, 1924, 2024)",
    emoji: "🗼",
    translations: {
      en: {
        question: "Which European capital hosted the Summer Olympics three times?",
        correct: "Paris",
        distractors: ["Rome", "Madrid", "Berlin", "Vienna", "Lisbon"],
        explanation: "Paris hosted the Summer Olympics in 1900, 1924 and 2024.",
      },
      lt: {
        question: "Kuri Europos sostinė vasaros olimpines rengė tris kartus?",
        correct: "Paryžius",
        distractors: ["Roma", "Madridas", "Berlynas", "Viena", "Lisabona"],
        explanation: "Paryžius vasaros olimpines rengė 1900, 1924 ir 2024 m.",
      },
    },
  },
  {
    id: "spo_ek_014",
    category: "sport",
    subTheme: "sports",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Basketball pro league (NBA, North America)",
    emoji: "🏀",
    translations: {
      en: {
        question: "The NBA is the top basketball league based in which region?",
        correct: "North America",
        distractors: ["Europe", "Asia", "South America", "Africa", "Oceania"],
        explanation: "The NBA is based in North America.",
      },
      lt: {
        question: "NBA — aukščiausia krepšinio lyga — yra kuriame regione?",
        correct: "Šiaurės Amerikoje",
        distractors: ["Europoje", "Azijoje", "Pietų Amerikoje", "Afrikoje", "Okeanijoje"],
        explanation: "NBA bazuojasi Šiaurės Amerikoje.",
      },
    },
  },
  {
    id: "spo_ek_015",
    category: "sport",
    subTheme: "rules",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Basketball rules (shot clock 24 seconds)",
    emoji: "⏱️",
    translations: {
      en: {
        question: "How many seconds does a team have to shoot in pro basketball?",
        correct: "24 seconds",
        distractors: [
          "20 seconds",
          "30 seconds",
          "35 seconds",
          "15 seconds",
          "45 seconds",
        ],
        explanation: "The shot clock in pro basketball is 24 seconds.",
      },
      lt: {
        question: "Per kiek sekundžių komanda turi mesti profesionaliame krepšinyje?",
        correct: "24 sekundės",
        distractors: [
          "20 sekundžių",
          "30 sekundžių",
          "35 sekundės",
          "15 sekundžių",
          "45 sekundės",
        ],
        explanation: "Atakos laikrodis profesionaliame krepšinyje yra 24 sekundės.",
      },
    },
  },
];
