/**
 * techContent — „Technologijos ir mokslas" trivijos klausimai (EN + LT).
 *
 * TESTINIS rinkinys (pirmas universalaus trivijos variklio bandymas):
 * po 15 klausimų kiekvienam lygiui (lengvas/vidutinis/sunkus/ekstremalus) = 60.
 * Temos „Oho" efektui: legendiniai žaidimai, kosmoso istorija, AI, pirmieji
 * kompiuteriai, grynas patikrintas mokslas.
 *
 * TAISYKLĖS (Manifestas):
 *   - 1 teisingas + 5 distractors; visi 6 variantai VISOSE kalbose ≤46 simbolių;
 *   - faktai 100% patikrinti (sourceVerified); neutralu (jokios politikos/religijos);
 *   - LT vidinės kabutės tik „..." (ne ASCII "); detalės — į explanation, ne į variantą.
 *
 * Formatas — žr. triviaTypes.ts (TriviaQuestion). category visada "tech".
 */

import { TriviaQuestion } from "./triviaTypes";

export const TECH_QUESTIONS: TriviaQuestion[] = [
  // ======================= LENGVAS (Easy) =======================
  {
    id: "tec_le_001",
    category: "tech",
    subTheme: "companies",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Company history (Apple Inc.)",
    emoji: "📱",
    translations: {
      en: {
        question: "Which company makes the iPhone?",
        correct: "Apple",
        distractors: ["Samsung", "Google", "Sony", "Microsoft", "Nokia"],
        explanation: "Apple released the first iPhone in 2007.",
      },
      lt: {
        question: "Kuri įmonė gamina iPhone?",
        correct: "Apple",
        distractors: ["Samsung", "Google", "Sony", "Microsoft", "Nokia"],
        explanation: "Apple pristatė pirmąjį iPhone 2007 metais.",
      },
    },
  },
  {
    id: "tec_le_002",
    category: "tech",
    subTheme: "space",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "NASA — Apollo 11 (1969)",
    emoji: "🌙",
    translations: {
      en: {
        question: "Where did Apollo 11 land in 1969?",
        correct: "The Moon",
        distractors: ["Mars", "Venus", "The Sun", "Jupiter", "Saturn"],
        explanation: "Apollo 11 was the first crewed Moon landing.",
      },
      lt: {
        question: "Kur 1969 m. nusileido Apollo 11?",
        correct: "Mėnulyje",
        distractors: ["Marse", "Veneroje", "Saulėje", "Jupiteryje", "Saturne"],
        explanation: "Apollo 11 — pirmasis žmonių nusileidimas Mėnulyje.",
      },
    },
  },
  {
    id: "tec_le_003",
    category: "tech",
    subTheme: "games",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Pac-Man (Namco, 1980)",
    emoji: "🟡",
    translations: {
      en: {
        question: "What color is the character Pac-Man?",
        correct: "Yellow",
        distractors: ["Red", "Blue", "Green", "Pink", "Orange"],
        explanation: "Pac-Man is the round yellow character who eats dots.",
      },
      lt: {
        question: "Kokios spalvos personažas Pac-Man?",
        correct: "Geltona",
        distractors: ["Raudona", "Mėlyna", "Žalia", "Rožinė", "Oranžinė"],
        explanation: "Pac-Man — apvalus geltonas personažas, ėdantis taškus.",
      },
    },
  },
  {
    id: "tec_le_004",
    category: "tech",
    subTheme: "computers",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Basic computing (input devices)",
    emoji: "🖱️",
    translations: {
      en: {
        question: "What does a computer mouse control?",
        correct: "The cursor",
        distractors: ["The volume", "The Wi-Fi", "The battery", "The printer", "The brightness"],
        explanation: "Moving the mouse moves the on-screen cursor.",
      },
      lt: {
        question: "Ką valdo kompiuterio pelė?",
        correct: "Žymeklį",
        distractors: ["Garsą", "Wi-Fi", "Bateriją", "Spausdintuvą", "Ryškumą"],
        explanation: "Judinant pelę juda ekrane esantis žymeklis.",
      },
    },
  },
  {
    id: "tec_le_005",
    category: "tech",
    subTheme: "ai",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Computer science (terminology)",
    emoji: "🤖",
    translations: {
      en: {
        question: "What does 'AI' stand for?",
        correct: "Artificial Intelligence",
        distractors: ["Automatic Internet", "Advanced Image", "Active Input", "Audio Interface", "Applied Industry"],
        explanation: "AI = Artificial Intelligence — machines that mimic thinking.",
      },
      lt: {
        question: "Ką reiškia santrumpa „AI”?",
        correct: "Dirbtinis intelektas",
        distractors: ["Automatinis internetas", "Pažangus vaizdas", "Aktyvi įvestis", "Garso sąsaja", "Taikomoji pramonė"],
        explanation: "AI = dirbtinis intelektas — mašinos, imituojančios mąstymą.",
      },
    },
  },
  {
    id: "tec_le_006",
    category: "tech",
    subTheme: "companies",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Company history (Microsoft)",
    emoji: "🪟",
    translations: {
      en: {
        question: "Which company created Windows?",
        correct: "Microsoft",
        distractors: ["Apple", "Google", "IBM", "Intel", "Adobe"],
        explanation: "Microsoft launched the Windows operating system in 1985.",
      },
      lt: {
        question: "Kuri įmonė sukūrė Windows?",
        correct: "Microsoft",
        distractors: ["Apple", "Google", "IBM", "Intel", "Adobe"],
        explanation: "Microsoft išleido Windows operacinę sistemą 1985 m.",
      },
    },
  },
  {
    id: "tec_le_007",
    category: "tech",
    subTheme: "space",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Astronomy (the Sun is a star)",
    emoji: "☀️",
    translations: {
      en: {
        question: "What is the closest star to Earth?",
        correct: "The Sun",
        distractors: ["The Moon", "Polaris", "Sirius", "Mars", "Venus"],
        explanation: "The Sun is our nearest star; the Moon is not a star.",
      },
      lt: {
        question: "Kuri žvaigždė arčiausiai Žemės?",
        correct: "Saulė",
        distractors: ["Mėnulis", "Šiaurinė", "Sirijus", "Marsas", "Venera"],
        explanation: "Saulė — artimiausia žvaigždė; Mėnulis nėra žvaigždė.",
      },
    },
  },
  {
    id: "tec_le_008",
    category: "tech",
    subTheme: "devices",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Basic computing (device types)",
    emoji: "💻",
    translations: {
      en: {
        question: "What do you call a portable computer?",
        correct: "Laptop",
        distractors: ["Desktop", "Server", "Router", "Monitor", "Printer"],
        explanation: "A laptop folds shut and runs on a battery.",
      },
      lt: {
        question: "Kaip vadinamas nešiojamas kompiuteris?",
        correct: "Nešiojamas kompiuteris",
        distractors: ["Stalinis", "Serveris", "Maršrutizatorius", "Monitorius", "Spausdintuvas"],
        explanation: "Nešiojamas kompiuteris susilanksto ir veikia iš baterijos.",
      },
    },
  },
  {
    id: "tec_le_009",
    category: "tech",
    subTheme: "games",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Pac-Man (Namco, 1980)",
    emoji: "🎮",
    translations: {
      en: {
        question: "What does Pac-Man eat in the maze?",
        correct: "Dots",
        distractors: ["Coins", "Keys", "Stars", "Gems", "Letters"],
        explanation: "Pac-Man clears each maze by eating all the dots.",
      },
      lt: {
        question: "Ką labirinte ėda Pac-Man?",
        correct: "Taškus",
        distractors: ["Monetas", "Raktus", "Žvaigždes", "Brangakmenius", "Raides"],
        explanation: "Pac-Man įveikia labirintą suėsdamas visus taškus.",
      },
    },
  },
  {
    id: "tec_le_010",
    category: "tech",
    subTheme: "energy",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Physics (photovoltaics)",
    emoji: "🔆",
    translations: {
      en: {
        question: "What powers a solar panel?",
        correct: "Sunlight",
        distractors: ["Wind", "Water", "Coal", "Gas", "Batteries"],
        explanation: "Solar panels turn sunlight into electricity.",
      },
      lt: {
        question: "Kas maitina saulės kolektorių?",
        correct: "Saulės šviesa",
        distractors: ["Vėjas", "Vanduo", "Anglis", "Dujos", "Baterijos"],
        explanation: "Saulės kolektoriai šviesą paverčia elektra.",
      },
    },
  },
  {
    id: "tec_le_011",
    category: "tech",
    subTheme: "companies",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Company history (Google / Android)",
    emoji: "📲",
    translations: {
      en: {
        question: "Which company makes the Android system?",
        correct: "Google",
        distractors: ["Apple", "Microsoft", "Samsung", "Sony", "Nokia"],
        explanation: "Google develops the Android operating system.",
      },
      lt: {
        question: "Kuri įmonė kuria Android sistemą?",
        correct: "Google",
        distractors: ["Apple", "Microsoft", "Samsung", "Sony", "Nokia"],
        explanation: "Android operacinę sistemą kuria Google.",
      },
    },
  },
  {
    id: "tec_le_012",
    category: "tech",
    subTheme: "robots",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Consumer robotics (robot vacuums)",
    emoji: "🧹",
    translations: {
      en: {
        question: "What does a robot vacuum mainly do?",
        correct: "Cleans floors",
        distractors: ["Cooks food", "Washes clothes", "Mows grass", "Paints walls", "Drives cars"],
        explanation: "A robot vacuum drives around cleaning floors on its own.",
      },
      lt: {
        question: "Ką daugiausia daro robotas dulkių siurblys?",
        correct: "Valo grindis",
        distractors: ["Gamina maistą", "Skalbia", "Pjauna žolę", "Dažo sienas", "Vairuoja"],
        explanation: "Robotas siurblys pats važinėja ir valo grindis.",
      },
    },
  },
  {
    id: "tec_le_013",
    category: "tech",
    subTheme: "space",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Spaceflight (SpaceX Falcon rockets)",
    emoji: "🚀",
    translations: {
      en: {
        question: "Which company makes Falcon rockets?",
        correct: "SpaceX",
        distractors: ["NASA", "Boeing", "Airbus", "Toyota", "Apple"],
        explanation: "SpaceX builds the reusable Falcon 9 rocket.",
      },
      lt: {
        question: "Kuri įmonė gamina „Falcon” raketas?",
        correct: "SpaceX",
        distractors: ["NASA", "Boeing", "Airbus", "Toyota", "Apple"],
        explanation: "SpaceX gamina daugkartinę „Falcon 9” raketą.",
      },
    },
  },
  {
    id: "tec_le_014",
    category: "tech",
    subTheme: "computers",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Basic computing (keyboard keys)",
    emoji: "⌨️",
    translations: {
      en: {
        question: "What does the 'Delete' key do?",
        correct: "Removes text",
        distractors: ["Saves a file", "Prints a page", "Opens a menu", "Adds a space", "Locks screen"],
        explanation: "The Delete key erases characters you have typed.",
      },
      lt: {
        question: "Ką daro klavišas „Delete”?",
        correct: "Ištrina tekstą",
        distractors: ["Išsaugo failą", "Spausdina", "Atveria meniu", "Prideda tarpą", "Užrakina"],
        explanation: "Klavišas „Delete” ištrina parašytus simbolius.",
      },
    },
  },
  {
    id: "tec_le_015",
    category: "tech",
    subTheme: "games",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Tetris (1984)",
    emoji: "🧱",
    translations: {
      en: {
        question: "Tetris is a game about fitting what?",
        correct: "Falling blocks",
        distractors: ["Cards", "Bubbles", "Words", "Cars", "Animals"],
        explanation: "In Tetris you rotate and stack falling blocks.",
      },
      lt: {
        question: "Tetris — žaidimas apie ką dėliojimą?",
        correct: "Krintančius blokus",
        distractors: ["Kortas", "Burbulus", "Žodžius", "Mašinas", "Gyvūnus"],
        explanation: "Tetris — sukioji ir dėlioji krintančius blokus.",
      },
    },
  },

  // ======================= VIDUTINIS (Medium) =======================
  {
    id: "tec_med_001",
    category: "tech",
    subTheme: "history",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Apple — first iPhone (2007)",
    emoji: "🗓️",
    translations: {
      en: {
        question: "In what year was the first iPhone released?",
        correct: "2007",
        distractors: ["2005", "2010", "2001", "2009", "2003"],
        explanation: "Steve Jobs unveiled the first iPhone in 2007.",
      },
      lt: {
        question: "Kuriais metais pasirodė pirmasis iPhone?",
        correct: "2007",
        distractors: ["2005", "2010", "2001", "2009", "2003"],
        explanation: "Steve Jobs pristatė pirmąjį iPhone 2007 m.",
      },
    },
  },
  {
    id: "tec_med_002",
    category: "tech",
    subTheme: "space",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "NASA — Apollo 11 (1969)",
    emoji: "🚩",
    translations: {
      en: {
        question: "Who was the first person to walk on the Moon?",
        correct: "Neil Armstrong",
        distractors: ["Buzz Aldrin", "Yuri Gagarin", "Michael Collins", "John Glenn", "Alan Shepard"],
        explanation: "Neil Armstrong stepped onto the Moon in July 1969.",
      },
      lt: {
        question: "Kas pirmas žengė Mėnulio paviršiumi?",
        correct: "Neil Armstrong",
        distractors: ["Buzz Aldrin", "Jurijus Gagarinas", "Michael Collins", "John Glenn", "Alan Shepard"],
        explanation: "Neil Armstrong žengė ant Mėnulio 1969 m. liepą.",
      },
    },
  },
  {
    id: "tec_med_003",
    category: "tech",
    subTheme: "space",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Spaceflight — Vostok 1 (1961)",
    emoji: "🌌",
    translations: {
      en: {
        question: "Who was the first human in space?",
        correct: "Yuri Gagarin",
        distractors: ["Neil Armstrong", "Alan Shepard", "John Glenn", "Buzz Aldrin", "Sergei Korolev"],
        explanation: "Yuri Gagarin orbited Earth in 1961 aboard Vostok 1.",
      },
      lt: {
        question: "Kas pirmas žmogus skrido į kosmosą?",
        correct: "Jurijus Gagarinas",
        distractors: ["Neil Armstrong", "Alan Shepard", "John Glenn", "Buzz Aldrin", "Sergejus Koroliovas"],
        explanation: "Jurijus Gagarinas apskriejo Žemę 1961 m. su Vostok 1.",
      },
    },
  },
  {
    id: "tec_med_004",
    category: "tech",
    subTheme: "games",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Mojang — Minecraft (2011)",
    emoji: "⛏️",
    translations: {
      en: {
        question: "Which studio created Minecraft?",
        correct: "Mojang",
        distractors: ["Nintendo", "Valve", "Rockstar", "Sega", "Ubisoft"],
        explanation: "Mojang released Minecraft fully in 2011.",
      },
      lt: {
        question: "Kuri studija sukūrė Minecraft?",
        correct: "Mojang",
        distractors: ["Nintendo", "Valve", "Rockstar", "Sega", "Ubisoft"],
        explanation: "Mojang išleido Minecraft 2011 m.",
      },
    },
  },
  {
    id: "tec_med_005",
    category: "tech",
    subTheme: "games",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Pac-Man (Namco, 1980)",
    emoji: "👾",
    translations: {
      en: {
        question: "In what year was Pac-Man released?",
        correct: "1980",
        distractors: ["1975", "1985", "1990", "1978", "1982"],
        explanation: "Pac-Man arrived in arcades in 1980.",
      },
      lt: {
        question: "Kuriais metais pasirodė Pac-Man?",
        correct: "1980",
        distractors: ["1975", "1985", "1990", "1978", "1982"],
        explanation: "Pac-Man pasirodė salonų automatuose 1980 m.",
      },
    },
  },
  {
    id: "tec_med_006",
    category: "tech",
    subTheme: "companies",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Company history (Microsoft founders)",
    emoji: "💼",
    translations: {
      en: {
        question: "Who founded Microsoft with Paul Allen?",
        correct: "Bill Gates",
        distractors: ["Steve Jobs", "Elon Musk", "Mark Zuckerberg", "Jeff Bezos", "Larry Page"],
        explanation: "Bill Gates and Paul Allen started Microsoft in 1975.",
      },
      lt: {
        question: "Kas su Paul Allen įkūrė Microsoft?",
        correct: "Bill Gates",
        distractors: ["Steve Jobs", "Elon Musk", "Mark Zuckerberg", "Jeff Bezos", "Larry Page"],
        explanation: "Bill Gates ir Paul Allen įkūrė Microsoft 1975 m.",
      },
    },
  },
  {
    id: "tec_med_007",
    category: "tech",
    subTheme: "companies",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Company history (SpaceX, Tesla)",
    emoji: "🚗",
    translations: {
      en: {
        question: "Who founded SpaceX and leads Tesla?",
        correct: "Elon Musk",
        distractors: ["Jeff Bezos", "Bill Gates", "Steve Jobs", "Larry Page", "Tim Cook"],
        explanation: "Elon Musk founded SpaceX in 2002.",
      },
      lt: {
        question: "Kas įkūrė SpaceX ir vadovauja Tesla?",
        correct: "Elon Musk",
        distractors: ["Jeff Bezos", "Bill Gates", "Steve Jobs", "Larry Page", "Tim Cook"],
        explanation: "Elon Musk įkūrė SpaceX 2002 m.",
      },
    },
  },
  {
    id: "tec_med_008",
    category: "tech",
    subTheme: "science",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Biology (photosynthesis)",
    emoji: "🌱",
    translations: {
      en: {
        question: "What gas do plants absorb to grow?",
        correct: "Carbon dioxide",
        distractors: ["Oxygen", "Nitrogen", "Helium", "Hydrogen", "Methane"],
        explanation: "Plants take in carbon dioxide during photosynthesis.",
      },
      lt: {
        question: "Kokias dujas augalai sugeria augdami?",
        correct: "Anglies dioksidą",
        distractors: ["Deguonį", "Azotą", "Helį", "Vandenilį", "Metaną"],
        explanation: "Augalai fotosintezės metu sugeria anglies dioksidą.",
      },
    },
  },
  {
    id: "tec_med_009",
    category: "tech",
    subTheme: "science",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Chemistry (water formula)",
    emoji: "💧",
    translations: {
      en: {
        question: "What is the chemical formula for water?",
        correct: "H2O",
        distractors: ["CO2", "O2", "NaCl", "H2", "HO2"],
        explanation: "Water is two hydrogen atoms and one oxygen: H2O.",
      },
      lt: {
        question: "Kokia vandens cheminė formulė?",
        correct: "H2O",
        distractors: ["CO2", "O2", "NaCl", "H2", "HO2"],
        explanation: "Vanduo — du vandenilio ir vienas deguonies atomas: H2O.",
      },
    },
  },
  {
    id: "tec_med_010",
    category: "tech",
    subTheme: "companies",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Company history (Google acquired YouTube, 2006)",
    emoji: "▶️",
    translations: {
      en: {
        question: "Which company owns YouTube?",
        correct: "Google",
        distractors: ["Apple", "Microsoft", "Amazon", "Meta", "Netflix"],
        explanation: "Google bought YouTube in 2006.",
      },
      lt: {
        question: "Kuriai įmonei priklauso YouTube?",
        correct: "Google",
        distractors: ["Apple", "Microsoft", "Amazon", "Meta", "Netflix"],
        explanation: "Google nupirko YouTube 2006 m.",
      },
    },
  },
  {
    id: "tec_med_011",
    category: "tech",
    subTheme: "robots",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Etymology — Karel Čapek, R.U.R. (1920)",
    emoji: "🦾",
    translations: {
      en: {
        question: "The word 'robot' comes from which language?",
        correct: "Czech",
        distractors: ["Latin", "Greek", "German", "Japanese", "Russian"],
        explanation: "From Czech 'robota' (forced labor), used in a 1920 play.",
      },
      lt: {
        question: "Iš kurios kalbos kilo žodis „robotas”?",
        correct: "Čekų",
        distractors: ["Lotynų", "Graikų", "Vokiečių", "Japonų", "Rusų"],
        explanation: "Iš čekų „robota” (sunkus darbas), 1920 m. pjesėje.",
      },
    },
  },
  {
    id: "tec_med_012",
    category: "tech",
    subTheme: "internet",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Computing terminology (email)",
    emoji: "✉️",
    translations: {
      en: {
        question: "What does 'email' stand for?",
        correct: "Electronic mail",
        distractors: ["Express mail", "Easy mail", "Encoded mail", "External mail", "Echo mail"],
        explanation: "Email is short for electronic mail.",
      },
      lt: {
        question: "Ką reiškia žodis „email”?",
        correct: "Elektroninis paštas",
        distractors: ["Greitas paštas", "Lengvas paštas", "Koduotas paštas", "Išorinis paštas", "Aido paštas"],
        explanation: "„Email” — tai elektroninis paštas.",
      },
    },
  },
  {
    id: "tec_med_013",
    category: "tech",
    subTheme: "ai",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Computer science (chatbots)",
    emoji: "💬",
    translations: {
      en: {
        question: "A program that chats like a person is a...?",
        correct: "Chatbot",
        distractors: ["Firewall", "Browser", "Spreadsheet", "Compiler", "Database"],
        explanation: "A chatbot talks with users in plain language.",
      },
      lt: {
        question: "Programa, kalbanti kaip žmogus, yra...?",
        correct: "Pokalbių robotas",
        distractors: ["Ugniasienė", "Naršyklė", "Skaičiuoklė", "Kompiliatorius", "Duomenų bazė"],
        explanation: "Pokalbių robotas bendrauja su vartotojais žmogaus kalba.",
      },
    },
  },
  {
    id: "tec_med_014",
    category: "tech",
    subTheme: "space",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Astronomy (Mars)",
    emoji: "🔴",
    translations: {
      en: {
        question: "Which planet is called the Red Planet?",
        correct: "Mars",
        distractors: ["Venus", "Jupiter", "Mercury", "Saturn", "Neptune"],
        explanation: "Iron dust gives Mars its reddish color.",
      },
      lt: {
        question: "Kuri planeta vadinama Raudonąja?",
        correct: "Marsas",
        distractors: ["Venera", "Jupiteris", "Merkurijus", "Saturnas", "Neptūnas"],
        explanation: "Geležies dulkės suteikia Marsui rausvą spalvą.",
      },
    },
  },
  {
    id: "tec_med_015",
    category: "tech",
    subTheme: "history",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Computing history (ENIAC, 1945)",
    emoji: "🖥️",
    translations: {
      en: {
        question: "What was an early room-sized computer named?",
        correct: "ENIAC",
        distractors: ["COBOL", "UNIX", "BASIC", "LINUX", "PYTHON"],
        explanation: "ENIAC (1945) filled a room and weighed many tons.",
      },
      lt: {
        question: "Kaip vadinosi ankstyvas kambario dydžio kompiuteris?",
        correct: "ENIAC",
        distractors: ["COBOL", "UNIX", "BASIC", "LINUX", "PYTHON"],
        explanation: "ENIAC (1945) užėmė visą kambarį ir svėrė daug tonų.",
      },
    },
  },

  // ======================= SUNKUS (Hard) =======================
  {
    id: "tec_hard_001",
    category: "tech",
    subTheme: "space",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "NASA — Apollo 11 (1969)",
    emoji: "🌕",
    translations: {
      en: {
        question: "In what year did Apollo 11 land on the Moon?",
        correct: "1969",
        distractors: ["1965", "1971", "1959", "1972", "1967"],
        explanation: "The first Moon landing happened on 20 July 1969.",
      },
      lt: {
        question: "Kuriais metais Apollo 11 nusileido Mėnulyje?",
        correct: "1969",
        distractors: ["1965", "1971", "1959", "1972", "1967"],
        explanation: "Pirmas nusileidimas Mėnulyje — 1969 m. liepos 20 d.",
      },
    },
  },
  {
    id: "tec_hard_002",
    category: "tech",
    subTheme: "companies",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Company history (Apple co-founders)",
    emoji: "🍎",
    translations: {
      en: {
        question: "Who built the first Apple computer with Jobs?",
        correct: "Steve Wozniak",
        distractors: ["Bill Gates", "Paul Allen", "Tim Cook", "Jony Ive", "Steve Ballmer"],
        explanation: "Steve Wozniak designed the Apple I in 1976.",
      },
      lt: {
        question: "Kas su Jobs sukūrė pirmąjį Apple kompiuterį?",
        correct: "Steve Wozniak",
        distractors: ["Bill Gates", "Paul Allen", "Tim Cook", "Jony Ive", "Steve Ballmer"],
        explanation: "Steve Wozniak sukūrė Apple I 1976 m.",
      },
    },
  },
  {
    id: "tec_hard_003",
    category: "tech",
    subTheme: "games",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Nintendo — Mario franchise",
    emoji: "🍄",
    translations: {
      en: {
        question: "Which company created the character Mario?",
        correct: "Nintendo",
        distractors: ["Sega", "Sony", "Microsoft", "Atari", "Capcom"],
        explanation: "Mario first appeared in Nintendo's Donkey Kong (1981).",
      },
      lt: {
        question: "Kuri įmonė sukūrė personažą Mario?",
        correct: "Nintendo",
        distractors: ["Sega", "Sony", "Microsoft", "Atari", "Capcom"],
        explanation: "Mario pirmąkart pasirodė Nintendo Donkey Kong (1981).",
      },
    },
  },
  {
    id: "tec_hard_004",
    category: "tech",
    subTheme: "science",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Physics (subatomic particles)",
    emoji: "⚛️",
    translations: {
      en: {
        question: "Which particle has a negative electric charge?",
        correct: "Electron",
        distractors: ["Proton", "Neutron", "Photon", "Atom", "Quark"],
        explanation: "Electrons carry a negative charge; protons positive.",
      },
      lt: {
        question: "Kuri dalelė turi neigiamą elektros krūvį?",
        correct: "Elektronas",
        distractors: ["Protonas", "Neutronas", "Fotonas", "Atomas", "Kvarkas"],
        explanation: "Elektronai turi neigiamą krūvį, protonai — teigiamą.",
      },
    },
  },
  {
    id: "tec_hard_005",
    category: "tech",
    subTheme: "science",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Physics (speed of light ≈ 299,792 km/s)",
    emoji: "💡",
    translations: {
      en: {
        question: "The speed of light is about how many km/s?",
        correct: "300,000",
        distractors: ["30,000", "3,000,000", "150,000", "1,000", "30"],
        explanation: "Light travels nearly 300,000 km every second.",
      },
      lt: {
        question: "Maždaug koks šviesos greitis km/s?",
        correct: "300 000",
        distractors: ["30 000", "3 000 000", "150 000", "1 000", "30"],
        explanation: "Šviesa per sekundę nukeliauja beveik 300 000 km.",
      },
    },
  },
  {
    id: "tec_hard_006",
    category: "tech",
    subTheme: "ai",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "IBM Deep Blue vs Kasparov (1997)",
    emoji: "♟️",
    translations: {
      en: {
        question: "Which 1997 IBM computer beat chess champ Kasparov?",
        correct: "Deep Blue",
        distractors: ["Watson", "AlphaGo", "ENIAC", "HAL 9000", "Skynet"],
        explanation: "Deep Blue beat world champion Garry Kasparov in 1997.",
      },
      lt: {
        question: "Kuris 1997 m. IBM kompiuteris įveikė šachmatininką Kasparovą?",
        correct: "Deep Blue",
        distractors: ["Watson", "AlphaGo", "ENIAC", "HAL 9000", "Skynet"],
        explanation: "Deep Blue 1997 m. nugalėjo čempioną Garį Kasparovą.",
      },
    },
  },
  {
    id: "tec_hard_007",
    category: "tech",
    subTheme: "ai",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "DeepMind AlphaGo vs Lee Sedol (2016)",
    emoji: "🧠",
    translations: {
      en: {
        question: "Which AI beat a Go champion in 2016?",
        correct: "AlphaGo",
        distractors: ["Deep Blue", "Watson", "ChatGPT", "Siri", "Cortana"],
        explanation: "AlphaGo defeated Go master Lee Sedol in 2016.",
      },
      lt: {
        question: "Kuris DI 2016 m. įveikė Go čempioną?",
        correct: "AlphaGo",
        distractors: ["Deep Blue", "Watson", "ChatGPT", "Siri", "Cortana"],
        explanation: "AlphaGo 2016 m. nugalėjo Go meistrą Lee Sedolį.",
      },
    },
  },
  {
    id: "tec_hard_008",
    category: "tech",
    subTheme: "space",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Spaceflight — Sputnik 1 (1957)",
    emoji: "📡",
    translations: {
      en: {
        question: "What was the first artificial satellite (1957)?",
        correct: "Sputnik 1",
        distractors: ["Apollo 1", "Vostok 1", "Explorer 1", "Hubble", "Voyager 1"],
        explanation: "Sputnik 1 was launched by the USSR in 1957.",
      },
      lt: {
        question: "Koks buvo pirmas dirbtinis palydovas (1957)?",
        correct: "Sputnik 1",
        distractors: ["Apollo 1", "Vostok 1", "Explorer 1", "Hubble", "Voyager 1"],
        explanation: "Sputnik 1 SSRS paleido 1957 m.",
      },
    },
  },
  {
    id: "tec_hard_009",
    category: "tech",
    subTheme: "science",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Physics (gravity)",
    emoji: "🍏",
    translations: {
      en: {
        question: "What force pulls objects toward Earth?",
        correct: "Gravity",
        distractors: ["Magnetism", "Friction", "Electricity", "Pressure", "Inertia"],
        explanation: "Gravity pulls all masses toward each other.",
      },
      lt: {
        question: "Kokia jėga traukia daiktus link Žemės?",
        correct: "Gravitacija",
        distractors: ["Magnetizmas", "Trintis", "Elektra", "Slėgis", "Inercija"],
        explanation: "Gravitacija traukia visas mases viena link kitos.",
      },
    },
  },
  {
    id: "tec_hard_010",
    category: "tech",
    subTheme: "internet",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Tim Berners-Lee — World Wide Web (1989–1991)",
    emoji: "🌐",
    translations: {
      en: {
        question: "Who invented the World Wide Web?",
        correct: "Tim Berners-Lee",
        distractors: ["Bill Gates", "Steve Jobs", "Alan Turing", "Vint Cerf", "Linus Torvalds"],
        explanation: "Tim Berners-Lee created the Web at CERN around 1989.",
      },
      lt: {
        question: "Kas išrado pasaulinį žiniatinklį (Web)?",
        correct: "Tim Berners-Lee",
        distractors: ["Bill Gates", "Steve Jobs", "Alan Turing", "Vint Cerf", "Linus Torvalds"],
        explanation: "Tim Berners-Lee sukūrė žiniatinklį CERN apie 1989 m.",
      },
    },
  },
  {
    id: "tec_hard_011",
    category: "tech",
    subTheme: "history",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Computing history (Ada Lovelace)",
    emoji: "📜",
    translations: {
      en: {
        question: "Who is seen as the first computer programmer?",
        correct: "Ada Lovelace",
        distractors: ["Alan Turing", "Grace Hopper", "Charles Babbage", "Bill Gates", "John von Neumann"],
        explanation: "Ada Lovelace wrote an algorithm in the 1840s.",
      },
      lt: {
        question: "Kas laikomas pirmuoju programuotoju?",
        correct: "Ada Lovelace",
        distractors: ["Alan Turing", "Grace Hopper", "Charles Babbage", "Bill Gates", "John von Neumann"],
        explanation: "Ada Lovelace parašė algoritmą dar 1840-aisiais.",
      },
    },
  },
  {
    id: "tec_hard_012",
    category: "tech",
    subTheme: "science",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Materials science (diamond hardness)",
    emoji: "💎",
    translations: {
      en: {
        question: "What is the hardest natural material?",
        correct: "Diamond",
        distractors: ["Gold", "Iron", "Quartz", "Granite", "Titanium"],
        explanation: "Diamond tops the Mohs hardness scale at 10.",
      },
      lt: {
        question: "Koks kiečiausias gamtinis material?",
        correct: "Deimantas",
        distractors: ["Auksas", "Geležis", "Kvarcas", "Granitas", "Titanas"],
        explanation: "Deimantas Moso skalėje turi aukščiausią kietumą — 10.",
      },
    },
  },
  {
    id: "tec_hard_013",
    category: "tech",
    subTheme: "robots",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Karel Čapek — R.U.R. (1920)",
    emoji: "🎭",
    translations: {
      en: {
        question: "Who coined the word 'robot' in a 1920 play?",
        correct: "Karel Čapek",
        distractors: ["Isaac Asimov", "Nikola Tesla", "Alan Turing", "Jules Verne", "Fritz Lang"],
        explanation: "Karel Čapek used 'robot' in his play R.U.R. (1920).",
      },
      lt: {
        question: "Kas 1920 m. pjesėje sugalvojo žodį „robotas”?",
        correct: "Karel Čapek",
        distractors: ["Isaac Asimov", "Nikola Tesla", "Alan Turing", "Jules Verne", "Fritz Lang"],
        explanation: "Karel Čapek žodį „robotas” pavartojo pjesėje R.U.R. (1920).",
      },
    },
  },
  {
    id: "tec_hard_014",
    category: "tech",
    subTheme: "space",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Astronomy (Jupiter is largest planet)",
    emoji: "🪐",
    translations: {
      en: {
        question: "Which is the largest planet in the Solar System?",
        correct: "Jupiter",
        distractors: ["Saturn", "Neptune", "Earth", "Mars", "The Sun"],
        explanation: "Jupiter is the biggest planet; the Sun is a star.",
      },
      lt: {
        question: "Kuri didžiausia Saulės sistemos planeta?",
        correct: "Jupiteris",
        distractors: ["Saturnas", "Neptūnas", "Žemė", "Marsas", "Saulė"],
        explanation: "Jupiteris — didžiausia planeta; Saulė yra žvaigždė.",
      },
    },
  },
  {
    id: "tec_hard_015",
    category: "tech",
    subTheme: "games",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Tetris — Alexey Pajitnov (1984)",
    emoji: "🟦",
    translations: {
      en: {
        question: "In what year was Tetris created?",
        correct: "1984",
        distractors: ["1980", "1989", "1991", "1978", "1986"],
        explanation: "Alexey Pajitnov created Tetris in 1984.",
      },
      lt: {
        question: "Kuriais metais sukurtas Tetris?",
        correct: "1984",
        distractors: ["1980", "1989", "1991", "1978", "1986"],
        explanation: "Alexey Pajitnov sukūrė Tetris 1984 m.",
      },
    },
  },

  // ======================= EKSTREMALUS (Extreme) =======================
  {
    id: "tec_ext_001",
    category: "tech",
    subTheme: "science",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Chemistry (gold symbol Au, from aurum)",
    emoji: "🥇",
    translations: {
      en: {
        question: "What is the chemical symbol for gold?",
        correct: "Au",
        distractors: ["Ag", "Gd", "Go", "Gl", "Gu"],
        explanation: "Gold's symbol Au comes from the Latin 'aurum'.",
      },
      lt: {
        question: "Koks aukso cheminis simbolis?",
        correct: "Au",
        distractors: ["Ag", "Gd", "Go", "Gl", "Gu"],
        explanation: "Aukso simbolis Au — iš lotyniško „aurum”.",
      },
    },
  },
  {
    id: "tec_ext_002",
    category: "tech",
    subTheme: "science",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Atmospheric science (N2 ≈ 78%)",
    emoji: "🌫️",
    translations: {
      en: {
        question: "Most abundant gas in Earth's atmosphere?",
        correct: "Nitrogen",
        distractors: ["Oxygen", "Carbon dioxide", "Argon", "Hydrogen", "Helium"],
        explanation: "Nitrogen makes up about 78% of the air.",
      },
      lt: {
        question: "Kokių dujų daugiausia Žemės atmosferoje?",
        correct: "Azotas",
        distractors: ["Deguonis", "Anglies dioksidas", "Argonas", "Vandenilis", "Helis"],
        explanation: "Azotas sudaro apie 78% oro.",
      },
    },
  },
  {
    id: "tec_ext_003",
    category: "tech",
    subTheme: "space",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Astronomy (sunlight ≈ 8 min 20 s)",
    emoji: "🌞",
    translations: {
      en: {
        question: "How long does sunlight take to reach Earth?",
        correct: "About 8 minutes",
        distractors: ["8 seconds", "8 hours", "1 minute", "1 hour", "1 second"],
        explanation: "Light from the Sun reaches us in about 8 minutes.",
      },
      lt: {
        question: "Per kiek laiko Saulės šviesa pasiekia Žemę?",
        correct: "Apie 8 minutes",
        distractors: ["8 sekundes", "8 valandas", "1 minutę", "1 valandą", "1 sekundę"],
        explanation: "Saulės šviesa mus pasiekia maždaug per 8 minutes.",
      },
    },
  },
  {
    id: "tec_ext_004",
    category: "tech",
    subTheme: "computers",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Computing basics (1 byte = 8 bits)",
    emoji: "🔢",
    translations: {
      en: {
        question: "How many bits are in one byte?",
        correct: "8",
        distractors: ["4", "16", "2", "32", "64"],
        explanation: "One byte equals 8 bits.",
      },
      lt: {
        question: "Kiek bitų yra viename baite?",
        correct: "8",
        distractors: ["4", "16", "2", "32", "64"],
        explanation: "Vienas baitas lygus 8 bitams.",
      },
    },
  },
  {
    id: "tec_ext_005",
    category: "tech",
    subTheme: "history",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Ray Tomlinson — first email (1971)",
    emoji: "📨",
    translations: {
      en: {
        question: "In what year was the first email sent?",
        correct: "1971",
        distractors: ["1969", "1975", "1965", "1983", "1990"],
        explanation: "Ray Tomlinson sent the first network email in 1971.",
      },
      lt: {
        question: "Kuriais metais išsiųstas pirmas el. laiškas?",
        correct: "1971",
        distractors: ["1969", "1975", "1965", "1983", "1990"],
        explanation: "Ray Tomlinson pirmą tinklo el. laišką išsiuntė 1971 m.",
      },
    },
  },
  {
    id: "tec_ext_006",
    category: "tech",
    subTheme: "ai",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "IBM Watson — Jeopardy! (2011)",
    emoji: "🧩",
    translations: {
      en: {
        question: "Which IBM computer won Jeopardy! in 2011?",
        correct: "Watson",
        distractors: ["Deep Blue", "AlphaGo", "HAL 9000", "Siri", "ENIAC"],
        explanation: "IBM Watson beat human champions on Jeopardy! in 2011.",
      },
      lt: {
        question: "Kuris IBM kompiuteris 2011 m. laimėjo „Jeopardy!”?",
        correct: "Watson",
        distractors: ["Deep Blue", "AlphaGo", "HAL 9000", "Siri", "ENIAC"],
        explanation: "IBM Watson 2011 m. nugalėjo žmones „Jeopardy!” viktorinoje.",
      },
    },
  },
  {
    id: "tec_ext_007",
    category: "tech",
    subTheme: "science",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Physics (neutron has no charge)",
    emoji: "⚪",
    translations: {
      en: {
        question: "Which particle has no electric charge?",
        correct: "Neutron",
        distractors: ["Proton", "Electron", "Photon", "Positron", "Quark"],
        explanation: "Neutrons are electrically neutral.",
      },
      lt: {
        question: "Kuri dalelė neturi elektros krūvio?",
        correct: "Neutronas",
        distractors: ["Protonas", "Elektronas", "Fotonas", "Pozitronas", "Kvarkas"],
        explanation: "Neutronai yra elektriškai neutralūs.",
      },
    },
  },
  {
    id: "tec_ext_008",
    category: "tech",
    subTheme: "space",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "NASA — Perseverance rover (2021)",
    emoji: "🚙",
    translations: {
      en: {
        question: "Which NASA rover landed on Mars in 2021?",
        correct: "Perseverance",
        distractors: ["Curiosity", "Opportunity", "Spirit", "Sojourner", "Viking"],
        explanation: "Perseverance touched down on Mars in February 2021.",
      },
      lt: {
        question: "Kuris NASA marsaeigis nusileido Marse 2021 m.?",
        correct: "Perseverance",
        distractors: ["Curiosity", "Opportunity", "Spirit", "Sojourner", "Viking"],
        explanation: "Perseverance nusileido Marse 2021 m. vasarį.",
      },
    },
  },
  {
    id: "tec_ext_009",
    category: "tech",
    subTheme: "internet",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "First website at CERN (1991)",
    emoji: "🕸️",
    translations: {
      en: {
        question: "In what year was the first website published?",
        correct: "1991",
        distractors: ["1989", "1993", "1995", "1990", "1987"],
        explanation: "The first website went live at CERN in 1991.",
      },
      lt: {
        question: "Kuriais metais paskelbta pirma svetainė?",
        correct: "1991",
        distractors: ["1989", "1993", "1995", "1990", "1987"],
        explanation: "Pirma svetainė pradėjo veikti CERN 1991 m.",
      },
    },
  },
  {
    id: "tec_ext_010",
    category: "tech",
    subTheme: "games",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Tetris designer (Alexey Pajitnov)",
    emoji: "🕹️",
    translations: {
      en: {
        question: "Who designed the original Tetris?",
        correct: "Alexey Pajitnov",
        distractors: ["Shigeru Miyamoto", "Hideo Kojima", "John Carmack", "Will Wright", "Gabe Newell"],
        explanation: "Soviet engineer Alexey Pajitnov made Tetris in 1984.",
      },
      lt: {
        question: "Kas sukūrė originalų Tetris?",
        correct: "Alexey Pajitnov",
        distractors: ["Shigeru Miyamoto", "Hideo Kojima", "John Carmack", "Will Wright", "Gabe Newell"],
        explanation: "Sovietų inžinierius Alexey Pajitnov sukūrė Tetris 1984 m.",
      },
    },
  },
  {
    id: "tec_ext_011",
    category: "tech",
    subTheme: "science",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Chemistry (sodium symbol Na, from natrium)",
    emoji: "🧂",
    translations: {
      en: {
        question: "What is the chemical symbol for sodium?",
        correct: "Na",
        distractors: ["So", "Sd", "S", "Sn", "Nm"],
        explanation: "Sodium's symbol Na comes from Latin 'natrium'.",
      },
      lt: {
        question: "Koks natrio cheminis simbolis?",
        correct: "Na",
        distractors: ["So", "Sd", "S", "Sn", "Nm"],
        explanation: "Natrio simbolis Na — iš lotyniško „natrium”.",
      },
    },
  },
  {
    id: "tec_ext_012",
    category: "tech",
    subTheme: "space",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Spaceflight — Salyut 1 (1971)",
    emoji: "🛰️",
    translations: {
      en: {
        question: "What was the first space station (1971)?",
        correct: "Salyut 1",
        distractors: ["Mir", "Skylab", "ISS", "Tiangong", "Vostok"],
        explanation: "Salyut 1 was launched by the USSR in 1971.",
      },
      lt: {
        question: "Kokia buvo pirma kosminė stotis (1971)?",
        correct: "Salyut 1",
        distractors: ["Mir", "Skylab", "ISS", "Tiangong", "Vostok"],
        explanation: "Salyut 1 SSRS paleido 1971 m.",
      },
    },
  },
  {
    id: "tec_ext_013",
    category: "tech",
    subTheme: "ai",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Alan Turing — Turing Test (1950)",
    emoji: "🧮",
    translations: {
      en: {
        question: "Who proposed the famous 'Turing Test'?",
        correct: "Alan Turing",
        distractors: ["John McCarthy", "Marvin Minsky", "Claude Shannon", "Norbert Wiener", "John von Neumann"],
        explanation: "Alan Turing proposed his test for machine thinking in 1950.",
      },
      lt: {
        question: "Kas pasiūlė garsųjį „Tiuringo testą”?",
        correct: "Alan Turing",
        distractors: ["John McCarthy", "Marvin Minsky", "Claude Shannon", "Norbert Wiener", "John von Neumann"],
        explanation: "Alan Turing testą mašinų mąstymui pasiūlė 1950 m.",
      },
    },
  },
  {
    id: "tec_ext_014",
    category: "tech",
    subTheme: "space",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Astronomy (Mars has 2 moons)",
    emoji: "🌑",
    translations: {
      en: {
        question: "How many moons does Mars have?",
        correct: "2",
        distractors: ["0", "1", "4", "8", "12"],
        explanation: "Mars has two small moons: Phobos and Deimos.",
      },
      lt: {
        question: "Kiek mėnulių turi Marsas?",
        correct: "2",
        distractors: ["0", "1", "4", "8", "12"],
        explanation: "Marsas turi du mažus mėnulius: Fobą ir Deimą.",
      },
    },
  },
  {
    id: "tec_ext_015",
    category: "tech",
    subTheme: "history",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Python — Guido van Rossum (1991)",
    emoji: "🐍",
    translations: {
      en: {
        question: "Which language did Guido van Rossum create?",
        correct: "Python",
        distractors: ["Java", "Ruby", "C++", "Pascal", "Perl"],
        explanation: "Guido van Rossum released Python in 1991.",
      },
      lt: {
        question: "Kurią kalbą sukūrė Guido van Rossum?",
        correct: "Python",
        distractors: ["Java", "Ruby", "C++", "Pascal", "Perl"],
        explanation: "Guido van Rossum išleido Python 1991 m.",
      },
    },
  },
];
