/**
 * transportRoutes — 🧳 „Garsūs maršrutai ir kelionės" potemė (tema „Transportas").
 *
 * MAŽAS FAILAS pagal potemę. 40 klausimų (10/lygiui). Šilko kelias, Route 66,
 * Orient Express, Transsibiro geležinkelis, Panamos kanalas, Camino de Santiago,
 * Inkų keliai, Pony Express, Panamerikos greitkelis ir kt.
 * Tik istoriniai/įsitvirtinę faktai — JOKIOS politikos.
 *
 * TAISYKLĖS: 1 teisingas + 5 distraktoriai; ≤46 simb.; teisingas NE ilgiausias >+5;
 * LT be vidinių kabučių; jokio atsakymo klausime; EMOJI NEUTRALUS (neišduoda atsakymo).
 */

import { TriviaQuestion } from "./triviaTypes";

export const TRANSPORT_ROUTES: TriviaQuestion[] = [
  // ===================== LENGVAS (9–12 m. vaikas) =====================
  {
    id: "trn_ro_001",
    category: "transport",
    subTheme: "routes",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Route 66 — established 1926, runs Chicago to Santa Monica, CA; 2,448 miles",
    emoji: "🛣️",
    translations: {
      en: {
        question: "Which famous US road runs from Chicago all the way to California?",
        correct: "Route 66",
        distractors: ["Route 1", "Interstate 80", "Highway 101", "Route 40", "The Blue Ridge Parkway"],
        explanation: "Route 66 stretches 2,448 miles from Chicago to Santa Monica on the Pacific coast.",
      },
      lt: {
        question: "Kuris garsus JAV kelias driekiasi nuo Čikagos iki Kalifornijos?",
        correct: "Route 66",
        distractors: ["Route 1", "Interstate 80", "Highway 101", "Route 40", "The Blue Ridge Parkway"],
        explanation: "Route 66 driekiasi 2 448 mylių nuo Čikagos iki Santa Monikos prie Ramiojo vandenyno.",
      },
    },
  },
  {
    id: "trn_ro_002",
    category: "transport",
    subTheme: "routes",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Camino de Santiago — pilgrimage to Santiago de Compostela, Spain; scallop shell symbol",
    emoji: "🧳",
    translations: {
      en: {
        question: "Pilgrims walk the Camino de Santiago to reach which country?",
        correct: "Spain",
        distractors: ["France", "Portugal", "Italy", "Germany", "Ireland"],
        explanation: "The pilgrimage leads to the city of Santiago de Compostela in northwest Spain.",
      },
      lt: {
        question: "Į kurią šalį keliauja piligrimai, eidami Camino de Santiago?",
        correct: "Ispanija",
        distractors: ["Prancūzija", "Portugalija", "Italija", "Vokietija", "Airija"],
        explanation: "Piligrimystė veda į Santiago de Compostelos miestą Šiaurės Vakarų Ispanijoje.",
      },
    },
  },
  {
    id: "trn_ro_003",
    category: "transport",
    subTheme: "routes",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Panama Canal — opened August 15, 1914; connects Atlantic and Pacific oceans",
    emoji: "🗺️",
    translations: {
      en: {
        question: "The Panama Canal links which two oceans for passing ships?",
        correct: "Atlantic and Pacific",
        distractors: ["Atlantic and Indian", "Pacific and Arctic", "Indian and Pacific", "Atlantic and Arctic", "Indian and Southern"],
        explanation: "The canal, opened in 1914, lets ships cross between the Atlantic and Pacific oceans.",
      },
      lt: {
        question: "Kuriuos du vandenynus Panamos kanalas sujungia praplaukiantiems laivams?",
        correct: "Atlanto ir Ramiojo",
        distractors: ["Atlanto ir Indijos", "Ramiojo ir Arkties", "Indijos ir Ramiojo", "Atlanto ir Arkties", "Indijos ir Pietų"],
        explanation: "Kanalas, atidarytas 1914 m., leidžia laivams plaukti tarp Atlanto ir Ramiojo vandenynų.",
      },
    },
  },
  {
    id: "trn_ro_004",
    category: "transport",
    subTheme: "routes",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Silk Road — ancient trade network roughly 4,000 miles long; China traded silk westward",
    emoji: "🧭",
    translations: {
      en: {
        question: "Which ancient trade route was named after cloth that China sent westward?",
        correct: "The Silk Road",
        distractors: ["The Spice Trail", "The Amber Road", "The Salt Route", "The Gold Road", "The Jade Path"],
        explanation: "China exported silk westward along this famous network of routes for centuries.",
      },
      lt: {
        question: "Kuris senovinis prekybos kelias pavadintas pagal audinį, kurį Kinija siuntė į vakarus?",
        correct: "Šilko kelias",
        distractors: ["Prieskonių takas", "Gintaro kelias", "Druskos maršrutas", "Aukso kelias", "Nefrito kelias"],
        explanation: "Kinija šimtmečius eksportavo šilką į vakarus šiuo garsiuoju kelių tinklu.",
      },
    },
  },
  {
    id: "trn_ro_005",
    category: "transport",
    subTheme: "routes",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Trans-Siberian Railway — Moscow to Vladivostok; world's longest railway at 9,288 km",
    emoji: "🚏",
    translations: {
      en: {
        question: "The Trans-Siberian Railway is famous for being the world's longest what?",
        correct: "Railway",
        distractors: ["Road", "Canal", "Bridge", "Tunnel", "Motorway"],
        explanation: "At 9,288 km, it stretches from Moscow to Vladivostok on Russia's Pacific coast.",
      },
      lt: {
        question: "Kuo pasaulyje yra ilgiausias Transsibiro geležinkelis?",
        correct: "Geležinkelis",
        distractors: ["Kelias", "Kanalas", "Tiltas", "Tunelis", "Greitkelis"],
        explanation: "9 288 km ilgio jis driekiasi nuo Maskvos iki Vladivostoko Rusijos Ramiojo vandenyno pakrantėje.",
      },
    },
  },
  {
    id: "trn_ro_006",
    category: "transport",
    subTheme: "routes",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Orient Express — luxury train first ran Paris to Constantinople 1883; linked Europe and Middle East",
    emoji: "🏞️",
    translations: {
      en: {
        question: "The Orient Express was a famous luxury train linking Paris to which eastern city?",
        correct: "Constantinople",
        distractors: ["St. Petersburg", "Alexandria", "Thessaloniki", "Bucharest", "Vladivostok"],
        explanation: "From 1883 the Orient Express carried passengers in style from Paris to Constantinople.",
      },
      lt: {
        question: "Su kuriuo rytų miestu prabangusis Orient Express traukinys jungė Paryžių?",
        correct: "Konstantinopolis",
        distractors: ["Sankt Peterburgas", "Aleksandrija", "Salonikiai", "Bukareštas", "Vladivostokas"],
        explanation: "Nuo 1883 m. Orient Express prabangiai gabeno keleivius iš Paryžiaus į Konstantinopolį.",
      },
    },
  },
  {
    id: "trn_ro_007",
    category: "transport",
    subTheme: "routes",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Pony Express — operated April 1860 to October 1861; riders carried mail on horseback",
    emoji: "🧭",
    translations: {
      en: {
        question: "The Pony Express carried letters across the USA using which animals?",
        correct: "Horses",
        distractors: ["Donkeys", "Mules", "Camels", "Oxen", "Dogs"],
        explanation: "Riders swapped horses every 10-15 miles to speed mail from Missouri to California.",
      },
      lt: {
        question: "Kokius gyvūnus Pony Express naudojo laiškams gabenti per JAV?",
        correct: "Arkliai",
        distractors: ["Asilai", "Mulai", "Kupranugariai", "Jaučiai", "Šunys"],
        explanation: "Raiteliai keitė arklius kas 10–15 mylių, kad greitai pristatytų paštą nuo Misūrio iki Kalifornijos.",
      },
    },
  },
  {
    id: "trn_ro_008",
    category: "transport",
    subTheme: "routes",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Appalachian Trail — 2,197.9 miles from Springer Mtn, Georgia to Mt Katahdin, Maine; 14 states",
    emoji: "🗺️",
    translations: {
      en: {
        question: "The Appalachian Trail is a long hiking path mainly in which country?",
        correct: "United States",
        distractors: ["Canada", "Australia", "New Zealand", "United Kingdom", "Switzerland"],
        explanation: "The trail spans about 2,200 miles through 14 US states from Georgia to Maine.",
      },
      lt: {
        question: "Kurioje šalyje daugiausia driekiasi ilgasis Apalačų žygių takas?",
        correct: "Jungtinės Valstijos",
        distractors: ["Kanada", "Australija", "Naujoji Zelandija", "Jungtinė Karalystė", "Šveicarija"],
        explanation: "Takas driekiasi apie 2 200 mylių per 14 JAV valstijų nuo Džordžijos iki Meino.",
      },
    },
  },
  {
    id: "trn_ro_009",
    category: "transport",
    subTheme: "routes",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Pan-American Highway — Guinness record for world's longest motorable road; passes through 14 countries",
    emoji: "🛣️",
    translations: {
      en: {
        question: "How many continents does the Pan-American Highway pass through?",
        correct: "Two",
        distractors: ["One", "Three", "Four", "Five", "Six"],
        explanation: "The highway runs through North and South America, crossing 14 countries.",
      },
      lt: {
        question: "Per kiek žemynų driekiasi Panamerikos greitkelis?",
        correct: "Du",
        distractors: ["Vieną", "Tris", "Keturis", "Penkis", "Šešis"],
        explanation: "Greitkelis eina per Šiaurės ir Pietų Ameriką, kirsdamas 14 šalių.",
      },
    },
  },
  {
    id: "trn_ro_010",
    category: "transport",
    subTheme: "routes",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Inca road system (Qhapaq Nan) — ~40,000 km network in South America; UNESCO 2014",
    emoji: "🏞️",
    translations: {
      en: {
        question: "Which ancient civilization built a 40,000 km road network across South America?",
        correct: "The Incas",
        distractors: ["The Aztecs", "The Maya", "The Olmecs", "The Toltecs", "The Zapotecs"],
        explanation: "The Inca road system, Qhapaq Nan, linked the vast empire from Colombia to Chile.",
      },
      lt: {
        question: "Kuri senovinė civilizacija pastatė 40 000 km kelių tinklą Pietų Amerikoje?",
        correct: "Inkai",
        distractors: ["Actekai", "Majai", "Olmekai", "Toltekai", "Sapotekai"],
        explanation: "Inkų kelių sistema Qhapaq Nan jungė didžiulę imperiją nuo Kolumbijos iki Čilės.",
      },
    },
  },

  // ===================== VIDUTINIS (12–18 m. paauglys) =====================
  {
    id: "trn_ro_011",
    category: "transport",
    subTheme: "routes",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Route 66 nickname 'Mother Road' coined by John Steinbeck in The Grapes of Wrath, 1939",
    emoji: "🧳",
    translations: {
      en: {
        question: "Which author nicknamed Route 66 the Mother Road in a famous novel?",
        correct: "John Steinbeck",
        distractors: ["Ernest Hemingway", "Jack Kerouac", "Mark Twain", "F. Scott Fitzgerald", "William Faulkner"],
        explanation: "Steinbeck used the phrase in his 1939 Dust Bowl novel The Grapes of Wrath.",
      },
      lt: {
        question: "Kuris rašytojas garsaus romano puslapiuose Route 66 pavadino Motinos keliu?",
        correct: "John Steinbeck",
        distractors: ["Ernest Hemingway", "Jack Kerouac", "Mark Twain", "F. Scott Fitzgerald", "William Faulkner"],
        explanation: "Steinbeckas šią frazę pavartojo 1939 m. romane apie Dulkių audros pabėgėlius.",
      },
    },
  },
  {
    id: "trn_ro_012",
    category: "transport",
    subTheme: "routes",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Trans-Siberian Railway — construction began 1891, completed 1916; crosses 8 time zones",
    emoji: "🗺️",
    translations: {
      en: {
        question: "How many time zones does the Trans-Siberian Railway cross on its full journey?",
        correct: "Eight",
        distractors: ["Four", "Six", "Ten", "Twelve", "Three"],
        explanation: "The six-day journey from Moscow to Vladivostok crosses eight time zones.",
      },
      lt: {
        question: "Kiek laiko juostų kerta Transsibiro geležinkelis per visą maršrutą?",
        correct: "Aštuonias",
        distractors: ["Keturias", "Šešias", "Dešimt", "Dvylika", "Tris"],
        explanation: "Šešių dienų kelionė iš Maskvos iki Vladivostoko kerta aštuonias laiko juostas.",
      },
    },
  },
  {
    id: "trn_ro_013",
    category: "transport",
    subTheme: "routes",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Pony Express operated only 18 months (April 1860 – October 1861); ended when telegraph completed",
    emoji: "🧭",
    translations: {
      en: {
        question: "The Pony Express shut down because a new technology replaced it — what was it?",
        correct: "The telegraph",
        distractors: ["The telephone", "The railroad", "The motor car", "The aeroplane", "The postal van"],
        explanation: "When the transcontinental telegraph was completed in October 1861, the Pony Express closed two days later.",
      },
      lt: {
        question: "Pony Express užsidarė, nes ją pakeitė nauja technologija — kokia?",
        correct: "Telegrafas",
        distractors: ["Telefonas", "Geležinkelis", "Automobilis", "Lėktuvas", "Pašto furgonas"],
        explanation: "Kai 1861 m. spalį buvo baigtas transžemyninis telegrafas, Pony Express užsidarė po dviejų dienų.",
      },
    },
  },
  {
    id: "trn_ro_014",
    category: "transport",
    subTheme: "routes",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Camino de Santiago — scallop shell is the pilgrim's emblem; pilgrims carry it as a symbol",
    emoji: "🏞️",
    translations: {
      en: {
        question: "Which creature's shell is the symbol of the Camino de Santiago pilgrimage?",
        correct: "Scallop",
        distractors: ["Oyster", "Snail", "Conch", "Clam", "Mussel"],
        explanation: "Medieval pilgrims wore the scallop shell to prove they had reached Santiago.",
      },
      lt: {
        question: "Kokio gyvūno kriauklė yra Camino de Santiago piligrimystės simbolis?",
        correct: "Šukutė",
        distractors: ["Austrė", "Sraigė", "Trimitinė kriauklė", "Geldutė", "Midija"],
        explanation: "Viduramžių piligrimai nešiojo šukutę, kad įrodytų, jog pasiekė Santjagą.",
      },
    },
  },
  {
    id: "trn_ro_015",
    category: "transport",
    subTheme: "routes",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Panama Canal — shortened New York to San Francisco voyage by ~8,000 nautical miles vs Cape Horn route",
    emoji: "🗺️",
    translations: {
      en: {
        question: "The Panama Canal saved ships from having to go around which cape?",
        correct: "Cape Horn",
        distractors: ["Cape of Good Hope", "Cape Hatteras", "Cape Cod", "Cape Finisterre", "Cape Verde"],
        explanation: "Ships save about 8,000 nautical miles by using the canal instead of sailing around Cape Horn.",
      },
      lt: {
        question: "Kurio kyšulio laivams nebereikėjo aplenkti dėl Panamos kanalo?",
        correct: "Horno kyšulys",
        distractors: ["Gerosios Vilties kyšulys", "Hateraso kyšulys", "Kodo kyšulys", "Finisterės kyšulys", "Žaliasis Kyšulys"],
        explanation: "Plaukdami kanalu laivai sutaupo apie 8 000 jūrmylių, nebeapiplaukdami Horno kyšulio.",
      },
    },
  },
  {
    id: "trn_ro_016",
    category: "transport",
    subTheme: "routes",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Silk Road — name coined by German geographer Ferdinand von Richthofen in 1877",
    emoji: "🧭",
    translations: {
      en: {
        question: "A German geographer coined the name Silk Road in 1877 — what was his surname?",
        correct: "Richthofen",
        distractors: ["Humboldt", "Hegel", "Liebknecht", "Schliemann", "Mercator"],
        explanation: "Ferdinand von Richthofen used the German term Seidenstrasse in his 1877 work on China.",
      },
      lt: {
        question: "Vokiečių geografas sukūrė pavadinimą Šilko kelias 1877 m. — kokia buvo jo pavardė?",
        correct: "Richthofenas",
        distractors: ["Humboldtas", "Hegelis", "Liebknechtas", "Schliemanas", "Mercatorius"],
        explanation: "Ferdinandas von Richthofenas 1877 m. darbe apie Kiniją vartojo terminą Seidenstrasse.",
      },
    },
  },
  {
    id: "trn_ro_017",
    category: "transport",
    subTheme: "routes",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Appalachian Trail — first completed thru-hike by Earl Shaffer in 1948; trail proposed by Benton MacKaye 1921",
    emoji: "🛣️",
    translations: {
      en: {
        question: "Who became the first person to thru-hike the entire Appalachian Trail in 1948?",
        correct: "Earl Shaffer",
        distractors: ["John Muir", "Benton MacKaye", "Bill Bryson", "Ed Garvey", "Emma Gatewood"],
        explanation: "Shaffer completed the 2,000-mile trail in one continuous journey after World War II.",
      },
      lt: {
        question: "Kas 1948 m. pirmasis nuėjo visą Apalačų taką viena nepertraukiama kelione?",
        correct: "Earl Shaffer",
        distractors: ["John Muir", "Benton MacKaye", "Bill Bryson", "Ed Garvey", "Emma Gatewood"],
        explanation: "Šafferis po Antrojo pasaulinio karo viena kelione įveikė visą 2 000 mylių taką.",
      },
    },
  },
  {
    id: "trn_ro_018",
    category: "transport",
    subTheme: "routes",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Orient Express — created by Belgian engineer Georges Nagelmackers; first ran October 4, 1883",
    emoji: "🏞️",
    translations: {
      en: {
        question: "The Orient Express was created by Georges Nagelmackers, who was from which country?",
        correct: "Belgium",
        distractors: ["France", "Switzerland", "Austria", "Germany", "England"],
        explanation: "Belgian engineer Nagelmackers founded the Wagons-Lits company that ran the Orient Express.",
      },
      lt: {
        question: "Iš kurios šalies kilęs Orient Express kūrėjas Georges Nagelmackers?",
        correct: "Belgija",
        distractors: ["Prancūzija", "Šveicarija", "Austrija", "Vokietija", "Anglija"],
        explanation: "Belgų inžinierius Nagelmackersas įkūrė Wagons-Lits kompaniją, valdžiusią Orient Express.",
      },
    },
  },
  {
    id: "trn_ro_019",
    category: "transport",
    subTheme: "routes",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Inca chasqui runners relayed messages along Qhapaq Nan; could cover ~1,250 miles in one week",
    emoji: "🧭",
    translations: {
      en: {
        question: "Inca chasqui runners used which device, made of knotted strings, to carry recorded messages?",
        correct: "Quipu",
        distractors: ["Papyrus", "Clay tablet", "Wax seal", "Bark scroll", "Stone disc"],
        explanation: "Runners relayed quipus — knotted string records — across the Inca road network at speed.",
      },
      lt: {
        question: "Kaip vadinosi inkų pasiuntinių časkių priemonė iš mazgotų virvių žinutėms perduoti?",
        correct: "Kipu",
        distractors: ["Papirusas", "Molinė lentelė", "Vaškinis antspaudas", "Žievės ritinys", "Akmens diskas"],
        explanation: "Pasiuntiniai inkų kelių tinklu sparčiai perdavinėjo kipus — mazgais užrašytus įrašus.",
      },
    },
  },
  {
    id: "trn_ro_020",
    category: "transport",
    subTheme: "routes",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Vasco da Gama reached India via Cape of Good Hope sea route in 1498, opening the maritime spice route",
    emoji: "🗺️",
    translations: {
      en: {
        question: "Which explorer first sailed the sea route around Africa to reach India in 1498?",
        correct: "Vasco da Gama",
        distractors: ["Christopher Columbus", "Ferdinand Magellan", "Bartolomeu Dias", "John Cabot", "Amerigo Vespucci"],
        explanation: "Da Gama rounded the Cape of Good Hope and reached India, opening the maritime spice route.",
      },
      lt: {
        question: "Kuris tyrinėtojas pirmasis 1498 m. nuplaukė jūros keliu aplink Afriką iki Indijos?",
        correct: "Vasco da Gama",
        distractors: ["Kristupas Kolumbas", "Fernandas Magelanas", "Bartolomėjus Diasas", "Johnas Cabotas", "Amerigo Vespucci"],
        explanation: "Da Gama apiplaukė Gerosios Vilties kyšulį ir pasiekė Indiją, atverdamas jūrinį prieskonių kelią.",
      },
    },
  },

  // ===================== SUNKUS (suaugęs, kuris domisi) =====================
  {
    id: "trn_ro_021",
    category: "transport",
    subTheme: "routes",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Route 66 decommissioned June 27, 1985; replaced by the Interstate Highway System",
    emoji: "🛣️",
    translations: {
      en: {
        question: "In which year was Route 66 officially removed from the US Highway System?",
        correct: "1985",
        distractors: ["1972", "1960", "1990", "2001", "1978"],
        explanation: "Route 66 was decommissioned on June 27, 1985, after Interstate highways took over its role.",
      },
      lt: {
        question: "Kuriais metais Route 66 oficialiai išbrauktas iš JAV greitkelių sistemos?",
        correct: "1985",
        distractors: ["1972", "1960", "1990", "2001", "1978"],
        explanation: "Route 66 panaikintas 1985 m. birželio 27 d., kai jo vaidmenį perėmė tarpvalstijiniai greitkeliai.",
      },
    },
  },
  {
    id: "trn_ro_022",
    category: "transport",
    subTheme: "routes",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Trans-Siberian Railway — construction started 1891 when Tsarevich Nicholas turned first sod at Vladivostok",
    emoji: "🏞️",
    translations: {
      en: {
        question: "In which city did Tsarevich Nicholas ceremonially begin Trans-Siberian construction in 1891?",
        correct: "Vladivostok",
        distractors: ["Moscow", "Chelyabinsk", "Irkutsk", "Novosibirsk", "Yekaterinburg"],
        explanation: "Nicholas shovelled the first earth at Vladivostok in May 1891; the line was completed in 1916.",
      },
      lt: {
        question: "Kuriame mieste caraitis Nikolajus 1891 m. iškilmingai pradėjo Transsibiro statybas?",
        correct: "Vladivostokas",
        distractors: ["Maskva", "Čeliabinskas", "Irkutskas", "Novosibirskas", "Jekaterinburgas"],
        explanation: "Nikolajus 1891 m. gegužę Vladivostoke iškasė pirmąją žemę; linija baigta 1916 m.",
      },
    },
  },
  {
    id: "trn_ro_023",
    category: "transport",
    subTheme: "routes",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Agatha Christie's Murder on the Orient Express published 1934; she first rode the train in 1928",
    emoji: "🧳",
    translations: {
      en: {
        question: "Agatha Christie set her murder mystery on the Orient Express after riding it in which year?",
        correct: "1928",
        distractors: ["1918", "1933", "1920", "1945", "1935"],
        explanation: "Christie first rode the Orient Express in 1928; her novel was published in 1934.",
      },
      lt: {
        question: "Kuriais metais Agatha Christie pirmą kartą važiavo Orient Express traukiniu, vėliau įkvėpusiu jos romaną?",
        correct: "1928",
        distractors: ["1918", "1933", "1920", "1945", "1935"],
        explanation: "Christie pirmą kartą Orient Express traukiniu važiavo 1928 m.; jos romanas išleistas 1934 m.",
      },
    },
  },
  {
    id: "trn_ro_024",
    category: "transport",
    subTheme: "routes",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Pan-American Highway has a break called the Darién Gap, ~96 km of impassable jungle between Panama and Colombia",
    emoji: "🗺️",
    translations: {
      en: {
        question: "What is the name of the jungle gap that interrupts the Pan-American Highway?",
        correct: "The Darién Gap",
        distractors: ["The Amazon Break", "The Chocó Gap", "The Andes Gap", "The Panama Rift", "The Isthmus Break"],
        explanation: "About 96 km of roadless jungle in Panama and Colombia interrupts the highway.",
      },
      lt: {
        question: "Kaip vadinamas džiunglių plyšys, pertraukiantis Panamerikos greitkelį?",
        correct: "Darjeno tarpas",
        distractors: ["Amazonės pertrauka", "Čoko tarpas", "Andų spraga", "Panamos plyšys", "Sąsmaukos pertrauka"],
        explanation: "Apie 96 km bekelių džiunglių Panamoje ir Kolumbijoje pertraukia greitkelį.",
      },
    },
  },
  {
    id: "trn_ro_025",
    category: "transport",
    subTheme: "routes",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Inca road Qhapaq Nan — declared UNESCO World Heritage Site on June 21, 2014; covers 6 countries",
    emoji: "🏞️",
    translations: {
      en: {
        question: "The Inca road Qhapaq Nan was declared a UNESCO World Heritage Site in which year?",
        correct: "2014",
        distractors: ["2000", "2008", "1992", "2019", "2005"],
        explanation: "UNESCO inscribed the Qhapaq Nan on June 21, 2014, recognising it across six countries.",
      },
      lt: {
        question: "Kuriais metais inkų kelias Qhapaq Nan paskelbtas UNESCO pasaulio paveldo objektu?",
        correct: "2014",
        distractors: ["2000", "2008", "1992", "2019", "2005"],
        explanation: "UNESCO jį įrašė 2014 m. birželio 21 d., pripažindama šešiose šalyse.",
      },
    },
  },
  {
    id: "trn_ro_026",
    category: "transport",
    subTheme: "routes",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Grand Trunk Road rebuilt by Sher Shah Suri 1540-1545; runs ~2,400 km from Afghanistan through Pakistan and India to Bangladesh; called Sadak-e-Azam",
    emoji: "🧭",
    translations: {
      en: {
        question: "Sher Shah Suri called his rebuilt Grand Trunk Road by what name meaning 'the great road'?",
        correct: "Sadak-e-Azam",
        distractors: ["Shahi Raj Marg", "Uttar Path", "Mughal Marg", "Bharat Marg", "Dilli Marg"],
        explanation: "Suri rebuilt the road between 1540 and 1545 and named it Sadak-e-Azam.",
      },
      lt: {
        question: "Kokiu didįjį kelią reiškiančiu vardu Šer Šahas Suris pavadino atstatytą Didįjį magistralinį kelią?",
        correct: "Sadak-e-Azam",
        distractors: ["Shahi Raj Marg", "Uttar Path", "Mughal Marg", "Bharat Marg", "Dilli Marg"],
        explanation: "Šer Šahas Suris atstatė kelią 1540–1545 m. ir jį pavadino Sadak-e-Azam.",
      },
    },
  },
  {
    id: "trn_ro_027",
    category: "transport",
    subTheme: "routes",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Trade winds — Portuguese perfected 'volta do mar' technique in 15th century; used circular wind loop to return from Africa",
    emoji: "🗺️",
    translations: {
      en: {
        question: "Portuguese sailors used which looping wind technique to sail home from Africa?",
        correct: "Volta do mar",
        distractors: ["Vento largo", "Mar de fora", "Brisa do sul", "Caminho do vento", "Rota do norte"],
        explanation: "The volta do mar used circular Atlantic winds and currents to make the homeward journey possible.",
      },
      lt: {
        question: "Kokį kilpinį vėjo metodą naudojo portugalų jūreiviai plaukdami namo iš Afrikos?",
        correct: "Volta do mar",
        distractors: ["Vento largo", "Mar de fora", "Brisa do sul", "Caminho do vento", "Rota do norte"],
        explanation: "Volta do mar išnaudojo žiedinius Atlanto vėjus ir sroves, kad grįžtamoji kelionė būtų įmanoma.",
      },
    },
  },
  {
    id: "trn_ro_028",
    category: "transport",
    subTheme: "routes",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Silk Road — Buddhism spread from India to China along these routes during Han Dynasty",
    emoji: "🧳",
    translations: {
      en: {
        question: "Which religion, besides goods, famously spread from India to China along the Silk Road?",
        correct: "Buddhism",
        distractors: ["Islam", "Christianity", "Hinduism", "Zoroastrianism", "Judaism"],
        explanation: "Buddhist ideas and texts travelled the Silk Road into China during the Han Dynasty.",
      },
      lt: {
        question: "Kuri religija, be prekių, Šilko keliu plačiai plito iš Indijos į Kiniją?",
        correct: "Budizmas",
        distractors: ["Islamas", "Krikščionybė", "Induizmas", "Zoroastrizmas", "Judaizmas"],
        explanation: "Budistinės idėjos ir tekstai Šilko keliu pasiekė Kiniją Hanų dinastijos laikais.",
      },
    },
  },
  {
    id: "trn_ro_029",
    category: "transport",
    subTheme: "routes",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Camino de Santiago — Camino Francés is the most popular route, starting in southern France, about 790 km",
    emoji: "🧭",
    translations: {
      en: {
        question: "The most walked Camino de Santiago route starts in southern France — what is it called?",
        correct: "Camino Francés",
        distractors: ["Camino Portugués", "Via de la Plata", "Camino del Norte", "Camino Primitivo", "Camino Inglés"],
        explanation: "The French Way (Camino Francés) covers about 790 km and draws the most pilgrims.",
      },
      lt: {
        question: "Kaip vadinamas populiariausias Camino de Santiago maršrutas, prasidedantis Pietų Prancūzijoje?",
        correct: "Camino Francés",
        distractors: ["Camino Portugués", "Via de la Plata", "Camino del Norte", "Camino Primitivo", "Camino Inglés"],
        explanation: "Prancūzų kelias (Camino Francés) driekiasi apie 790 km ir pritraukia daugiausiai piligrimų.",
      },
    },
  },
  {
    id: "trn_ro_030",
    category: "transport",
    subTheme: "routes",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Khyber Pass — 53 km mountain pass linking Afghanistan and Pakistan; used by Alexander the Great, Babur, Genghis Khan",
    emoji: "🏞️",
    translations: {
      en: {
        question: "The Khyber Pass links Afghanistan with which neighbouring country?",
        correct: "Pakistan",
        distractors: ["India", "Iran", "China", "Tajikistan", "Uzbekistan"],
        explanation: "The 53-km pass through the Hindu Kush has been a strategic crossing for millennia.",
      },
      lt: {
        question: "Su kuria kaimynine šalimi Chiberio perėja jungia Afganistaną?",
        correct: "Pakistanas",
        distractors: ["Indija", "Iranas", "Kinija", "Tadžikistanas", "Uzbekistanas"],
        explanation: "53 km perėja per Hindukušo kalnus jau tūkstantmečius yra strateginis praėjimas.",
      },
    },
  },

  // ===================== EKSTREMALUS (srities žinovas) =====================
  {
    id: "trn_ro_031",
    category: "transport",
    subTheme: "routes",
    level: "ekstremalus",
    isTrap: true,
    sourceVerified: "Silk Road — actual name coined 1877 by Richthofen; ancient traders never used this term themselves",
    emoji: "🧭",
    translations: {
      en: {
        question: "Ancient merchants who used the Silk Road actually called their network by that name — true or false?",
        correct: "False — the name came later",
        distractors: ["True — it was a Han Dynasty name", "True — Romans coined it", "True — Arabic traders named it", "True — it appeared in Chinese texts", "False — it was called the Spice Road"],
        explanation: "The term was popularized in 1877 by German geographer von Richthofen; ancient traders used no single name.",
      },
      lt: {
        question: "Senovės pirkliai, naudoję Šilko kelią, jį patys taip ir vadino — tiesa ar ne?",
        correct: "Ne — pavadinimas atsirado vėliau",
        distractors: ["Taip — tai Hanų dinastijos pavadinimas", "Taip — jį sukūrė romėnai", "Taip — jį pavadino arabų pirkliai", "Taip — jis minimas kinų tekstuose", "Ne — jis vadintas Prieskonių keliu"],
        explanation: "Terminą 1877 m. išpopuliarino vokiečių geografas von Richthofenas; senovės pirkliai vieningo pavadinimo neturėjo.",
      },
    },
  },
  {
    id: "trn_ro_032",
    category: "transport",
    subTheme: "routes",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Panama Canal — US construction began 1904, opened August 15, 1914; France attempted first and failed 1881-1889 under de Lesseps",
    emoji: "🗺️",
    translations: {
      en: {
        question: "Which country first attempted to build the Panama Canal before the USA took over?",
        correct: "France",
        distractors: ["Britain", "Spain", "Colombia", "Netherlands", "Germany"],
        explanation: "Ferdinand de Lesseps led a failed French attempt from 1881 to 1889; the US succeeded in 1914.",
      },
      lt: {
        question: "Kuri šalis pirmoji bandė iškasti Panamos kanalą, kol JAV perėmė darbą?",
        correct: "Prancūzija",
        distractors: ["Britanija", "Ispanija", "Kolumbija", "Nyderlandai", "Vokietija"],
        explanation: "Ferdinandas de Lessepsas vadovavo nesėkmingam prancūzų bandymui 1881–1889 m.; JAV pavyko 1914 m.",
      },
    },
  },
  {
    id: "trn_ro_033",
    category: "transport",
    subTheme: "routes",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Pony Express — riders were young and light; job ads reportedly preferred orphans; each rider covered 75-100 miles per shift",
    emoji: "🛣️",
    translations: {
      en: {
        question: "About how many miles did a single Pony Express rider cover in one shift before handing off?",
        correct: "75 to 100 miles",
        distractors: ["10 to 20 miles", "200 to 300 miles", "30 to 50 miles", "500 miles", "150 to 200 miles"],
        explanation: "Riders galloped 75-100 miles per shift; horses were swapped every 10-15 miles along the way.",
      },
      lt: {
        question: "Kiek apytikriai mylių nujodavo vienas Pony Express raitelis per pamainą iki estafetės perdavimo?",
        correct: "75 iki 100 mylių",
        distractors: ["10 iki 20 mylių", "200 iki 300 mylių", "30 iki 50 mylių", "500 mylių", "150 iki 200 mylių"],
        explanation: "Raiteliai nujodavo 75–100 mylių per pamainą; arkliai keičiami kas 10–15 mylių.",
      },
    },
  },
  {
    id: "trn_ro_034",
    category: "transport",
    subTheme: "routes",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Orient Express — first direct all-rail service Paris to Constantinople began 1889; before that, Danube ferry was needed",
    emoji: "🏞️",
    translations: {
      en: {
        question: "In what year did the Orient Express offer its first fully overland rail journey to Constantinople?",
        correct: "1889",
        distractors: ["1883", "1895", "1900", "1878", "1910"],
        explanation: "The 1883 inaugural trip used a Danube ferry; a fully overland rail route opened in 1889.",
      },
      lt: {
        question: "Kuriais metais Orient Express pirmą kartą pasiūlė kelionę iki Konstantinopolio vien sausuma geležinkeliu?",
        correct: "1889",
        distractors: ["1883", "1895", "1900", "1878", "1910"],
        explanation: "1883 m. pirmajame reise teko naudotis Dunojaus keltu; ištisas geležinkelio maršrutas atidarytas 1889 m.",
      },
    },
  },
  {
    id: "trn_ro_035",
    category: "transport",
    subTheme: "routes",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Camino de Santiago — to receive Compostela certificate, pilgrims must walk at least 100 km or cycle 200 km",
    emoji: "🧳",
    translations: {
      en: {
        question: "What is the minimum distance on foot to earn the Compostela certificate on the Camino?",
        correct: "100 km",
        distractors: ["50 km", "200 km", "500 km", "790 km", "25 km"],
        explanation: "Pilgrims must walk at least 100 km (or cycle 200 km) and collect stamps to earn the certificate.",
      },
      lt: {
        question: "Koks minimalus pėsčiomis nueitas atstumas, norint gauti Compostela pažymėjimą Camino kelyje?",
        correct: "100 km",
        distractors: ["50 km", "200 km", "500 km", "790 km", "25 km"],
        explanation: "Piligrimai turi nueiti bent 100 km pėsčiomis (arba 200 km dviračiu) ir surinkti antspaudus.",
      },
    },
  },
  {
    id: "trn_ro_036",
    category: "transport",
    subTheme: "routes",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Appalachian Trail — Benton MacKaye published proposal in 1921; first section opened 1923 in New York; trail completed 1937",
    emoji: "🗺️",
    translations: {
      en: {
        question: "In which year did Benton MacKaye publish his original proposal for the Appalachian Trail?",
        correct: "1921",
        distractors: ["1910", "1930", "1937", "1948", "1915"],
        explanation: "MacKaye's 1921 article proposed a footpath along the Appalachian ridge; the trail opened fully by 1937.",
      },
      lt: {
        question: "Kuriais metais Bentonas MacKaye paskelbė pirminį Apalačų tako pasiūlymą?",
        correct: "1921",
        distractors: ["1910", "1930", "1937", "1948", "1915"],
        explanation: "1921 m. straipsnyje MacKaye pasiūlė pėsčiųjų taką Apalačų kalnagūbriu; takas visiškai atidarytas 1937 m.",
      },
    },
  },
  {
    id: "trn_ro_037",
    category: "transport",
    subTheme: "routes",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Silk Road — traded goods both ways; Roman glassware traveled east to China in exchange for silk, verified by archaeological finds",
    emoji: "🧭",
    translations: {
      en: {
        question: "Archaeologists have found Roman glassware in ancient Chinese burial sites — what did China send back west in trade?",
        correct: "Silk",
        distractors: ["Jade", "Porcelain", "Tea", "Paper", "Bronze"],
        explanation: "Roman-made soda-lime glass traveled east along the Silk Road and was found in elite Chinese tombs.",
      },
      lt: {
        question: "Archeologai rado romėniško stiklo senovinėse kinų kapavietėse — ką Kinija siuntė atgal į vakarus mainais?",
        correct: "Šilkas",
        distractors: ["Nefritas", "Porcelianas", "Arbata", "Popierius", "Bronza"],
        explanation: "Romėnų pagamintas natrio kalkių stiklas keliavo į rytus ir rastas kilmingųjų kinų kapavietėse.",
      },
    },
  },
  {
    id: "trn_ro_038",
    category: "transport",
    subTheme: "routes",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Trans-Siberian Railway — 9,288 km from Moscow to Vladivostok; crosses 87 cities; construction took 25 years (1891-1916)",
    emoji: "🏞️",
    translations: {
      en: {
        question: "How many years did it take to build the full Trans-Siberian Railway from start to finish?",
        correct: "25 years",
        distractors: ["10 years", "15 years", "40 years", "5 years", "50 years"],
        explanation: "Construction ran from 1891 to 1916 — a 25-year project spanning deserts, mountains, and permafrost.",
      },
      lt: {
        question: "Kiek metų truko visiškai pastatyti Transsibiro geležinkelį nuo pradžios iki pabaigos?",
        correct: "25 metai",
        distractors: ["10 metų", "15 metų", "40 metų", "5 metai", "50 metų"],
        explanation: "Statyba vyko 1891–1916 m. — 25 metų projektas, apimantis dykumas, kalnus ir amžinojo įšalo zonas.",
      },
    },
  },
  {
    id: "trn_ro_039",
    category: "transport",
    subTheme: "routes",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Grand Trunk Road — Rudyard Kipling's novel Kim (1901) features the Grand Trunk Road as a setting; he called it 'a river of life'",
    emoji: "🛣️",
    translations: {
      en: {
        question: "In Rudyard Kipling's novel Kim, which famous road is described as a river of life?",
        correct: "The Grand Trunk Road",
        distractors: ["The Silk Road", "The Khyber Pass road", "The Mughal road", "The Delhi road", "The Calcutta road"],
        explanation: "Kipling's 1901 novel Kim follows its hero along the Grand Trunk Road across the subcontinent.",
      },
      lt: {
        question: "Rudyardo Kiplingo romane Kim kuris garsus kelias apibūdintas kaip gyvybės upė?",
        correct: "Didysis magistralinis kelias",
        distractors: ["Šilko kelias", "Chiberio perėjos kelias", "Mogolų kelias", "Delio kelias", "Kalkutos kelias"],
        explanation: "Kiplingo 1901 m. romane Kim herojus keliauja Didžiuoju magistraliniu keliu per visą subkontinentą.",
      },
    },
  },
  {
    id: "trn_ro_040",
    category: "transport",
    subTheme: "routes",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Panama Canal — took about 10 hours to cross; ~75 ships transit daily on average; US handed canal to Panama December 31, 1999",
    emoji: "🗺️",
    translations: {
      en: {
        question: "On which date did the United States formally hand full control of the Panama Canal to Panama?",
        correct: "31 December 1999",
        distractors: ["4 July 1976", "1 January 2000", "15 August 1989", "1 October 1979", "31 December 1989"],
        explanation: "Under the 1977 Torrijos-Carter Treaties, the US transferred the canal to Panama at noon on 31 Dec 1999.",
      },
      lt: {
        question: "Kokią dieną JAV oficialiai perdavė visą Panamos kanalo kontrolę Panamai?",
        correct: "1999 m. gruodžio 31 d.",
        distractors: ["1976 m. liepos 4 d.", "2000 m. sausio 1 d.", "1989 m. rugpjūčio 15 d.", "1979 m. spalio 1 d.", "1989 m. gruodžio 31 d."],
        explanation: "Pagal 1977 m. Torrijos-Carterio sutartis JAV perdavė kanalą Panamai 1999 m. gruodžio 31 d. vidurdienį.",
      },
    },
  },
];
