/**
 * transportAviation — ✈️ „Aviacija" potemė (tema „Transportas").
 *
 * MAŽAS FAILAS pagal potemę. 40 klausimų (10/lygiui). Aviacijos istorija,
 * fizika, rekordai ir įdomūs faktai — nuo Brolių Raitų iki reaktyvinių lėktuvų.
 * Tik istoriniai/patvirtinti faktai — jokių naujausių reitingų ar incidentų.
 *
 * TAISYKLĖS: 1 teisingas + 5 distraktoriai; ≤46 simb.; teisingas NE ilgiausias >+5;
 * LT be vidinių kabučių; jokio atsakymo klausime; EMOJI NEUTRALUS (neišduoda atsakymo).
 */

import { TriviaQuestion } from "./triviaTypes";

export const TRANSPORT_AVIATION: TriviaQuestion[] = [
  // ===================== LENGVAS (9–12 m. vaikas) =====================
  {
    id: "trn_av_001",
    category: "transport",
    subTheme: "aviation",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Wright brothers first powered flight Dec 17 1903, Kitty Hawk, NC — NASA / Smithsonian NASM",
    emoji: "🛩️",
    translations: {
      en: {
        question: "Which brothers made the very first powered aeroplane flight?",
        correct: "The Wright brothers",
        distractors: ["The Bell brothers", "The Ford brothers", "The Edison brothers", "The Marx brothers", "The Boeing brothers"],
        explanation: "Orville and Wilbur Wright flew at Kitty Hawk on 17 December 1903.",
      },
      lt: {
        question: "Kurie broliai atliko pirmąjį varikliu varomą skrydį lėktuvu?",
        correct: "Broliai Raitai",
        distractors: ["Broliai Belai", "Broliai Fordai", "Broliai Edisonai", "Broliai Marksai", "Broliai Boeingai"],
        explanation: "Orvilas ir Vilburas Raitai skrido Kitty Hawke 1903 m. gruodžio 17 d.",
      },
    },
  },
  {
    id: "trn_av_002",
    category: "transport",
    subTheme: "aviation",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Hot air balloon first flight with animal passengers Sep 19 1783 at Versailles — Château de Versailles / Smithsonian",
    emoji: "🎈",
    translations: {
      en: {
        question: "A sheep, a duck and a rooster were the first passengers in what flying craft?",
        correct: "A hot air balloon",
        distractors: ["A glider", "A blimp", "A helicopter", "An aeroplane", "A hang glider"],
        explanation: "The Montgolfier brothers sent these animals aloft at Versailles in 1783.",
      },
      lt: {
        question: "Avis, antis ir gaidys pirmieji skrido kokiu skraidančiu aparatu?",
        correct: "Oro balionu",
        distractors: ["Sklandytuvu", "Dirižabliu", "Sraigtasparniu", "Lėktuvu", "Deltaplanu"],
        explanation: "Broliai Mongolfjė šiuos gyvūnus pakėlė į orą prie Versalio 1783 m.",
      },
    },
  },
  {
    id: "trn_av_003",
    category: "transport",
    subTheme: "aviation",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Boeing 747 iconic hump upper deck design — Boeing / Smithsonian Air & Space",
    emoji: "✈️",
    translations: {
      en: {
        question: "Which wide-body jet is famous for its distinctive upper-deck hump?",
        correct: "Boeing 747",
        distractors: ["Airbus A380", "Boeing 737", "Concorde", "DC-10", "Airbus A320"],
        explanation: "The 747's raised cockpit and upper deck gave it its unmistakable silhouette.",
      },
      lt: {
        question: "Kuris plataus korpuso reaktyvinis lėktuvas garsėja būdinga viršutinio denio kupra?",
        correct: "Boeing 747",
        distractors: ["Airbus A380", "Boeing 737", "Concorde", "DC-10", "Airbus A320"],
        explanation: "Pakeltas kokpitas ir viršutinis denis suteikė 747 nepakartojamą siluetą.",
      },
    },
  },
  {
    id: "trn_av_004",
    category: "transport",
    subTheme: "aviation",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Contrails are ice crystals formed from engine water vapor at high altitude — FAA / Britannica",
    emoji: "🛫",
    translations: {
      en: {
        question: "Those white streaks a jet leaves across the sky are made of what?",
        correct: "Ice crystals",
        distractors: ["Steam", "Exhaust smoke", "Paint", "Cloud dust", "Water drops"],
        explanation: "Engine water vapour freezes instantly in the cold air, forming ice crystal trails.",
      },
      lt: {
        question: "Iš ko susidaro baltos linijos, kurias lėktuvas palieka danguje?",
        correct: "Ledo kristalų",
        distractors: ["Garo", "Išmetamų dujų dūmų", "Dažų", "Debesų dulkių", "Vandens lašų"],
        explanation: "Variklių vandens garai akimirksniu užšąla šaltame ore ir sudaro ledo kristalų pėdsaką.",
      },
    },
  },
  {
    id: "trn_av_005",
    category: "transport",
    subTheme: "aviation",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "IATA three-letter airport codes — IATA / Simple Flying explainer",
    emoji: "🧳",
    translations: {
      en: {
        question: "How many letters make up the IATA airport code printed on a luggage tag?",
        correct: "Three",
        distractors: ["Two", "Four", "Five", "Six", "One"],
        explanation: "IATA assigns every airport a three-letter code, such as LHR, JFK or CDG.",
      },
      lt: {
        question: "Iš kiek raidžių sudarytas IATA oro uosto kodas, spausdinamas ant bagažo lipduko?",
        correct: "Trijų",
        distractors: ["Dviejų", "Keturių", "Penkių", "Šešių", "Vienos"],
        explanation: "IATA kiekvienam oro uostui suteikia trijų raidžių kodą, pvz., LHR, JFK ar CDG.",
      },
    },
  },
  {
    id: "trn_av_006",
    category: "transport",
    subTheme: "aviation",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Round airplane windows prevent stress cracks — post-de Havilland Comet redesign; How Stuff Works / AFAR",
    emoji: "🛬",
    translations: {
      en: {
        question: "Why are passenger aircraft windows oval rather than square?",
        correct: "To spread air pressure evenly",
        distractors: ["To reduce overall window weight", "To look more aerodynamic", "To let in more natural light", "To fit more rows of seats", "To satisfy aviation designers"],
        explanation: "Rounded edges stop pressure from concentrating at corners and cracking the frame.",
      },
      lt: {
        question: "Kodėl keleivių lėktuvų langai ovalūs, o ne kvadratiniai?",
        correct: "Kad tolygiai paskirstytų oro slėgį",
        distractors: ["Kad sumažintų bendrą langų svorį", "Kad atrodytų aerodinamiškiau", "Kad praleistų daugiau natūralios šviesos", "Kad tilptų daugiau sėdynių eilių", "Kad patiktų aviacijos dizaineriams"],
        explanation: "Suapvalinti kraštai neleidžia slėgiui kauptis kampuose ir įskelti rėmo.",
      },
    },
  },
  {
    id: "trn_av_007",
    category: "transport",
    subTheme: "aviation",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Cockpit name originates from cockfighting pit, later naval coxswain station — Britannica",
    emoji: "✈️",
    translations: {
      en: {
        question: "What is the name for the area of an aircraft where the pilots sit?",
        correct: "Cockpit",
        distractors: ["Control room", "Bridge", "Helm bay", "The galley", "Pilot cabin"],
        explanation: "Originally a pit for cockfighting, the word later moved to naval and then aviation use.",
      },
      lt: {
        question: "Kaip vadinama lėktuvo vieta, kurioje sėdi pilotai?",
        correct: "Kokpitas",
        distractors: ["Valdymo kambarys", "Kapitono tiltelis", "Vairo skyrius", "Virtuvėlė", "Pilotų kabina"],
        explanation: "Iš pradžių žodis reiškė gaidžių peštynių arenėlę, vėliau perėjo į laivybą ir aviaciją.",
      },
    },
  },
  {
    id: "trn_av_008",
    category: "transport",
    subTheme: "aviation",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Hartsfield-Jackson Atlanta busiest airport 2024 with 108.1M passengers — ACI World / Fox 5 Atlanta",
    emoji: "🛫",
    translations: {
      en: {
        question: "In which US city is the world's busiest passenger airport?",
        correct: "Atlanta",
        distractors: ["New York", "Chicago", "Los Angeles", "Dallas", "Denver"],
        explanation: "Hartsfield-Jackson Atlanta handled over 108 million passengers in 2024.",
      },
      lt: {
        question: "Kuriame JAV mieste yra pasaulio judriausias keleivinis oro uostas?",
        correct: "Atlanta",
        distractors: ["Niujorke", "Čikagoje", "Los Andžele", "Dalase", "Denveryje"],
        explanation: "Hartsfild-Džeksono Atlanta oro uostas 2024 m. aptarnavo daugiau nei 108 mln. keleivių.",
      },
    },
  },
  {
    id: "trn_av_009",
    category: "transport",
    subTheme: "aviation",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Helicopters have a main rotor and tail rotor; Igor Sikorsky VS-300 design 1939 — ASME / Smithsonian",
    emoji: "🚁",
    translations: {
      en: {
        question: "What spinning part on top of a helicopter provides its main lift?",
        correct: "The main rotor",
        distractors: ["Propeller", "Tail fin", "Jet engine", "Turbine fan", "Wing flap"],
        explanation: "Rotating blades on the main rotor push air down, lifting the helicopter up.",
      },
      lt: {
        question: "Kuri besisukanti dalis sraigtasparnio viršuje sukuria pagrindinę kėlimo jėgą?",
        correct: "Pagrindinis rotorius",
        distractors: ["Propeleris", "Uodegos stabilizatorius", "Reaktyvinis variklis", "Turbinos ventiliatorius", "Sparno sklendė"],
        explanation: "Besisukančios pagrindinio rotoriaus mentės stumia orą žemyn ir kelia sraigtasparnį aukštyn.",
      },
    },
  },
  {
    id: "trn_av_010",
    category: "transport",
    subTheme: "aviation",
    level: "lengvas",
    isTrap: true,
    sourceVerified: "Flight recorders painted bright orange/yellow since ~1965 mandate — Wikipedia Flight recorder / Britannica",
    emoji: "🧳",
    translations: {
      en: {
        question: "Despite its name, what colour is an aircraft's black box actually painted?",
        correct: "Orange",
        distractors: ["Black", "Yellow", "Red", "White", "Silver"],
        explanation: "It is bright orange so crash investigators can spot it easily in wreckage.",
      },
      lt: {
        question: "Nepaisant pavadinimo, kokia spalva iš tikrųjų dažoma lėktuvo juodoji dėžė?",
        correct: "Oranžinė",
        distractors: ["Juoda", "Geltona", "Raudona", "Balta", "Sidabrinė"],
        explanation: "Ryškiai oranžinė spalva padeda tyrėjams greitai rasti dėžę lėktuvo nuolaužose.",
      },
    },
  },

  // ===================== VIDUTINIS (12–18 m. paauglys) =====================
  {
    id: "trn_av_011",
    category: "transport",
    subTheme: "aviation",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Wright Flyer first flight lasted 12 sec, 120 ft (Orville); longest 59 sec, 852 ft (Wilbur) — NASA / NPS",
    emoji: "🛩️",
    translations: {
      en: {
        question: "How long did the very first powered aeroplane flight last?",
        correct: "12 seconds",
        distractors: ["4 seconds", "30 seconds", "59 seconds", "2 minutes", "5 minutes"],
        explanation: "Orville Wright's first flight on 17 Dec 1903 lasted just 12 seconds and covered 120 feet.",
      },
      lt: {
        question: "Kiek laiko truko pats pirmasis varikliu varomas lėktuvo skrydis?",
        correct: "12 sekundžių",
        distractors: ["4 sekundes", "30 sekundžių", "59 sekundes", "2 minutes", "5 minutes"],
        explanation: "Orvilo Raito pirmasis skrydis 1903 m. gruodžio 17 d. truko vos 12 sekundžių ir nulėkė 120 pėdų.",
      },
    },
  },
  {
    id: "trn_av_012",
    category: "transport",
    subTheme: "aviation",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Concorde cruised at Mach 2.04, approx 2 179 km/h — Britannica / National Museums Scotland",
    emoji: "✈️",
    translations: {
      en: {
        question: "The Concorde cruised at roughly twice the speed of sound, known as what?",
        correct: "Mach 2",
        distractors: ["Mach 0.85", "Mach 1", "Mach 3", "Mach 4", "Mach 5"],
        explanation: "Concorde's cruise speed of Mach 2.04 meant London to New York in about three hours.",
      },
      lt: {
        question: "Concorde skrido maždaug dvigubai greičiau už garso greitį — kaip tai vadinama?",
        correct: "Mach 2",
        distractors: ["Mach 0,85", "Mach 1", "Mach 3", "Mach 4", "Mach 5"],
        explanation: "Concorde greitis Mach 2,04 leido skristi iš Londono į Niujorką vos per tris valandas.",
      },
    },
  },
  {
    id: "trn_av_013",
    category: "transport",
    subTheme: "aviation",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "de Havilland Comet entered service 2 May 1952 with BOAC as world's first jet airliner — RAF Museum / Simple Flying",
    emoji: "🛫",
    translations: {
      en: {
        question: "Which aircraft became the world's first commercial jet airliner in 1952?",
        correct: "De Havilland Comet",
        distractors: ["Boeing 707", "Douglas DC-8", "Tupolev Tu-104", "Avro Canada C102", "Boeing 377"],
        explanation: "The Comet entered service with BOAC on 2 May 1952, flying London to Johannesburg.",
      },
      lt: {
        question: "Kuris lėktuvas 1952 m. tapo pirmuoju pasaulyje komerciniu reaktyviniu laineriu?",
        correct: "De Havilland Comet",
        distractors: ["Boeing 707", "Douglas DC-8", "Tupolev Tu-104", "Avro Canada C102", "Boeing 377"],
        explanation: "Comet pradėjo skrydžius su BOAC 1952 m. gegužės 2 d. maršrutu Londonas–Johanesburgas.",
      },
    },
  },
  {
    id: "trn_av_014",
    category: "transport",
    subTheme: "aviation",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Montgolfier brothers — Joseph and Etienne, paper manufacturers; first public balloon Jun 4 1783 — Britannica",
    emoji: "🎈",
    translations: {
      en: {
        question: "What was the profession of the Montgolfier brothers who invented the hot air balloon?",
        correct: "Paper manufacturers",
        distractors: ["Watch and clock repairers", "Travelling glassblowers", "Cathedral stonemasons", "Ironworkers and smiths", "Textile mill workers"],
        explanation: "Joseph and Etienne Montgolfier ran a paper factory, which gave them the materials to experiment.",
      },
      lt: {
        question: "Kokia profesija vertėsi broliai Mongolfjė, išradę oro balioną?",
        correct: "Popieriaus gamintojai",
        distractors: ["Laikrodžių taisytojai", "Keliaujantys stiklo pūtikai", "Katedrų mūrininkai", "Kalviai ir metalo meistrai", "Tekstilės fabrikų darbininkai"],
        explanation: "Žozefas ir Etjenas Mongolfjė turėjo popieriaus fabriką, iš kurio gavo medžiagų eksperimentams.",
      },
    },
  },
  {
    id: "trn_av_015",
    category: "transport",
    subTheme: "aviation",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Boeing 747 first commercial service Pan Am Jan 22 1970 JFK–LHR — Airways Magazine / This Day in Aviation",
    emoji: "✈️",
    translations: {
      en: {
        question: "Which airline put the Boeing 747 into commercial service first?",
        correct: "Pan Am",
        distractors: ["TWA", "British Airways", "Lufthansa", "Air France", "Delta"],
        explanation: "Pan Am flew the 747's first passenger service on 22 January 1970, New York to London.",
      },
      lt: {
        question: "Kuri aviakompanija pirmoji pradėjo komercinius skrydžius su Boeing 747?",
        correct: "Pan Am",
        distractors: ["TWA", "British Airways", "Lufthansa", "Air France", "Delta"],
        explanation: "Pan Am 1970 m. sausio 22 d. atliko pirmąjį keleivių skrydį Niujorkas–Londonas.",
      },
    },
  },
  {
    id: "trn_av_016",
    category: "transport",
    subTheme: "aviation",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Hughes H-4 Hercules flew only once, Nov 2 1947, for about 1 mile at 70 ft altitude — ASME / New Atlas",
    emoji: "🛩️",
    translations: {
      en: {
        question: "How many times did the giant Hughes H-4 Hercules flying boat ever fly?",
        correct: "Once",
        distractors: ["Never", "Twice", "Five times", "Twelve times", "Hundreds of times"],
        explanation: "On 2 November 1947, it flew for about one mile at 70 feet altitude — its only flight ever.",
      },
      lt: {
        question: "Kiek kartų iš viso skrido milžiniškas skraidantis laivas Hughes H-4 Hercules?",
        correct: "Vieną kartą",
        distractors: ["Niekada", "Du kartus", "Penkis kartus", "Dvylika kartų", "Šimtus kartų"],
        explanation: "1947 m. lapkričio 2 d. jis skrido apie vieną mylią 70 pėdų aukštyje — tai buvo vienintelis jo skrydis.",
      },
    },
  },
  {
    id: "trn_av_017",
    category: "transport",
    subTheme: "aviation",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Cabin altitude pressurised to 8 000 ft max to balance structural weight vs passenger comfort — SKYbrary / Honeywell",
    emoji: "🛬",
    translations: {
      en: {
        question: "Why do jet airliners pressurise the cabin during flight?",
        correct: "So passengers can breathe normally",
        distractors: ["To keep the interior temperature low", "To reduce the roar of the engines", "To improve the aircraft's fuel burn", "To prevent turbulence shaking seats", "To power the in-flight entertainment"],
        explanation: "At cruising altitude the outside air is too thin; pressurisation keeps enough oxygen inside.",
      },
      lt: {
        question: "Kodėl reaktyviniai laineriai skrydžio metu palaiko slėgį salone?",
        correct: "Kad keleiviai galėtų normaliai kvėpuoti",
        distractors: ["Kad būtų palaikoma žema vidaus temperatūra", "Kad sumažėtų variklių ūžesys salone", "Kad sumažėtų lėktuvo kuro sąnaudos", "Kad turbulencija nedrebintų sėdynių", "Kad veiktų pramogų sistema"],
        explanation: "Dideliame aukštyje oras lauke per retas; padidintas slėgis išlaiko salone pakankamai deguonies.",
      },
    },
  },
  {
    id: "trn_av_018",
    category: "transport",
    subTheme: "aviation",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Concorde last commercial flight Oct 24 2003; retired due to economics and 2000 crash aftermath — History.com",
    emoji: "✈️",
    translations: {
      en: {
        question: "In which year did Concorde make its very last commercial flight?",
        correct: "2003",
        distractors: ["1997", "2000", "2001", "2010", "2012"],
        explanation: "British Airways and Air France both retired Concorde on 24 October 2003.",
      },
      lt: {
        question: "Kuriais metais Concorde atliko paskutinį komercinį skrydį?",
        correct: "2003",
        distractors: ["1997", "2000", "2001", "2010", "2012"],
        explanation: "British Airways ir Air France galutinai nustojo eksploatuoti Concorde 2003 m. spalio 24 d.",
      },
    },
  },
  {
    id: "trn_av_019",
    category: "transport",
    subTheme: "aviation",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Igor Sikorsky flew first practical single-rotor helicopter VS-300 on Sep 14 1939 — Connecticut History / ASME",
    emoji: "🚁",
    translations: {
      en: {
        question: "Who flew the first practical single-rotor helicopter in 1939?",
        correct: "Igor Sikorsky",
        distractors: ["Orville Wright", "Howard Hughes", "Juan de la Cierva", "Paul Cornu", "Heinrich Focke"],
        explanation: "Sikorsky's VS-300 lifted off on 14 September 1939 at Stratford, Connecticut.",
      },
      lt: {
        question: "Kas 1939 m. skrido pirmuoju praktiniu vieno rotoriaus sraigtasparniu?",
        correct: "Igor Sikorsky",
        distractors: ["Orville Wright", "Howard Hughes", "Juan de la Cierva", "Paul Cornu", "Heinrich Focke"],
        explanation: "Sikorsky VS-300 pakilo 1939 m. rugsėjo 14 d. Stratforde, Konektikuto valstijoje.",
      },
    },
  },
  {
    id: "trn_av_020",
    category: "transport",
    subTheme: "aviation",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Wright brothers ran a bicycle shop in Dayton Ohio before aviation — Britannica / NPS",
    emoji: "🛩️",
    translations: {
      en: {
        question: "Before building their famous Flyer, what business did the Wright brothers run?",
        correct: "A bicycle shop",
        distractors: ["A watch repair shop", "A printing press", "A car garage", "A camera shop", "A hardware store"],
        explanation: "Their Dayton bicycle shop funded experiments and gave them key mechanical skills.",
      },
      lt: {
        question: "Prieš sukurdami garsųjį Flyer, kokį verslą turėjo broliai Raitai?",
        correct: "Dviračių parduotuvę",
        distractors: ["Laikrodžių taisyklą", "Spaustuvę", "Automobilių dirbtuves", "Fotoaparatų parduotuvę", "Ūkinių prekių parduotuvę"],
        explanation: "Jų dviračių parduotuvė Deitone finansavo eksperimentus ir suteikė svarbių mechanikos įgūdžių.",
      },
    },
  },

  // ===================== SUNKUS (suaugęs, kuris domisi) =====================
  {
    id: "trn_av_021",
    category: "transport",
    subTheme: "aviation",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Black box invented by Australian David Warren in 1956, called ARL Flight Memory Unit — DST / Wikipedia",
    emoji: "🧳",
    translations: {
      en: {
        question: "Which country's scientist first invented the flight data recorder in 1956?",
        correct: "Australia",
        distractors: ["United Kingdom", "United States", "France", "Germany", "Canada"],
        explanation: "David Warren built his prototype at the Aeronautical Research Laboratory in Melbourne.",
      },
      lt: {
        question: "Kurios šalies mokslininkas pirmasis išrado skrydžių duomenų registratorių 1956 m.?",
        correct: "Australijos",
        distractors: ["Jungtinės Karalystės", "Jungtinių Valstijų", "Prancūzijos", "Vokietijos", "Kanados"],
        explanation: "Davidas Warrenas sukūrė prototipą Melburno Aeronautikos tyrimų laboratorijoje.",
      },
    },
  },
  {
    id: "trn_av_022",
    category: "transport",
    subTheme: "aviation",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "LAX: original two-letter code LA padded with X when IATA moved to three-letter system — Simple Flying / RD.com",
    emoji: "🛫",
    translations: {
      en: {
        question: "What does the X in airport code LAX actually stand for?",
        correct: "Nothing — it was added as a filler",
        distractors: ["It stands for extra runway capacity", "Los Angeles International Xpress", "It marks an expansion terminal", "It denotes an executive-class hub", "Xavier Field, the original name"],
        explanation: "When IATA expanded codes from two to three letters, a plain X was added to the old LA code.",
      },
      lt: {
        question: "Ką iš tikrųjų reiškia raidė X oro uosto kode LAX?",
        correct: "Nieko — ji pridėta tik kaip užpildas",
        distractors: ["Ji žymi papildomų kilimo takų pajėgumą", "Los Angeles International Xpress", "Ji žymi plėtros terminalą", "Ji nurodo vadovų klasės mazgą", "Xavier Field — pradinis pavadinimas"],
        explanation: "Kai IATA praplėtė kodus nuo dviejų iki trijų raidžių, prie senojo LA kodo tiesiog pridėta X.",
      },
    },
  },
  {
    id: "trn_av_023",
    category: "transport",
    subTheme: "aviation",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Frank Whittle patented jet engine 1930, first flew 15 May 1941 in Gloster E.28/39 — Britannica / AOPA",
    emoji: "🛩️",
    translations: {
      en: {
        question: "Who patented the jet engine first and in which country?",
        correct: "Frank Whittle, UK",
        distractors: ["Hans von Ohain, Germany", "Igor Sikorsky, USA", "Ernst Heinkel, Germany", "Geoffrey de Havilland, UK", "Donald Douglas, USA"],
        explanation: "Whittle filed his patent in 1930; von Ohain independently developed his own engine in Germany.",
      },
      lt: {
        question: "Kas pirmasis patentavo reaktyvinį variklį ir kurioje šalyje?",
        correct: "Frank Whittle, JK",
        distractors: ["Hans von Ohain, Vokietija", "Igor Sikorsky, JAV", "Ernst Heinkel, Vokietija", "Geoffrey de Havilland, JK", "Donald Douglas, JAV"],
        explanation: "Whittle'as pateikė patentą 1930 m.; von Ohainas savarankiškai sukūrė savo variklį Vokietijoje.",
      },
    },
  },
  {
    id: "trn_av_024",
    category: "transport",
    subTheme: "aviation",
    level: "sunkus",
    isTrap: true,
    sourceVerified: "Spruce Goose is made mainly of birch via Duramold process, not spruce — Wikipedia Hughes H-4 / ASME",
    emoji: "🛩️",
    translations: {
      en: {
        question: "The Spruce Goose is famous as a wooden plane, but what wood was mainly used?",
        correct: "Birch",
        distractors: ["Spruce", "Oak", "Balsa", "Pine", "Walnut"],
        explanation: "Its nickname is misleading — the laminated Duramold wood used was predominantly birch.",
      },
      lt: {
        question: "Spruce Goose garsėja kaip medinis lėktuvas, bet iš kokios medienos jis daugiausia pagamintas?",
        correct: "Beržo",
        distractors: ["Eglės", "Ąžuolo", "Balsmedžio", "Pušies", "Graikinio riešuto"],
        explanation: "Slapyvardis klaidina — laminuotą Duramold medieną daugiausia sudarė beržas.",
      },
    },
  },
  {
    id: "trn_av_025",
    category: "transport",
    subTheme: "aviation",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Concorde fastest transatlantic crossing Feb 7 1996: NY to London in 2h 52min 59s — Simple Flying / Heritage Concorde",
    emoji: "✈️",
    translations: {
      en: {
        question: "Concorde set a record Atlantic crossing in 1996 — roughly how fast was it?",
        correct: "Under 3 hours",
        distractors: ["Under 1 hour", "Under 5 hours", "Under 7 hours", "About 4 hours", "About 8 hours"],
        explanation: "On 7 Feb 1996 it flew New York to London in 2 hours 52 minutes, a record still unbeaten.",
      },
      lt: {
        question: "Concorde 1996 m. rekordiškai perskrido Atlantą — maždaug kiek laiko tai truko?",
        correct: "Mažiau nei 3 valandas",
        distractors: ["Mažiau nei 1 valandą", "Mažiau nei 5 valandas", "Mažiau nei 7 valandas", "Apie 4 valandas", "Apie 8 valandas"],
        explanation: "1996 m. vasario 7 d. jis skrido iš Niujorko į Londoną per 2 valandas 52 minutes — rekordas iki šiol nepagerintas.",
      },
    },
  },
  {
    id: "trn_av_026",
    category: "transport",
    subTheme: "aviation",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Autopilot first publicly demonstrated by Lawrence Sperry on Jun 18 1914 on the Seine, Paris — migflug / Simple Flying",
    emoji: "🛩️",
    translations: {
      en: {
        question: "Who first publicly demonstrated autopilot on an aircraft in 1914?",
        correct: "Lawrence Sperry",
        distractors: ["Orville Wright", "Glenn Curtiss", "Louis Bleriot", "Alberto Santos-Dumont", "Roland Garros"],
        explanation: "He flew hands-free down the Seine with 100 000 Parisians watching in June 1914.",
      },
      lt: {
        question: "Kas 1914 m. pirmą kartą viešai demonstravo autopilotą lėktuve?",
        correct: "Lawrence Sperry",
        distractors: ["Orville Wright", "Glenn Curtiss", "Louis Bleriot", "Alberto Santos-Dumont", "Roland Garros"],
        explanation: "1914 m. birželį jis skrido nelaikydamas rankų ant vairo palei Seną, stebint 100 000 paryžiečių.",
      },
    },
  },
  {
    id: "trn_av_027",
    category: "transport",
    subTheme: "aviation",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Daocheng Yading Airport, China, highest commercial airport at 4 411 m (14 472 ft), opened 2013 — Guinness / Wikipedia",
    emoji: "🛫",
    translations: {
      en: {
        question: "Daocheng Yading, the world's highest commercial airport, is in which country?",
        correct: "China",
        distractors: ["Nepal", "Bolivia", "Peru", "Tibet (separate)", "India"],
        explanation: "Located at 4 411 metres in Sichuan province, it opened in September 2013.",
      },
      lt: {
        question: "Kurioje šalyje yra Daočengo Jadingo oro uostas, aukščiausias komercinis pasaulyje?",
        correct: "Kinijoje",
        distractors: ["Nepale", "Bolivijoje", "Peru", "Tibete (atskirai)", "Indijoje"],
        explanation: "Esantis 4 411 metrų aukštyje Sičuano provincijoje, jis atidarytas 2013 m. rugsėjį.",
      },
    },
  },
  {
    id: "trn_av_028",
    category: "transport",
    subTheme: "aviation",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Boeing 747 hump exists because nose cargo door required raised cockpit; military CXHLS origin — Smithsonian / We Are The Mighty",
    emoji: "✈️",
    translations: {
      en: {
        question: "Why does the Boeing 747 have its famous upper-deck hump?",
        correct: "To free the nose for a cargo door",
        distractors: ["For extra first-class seats only", "To reduce wind drag only", "For a radar dome", "To house extra fuel tanks", "To improve pilot visibility"],
        explanation: "The cockpit was raised so a hinged nose door could swing open for loading cargo.",
      },
      lt: {
        question: "Kodėl Boeing 747 turi garsiąjį viršutinio denio kuprą?",
        correct: "Kad priekyje tilptų krovininės durys",
        distractors: ["Tik papildomoms pirmos klasės vietoms", "Tik oro varžai sumažinti", "Radarų kupolui", "Papildomoms kuro cisternoms", "Piloto matomumui gerinti"],
        explanation: "Kokpitas buvo pakeltas, kad lankstomos priekinės durys galėtų atsidaryti kroviniams.",
      },
    },
  },
  {
    id: "trn_av_029",
    category: "transport",
    subTheme: "aviation",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "First human flight in hot air balloon Nov 21 1783 — Jean-Francois Pilatre de Rozier and Marquis d'Arlandes — Smithsonian",
    emoji: "🎈",
    translations: {
      en: {
        question: "In what year did the first humans fly in a hot air balloon?",
        correct: "1783",
        distractors: ["1776", "1800", "1815", "1850", "1770"],
        explanation: "Pilatre de Rozier and the Marquis d'Arlandes flew over Paris on 21 November 1783.",
      },
      lt: {
        question: "Kuriais metais pirmieji žmonės skrido oro balione?",
        correct: "1783",
        distractors: ["1776", "1800", "1815", "1850", "1770"],
        explanation: "Pilatras de Rozjė ir markizas d'Arlandas skrido virš Paryžiaus 1783 m. lapkričio 21 d.",
      },
    },
  },
  {
    id: "trn_av_030",
    category: "transport",
    subTheme: "aviation",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Aircraft wings generate lift via Bernoulli's principle (pressure differential) — FAA Boldmethod / Pilot Institute",
    emoji: "🛬",
    translations: {
      en: {
        question: "What physical principle explains why a wing's curved top creates lift?",
        correct: "Bernoulli's principle",
        distractors: ["Newton's first law", "Archimedes' principle", "Boyle's law", "Pascal's law", "Hooke's law"],
        explanation: "Lower pressure above the wing, plus air pushed downward, creates lift.",
      },
      lt: {
        question: "Koks fizikos dėsnis paaiškina, kodėl išlenkta sparno viršutinė pusė kuria kėlimo jėgą?",
        correct: "Bernulio principas",
        distractors: ["Niutono pirmasis dėsnis", "Archimedo principas", "Boilio dėsnis", "Paskalio dėsnis", "Huko dėsnis"],
        explanation: "Mažesnis slėgis virš sparno ir žemyn nukreipiamas oras kartu sukuria kėlimo jėgą.",
      },
    },
  },

  // ===================== EKSTREMALUS (srities žinovas) =====================
  {
    id: "trn_av_031",
    category: "transport",
    subTheme: "aviation",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "De Havilland Comet square windows caused fatigue cracks; redesigned with oval windows post-1954 — Smithsonian / IFLScience",
    emoji: "🛩️",
    translations: {
      en: {
        question: "Square windows on the early de Havilland Comet caused fatal crashes due to what?",
        correct: "Metal fatigue at corners",
        distractors: ["Bird strikes on glass", "Faulty rivet placement", "Incorrect glass thickness", "Vibration from engines", "Explosive decompression valves"],
        explanation: "Pressurisation cycles caused cracks to grow from the sharp window corners, leading to fuselage failure.",
      },
      lt: {
        question: "Dėl ko kvadratiniai ankstyvojo de Havilland Comet langai sukėlė mirtinas katastrofas?",
        correct: "Metalo nuovargio kampuose",
        distractors: ["Paukščių smūgių į stiklą", "Klaidingo kniedžių išdėstymo", "Netinkamo stiklo storio", "Variklių vibracijos", "Sprogių dekompresijos vožtuvų"],
        explanation: "Slėgio ciklai skatino plyšių plitimą nuo aštrių langų kampų, todėl suirdavo lėktuvo korpusas.",
      },
    },
  },
  {
    id: "trn_av_032",
    category: "transport",
    subTheme: "aviation",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Airbus A380 first full-length double-deck airliner; entered service Oct 25 2007 with Singapore Airlines — Airbus official",
    emoji: "✈️",
    translations: {
      en: {
        question: "Which airliner was the first to offer a full-length double passenger deck?",
        correct: "Airbus A380",
        distractors: ["Boeing 747", "Boeing 777X", "Douglas DC-10", "Lockheed L-1011", "Tupolev Tu-144"],
        explanation: "The A380, in service from 2007, has two continuous passenger decks running the full fuselage length.",
      },
      lt: {
        question: "Kuris laineris pirmasis pasiūlė per visą ilgį dviaukštį keleivių saloną?",
        correct: "Airbus A380",
        distractors: ["Boeing 747", "Boeing 777X", "Douglas DC-10", "Lockheed L-1011", "Tupolev Tu-144"],
        explanation: "A380, naudojamas nuo 2007 m., turi du ištisinius keleivių denius per visą korpuso ilgį.",
      },
    },
  },
  {
    id: "trn_av_033",
    category: "transport",
    subTheme: "aviation",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Cabin pressurised to 8 000 ft not sea level to reduce structural stress and fuselage weight — SKYbrary / Migflug",
    emoji: "🛬",
    translations: {
      en: {
        question: "Commercial jets pressurise to 8 000 ft equivalent, not sea level — why not sea level?",
        correct: "The fuselage would need to be far heavier",
        distractors: ["Passengers prefer the thin high-altitude air", "Aviation rules forbid sea level", "Jet engines cannot manage it", "The windows cannot hold sea level", "Oxygen masks would not fit well"],
        explanation: "A lower pressure differential means thinner, lighter fuselage skin, saving enormous weight.",
      },
      lt: {
        question: "Laineriuose palaikomas 8 000 pėdų aukščio slėgis, o ne jūros lygio — kodėl ne jūros lygio?",
        correct: "Korpusas turėtų būti daug sunkesnis",
        distractors: ["Keleiviai mieliau kvėpuoja retu oru", "Aviacijos taisyklės draudžia jūros lygį", "Reaktyviniai varikliai to nepajėgtų", "Langai neatlaikytų jūros lygio slėgio", "Deguonies kaukės gerai netiktų"],
        explanation: "Mažesnis slėgio skirtumas leidžia korpuso apvalkalą daryti plonesnį ir lengvesnį — sutaupoma daug svorio.",
      },
    },
  },
  {
    id: "trn_av_034",
    category: "transport",
    subTheme: "aviation",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Raymonde de Laroche received world's first female pilot licence Mar 8 1910 from Aeroclub de France — AeroTime / VinAviNews",
    emoji: "🛩️",
    translations: {
      en: {
        question: "Who received the world's first official pilot licence issued to a woman, in 1910?",
        correct: "Raymonde de Laroche",
        distractors: ["Harriet Quimby", "Amelia Earhart", "Bessie Coleman", "Marie Marvingt", "Ruth Law"],
        explanation: "The French actress earned licence No. 36 from the Aeroclub de France on 8 March 1910.",
      },
      lt: {
        question: "Kas 1910 m. gavo pirmąjį oficialų piloto pažymėjimą, išduotą moteriai?",
        correct: "Raymonde de Laroche",
        distractors: ["Harriet Quimby", "Amelia Earhart", "Bessie Coleman", "Marie Marvingt", "Ruth Law"],
        explanation: "Prancūzų aktorė gavo pažymėjimą Nr. 36 iš Aeroclub de France 1910 m. kovo 8 d.",
      },
    },
  },
  {
    id: "trn_av_035",
    category: "transport",
    subTheme: "aviation",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Concorde sonic boom prevented overland supersonic flight, limited to ocean routes — Britannica / PBS NOVA",
    emoji: "✈️",
    translations: {
      en: {
        question: "Why was Concorde not allowed to fly supersonically over most land areas?",
        correct: "Its sonic boom disturbed people below",
        distractors: ["Its engines overheated inland", "Land radar could not track it", "Overland air is too turbulent", "It needed ocean spray for cooling", "Landing gear failed over land"],
        explanation: "The shock wave created a loud boom on the ground, so supersonic flight was restricted to oceans.",
      },
      lt: {
        question: "Kodėl Concorde nebuvo leidžiama viršgarsiniu greičiu skristi virš daugumos sausumos plotų?",
        correct: "Jo garso bumas trikdė žmones apačioje",
        distractors: ["Jo varikliai peršildavo virš sausumos", "Sausumos radarai negalėjo jo sekti", "Virš sausumos oras per daug turbulentingas", "Jam aušinti reikėjo jūros purslų", "Važiuoklė strigdavo virš sausumos"],
        explanation: "Smūginė banga sukeldavo garsų bumą žemėje, todėl viršgarsiniai skrydžiai buvo apriboti vien vandenynais.",
      },
    },
  },
  {
    id: "trn_av_036",
    category: "transport",
    subTheme: "aviation",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Wright Flyer made of spruce and ash wood frame covered with muslin fabric, total weight 274 kg empty — NASM Smithsonian",
    emoji: "🛩️",
    translations: {
      en: {
        question: "The 1903 Wright Flyer airframe was made from wood and which fabric?",
        correct: "Muslin",
        distractors: ["Canvas", "Silk", "Linen", "Cotton duck", "Nylon"],
        explanation: "A spruce and ash wooden frame was covered with unbleached muslin to form the wings.",
      },
      lt: {
        question: "1903 m. Wright Flyer korpusas buvo pagamintas iš medienos ir kurio audinio?",
        correct: "Muslino",
        distractors: ["Drobės", "Šilko", "Linų", "Storintos medvilnės", "Nailono"],
        explanation: "Eglės ir uosio medinis rėmas sparnams sudaryti buvo aptrauktas nebalintu muslinu.",
      },
    },
  },
  {
    id: "trn_av_037",
    category: "transport",
    subTheme: "aviation",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "LHR stands for London Heath Row (historical village demolished for airport) — Heathrow/Wikipedia / Oreate AI",
    emoji: "🛫",
    translations: {
      en: {
        question: "Airport code LHR refers to Heathrow — what does the HR stand for?",
        correct: "Heath Row (the old village)",
        distractors: ["Heathrow Runway abbreviation", "High-capacity Route marker", "Hillingdon Regional airfield", "Her Royal designation prefix", "Historic Runway site code"],
        explanation: "The village of Heath Row was demolished in 1944 to build the airport; its name lives on in the code.",
      },
      lt: {
        question: "Oro uosto kodas LHR reiškia Heathrow — ką reiškia jo raidės HR?",
        correct: "Heath Row (senasis kaimas)",
        distractors: ["Heathrow kilimo tako santrumpa", "Didelio pajėgumo maršruto žyma", "Hillingdon regioninis aerodromas", "Her Royal priešdėlio žyma", "Istorinio kilimo tako kodas"],
        explanation: "Heath Row kaimas 1944 m. buvo nugriautas oro uostui statyti; jo vardas išliko kode.",
      },
    },
  },
  {
    id: "trn_av_038",
    category: "transport",
    subTheme: "aviation",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Spruce Goose H-4 wingspan 97.8 m (321 ft), longer than a football field — ASME / New Atlas",
    emoji: "🛩️",
    translations: {
      en: {
        question: "The Hughes H-4 Hercules had a wingspan of roughly how many metres?",
        correct: "About 98 metres",
        distractors: ["About 40 metres", "About 60 metres", "About 70 metres", "About 120 metres", "About 200 metres"],
        explanation: "Its 97.8-metre wingspan exceeded a standard football field in length.",
      },
      lt: {
        question: "Maždaug kokio metrų sparnų mosto buvo Hughes H-4 Hercules?",
        correct: "Apie 98 metrus",
        distractors: ["Apie 40 metrų", "Apie 60 metrų", "Apie 70 metrų", "Apie 120 metrų", "Apie 200 metrų"],
        explanation: "Jo 97,8 metro sparnų mostas viršijo standartinio futbolo lauko ilgį.",
      },
    },
  },
  {
    id: "trn_av_039",
    category: "transport",
    subTheme: "aviation",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Commercial jets cruise at 35 000–42 000 ft for fuel efficiency; thinner air = less drag — FAA / Explore.com",
    emoji: "🛬",
    translations: {
      en: {
        question: "Commercial jets cruise around 35 000 feet mainly for which reason?",
        correct: "Thinner air means far less drag",
        distractors: ["Regulations strictly forbid lower cruise", "Pilots stay more alert at that height", "Radio signals travel much further up", "Fuel lines freeze at lower altitude", "Passengers strongly prefer the view"],
        explanation: "Reduced air density dramatically cuts drag, letting engines burn far less fuel per kilometre.",
      },
      lt: {
        question: "Dėl ko komerciniai reaktyviniai laineriai skrenda maždaug 35 000 pėdų aukštyje?",
        correct: "Retesnis oras sukelia kur kas mažesnę varžą",
        distractors: ["Taisyklės griežtai draudžia skristi žemiau", "Pilotai tame aukštyje labiau budrūs", "Radijo signalai sklinda kur kas toliau", "Kuro vamzdžiai užšąla žemesniame aukštyje", "Keleiviai labai mėgsta tokio aukščio vaizdą"],
        explanation: "Mažesnis oro tankis smarkiai mažina varžą, todėl varikliai sunaudoja kur kas mažiau kuro kilometrui.",
      },
    },
  },
  {
    id: "trn_av_040",
    category: "transport",
    subTheme: "aviation",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Hughes loathed the nickname Spruce Goose; birch rhyme explanation — Wikipedia H-4 / WeAreTheMighty",
    emoji: "🛩️",
    translations: {
      en: {
        question: "Howard Hughes hated the Spruce Goose nickname — according to lore, why did critics use spruce and not birch?",
        correct: "Nothing rhymes well with birch",
        distractors: ["Spruce was listed in blueprints", "Birch sounds too beautiful", "Hughes owned spruce forests", "Birch was a military secret", "Spruce sounded more dramatic"],
        explanation: "A worker explained the name stuck because nobody could think of a word that rhymed with birch.",
      },
      lt: {
        question: "Hjugas nekentė pravardės Spruce Goose — pasak legendos, kodėl kritikai rinkosi eglę, o ne beržą?",
        correct: "Niekas gerai nesirimuoja su beržu",
        distractors: ["Eglė buvo nurodyta brėžiniuose", "Beržas skamba per gražiai", "Hjugas valdė eglynus", "Beržas buvo karinė paslaptis", "Eglė skambėjo dramatiškiau"],
        explanation: "Darbininkas paaiškino, kad pravardė prigijo, nes niekas nesugalvojo žodžio, kuris rimuotųsi su beržu.",
      },
    },
  },
];
