/**
 * transportTrains — 🚂 „Traukiniai ir metro" potemė (tema „Transportas").
 *
 * MAŽAS FAILAS pagal potemę. 40 klausimų (10/lygiui). Traukinių istorija,
 * rekordai, technologijos, linijos ir žymios stotys.
 * Tik patikrinti faktai — jokių mitų kaip tikrų faktų.
 *
 * TAISYKLĖS: 1 teisingas + 5 distraktoriai; ≤46 simb.; teisingas NE ilgiausias >+5;
 * LT be vidinių kabučių; jokio atsakymo klausime; EMOJI NEUTRALUS (neišduoda atsakymo).
 */

import { TriviaQuestion } from "./triviaTypes";

export const TRANSPORT_TRAINS: TriviaQuestion[] = [
  // ===================== LENGVAS (9–12 m. vaikas) =====================
  {
    id: "trn_tr_001",
    category: "transport",
    subTheme: "trains",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Stephenson's Rocket won Rainhill Trials 1829 — Science and Industry Museum, Manchester",
    emoji: "🚂",
    translations: {
      en: {
        question: "The famous early locomotive Rocket was built by which family?",
        correct: "The Stephensons",
        distractors: ["The Watts", "The Brunels", "The Edisons", "The Trevithicks", "The Darwins"],
        explanation: "George and Robert Stephenson built Rocket, which won the 1829 Rainhill Trials.",
      },
      lt: {
        question: "Kuriai šeimai priklausė garsus ankstyvasis garvežys Rocket?",
        correct: "Stephensonams",
        distractors: ["Wattams", "Brunelams", "Edisonams", "Trevithickams", "Darwinams"],
        explanation: "Džordžas ir Robertas Stephensonai pastatė Rocket, laimėjusį 1829 m. Rainhill bandymus.",
      },
    },
  },
  {
    id: "trn_tr_002",
    category: "transport",
    subTheme: "trains",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "London Underground opened 9 Jan 1863 — London Transport Museum / Guinness World Records",
    emoji: "🚇",
    translations: {
      en: {
        question: "Which city has the oldest underground metro in the world?",
        correct: "London",
        distractors: ["Paris", "New York", "Berlin", "Tokyo", "Vienna"],
        explanation: "London's Underground opened in January 1863, the first metro system ever built.",
      },
      lt: {
        question: "Kuriame mieste yra seniausias pasaulyje požeminis metro?",
        correct: "Londonas",
        distractors: ["Paryžius", "Niujorkas", "Berlynas", "Tokijas", "Viena"],
        explanation: "Londono metro atidarytas 1863 m. sausį — pirmoji metro sistema pasaulyje.",
      },
    },
  },
  {
    id: "trn_tr_003",
    category: "transport",
    subTheme: "trains",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Japan Shinkansen opened 1 Oct 1964 before Tokyo Olympics — Japan House London",
    emoji: "🚄",
    translations: {
      en: {
        question: "Japan's famous bullet train is known by which name?",
        correct: "Shinkansen",
        distractors: ["Nozomi", "Hikari", "Komachi", "Sakura", "Hayabusa"],
        explanation: "Shinkansen means 'new main line'; the service launched in 1964 before the Tokyo Olympics.",
      },
      lt: {
        question: "Kuo vadinamas garsusis Japonijos greitasis traukinys?",
        correct: "Shinkansen",
        distractors: ["Nozomi", "Hikari", "Komachi", "Sakura", "Hayabusa"],
        explanation: "Shinkansen reiškia naują pagrindinę liniją; eismas pradėtas 1964 m. prieš Tokijo olimpiadą.",
      },
    },
  },
  {
    id: "trn_tr_004",
    category: "transport",
    subTheme: "trains",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Trans-Siberian Railway Moscow–Vladivostok 9,289 km — Britannica",
    emoji: "🛤️",
    translations: {
      en: {
        question: "The Trans-Siberian Railway runs from Moscow all the way to which city?",
        correct: "Vladivostok",
        distractors: ["Beijing", "Ulaanbaatar", "Novosibirsk", "Irkutsk", "Yekaterinburg"],
        explanation: "At 9,289 km, the Moscow–Vladivostok route is the world's longest railway line.",
      },
      lt: {
        question: "Transsibirinė geležinkelio linija eina nuo Maskvos iki kurio miesto?",
        correct: "Vladivostoko",
        distractors: ["Pekino", "Ulan Batoro", "Novosibirsko", "Irkutsko", "Jekaterinburgo"],
        explanation: "9 289 km Maskva–Vladivostokas yra ilgiausia geležinkelio linija pasaulyje.",
      },
    },
  },
  {
    id: "trn_tr_005",
    category: "transport",
    subTheme: "trains",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Channel Tunnel opened 6 May 1994, connects UK and France — Britannica / History.com",
    emoji: "🎫",
    translations: {
      en: {
        question: "The Channel Tunnel links England to which neighbouring country?",
        correct: "France",
        distractors: ["Belgium", "Netherlands", "Spain", "Ireland", "Germany"],
        explanation: "Opened in 1994, the Chunnel runs between Folkestone and Calais under the sea.",
      },
      lt: {
        question: "Lamanšo tunelis jungia Angliją su kuria kaimynine šalimi?",
        correct: "Prancūzija",
        distractors: ["Belgija", "Nyderlandai", "Ispanija", "Airija", "Vokietija"],
        explanation: "Atidarytas 1994 m., tunelis driekiasi tarp Folkestono ir Kalė po jūra.",
      },
    },
  },
  {
    id: "trn_tr_006",
    category: "transport",
    subTheme: "trains",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Maglev trains levitate using magnets, no wheel-rail contact — US Dept of Energy",
    emoji: "🚉",
    translations: {
      en: {
        question: "A maglev train floats above the track using what force?",
        correct: "Magnetism",
        distractors: ["Air pressure", "Electricity", "Gravity", "Steam", "Hydraulics"],
        explanation: "Maglev stands for magnetic levitation — powerful magnets lift the train off the track.",
      },
      lt: {
        question: "Kokią jėgą naudoja virš bėgių sklendžiantis maglev traukinys?",
        correct: "Magnetizmą",
        distractors: ["Oro slėgį", "Elektrą", "Gravitaciją", "Garą", "Hidrauliką"],
        explanation: "Maglev reiškia magnetinę levitaciją — galingi magnetai pakelia traukinį nuo bėgių.",
      },
    },
  },
  {
    id: "trn_tr_007",
    category: "transport",
    subTheme: "trains",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "London Underground nicknamed 'the Tube' — London Transport Museum",
    emoji: "🚇",
    translations: {
      en: {
        question: "What nickname is London's underground railway system known by?",
        correct: "The Tube",
        distractors: ["The Pipe", "The Burrow", "The Tunnel", "The Shaft", "The Loop"],
        explanation: "Londoners call their metro 'the Tube' because of the circular tunnel cross-section.",
      },
      lt: {
        question: "Kokia pravarde vadinamas Londono požeminis geležinkelis?",
        correct: "The Tube",
        distractors: ["The Pipe", "The Burrow", "The Tunnel", "The Shaft", "The Loop"],
        explanation: "Londoniečiai savo metro vadina The Tube dėl apvalaus tunelio skerspjūvio.",
      },
    },
  },
  {
    id: "trn_tr_008",
    category: "transport",
    subTheme: "trains",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Steam locomotive burns fuel to boil water and make steam — How Steam Engines Work, HowStuffWorks",
    emoji: "🚂",
    translations: {
      en: {
        question: "A steam locomotive moves by burning fuel to produce what substance?",
        correct: "Steam",
        distractors: ["Smoke", "Gas", "Hot water", "Electricity", "Oil"],
        explanation: "Burning coal heats water in the boiler; the expanding steam pushes pistons that turn the wheels.",
      },
      lt: {
        question: "Kokią medžiagą degindamas kurą gamina garvežys, kad galėtų judėti?",
        correct: "Garą",
        distractors: ["Dūmus", "Dujas", "Karštą vandenį", "Elektrą", "Naftą"],
        explanation: "Degančios akmens anglys įkaitina katilo vandenį; besiplečiantis garas stumia stūmoklius, kurie suka ratus.",
      },
    },
  },
  {
    id: "trn_tr_009",
    category: "transport",
    subTheme: "trains",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Grand Central Terminal opened Feb 2, 1913, 44 platforms — Guinness World Records",
    emoji: "🚉",
    translations: {
      en: {
        question: "Grand Central Terminal, the world's largest station by platforms, is in which city?",
        correct: "New York",
        distractors: ["Chicago", "London", "Paris", "Tokyo", "Los Angeles"],
        explanation: "Grand Central in Manhattan has 44 platforms and 67 tracks, opened in 1913.",
      },
      lt: {
        question: "Kuriame mieste yra Grand Central — didžiausia pasaulyje stotis pagal peronų skaičių?",
        correct: "Niujorke",
        distractors: ["Čikagoje", "Londone", "Paryžiuje", "Tokijuje", "Los Andžele"],
        explanation: "Manhateno Grand Central, atidaryta 1913 m., turi 44 peronus ir 67 kelius.",
      },
    },
  },
  {
    id: "trn_tr_010",
    category: "transport",
    subTheme: "trains",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "TGV is France's high-speed train, TGV = Train à Grande Vitesse — Britannica",
    emoji: "🚄",
    translations: {
      en: {
        question: "The letters TGV stand for the name of which country's high-speed train?",
        correct: "France",
        distractors: ["Germany", "Spain", "Italy", "Belgium", "Switzerland"],
        explanation: "TGV means Train à Grande Vitesse — French for high-speed train, in service since 1981.",
      },
      lt: {
        question: "Santrumpa TGV žymi kurios šalies greitaeigį traukinį?",
        correct: "Prancūzijos",
        distractors: ["Vokietijos", "Ispanijos", "Italijos", "Belgijos", "Šveicarijos"],
        explanation: "TGV — Train à Grande Vitesse, prancūziškai greitaeigis traukinys, veikia nuo 1981 m.",
      },
    },
  },

  // ===================== VIDUTINIS (12–18 m. paauglys) =====================
  {
    id: "trn_tr_011",
    category: "transport",
    subTheme: "trains",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Rainhill Trials 1829: Rocket averaged 12 mph, peaked 30 mph — Science and Industry Museum",
    emoji: "🚂",
    translations: {
      en: {
        question: "The Rainhill Trials of 1829 chose the best locomotive for which new railway?",
        correct: "Liverpool and Manchester",
        distractors: ["London and Birmingham", "Great Western", "Midland", "North Eastern", "Caledonian"],
        explanation: "Rocket won the Trials and was chosen to power the world's first inter-city passenger railway.",
      },
      lt: {
        question: "Kurio naujo geležinkelio geriausias garvežys buvo renkamas 1829 m. Rainhill bandymais?",
        correct: "Liverpulio ir Mančesterio",
        distractors: ["Londono ir Birmingemo", "Didžiojo Vakarų", "Midland", "Šiaurės Rytų", "Kaledonijos"],
        explanation: "Rocket laimėjo ir tapo pirmosios pasaulyje tarpmiestinės keleivių linijos varikliu.",
      },
    },
  },
  {
    id: "trn_tr_012",
    category: "transport",
    subTheme: "trains",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Trans-Siberian crosses 8 time zones Moscow–Vladivostok — Britannica / multiple travel sources",
    emoji: "🛤️",
    translations: {
      en: {
        question: "Travelling the whole Trans-Siberian Railway from Moscow, how many time zones do you cross?",
        correct: "Eight",
        distractors: ["Four", "Six", "Ten", "Three", "Five"],
        explanation: "The full Moscow–Vladivostok journey spans eight time zones and takes about seven days.",
      },
      lt: {
        question: "Keliaujant visu Transsibiro geležinkeliu nuo Maskvos, kiek laiko juostų kertate?",
        correct: "Aštuonias",
        distractors: ["Keturias", "Šešias", "Dešimt", "Tris", "Penkias"],
        explanation: "Visa Maskvos–Vladivostoko kelionė apima aštuonias laiko juostas ir trunka apie septynias dienas.",
      },
    },
  },
  {
    id: "trn_tr_013",
    category: "transport",
    subTheme: "trains",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Channel Tunnel is 50.45 km total, 37.9 km undersea — Eurotunnel / Britannica",
    emoji: "🎫",
    translations: {
      en: {
        question: "How many separate tunnels make up the Channel Tunnel structure?",
        correct: "Three",
        distractors: ["One", "Two", "Four", "Five", "Six"],
        explanation: "Two rail tunnels carry trains in each direction; a smaller service tunnel runs between them.",
      },
      lt: {
        question: "Iš kiek atskirų tunelių sudarytas Lamanšo tunelių kompleksas?",
        correct: "Trijų",
        distractors: ["Vieno", "Dviejų", "Keturių", "Penkių", "Šešių"],
        explanation: "Dviem geležinkelio tuneliais traukiniai važiuoja į abi puses; tarp jų driekiasi mažesnis aptarnavimo tunelis.",
      },
    },
  },
  {
    id: "trn_tr_014",
    category: "transport",
    subTheme: "trains",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Standard rail gauge 4 ft 8.5 in (1435 mm) from Stephenson practice — Britannica / ICE",
    emoji: "🛤️",
    translations: {
      en: {
        question: "What is the name for the 1,435 mm track width used on most of the world's railways?",
        correct: "Standard gauge",
        distractors: ["Broad gauge", "Cape gauge", "Narrow gauge", "Imperial gauge", "Metric gauge"],
        explanation: "1,435 mm became standard from early British railways built to George Stephenson's practice.",
      },
      lt: {
        question: "Kaip vadinamas 1 435 mm bėgių plotis, naudojamas daugumoje pasaulio geležinkelių?",
        correct: "Standartinis vėžys",
        distractors: ["Platusis vėžys", "Keipo vėžys", "Siaurasis vėžys", "Imperinis vėžys", "Metrinis vėžys"],
        explanation: "1 435 mm tapo standartu nuo ankstyvų britų geležinkelių, statytų pagal Džordžo Stephensono praktiką.",
      },
    },
  },
  {
    id: "trn_tr_015",
    category: "transport",
    subTheme: "trains",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "TGV speed record 574.8 km/h on 3 April 2007, LGV Est — Wikipedia / Al Jazeera",
    emoji: "🚄",
    translations: {
      en: {
        question: "Which country's train holds the all-time wheel-on-rail speed record at 574.8 km/h?",
        correct: "France",
        distractors: ["Japan", "Germany", "China", "Italy", "Spain"],
        explanation: "A specially modified French TGV set the record on 3 April 2007 on the LGV Est line.",
      },
      lt: {
        question: "Kurios šalies traukinys laiko visų laikų bėginio greičio rekordą — 574,8 km/h?",
        correct: "Prancūzija",
        distractors: ["Japonija", "Vokietija", "Kinija", "Italija", "Ispanija"],
        explanation: "Specialiai paruoštas prancūzų TGV pasiekė šį rekordą 2007 m. balandžio 3 d. LGV Est linijoje.",
      },
    },
  },
  {
    id: "trn_tr_016",
    category: "transport",
    subTheme: "trains",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Shinkansen opened Oct 1 1964, Tokyo–Osaka in ~4 hours — Japan House London",
    emoji: "🚄",
    translations: {
      en: {
        question: "Japan's first Shinkansen line linked Tokyo to which other major city in 1964?",
        correct: "Osaka",
        distractors: ["Kyoto", "Nagoya", "Hiroshima", "Fukuoka", "Sapporo"],
        explanation: "The Tokaido Shinkansen cut the Tokyo–Osaka journey from about six and a half hours to about four.",
      },
      lt: {
        question: "Pirmoji Japonijos Shinkansen linija 1964 m. sujungė Tokiją su kuriuo kitu dideliu miestu?",
        correct: "Osaka",
        distractors: ["Kjoto", "Nagoja", "Hirošima", "Fukuoka", "Saporo"],
        explanation: "Tokaido Shinkansen sutrumpino Tokijo–Osakos kelionę nuo maždaug šešių su puse valandos iki maždaug keturių.",
      },
    },
  },
  {
    id: "trn_tr_017",
    category: "transport",
    subTheme: "trains",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Orient Express 1883 inaugural reached Giurgiu (ferry+steamer onward); first direct all-rail Paris–Constantinople 1889 — Wikipedia",
    emoji: "🎫",
    translations: {
      en: {
        question: "In 1889 the Orient Express began the first direct all-rail run from Paris to which city?",
        correct: "Istanbul",
        distractors: ["Munich", "Budapest", "Athens", "Belgrade", "Bucharest"],
        explanation: "The 1883 run reached only Giurgiu in Romania; passengers crossed the Danube by ferry; the full rail route opened in 1889.",
      },
      lt: {
        question: "1889 m. Orient Express pradėjo pirmą tiesioginį geležinkelio reisą iš Paryžiaus į kurį miestą?",
        correct: "Stambulą",
        distractors: ["Miuncheną", "Budapeštą", "Atėnus", "Belgradą", "Bukareštą"],
        explanation: "1883 m. reisas pasiekė tik Giurgiu Rumunijoje; keleiviai keltu kirto Dunojų; visas geležinkelio kelias atidarytas 1889 m.",
      },
    },
  },
  {
    id: "trn_tr_018",
    category: "transport",
    subTheme: "trains",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Funicular: two cars on cable counterbalance each other — HowStuffWorks / Cape Point",
    emoji: "🚉",
    translations: {
      en: {
        question: "In a funicular railway, how do the two cars use each other to save energy?",
        correct: "They counterbalance",
        distractors: ["They share a motor", "They push each other", "They run on batteries", "They use solar panels", "They ride on air"],
        explanation: "The descending car's weight pulls the ascending one up via a shared cable and pulley.",
      },
      lt: {
        question: "Kaip funikulieriaus du vagonai padeda vienas kitam taupyti energiją?",
        correct: "Atsveria vienas kitą",
        distractors: ["Dalijasi varikliu", "Stumia vienas kitą", "Veikia baterijomis", "Naudoja saulės baterijas", "Lekia ore"],
        explanation: "Žemyn leidžiantis vagonas savo svoriu per bendrą lyną ir skriemulį traukia kylantįjį aukštyn.",
      },
    },
  },
  {
    id: "trn_tr_019",
    category: "transport",
    subTheme: "trains",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Liverpool and Manchester Railway opened Sep 15, 1830 — Britannica / Science and Industry Museum",
    emoji: "🚂",
    translations: {
      en: {
        question: "The Liverpool and Manchester Railway of 1830 was a world first for what reason?",
        correct: "First steam inter-city passenger line",
        distractors: ["First underground tunnel railway", "First fully electric railway", "First railway suspension bridge", "First commercial monorail", "First high-speed express line"],
        explanation: "It was the world's first railway to run scheduled steam-powered passenger services between cities.",
      },
      lt: {
        question: "Kuo 1830 m. Liverpulio ir Mančesterio geležinkelis tapo pirmasis pasaulyje?",
        correct: "Garinė tarpmiestinė keleivių linija",
        distractors: ["Požeminė tunelio linija", "Visiškai elektrinis geležinkelis", "Geležinkelio pakabinamas tiltas", "Komercinis monorelsas", "Greitaeigė ekspreso linija"],
        explanation: "Tai buvo pirmasis pasaulyje garinis geležinkelis, reguliariai vežęs keleivius tarp miestų.",
      },
    },
  },
  {
    id: "trn_tr_020",
    category: "transport",
    subTheme: "trains",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "George Pullman built Palace Car 1864, founded Pullman Palace Car Company 1867 — Smithsonian",
    emoji: "🛤️",
    translations: {
      en: {
        question: "George Pullman became famous in the 1860s for inventing a luxurious type of what?",
        correct: "Sleeping car",
        distractors: ["Dining car", "Steam locomotive", "Signal system", "Steel rail", "Ticket machine"],
        explanation: "His Pullman Palace Cars made overnight rail travel comfortable for the first time.",
      },
      lt: {
        question: "Kokio tipo prabangų vagoną išradęs Džordžas Pullmanas išgarsėjo 1860-aisiais?",
        correct: "Miegamąjį vagoną",
        distractors: ["Vagoną restoraną", "Garo garvežį", "Signalų sistemą", "Plieninį bėgį", "Bilietų automatą"],
        explanation: "Jo Pullman Palace Cars pirmą kartą pavertė naktines keliones traukiniu patogiomis.",
      },
    },
  },

  // ===================== SUNKUS (suaugęs, kuris domisi) =====================
  {
    id: "trn_tr_021",
    category: "transport",
    subTheme: "trains",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Werner von Siemens demonstrated first electric railway at Berlin Trades Exhibition, 31 May 1879 — Siemens AG / Guinness",
    emoji: "🚉",
    translations: {
      en: {
        question: "Who demonstrated the world's first electric passenger railway in Berlin in 1879?",
        correct: "Werner von Siemens",
        distractors: ["Thomas Edison", "Nikola Tesla", "Robert Stephenson", "Isambard Brunel", "James Watt"],
        explanation: "At the Berlin Trades Exhibition, Siemens ran a 300-metre electric oval carrying 86,000 visitors.",
      },
      lt: {
        question: "Kas 1879 m. Berlyne demonstravo pirmą pasaulyje elektrinį keleivių geležinkelį?",
        correct: "Werneris von Siemens",
        distractors: ["Thomasas Edisonas", "Nikola Tesla", "Robertas Stephensonas", "Isambardas Brunelis", "Jamesas Wattas"],
        explanation: "Berlyno pramonės parodoje Siemensas 300 m ilgio elektriniu žiedu pavežiojo 86 000 lankytojų.",
      },
    },
  },
  {
    id: "trn_tr_022",
    category: "transport",
    subTheme: "trains",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Shanghai Maglev top commercial speed 431 km/h Pudong Airport line, opened 2004 — Wikipedia / Guinness",
    emoji: "🚄",
    translations: {
      en: {
        question: "Which city runs the world's fastest commercial maglev, rated at up to 431 km/h?",
        correct: "Shanghai",
        distractors: ["Tokyo", "Seoul", "Beijing", "Osaka", "Guangzhou"],
        explanation: "The Shanghai Transrapid links the city to Pudong Airport and covers 30 km in about 8 minutes.",
      },
      lt: {
        question: "Kuriame mieste veikia greičiausias komercinis maglev pasaulyje, kurio projektinis greitis iki 431 km/h?",
        correct: "Šanchajuje",
        distractors: ["Tokijuje", "Seule", "Pekine", "Osakoje", "Guangžou"],
        explanation: "Šanchajaus Transrapid jungia miestą su Pudongo oro uostu ir nuvažiuoja 30 km per maždaug 8 minutes.",
      },
    },
  },
  {
    id: "trn_tr_023",
    category: "transport",
    subTheme: "trains",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Rack railway: cog engages centre rack rail for steep climbs — Wikipedia / Gaugemaster",
    emoji: "🛤️",
    translations: {
      en: {
        question: "A cog (rack) railway climbs steep hills by gripping what extra feature on the track?",
        correct: "A centre rack rail",
        distractors: ["A third power rail", "A rubber guide strip", "Overhead wires", "A braking cable", "Steel teeth on sleepers"],
        explanation: "A toothed pinion on the train meshes with the rack rail, preventing slipping on steep slopes.",
      },
      lt: {
        question: "Į kokią papildomą bėgio dalį kabindamasis krumpliastiebis geležinkelis įveikia stačius šlaitus?",
        correct: "Centrinį krumpliastiebį",
        distractors: ["Trečią srovės bėgį", "Guminę kreipiamąją juostą", "Viršutinius laidus", "Stabdymo kabelį", "Plieninius dantis ant pabėgių"],
        explanation: "Ant traukinio esantis dantratis kimba į krumpliastiebį ir neleidžia slysti stačiuose šlaituose.",
      },
    },
  },
  {
    id: "trn_tr_024",
    category: "transport",
    subTheme: "trains",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Grand Central Terminal has 44 platforms — Guinness World Records; opened Feb 2, 1913",
    emoji: "🚉",
    translations: {
      en: {
        question: "Grand Central Terminal holds the record for most platforms in one station. How many are there?",
        correct: "44",
        distractors: ["28", "36", "52", "67", "100"],
        explanation: "The 44 platforms are spread across two underground levels, served by 67 tracks in total.",
      },
      lt: {
        question: "Grand Central Terminal turi daugiausiai peronų iš visų pasaulio stočių. Kiek jų ten yra?",
        correct: "44",
        distractors: ["28", "36", "52", "67", "100"],
        explanation: "44 peronai išsidėstę dviejuose požeminiuose aukštuose, o juos aptarnauja iš viso 67 keliai.",
      },
    },
  },
  {
    id: "trn_tr_025",
    category: "transport",
    subTheme: "trains",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Track switch (points): pair of tapered rails moved to divert trains — Aldon / trainspottr.com",
    emoji: "🛤️",
    translations: {
      en: {
        question: "The movable tapered rails that divert a train from one track to another are called what?",
        correct: "Points (switch rails)",
        distractors: ["Timber sleepers", "Steel fishplates", "Check rails", "Guard rails", "Diamond crossing frogs"],
        explanation: "When the points move, a gap opens beside one running rail, steering the wheels onto the new track.",
      },
      lt: {
        question: "Kaip vadinamos judančios smailėjančios bėgių dalys, nukreipiančios traukinį iš vieno kelio į kitą?",
        correct: "Iešmas",
        distractors: ["Mediniai pabėgiai", "Plieninės sandūrinės tvarslės", "Kontrbėgiai", "Apsauginiai bėgiai", "Kryžmės širdys"],
        explanation: "Pajudinus iešmą, prie einamojo bėgio atsiveria tarpas ir ratai nukrypsta į naują kelią.",
      },
    },
  },
  {
    id: "trn_tr_026",
    category: "transport",
    subTheme: "trains",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Shinkansen average annual delay under 1 minute for decades — JR Central / JRailPass",
    emoji: "🚄",
    translations: {
      en: {
        question: "Japan's Shinkansen is famous for punctuality: what is the approximate average annual delay?",
        correct: "Under one minute",
        distractors: ["About five minutes", "Under ten minutes", "About fifteen minutes", "Under thirty seconds", "About three minutes"],
        explanation: "The Tokaido Shinkansen has maintained an average delay well under one minute for many years.",
      },
      lt: {
        question: "Japonijos Shinkansen garsus punktualumu: koks apytikslis vidutinis metinis vėlavimas?",
        correct: "Mažiau nei viena minutė",
        distractors: ["Apie penkias minutes", "Mažiau nei dešimt minučių", "Apie penkiolika minučių", "Mažiau nei 30 sekundžių", "Apie tris minutes"],
        explanation: "Tokaido Shinkansen daugelį metų išlaikė vidutinį vėlavimą gerokai mažesnį nei viena minutė.",
      },
    },
  },
  {
    id: "trn_tr_027",
    category: "transport",
    subTheme: "trains",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Orient Express run by Compagnie Internationale des Wagons-Lits, founded 1872 by Georges Nagelmackers — Wikipedia",
    emoji: "🎫",
    translations: {
      en: {
        question: "The Orient Express was operated by a company founded by which Belgian entrepreneur?",
        correct: "Georges Nagelmackers",
        distractors: ["George Mortimer Pullman", "Henri Nestlé", "Alfred Krupp von Bohlen", "Werner von Siemens", "Karl Friedrich Benz"],
        explanation: "Nagelmackers founded Compagnie Internationale des Wagons-Lits in 1872 after seeing Pullman's US sleepers.",
      },
      lt: {
        question: "Orient Express valdė kompanija, kurią įkūrė kuris belgų verslininkas?",
        correct: "Georges Nagelmackers",
        distractors: ["George Mortimer Pullman", "Henri Nestlé", "Alfred Krupp von Bohlen", "Werner von Siemens", "Karl Friedrich Benz"],
        explanation: "Nagelmackers, įkvėptas Pullmano JAV miegamųjų vagonų, 1872 m. įkūrė Compagnie Internationale des Wagons-Lits.",
      },
    },
  },
  {
    id: "trn_tr_028",
    category: "transport",
    subTheme: "trains",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "London Underground first section used steam locomotives — History of the London Underground, Wikipedia",
    emoji: "🚇",
    translations: {
      en: {
        question: "When the London Underground opened in 1863, what powered its trains?",
        correct: "Steam locomotives",
        distractors: ["Electric motors", "Diesel engines", "Horse traction", "Cable haulage", "Gas turbines"],
        explanation: "Early Underground trains were steam-hauled; passengers endured smoky, sulphurous tunnels.",
      },
      lt: {
        question: "Kuo buvo varomi Londono metro traukiniai, kai 1863 m. jis atidarytas?",
        correct: "Garo garvežiais",
        distractors: ["Elektros varikliais", "Dyzeliniais varikliais", "Arkliais", "Lynų sistema", "Dujų turbinomis"],
        explanation: "Ankstyvieji metro traukiniai buvo gariniai; keleiviai kentėdavo dūmais ir siera prisotintuose tuneliuose.",
      },
    },
  },
  {
    id: "trn_tr_029",
    category: "transport",
    subTheme: "trains",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Japan L0 Series maglev Guinness record 603 km/h set 21 April 2015 on Yamanashi Maglev Line — Guinness World Records",
    emoji: "🚄",
    translations: {
      en: {
        question: "Japan's L0 Series maglev set a Guinness speed record of 603 km/h in which year?",
        correct: "2015",
        distractors: ["2003", "2007", "2011", "2019", "2022"],
        explanation: "The record was set on 21 April 2015 on the Yamanashi test line in Japan.",
      },
      lt: {
        question: "Kuriais metais Japonijos L0 Series maglev pasiekė Guinness greičio rekordą — 603 km/h?",
        correct: "2015",
        distractors: ["2003", "2007", "2011", "2019", "2022"],
        explanation: "Rekordas nustatytas 2015 m. balandžio 21 d. Japonijos Yamanashi bandomojoje linijoje.",
      },
    },
  },
  {
    id: "trn_tr_030",
    category: "transport",
    subTheme: "trains",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Channel Tunnel longest undersea section 37.9 km — Eurotunnel LeShuttle / Britannica",
    emoji: "🎫",
    translations: {
      en: {
        question: "Of the Channel Tunnel's total 50.45 km length, how much runs under the sea?",
        correct: "About 38 km",
        distractors: ["About 20 km", "About 50 km", "About 10 km", "About 30 km", "About 45 km"],
        explanation: "The undersea section is 37.9 km, making it the world's longest undersea rail tunnel.",
      },
      lt: {
        question: "Kiek iš visų 50,45 km Lamanšo tunelio driekiasi po jūra?",
        correct: "Apie 38 km",
        distractors: ["Apie 20 km", "Apie 50 km", "Apie 10 km", "Apie 30 km", "Apie 45 km"],
        explanation: "Povandeninis ruožas yra 37,9 km, todėl tai ilgiausias pasaulyje povandeninis geležinkelio tunelis.",
      },
    },
  },

  // ===================== EKSTREMALUS (srities žinovas) =====================
  {
    id: "trn_tr_031",
    category: "transport",
    subTheme: "trains",
    level: "ekstremalus",
    isTrap: true,
    sourceVerified: "Stephenson's Rocket was built by Robert Stephenson, not solely George — Science Museum Group",
    emoji: "🚂",
    translations: {
      en: {
        question: "Stephenson's Rocket is often called George's work, but who was the lead engineer who built it?",
        correct: "Robert Stephenson",
        distractors: ["George Stephenson", "Richard Trevithick", "John Blenkinsop", "Timothy Hackworth", "Matthew Murray"],
        explanation: "Rocket was designed and built by Robert Stephenson at his Newcastle works, with his father's guidance.",
      },
      lt: {
        question: "Rocket dažnai priskiriamas Džordžui, tačiau kas buvo pagrindinis inžinierius, jį pastatęs?",
        correct: "Robertas Stephensonas",
        distractors: ["Džordžas Stephensonas", "Richardas Trevithickas", "Johnas Blenkinsopas", "Timothy Hackworthas", "Matthew Murray"],
        explanation: "Rocket suprojektavo ir pastatė Robertas Stephensonas savo Niukaslio dirbtuvėse, padedamas tėvo.",
      },
    },
  },
  {
    id: "trn_tr_032",
    category: "transport",
    subTheme: "trains",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Abt rack system most widely used rack railway type — Wikipedia / Gaugemaster",
    emoji: "🛤️",
    translations: {
      en: {
        question: "Of all rack railway systems, which engineer's design became the most widely adopted worldwide?",
        correct: "Roman Abt",
        distractors: ["Niklaus Riggenbach", "Emil Strub", "Eduard Locher", "Sylvester Marsh", "Georg von Siemens"],
        explanation: "Swiss engineer Roman Abt devised parallel toothed plates that engage more smoothly and reliably.",
      },
      lt: {
        question: "Kurio inžinieriaus krumpliastiebio geležinkelio konstrukcija pasaulyje paplito labiausiai?",
        correct: "Romanas Abtas",
        distractors: ["Niklausas Riggenbachas", "Emilis Strubas", "Eduardas Locheris", "Sylvesteris Maršas", "Georgas von Siemensas"],
        explanation: "Šveicarų inžinierius Romanas Abtas sukūrė lygiagrečias dantytas plokšteles, kurios kimba sklandžiau ir patikimiau.",
      },
    },
  },
  {
    id: "trn_tr_033",
    category: "transport",
    subTheme: "trains",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Beijing Subway and Shanghai Metro consistently top annual ridership tables 2023-2024 — Wikipedia List of metro systems",
    emoji: "🚇",
    translations: {
      en: {
        question: "Which country is home to the world's busiest metro systems, such as Shanghai and Beijing?",
        correct: "China",
        distractors: ["Japan", "Russia", "USA", "India", "South Korea"],
        explanation: "Shanghai, Beijing and Guangzhou are the three busiest metros by annual ridership.",
      },
      lt: {
        question: "Kurioje šalyje veikia judriausios pasaulio metro sistemos, tarp jų Šanchajaus ir Pekino?",
        correct: "Kinija",
        distractors: ["Japonija", "Rusija", "JAV", "Indija", "Pietų Korėja"],
        explanation: "Šanchajaus, Pekino ir Guangžou metro yra trys judriausios pasaulyje pagal metinį keleivių srautą.",
      },
    },
  },
  {
    id: "trn_tr_034",
    category: "transport",
    subTheme: "trains",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Trans-Siberian Railway built 1890–1916 under Alexander III and Nicholas II — Britannica",
    emoji: "🛤️",
    translations: {
      en: {
        question: "Under which Russian tsar was construction of the Trans-Siberian Railway first ordered?",
        correct: "Alexander III",
        distractors: ["Nicholas II", "Nicholas I", "Alexander II", "Peter the Great", "Catherine the Great"],
        explanation: "Alexander III issued the imperial rescript in 1891; his son Nicholas II completed the line.",
      },
      lt: {
        question: "Kurio Rusijos caro įsakymu buvo pradėta tiesti Transsibirinė geležinkelio linija?",
        correct: "Aleksandro III",
        distractors: ["Nikolajaus II", "Nikolajaus I", "Aleksandro II", "Petro Didžiojo", "Kotrynos Didžiosios"],
        explanation: "Aleksandras III 1891 m. pasirašė imperatoriškąjį reskriptą; jo sūnus Nikolajus II liniją užbaigė.",
      },
    },
  },
  {
    id: "trn_tr_035",
    category: "transport",
    subTheme: "trains",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Hohensalzburg Fortress cable railway c.1495 — oldest preserved funicular — Hill Hiker / HowStuffWorks",
    emoji: "🚉",
    translations: {
      en: {
        question: "The oldest surviving funicular mechanism, dating to about 1495, is at which Austrian fortress?",
        correct: "Hohensalzburg",
        distractors: ["Schönbrunn", "Belvedere", "Burg Kreuzenstein", "Hardegg Castle", "Hochosterwitz"],
        explanation: "The cable system at Hohensalzburg Fortress in Salzburg dates back to around 1495.",
      },
      lt: {
        question: "Kurioje Austrijos pilyje yra seniausias išlikęs funikulieriaus mechanizmas (maždaug 1495 m.)?",
        correct: "Hohensalzburg",
        distractors: ["Schönbrunn", "Belvedere", "Burg Kreuzenstein", "Hardegg", "Hochosterwitz"],
        explanation: "Salzburgo Hohensalzburg pilyje esanti lynų sistema siekia maždaug 1495 metus.",
      },
    },
  },
  {
    id: "trn_tr_036",
    category: "transport",
    subTheme: "trains",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "TGV first service 1981 Paris–Lyon; project approved 1974 — SNCF / Electric Railway Society",
    emoji: "🚄",
    translations: {
      en: {
        question: "When did France's TGV enter regular passenger service for the first time?",
        correct: "1981",
        distractors: ["1976", "1990", "1994", "1970", "1985"],
        explanation: "The first TGV service ran on the Paris–Lyon line on 27 September 1981.",
      },
      lt: {
        question: "Kada Prancūzijos TGV pirmą kartą pradėjo reguliarų keleivių eismą?",
        correct: "1981",
        distractors: ["1976", "1990", "1994", "1970", "1985"],
        explanation: "Pirmasis TGV reisas Paryžiaus–Liono linijoje nuvažiavo 1981 m. rugsėjo 27 d.",
      },
    },
  },
  {
    id: "trn_tr_037",
    category: "transport",
    subTheme: "trains",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "William Huskisson killed at opening of Liverpool and Manchester Railway Sep 15 1830 — Britannica",
    emoji: "🚂",
    translations: {
      en: {
        question: "The 1830 opening of the Liverpool–Manchester Railway was marred when which official was fatally struck by a train?",
        correct: "William Huskisson",
        distractors: ["Robert Peel", "Arthur Wellesley", "George Canning", "Henry Brougham", "Lord Liverpool"],
        explanation: "Huskisson, an MP and former cabinet minister, was hit by Rocket while standing on the track.",
      },
      lt: {
        question: "1830 m. Liverpulio–Mančesterio geležinkelio atidarymo džiaugsmą aptemdė kurio pareigūno žūtis po traukinio ratais?",
        correct: "Williamas Huskissonas",
        distractors: ["Robertas Peel", "Arthuras Wellesley", "George Canning", "Henry Brougham", "Lord Liverpool"],
        explanation: "Huskissonas, parlamento narys ir buvęs ministras, buvo partrenktas Rocket stovėdamas ant bėgių.",
      },
    },
  },
  {
    id: "trn_tr_038",
    category: "transport",
    subTheme: "trains",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Eurostar max operating speed 300 km/h on HS lines; reduced to 160 km/h inside Channel Tunnel — Eurostar / everyrail.com",
    emoji: "🎫",
    translations: {
      en: {
        question: "At what speed does Eurostar travel inside the Channel Tunnel, slower than its line maximum?",
        correct: "160 km/h",
        distractors: ["300 km/h", "200 km/h", "250 km/h", "100 km/h", "220 km/h"],
        explanation: "Eurostar slows to 160 km/h inside the tunnel for safety, though it reaches 300 km/h on open HS lines.",
      },
      lt: {
        question: "Kokiu greičiu Eurostar važiuoja Lamanšo tuneliu, lėčiau nei jo didžiausias greitis linijoje?",
        correct: "160 km/h",
        distractors: ["300 km/h", "200 km/h", "250 km/h", "100 km/h", "220 km/h"],
        explanation: "Saugos sumetimais tuneliu Eurostar lėtina iki 160 km/h, nors atvirose greitose linijose siekia 300 km/h.",
      },
    },
  },
  {
    id: "trn_tr_039",
    category: "transport",
    subTheme: "trains",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Siemens Berlin electric railway 1879 ran at 150 V DC through the rails — Siemens AG",
    emoji: "🚉",
    translations: {
      en: {
        question: "Siemens's 1879 Berlin electric railway delivered electricity to the locomotive through what?",
        correct: "The running rails",
        distractors: ["Overhead wires", "A third rail", "Onboard batteries", "A live track centre bar", "Ground-level supply rail"],
        explanation: "150-volt DC current ran through the two running rails back to the locomotive — a risky early design.",
      },
      lt: {
        question: "Per ką Siemenso 1879 m. Berlyno elektrinis geležinkelis tiekė elektrą garvežiui?",
        correct: "Važiuojamuosius bėgius",
        distractors: ["Viršutinius laidus", "Trečią bėgį", "Borto akumuliatorius", "Centrinę srovės juostą", "Paviršinį tiekimo bėgį"],
        explanation: "150 voltų nuolatinė srovė tekėjo per abu važiuojamuosius bėgius atgal į garvežį — rizikingas ankstyvasis sprendimas.",
      },
    },
  },
  {
    id: "trn_tr_040",
    category: "transport",
    subTheme: "trains",
    level: "ekstremalus",
    isTrap: true,
    sourceVerified: "TGV record 574.8 km/h used modified TGV V150 with larger wheels and extra power cars — Wikipedia TGV world speed record",
    emoji: "🚄",
    translations: {
      en: {
        question: "The TGV's 574.8 km/h record was set by a modified test train — what key change boosted its speed?",
        correct: "Larger-diameter wheels",
        distractors: ["A rocket booster", "A new track design", "Lighter aluminium body", "Vacuum tubes", "Hydrogen fuel cells"],
        explanation: "The V150 used oversized wheels to spin each motor revolution into more forward distance, among other changes.",
      },
      lt: {
        question: "574,8 km/h rekordą pasiekė modifikuotas bandomasis TGV — koks pagrindinis pakeitimas padidino jo greitį?",
        correct: "Didesnio skersmens ratai",
        distractors: ["Raketinis stiprintuvas", "Nauja bėgių konstrukcija", "Lengvesnis aliuminio kėbulas", "Vakuuminiai vamzdžiai", "Vandenilio kuro elementai"],
        explanation: "Be kitų pakeitimų, V150 turėjo padidinto skersmens ratus, kad per vieną variklio apsisukimą nuvažiuotų didesnį atstumą.",
      },
    },
  },
];
