/**
 * transportShips — 🚢 „Laivai ir jūra" potemė (tema „Transportas").
 *
 * MAŽAS FAILAS pagal potemę. 40 klausimų (10/lygiui). Laivų ir jūrų
 * navigacijos ISTORIJOS ir MOKSLO faktai: plūdurumas, Titanikas, buriniai
 * laivai, šviesos namai, Plimsoll linija, mazgai, submarinos, kanalai ir kt.
 * Tik patikrinti istoriniai/moksliniai faktai — JOKIŲ dabartinių čempionų.
 *
 * TAISYKLĖS: 1 teisingas + 5 distraktoriai; ≤46 simb.; teisingas NE ilgiausias >+5;
 * LT be vidinių kabučių; jokio atsakymo klausime; EMOJI NEUTRALUS (neišduoda atsakymo).
 */

import { TriviaQuestion } from "./triviaTypes";

export const TRANSPORT_SHIPS: TriviaQuestion[] = [
  // ===================== LENGVAS (9–12 m. vaikas) =====================
  {
    id: "trn_sh_001",
    category: "transport",
    subTheme: "ships",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Archimedes principle — ships float because displaced water weight equals ship weight; basic physics",
    emoji: "🌊",
    translations: {
      en: {
        question: "Why does a heavy steel ship float on water?",
        correct: "It displaces its own weight in water",
        distractors: [
          "Steel is naturally lighter than water",
          "Engines push it upward constantly",
          "Salt water holds up any solid",
          "Its hull is filled with helium",
          "The hull magnetically repels water",
        ],
        explanation: "A ship's hollow shape pushes aside (displaces) water that weighs as much as the ship, so it floats.",
      },
      lt: {
        question: "Kodėl sunkus plieninis laivas plaukia vandeniu?",
        correct: "Jis išstumia savo svoriui lygų vandenį",
        distractors: [
          "Plienas iš prigimties lengvesnis",
          "Varikliai nuolat stumia jį aukštyn",
          "Sūrus vanduo laiko bet ką",
          "Korpusas pripildytas helio dujų",
          "Korpusas magnetiškai atstumia vandenį",
        ],
        explanation: "Tuščiaviduris korpuso pavidalas išstumia vandenį, kuris sveria tiek, kiek laivas — todėl jis plaukia.",
      },
    },
  },
  {
    id: "trn_sh_002",
    category: "transport",
    subTheme: "ships",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Ship terminology — bow is the front, stern is the rear; universal maritime standard",
    emoji: "⚓",
    translations: {
      en: {
        question: "What is the front end of a ship called?",
        correct: "The bow",
        distractors: [
          "The stern",
          "The port",
          "The keel",
          "The helm",
          "The deck",
        ],
        explanation: "The front of a ship is the bow; the back is the stern.",
      },
      lt: {
        question: "Kaip vadinamas laivo priekis?",
        correct: "Laivapriekis (bow)",
        distractors: [
          "Laivagalis (stern)",
          "Prieplauka",
          "Kilis",
          "Vairas",
          "Denis",
        ],
        explanation: "Laivo priekis vadinamas laivapriekiu, o galas — laivagaliu.",
      },
    },
  },
  {
    id: "trn_sh_003",
    category: "transport",
    subTheme: "ships",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Viking longship — used both oars and a square sail; World History Encyclopedia",
    emoji: "🧭",
    translations: {
      en: {
        question: "How did Vikings power their longships when there was no wind?",
        correct: "By rowing with oars",
        distractors: [
          "By using a steam engine",
          "By towing with ropes from shore",
          "By a waterwheel",
          "By paddling with hands",
          "By a propeller",
        ],
        explanation: "Viking longships had both a big square sail and rows of oars, so sailors could row when winds dropped.",
      },
      lt: {
        question: "Kaip vikingai varydavo ilguosius laivus, kai nebūdavo vėjo?",
        correct: "Irkluodami irklais",
        distractors: [
          "Garo varikliu",
          "Vilkdami virvėmis nuo kranto",
          "Vandens ratu",
          "Irkluodami rankomis",
          "Sraigtu",
        ],
        explanation: "Vikingų ilgieji laivai turėjo ir didelę keturkampę burę, ir irklų eiles, todėl per štilį jūreiviai galėjo irkluoti.",
      },
    },
  },
  {
    id: "trn_sh_004",
    category: "transport",
    subTheme: "ships",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Lighthouse — warns ships of rocks and coastlines; general maritime knowledge",
    emoji: "🗺️",
    translations: {
      en: {
        question: "What is the main job of a lighthouse?",
        correct: "Warn ships of danger near the coast",
        distractors: [
          "Guide aeroplanes to land safely",
          "Measure wind and wave speeds",
          "Store emergency fuel for ships",
          "Send radio signals to ports",
          "House and shelter harbour staff",
        ],
        explanation: "Lighthouses shine a bright light to warn sailors of rocks, reefs, and dangerous coastlines.",
      },
      lt: {
        question: "Kuo svarbiausia švyturio paskirtis?",
        correct: "Įspėti laivus apie pavojų prie kranto",
        distractors: [
          "Nukreipti lėktuvus saugiai tūpti",
          "Matuoti vėjo ir bangų greitį",
          "Laikyti avarinį kurą laivams",
          "Siųsti radijo signalus į uostus",
          "Apgyvendinti ir priglausti uosto darbuotojus",
        ],
        explanation: "Švyturiai šviečia ryškia šviesa ir perspėja jūrininkus apie uolas, rifus bei pavojingas pakrantes.",
      },
    },
  },
  {
    id: "trn_sh_005",
    category: "transport",
    subTheme: "ships",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Port and starboard — port = left, starboard = right; NOAA Ocean Service",
    emoji: "🚢",
    translations: {
      en: {
        question: "When you face forward on a ship, which side is port?",
        correct: "The left side",
        distractors: [
          "The right side",
          "The back side",
          "The front side",
          "The top side",
          "The bottom side",
        ],
        explanation: "Port is always the left side of the ship when facing the bow; starboard is the right.",
      },
      lt: {
        question: "Kai žvelgi į laivo priekį, kuri pusė yra kairė (port)?",
        correct: "Kairė pusė",
        distractors: [
          "Dešinė pusė",
          "Galinė pusė",
          "Priekinė pusė",
          "Viršutinė pusė",
          "Apatinė pusė",
        ],
        explanation: "Port visada yra kairė laivo pusė, kai žiūri į priekį; starboard — dešinė.",
      },
    },
  },
  {
    id: "trn_sh_006",
    category: "transport",
    subTheme: "ships",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Titanic sank on its maiden voyage April 1912; Britannica / Royal Museums Greenwich",
    emoji: "🌊",
    translations: {
      en: {
        question: "On which voyage did the Titanic sink in 1912?",
        correct: "Its first (maiden) voyage",
        distractors: [
          "Its tenth voyage",
          "Its hundredth voyage",
          "Its final scheduled voyage",
          "A test voyage in harbour",
          "A rescue voyage",
        ],
        explanation: "The Titanic hit an iceberg and sank during its very first Atlantic crossing in April 1912.",
      },
      lt: {
        question: "Kurio plaukimo metu 1912 m. nuskendo Titanikas?",
        correct: "Pirmojo (krikštynų) plaukimo",
        distractors: [
          "Dešimtojo reguliaraus plaukimo",
          "Šimtojo jubiliejinio plaukimo",
          "Paskutinio suplanuoto plaukimo",
          "Bandomojo plaukimo uoste",
          "Gelbėjimo operacijos plaukimo",
        ],
        explanation: "Titanikas atsitrenkė į ledkalnį ir nuskendo per pirmąjį savo Atlanto perplaukimą 1912 m. balandį.",
      },
    },
  },
  {
    id: "trn_sh_007",
    category: "transport",
    subTheme: "ships",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Anchor — holds ship in place by digging flukes into seabed; basic maritime knowledge",
    emoji: "⚓",
    translations: {
      en: {
        question: "What keeps an anchored ship from drifting away?",
        correct: "The anchor digs into the seabed",
        distractors: [
          "The engine runs in reverse",
          "A rope tied to the dock",
          "The rudder holds it still",
          "Special magnetic boots",
          "The crew holds ropes",
        ],
        explanation: "An anchor's curved flukes dig into the mud or sand on the seafloor and hold the ship steady.",
      },
      lt: {
        question: "Kas neleidžia inkare stovinčiam laivui nuplaukti?",
        correct: "Inkaras įsikimba į jūros dugną",
        distractors: [
          "Variklis dirba atbuline eiga",
          "Virvė, pririšta prie krantinės",
          "Vairas laiko jį vietoje",
          "Specialūs magnetiniai batai",
          "Įgula laiko virves",
        ],
        explanation: "Lenktos inkaro letenos įsikimba į jūros dugno dumblą ar smėlį ir laiko laivą vietoje.",
      },
    },
  },
  {
    id: "trn_sh_008",
    category: "transport",
    subTheme: "ships",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Submarine — travels underwater; general knowledge / Britannica",
    emoji: "🛟",
    translations: {
      en: {
        question: "What makes a submarine different from all other ships?",
        correct: "It can travel underwater",
        distractors: [
          "It can fly over water",
          "It runs without a crew",
          "It uses no fuel",
          "It is invisible to radar",
          "It can travel on land too",
        ],
        explanation: "A submarine dives below the surface by filling ballast tanks with water to make itself heavier.",
      },
      lt: {
        question: "Kuo povandeninis laivas skiriasi nuo visų kitų laivų?",
        correct: "Jis gali plaukti po vandeniu",
        distractors: [
          "Jis gali skristi virš vandens",
          "Jis plaukia be įgulos",
          "Jis nenaudoja kuro",
          "Jis nematomas radarui",
          "Jis gali važiuoti sausuma",
        ],
        explanation: "Povandeninis laivas neria pildydamas balasto cisternas vandeniu, kad taptų sunkesnis.",
      },
    },
  },
  {
    id: "trn_sh_009",
    category: "transport",
    subTheme: "ships",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Mayflower carried 102 passengers from England to America in 1620; History.com",
    emoji: "⛵",
    translations: {
      en: {
        question: "Which famous ship carried the Pilgrims to America in 1620?",
        correct: "The Mayflower",
        distractors: [
          "The Santa Maria",
          "The Endeavour",
          "The Victory",
          "The Niña",
          "The Beagle",
        ],
        explanation: "The Mayflower sailed 102 passengers from England to America in a 66-day voyage.",
      },
      lt: {
        question: "Kuris garsus laivas 1620 m. atvežė piligrimus į Ameriką?",
        correct: "Mayflower",
        distractors: [
          "Santa Maria",
          "Endeavour",
          "Victory",
          "Niña",
          "Beagle",
        ],
        explanation: "Mayflower per 66 dienų kelionę iš Anglijos į Ameriką atgabeno 102 keleivius.",
      },
    },
  },
  {
    id: "trn_sh_010",
    category: "transport",
    subTheme: "ships",
    level: "lengvas",
    isTrap: false,
    sourceVerified: "Suez Canal connects Mediterranean and Red Sea; opened 1869; Britannica",
    emoji: "🗺️",
    translations: {
      en: {
        question: "Which two seas does the Suez Canal connect?",
        correct: "The Mediterranean and Red seas",
        distractors: [
          "The Black and Caspian seas",
          "The Atlantic and Pacific",
          "The North and Baltic seas",
          "The Arabian and Coral seas",
          "The Arctic and Bering seas",
        ],
        explanation: "The Suez Canal, opened in 1869, cuts through Egypt to link the Mediterranean with the Red Sea.",
      },
      lt: {
        question: "Kurias dvi jūras jungia Sueco kanalas?",
        correct: "Viduržemio ir Raudonąją jūras",
        distractors: [
          "Juodąją ir Kaspijos jūras",
          "Atlantą ir Ramųjį vandenyną",
          "Šiaurės ir Baltijos jūras",
          "Arabijos ir Koralo jūras",
          "Arktinę ir Beringo jūras",
        ],
        explanation: "Sueco kanalas, atidarytas 1869 m., kerta Egiptą ir jungia Viduržemio jūrą su Raudonąja jūra.",
      },
    },
  },

  // ===================== VIDUTINIS (12–18 m. paauglys) =====================
  {
    id: "trn_sh_011",
    category: "transport",
    subTheme: "ships",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Starboard = right side from Old English steorbord (steer + board); NOAA Ocean Service",
    emoji: "🧭",
    translations: {
      en: {
        question: "The word starboard comes from Old English words meaning what?",
        correct: "Steer and side of a boat",
        distractors: [
          "Star and horizon board",
          "Storage and board",
          "Star and direction",
          "Step and border",
          "Stable and road",
        ],
        explanation: "Starboard is from stéor (steer) + bord (side of a ship) — the steering oar was on that side.",
      },
      lt: {
        question: "Ką reiškė senosios anglų kalbos žodžiai, iš kurių kilo starboard?",
        correct: "Vairą ir laivo šoną",
        distractors: [
          "Žvaigždę ir horizontą",
          "Sandėlį ir lentą",
          "Žvaigždę ir kryptį",
          "Žingsnį ir ribą",
          "Tvirtumą ir kelią",
        ],
        explanation: "Starboard kilo iš stéor (vairuoti) ir bord (laivo šonas) — vairas būdavo toje pusėje.",
      },
    },
  },
  {
    id: "trn_sh_012",
    category: "transport",
    subTheme: "ships",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Titanic had 20 lifeboats for 1178 people; ~2,200 on board; Britannica / Royal Museums Greenwich",
    emoji: "🛟",
    translations: {
      en: {
        question: "How many lifeboats did the Titanic have when it sank in 1912?",
        correct: "20",
        distractors: [
          "50",
          "100",
          "8",
          "35",
          "64",
        ],
        explanation: "Titanic had 20 lifeboats — enough for only 1,178 people out of about 2,200 on board.",
      },
      lt: {
        question: "Kiek gelbėjimo valčių turėjo Titanikas, kai nuskendo 1912 m.?",
        correct: "20",
        distractors: [
          "50",
          "100",
          "8",
          "35",
          "64",
        ],
        explanation: "Titanikas turėjo 20 gelbėjimo valčių — pakankamai tik 1 178 iš maždaug 2 200 žmonių.",
      },
    },
  },
  {
    id: "trn_sh_013",
    category: "transport",
    subTheme: "ships",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Knot = 1 nautical mile per hour = 1.852 km/h; international standard 1929",
    emoji: "⚓",
    translations: {
      en: {
        question: "In sea travel, one knot equals one nautical mile per what?",
        correct: "Hour",
        distractors: [
          "Minute",
          "Second",
          "Day",
          "Watch (4 hours)",
          "Tide cycle",
        ],
        explanation: "One knot is one nautical mile per hour, about 1.852 kilometres per hour.",
      },
      lt: {
        question: "Jūrų navigacijoje vienas mazgas yra viena jūrmylė per kurį laiko vienetą?",
        correct: "Valandą",
        distractors: [
          "Minutę",
          "Sekundę",
          "Dieną",
          "Vachtą (4 val.)",
          "Potvynio ciklą",
        ],
        explanation: "Vienas mazgas — tai viena jūrmylė per valandą, apie 1,852 km/val.",
      },
    },
  },
  {
    id: "trn_sh_014",
    category: "transport",
    subTheme: "ships",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Plimsoll line — load line on hull showing safe loading limit; Samuel Plimsoll 1876 Merchant Shipping Act; Royal Museums Greenwich",
    emoji: "🚢",
    translations: {
      en: {
        question: "What does the Plimsoll line marked on a ship's hull show?",
        correct: "The maximum safe loading level",
        distractors: [
          "The year the ship was built",
          "Where the anchor is stored",
          "The waterproof paint boundary",
          "The engine room location",
          "The captain's cabin level",
        ],
        explanation: "The Plimsoll line marks how deep a loaded ship can safely sit in the water.",
      },
      lt: {
        question: "Ką rodo Plimsoll linija ant laivo korpuso?",
        correct: "Didžiausią saugų pakrovimo lygį",
        distractors: [
          "Metus, kuriais laivas pastatytas",
          "Kur laikomas inkaras",
          "Vandeniui atsparių dažų ribą",
          "Variklių skyriaus vietą",
          "Kapitono kajutės aukštį",
        ],
        explanation: "Plimsoll linija rodo, kaip giliai pakrautas laivas gali saugiai grimzti vandenyje.",
      },
    },
  },
  {
    id: "trn_sh_015",
    category: "transport",
    subTheme: "ships",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Magnetic compass invented in China during Han dynasty; used in navigation by Song Dynasty (12th c.); spread to Europe via Arab merchants; World History Encyclopedia",
    emoji: "🧭",
    translations: {
      en: {
        question: "Where was the magnetic compass first invented for navigation?",
        correct: "China",
        distractors: [
          "Ancient Greece",
          "Arab lands",
          "Portugal",
          "Viking Scandinavia",
          "Ancient Egypt",
        ],
        explanation: "Chinese inventors first used a magnetic compass for navigation during the Song Dynasty around the 11th–12th century.",
      },
      lt: {
        question: "Kur pirmiausia buvo išrastas magnetinis kompasas navigacijai?",
        correct: "Kinijoje",
        distractors: [
          "Senovės Graikijoje",
          "Arabų šalyse",
          "Portugalijoje",
          "Vikingų Skandinavijoje",
          "Senovės Egipte",
        ],
        explanation: "Kinijos išradėjai pirmieji panaudojo magnetinį kompasą navigacijai Sungų dinastijos laikais XI–XII a.",
      },
    },
  },
  {
    id: "trn_sh_016",
    category: "transport",
    subTheme: "ships",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Santa Maria — Columbus flagship 1492; ran aground Christmas Day; was a nau/carrack; Britannica / Smithsonian",
    emoji: "⛵",
    translations: {
      en: {
        question: "Which ship was Christopher Columbus's flagship on his 1492 voyage?",
        correct: "The Santa Maria",
        distractors: [
          "The Niña",
          "The Pinta",
          "The Mayflower",
          "The Victoria",
          "The Beagle",
        ],
        explanation: "The Santa Maria was the largest of Columbus's three ships and ran aground on Christmas Day 1492.",
      },
      lt: {
        question: "Kuris laivas buvo Kristupo Kolumbo flagmanas 1492 m. kelionėje?",
        correct: "Santa Maria",
        distractors: [
          "Niña",
          "Pinta",
          "Mayflower",
          "Victoria",
          "Beagle",
        ],
        explanation: "Santa Maria buvo didžiausias iš trijų Kolumbo laivų ir užplaukė ant rifų 1492 m. Kalėdų dieną.",
      },
    },
  },
  {
    id: "trn_sh_017",
    category: "transport",
    subTheme: "ships",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Panama Canal uses locks to lift ships 26 m to Gatun Lake above sea level; Britannica / Panama Canal Authority",
    emoji: "🗺️",
    translations: {
      en: {
        question: "Why does the Panama Canal need locks, but the Suez Canal does not?",
        correct: "Ships must be raised above sea level",
        distractors: [
          "Panama has powerful tidal bores",
          "The Suez ships are far larger",
          "The Panama waterway flows backwards",
          "The Suez route crosses open desert",
          "Panama handles five times more traffic",
        ],
        explanation: "The Panama Canal lifts ships about 26 m up to Gatun Lake; the Suez is a sea-level cut that needs no locks.",
      },
      lt: {
        question: "Kodėl Panamos kanalui reikia šliuzų, o Sueco kanalui — ne?",
        correct: "Laivus reikia pakelti virš jūros lygio",
        distractors: [
          "Panamoje plūsta galingi potvynio antplūdžiai",
          "Sueco kanalo laivai gerokai didesni",
          "Panamos vandens kelias teka atgal",
          "Sueco kelias kerta atvirą dykumą",
          "Panamoje penkiskart didesnis eismas",
        ],
        explanation: "Panamos kanalas pakelia laivus apie 26 m iki Gatuno ežero; Sueco kanalas yra jūros lygio pjūvis be šliuzų.",
      },
    },
  },
  {
    id: "trn_sh_018",
    category: "transport",
    subTheme: "ships",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Viking longship shallow draft ~1 m allowed river navigation deep into Europe; World History Encyclopedia",
    emoji: "🧭",
    translations: {
      en: {
        question: "Why could Viking longships sail far up rivers into Europe?",
        correct: "Their very shallow hull needed little water",
        distractors: [
          "The hull could fold completely flat",
          "They used retractable wooden road wheels",
          "They skimmed over river shallows on air",
          "Oarsmen waded out in the river to push",
          "They carried inflatable outrigger floats",
        ],
        explanation: "A longship needed only about 1 metre of water, so it could sail up rivers no other ship could enter.",
      },
      lt: {
        question: "Kodėl vikingų ilgieji laivai galėjo plaukti giliai į Europos upes?",
        correct: "Jų sekli grimzlė reikalavo mažai vandens",
        distractors: [
          "Korpusą buvo galima sulankstyti plokščiai",
          "Jie turėjo įtraukiamus medinius ratus",
          "Jie skriedavo virš seklumų ant oro",
          "Irklininkai bridavo upe ir jį stumdavo",
          "Jie vežiojo pripučiamus šoninius plūdurus",
        ],
        explanation: "Ilgajam laivui užtekdavo vos apie 1 metro vandens, todėl jis įplaukdavo į upes, kurios kitiems laivams būdavo neįveikiamos.",
      },
    },
  },
  {
    id: "trn_sh_019",
    category: "transport",
    subTheme: "ships",
    level: "vidutinis",
    isTrap: true,
    sourceVerified: "Titanic 'unsinkable' myth — White Star Line promotional material used qualified language; the absolute claim grew after the sinking; Snopes / Wikipedia Legends",
    emoji: "🌊",
    translations: {
      en: {
        question: "Did White Star Line's original brochure call Titanic absolutely unsinkable?",
        correct: "No, it said designed to be unsinkable",
        distractors: [
          "Yes, it was guaranteed unsinkable",
          "Yes, certified unsinkable by the Navy",
          "Yes, scientifically proven unsinkable",
          "Yes, tested unsinkable for 10 years",
          "Yes, insured officially as unsinkable",
        ],
        explanation: "The brochure said the ships were designed to be unsinkable. The absolute claim spread only after she sank.",
      },
      lt: {
        question: "Ar originalus White Star Line prospektas vadino Titaniką absoliučiai nenuskandinamu?",
        correct: "Ne, jis teigė, kad suprojektuotas neskęsti",
        distractors: [
          "Taip, garantuotai nenuskandinamas",
          "Taip, karinio jūrų laivyno patvirtintas",
          "Taip, moksliškai įrodytas",
          "Taip, išbandytas 10 metų",
          "Taip, apdraustas kaip nenuskandinamas",
        ],
        explanation: "Prospekte buvo rašoma, kad laivai suprojektuoti neskęsti. Absoliutus teiginys paplito tik po katastrofos.",
      },
    },
  },
  {
    id: "trn_sh_020",
    category: "transport",
    subTheme: "ships",
    level: "vidutinis",
    isTrap: false,
    sourceVerified: "Caravel — developed in Portugal mid-15th century by Prince Henry the Navigator; lateen sails; World History Encyclopedia",
    emoji: "⛵",
    translations: {
      en: {
        question: "The caravel sailing ship was developed in which country in the 1400s?",
        correct: "Portugal",
        distractors: [
          "Spain",
          "England",
          "Venice",
          "Holland",
          "France",
        ],
        explanation: "Portuguese shipbuilders developed the caravel around 1450 to explore Africa's coast and beyond.",
      },
      lt: {
        question: "Kurioje šalyje XV a. buvo sukurtas karavelio burlaivis?",
        correct: "Portugalijoje",
        distractors: [
          "Ispanijoje",
          "Anglijoje",
          "Venecijoje",
          "Olandijoje",
          "Prancūzijoje",
        ],
        explanation: "Portugalijos laivų statytojai apie 1450 m. sukūrė karavelį Afrikos krantų ir tolesnių žemių tyrinėjimui.",
      },
    },
  },

  // ===================== SUNKUS (suaugęs, kuris domisi) =====================
  {
    id: "trn_sh_021",
    category: "transport",
    subTheme: "ships",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Plimsoll line — Merchant Shipping Act 1876 made it compulsory; Samuel Plimsoll known as Sailor's Friend; Historic UK / Lloyd's Register",
    emoji: "🚢",
    translations: {
      en: {
        question: "Samuel Plimsoll won the load-line law to protect which group of people?",
        correct: "Merchant sailors",
        distractors: [
          "Fishermen on lakes",
          "Ferry passengers",
          "Naval officers",
          "Lighthouse keepers",
          "Dock labourers",
        ],
        explanation: "Plimsoll campaigned to stop overloaded coffin ships sinking; the 1876 law made load lines compulsory.",
      },
      lt: {
        question: "Kuria žmonių grupe rūpinosi Plimsoll, iškovojęs grimzlės linijos įstatymą?",
        correct: "Prekybinių laivų jūrininkais",
        distractors: [
          "Žvejais ežeruose",
          "Keltų keleiviais",
          "Karinio jūrų laivyno karininkais",
          "Švyturių sargais",
          "Uosto darbininkais",
        ],
        explanation: "Plimsoll kovojo prieš perkrautus laivus žudikus; 1876 m. įstatymas grimzlės linijas padarė privalomas.",
      },
    },
  },
  {
    id: "trn_sh_022",
    category: "transport",
    subTheme: "ships",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Speed log — chip log with knotted rope and 28-second glass measured ship speed 17th century; Royal Museums Greenwich / HISTORY.com",
    emoji: "⚓",
    translations: {
      en: {
        question: "How did 17th-century sailors count a ship's speed in knots at sea?",
        correct: "They counted rope knots paid out in 28 seconds",
        distractors: [
          "They read a mechanical propeller dial",
          "They tracked star angles with a sextant",
          "They measured how far the coastline moved",
          "They timed how fast ocean waves passed",
          "They read a wooden water-wheel counter",
        ],
        explanation: "A knotted rope was paid out for 28 seconds; the number of knots that slipped through gave speed directly.",
      },
      lt: {
        question: "Kaip XVII a. jūrininkai jūroje skaičiuodavo laivo greitį mazgais?",
        correct: "Skaičiavo per 28 sek. išleistus virvės mazgus",
        distractors: [
          "Žiūrėjo į mechaninio sraigto rodyklę",
          "Stebėjo žvaigždžių kampus sekstantu",
          "Matavo, kaip tolsta pakrantės linija",
          "Matavo, kaip greitai praplaukia bangos",
          "Žiūrėjo į medinio vandens rato skaitiklį",
        ],
        explanation: "Mazguotą virvę leisdavo į vandenį 28 sekundes; pro rankas praslydusių mazgų skaičius iš karto rodė greitį.",
      },
    },
  },
  {
    id: "trn_sh_023",
    category: "transport",
    subTheme: "ships",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Lighthouse of Alexandria (Pharos) — built c. 280 BCE, one of Seven Wonders; World History Encyclopedia / Britannica",
    emoji: "🗺️",
    translations: {
      en: {
        question: "The ancient Pharos lighthouse was one of which famous list?",
        correct: "The Seven Wonders of the Ancient World",
        distractors: [
          "The Seven Great Seas of antiquity",
          "The Seven Sacred Harbours of Egypt",
          "The Seven UNESCO World Heritage Sites",
          "The Seven Historic Trade Routes",
          "The Seven Great Roman Bridges",
        ],
        explanation: "Built around 280 BCE on the island of Pharos in Alexandria, it stood over 100 m tall and lit ships safely into port.",
      },
      lt: {
        question: "Senasis Pharos švyturys priklausė kuriam garsiam sąrašui?",
        correct: "Septyniems senovės pasaulio stebuklams",
        distractors: [
          "Septynioms didžiosioms senovės jūroms",
          "Septyniems šventiems Egipto uostams",
          "Septyniems UNESCO paveldo objektams",
          "Septyniems istoriniams prekybos keliams",
          "Septyniems didžiuosiems romėnų tiltams",
        ],
        explanation: "Pastatytas apie 280 m. pr. Kr. Aleksandrijos Faro saloje, jis siekė per 100 m aukščio ir vedė laivus į uostą.",
      },
    },
  },
  {
    id: "trn_sh_024",
    category: "transport",
    subTheme: "ships",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "H.L. Hunley — first submarine to sink an enemy warship in combat, Feb 17 1864; Britannica / American Battlefield Trust",
    emoji: "🌊",
    translations: {
      en: {
        question: "The H.L. Hunley became historically notable as the first submarine to do what?",
        correct: "Sink an enemy warship in combat",
        distractors: [
          "Cross the Atlantic Ocean",
          "Carry passengers underwater",
          "Use a diesel engine",
          "Dive deeper than 100 m",
          "Fire a torpedo from a tube",
        ],
        explanation: "On 17 February 1864 the Hunley sank the USS Housatonic — the first successful combat submarine attack in history.",
      },
      lt: {
        question: "Kuo istoriniu atžvilgiu tapo garsus povandeninis laivas H.L. Hunley?",
        correct: "Pirmasis nuskandino priešo karo laivą",
        distractors: [
          "Pirmasis perplaukė Atlantą po vandeniu",
          "Pirmasis vežė keleivius po vandeniu",
          "Pirmasis povandeninis su dyzeliniu varikliu",
          "Paniro giliau nei 100 metrų",
          "Pirmasis iššovė torpedą iš vamzdžio",
        ],
        explanation: "1864 m. vasario 17 d. Hunley nuskandino USS Housatonic — tai buvo pirmoji sėkminga kovinė povandeninio laivo ataka istorijoje.",
      },
    },
  },
  {
    id: "trn_sh_025",
    category: "transport",
    subTheme: "ships",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Galleon — 16th-17th century ship; backbone of Spanish Armada 1588; 3-4 masts, square and lateen rigged; Britannica / World History Encyclopedia",
    emoji: "⛵",
    translations: {
      en: {
        question: "The galleon warship was the main fighting vessel of which famous 1588 fleet?",
        correct: "The Spanish Armada",
        distractors: [
          "The Ottoman galley fleet",
          "The Genoese galley fleet",
          "The Dutch East India fleet",
          "The French Armée navale",
          "The Venetian fleet",
        ],
        explanation: "Philip II of Spain sent an Armada of galleons against England in 1588; it was repelled partly by weather.",
      },
      lt: {
        question: "Galeonas buvo pagrindinis karo laivas kurioje garsioje 1588 m. flotilėje?",
        correct: "Ispanų Armadoje",
        distractors: [
          "Osmanų galerų laivyne",
          "Genujiečių galerų laivyne",
          "Olandų Rytų Indijos laivyne",
          "Prancūzų Armée navale",
          "Venecijos laivyne",
        ],
        explanation: "Ispanijos Filipas II 1588 m. prieš Angliją pasiuntė galeonų Armadą; ją iš dalies atmušė ir oro sąlygos.",
      },
    },
  },
  {
    id: "trn_sh_026",
    category: "transport",
    subTheme: "ships",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Suez Canal — no locks, sea-level cut, opened 17 November 1869; Britannica / Suez Canal Authority",
    emoji: "🗺️",
    translations: {
      en: {
        question: "Why does the Suez Canal need no locks to raise ships?",
        correct: "Both seas sit at the same sea level",
        distractors: [
          "Powerful underwater pumps lift ships",
          "Tidal surges push all ships through",
          "The canal surface slopes gently down",
          "There is absolutely no current there",
          "Ships use full engine power only",
        ],
        explanation: "Both seas sit at nearly the same sea level, so ships sail through without being lifted or lowered.",
      },
      lt: {
        question: "Kodėl Sueco kanalui nereikia šliuzų laivams kelti?",
        correct: "Abi jūros yra tame pačiame jūros lygyje",
        distractors: [
          "Galingi povandeniniai siurbliai kelia laivus",
          "Potvynio bangos stumia laivus pro kanalą",
          "Kanalo paviršius nuolaidžiai leidžiasi",
          "Ten visiškai nėra jokios srovės",
          "Laivai plaukia tik visa variklių galia",
        ],
        explanation: "Abi jūros yra beveik tame pačiame jūros lygyje, todėl laivai plaukia nekildami ir nenusileisdami.",
      },
    },
  },
  {
    id: "trn_sh_027",
    category: "transport",
    subTheme: "ships",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Viking longship clinker-built — overlapping planks riveted together; lighter and flexible; collectorhow.blog / World History Encyclopedia",
    emoji: "🧭",
    translations: {
      en: {
        question: "Viking longships used clinker construction — what does this mean?",
        correct: "Hull planks overlapped and were riveted",
        distractors: [
          "The entire hull was cast from iron",
          "Planks met edge to edge with no overlap",
          "The ship's keel was always fitted last",
          "Planks were sealed and glued with pine tar",
          "The ship had no internal wooden frame",
        ],
        explanation: "Overlapping (lapstrake) planks riveted together made the hull lighter, flexible, and strong enough for open seas.",
      },
      lt: {
        question: "Vikingų ilgieji laivai buvo statomi klinkeriniu būdu — ką tai reiškia?",
        correct: "Lentos persidengdavo ir būdavo sukniedijamos",
        distractors: [
          "Visas korpusas būdavo liejamas iš geležies",
          "Lentos jungtos briaunomis, be persidengimo",
          "Laivo kilis visada įstatomas paskutinis",
          "Lentos būdavo sandarinamos pušų derva",
          "Laivas neturėdavo vidinio medinio karkaso",
        ],
        explanation: "Persidengusios sukniedytos lentos suteikdavo korpusui lengvumą, lankstumą ir pakankamą tvirtumą atvirai jūrai.",
      },
    },
  },
  {
    id: "trn_sh_028",
    category: "transport",
    subTheme: "ships",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Titanic length 882 ft 9 in (269 m); 2nd of 3 Olympic-class ships; Britannica",
    emoji: "🚢",
    translations: {
      en: {
        question: "Roughly how long was the Titanic from bow to stern?",
        correct: "About 269 metres (882 feet)",
        distractors: [
          "About 100 metres (330 feet)",
          "About 500 metres (1 640 feet)",
          "About 150 metres (490 feet)",
          "About 400 metres (1 310 feet)",
          "About 50 metres (165 feet)",
        ],
        explanation: "At 269 m, the Titanic was one of the largest ships ever built when it launched in 1912.",
      },
      lt: {
        question: "Maždaug koks buvo Titaniko ilgis nuo laivapriekio iki laivagalio?",
        correct: "Apie 269 metrus (882 pėdos)",
        distractors: [
          "Apie 100 metrų (330 pėdų)",
          "Apie 500 metrų (1 640 pėdų)",
          "Apie 150 metrų (490 pėdų)",
          "Apie 400 metrų (1 310 pėdų)",
          "Apie 50 metrų (165 pėdos)",
        ],
        explanation: "269 m ilgio Titanikas buvo vienas didžiausių kada nors pastatytų laivų, kai 1912 m. buvo paleistas į vandenį.",
      },
    },
  },
  {
    id: "trn_sh_029",
    category: "transport",
    subTheme: "ships",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Caravel — lateen (triangular) sails allowed sailing closer to wind; aided Age of Exploration; World History Encyclopedia",
    emoji: "⛵",
    translations: {
      en: {
        question: "What type of sail gave the caravel its ability to sail against the wind?",
        correct: "Lateen (triangular) sails",
        distractors: [
          "Square sails on three masts",
          "Junk sails from China",
          "Bermuda mainsail",
          "Spinnaker balloon sails",
          "Lug sails on a gaff",
        ],
        explanation: "Triangular lateen sails let caravels sail much closer to the wind than any square-rigged ship could.",
      },
      lt: {
        question: "Kokio tipo burės leido karaveliui plaukti prieš vėją?",
        correct: "Lotyniškos (trikampės) burės",
        distractors: [
          "Keturkampės burės ant trijų stiebų",
          "Džonkų burės iš Kinijos",
          "Bermudų grotburė",
          "Baliono tipo spinakeriai",
          "Lyginės burės ant gaflio",
        ],
        explanation: "Trikampės lotyniškos burės leisdavo karaveliams plaukti gerokai arčiau vėjo nei bet kuris keturkampes bures turintis laivas.",
      },
    },
  },
  {
    id: "trn_sh_030",
    category: "transport",
    subTheme: "ships",
    level: "sunkus",
    isTrap: false,
    sourceVerified: "Anchor chain weight on seabed aids holding power; primary holding is chain + flukes digging in; Britannica / marineinsight",
    emoji: "⚓",
    translations: {
      en: {
        question: "What provides most of an anchor's holding power in calm conditions?",
        correct: "The chain weight lying on the seabed",
        distractors: [
          "The anchor's own weight alone",
          "Electric winches gripping the hull",
          "Magnets in the anchor head",
          "The rope tension from the ship",
          "Suction cups on the flukes",
        ],
        explanation: "A long chain on the seafloor keeps the pull horizontal, driving the flukes deeper rather than lifting them.",
      },
      lt: {
        question: "Kas suteikia inkaro laikymo galią ramiu oru?",
        correct: "Ant dugno gulinčios grandinės svoris",
        distractors: [
          "Vien tik paties inkaro svoris",
          "Elektrinės gervės, įsitvėrusios korpusą",
          "Inkaro galvutėje įtaisyti magnetai",
          "Virvės įtempimas nuo laivo",
          "Siurbtukai ant inkaro letenų",
        ],
        explanation: "Ilga grandinė ant jūros dugno laiko trauką horizontalią ir spaudžia letenas gilyn, o ne kelia jas aukštyn.",
      },
    },
  },

  // ===================== EKSTREMALUS (srities žinovas) =====================
  {
    id: "trn_sh_031",
    category: "transport",
    subTheme: "ships",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Pharos of Alexandria — the word 'pharos' became the word for lighthouse in many Romance languages (French phare, Italian faro, Spanish faro, Portuguese farol); World History Encyclopedia",
    emoji: "🗺️",
    translations: {
      en: {
        question: "The ancient Pharos lighthouse gave its name to the word for lighthouse in which language family?",
        correct: "Romance languages (French, Italian, Spanish)",
        distractors: [
          "The entire Germanic language family",
          "All Slavic languages spoken in Europe",
          "The Arabic language and its dialects only",
          "Ancient and modern Semitic language group",
          "All Nordic and Scandinavian languages",
        ],
        explanation: "Pharos (Φάρος) became phare (French), faro (Italian/Spanish), farol (Portuguese) — the standard word for lighthouse.",
      },
      lt: {
        question: "Kurios kalbų šeimos žodis švyturiui kilo iš senojo Pharos švyturio?",
        correct: "Romanų kalbose (prancūzų, italų, ispanų)",
        distractors: [
          "Visose germanų kalbose visoje Europoje",
          "Visose slavų kalbose šiuolaikinėje Europoje",
          "Tik arabų kalboje ir jos tarmėse",
          "Senovės ir šiuolaikinėse semitų kalbose",
          "Visose šiaurės ir skandinavų kalbose",
        ],
        explanation: "Pharos (Φάρος) virto phare (prancūzų), faro (italų/ispanų), farol (portugalų) — standartiniu žodžiu švyturiui.",
      },
    },
  },
  {
    id: "trn_sh_032",
    category: "transport",
    subTheme: "ships",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "MSC Irina (2023) ~24 346 TEU, ~400 m length — largest container ship class; gocomet.com / ship-technology.com 2024",
    emoji: "🚢",
    translations: {
      en: {
        question: "The largest container ships built around 2023 can carry roughly how many TEU boxes?",
        correct: "About 24 000",
        distractors: [
          "About 5 000",
          "About 50 000",
          "About 100 000",
          "About 1 000",
          "About 10 000",
        ],
        explanation: "Ultra-large container vessels like the MSC Irina class hold around 24,000 TEU — each TEU is one standard 20-foot container.",
      },
      lt: {
        question: "Didžiausi apie 2023 m. pastatyti konteinerių laivai gali vežti maždaug kiek TEU konteinerių?",
        correct: "Apie 24 000",
        distractors: [
          "Apie 5 000",
          "Apie 50 000",
          "Apie 100 000",
          "Apie 1 000",
          "Apie 10 000",
        ],
        explanation: "Itin dideli konteinerių laivai, kaip MSC Irina klasė, talpina apie 24 000 TEU — kiekvienas TEU yra vienas standartinis 20 pėdų konteineris.",
      },
    },
  },
  {
    id: "trn_sh_033",
    category: "transport",
    subTheme: "ships",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Santa Maria was a nau/carrack, NOT a caravel; Niña and Pinta were caravels; Britannica / Smithsonian",
    emoji: "⛵",
    translations: {
      en: {
        question: "Columbus's flagship Santa Maria was actually which ship type — not a caravel?",
        correct: "A nau (carrack)",
        distractors: [
          "A galleon",
          "A brigantine",
          "A cog",
          "A fluyt",
          "A xebec",
        ],
        explanation: "The Santa Maria was a heavier nau (carrack); only the Niña and Pinta were the lighter caravels.",
      },
      lt: {
        question: "Kolumbo flagmanas Santa Maria buvo kurio tipo laivas — ne karavelis?",
        correct: "Nao (karaka)",
        distractors: [
          "Galeonas",
          "Brigantinas",
          "Kogas",
          "Fleutas",
          "Žebeka",
        ],
        explanation: "Santa Maria buvo sunkesnis nao (karaka); tik Niña ir Pinta buvo lengvesni karaveliai.",
      },
    },
  },
  {
    id: "trn_sh_034",
    category: "transport",
    subTheme: "ships",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Plimsoll line — 1894 position of line fixed by law; 1876 Merchant Shipping Act made lines compulsory; Samuel Plimsoll nickname 'Sailor's Friend'; Royal Museums Greenwich",
    emoji: "🚢",
    translations: {
      en: {
        question: "What nickname was Samuel Plimsoll given for his campaign to protect sailors?",
        correct: "The Sailor's Friend",
        distractors: [
          "The Sea Captain",
          "The Iron Merchant",
          "The Harbour Master",
          "The Ocean Lawyer",
          "The Load Inspector",
        ],
        explanation: "Plimsoll was widely known as The Sailor's Friend for campaigning against overloaded, unsafe ships.",
      },
      lt: {
        question: "Kokią pravardę gavo Samuelis Plimsoll už kampaniją ginant jūrininkus?",
        correct: "Jūrininkų draugas",
        distractors: [
          "Jūrų kapitonas",
          "Geležies pirklys",
          "Uosto viršininkas",
          "Vandenyno advokatas",
          "Krovinio inspektorius",
        ],
        explanation: "Plimsoll buvo plačiai žinomas kaip Jūrininkų draugas dėl kovos prieš perkrautus nesaugius laivus.",
      },
    },
  },
  {
    id: "trn_sh_035",
    category: "transport",
    subTheme: "ships",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "International nautical mile standardised at 1852 m (6076 ft) in 1929; adopted by UK in 1970; Wikipedia Knot (unit)",
    emoji: "🧭",
    translations: {
      en: {
        question: "One nautical mile is defined as one minute of what on the Earth's surface?",
        correct: "Latitude",
        distractors: [
          "Longitude anywhere on Earth",
          "Meridian at the poles",
          "Great-circle arc in degrees",
          "Tidal arc at spring tide",
          "Magnetic declination",
        ],
        explanation: "One nautical mile equals one minute (1/60 of a degree) of latitude, making it 1,852 metres exactly.",
      },
      lt: {
        question: "Vienos kurios Žemės paviršiaus koordinatės minutė atitinka jūrmylę?",
        correct: "Platumos",
        distractors: [
          "Ilgumos bet kur Žemėje",
          "Meridiano prie polių",
          "Didžiojo apskritimo lanko laipsniais",
          "Potvynio lanko",
          "Magnetinio nuokrypio",
        ],
        explanation: "Viena jūrmylė lygi vienai platumos minutei (1/60 laipsnio) — tai tiksliai 1 852 metrai.",
      },
    },
  },
  {
    id: "trn_sh_036",
    category: "transport",
    subTheme: "ships",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Gatun Lake — created by Gatun Dam; ships lifted ~26 m (85 ft) above sea level; Panama Canal Authority / Britannica",
    emoji: "🗺️",
    translations: {
      en: {
        question: "Ships crossing the Panama Canal are raised how high above sea level at Gatun Lake?",
        correct: "About 26 metres (85 feet)",
        distractors: [
          "About 5 metres (16 feet)",
          "About 100 metres (328 feet)",
          "About 50 metres (164 feet)",
          "About 10 metres (33 feet)",
          "About 200 metres (656 feet)",
        ],
        explanation: "Three Gatun locks lift ships 26 m to the lake; three locks on the other side lower them back to sea level.",
      },
      lt: {
        question: "Kaip aukštai virš jūros lygio keliami laivai kertant Panamos kanalą Gatuno ežere?",
        correct: "Apie 26 metrus (85 pėdos)",
        distractors: [
          "Apie 5 metrus (16 pėdų)",
          "Apie 100 metrų (328 pėdų)",
          "Apie 50 metrų (164 pėdų)",
          "Apie 10 metrų (33 pėdų)",
          "Apie 200 metrų (656 pėdų)",
        ],
        explanation: "Trys Gatuno šliuzai kelia laivus 26 m iki ežero lygio; trys šliuzai kitoje pusėje grąžina juos į jūros lygį.",
      },
    },
  },
  {
    id: "trn_sh_037",
    category: "transport",
    subTheme: "ships",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "H.L. Hunley — 40 feet long, 8-man crank crew; sank three times during war killing 21 men including Hunley himself; Britannica / American Battlefield Trust",
    emoji: "🌊",
    translations: {
      en: {
        question: "How did the crew of the H.L. Hunley actually propel the submarine?",
        correct: "By hand-cranking a single screw",
        distractors: [
          "By a coal-fired steam engine",
          "By a battery-powered motor",
          "By foot pedals like a bicycle",
          "By compressed air jets",
          "By a clockwork spring motor",
        ],
        explanation: "Seven crewmen turned a hand crank that drove the propeller; one steered. It was exhausting and dangerous work.",
      },
      lt: {
        question: "Kaip H.L. Hunley įgula iš tikrųjų varydavo povandeninį laivą?",
        correct: "Rankomis sukama rankena, varančia sraigtą",
        distractors: [
          "Anglimis kūrenamu garo katilo varikliu",
          "Akumuliatoriniu elektros varikliu",
          "Pedalais, kaip dviratyje",
          "Suslėgto oro srovėmis",
          "Spyruokliniu laikrodžio mechanizmu",
        ],
        explanation: "Septyni įgulos nariai suko rankeną, varančią sraigtą, o vienas vairavo. Tai buvo varginantis ir pavojingas darbas.",
      },
    },
  },
  {
    id: "trn_sh_038",
    category: "transport",
    subTheme: "ships",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Titanic struck iceberg April 14 1912 at 23:40 ship's time; 5 of 16 watertight compartments breached; could survive 4; Britannica",
    emoji: "🛟",
    translations: {
      en: {
        question: "Titanic's design could survive flooding of 4 compartments — but the iceberg breached how many?",
        correct: "Five or more",
        distractors: [
          "Only one",
          "Exactly two",
          "Exactly three",
          "All sixteen",
          "Exactly four",
        ],
        explanation: "The Titanic was designed to stay afloat if up to 4 compartments flooded; the iceberg breached at least 5, dooming her.",
      },
      lt: {
        question: "Titaniko konstrukcija atlaikytų 4 užtvindytus skyrius — kiek jų pramušė ledkalnis?",
        correct: "Penkis ar daugiau",
        distractors: [
          "Tik vieną",
          "Lygiai du",
          "Lygiai tris",
          "Visus šešiolika",
          "Lygiai keturis",
        ],
        explanation: "Titanikas buvo suprojektuotas plaukti užtvindžius iki 4 skyrių; ledkalnis pramušė mažiausiai 5, ir tai jį pasmerkė.",
      },
    },
  },
  {
    id: "trn_sh_039",
    category: "transport",
    subTheme: "ships",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Mayflower 1620 — 102 passengers, 30 crew, 66-day voyage; ship ~80 ft long, 180-ton cargo capacity; History.com / Plimoth Patuxent",
    emoji: "⛵",
    translations: {
      en: {
        question: "The Mayflower's 1620 voyage of 2 750 miles took how many days?",
        correct: "66 days",
        distractors: [
          "14 days",
          "180 days",
          "30 days",
          "120 days",
          "7 days",
        ],
        explanation: "The Mayflower averaged roughly 2 mph across the Atlantic, taking 66 days to cover about 2,750 miles.",
      },
      lt: {
        question: "Kiek dienų truko 1620 m. Mayflower kelionė per 2 750 mylių?",
        correct: "66 dienas",
        distractors: [
          "14 dienų",
          "180 dienų",
          "30 dienų",
          "120 dienų",
          "7 dienas",
        ],
        explanation: "Mayflower plaukė vidutiniškai apie 2 mylias per valandą per Atlantą, nuplaukdamas apie 2 750 mylių per 66 dienas.",
      },
    },
  },
  {
    id: "trn_sh_040",
    category: "transport",
    subTheme: "ships",
    level: "ekstremalus",
    isTrap: false,
    sourceVerified: "Chip log knot interval ~47.25 ft chosen so 28-second glass gives speed directly in nautical miles per hour; HISTORY.com / NOAA",
    emoji: "🧭",
    translations: {
      en: {
        question: "Why were rope knots spaced exactly 47.25 feet apart on the old ship's log line?",
        correct: "28-second glass made knots read speed directly",
        distractors: [
          "It matched the length of one ship hull",
          "It was the length of one oar",
          "It matched the depth of the English Channel",
          "It was based on a sailor's arm span",
          "It equalled one fathom times three",
        ],
        explanation: "47.25 ft is the same fraction of a nautical mile as 28 seconds is of an hour, so knots counted = knots of speed.",
      },
      lt: {
        question: "Kodėl ant seno laivo lago virvės mazgai buvo kas lygiai 47,25 pėdos?",
        correct: "Kad 28 sek. laikrodis tiesiai rodytų greitį",
        distractors: [
          "Tai atitiko viso laivo korpuso ilgį metrais",
          "Tai buvo vieno irklo ilgis",
          "Tai atitiko Lamanšo gylį",
          "Tai rėmėsi jūrininko rankų išskėtimu",
          "Tai prilygo trims sieksniams",
        ],
        explanation: "47,25 pėdos sudaro tokią pat jūrmylės dalį, kokią 28 sekundės sudaro valandoje — todėl suskaičiuotų mazgų skaičius lygus greičiui mazgais.",
      },
    },
  },
];
